### ISSUE TITLE
Inline ```<code>``` element sanitized on purpose?

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1002]
Is the inline ```<code>``` element sanitized on purpose?

I was busy writing some documentation in tiny-mci and wanted to use Formats -> Inline -> Code, but in the publication itself it doesn't show because it is removed by zotonic's sanitizer.

Is this on purpose?

**Comment by mworrell** [comment]
I think it is just an oversight - just add it to the element whitelist.

**Comment by mmzeeman** [comment]
Ok, will do :+1:

**Comment by mworrell** [comment]
Maybe just add it to the z_stdlib whitelist.

**Comment by mmzeeman** [comment]
Done. see: https://github.com/zotonic/z_stdlib/commit/e570b5f6142a52a10760de2d08ff871cfe6e10f3
