### ISSUE TITLE
Pager uses wrong url

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1005]
Hi!

When you have a custom url and you include a pager in the template, the pager goes to the wrong url (the default url). We did not check the view page on multiple paths box, so the pager should use the custom url instead.

~ Dorien

**Comment by mworrell** [comment]
Can you explain what you mean with "custom URL"? Can you give a detailed example?

**Comment by DorienD** [comment]
I have to check the show page on mulitple paths box when i fill in the page path

![screen shot 2015-08-27 at 19 21 50](https://cloud.githubusercontent.com/assets/5102362/9527707/ec04fab8-4cf0-11e5-820b-297040165c3c.png)

**Comment by mworrell** [comment]
What are the URLs in the pager you get, what is the URL of the page, and do you have any dispatch rules for this page path?

**Comment by DorienD** [comment]
URL: /nl/page/3210?page=3#content-pager

We have no dispatch rule for that page.
