### ISSUE TITLE
Admin edit page: pressing Enter on title field deletes media connection

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1006]
Test case: a page with an attached medium:

* Reload the page, so that the focus is on the title field.
* Message appears that the medium "has been disconnected".

**Comment by mworrell** [comment]
The unlink action in the media items is (has become?) a button.
As this button is before the save button, it is selected as the default action.

We can do two things:

 * Change this button into an anchor
 * Add a (fake/hidden) save button at the top of the form for the default action

**Comment by ArthurClemens** [comment]
b3379ee69b2adccf15fa4ac4888d4fca77a9692d
