### ISSUE TITLE
Problem with starting Zotonic.

### ISSUE THREAD

**Issue by romul** [zotonic/zotonic#1008]
I've installed Zotonic from git and have tried release-0.13.x branch, 0.13.2 and 0.12.4 tags. In all cases I get the same error when trying to run `bin/zotonic start`:
` [error] Unable to read boot script (start_sasl.script): {error,enoent}`

This issue is also described in Zotonic user group:
https://groups.google.com/forum/#!topic/zotonic-users/G6STS18DE1E
https://groups.google.com/forum/#!topic/zotonic-users/00ZBFajOcYo

How could I fix it?

**Comment by ArthurClemens** [comment]
Which platform and which Erlang are you using?

**Comment by mworrell** [comment]
Actually I just saw the same error on my dev machine. But it didn't affect anything (as far as I can see).

My dev machine runs R16B03-1 on OS X

**Comment by romul** [comment]
@ArthurClemens I'm using Mac OS X 10.9 and Erlang 17.5

**Comment by romul** [comment]
@mworrell When I'm trying to add new site to zotonic it writes that "Zotonic is not started, check logs", and in the logs I see only this error about start_sasl.script.

**Comment by mworrell** [comment]
I think those the error and the connect problem are unrelated.

You can check with `epmd -names` which sites are running.

Erlang has some peculiarities about connecting to nodes, you need to use the correct short/long name.
On my dev machine I start Zotonic always in debug mode, and then use the Erlang command line.

**Comment by romul** [comment]
Ok, let's assume that this error doesn't matter and start from the beginning.
I do following:
*  `git pull origin master`
*  `git log | head -n 3`
```
commit 7181857a397c915ea749fcf83431360d120770ee
Author: Arthur Clemens <arthurclemens@gmail.com>
Date:   Sun Aug 30 22:50:28 2015 +0200
```
* `make`
* `bin/zotonic debug`
```
Erlang/OTP 17 [erts-6.4] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:true] [dtrace]

Eshell V6.4  (abort with ^G)
(zotonic001@MacBook-Pro-Apple)1> ** Found 0 name clashes in code paths 
11:00:46.280 [info] Application lager started on node 'zotonic001@MacBook-Pro-Apple'
Setup running ...
Directories verified. Res = {[ok],[]}
11:00:46.288 [info] Application setup started on node 'zotonic001@MacBook-Pro-Apple'
Setup finished processing hooks ...
11:00:46.288 [error] Unable to read boot script (start_sasl.script): {ok,[]}

11:00:46.313 [info] Starting reporters with []
11:00:46.313 [info] Application exometer_core started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.316 [info] Application exometer started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.317 [info] Application depcache started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.325 [info] Application mimetypes started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.363 [info] Application inets started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.378 [info] Application asn1 started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.378 [info] Application public_key started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.393 [info] Application ssl started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.397 [info] Application xmerl started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.397 [info] Application mochiweb started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.403 [info] Application sendfile started on node 'zotonic001@MacBook-Pro-Apple'
** Found 0 name clashes in code paths 
11:00:46.464 [info] Application webzmachine started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.464 [info] Application z_stdlib started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.466 [info] Application poolboy started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.476 [info] Application jobs started on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.492 [info] Application gproc started on node 'zotonic001@MacBook-Pro-Apple'
** Found 0 name clashes in code paths 
11:00:46.589 [info] starting emqtt on node 'zotonic001@MacBook-Pro-Apple'
11:00:46.600 [info] emqtt_auth is started
11:00:46.602 [info] emqtt_retained is started.
11:00:46.604 [info] emqtt_router is started.
11:00:46.605 [info] emqtt_registry is started.
11:00:46.607 [info] emqtt_client_monitor is started.
11:00:46.612 [info] emqtt broker is running now.
11:00:50.668 [info] 
11:00:50.668 [info] Zotonic started
11:00:50.668 [info] ===============
11:00:50.668 [info] Config files used:
11:00:50.668 [info] - /Users/roman/.zotonic/1.0/erlang.config
11:00:50.668 [info] - /Users/roman/.zotonic/1.0/zotonic.config
11:00:50.668 [info] 
11:00:50.668 [info] Web server listening on IPv4 any:8000
11:00:50.668 [info] Web server listening on IPv6 ::8000
11:00:50.668 [info] 
11:00:54.682 [warning] lager_error_logger_h dropped 1 messages in the last second that exceeded the limit of 50 messages/sec
11:00:54.682 [info] gen_smtp_server starting at 'zotonic001@MacBook-Pro-Apple'

11:00:54.687 [info] gen_smtp_server listening on {127,0,0,1}:2525 via tcp

11:00:54.770 [info] Site started: zotonic_status (<0.251.0>)
11:00:54.809 [info] [fswatch] Starting fswatch file monitor.
11:00:54.840 [info] Application zotonic started on node 'zotonic001@MacBook-Pro-Apple'
```
* `epmd -names`
```
epmd: up and running on port 4369 with data:
name zotonic001 at port 51446
```
* Open http://localhost:8000/. It works.
* `bin/zotonic addsite -s blog yoursite`
```
erl_call: can't ei_gethostbyname(MacBook-Pro-Apple)
Zotonic is not running. You need to start Zotonic first to use this command.
```

**Comment by mworrell** [comment]
Looks like a red herring - epmd shows that Zotonic is in fact running.  It is just the command line tools which can't reach it, and then conclude that it is not running.

I think that `zotonic001@MacBook-Pro-Apple` doesn't resolve well.

Is `MacBook-Pro-Apple` in your /etc/hosts file?

/cc @arjan (because he has been having "fun" with these node names)

**Comment by romul** [comment]
@mworrell  Wow, you have nailed it! Adding comp name to /etc/hosts helped.
Thank you very much. And please add this advice to `Adding your first site` section of docs. You will save a lot of time for many people ;-)

**Comment by mworrell** [comment]
Thanks!  Good to know that it helped, and indeed an important addition to the *first site* docs

**Comment by OlegUm** [comment]
I can not solve this problem by adding the name of my computer in the file /etc /hosts.

My  /etc /hosts: 
127.0.0.1	localhost
127.0.1.1	oleg-TP

...

oleg@oleg-TP:~/zotonic$ bin/zotonic debug
Erlang/OTP 18 [erts-7.1] [source-2882b0c] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:true]

Eshell V7.1  (abort with ^G)
(zotonic001@oleg-TP)1> ** Found 0 name clashes in code paths 
20:26:05.712 [info] Application lager started on node 'zotonic001@oleg-TP'
Setup running ...
Directories verified. Res = {[ok],[]}
20:26:05.722 [info] Application setup started on node 'zotonic001@oleg-TP'
Setup finished processing hooks ...
20:26:05.723 [error] Unable to read boot script (start_sasl.script): {error,enoent}
...

Does not work!

**Comment by ArthurClemens** [comment]
Why do you have

127.0.1.1

instead of 

127.0.0.1

?

**Comment by OlegUm** [comment]
It is, by definition, in ubuntu...
I tried to do it like this: 

```
127.0.0.1   localhost oleg-TP
...
```
No result.

**Comment by ArthurClemens** [comment]
It should be:

127.0.0.1   oleg-TP

**Comment by OlegUm** [comment]
```
#127.0.0.1	localhost
#127.0.1.1	oleg-TP
127.0.0.1	oleg-TP
```
No result.

**Comment by ArthurClemens** [comment]
Could you check http://www.leonardoborda.com/blog/127-0-1-1-ubuntu-debian/ , the part

> To see whether your system hostname can be resolved to an IP address with a fully qualified domain name, use the `hostname --fqdn` command.

**Comment by OlegUm** [comment]
```
oleg@oleg-TP:~/zotonic$ hostname  --fqdn
oleg-TP

```

**Comment by OlegUm** [comment]
Hi guys, how to solve the problem for ubuntu?

**Comment by mworrell** [comment]
What I usually do on my machine (OS X) is to add a compete host like `test.local` to my `/etc/hosts` file.

In the site config I then set the hostname to `test.local:8000`

Then I use this hostname for accessing the different vhosts.
For the Zotonic status panel I just go straight to `http://127.0.0.1:8000/`

I use a postfix `.local` as not all browsers turned out to be handling hostnames without a `.` well.

**Comment by mworrell** [comment]
BTW you can ignore the `Unable to read boot script (start_sasl.script): {error,enoent}` message.
