### ISSUE TITLE
Problem moving resources to other site. 

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1011]
mod_backup has an option where you can save a resource to disk to restore it. This was very handy also for moving content to another site. 

With the addition of content groups this functionality doesn't work anymore.

```erlang
z_db error {error,error,<<"23503">>,<<"insert or update on table \"rsc\" violates foreign key constraint \"fk_rsc_content_group_id\"">>,[{detail,<<"Key (content_group_id)=(5740) is not present in table \"rsc\".">>}]}
```

Before the update the content-group id should be checked and omitted if it doesn't exist.

**Comment by mworrell** [comment]
I think we should export the content-group using its name. If it doesn't exist on import then we can replace it with 'undefined'.
