### ISSUE TITLE
Site chooses wrong language for logged in user

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1012]
When you have a site with default language 'nl',
and a user with language setting 'en' 

and that user is logged in a 'nl' page is served instead of 'en' one which is the configured language for that user.

**Comment by mworrell** [comment]
It might also depend on the url, is there a language code in there?

**Comment by mmzeeman** [comment]
No, no language in the url

**Comment by mmzeeman** [comment]
I've made a fix on master, must be pushed to 0.13 and 0.12 when ok.

https://github.com/zotonic/zotonic/commit/f101a82f27fb8188bf7c3b6328a65103c66950fa

**Comment by mmzeeman** [comment]
Fixed
