### ISSUE TITLE
Remember state in category tree

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1014]
Hi!

The category page has really pretty dropdown thingies. And i think that one little tweak would make it even more awesome, that it remembers the state i was last at. So the that it remembers the fold outs :) 

~ Dorien

**Comment by mworrell** [comment]
Remembering state is not a little tweak ... it is quite some work and decisions.

For whom to remember?  (browser, user, group, everybody?)
Where to remember? (session, user, global?)
How long to remember?  (tab, session, forever?)
How to remember? (ids? data structure?)

**Comment by ArthurClemens** [comment]
Perhaps client side cookies are sufficient for this?

**Comment by mworrell** [comment]
Or use the persistent state? Both would be a per browser setting.

**Comment by mmzeeman** [comment]
If we want more state in the admin's ui it is probably best to re-implement them in our dynamic component system with mithril. It allows one to explicitly program ui state changes, and leaves open the option to use localstorage, cookies, or storage on the server.

**Comment by ArthurClemens** [comment]
I am all for Mithril, but that would be a rewrite.

**Comment by mmzeeman** [comment]
People expect more and more interactive components on a page, and sometimes even live collaboration between multiple people interacting with the resource. If you go that way you will probably have to review where state is changed, where state is stored, and how it is displayed.

**Comment by mworrell** [comment]
Closing this, having state for this UI component is something for when we upgrade the admin ui with Cotonic (or Elm, Mithril etc).

We are now showing the component in a "folded out" state, which solves quite some problems.
