### ISSUE TITLE
Add documentation for mod_component

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1015]
I would like to try out mod_component. Some more documentation would be welcome.

**Comment by mmzeeman** [comment]
Indeed, thanks for the reminder. I'll work on it on master. It needs examples too.

During writing of the documentation I will probably change things. I currently use it for channel.me's chat implementation and it has proven to be very stable.

It mainly is an on-demand-loader of js and css. This loader checks what js and css is already loaded in the page and computes the files which needs loading. I use it together with mithril. 

One improvement, on which I chatted about with @mworrell is that we want to change the template compiler in such a way that it can create mithril code which can be used in views. This would allow front-enders to more easily use it too. One other thing which I missed during implementation was a nice/easy way to implement state machines in javascript. 

Together with zotonic's pubsub it works like a charm. It is really stable and very nice to work with. (Short video is on this page: http://channel.me/live-chat)

**Comment by ArthurClemens** [comment]
I see 2 types of frontenders:

1. Those working with templates
2. Those working with JS-only Single Page Applications

Mithril's domain is clearly in the last category. Especially the users of Mithril are attracted to the low footprint and simple MVC structure.

Myself I am using Mithril extensively for SPAs, where I see Zotonic as data provider. My main concern is to reduce other JS dependencies (jQuery and such) to bring down page load times. Some work is https://github.com/ArthurClemens/Polythene, https://github.com/ArthurClemens/mithril-slider, https://github.com/ArthurClemens/mithril-page-slider and https://github.com/ArthurClemens/mithril-infinite.

Combining the capabilities would be interesting. For instance do a server request from the Mithril instance and receive ready to use data.

I noticed that the bundled Mithril is quite old. It should really be 0.2 to work with Mithril components.

**Comment by mmzeeman** [comment]
Note that receiving ready to use data is already possible with m.trust.See:  http://mithril.js.org/mithril.trust.html

SPA's are interesting because they move common server-side functionality to the client. The client has to route request, etc. Sometimes as a workaround for slow and dumb servers. But we have a fast and smart server so we need a little bit different solution. 

Currently I use mithril components mainly because I can program the client side state more easily. I implement this as state-machines on the client side which handles state transitions, implement a gui which renders the current client side state. Client side state changes occur because the component is hooked to topics. On the server side there are also state machines.

This works very well for interactive things. For us the downside is however that our front-end guy doesn't dare to touch javascript. I would like to give him the ability to easily write templates which contain the ui code, in plain html, needed to display the states the component can be in. This is possible.

**Comment by mworrell** [comment]
This was an internal note I made on how components and the template system can work together:

# Layouts, components and templates

Web Apps need to be able to dynamically change the page without changing the reloading the page.

This is a proposal for splitting the current template setup in different parts:

 * Base template
 * Layout
 * Components

The base template contains all basic parts of the page. Think of the HTML head, default JavaScript includes etc.

The layout contains the various blocks, columns etc. All the placeholder blocks are without content, or contain fixed content which can’t be replaced.

The components define the different components loaded into the layout’s placeholder blocks.

The combination of the above defines a page.

# Initial page load

The initial page is loaded like in the current situation. The top template with the components selects the layout and all components on the page. The layout defines the default base template, if not overruled.

The rendered page is returned to the browser for display.

# Loading a new page

In the browser all location changes are intercepted using the PushState API. The new URL is sent to the server for dispatch. The server returns the names of the new base, layout and components.

If the base changes then the browser is redirected to the new page.

If the layout changes then the browser stays on the page, rearranges the components in the new layout, and loads any missing components from the server.

If only components change then new components are loaded and old ones are either discarded or set to offscreen state. This state is useful for components that need to keep track of state for a possible later reinvocation, think of chat components.

# Components

Components are normal templates. They contain:

lib-tags for JavaScript and CSS includes
A block with HTML content
JavaScript template tag with JavaScript that needs to be executed on load
The browser will load all required new JavaScript and CSS files before inserting the HTML and executing the content load.

**Comment by mworrell** [comment]
Now on its own Wiki page https://github.com/zotonic/zotonic/wiki/Layouts,-components-and-templates

**Comment by mmzeeman** [comment]
:+1:

**Comment by mmzeeman** [comment]
I have created a simple example module for mod_component. It shows how to get a mithril component on your page.

https://github.com/mmzeeman/mod_component_example

**Comment by mworrell** [comment]
:+1:

**Comment by mworrell** [comment]
`mod_component` is deprecated and replaced with Cotonic.
