### ISSUE TITLE
Pot file generation requires strict handling of string concatenation

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1020]
Not sure if this is a bug or unwritten specification. 

When a `?__` call is concatenated with a string, it does not get added to the pot file:
```
?__("String test 1:", Context) ++ " " ++ Title
```

However this works:
```
[?__("String test 2:", Context), " " ++ Title]]
```

**Comment by ArthurClemens** [comment]
Documented.

**Comment by mworrell** [comment]
Please note that in the not-too-distant future we want to make all constants and strings binaries...
