### ISSUE TITLE
Determining if there are more pages for "load more.."

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1025]
If a search query returns exactly the number of items in a single page then the `moreresults` action is still shown (even if activating it won't show more results).

Original report:

We are trying to make a load more button with the zotonic {% button %}

{% button class="list__more" text="Load more..." action={moreresults result=result
                        target="list--content-group"
                        template="list/list-item.tpl"}
                        %}

I have a result with a pagelen of 6. So that would mean that if there are more than 6 results in the query the load more button should appear. I have tested it with three results, the first query had 2 results and the load more button did not appear, succes. The second query had  7 results and the load more button appeared, succes. The third result had 6 results and the load more button appeared, thats not supposed to happen since there are no results to load. 

Maybe there is a => 'pagelen' to show the button somewhere?

**Comment by mworrell** [comment]
Actually the load more doesn't know for sure if there aren't any more pages, it depends on the kind of query.  That is why it appears in this case.  The last result was a full page, so there might be a next page... changing this behaviour is quite a bit of work.

**Comment by mworrell** [comment]
Fixed using lookahead in (most) queries.
