### ISSUE TITLE
Deleting content groups does not work.

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1026]
Deleting content groups does not work. This problem is easy to reproduce:

1. Create a content group
2. Delete it through the Structure -> Content Groups screen
3. Look at the Content -> Pages screen to verify the group still exists.

After a while the content group will also reappear in the the content group hierarchy. You can force this to happen by executing the following expression at the shell:

````
m_hierarchy:ensure(content_group, z:c(yoursitename)).
````

On a related note, pages in the content group are still a member of the group. I would expect these to be set back to the default.

Deleting a group through the full edit screen does work, but the pages in the group will be orphans without a group instead of being put back into the default group. This might be intentional but I suggest this should be reflected in the sidebar. 

On a side note, it would be nice to have a way of migrating content to another group in batches.

**Comment by mworrell** [comment]
Moving this to 0.13.5.

It needs some good solution.

**Comment by mworrell** [comment]
This is fixed as part of #1041

See 6a06b0b
