### ISSUE TITLE
ACL user groups: default block for 'meta' categorie on anything by system groups

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1030]
I propose to add a default block to creation/editing/linking anything in the meta category.

This greatly reduces the number of access control rules when defining who can create what in which content group. This as the *all* category selection can be used, without accidentally allowing creation of new categories (etc) in non-system content groups.

Alternatively we could divide the whole category tree in two: system related categories and non-system categories.

/cc @arjan @fredpook @mmzeeman @ArthurClemens

**Comment by ArthurClemens** [comment]
How would this default block look like?

**Comment by mworrell** [comment]
I think of breaking the lookups if we arrive at category 'meta' and on a non-system content group.  Am looking into the lookup code.

This means that creating/editing/linking/deleting meta should be allowed explicitly, and that any wildcard for content-group or category wouldn't apply for these.

**Comment by mworrell** [comment]
Made some changes. 

Adding/editing/deleting/linking meta content is only allowed if one of these holds:

 * The ACL rule definition refers to the system content group
 * The ACL rule explicitly refers to the meta category or a sub-category of meta 

In all other "edit" rules the meta category is removed from the 'all' definition.
