### ISSUE TITLE
mod_acl_user_groups: add "view only" option

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1034]
The acl configuration is to difficult and sensitive to allow the client to edit it. Yet the client wants to view it to be able to communicate with the developers about it. Can a view only option be added?

**Comment by mworrell** [comment]
Proposal:

 * Assign access to the module for all people allowed to inspect the rules
 * Tie the edit permission to some other configuration, maybe insertion of user groups?

**Comment by mworrell** [comment]
Fixed.

If you are allowed to insert user groups *and* use the mod_acl_user_groups, then you can edit the ACL rules.

**Comment by fredpook** [comment]
#1199 fix seems to coflict with this restriction. Shall I open a new issue?

**Comment by mworrell** [comment]
The condition introduced in #1199 is about who can edit members of an user group.

The *who can edit memberships* is now:
 * link permission on the user group
 * view permission on the member
 * use permission on the `mod_acl_user_groups`

The checks for who can view the ACL rules is handled in the templates:

```
{% if m.acl.use.mod_acl_user_groups %}
```

What is wrong?

**Comment by fredpook** [comment]
both need use permission on the mod_acl_user_groups.
The usecase for most clients is 
- don't change the acl rules
- do change user permissions

**Comment by mworrell** [comment]
I don't think I understand the problem.

Both do indeed need the `use mod_acl_user_groups` permission.
To edit you need more permissions (different for rules and group memberships).

**Comment by fredpook** [comment]
What rights do I have to include/exclude so the administrator has only read access to the acl rule overview page
but is still able to change 1 person from user to editor group (for instance)

I have tried all possible combinatios.

**Comment by mworrell** [comment]
Don't give *create* permission on `acl_user_group` category.
But do give *link* permission.

**Comment by fredpook** [comment]
That's the first that i tried but the acl rule page is still editable.
![alc-usergroup](https://cloud.githubusercontent.com/assets/5276922/13987313/473551ca-f107-11e5-990d-64fae8b4ec62.png)

**Comment by mworrell** [comment]
It says literally in the template:

```
{% with m.acl.insert.acl_user_group as is_editable %}
```

So you must have insert permission on some content group for the category `acl_user_group`

**Comment by fredpook** [comment]
I found a workaround with a block rule
![alc-usergroup-block](https://cloud.githubusercontent.com/assets/5276922/13988148/f34a82c0-f10a-11e5-9d05-a7a68a37b7f8.png)
the rule in the screenshot above (which looks like the inverse of the block rule) has to be removed to make it work

**Comment by mworrell** [comment]
We have to check this a bit better, can you make a dump of your ACL rules and mail it?
(Especially the non-working set of rules)
