### ISSUE TITLE
Strange &#x0; when saving in rte (code)

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1035]
Hi!

We have encoutered a strange thing with the RTE. We have made a paragraph and added an image, when editing in the <> code editing and we click somewhere around the image tag (zotonic image tag) and then on ok we get this strange & #x0; in the code and we can't save it.

Attached the screenshot.
![screen shot 2015-09-16 at 09 58 42](https://cloud.githubusercontent.com/assets/5102362/9899406/db053aac-5c59-11e5-8b66-31e502f7b8f5.png)

**Comment by mworrell** [comment]
Is this consistent between browsers?
Is this `&#0;` already present in the HTML of tinymce?  
Or is it added in the code editor?

If it is added in the code editor then it is a problem in the code editor.
It if is already present after inserting the Zotonic img tag, then it might be a problem with the Zotonic img plugin.

**Comment by loetie** [comment]
Hi Marc,

- Browsers: Mac Firefox and Mac Chrome both have the same issue, we haven't tested it any further than that.
- It is added in the code editor when clicking on "OK" if your cursor is in the zotonic media tag. It is not already present when loading the code editor.

**Comment by mworrell** [comment]
Then it is an issue with the code editor, which is an upstream project.

I think it is this project https://github.com/tinymce-plugins/codemagic

@ArthurClemens is it indeed that plugin?

**Comment by mworrell** [comment]
Tagging this with *wontfix* as it is a minor issue and should be fixed upstream.

**Comment by ArthurClemens** [comment]
This is the codemirror plugin. Which version of tinymce are you using?

**Comment by mworrell** [comment]
@ArthurClemens I saw it with the newest version included in Zotonic.

**Comment by ArthurClemens** [comment]
The plugin is barely supported. I can remove the plugin and enable the default code editor, which is fairly bare, but probably sufficient to make some corrections. See the [tinymce demo](http://www.tinymce.com/tryit/full.php) (top bar right: Tools > Source code).

**Comment by ArthurClemens** [comment]
SHA: c0bc78f6bd434017b30db6c77d460c9f2fa93e53
