### ISSUE TITLE
erlang_localtime - use the origin repository

### ISSUE THREAD

**Issue by onnet** [zotonic/zotonic#1036]
Hi!

https://github.com/choptastic doesn't reflect recent changes.

Could we please change deps to elang_localtime's origin:

https://github.com/dmitryme/erlang_localtime

Regards,
Kirill

**Comment by mworrell** [comment]
We need to make some changes to our code then, as we use ``localtime:list_timezones()`` to fetch the list of supported timezones.  This function is not present in the original version.

**Comment by onnet** [comment]
@mworrell Many thanks for that, Marc!

**Comment by mworrell** [comment]
Changed this on master - needs some testing before merging into 0.13.x

**Comment by ddeboer** [comment]
Fixed on 0.x too.
