### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1037]
It would be handy to have bulk delete functionality from the admin interface.

**Comment by mworrell** [comment]
You mean a *delete* button and maybe a *check-all* and then a bulk action (like delete, unpublish, etc)

**Comment by arjan** [comment]
You mean like this? http://modules.zotonic.com/page/383/mod-bulk-commands

**Comment by mworrell** [comment]
Cool :)

We definitely need a way to explore the modules from the Zotonic modules interface ...

**Comment by mmzeeman** [comment]
Nice :-) :+1:

**Comment by ArthurClemens** [comment]
For Foswiki we had a mechanism to show the modules in the admin, with some basic info per module and the option to install, plus all dependencies.
