### ISSUE TITLE
Localized strings that are part of records do not end up in the pot file

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1040]
For instance `mod_admin.erl` the menu items (line 110 and below) are not copied to .pot:

```
#menu_item{id=admin_structure,
                label=?__("Structure", Context)},
```

But strings written like this are:

```
observe_admin_menu(admin_menu, Acc, Context) ->
	Test = ?__("Structure", Context),
```

Apparently records are not parsed well.

**Comment by mworrell** [comment]
Currently we parse the source code with the Erlang parser. The parse tree is then searched for any calls to the translation routines.

This fails if:

 * We don't have the right include paths
 * Complicated syntax constructs which the parse-tree-walker doesn't understand.

I think we might want to change this to a simpler approach: use a very simple parser to find any string within the `?__(…, …)` macro calls.

**Comment by ArthurClemens** [comment]
sha: fe7e4a73dfd3cd694a2ab853b1c8dee994addb60

**Comment by mworrell** [comment]
So it was something inside an expression.

It seems to me that this kind of string extraction might be a bit brittle, as I suspect there are more syntax constructions that might have been missed... maybe we should use a simplified parser that just tokenizes and looks for the macro?

**Comment by ArthurClemens** [comment]
I agree but this fix was the quickest solution.

**Comment by mworrell** [comment]
And a good fix :+1:
