### ISSUE TITLE
When category is deleted, page ends up without category and category cannot be set

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1041]
This is not the category Uncategorized, it is just nothing. ``category_id`` still has the value of the deleted category, but because the page does not exist, there is no title to display.

This leads to the situation that when the category popup is opened, the category cannot be set because the check ``m.acl.insert[r.category.name|as_atom]`` fails.

Either:

 1. Patching: The check on ``_admin_edit_header.tpl`` is loosened so that the user may set the category.
 1. Fixing the root cause: On deletion of the category, the affected pages get the category Uncategorized.

**Comment by mworrell** [comment]
In the database it is already set to `null` by a foreign key constraint.
The old content group I'd comes from the cached resources.

In my opinion we can do three possibilities:

 * refuse to delete a content group iff there are referring resources
 * invalidate all the cached resources (and hierarchy)
 * let the database track changed resource ids and store those in a queue for processing

The last option would work well if a resource has been changed by any query and decouple, which is nice. But this is also the most work.

Second option is the quickest and dirtiest, and only effective if content group deletion is a rare occurrence.

The first option is nice safe, it would also force the user to make a decision where to move the resources to. In this case I would change the foreign key constraint to restrict deletion iff any resource is still in the content group.

At the moment I think the first option has my preference.

**Comment by mworrell** [comment]
Oops, I read wrongly s/content-group/category/  Though the two problems are related.

See also #1026 

I think we can have a generic solution here.

**Comment by ArthurClemens** [comment]
Option 1 is acceptable if we offer bulk options so that all pages from the category can either be deleted or set to another category.

**Comment by mworrell** [comment]
Shall we set a fk constraint on the category and content-group or make this a software check?

We could add the "move all" to the *clog-menu* in the category/content-group hierarchy sorter.
This could add some background job, where we can show progress on the page.

**Comment by ArthurClemens** [comment]
I prefer a "fix this for me" solution from the user POV. A constraint will probably just give an error "you cannot delete this category" which is not very helpful.

Category deletion can happen:
1. From the category menu "remove"
1. From the edit page of a category

These pages are not set up to find all connected pages and change their category.

It may well be that these pages should get connected to a new to be defined category. Or that they should get deleted.

We can think of many ways to solve this elegantly, but I don't think that the issue is that major.

Easiest is to automatically change their category to "Uncategorized".

**Comment by mworrell** [comment]
If I remember correctly, right now we move the pages either one category 'up' or set them to the category 'uncategorized' (if we can't move them 'up').

We could add this as a job before the actual deletion.

Another thing we could do is add some eventual consistency when reading or pivoting a resource, setting the category_id and content_group_id to sensible values.
