### ISSUE TITLE
Wrong "wrong password" notification text on the login screen of zotonic status site.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1047]
![screenshot from 2015-10-01 15 00 09](https://cloud.githubusercontent.com/assets/1024972/10221192/40e88406-684d-11e5-86bd-c82f4b7ac473.png)

**Comment by ArthurClemens** [comment]
The wording has never changed since the beginning.

Because we are on the issue, should we provide a help text that the password can be found in the 
~/.zotonic/version/zotonic.config file?

**Comment by mmzeeman** [comment]
Indeed, that would be really helpful. :+1:

**Comment by ArthurClemens** [comment]
#3d3292fddf14a3195172c1eaecf82337157d380d

**Comment by mmzeeman** [comment]
Thanks. I was setting up a new dev environment yesterday and I bumped into this one. Didn't have the time to check it out right away.

**Comment by mworrell** [comment]
Misschien kunnen we die [version] nog ergens opvissen... ik ga zo even zoeken.

**Comment by mworrell** [comment]
En ook :+1: !
