### ISSUE TITLE
Strange year pprint

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1048]
Hi!

I have encountered a strange date situation. When i remove a date from date_end and i pprint this date i get this: {{9999,8,17},{12,0,0}}. When i check the date_end of that id with base export i see undefined. When i then pprint id_date_end|date:"Y" i get nothing. Really weird. This was all so i can make an if statement to check if date_end is filled or not. I fixed this now with:

{% if id.date_start|date:"Y" and id.date_end|date:"Y" %}

But i think the date_end should just be empty when its empty right?

~ Dorien

**Comment by mworrell** [comment]
That date is *St. Juttemis"

We use it to be able to query open ended date ranges.
Most Zotonic routines know this date and will suppress it in outputs.

So no, an empty end date is not empty :-)

**Comment by mworrell** [comment]
Made a change to `z_convert:to_bool/1` as it is indeed logical to see this as a *false* condition.

https://github.com/zotonic/z_stdlib/commit/8d2ca3c839662c37e5bedc7d7f98d86a9f08709f
