### ISSUE TITLE
Document 'catinclude' option for moreresults action.

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1053]
Hi!

We use the action 'moreresults' to paginate trough our results, but! It does not do a catinclude. To give it some more context:

I have a query page that shows all the events with the template list-item-vertical.event.tpl. Initially i show 6 results and the load more button (action moreresults). I click on the button and it loads 6 more results, but! It loads the list-item-vertical.tpl instead of the list-item-vertical.event.tpl. 

~ Dorien

**Comment by mworrell** [comment]
For now you can use one of two workarounds:

 * include a template that then does the catinclude
 * include a template for all ids, loop over them and use catinclude in the loop

**Comment by arjan** [comment]
actually, looking at the [source code](https://github.com/zotonic/zotonic/blob/master/modules/mod_base/actions/action_base_moreresults.erl#L98), the `moreresults` action *does* have a `catinclude` parameter, which does a catinclude when it is set to true.

**Comment by mworrell** [comment]
Cool! So it is only a documentation issue.  Changing the label.

**Comment by DorienD** [comment]
Nice! it words when i add catinclude as a parameter :)
