### ISSUE TITLE
Simplify the 'escape' filter semantics

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1054]
Currently the *escape* filter is always moved to the last position in the filter list, even when it is written earlier.

This leads to unexpected behavior  and complexity/ambiguity in the template compiler.

I propose to remove the special handling of the *escape* filter and just apply it where it is written. This makes the filter behave similar to the *force_escape* filter.

This is from the Django documentation at https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#escape:

> The escaping is only applied when the string is output, so it does not matter where in a chained sequence of filters you put escape: it will always be applied as though it were the last filter. If you want escaping to be applied immediately, use the force_escape filter.
> 
> Applying escape to a variable that would normally have auto-escaping applied to the result will only result in one round of escaping being done. So it is safe to use this function even in auto-escaping environments. If you want multiple escaping passes to be applied, use the force_escape filter.

/cc @mmzeeman @ArthurClemens @arjan @kaos

**Comment by ArthurClemens** [comment]
Agreed
