### ISSUE TITLE
z_html:strip creates spaces

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1057]
Test string:

```
z_html:strip(<<"<ul><li>This is a list item.</li></ul>">>).
```

results in:

```
<<"This is a list item. ">>
```

This is a bit unfortunate little bug, because I am doing a check on the work on translators to see if they have left any trailing spaces. Because of the bug I get notified on the trailing spaces while they do not exist in the original text.

**Comment by mmzeeman** [comment]
The ```z_html:strip/1``` does this: 

```erlang
strip(<<$>,T/binary>>, in_tag, Acc) ->
        strip(T, in_text, <<Acc/binary, 32>>);
```

So when a tag closes a space is inserted. It looks like this is there for a reason.

**Comment by mmzeeman** [comment]
There was no unit test which needed adding spaces. Fixed this via https://github.com/zotonic/z_stdlib/commit/62c103e26b35edde1c360644f977540dd236db37

You need to update z_stdlib to get the fix.

**Comment by mworrell** [comment]
The space is there because block level elements should separate visibly the inside those elements.

Maybe we could do a right-strip at the end of the conversion?

**Comment by ArthurClemens** [comment]
I am afraid that a right-strip will also strip the spaces by the translators, defeating my check.

**Comment by mworrell** [comment]
Then the stripper needs to be changed a bit, maybe returning parts of stripped text, then intersecting them with a space. That would prevent any additional spaces.  (Or some other algorithm)

**Comment by mmzeeman** [comment]
If that is the case maybe we should properly parse the html and insert spaces for block level elements.

**Comment by ArthurClemens** [comment]
The spaces are only needed in the middle of the string, not at the left or right side.

**Comment by mmzeeman** [comment]
If adding spaces depends on the semantics, then adding spaces should be done after parsing. Stripping is currently done by a simple state machine which doesn't know the difference between block and inline elements.

**Comment by mmzeeman** [comment]
For what it is worth. 

Django properly parses the html, but does not insert spaces for block level elements. They leave entity,- and char refs in place. 

We could use our html parser and insert spaces for close-block-level-tag-which-is-not-followed-by-whitespace. But that would automatically expand entity and charrefs.

**Comment by mworrell** [comment]
Problem is that we use strip in places that need a "quick" strip, so parsing is a bit much overhead. I think we can change the strip to not add a space at the end, and only one at a closing tag if that tag is not followed by a space or `</`.

**Comment by mworrell** [comment]
I added some alternative rules about when to insert a space or not.
All tests (and an additional one) are passing.

https://github.com/zotonic/z_stdlib/commit/a92065a85e26e6647e1e11a6ecf318166dc454e7

**Comment by ArthurClemens** [comment]
Thanks upfront. I will check the coming days.
