### ISSUE TITLE
Portrait photo gets to be landscape when uploaded

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1063]
Hi!

I have this picture that is shot with a advanced camera(spiegel relfex). When i add this picture to zotonic it gets uploaded in landscape mode (but the picture is shot in portrait mode). When i change the size in photoshop and upload it again it works, also if i just save the image in photoshop without changing anything it also uploads in the correct portrait mode. Really strange?

![p1030165](https://cloud.githubusercontent.com/assets/5102362/10662274/c54f1d74-78b3-11e5-9183-df5bfa5887e6.JPG)

**Comment by arjan** [comment]
Do you have `exiftool` installed? Zotonic needs that tool to determine the correct orientation of the photo.

**Comment by arjan** [comment]
Just tested; on my local install Zotonic rotates the photo just fine.

**Comment by DorienD** [comment]
I will ask Marco to check this. Thanks!

**Comment by DorienD** [comment]
We have just installed it but still it shows the picture in landscape mode. Also on dev (0.13.x) it occurs. Could there be anything else i could check?

**Comment by mworrell** [comment]
@DorienD did you re-upload the file after installing `exiftool` ?

**Comment by DorienD** [comment]
Yes ofcourse :) i replaced the media item. I have also removed the rsc and uploaded it again. Are there some special configuration things needed?

**Comment by mworrell** [comment]
Can you `{% print id.medium %}` ?

**Comment by mworrell** [comment]
Just tested with your test image, works well here on my local dev machine too.

**Comment by mworrell** [comment]
I get `{orientation,6}` for this photo. Which corresponds to a 90 degree rotation.

To see if your tools can be found you can, in the shell, also try:

```
(zotonic001@Lamma)2> z_media_identify:identify_file_direct("/path/to/your/file.jpg", z:c(sitename)).
{ok,[{orientation,6},
     {width,3648},
     {height,2736},
     {mime,"image/jpeg"}]}
```

**Comment by DorienD** [comment]
z_media_identify:identify_file_direct("/srv/zotonic/sites/musework/files/archive/2015/10/22/c54f1d74_78b3_11e5_9183_df5bfa5887e6-71458293.jpg", z:c(musework)).
{ok,[{orientation,1},
     {width,3648},
     {height,2736},
     {mime,"image/jpeg"}]}

This is what i get after doing the z_media_identify

**Comment by arjan** [comment]
And the output of `exiftool` command? And the exiftool version?

**Comment by mworrell** [comment]
The command to be run on Linux is:

```
LANG=en exif -m -t Orientation /srv/zotonic/sites/musework/files/archive/2015/10/22/c54f1d74_78b3_11e5_9183_df5bfa5887e6-71458293.jpg
```

**Comment by DorienD** [comment]
Exiftool version number 8.60

I performed: LANG=en exiftool -m -t Orientation /srv/zotonic/sites/musework/files/archive/2015/10/22/c54f1d74_78b3_11e5_9183_df5bfa5887e6-71458293.jpg

And the result below:

Resulted in file not found: Orientation 
File Name	c54f1d74_78b3_11e5_9183_df5bfa5887e6-71458293.jpg
Directory	/srv/zotonic/sites/musework/files/archive/2015/10/22
File Size	5.2 MB
File Modification Date/Time	2015:10:22 12:23:13+02:00
File Permissions	rw-r--r--
File Type	JPEG
MIME Type	image/jpeg
Exif Byte Order	Little-endian (Intel, II)
Make	Panasonic
Camera Model Name	DMC-TZ7
Orientation	Rotate 90 CW
X Resolution	180
Y Resolution	180
Resolution Unit	inches
Software	Ver.1.2
Modify Date	2015:08:18 14:29:59
Y Cb Cr Positioning	Co-sited
Exposure Time	1/500
F Number	5.6
Exposure Program	Landscape
ISO	80
Exif Version	0221
Date/Time Original	2015:08:18 14:29:59
Create Date	2015:08:18 14:29:59
Components Configuration	Y, Cb, Cr, -
Compressed Bits Per Pixel	4
Exposure Compensation	0
Max Aperture Value	3.3
Metering Mode	Multi-segment
Light Source	Unknown
Flash	Off, Did not fire
Focal Length	4.1 mm
Image Quality	High
Firmware Version	0.1.2.0
White Balance	Auto
Focus Mode	Auto
AF Area Mode	Auto or Face Detect
Image Stabilization	On, Mode 2
Macro Mode	Off
Shooting Mode	Scenery
Audio	No
Data Dump	(Binary data 8200 bytes, use -b option to extract)
White Balance Bias	0
Flash Bias	0
Internal Serial Number	(F57) 2009:11:21 no. 0057
Panasonic Exif Version	0290
Color Effect	Off
Time Since Power On	00:01:10.31
Burst Mode	Off
Sequence Number	0
Contrast Mode	Medium Low
Noise Reduction	Standard
Self Timer	Off
Rotation	Rotate 90 CW
AF Assist Lamp	Disabled and Not Required
Color Mode	Normal
Optical Zoom Mode	Standard
Conversion Lens	Off
Travel Day	n/a
World Time Location	Home
Program ISO	n/a
Advanced Scene Mode	Normal
Faces Detected	0
AF Point Position	0.5 0.5
Num Face Positions	0
Faces Recognized	0
Flash Warning	No
Maker Note Version	0131
Scene Mode	Scenery
WB Red Level	1650
WB Green Level	1054
WB Blue Level	1992
Flash Fired	No
Text Stamp	Off
Baby Age	(not set)
Transform	Off
Flashpix Version	0100
Color Space	sRGB
Exif Image Width	3648
Exif Image Height	2736
Interoperability Index	R98 - DCF basic file (sRGB)
Interoperability Version	0100
Sensing Method	One-chip color area
File Source	Digital Camera
Scene Type	Directly photographed
Custom Rendered	Normal
Exposure Mode	Auto
Digital Zoom Ratio	0
Focal Length In 35mm Format	25 mm
Scene Capture Type	Landscape
Gain Control	None
Contrast	Normal
Saturation	Normal
Sharpness	Normal
PrintIM Version	0250
Compression	JPEG (old-style)
Thumbnail Offset	10752
Thumbnail Length	6093
MPF Version	0100
Number Of Images	2
MP Image Flags	Dependent child image
MP Image Format	JPEG
MP Image Type	Large Thumbnail (full HD equivalent)
MP Image Length	876212
MP Image Start	4575232
Dependent Image 1 Entry Number	0
Dependent Image 2 Entry Number	0
Image Width	3648
Image Height	2736
Encoding Process	Baseline DCT, Huffman coding
Bits Per Sample	8
Color Components	3
Y Cb Cr Sub Sampling	YCbCr4:2:2 (2 1)
Aperture	5.6
Blue Balance	1.889943
Image Size	3648x2736
Preview Image	(Binary data 876212 bytes, use -b option to extract)
Red Balance	1.565465
Scale Factor To 35 mm Equivalent	6.1
Shutter Speed	1/500
Thumbnail Image	(Binary data 6093 bytes, use -b option to extract)
Circle Of Confusion	0.005 mm
Field Of View	71.5 deg
Focal Length	4.1 mm (35 mm equivalent: 25.0 mm)
Hyperfocal Distance	0.61 m
Light Value	14.3
    1 image files read
    1 files could not be read

**Comment by CyBeRoni** [comment]
'exiftool' and 'exif' are different tools. Which does Zotonic want?

**Comment by arjan** [comment]
Good question. It used to be exiftool, but now it's 'exif', I see.

**Comment by mworrell** [comment]
We use `exif` for deriving the Orientation from the file.  
It is also used in `mod_exif`

**Comment by DorienD** [comment]
It works!
