### ISSUE TITLE
Sites dispatcher is a bottleneck

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1065]
All requests are first dispatched by one process. This can cause a filled message box on a busy server because the dispatcher isn't called as often as it should. We can solve this by using https://github.com/zotonic/router to dispatch requests. It is a ets based trie implementation which can also be used for dispatching http requests.

**Comment by witeman** [comment]
Cheers!  I just have began to make original dispatcher to poolboyed dispatchers.  Although it is easy to modify, it is not as good as router solution.

**Comment by mmzeeman** [comment]
The current dispatcher masks a couple of other bottlenecks. If you just change the dispatcher things will get worse. I’m busy with a wiki page on this https://github.com/zotonic/zotonic/wiki/Improving-zotonic's-throughput

**Comment by witeman** [comment]
Sure, I will wait for your integration of the router solution!

This is a help in time :) Thanks a lot!

**Comment by mmzeeman** [comment]
Do you currently have problems with it?

**Comment by arjan** [comment]
@witeman I have a poolboy implementation of the dispatcher lying somewhere, coded it a while back. But it did not drastically increase the throughput, I must say. I'll see if I can find the code, just for reference.

**Comment by mmzeeman** [comment]
That is because there are a couple of bottlenecks after the dispatcher. I have a simple site dispatcher implementation which has all dispatch rules in ets. It pointed me to some other problems. So just removing the dispatcher bottleneck doesn't do anything. It can even make things worse.

**Comment by mmzeeman** [comment]
Screenshot of ets of zotonic under stress with current server based dispatcher.

<img width="670" alt="screen shot 2015-10-22 at 11 58 31" src="https://cloud.githubusercontent.com/assets/1024972/10701929/a0511b80-79c6-11e5-82f9-840539bc18c3.png">

**Comment by witeman** [comment]
When we did the stress testing, we encountered the dispatch process gen_server call timeout.  But this is really sophisticated, one process to do the gateway things above webmachine.

BR.
Witeman

**Comment by mworrell** [comment]
This has been fixed, the new dispatch compiler seems to be working well.

We need to add some test sets, and maybe move it to its own repository.
See issue #1072

**Comment by arjan** [comment]
Wow, this looks really impressive! I'm looking forward to give it a go.

**Comment by mmzeeman** [comment]
It is impressive. Don't forget to upgrade the depcache too. Quite an interesting approach too. Data as code.

Controller controller_hello_world now maxes out at 24k req/s on my 4 core i5 dev machine (without access logging).

**Comment by witeman** [comment]
Well done!!!  Cheers Zotonic Team!!!

**Comment by mworrell** [comment]
@witeman Thanks :) We are moving the dispatch compiler to its own repository, as we suspect other projects can make use of it as well.

**Comment by mworrell** [comment]
And @mmzeeman is still doing great work on the logging bottleneck.
