### ISSUE TITLE
Website gets set to '/' on rsc duplicate

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#1066]
When duplicating a resource, it gets its 'website' property set to "/", which is an invalid URL.
Therefore the page fails to save in the admin after the duplicate action.

**Comment by mworrell** [comment]
I assume that this is only the case if the website property was empty before?

**Comment by arjan** [comment]
yes.

**Comment by mworrell** [comment]
Fixed in https://github.com/zotonic/z_stdlib/commit/245a46e089ffa5c591ea2b4c891e0ee3a488e632
