### ISSUE TITLE
The modified check of the template server is a bottleneck.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1068]
When you remove the dispatcher bottleneck the template server becomes a bottleneck. This is because when you render a template a check_modified check is sent to the template server.

@mworrell has some ideas to change this modified check with help of the inotify, fswatcher and the just added file change poller.

<img width="679" alt="screen shot 2015-10-22 at 08 31 08" src="https://cloud.githubusercontent.com/assets/1024972/10701962/eb0cdca4-79c6-11e5-8df2-509554c233c0.png">

**Comment by mmzeeman** [comment]
Amazing what effect this change had.

**Comment by mworrell** [comment]
We still have to remove the configuration to not check mtimes. It is not used anymore anyway.
