### ISSUE TITLE
Bottleneck when retrieving language settings

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1069]
When the language settings are set in the dispatcher they are retrieved from the site's depcache process.  This causes a bottleneck after dispatching.

See (the 200 messages in the depcache process, the logger is another issue)

<img width="651" alt="screen shot 2015-10-22 at 12 06 44" src="https://cloud.githubusercontent.com/assets/1024972/10703060/bae44632-79cd-11e5-8e2f-5547ba64ca80.png">

**Comment by mworrell** [comment]
I think we can make this better using mochiglobal.
The config doesn't change much, so we can compile it to a module on changes.

**Comment by mmzeeman** [comment]
I tried it with mochiglobal. Interesting concept... data as code. I got all sorts of ideas for other things.
However, mochiglobal makes flushing and resetting after crashes more difficult. With z_depcache:memo it works nicely too, and it has automatic dependency handling.
