### ISSUE TITLE
More control over search ranking

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1076]
As discussed yesterday with @mworrell, @loetie and @fredpook (see our notes below), the way search results are currently ranked can be confusing for users:
- related pages are ranked higher than a page that is primarily about the search term when that search term appears more often on the related pages
- for results in categories such as news or blog, old items can be ranked above more recent and relevant ones
- results in categories that form the core business (such as subsidies) are ranked too low.

These issues (and related ones) can be solved by allowing more fine-grained control of the way Zotonic ranks search results (through PostgreSQL’s weights A/B/C/D). This can be done as follows.
1. A single resource is ranked higher when the `is_featured` property is set.
2. All resources in a category are ranked higher when the `is_featured` property is set on the category.
3. A new `search_rank` (?) fold notification allows even more detailed control. By observing this notification, sites can prefer more recent items over outdated ones. To work correctly for date-related ranking, this notification must be scheduled to run each day/week/month.

![img_2117 1](https://cloud.githubusercontent.com/assets/89267/10944450/8b8975ba-8319-11e5-85fd-af790740638e.jpg)

**Comment by mworrell** [comment]
Note:

Maybe the re-indexing of old events (ie. in the past) could be run in batches? Like fetching date ranges for stuff that is between thresholds. This query could even be a configurable query.

If we run this query then we could get the set of pages to newly add to one of the buckets: important, normal, low, and not-important-at-all (need to come up with names, maybe just A, B, C and D).

By using buckets (and reindexing accordingly) we might be able to prevent big re-indexing actions.

The text of a resource is re-sorted into the A/B/C/D categories depending on the priority. This priority should also be saved with the resource, so that we can use it in more dynamic ways for filtering/sorting etc.

**Comment by mworrell** [comment]
See the full text indexing proposal on #1113

**Comment by fredpook** [comment]
See also: #1113

"Proposal to make full text indexing really flexible: add templates for rendering the texts that need to be indexed. The template can be made of four blocks/parts. Each part signifying a A...D priority. After rendering we can fetch the parts and build the full text index. If we use a catinclude for the template then it is easy for front end programmers to fine tune how different categories can be indexed.

In the template itself we can loop over the different languages provided by the resource. The pivoter will use the default language as pre-selected language for rendering (and sudo permissions to access the resource)."

**Comment by ddeboer** [comment]
This can only and will be done on master.

**Comment by ddeboer** [comment]
> 1. A single resource is ranked higher when the is_featured property is set.
> 2. All resources in a category are ranked higher when the is_featured property is set on the category.
> 3. A new search_rank (?) fold notification allows even more detailed control. By observing this notification, sites can prefer more recent items over outdated ones. To work correctly for date-related ranking, this notification must be scheduled to run each day/week/month.

We can now add this behaviour in the [pivot templates](http://zotonic.com/docs/latest/cookbook/pivot-templates.html#cookbook-pivot-templates) (1.0 only). @mworrell How would this work? If `is_featured` is false, move the title, description etc. down to the C or D block? Or are there other ways in PostgreSQL?

**Comment by ddeboer** [comment]
As a sidenote, in mod_elasticsearch we solved

> 3 A new search_rank (?) fold notification allows even more detailed control. By observing this notification, sites can prefer more recent items over outdated ones. To work correctly for date-related ranking, this notification must be scheduled to run each day/week/month.

with [support for custom sort functions](https://github.com/driebit/mod_elasticsearch/pull/24/files).

**Comment by mworrell** [comment]
I think we can consider this fixed using the pivot templates http://docs.zotonic.com/en/latest/cookbook/pivot-templates.html#cookbook-pivot-templates

These templates should move text between the blocks depending on the `is_featured` flags and other application specific conditions.
