### ISSUE TITLE
Use os:find_executable in all places where external programs are called

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1078]
I just ran into this problem and found this mailing list post:

https://groups.google.com/forum/#!topic/zotonic-developers/EiiUnoFLkQc

The output of 'which' on SunOS is different to Linux if the binary isn't found. But most importantly, running 'which' from a program and parsing the output is a terriblly non-portable idea in general especially if there is a native way to do the same: [os:find_executable](http://www.erlang.org/doc/man/os.html) should do this in a portable way. 

Alternatively, check the return status rather than relying on string comparisons.

**Comment by arjan** [comment]
Getting the process output of a program and the exit code at the same time is problematic for Erlang, you cannot do that with the standard library but you'll have to rely on a library like https://github.com/saleyn/erlexec to do that.

I'll :+1: the `os:find_executable`, we should use that on all instances where we call external programs.

**Comment by mworrell** [comment]
Should we also check this when calling`identify` (and friends) ?

**Comment by CyBeRoni** [comment]
Whereever 'which' is currently used I'd say.

**Comment by mworrell** [comment]
That is now fixed, except in https://github.com/zotonic/zotonic/blob/7bbe654c92c65426dd06a6535f13ed076f02ebd1/src/filewatcher/z_filewatcher_handler.erl#L300 where it is part of the cmd.

**Comment by mworrell** [comment]
We might be able to generate better error messages if we first check for `identify` and `convert` before calling it.

**Comment by mworrell** [comment]
BTW was is the `os:type()` on SunOS?

**Comment by CyBeRoni** [comment]
'sunos', as per documentation:

```
2> os:type().
{unix,sunos}
```

**Comment by mworrell** [comment]
Ok, then the `{unix, _Arch}` will also enable the notification on SunOS
