### ISSUE TITLE
HTTP2 support (was SPDY support)

### ISSUE THREAD

**Issue by jult** [zotonic/zotonic#1079]
Do you intend to add this to the serving particles, or do we have to resort to using proxying for that?
https://developers.google.com/speed/spdy/

I've recently added spdy to a TLS-only hosting nginx webserver I maintain, it showed significant speed-gains.

**Comment by mworrell** [comment]
For the 1.0 we will be replacing MochiWeb with either Cowboy or Elli.
After that replacement we also want to add http2 support (which is the successor of spdy)

**Comment by ddeboer** [comment]
Removed 1.0 milestone; see #1138.

**Comment by mworrell** [comment]
On master we use Cowboy2, which has http2 support.
