### ISSUE TITLE
Unpublished resources turn up in search results when mod_acl_user_groups is enabled

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1081]
When a search is executed, an `acl_add_sql_check` notification [is thrown](https://github.com/zotonic/zotonic/blob/master/src/support/z_search.erl#L263). Mod_acl_user_groups listens to this notification and returns a query extended with a content group clause. This, however, prevents the [sane defaults](https://github.com/zotonic/zotonic/blob/master/src/support/z_search.erl#L265) in `z_search`, including the exclusion of unpublished resources, from being added to the search SQL. 

I propose that we:
- either always add the defaults
- or make the `z_notifier:first` a fold so we can add our own observer in addition to the user groups one to add the defaults.

**Comment by mworrell** [comment]
Actually this is not as easy as it sounds.

The same queries are used in the admin and for editorial views, where the publication flag and period are not checked.

We have to ensure that the argument `is_published=all` is set for all admin related queries. This sets the `no_publish_check` flag in the arguments passed with the `acl_add_sql_check`

Then this flag can be checked to see if we should add or not add the publication checks.

What is done in MaxClass is:

 * If admin user, then never add a publication check
 * If anonymous user then always add a publication check
 * Otherwise check the `no_publish_check` flag

The question is what we define as a 'admin' user in this context. Usually it is the admin, sudo, or any user with `use.mod_admin_config` permission.

**Comment by ddeboer** [comment]
> The question is what we define as a 'admin' user in this context. Usually it is the admin, sudo, or any user with use.mod_admin_config permission.

This sounds exactly right: let’s just stick to `z_acl:is_admin/1`. The only potentially confusing side-effect for those admin users is that they will see unpublished/invisible resources in their search results outside the admin, too.

**Comment by mworrell** [comment]
We have to check the views in the admin, if this goes well with non-admin-users (aka editors who are allowed to use the admin).

But besides that it sounds like a safe plan.

**Comment by ddeboer** [comment]
By the way, shouldn’t we add `use mod_admin` to `z_acl:is_admin/1` as well? When granting groups access to the admin, we usually do so by giving them use access to `mod_admin`.

**Comment by mworrell** [comment]
The semantics of `is_admin` are that they can configure the site. So that might be a bit over the top.

**Comment by ddeboer** [comment]
We often have user groups, such as editors, that should be able to use the admin without giving them access to `mod_admin_config` pages such as Status. As those editors are the ones that publish resources, they should be able to view unpublished ones. 

A completely different solution, of course, is to add a separate ‘view unpublished’ permission to the ACL rules. The problem I have with that, though, is that we go this way the permission list can get very crowded very soon.

**Comment by ddeboer** [comment]
Or, more generically: if users have edit permissions on a resource, we can assume they are able to view unpublished resources in the same category.

**Comment by mworrell** [comment]
That is something impossible to check using some generic SQL.

I propose to just ensure that the `is_published=all` is added to the admin queries (or that the `no_publish_check` is set for admin related queries.

This is generic and no magic is involved, which makes maintenance easier.

**Comment by ddeboer** [comment]
After having discussed this, we come to the conclusion: only check `use.mod_admin` (not `is_admin`).

**Comment by ddeboer** [comment]
:+1:

**Comment by ddeboer** [comment]
@mworrell Tested this on 0.13.x and seems to work.
