### ISSUE TITLE
ifwith template tag

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1085]
This concerns a small suggestion for the template language. A pattern that is often seen in templates is combining the `if` and `with` tag. Something like:

````
{% with maybeathing as result  %}
    {% if result %}
        ....
    {% endif %}
{% endwith %}
````

We could roll this into one succinct statement that would function like this:

````
{% ifwith maybeathing as result  %}
        ....
{% endwith %}
````

**Comment by ArthurClemens** [comment]
Would this work for a multi variable definition?

**Comment by mworrell** [comment]
I was wondering that too - I don't think that would work. Or at least I can't come up with good semantics with that one, as it is unclear if we should *and* or *or* the terms.

**Comment by Dirklectisch** [comment]
This would be most useful with a single variable definition. For multi variable definitions I would choose *and* semantics if needed but we could also not support that at all.

**Comment by arjan** [comment]
@Dirklectisch :+1: , this is similar to clojure's `if-let`, which also is restricted to a single variable assignment. I'd also like it to have an optional `{% else %}` clause, btw.

**Comment by Dirklectisch** [comment]
@arjan Clojure's `if-let` was indeed my inspiration.

**Comment by mworrell** [comment]
So then we would get the following syntax?

```
{% ifwith some-expression as var %}
{% else %}
{% endifwith %}
```

Or do we also need a `{% elifwith %}` ?

**Comment by mworrell** [comment]
Of course we could also extend the `if` a bit with an optional `as var`:

```
{% if some-expression as var %}
...
{% endif %}
```

**Comment by mmzeeman** [comment]
Is that indeed a common template pattern? I searched a bit in the admin templates, but couldn't find any.

**Comment by mmzeeman** [comment]
Or is it possible to make the value of the expression available as 'it'? And make that available?

```
{% if some-expr  %}
    {{ it }}
{% endwith %}
```

**Comment by arjan** [comment]
That seems too much like magic to me. And would cause problems with nested clauses. The `as var` syntax proposal seems also nice to me. But then it would also need to work for the `{% elseif %}`.

**Comment by mmzeeman** [comment]
Do you have something like this as a common pattern in your templates?

**Comment by mworrell** [comment]
The combination of a with and an if happens quite  often with search results.

**Comment by arjan** [comment]
Nice! Could you document this somewhere?

**Comment by mworrell** [comment]
Good one :) - completely forgotten because of all changes to make the tests run again...
