### ISSUE TITLE
improvement:  Multi value inputs for resource model

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1086]
Sometimes you might want to store the output of a group of checkboxes in the admin in 1 property.
Currently it will just store the first one in the list.
Any ideas how to do this?
cc @ArthurClemens @arjan @mworrell

**Comment by ArthurClemens** [comment]
I've never succeeded to get this to work. My solution for multi values is to always use connections.

**Comment by mworrell** [comment]
Actually, that is a good solution for the problem we were facing. Closing for now.
