### ISSUE TITLE
Setting ‘uri’ property requires access to mod_admin_config

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1087]
See https://github.com/zotonic/zotonic/blob/master/src/models/m_rsc_update.erl#L551. This is rather confusing. What is the rationale behind it? I’d like to use the `uri` property in non-authoritative (linked data) resources to point to their external, authoritative URI.

**Comment by mworrell** [comment]
This might be a bit too careful, protecting some system resources and the like.
I think this check can be relaxed, to just edit permissions (i.e. the whole check could be removed).

/cc @arjan

**Comment by ddeboer** [comment]
Agree on removing the check.

**Comment by ddeboer** [comment]
After discussion: if users have update permissions on the resource, allow them to change its `uri`, too.
