### ISSUE TITLE
Support for DKIM e-mail signing

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#1089]
To help get around spam filters it would be nice to sign outgoing e-mails with a DKIM signature. `gen_smtp` [already supports this](https://github.com/Vagabond/gen_smtp#dkim-signing-of-outgoing-emails) so it should not be too hard to add it to `z_email`.

**Comment by mworrell** [comment]
We could use this iff the sending site has an SSL key configured and mod_ssl enabled.
Can it be self-signed, or do we then make spam-ratings worse?

**Comment by mworrell** [comment]
Might need a configuration screen that also tells the user which DNS entry is needed to make it all work.
The config screen only needs an on/off if we use the keys from mod_ssl.

**Comment by CyBeRoni** [comment]
DKIM is not dependent on CA-signed certificate, and in fact you would typically not use your HTTPS keys for this.

**Comment by arjan** [comment]
But using a self-signed cert would quite defeat the purpose or not?

**Comment by arjan** [comment]
or is the fact that the public key is acquired through DNS enough?

**Comment by CyBeRoni** [comment]
There is no cert in DKIM. It's entirely based DNS-based public keys.

**Comment by arjan** [comment]
Cool, that makes it quite easy. Only thing is that it would be good to have a configuration page where it explains how to set up the DNS record, possibly with a check button to see if is correctly installed.

**Comment by mworrell** [comment]
:+1:   (especially for the check button ... otherwise it becomes really difficult to check)

**Comment by arjan** [comment]
This has been fixed in 73199483e7f1a8c3fc64d11acd1803b24880e79c; except for the check button. There are plenty of web tools out there to check it. Lets leave the check button on the wish list.

**Comment by arjan** [comment]
See #1266
