### ISSUE TITLE
Postbacks, comet and websocket requests start unneeded extra page-session

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1090]
Postbacks and websocket requests start unneeded extra page sessions.

It also looks like only websocket connected page's can reload themselves when they notice the session has expired. Comet connections will fail when this happens and start a very slow polling loop and will never attach again.

This also looks strange:

https://github.com/zotonic/zotonic/blob/master/src/support/z_context.erl#L629

A continue page session which later on ensure's a page session.

**Comment by mworrell** [comment]
This is now fixed on master, with a considerable amount of changes.
Merging into the 0.13.x will take some time and testing.
Postponing to the 0.13.7

**Comment by mmzeeman** [comment]
I would like to put the connection test page on 0.13 as well. Is that ok with you too... 

That was how I found the problem.

**Comment by mworrell** [comment]
That is ok with me. 

Keep it for the 0.13.7?  So that we don't delay the 0.13.6?

/cc @ddeboer

**Comment by ddeboer** [comment]
Agreed on fixing this in 0.13.7.

**Comment by mmzeeman** [comment]
0.13.7 is fine with me. 

This problem was here for a long time. Starting an extra process is not that big of deal anyway. It is better to test the new connection code before hot-loading it to 15k connected clients :-)

**Comment by ddeboer** [comment]
Postponing this once again, sorry @mmzeeman. :wink:

**Comment by mmzeeman** [comment]
no, this must be in. otherwise the connection test page doesn't work and i have to have that in next release.

**Comment by mmzeeman** [comment]
@ddeboer What is the reason for post phoning?

**Comment by mmzeeman** [comment]
I will merge this fixes and refactor and after you spit off the 0.13.7 branch. We need these transport fixes on our server. @ddeboer @mworrell

**Comment by ddeboer** [comment]
@mmzeeman Sounds good. 0.13.8 is [scheduled](https://github.com/zotonic/zotonic/milestones) for the first Monday next month](https://github.com/zotonic/zotonic/pull/1142): 1st of Feb. Would it still be in time for you if we release your fixes in 0.13.8?

**Comment by mmzeeman** [comment]
No that is too late. 

I will test the changes and run off the 0.13.x branch before the release. There isn't anything I need in the 0.13.7 release anyway. 

We have a client with problems connecting with comet and websockets. The connection test page should help them fix this. The page however uncovered several bug in zotonics transport layer. This is just one of them.
