### ISSUE TITLE
Documentation: The module overview doesn't show the module names

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1091]
http://zotonic.com/docs/0.13/ref/modules/index.html
is another overview?

but I miss
http://zotonic.com/docs/0.12/ref/modules/index.html

**Comment by ArthurClemens** [comment]
What are you missing?

**Comment by fredpook** [comment]
The module overview like it was on:
http://zotonic.com/docs/0.12/ref/modules/index.html

**Comment by mworrell** [comment]
Basically, the name of the module is gone.

**Comment by mworrell** [comment]
Seems like the 'h1' with the module name is not part of the stub anymore?

**Comment by ArthurClemens** [comment]
The generated documentation on my machine works as before. The directory contains the meta- files that each have a title. Something with the zotonic.com server setup?

**Comment by mworrell** [comment]
Let's see what happens after some more pushes - I don't think the server was updated though.

**Comment by ArthurClemens** [comment]
Still no change on the server.

**Comment by mworrell** [comment]
On the server we have `Sphinx (sphinx-build) 1.2.2`
Which version do you use?  On my dev machine I have 1.1.3

**Comment by ArthurClemens** [comment]
On my machine 1.2.2

**Comment by mworrell** [comment]
Interesting .... the server is running Ubuntu, checking it on my local Ubuntu machine.

**Comment by mworrell** [comment]
When I run this on my Ubuntu server I get the following errors:

```
/home/marc/zotonic/zotonic/doc/ref/modules/mod_tkvstore.rst:2: SEVERE: Problems with "include" directive path:
InputError: [Errno 2] No such file or directory: 'ref/modules/meta-mod_tkvstore.rst'.
```

**Comment by ArthurClemens** [comment]
I believe that the meta files need to be generated.

**Comment by mworrell** [comment]
Stub generation was looking for directories with the name `mod_*.erl`
Easy to fix.
