### ISSUE TITLE
/ in website field after duplicating page

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1093]
Hi!

Every time when i duplicate a page i get a / in the website address field. Which makes saving impossible because you don't see the website field in first view.

~ Dorien

**Comment by mworrell** [comment]
This was an old(er) issue and has been fixed in z_stdlib.  
Please update your deps/z_stdlib.

**Comment by mworrell** [comment]
BTW why can't you save with a '/' in the website field?  The website field can contain a url to the local website (eg, `/foo/bar?a=b`)

**Comment by DorienD** [comment]
Ah, doing it now :)

**Comment by DorienD** [comment]
idk it says i have to fill in a correct url

**Comment by mworrell** [comment]
On the 0.13.x?
I can save here with a '/' in the website field.

**Comment by DorienD** [comment]
I have just pulled 0.13.x and still get this error: 
![screen shot 2015-11-25 at 15 38 17](https://cloud.githubusercontent.com/assets/5102362/11399930/9ac8d1de-938a-11e5-8a56-6cf66c4da34c.png)

**Comment by arjan** [comment]
I suspect the website field might be an `<input type="url">`

**Comment by mworrell** [comment]
Are you using your own templates?
This doesn't look like the admin.

**Comment by DorienD** [comment]
i will check if we use our own templates there

**Comment by DorienD** [comment]
We have overwritten the template but the html seems to be the same, the input is indeed type="url"

**Comment by arjan** [comment]
That popup you see is a browser builtin popup; Chrome, I believe.
We can also disable it by doing `<form novalidate>` in the rsc form tag
