### ISSUE TITLE
controller_page: change 302 redirect to 301

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1094]
When a `page_path` setting changes the page location, a temporary 302 redirect is used.

The code comments say:

```
%% Check if we need to be at a different URL. If the page_path
%% of a resource is set, we need to redirect there if the
%% current request's path is not equal to the resource's path.
```

I believe that this should be a permanent redirect (301), because the location will only change when the page_path is changed - for many pages this is the permanent location.

In terms of SEO, the 302 redirects result in ranking penalties. Grabbed from [a random SEO site](https://moz.com/learn/seo/redirection):

> A 302 redirect is a temporary redirect. It passes 0% of link juice (ranking power) and, in most cases, should not be used. The Internet runs on a protocol called HyperText Transfer Protocol (HTTP) which dictates how URLs work. It has two major versions, 1.0 and 1.1. In the first version, 302 referred to the status code "Moved Temporarily." This was changed in version 1.1 to mean "Found."

> A 301 redirect is a permanent redirect which passes between 90-99% of link juice (ranking power) to the redirected page. 301 refers to the HTTP status code for this type of redirect. In most instances, the 301 redirect is the best method for implementing redirects on a website.

**Comment by mworrell** [comment]
My only problem with making this a 301 is that permanent might clash with the fact that the property can be edited. Those changes will not affect any browsers that cached the redirect.

When are you hitting the non-`page_path` url? As the `page_url` property would return the page_path.
Or is this in the case you have some pre-existing page which now gets its own unique page_path?

(I understand that this is about the page_path redirect, and not the website redirect)

**Comment by arjan** [comment]
Interesting term, btw, "link juice"... sounds nasty for some reason :p

**Comment by mworrell** [comment]
It sounds like some script kiddy language, or some consultant trying to be hip.

**Comment by ArthurClemens** [comment]
The browser cache is an important issue that I had not considered. From http://stackoverflow.com/questions/9130422/how-long-do-browsers-cache-http-301s :

> Chrome and Firefox will cache a 301 redirect with no expiry date.
That is, it will remain cached for as long as the browser's cache can accommodate it. It will be removed from the cache if you manually clear the cache, or if the cache entries are purged to make room for new ones.

> If you previously issued a 301 redirect but want to un-do that
If people still have the cached 301 redirect in their browser they will continue to be taken to the target page regardless of whether the source page still has the redirect in place. Your options for fixing this include:
The simplest and best solution is to issue another 301 redirect back again.

This is not maintainable. 

I need to investigate the root cause further.

**Comment by mworrell** [comment]
Those browsers keep the 301 even longer than I suspected...
