### ISSUE TITLE
Collaboration groups

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1099]
We have sites where access to content is divided into projects, research groups or (university) minors. In all cases, it comes down to a group of users (e.g., students) having a one-to-one access relation to a group of content (e.g., publications). 

As discussed today with @mworrell and @fredpook, it doesn’t really make sense to have both a user and a content group for these cases. After all, the site’s editors and admins think in terms of adding one entity (project, group, minor), not two.

So let’s introduce ‘collaboration groups’.

1. Add a separate module `mod_collaboration_groups`.
2. A collaboration group is a subcategory of content group.
3. In the user group (on the user’s permissions dialog) we render all user groups plus all collaboration groups, probably in a separate `optgroup`. Admins can then give users (students) direct access to a group of content (minor), without a user group in between.
4. In the admin ACL list, we show one dropdown for collaboration groups rules (labeled ‘collaboration group’) instead of the two currently shown (user and content group).

**Comment by mworrell** [comment]
I was thinking that we could also integrate this into the mod_acl_user_groups. As it is not that much extra and integrates quite closely to logic and presentation of the ACL rules managed by mod_acl_user_groups.

**Comment by ddeboer** [comment]
Fair enough. The only optional thing I see is the creation of the ‘collaboration group’ subcategory. Let’s hope it doesn’t confuse users that do not need collaboration groups too much. :wink:

**Comment by mworrell** [comment]
I though, that we could add a tab with default access rules for 'collaboration groups'.
Exceptions on the default rules could be configured in the normal ACL rules tab.

**Comment by ddeboer** [comment]
Yes, let’s add collaboration groups default ACLs in the interface.

**Comment by ddeboer** [comment]
@mworrell Is this something you want to work on?

**Comment by mworrell** [comment]
Proposal for interface:

1. Add tab *Collaboration Groups* to the access control rules view on /admin/acl/rules
2. On that tab show allow adding rules, similar to the normal rules except that the user and content group don't need to be specified.

Question:

Do we need to discern roles within a collaboration group (think of manager vs member)?
There are two options here: we allow two roles and add specific code, or we define *generic managers* via the usual access control rules.

**Comment by ddeboer** [comment]
> Proposal for interface:

Those are the general rules for each collaboration group, right? In that case, I agree with the UI.

> Do we need to discern roles within a collaboration group (think of manager vs member)?

Yes: we have some use cases that require this differentiation, e.g. students editing only their own publications (`{is_owner, true}`) and teachers reviewing all of them. The problem is that we currently have no concept of ‘roles’ in mod_acl_user_groups: it is covered by the concept of ‘user groups’. So the differentiation actually calls for *multiple* user groups per content groups, while the idea of collaboration groups is to have a one-to-one relation; see https://github.com/zotonic/zotonic/issues/1099#issue-119695564.

Of course, in the above example, we could add each teacher to an *additional* user group ‘teachers’. What about then inheriting that user group’s permissions (e.g., `[view, update, delete]`) but changing the content group id to the collaboration group id? 

@fredpook Any input?

**Comment by mworrell** [comment]
Let's keep it simple for now:

 * We define members of a collaboration group in the same way we define membership of an user group.
 * There is only a single *role*: membership
 * Teachers/managers are given special rights via the usual ACL rules
 * We have *only_own* in the usual ACL rules, I think that can cover the use case of students editing their own publications.
 * We don't (yet) support visibility levels: "public", "group", "private"

ok?

**Comment by ddeboer** [comment]
Yes.

> We have only_own in the usual ACL rules, I think that can cover the use case of students editing their own publications.

You mean ‘manage own’ (`{is_owner, true}`), right?

**Comment by mworrell** [comment]
Indeed, that permission.

**Comment by ddeboer** [comment]
:+1:

**Comment by ddeboer** [comment]
Postponed to 0.13.8.

**Comment by mworrell** [comment]
Yes, can't get it properly tested before release.

**Comment by mmzeeman** [comment]
The groups are very handy for us. We have a multi-tenant setup with separate accounts. Currently I do this with predicates and a custom acl.

**Comment by mworrell** [comment]
See merge request #1238

**Comment by mworrell** [comment]
The first version has been merged. Closing this issue.
(Documentation will come with #1240 )
