### ISSUE TITLE
Unrecognized files get a .bin extension

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#11]
_From http://code.google.com/p/zotonic/issues/detail?id=5_

<b>What steps will reproduce the problem?</b>
1. Upload a non-image file, like a .tgz or a .txt, using the &quot;add media&quot;
button in the admin edit page.

<b>What is the expected output? What do you see instead?</b>

The extension of the file will be changed to .bin. This causes browsers not
to display the file correctly.

**Comment by jult** [comment]
OK, so how do we add .mbd files to not become .bin and to be allowed for upload? (still happens, with zotonic 0.13.6)
.mbd seems to be application/mbedlet (whatever that is..).

**Comment by mworrell** [comment]
`.mbd` is unknown to the *mimetypes* application we use, that is why it is mapped to *application/octet-stream`

What does the `file` command line utility say?

If you want to accept the file then you can add an observer for the `#media_identify_file` notification.
This is called from `z_meda_identify.erl` in the following way:

```
case z_notifier:first(#media_identify_file{filename=File, original_filename=OriginalFilename, extension=Extension}, Context) of
     {ok, Props} -> ...
     undefined ...
end
```

The Props should contain (in your case) `[{mime, "application/mbedlet"}]`
