### ISSUE TITLE
Page title is limited to 80 chars, but admin interface allows much longer texts

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1106]
Either the limit should be increased, or a validation message should be displayed.

**Comment by mworrell** [comment]
Isn't the title only limited for the pivot? In the serialized props there is no real limit for the page title length.

**Comment by ArthurClemens** [comment]
Indeed the message shows a pivot error. But I cannot remember creating that pivot myself.

**Comment by mworrell** [comment]
In the pivot we now truncate the title (and other fields).
