### ISSUE TITLE
Live validation doesn't set invalid/valid class on form

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1107]
Hi!

See this comment: https://github.com/zotonic/zotonic/commit/1666ed4e6bea8f01ca503037fc7da8d7acf63e24

The `this` in the onvalid/invalid functions refers to the form element, and not the live validation object.

**Comment by ArthurClemens** [comment]
I am missing simple test pages for these kind of things. I either have to look for a page where validation is used, or create my own page.

**Comment by DorienD** [comment]
I tried it with the survey page. Add 1 question and a page break and you can test the live validation.

**Comment by mworrell** [comment]
It is actually a simple fix if we add the usual `self = this;` in front of the functions (aka methods).

**Comment by mworrell** [comment]
@DorienD could you check with the above fix?

**Comment by mworrell** [comment]
Closing, assuming it also works for @DorienD as well.
