### ISSUE TITLE
PNG/GIF should stay PNG/GIF when using the {% image %} tag

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1111]
Because of a mistake in the ImageMagick config?

**Comment by mworrell** [comment]
Did you add the 'lossless' resize option?

**Comment by arjan** [comment]
Yeah, without `lossless`, all images are converted to JPG, currently.

Actually, this behaviour is quite annoying; because PNG files usually need to stay PNG files; PNG files usually contains text/graphics which leave compression artefacts with JPG. @mworrell what about changing this?

**Comment by arjan** [comment]
Maybe a `lossless="auto"` option? (which would be the default?)

**Comment by mworrell** [comment]
Makes sense, though only per default for PNG and GIF. As there quite some users uploading BMP and other lossless formats instead of photos.

**Comment by arjan** [comment]
true. I'll work on this.

**Comment by arjan** [comment]
@ddboer OK if I hijack this ticket? :)

**Comment by ArthurClemens** [comment]
Or set the destination format: `format="png"`

**Comment by arjan** [comment]
No, the issue is that I want the images look good depending on the source mime type;
so when it is PNG, it should stay png, when its a JPG, it should stay JPG.

Basically `lossless="auto"` would mean something like:

input jpg -> output jpg
input png -> output png
input gif -> output gif
input other lossless format -> png
input other lossy format -> jpg

**Comment by ArthurClemens** [comment]
A bit cryptic but workable.

**Comment by arjan** [comment]
yeah.. i'll try to document it more clearly.

**Comment by mworrell** [comment]
> Basically lossless="auto" would mean something like:
> 
> input jpg -> output jpg
> input png -> output png
> input gif -> output gif
> input other lossless format -> png
> 
I prefer the "other lossless" to be mapped to JPG, just to prevent big scans and other bitmap images to become huge PNG images. Web designers will know to upload PNG or GIF.
So only keep GIF and PNG as-is, all other formats to JPG
> input other lossy format -> jpg
>

**Comment by ddeboer** [comment]
> Did you add the 'lossless' resize option?

Indeed, this works, but it is counter-intuitive. When I upload a transparent PNG, I expect it to stay transparent when rendering it unless I specify otherwise.

> @ddeboer OK if I hijack this ticket? :)

No problem! Great if we can come up with a generic solution.

**Comment by mworrell** [comment]
@ddeboer the current business rule is to always render to JPEG unless stated otherwise. This is to be able to handle arbitrary user input without generating huge lossless files.
