### ISSUE TITLE
Add page blocks to full text search

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1113]
The content of page blocks is currently not searchable. Let’s make it so, perhaps with a slightly lower priority than the body text?

**Comment by mworrell** [comment]
Maybe this can be checked in the context of #1076 ?

**Comment by mworrell** [comment]
Putting this on the same milestone as #1076

**Comment by ddeboer** [comment]
Agreed.

**Comment by ddeboer** [comment]
Discussed today:

* only index page block title and body, with same priority (A/B) as parent resource
* embedded page blocks (that refer to other resources) that are inline should be indexed as well.

**Comment by mworrell** [comment]
Proposal to make full text  indexing really flexible: add templates for rendering the texts that need to be indexed. The template can be made of four blocks/parts. Each part signifying a A...D priority. After rendering we can fetch the parts and build the full text index. If we use a catinclude for the template then it is easy for front end programmers to fine tune how different categories can be indexed.

In the template itself we can loop over the different languages provided by the resource. The pivoter will use the default language as pre-selected language for rendering (and sudo permissions to access the resource).

**Comment by ddeboer** [comment]
I like it!

**Comment by mworrell** [comment]
Note: also add a block that can be filled with a proposed re-indexing date. In this way an event can be automatically demoted after its end date.

**Comment by fredpook** [comment]
+1

**Comment by ddeboer** [comment]
We decided that @mworrell will create the template (`fulltext.tpl`). We’ll then discuss together what that template should exactly look like.
