### ISSUE TITLE
Media tag should omit width and height from img tag for browser side resizing

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1118]
In order to leave the exact sizing of images over to browsers the added calculated width and height attributes should be omitted from the img tag. Is there a way to do that?

**Comment by mworrell** [comment]
You can use the `{% image_url %}` tag and the add the `<img />` around it yourself.

Another, often used, option is to use css to resize to the container.
Something like this:

```
img {
    max-width: 100%;
    height: auto !important;
}
```

**Comment by mmzeeman** [comment]
Thanks, the auto height worked perfectly. 

Btw, the height/width parameters also confused Justin. He thought the values where used verbatim in the resulting img tag. But if you read the manual you see that those parameters really mean ```max_width``` and ```max_height``` and are used to generate the img url.
