### ISSUE TITLE
File changes not picked up reliably when fswatch is used (OSX)

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1120]
Filewatcher `fswatch` maps watched filenames with `realpath(3)`.

This differs from what zotonic is using internally when symbolic links are used. Reported changes are not picked up automatically because of this. 

Unfortunately erlang does not have support for the realpath system call.

**Comment by mworrell** [comment]
Maybe we could start using https://github.com/synrc/fs instead of the current fswatch/inotify code?

**Comment by arjan** [comment]
I doubt that that fixes the issue. The filewatcher already resolves symlinks before watching (see `z_filewatcher_sup:watch_dirs()`), so it knows about them. So it should be not so hard to translate the real path back to the symlinked path before handing off the notification.

**Comment by mworrell** [comment]
There might still be a conflict, as the `watch_dirs` is using a relative path and doesn't know the realpath. So we still need some logic to map between them, which could also be done using some heuristics based on the module/site name in the relative-path and the real-path.

BTW I added the fs ref above as it enables us to remove some code from Zotonic :)

**Comment by ddeboer** [comment]
Should we remove this from the 1.0 milestone?

**Comment by mmzeeman** [comment]
The only robust way to solve this is to use resolved symlink paths ourselves. Erlang lacks a call to `realpath(1)`, but I think we could write an erlang function which tracks back over a path and use `file:read_link/1` on symlinks.

**Comment by ddeboer** [comment]
Removing this from 1.0 as solving this issue shouldn’t introduce any BC issues.

Also, this issue has become a bit less pressing now that we ship with [Docker images](http://docs.zotonic.com/en/latest/developer-guide/docker.html) that contain a fully isolated Alpine-based Zotonic instance, with inotify enabled and working correctly.

**Comment by mmzeeman** [comment]
Indeed, this is just a bug, no BC issue.

Personally I don't use Docker (+ Virtualbox?), but indeed using Linux a workaround.

**Comment by mworrell** [comment]
I added a heuristic that should solve this issue in 6078f9f

**Comment by mworrell** [comment]
If this doesn't solve the issue, then please reopen.
