### ISSUE TITLE
Merge mod_geomap and mod_geo

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1122]
- Merge mod_geomap and [mod_geo](https://github.com/arjan/mod_geo) into one module.
- Keep that module in the Zotonic repository.
- Use OpenStreetMaps or Google Maps based on config value.

Benefits:
- Zotonic supports Google Maps out of the box.
- Less code/template duplication.

**Comment by mworrell** [comment]
:+1:

**Comment by mworrell** [comment]
When merging these, could we add some extra pivot using postgis (iff the extension is installed - something to check on startup).

**Comment by mworrell** [comment]
Mod_geo has been merged into zotonic/mod_geomap
