### ISSUE TITLE
Linking user groups should not require insert permissions on them

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1125]
When I give users link permission on user groups, those users still cannot do so. This is caused by an extra [`can_insert(acl_user_group, Context)`](https://github.com/zotonic/zotonic/blob/master/modules/mod_acl_user_groups/support/acl_user_groups_checks.erl#L385) which to me looks wrong. The use case where some users should not be permitted to edit user groups themselves, but should be able to assign users to groups, is quite common.

@mworrell Any idea why that check is there?

**Comment by mworrell** [comment]
Where is that check?

**Comment by ddeboer** [comment]
Click the link above to find out. :wink:

**Comment by mworrell** [comment]
Didn't see that it was a link :)

That check is there for extra security. Now it is very strict, the user must have:

  1. edit permission on the user group
  2. edit permission on the user
  3. link permission on the user group
  4. permission to insert user groups

We might want to make this less strict, I propose:

  1. link permission on the user group
  2. use permission on mod_acl_user_groups
  3. view permission on the user

**Comment by ddeboer** [comment]
I agree with that proposal.
