### ISSUE TITLE
Remove usage of deprecated md5_mac and sha_mac.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1126]
Already done on master

**Comment by ddeboer** [comment]
Do you mean we should cherry-pick those master changes into 0.13.x?

**Comment by mmzeeman** [comment]
Yes, i wanted to mark them before doing it. There doesn't seem to be a way to mark commits.

**Comment by ddeboer** [comment]
That’s correct. A solution is to commit into a separate topic branch and when you’re done squash all commits into one before merging the branch into master. That way, there’s only one commit you need to cherry-pick. :wink:

**Comment by mmzeeman** [comment]
This was just a single commit. But easily forgotten. I got called away into a skype meeting before I could paste the link of the commit.

https://github.com/zotonic/zotonic/commit/7c7e210cfee4e8ddee75f38dc5c8170ba3fd4bea

**Comment by ddeboer** [comment]
Awesome!

**Comment by mworrell** [comment]
Shall I cherry-pick that one?

**Comment by mmzeeman** [comment]
Fine by me :-)

**Comment by mworrell** [comment]
Done.

https://github.com/zotonic/zotonic/commit/da968aedb5ae088d1508381c27381aadd7514d27
