### ISSUE TITLE
Build documentation on Travis

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1128]
So we can test whether there are any invalid references etc.

**Comment by mworrell** [comment]
As far as I know the build process just continues in the presence of missing refs etc.

**Comment by mworrell** [comment]
We do build the edocs - as those give a failure we can test on.

**Comment by ddeboer** [comment]
What I’m used to doing is run sphinx (`make html`) on Travis and make the build fail if any errors are introduced in the docs.

**Comment by mworrell** [comment]
Best is to fix this on master, as there the current development is taking place.

Shall we set this to the 1.0 milestone?
