### ISSUE TITLE
Click-Jacking protection

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1132]
Zotonic doesn't have clickjacking protection.

https://www.owasp.org/index.php/Clickjacking

It would be nice if we have a feature where we can enable this. This might be important for admin consoles and other area's where users have to login.

**Comment by mworrell** [comment]
We can have controller_admin (and other admin controllers) add the relevant headers.

It could also be added as a kind of middleware module for the other controllers, where the headers are added if a config value has been set.

**Comment by mworrell** [comment]
@mmzeeman do we need extra things before closing this ticket? Any Javascript additions?

**Comment by mworrell** [comment]
Do we want more pages with protection or a more global switch, or is this enough for now?

/cc @ddeboer @arjan

**Comment by mmzeeman** [comment]
JS additions are needed when you want to support framing from specific domains as not all browsers (Chrome, Safari) support ALLOW-FROM.

It could be useful for sensitive parts where you have to login.

**Comment by ddeboer** [comment]
Good security improvements!

I’m not exactly sure how the `SAMEORIGIN` header works, but is there anything against adding it to all responses?

**Comment by mworrell** [comment]
@ddeboer Good question. It basically inhibits running inside an iframe. Which is not so good for @mmzeeman, who runs channel.me inside an iframe.

**Comment by mmzeeman** [comment]
Some of our clients do this. It has to be configurable.

**Comment by mworrell** [comment]
What is the behavior if the a page with `SAMEORIGIN` is opened inside an iframe?  Will it be hidden? Opening in a new tab? Some magic?

**Comment by ddeboer** [comment]
Has this issue been fixed appropriately by the commit shown above, or is more work to be done?
