### ISSUE TITLE
Error after update zotonic

### ISSUE THREAD

**Issue by imagency** [zotonic/zotonic#1135]
Hello, today I've made pull request from zotonic git repositiry:
git pull origin master 
with the last zotonic changes and after recompile zotonic I've got an error in Chrome:
GET 500 (Internal Server Error)

In zotonic debug mode I see such error:
[error] Error compiling template: <<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">> ({'EXIT',{function_clause,[{erlydtl_compiler,elif_ast,[{elif,{expr,"and",{expr,"not",{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,22},<<"pref_tz">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,17},<<"user">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,13},<<"acl">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,11},<<"m">>}}}}}}}}},{expr,"not",{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,70},<<"value">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,52},<<"timezone_is_fixed">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,47},<<"site">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,40},<<"config">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,38},<<"m">>}}}}}}}}}}}},[{text,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,76},<<"\nif (typeof(jstz) == \"object\") {\n\tvar ua_tz = jstz.determine();\n\tif (ua_tz.name() != '">>},{value,{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,32},<<"timezone">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,28},<<"req">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,26},<<"m">>}}}}}},[]},{text,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,41},<<"') {\n\t\tua_probe += \"&tz=\" + urlencode(ua_tz.name());\n\t}\n}\n">>}]},{{{tree,nil,{attr,0,[],none},[]},{ast_info,[],[],[]}},{treewalker,0,false,[]}},{dtl_context,[[{'$autoid',{tree,variable,{attr,0,[],none},'AutoId_qlpfdu'}}],[{'$autoid',{tree,variable,{attr,0,[],none},'AutoId_wcpeyp'}}]],{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[[<<"content">>|{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,[{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,6,18},<<"\n<div class=\"col-md-6 col-md-offset-3\">\n    <div class=\"jumbotron\">\n        <h1>">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,9,15},<<" Powered by ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,9,27},<<" <span class=\"zotonic-logo\"><em>Zotonic</em></span></h1>\n        <p>\n            ">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,11,15},<<" Welcome, visitor! The page you are\n            currently looking at is the default page for a\n            Zotonic web server. The fact that you are seeing\n            this page could mean that the website you are\n            trying to visit has not been configured\n            correctly. ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,11,304},<<"\n        </p>\n        <p>\n            ">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,14,15},<<" If you feel that you are here by mistake,\n            please hit the \"back\" button in your browser or\n            try a different address. If you are here to manage\n            this server, please enter the password below. ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,14,239},<<"\n        </p>\n    </div>\n</div>\n<div class=\"col-md-6 col-md-offset-3\">\n   <div class=\"panel panel-default\">\n        <div class=\"panel-heading\">\n            <h3 class=\"panel-title\">">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,21,39},<<" Enter your passwor...">>}},...]}]],...}}},...}],...},...]}})
12:52:03.910 [error] Error in process <0.1021.0> on node zotonic001@podzamok with exit value:
{function_clause,[{erlydtl_compiler,elif_ast,[{elif,{expr,"and",{expr,"not",{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,22},<<"pref_tz">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,17},<<"user">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,13},<<"acl">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,11},<<"m">>}}}}}}}}},{expr,"not",{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,70},<<"value">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,52},<<"timezone_is_fixed">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,47},<<"site">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,40},<<"config">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,38},<<"m">>}}}}}}}}}}}},[{text,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,9,76},<<"\nif (typeof(jstz) == \"object\") {\n\tvar ua_tz = jstz.determine();\n\tif (ua_tz.name() != '">>},{value,{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,32},<<"timezone">>},{attribute,{{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,28},<<"req">>},{variable,{identifier,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,26},<<"m">>}}}}}},[]},{text,{<<"/home/zotonic/zotonic/modules/mod_base/templates/_ua_probe.tpl">>,12,41},<<"') {\n\t\tua_probe += \"&tz=\" + urlencode(ua_tz.name());\n\t}\n}\n">>}]},{{{tree,nil,{attr,0,[],none},[]},{ast_info,[],[],[]}},{treewalker,0,false,[]}},{dtl_context,[[{'$autoid',{tree,variable,{attr,0,[],none},'AutoId_qlpfdu'}}],[{'$autoid',{tree,variable,{attr,0,[],none},'AutoId_wcpeyp'}}]],{dict,7,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[[<<"content">>|{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,[{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,6,18},<<"\n<div class=\"col-md-6 col-md-offset-3\">\n    <div class=\"jumbotron\">\n        <h1>">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,9,15},<<" Powered by ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,9,27},<<" <span class=\"zotonic-logo\"><em>Zotonic</em></span></h1>\n        <p>\n            ">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,11,15},<<" Welcome, visitor! The page you are\n            currently looking at is the default page for a\n            Zotonic web server. The fact that you are seeing\n            this page could mean that the website you are\n            trying to visit has not been configured\n            correctly. ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,11,304},<<"\n        </p>\n        <p>\n            ">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,14,15},<<" If you feel that you are here by mistake,\n            please hit the \"back\" button in your browser or\n            try a different address. If you are here to manage\n            this server, please enter the password below. ">>}},{text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,14,239},<<"\n        </p>\n    </div>\n</div>\n<div class=\"col-md-6 col-md-offset-3\">\n   <div class=\"panel panel-default\">\n        <div class=\"panel-heading\">\n            <h3 class=\"panel-title\">">>},{trans,{trans_text,{<<"/home/zotonic/zotonic/priv/sites/zotonic_status/templates/logon.tpl">>,21,39},<<" Enter your password to manage this ser...">>}},...]}]],...}}},...}],...},...]}

**Comment by mworrell** [comment]
Did you recompile the .yrl file?

We added an extra option there and changed the syntax tree for if and elif expressions.

- Marc

**Comment by imagency** [comment]
Hello, Marc, what I did:
git pull origin master 
zotonic stop
zotonic compile
zotonic start
is that not enough for recompile all zotonic files?

**Comment by mworrell** [comment]
Rebar places erlydtl_parser.erl on two different spots, depending on the version of rebar. 

Can you check the dates of that file and the .yrl file? Or otherwise touch the yrl file?

- Marc

**Comment by imagency** [comment]
The last modification date of file
/home/zotonic/zotonic/src/erlydtl/erlydtl_parser.yrl 
is 11.01.2016
and file
/home/zotonic/zotonic/src/erlydtl_parser.erl 
is modified 27.11.2015, so it is not modified today.

And there is no file erlydtl_parser.erl in /home/zotonic/zotonic/src/erlydtl/ directory.

**Comment by mworrell** [comment]
Strange, you can remove the .erl version and try to make a new one with "make"

**Comment by imagency** [comment]
Thanks, Marc! I followed your advice. With a happy result. Everything works fine now.
