### ISSUE TITLE
Zotonic 1.0

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1138]
In our meeting today between @arjan, @mworrell, @mmzeeman, @fredpook and myself, we decided the following concerning the 1.0 release.
- 1.0 is not about features, performance, tests or documentation. Instead, it is a chance to introduce BC breaks that we will have to live with for a while: at least until 2.0, following [semantic versioning](http://semver.org).
- Therefore, the 1.0 milestone should _only_ contain items that will introduce BC breaks.
- It then comes down to three things: 
  - swap the webserver (excluding HTTP2)
  - use binaries instead of lists
  - check whether the current MQTT implementation is future-proof.

We will not forget about all cool features and other improvements, but they will be introduced in 1.\* minor versions; 1.0 does not depend on them.

@mworrell Let’s start cleaning up the 1.0 milestone. :wink:

**Comment by ddeboer** [comment]
Just cleaned up the 1.0 milestone together with @mworrell.

**Comment by mworrell** [comment]
Closing issue - milestone has been cleaned up and further release planning is on its way.
