### ISSUE TITLE
Improve admin pages overview with sort menu

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1140]
Currently the sorting possibilities are just the column headers  
"Title" "Category" "Created on" "Modified on" "Modified by"
and "Modified on" is the default

When you search for a text sorting on relevancy is expected but there is no header or UI for this.

Proposal is to add a UI dropdown for sorting on the top right
![admin_order](https://cloud.githubusercontent.com/assets/5276922/12266881/d2f52464-b945-11e5-8c9c-aee4d975c978.png)
between category dropdown and page length dropdown.
1 with the sort options
and 1 with asc/desc

The sort options can be
- relevancy
- title
- modified on
- modified by
- created on
- created by
- publication start
- publication start
- date start
- date end
- first name
- last name
- unique name
- id

**Comment by mworrell** [comment]
There is now a sort in the search panel.
We could add more options when needed.
