### ISSUE TITLE
Pass qargs to search

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1147]
As discussed with @mworrell: `pager` [supports a `qargs` argument](http://zotonic.com/docs/latest/ref/scomps/scomp_pager.html) that “Append[s] all the arguments in the HTTP request’s query string whose name starts with a ‘q’ as an argument to the dispatch rule.”.

We need this argument for `search` as well in order to pass complex search facets to the backend (for instance, multiple `hassubject` or `subject` edges).

cc @loetie @dirklectisch

**Comment by ddeboer** [comment]
@mworrell Is this a duplicate of https://github.com/zotonic/zotonic/issues/975#issuecomment-171324594?

**Comment by Dirklectisch** [comment]
@mworrell Is this one done?

**Comment by mworrell** [comment]
This has been done in 86ff3e686b5794b217fa10ab32cf36b773bab11d
