### ISSUE TITLE
Show 403 page instead of redirect to the login page on access-denied

### ISSUE THREAD

**Issue by alvaropag** [zotonic/zotonic#1148]
Using the option {acl, {edit, my_page_id}} in the dispatch rules causes a redirect to the login page when a user that don't have permission to edit a page try to do it. I'd like to be able to intercept this redirection and show some template/message telling the user he doesn't have permission to execute this action.

Talking with @mworrell via email he suggested 

-------------------------------------------------------------------------------------------

Recently I was also thinking that we should be able to show the same template but then with an error message.

Or at least not change the url.

For other errors we now use a controller_error, which doesn’t change the url and displays a different html page.
On that page we can then just add the “log on” button and some explanation.

Looking at the code the problem is that the z_acl:wm_is_authorized/2 function wants to redirect.
We might want to add an option to throw/return an access denied error - which can then call controller_error.

It is in this code:

> %% @doc Convenience function, check if the current user has enough permissions, if not then
> %% redirect to the logon page.
> -spec wm_is_authorized(boolean() | acl(), #context{}) -> webzmachine:reply().
> wm_is_authorized(true, Context) ->
>     ?WM_REPLY(true, Context);
> wm_is_authorized(false, Context) ->
>     wm_is_authorized(false, logon, Context);
> wm_is_authorized(ACLs, Context) when is_list(ACLs) ->
>     wm_is_authorized(ACLs, logon, Context).

And here:

> wm_is_authorized(false, Redirect, Context) ->
>     ContextLocation = wm_set_location(Redirect, Context),
>     ?WM_REPLY({halt, 302}, ContextLocation);

=============================================================
So, what is the best alternative? Redirect to controller_error? Show the same page with an error? Redirect to a custom template?

**Comment by mworrell** [comment]
I think it should be ok to now *not* redirect but show a 403-like page, with the option to log on. This page can be changed to do the actual redirect.

If Javascript redirects then we can also keep the hash-part of the url in tact during the login (as we don't see the hash-part of the url on the server).

Pulling in some others.

@ddeboer @mmzeeman @arjan

**Comment by mmzeeman** [comment]
Sounds like a plan. When somebody is already logged in it doesn't make sense to show the logon page anyhow.

**Comment by mworrell** [comment]
Indeed, good point. It is quite confusing to show the login page if somebody is already logged on. At least in a template we can tell what is wrong and offer the possibility to go back or log on as a different user.

**Comment by ddeboer** [comment]
:+1: on the fix
