### ISSUE TITLE
Use MQTT for TPL/ERL decoupling

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1158]
There‘s lot of micro-coupling between .tpl and .erl files: Erlang `z_render`ing into specific div ids, for instance. 

@mmzeeman I guess we can use `{% live %}` with MQTT for proper decoupling between templates and server notifications/events. However, I haven’t yet found a way to pass template variables back from my MQTT publisher. 

So something like:

``` django
{% live template="_my_template_that_needs_some_params.tpl" topic="~site/bla" %}
```

And then publish to `~site/bla` publisher with some tuples as payload: `[{ding, <<"dong">>}, …]` that are then rendered in  `_my_template_that_needs_some_params.tpl`:

``` django
{{ ding }}
```

Should this be possible? If not, why not? Is it unsafe? Or am I being crazy?

**Comment by mmzeeman** [comment]
Interesting. Yes, we must do something in that area.

The live scomp is currently a bit simplistic, so improvements are not that far fetched.

Another, more generic possibility is:

```
{% wire type={mqtt topic="~site/bla"} action={..} postback={..} %}
```

I recently changed this to pass js args in a publish message on the page back to zotonic. 

Do you have a specific use case with such a tpl/erl coupling? It might give some clues to work on something real.

**Comment by ddeboer** [comment]
My use case: search on an external API that returns both results (`#search_result{}`) and dynamic facets based on those results. 

1. One search query to the API will publish to (for instance) `~site/api-search-result`.
2. A `results.tpl` subscribes to it to render search results.
3. A `facets.tpl` listens to it to render facet input elements.
4. When the user clicks facet input elements or enters text, a new query must be executed. The `facets.tpl` could itself publish to `~site/api-search-query`.

**Comment by mmzeeman** [comment]
For the facets part you need to be able to update things carefully. The current live scomp will simply overwrite the local page state of the input elements.

@mworrell and me are thinking about how to handle this. Nothing concrete yet. 

For channel.me I now use mithril based components on the page. This approach works, but is not very easy. We really miss the ease of use of templates. 

I would really like to experiment with https://medium.com/google-developers/introducing-incremental-dom-e98f79ce2c5f#.b41sg1alt. That would allow us to write dynamic js things with our current templates. Rendering html, for the quick first view, and js, to allow dynamic updates from the same template. The template then can use server and page based actions, models and pub-sub.

**Comment by mmzeeman** [comment]
Maybe it is an idea to arrange a meeting on this subject? There are a lot of new developments on this subject outside zotonic's world too. New frontend languages like typescript, purescript, elm are emerging because the code on the client side is getting more and more complex. New js frontend libraries like React/Angular/Mithril. All needed in order to make more dynamic interactive webpages/spa's. What do these developments mean for CMS's? What direction should zotonic take? Ping @mworrell @arjan

**Comment by ddeboer** [comment]
Good idea. I started looking at MQTT right away, but there may be different and possibly better solutions to the general problem of client (JS)/server-interaction.

**Comment by mworrell** [comment]
The `live` scomp accepts `topic` arguments.
Also works on master.
