### ISSUE TITLE
Importing CSV file with CR line breaks doesn’t work

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1160]
When importing a CSV File with CR line breaks (`\r`) all rows are erroneously concatenated into one list so no data gets imported. No error is thrown either. When I convert my file to LF (`\n`) line separators, the import works fine. 

So: should we look for and automatically convert non-LF line separators (also CRLF) to LF or document that only LF line breaks work?

**Comment by mworrell** [comment]
Interesting, are you using an old-fashioned Mac editor that uses *cr* line breaks?

It is ok to make some changes to this - we can accept all of them, but need to be careful in handling to not add empty lines. We can *snif* which line breaks are used and then stick to them or just accept any mix of line break characters (ascii `13,10`, `10` or `13`).

Though I vaguely remember a project that uses the *cr* for newlines in fields. I think we shouldn't support that though. @arjan
