### ISSUE TITLE
Change tag naming scheme to ‘0.13.7’ (instead of ‘release-0.13.7’)

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1161]
We have [decided](http://zotonic.com/docs/latest/dev/releasing.html?highlight=release%20schedule#schedule) to name our stable release branches `release-0.13.7`. However, that name will conflict with our current tag naming scheme (which would yield `release-0.13.7` for the tag as well). Git then gives:

```
warning: refname 'release-0.13.7' is ambiguous.
```

So I propose to rename our tags to just the number (`0.13.7`) while for now keeping `release` in our branch names. This is what most other OSS projects are doing too. Of course renaming old tags is a no-go, so we should only do this from `0.13.7` onwards.

Is anyone opposed to this?

**Comment by mworrell** [comment]
Sounds good to me - also a bit clearer (and more following other projects).

/cc @arjan

**Comment by arjan** [comment]
:+1: :)

**Comment by ddeboer** [comment]
We’ll be using the new tag names from 0.13.7 onwards.
