### ISSUE TITLE
Make ssl redirect optionally 301

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1164]
I have implemented https using mod_ssl. I am seeing that the http urls get redirected with a 302. I remember the discussion we had on #1094 but here I would like to have the url location permanently at https.

So this is a request to make the redirect configurable. Possibly by using a config setting:

```
mod_ssl.is_permanent: true/false
```

**Comment by ddeboer** [comment]
@ArthurClemens Do you have time to work on this?

**Comment by mmzeeman** [comment]
I can also do it if you like.

**Comment by ArthurClemens** [comment]
:thumbsup:
