### ISSUE TITLE
validator date error

### ISSUE THREAD

**Issue by masteroy** [zotonic/zotonic#1165]
I use validator date well in version 0.13, but when I upgrade my zotonic to 1.0-dev, I found that it always print "please correct".
I trace the code, and found that the Validations in z_validation:validate/2 is  [{date,validator_base_date,[<<"b">>,"-"]}] in 1.0-dev and [{date,validator_base_date,["b","-"]}] in 0.13.
the <<"b">> will always match false in validator_base_date:validate/5
I think it must be something change when the browser pickle the validator before post to the sever, but I'm not good at JavaScript
forgive my poor English

**Comment by mworrell** [comment]
Thanks for this report and the digging!

The master (1.0-dev) is undergoing what we call *the binaryficaton*. That is that more and more values are passed as binaries. I think this is a victim of that and needs to be fixed.
