### ISSUE TITLE
Documentation mentions resource instead of controller..

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1166]
http://zotonic.com/docs/0.13/cookbook/frontend-contactform.html

*Via @heiheshang in zotonic/zotonic from gitter*

**Comment by ddeboer** [comment]
Do you mean `resource_default_contact`? Not sure that it should be a controller either. An action might be better?

**Comment by heiheshang** [comment]
I just tried the example

**Comment by mmzeeman** [comment]
Now I am confused too. We used to call controllers resources because we call our rsc's resources. I thought this example was still using the old naming scheme. This is also something different as an action.

Where should one put an event handler like this? Usually I put it in the module or site's module.

**Comment by mworrell** [comment]
Maybe best to make it an event handler in the site module?  
Let’s call it *yoursite* and give some explanation.

That resource name is very confusing.

**Comment by heiheshang** [comment]
that's exactly what I did

**Comment by ddeboer** [comment]
> Maybe best to make it an event handler in the site module?

I prefer not to do this where possible as the site module is usually already one of the largest modules. To improve code organisation, I push as much as possible out of the site module into separate, dedicated modules. A contact form is a good use case for this. 

> This is also something different as an action.

Why?

**Comment by mworrell** [comment]
Regarding action: this is just a simple postback *do something with this form*.

I agree encouraging people to add an Erlang module in `.../yoursite/support/yoursite_contact_form.erl`, that would help with teaching the preferred code organization.

(Until we make everything OTP compatible... then we have to move directories around, but that is for Zotonic 2.0 :roller_coaster:  )

**Comment by mmzeeman** [comment]
Because an action is a module which renders something in the browser and is also selected by the priority mechanism.

**Comment by mworrell** [comment]
BTW I saw that the `blog` skeleton adds an Erlang module with a fixed name to every generated site. We have to change that.

**Comment by mmzeeman** [comment]
It would work if the form action would render the usual stuff for forms. Then you could easily priority override handling the form.

**Comment by ddeboer** [comment]
> Because an action is a module which renders something in the browser and is also selected by the priority mechanism.

You’re right. I would add: an action is re-usable while handling the contact form submission is probably specific to that one contact form and its inputs. By the way, in the [current docs](http://zotonic.com/docs/latest/manuals/templates/actions.html#manual-template-actions) actions are defined only very vaguely:

> Actions are the basis of all interactivity on a Zotonic web page. (…) A wire indicates that something should happen when the wire is triggered. What should happen, is specified as the action.

**Comment by ddeboer** [comment]
> `.../yoursite/support/yoursite_contact_form.erl`

So do we agree on this as the solution for the contact form chapter? So not some kind of controller in `controllers/`.

**Comment by mmzeeman** [comment]
There are actions with a postback event handler btw. `action_base_logoff` is an example.

Having an example with your_site stuff in it is also not so nice as you can't copy paste it in your codebase.

**Comment by mmzeeman** [comment]
Looking back at the recent gitter and mailinglist questions it helps if we have better feedback for new users too. Error messages on eaccess and maybe other things like a descriptive message when a form is posted to /postback? (forgot wire your form?)

**Comment by mmzeeman** [comment]
Having examples with `your_site` in it will make the descriptions vague too.  A lot of users expect examples to work immediately and start with tinkering *after* they got the example working.

**Comment by ddeboer** [comment]
> it helps if we have better feedback for new users too

Definitely a good idea. Not directly related to this issue, so created a new one: #1167.

**Comment by ddeboer** [comment]
@mmzeeman Do you have a suggestion what we should instead of `your_site`? Just leaving it out won’t work for the dispatch rules part of this cookbook, for instance. Or replace it with something more real, such as `blog`?

**Comment by mmzeeman** [comment]
I'll think about it. What I usually see is that new users tend to copy paste things and expect it to work before having to edit things.

**Comment by mworrell** [comment]
Maybe we should have a default `testsite` site out of the box?
