### ISSUE TITLE
Don't scan hidden files and directories within sites and modules

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1175]
Zotonic has the tendency to scan all directories within sites and modules. This gives some problems for example when there is a config file inside. See the following error example:

````
10:27:22.122 [error] Could not consult site config: /vagrant/sites/.bundle/config: 1: syntax error before: '--'
````

Please ignore stuff beginning with a dot `.`.

**Comment by mmzeeman** [comment]
*Scanning vagrant's synced folders is also very slow.*

**Comment by mmzeeman** [comment]
Erlangs `filelib:wildcard/1` includes files and directories which start with dots. This is usually not what one expects because unix wildcards skips them. I've a patch ready with a unix like wildcard function. This causes all directories with dotfiles to be skipped from scans.

**Comment by mworrell** [comment]
:+1:

**Comment by Dirklectisch** [comment]
Thanks for the super fast fix!
