### ISSUE TITLE
Strange sasl message at zotonic boot time

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1176]
When zotonic starts the following message is logged.

```
11:00:46.961 [error] Unable to read boot script (start_sasl.script): {error,enoent}
```

and it looks like this also causes an extra directory named `log.zotonic001@Buka` to be created. 

Is there something wrong with the order things are started?

**Comment by ddeboer** [comment]
Yeah, we’re seeing this to. I think @mworrell mentioned this was due to a dep on master. @mworrell Do you remember which one?

**Comment by mworrell** [comment]
Yes, `setup`.  I also saw it mentioned on the Erlang mailinglists.

**Comment by mworrell** [comment]
Not seeing this on master anymore, might have been fixed in the config or in `setup`.
