### ISSUE TITLE
Notified datamodel

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1178]
When working on #1173 I found that we need a separation between `manage_schema` handling in Zotonic’s core on the one hand and modules that can handle certain types of datamodel entries (such as acl rules) on the other.

As discussed with @mworrell today, we propose to:
* extend `#datamodel{}` with an extra record field `notify` or something similar
* `z_datamodel` throws a first notification with the content of the `notify` list as an argument
* modules observe the notification to persist the `notify` datamodel entries.

**Comment by mworrell** [comment]
I would propose to have a separate notification for each 'notify' element.

Something like:

```
z_notifier:first(#datamodel_notify{module=..., datamodel=..., notify=...}, Context)
```

Where `notify` would contain the single element from the `#datamodel.notify` list.
