### ISSUE TITLE
zotonic_setup doesn't skip commented user_modules_dir and user_sites_dir

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1181]
The zotonic scripts are all initialized by `src/scrips/helpers/zotonic_setup`. This shell script prepares environment variables to run zotonic scripts. It has to consult `zotonic.config` to see where the users site and module dirs are. This script doesn't recognise commented out values in the proplist and silently uses the commented out values.

**Comment by mworrell** [comment]
I am seriously considering to redo these scripts in erlang or escript.
That would fix many cross-server issues and also make the maintenance commands easily accessible to the Erlang system.

**Comment by mmzeeman** [comment]
:+1:

Another thing I would like is the ability to add custom scripts which are integrated with zotonic. 

```
$ zotonic do_custom_thing
```

I think I'm going te make a simple escript which can consult and query an erlang config file to fix this.

**Comment by mmzeeman** [comment]
Fixed  by https://github.com/zotonic/zotonic/commit/f471359eb5566a55abb2c45e539aa5e70b81031b
