### ISSUE TITLE
Brute force password hack protection.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1190]
Some sites contain sensitive information. For these environments it is usually required to have brute force password guess protection.

**Comment by mworrell** [comment]
Yes we need to look into this.

Are there any known working method that are consuming acceptable memory relative to the number of tries/accounts?

We need to track at least:

 * Password errors per user (till succeed)
 * Password errors per IP address

This is very doable with quick tries, though a bit harder for slower brute force attacks (as the amount of administration will rise quite a bit).

The per-user error count can be stored in a table. Inclusive information about the last successful attempt(s).

The per-ip might be a held in a circular buffer, or in a hash table that we periodically flush.
Any block could be added to an in-memory hash table, that is also periodically flushed (including a log entry to some table, which could be used for a more permanent block).

This would add the following use cases:

 * Consume last two successful logons
 * Register new successful logon
 * Consume block-flag for an ip address
 * Consume block-flag for an user account
 * Register failed logon ip address
 * Register failed login user account (including non-existing?)

**Comment by mmzeeman** [comment]
Other important things to keep in mind.
 
 * When security gets more important audit logs are usually required too.
  * Hack reports to maintainer, possibility to install a blocks automatically.
  * Configurable maximum on the number of failed login attempts.
  * Registration of successful logins.
  * Security on IP level. Limit some of the functionality based on ip-address.
  * Session hijacking protection based on another mechanism than session cookies. (a pickled session-id containing the ip of the browser, local-storage with a shared secret used on transport messages)

**Comment by ArthurClemens** [comment]
I believe it is fairly common practice to have an increasing response delay for each unsuccessful login attempt.

**Comment by CyBeRoni** [comment]
> Password errors per user (till succeed)

Keep in mind that locking the *real* user out is not typically a desired outcome of brute-force protection.

> Are there any known working method that are consuming acceptable memory relative to the number of tries/accounts?

An IP is either 4 (IPv4) or 16 (IPv6) bytes so it may not be worth to spend too much time optimising that. Though for that latter case, you want to not match on the specific IP but rather the /64 so you could reduce it to 8 bytes easily.

**Comment by mworrell** [comment]
To prevent locking out the real user we might be a bit more lenient if the access comes from an IP address that the user used before (for successful logins).

**Comment by mworrell** [comment]
Anyway, someone, somewhere, has probably a good implementation already. We should find a good example and port that over.

**Comment by mmzeeman** [comment]
A client requested us to implement it like this:

  1) Block the user-account after N failed login attempts.
  2) When the account is blocked users can use the reset-password functionality. When the password is successfully reset, the account is deblocked.

Blocking a user introduces a new state in user-accounts, but I like the idea. To do this we only have to introduce an error-count per user which is reset after a succesful login.

They also wanted us to implement more elaborate password restrictions. Like mixing numbers, small-caps, caps, and special chars, and a restriction that new passwords should not be the same as the last 4 passwords and not be the same as the username.

They also want audit logging for user account mutations and login attempts. (stored for 2 months)

**Comment by CyBeRoni** [comment]
>  Like mixing numbers, small-caps, caps, and special chars, and a restriction that new passwords should not be the same as the last 4 passwords and not be the same as the username.

Old-fashioned thinking to the max. (Except that last part -- that's just common sense.) 

I think password entropy is much more important -- satisfiable either by making your password more random or by increasing its length. A simple, but long, password, is typically more secure than a difficult but short password.

**Comment by ArthurClemens** [comment]
Agreed. XKCD explains it well:
https://imgs.xkcd.com/comics/password_strength.png

**Comment by crownedgrouse** [comment]
Hi, is there also protection against SQL injection in Zotonic ?

A good practice with postgresql is to use dollar quoting  with random string identifier : 

`UPDATE users SET password=$E1234$newhash$E1234$ WHERE code=14587 ;`

where E1234 is a randomly chosen string at SQL request time, so that attacker cannot guess what it will be and so cannot try to do SQL injection by inserting '  or $$ in login stage ...

**Comment by mmzeeman** [comment]
I wonder how many of our users would understand the warning "Please increase the entropy of your password". ;-)

**Comment by crownedgrouse** [comment]
on the main subject, what about give a fail2ban log filter  ereg and let the job be done by specialized tools ?

**Comment by ArthurClemens** [comment]
"Please read this comic, then create your password."

**Comment by crownedgrouse** [comment]
some more reasons to use external tools : 

- this avoid reinvent the wheel
- zotonic does not run as root, so hard to apply iptable or write in  hosts.deny  . 
- easy to write an 'apache' like log for authentification, and easy to create or reuse fail2ban filters (or equivalent) tools for security
- zotonic run generally behind a proxy (nginx ...) that probably already used those tools.

**Comment by crownedgrouse** [comment]
one more : 
- external tool allow to protect the whole machine and other services on the same machine from rogue IP, while doing it inside Zotonic only protect Zotonic.

**Comment by mmzeeman** [comment]
@crownedgrouse Yes there is sql protection. Passwords are never stored, what we store instead are bcrypt password hashes.

We also don't like to rely on external tools. I don't run zotonic behind nginx because this tends to duplicate response times and complicates the server setup. 

Users also want feedback on when their account is blocked and from what location possible brute force attempts are coming from. So the information from the external tools has to flow back into zotonic. They need have to have some feedback.

I think we should make it possible to implement different ways of dealing with this. It would be nice if a zotonic notification would be fired after a failed and successful logins. That information can be used by custom modules which can handle this outside the core of zotonic. It seems that everybody wants to have a slightly different way of dealing with issues like these. 

This issue is also related to #1732

**Comment by mworrell** [comment]
Maybe use a bloom filter?  An example is described in the paper ("Data Sketching", by Graham Cormode) http://queue.acm.org/detail.cfm?id=3104030

**Comment by crownedgrouse** [comment]
@mmzeeman  no problem, it is your product, but this is maybe not the case for company using those tools, so even if this can be handled inside zotonic, I think it would be smart to generate an 'apache' like log, to allow people create their own filter and use their own tools. 

On SQL injection, it is not only a password matter. Can a user allowed to create page, let say by modifying a text field, do a SQL injection ?  As far code is opensource, easy to know the database structure and do  "  ; update xxxxx set yyyyyy='zzzzz' ;"  in afield ?

**Comment by mworrell** [comment]
Per SQL injection: we use parametrized SQL queries, so PostgreSQL takes care of this.

**Comment by mmzeeman** [comment]
@crownedgrouse There already is an apache like log. You can find at in priv/log/access. Another thing is that ip-level blocking is not always handy. Some of our customers login with entire office from behind one ip-address. An automatic block would lock out all users of the entire office.

**Comment by crownedgrouse** [comment]
hum, I forgot priv/log/access indeed. So easy to add external tool if needed.
I undestand that ip-level blocking can be a bit raw in the case you mentionned above. But a smart attacker will do a round robin on a set of username login  with potentially a long time between attempts.
So not easy to detect a brute force attack then. So even you want zotonic to handle security , a global counter for fail login must be kept per IP-address in order to block this IP whatever le username used.
MHO

**Comment by crownedgrouse** [comment]
And by experience, many login failure on a same username, from same IP, it is probably the real user that lost its password ! :) ... humour

**Comment by CyBeRoni** [comment]
> I wonder how many of our users would understand the warning "Please increase the entropy of your password". ;-)

Obviously, not many. But they all understand the UI that's been created for exactly this which tells them their password is 'weak', 'strong' or somewhere inbetween. Those things tend to use entropy to gauge strength.

**Comment by mworrell** [comment]
I agree that a gauge/flag is better - as I hate it when my randomly generated password is not accepted because it is missing some funky character.

**Comment by mworrell** [comment]
`mod_ratellimit` protects against brute force password attacks and repeated password reset requests.
