### ISSUE TITLE
pubzub.subscribe also acks on {error,eacces}

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1193]
When subscribing to server topics from javascript I noticed the ack function is also called when the users does not have permission to subscribe to the topic. It means that the subscribe operation has completed, not what the result was.

Should we change this so it comes more inline with the mqtt spec and use success and failure response codes for this?

**Comment by mworrell** [comment]
Yes :+1: 

I vaguely remember that those response codes are quite new, aren't they?  But we should mimic the real MQTT behavior here.

**Comment by mworrell** [comment]
Client side `PubZub` has been replaced with cotonic (on master).  Closing this issue.
