### ISSUE TITLE
mod_custom_redirect appears non-functional for hostnames

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1196]
mod_custom_redirect allows setting up hostnames to redirect to other places. That is currently (0.13.7) non-functional. Adding an entry with a hostname to the table, with or without a path, and then navigating to that url gives the zotonic status page as if the hostname is not recognised.

Adding only a path does function correctly.

**Comment by mworrell** [comment]
According to @CyBeRoni this has been fixed in https://github.com/zotonic/zotonic/commit/845641dc5ba4f840999e530af30576c04dcfbfd9
