### ISSUE TITLE
Erlang's default DH key parameters are weak.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1198]
The default 1024 bit Diffie Hellman key used in Erlang is found to be weak by http://www.ssllabs.com.

This can be fixed by passing another key via the openssl options. `{dh, public_key:der_encoded()}` or `{dhfile, path()}`.

We need to either need to add our own default key, or let mod_ssl generate a dh key before it starts instead of using the default key and pass the filename of that key. 

See also: http://ezgr.net/increasing-security-erlang-ssl-cowboy/

Generating a separate key dh key for each installation looks like the way to go. Ping @marc, what do you think? Probably also something for the upcoming milestone.

**Comment by mworrell** [comment]
I am for generating a separate key per install.

**Comment by mworrell** [comment]
Should we merge this in the 0.13.x as well?

**Comment by mmzeeman** [comment]
Yes, doing that now.
