### ISSUE TITLE
Leap year error during static files request.   

### ISSUE THREAD

**Issue by LilDash** [zotonic/zotonic#1202]
Zotonic crashed with this error:  `{badarg,[{erlang,universaltime_to_localtime,[{{2017,2,29},{2,13,1}}],[]}`

The code :  `{{{Y+1,M,D},HIS}, ReqData, State};` in the controller_file.erl(line 105)  makes leap year error during static files request.

**Comment by mworrell** [comment]
Wow, that its embarrassing. Thanks for the fix!

**Comment by mworrell** [comment]
A hotfix release was made to handle this issue https://github.com/zotonic/zotonic/releases/tag/0.13.8

**Comment by mworrell** [comment]
@LilDash Thanks again for reporting and fixing this.

**Comment by LilDash** [comment]
my pleasure : )
