### ISSUE TITLE
Release numbering

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1204]
I propose the following changes to the pre-1.0 release numbering so we start getting used to [semantic versioning](http://semver.org/).

1. Increase the minor (instead of patch) number for all monthly releases, so 0.13.9 will become 0.14.0 instead; next month 0.15.0, etc.
2. Rename the current dev branch (`release-0.13.x`) to `0.x`. If we need to keep a branch alive (e.g. for Bootstrap BC), we rename it to `0.15.x`.
3. Hotfixes, such as today’s leap year error, will get patch numbers (0.15.1).

**Comment by mworrell** [comment]
:+1:

**Comment by mmzeeman** [comment]
:+1:

**Comment by ddeboer** [comment]
Just pushed branch `release-0.x`, based on `release-0.13.x`. Please continue working on `release-0.x`; I’ll delete `release-0.13.x` tomorrow.

**Comment by mworrell** [comment]
Go, go, go!  :+1: 

I just mailed the mailinglist to explain these changes and our release schedule.

**Comment by ddeboer** [comment]
Just deleted `release-0.13.x`. I’ve added Semver numbering to the docs, too: #1209.
