### ISSUE TITLE
DPI setting for generated PNGs

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1205]
Just had a problem with PNG images in emails.
Mac OS X Mail adheres to the DPI setting in the images when displaying images.
The generated PNGs had 144DPI, so they were displaying too small.

We should remove the DPI information (or set a sensible default) when generating PNG previews.

**Comment by arjan** [comment]
Imagemagick has a -strip option to remove all metadata, that should be
enough I guess.

**Comment by mworrell** [comment]
Just checked - doesn't seem to remove it.
The options `-set units PixelsPerInch -density 72` seem to set a good default though (screen shots on OS X are also 72dpi)
