### ISSUE TITLE
Inconsistent URI property behaviour

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1207]
Setting and retrieving the URI property works rather inconsistently:

```erlang
> m_rsc:update(102, [{uri, <<"http://dinges.com">>}], z_acl:sudo(C)).
> m_rsc:p(102, uri, C).
<<"http://mywebsite.dev/id/102">>
```

But:

```erlang
> proplists:get_value(uri, m_rsc:get_visible(102, C)).
<<"http://dinges.com">>
```

Same goes for editing the ‘Unique URI’ field in the admin.

**Comment by mworrell** [comment]
The semantics of the `uri` are a bit tricky. 

For *non authoritative* uris we use the `uri` property.
For *authoritative* uris we generate the resource's non-informative uri using the `id` dispatch rule.

This makes setting/retrieving the uri indeed inconsistent.
Maybe we need an alternative `resource_uri` property (or something similar) for the *computed* uri.

**Comment by mworrell** [comment]
If we change this behavior then we do need to check templates and code, as the `uri` property is probably used to fetch the non-informative uri.
