### ISSUE TITLE
Build docs for 0.14

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1210]
We released 0.14.0 today, but 0.14 is not displayed on http://zotonic.com/docs. I couldn’t find any configuration in the repository for which branches we build the docs. Is this something that is determined by the script that listens to the `http://www.zotonic.com/api/zotonicdocs/make` webhook?

**Comment by mworrell** [comment]
Found it.  It is in the zotonicwww project, the priv/build.sh script.

> DOCBRANCHES="release-0.13.x master"


Which we clearly need to set to something else.

- Marc

**Comment by ddeboer** [comment]
We do indeed. Any suggestions as to where? :wink:

**Comment by mworrell** [comment]
Maybe just a 0.x documentation and remove all older docs?

/cc @kaos @arjan

**Comment by arjan** [comment]
:+1:

**Comment by ddeboer** [comment]
@arjan You set up the doc build originally, correct? Do you have some time to look into this?

**Comment by arjan** [comment]
I updated the build script and changed the doc sidebar, removing links to old documentation versions.

Docs are now built for the `0.x` and `master` branches only; http://zotonic.com/docs redirect to the stable docs, http://zotonic.com/docs/0.x/index.html.

**Comment by ddeboer** [comment]
Yeah, awesome! Much better now. Cheers! 😄
