### ISSUE TITLE
Private details of person records

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1211]
We have ACL checks on property access.
The ACL property checks are not implemented by the current standard shipping modules.

With the enhancements to mod_export it is now easy to export email addresses of publicly viewable people.This is unwanted behavior.

With @ddeboer we came to the following idea, which needs some feedback and details filled in.
We make a new ACL module that adds some property checks for person records.
- Not expose `email`, `address_...`, `phone`, geo-locations and `date_start/end`.
- The address fields in `mailing_...` are exposed.
- An extra email fields `mailing_email` should be added (and also phone?)

Besides that we will need some settings in the record itself to toggle the privacy level of this information.

We need to think of indexing, normally we index everything. Not indexing the private properties will hide these from search results, this is both wanted and unwanted.

/cc @arjan @michielklonhammer @mmzeeman

**Comment by mworrell** [comment]
Ideas for indexing:

 * Do not index private address information and email (email can also be found via the identity tables)
 * Round geo location to within a couple of kms from the real address

**Comment by ddeboer** [comment]
Agreed, on the indexing approach as well. 

How do we determine who gets to see the private details? Use access to the new mod_protect_identity (or something similar)?

**Comment by mworrell** [comment]
I think we can hide the properties in the `mod_acl_user_group`, if an user has 'edit' permission then the user should be able to see everything. Properties in the record can change the level of privacy, with a different default for `person` categories than for other categories.

**Comment by ddeboer** [comment]
Makes sense: then we don’t need the extra module. 

@fredpook Any thoughts?

**Comment by ddeboer** [comment]
#1224 should solve this at least partly.

**Comment by ddeboer** [comment]
Any more work to be done here?

**Comment by mworrell** [comment]
Yes - we need to come to a final decision on this.

**Comment by mworrell** [comment]
I am now looking into a couple of privacy levels:

 1. Public
 2. Members
 3. Members of same user groups *only for person category*
 4. Members of collaboration group
 5. Managers of (collaboration-) group
 6. Editors

The value would be stored in the *privacy* property

**Comment by krista-ramakers** [comment]
Will these privacy levels also work for the templates?

**Comment by mworrell** [comment]
The ACL checks on properties work for all access methods. So also in templates (and exports).

**Comment by mworrell** [comment]
Moved the issues around indexing these properties to https://github.com/zotonic/zotonic/issues/1604
