### ISSUE TITLE
Improve less=auto behaviour for PNGs

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1216]
See https://github.com/zotonic/zotonic/commit/1ed7bb6349998e8ddce8f6650480bd00cd11a13a#commitcomment-16670016.

@mworrell suggests:

> Maybe the automatic lossless should be limited to certain file sizes? 
> Nobody is waiting for big uncompressed PNG files.
> And lossless problems are mostly only a problem for small images, like a logo, or images with an alpha channel. For big images JPEGs are mostly sharp enough, even when rendered from a PNG.

**Comment by ddeboer** [comment]
@mworrell Though that will create somewhat inconsistent behaviour, I can’t think of a better solution now.

**Comment by mworrell** [comment]
From the commit comments:

Maybe the automatic lossless should be limited to certain file sizes? 
Nobody is waiting for big uncompressed PNG files.
And lossless problems are mostly only a problem for small images, like a logo, or images with an alpha channel. For big images JPEGs are mostly sharp enough, even when rendered from a PNG.

**Comment by ddeboer** [comment]
See above, @mworrell. :wink:

**Comment by mworrell** [comment]
Haha, missed it because of all the meta-information :)

**Comment by ddeboer** [comment]
An alternative is to change the default to `lossless=false`. That way, users have to explicitly mark mediaclasses for small, lossless PNG mediaclasses (such as logos) to `lossless=true`. We could then drop `lossless=auto`.

**Comment by ddeboer** [comment]
@ArthurClemens Would the above be a good solution to your problem?

**Comment by mworrell** [comment]
@ddeboer Having `lossless=auto` as an option is good if you don't know the mime type of the input. It might be a small photo.

I agree that the default should be `false`, this gives unexpected behavior when displaying large uploaded PNGs (which happens quite a lot).

**Comment by ArthurClemens** [comment]
I agree with default `lossless=false`.
