### ISSUE TITLE
Don't expose unchecked properties in public API

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1226]
We currently export functions that expose resource properties that have not been checked for ACL permissions. For instance: `m_rsc:get` and `m_rsc:get_raw`.

Proposal:
1. Rename `m_rsc:get` to `m_rsc:get_cached`. Don’t export this function (it’s for internal use only).
2. Rename `m_rsc:get_visible` to `m_rsc:get`.
3. Don’t export `m_rsc:get_raw`.
4. Document this and note that developers can always get the full resource by passing a `z_acl:sudo(Context)`.

Are there are other modules where we expose unchecked data?

**Comment by ddeboer** [comment]
@mworrell @arjan Do you agree with this approach? If so, I can open a PR for this.

**Comment by mworrell** [comment]
Makes sense.

**Comment by mworrell** [comment]
The `get_raw` is actually used in `m_rsc_update` and the pivoting routines.
So we might want to keep it.

The `get` is used by some low level routines, like *merge* and *backup*. Maybe we can just rename it to `get_cached_noacl`, to make clear that there are no ACL checks done.

**Comment by ddeboer** [comment]
How about only exposing functions that do the ACL checks and requiring the caller (e.g. z_pivot_rsc) to provide a sudo Context? That way, it becomes very explicit when admin permission rights are used.

**Comment by ddeboer** [comment]
Ping @mworrell.

**Comment by mworrell** [comment]
I am ok with the *use sudo if you want sudo rights* approach.

**Comment by ddeboer** [comment]
Should we then also remove `m_rsc:p_no_acl/3`? The same can be achieved by calling `m_rsc:p(…, …, z_acl:sudo(Context))`.

**Comment by mworrell** [comment]
Good question, it is a function we are quite commonly using ...

**Comment by ddeboer** [comment]
I’d say: remove it for consistency’s sake. The idea is to limit the data you get by default and have developers do a bit of work if they want to get everything.

However, adding the `z_acl:sudo(Context)` everywhere feels quite laborious. We could mitigate this by only adding it at the highest level possible.

**Comment by mworrell** [comment]
`get`, `get_raw` and `get_raw_lock` all check access permissions now.
