### ISSUE TITLE
Updating a resource requires insert permission on its category

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1229]
Because of [`can_insert_category`](https://github.com/zotonic/zotonic/blob/master/modules/mod_acl_user_groups/support/acl_user_groups_checks.erl#L185). Why is that check there? Is it because we often don’t differentiate between insert and update?

This is similar to #1125.

**Comment by mworrell** [comment]
We have to check where it is used and might need to differentiate between insert and update (those are indeed different actions in the ACL, so should be checked different)

**Comment by ddeboer** [comment]
So we need to add some `can_update_category` or `can_category`, right?

**Comment by mworrell** [comment]
I will check how this is used and tune it.

**Comment by ddeboer** [comment]
Awesome!

**Comment by mworrell** [comment]
@ddeboer can you check branch  issue-1229-acl-update-check ?

**Comment by ddeboer** [comment]
Will do, please open a PR, as that makes commenting easier.

**Comment by mworrell** [comment]
See https://github.com/zotonic/zotonic/pull/1232

**Comment by mworrell** [comment]
This has been merged.
