### ISSUE TITLE
Firefox: problem with response to form-data post when uploading in admin

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1230]
Hi!

When adding a depiction (pdf) in firefox we get a strange window.

![screen shot 2016-03-30 at 16 08 51](https://cloud.githubusercontent.com/assets/5102362/14148357/7043ceb4-f69f-11e5-93b7-ca4aee40040f.png)

~ Dorien

**Comment by mworrell** [comment]
This is probably because of a Javascript error.
Can you check the console log?

**Comment by mworrell** [comment]
Just checked with Zotonic 0.x on Firefox 44.0.2, and I can't reproduce the problem.

**Comment by DorienD** [comment]
Strange, i have just updated 0.x and it still gives me that strange popup. Also it gives a error in the console (added screen)

![screen shot 2016-03-31 at 17 10 14](https://cloud.githubusercontent.com/assets/5102362/14180493/81e6a55a-f763-11e5-8efe-c4b9fedcf2ee.png)

**Comment by mworrell** [comment]
Try to disable all ginger modules and then check again.
I test against vanilla Zotonic.

**Comment by loetie** [comment]
Also reported by some clients (6-4-2016), i also cannot reproduce it myself.

**Comment by mworrell** [comment]
Note for debugging: might only be happening if no ws connection is used but the Ajax postbacks.

**Comment by fredpook** [comment]
As debugged: Multipart form post to hidden iframe should return text/plain and not text/x-ubf

**Comment by mworrell** [comment]
I could reproduce the problem after I understood that the problem was not adding per se, but uploading a new file. Please be specific in your reports!  :)

**Comment by DorienD** [comment]
Check! Will do next time :)
