### ISSUE TITLE
Site testsandboxdb is gone?

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1234]
I see some tests still [referring to testsandboxdb](https://github.com/zotonic/zotonic/search?utf8=%E2%9C%93&q=testsandboxdb). That site, however, (no longer?) exists. Should we re-add it? Testing against a site with a database connection seems very useful to me, as a lot of Zotonic functionality depends on `z_db` calls and will fail if no database is available. 

/cc @arjan

**Comment by mworrell** [comment]
Yes :+1: 

(nice issue number btw)

Travis-CI has support for running with a complete PostgreSQL database, so I think we definitely should try to get this back up & running.

**Comment by mworrell** [comment]
#1235 has been merged, closing issue.

**Comment by mmzeeman** [comment]
The tests using site testsandboxdb are only compiled, not run.

**Comment by ddeboer** [comment]
See #1392.
