### ISSUE TITLE
Firefox: reordering connection lists opens quick edit

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#1239]
It seems (also on the demo site) in firefox when you move a page connection up or down it also triggers the edit popup. This makes fast usage of the sorting of page connections impossible.
This does not seem to happen in chrome.

I assume this is a bug? (and not a feature?)

**Comment by mworrell** [comment]
Seems that in Firefox the click handler is called after the drag/drop is done.

**Comment by mworrell** [comment]
This seems to be tracked here https://bugzilla.mozilla.org/show_bug.cgi?id=787944
Checking out the comments and possible resolutions.

**Comment by mworrell** [comment]
Added a workaround by setting the sortable option *helper* to *clone*.

**Comment by mworrell** [comment]
For the record: this is a regression in Firefox, and should be fixed there. When Firefox is fixed, then this workaround can be removed.

**Comment by arjan** [comment]
That bug is almost 4 years old, and closed due to lack of activity..  I guess your workaround will be permanent :-s

**Comment by mworrell** [comment]
@arjan *snif*

**Comment by ddeboer** [comment]
Aren’t al workarounds? :wink:
