### ISSUE TITLE
rebar3 support

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#1241]
[Rebar3](http://www.rebar3.org/) is becoming the de-facto standard for Erlang compilation, now that it's even going to be officially supported by the OTP team.

Things like dependency management are easier (and faster) with rebar3.

Should we move our compilation process to it as well?

**Comment by arjan** [comment]
WIP branch: https://github.com/arjan/zotonic/tree/rebar3

**Comment by ddeboer** [comment]
Yeah!
