### ISSUE TITLE
Link from query page to query documentation is broken

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1242]
Hi!

That link is broken again :)

http://zotonic.com/docs/latest/manuals/datamodel/search.html

~ Dorien

**Comment by mworrell** [comment]
I guess it should be this?

http://zotonic.com/docs/latest/developer-guide/search.html#query-model-arguments

/cc @ddeboer

**Comment by mworrell** [comment]
@DorienD On which version of Zotonic?  0.x ? 0.15?

**Comment by mworrell** [comment]
Seems to be an issue with the translations, which were not updated when the english template was changed.

**Comment by ddeboer** [comment]
@mworrell LOL. Why is that link even translated? :wink:

**Comment by mworrell** [comment]
It is in a running text, so there are even HTML tags in the translations.

**Comment by ddeboer** [comment]
Fair enough!
