### ISSUE TITLE
What has happened to release-0.13.x?

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1244]
I am trying to update 0.13 locally, and Git gives me an error:

```
Your configuration specifies to merge with the ref 'refs/heads/release-0.13.x'
from the remote, but no such ref was fetched.
```

I also cannot find the branch with `git branch -r` or at at https://github.com/zotonic/zotonic/branches, so now I am getting confused.

* http://zotonic.com/download says "The latest release of Zotonic is release 0.14.0", but where is that?
* http://zotonic.com/docs/0.13/index.html says "0.13 stable", no mentioning of 0.14 on the page
* http://zotonic.com/docs/latest/developer-guide/releasenotes/index.html lists 0.14, but no mentioning of any changes to be made

**Comment by ddeboer** [comment]
A couple of things happened.

1. From [0.13.7](https://github.com/zotonic/zotonic/releases/tag/0.13.7) onwards, we dropped the `release-` prefix. You can find all releases at the GitHub [releases page](https://github.com/zotonic/zotonic/releases). To get the latest release:

    ```
    $ git fetch
    $ git checkout 0.15.0
    ```

2. We reduced the number of development branches: `master` for 1.0 and one `0.x` branch for all < 1.0 releases. So development for 0.15 and the upcoming 0.16 happens in the `0.x` branch.

3. We release a new minor version every month (#1204).

4. Unfortunately, we’re having some trouble to get the docs to build properly using the new structure (#1210), so there’s still only 0.13 in the docs.

**Comment by ArthurClemens** [comment]
thanks

**Comment by mworrell** [comment]
BTW, of your Zotonic configs, use a directory like `~/.zotonic/0/...`

Then your configs will work for every 0.x going forward.
