### ISSUE TITLE
403 page shows both "You need to log on" and a sign in form

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1245]
<img width="829" alt="no_access" src="https://cloud.githubusercontent.com/assets/350303/14586727/02a4ebc0-04a2-11e6-8556-4a0c7fe85768.png">

Both the title and "This page is only visible for authenticated users, log on to view this page." are redundant. Having double messages is not helpful.

Why not just show the sign in form?

**Comment by ArthurClemens** [comment]
Sometimes I even see a "back" button after the message.

**Comment by mworrell** [comment]
The *back* button appears if there is a referrer header, so we have some page to go back to.

I agree that the text can be better. At first the logon form wasn't there, I added it later.

The logic of that page is:

 * If no user logged on show logon form
 * If user logged on, show button (link) to logon as different user
 * If a referrer is known, show 'back' button

**Comment by mworrell** [comment]
I think it is good to have an explanation that you don't have access rights. The wording needs to be better than what I added.

**Comment by ArthurClemens** [comment]
Suggestion:

![zotonic 403 001](https://cloud.githubusercontent.com/assets/350303/14597484/47aff8d0-054d-11e6-8847-d5e29d428269.png)
![zotonic 403 002](https://cloud.githubusercontent.com/assets/350303/14597483/47ae9918-054d-11e6-8ffe-14f2ff7be2b4.png)
![zotonic 403 003](https://cloud.githubusercontent.com/assets/350303/14597486/47b1499c-054d-11e6-9731-5630169dd2eb.png)
![zotonic 403 004](https://cloud.githubusercontent.com/assets/350303/14597485/47b02be8-054d-11e6-8ba6-a92d21467c0e.png)

**Comment by mworrell** [comment]
Nice, I like them!  Easy to incorporate as well.

/cc @mmzeeman

**Comment by ddeboer** [comment]
@mworrell Do you have time to work on this so it can get into the 0.16 release or should we postpone?

**Comment by mworrell** [comment]
@ddeboer Working on it.

**Comment by ddeboer** [comment]
Awesome!

**Comment by ArthurClemens** [comment]
👏
