### ISSUE TITLE
Facebook login is broken for apps on API version 2.6

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1247]
1. Connect Zotonic to a Facebook version 2.6 app.
2. Try to log in but don’t give e-mail permission.
3. Try to log in again and you’ll see the screen below. The ‘change permissions’ doesn’t work.

![screen shot 2016-04-19 at 15 52 24](https://cloud.githubusercontent.com/assets/89267/14641476/c1327224-0646-11e6-815f-971035110a5a.png)

**Comment by mworrell** [comment]
What does not work?  Is there no url, does Facebook not request new permissions?

From the code I see that we do add `"&auth_type=rerequest"` to the permissions url, which should request new permissions.

**Comment by ddeboer** [comment]
Clicking the ‘change permissions’ link doesn't do anything.

**Comment by mworrell** [comment]
Is the anchor's href property empty?
