### ISSUE TITLE
Switch to Universal Analytics

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1249]
Google has deprecated the old Analytics, so let’s [switch to Universal](https://developers.google.com/analytics/devguides/collection/analyticsjs/#the_javascript_tracking_snippet). I’m in favour of the [alternative script] that allows modern browsers to preload (but gives a slight penalty on IE 9 and below).

**Comment by mworrell** [comment]
Google now also uses https for all their analytics https://support.google.com/analytics/answer/6385009

**Comment by tahteche** [comment]
I have been looking into this issue. A little huddle I see in switching to Google Universal Analytics is that Zotonic has a Custom Variable `User`.
In the old Google Analytics custom variables were created only from the Analytics code and then pushed to Google Analytics but in the new Universal Analytics, custom variables have been replaced with Dimensions which are configured from the Analytics dashboard and no longer just from the Analytics code. Hence any Zotonic user intending to use the `User` custom variable will have to create it themselves from the Google Analytics dashboard then supply its index to Zotonic.

After the switch to Universal Analytics using Google analytics in Zotonic will differ from the present way in that:
- The user will have to create a custom Dimension probably named `User` to support the present `User` custom variable.
- The user will be required to supply not just his Google analytics tracking id but also the index of the `User` Dimension created earlier before its data can be pushed to Google Analytics.

https://developers.google.com/analytics/devguides/collection/upgrade/reference/gajs-analyticsjs#custom-vars

**Comment by arjan** [comment]
Google has something called its [User ID feature](https://support.google.com/analytics/answer/3123666), which might be a better fit.
However it still needs to be configured on the analytics admin page.

But the user id can be sent with the tracking code, see here:
https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#user_id

```
ga('create', 'UA-XXXXX-Y', 'auto', {
  userId: USER_ID
});
ga('send', 'pageview');
```

Seems straightforward this way.

**Comment by mworrell** [comment]
Is there anyone actually using the *User* property?

A possibility is to remove the feature for now, and the re-add it as an option via the SEO configuration?

**Comment by arjan** [comment]
We can always send `m.acl.user` to analytics, right? It's a matter of configuration (in GA) whether webmasters decide to do something with it.

**Comment by mworrell** [comment]
Ah, if it doesn't hurt anything, then it is the right thing to do.

**Comment by mmzeeman** [comment]
Also be sure to set `{'nonInteraction': 1}` when it is not a user interaction. This is important for SEO ranking because it influences the bounce rate.
