### ISSUE TITLE
Mod_export error

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1251]
Hi!

Error when exporting a query page with cat=person:

`14:34:57.832 [error] webmachine_mochiweb:147 caught error badarg (stacktrace [{erlang,iolist_to_binary,[[id]],[]},{z_convert,to_binary,1,[{file,"src/z_convert.erl"},{line,104}]},{export_encoder_csv,'-header/3-lc$1/1-0-',2,[{file,"modules/mod_export/support/export_encoder_csv.erl"},{line,60}]},{export_encoder_csv,header,3,[{file,"modules/mod_export/support/export_encoder_csv.erl"},{line,60}]},{export_encoder,do_header_1,3,[{file,"modules/mod_export/support/export_encoder.erl"},{line,115}]},{webmachine_request,send_stream_body,4,[{file,"src/webmachine_request.erl"},{line,241}]},{webmachine_request,send_response_body_data,4,[{file,"src/webmachine_request.erl"},{line,218}]},{webmachine_request,send_response,1,[{file,"src/webmachine_request.erl"},{line,126}]}])`

**Comment by mworrell** [comment]
Can you check this on the 0.x branch?
I suspect it has been fixed last friday.

**Comment by fredpook** [comment]
Tested on 0.16.0 and works.

**Comment by mworrell** [comment]
Ok, then I assume this can be closed.
Please re-open if the issue persists.
