### ISSUE TITLE
Improve upgrade path for Zotonic versions

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1253]
Proposal: add `z:upgrade()` which 
1. calls `make get-deps` (Rebar)
2. calls `zotonic_deps:ensure()` to add code path for newly added deps
3. calls something similar to `z_code_reloader:reload()` to load updated beams in `deps/`.

**Comment by ddeboer** [comment]
We also need to check `zotonic_deps:ensure()`, as it currently seems broken.

**Comment by arjan** [comment]
In the rebar3 branch, I removed zotonic_deps altogether because it did not to anything.

**Comment by mworrell** [comment]
As we are now using rebar3 and the umbrella app, this will be quite different from before.

I think of:

 1. Run `rebar3 compile`, this also fetches and updates all dependencies
 2. The running Zotonic should ensure that the code path is complete with all apps in the `_build/default/*` directory

**Comment by mworrell** [comment]
Of course, using a release is a possibility too, with `relup` to upgrade.

**Comment by mworrell** [comment]
We will be using rebar3 and hex for the updates. Closing this issue.
