### ISSUE TITLE
merge emqtt?

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#1256]
It seems emqtt (https://github.com/emqtt/emqttd) has had quite some improvements and is under active development again.
Currently zotonic uses a fork of emqtt, mainly because the original repo was unmaintained. Now that it's active again, it might make sense to investigate whether we can depend on the new repo instead of maintaining our own fork.

**Comment by mworrell** [comment]
We have some changes, so we might want to rebase those and make a pull request.

I tried to do a merge here but found some last minute problems: https://github.com/emqtt/emqttd/pull/19

Didn't get around to make a new merge request.

**Comment by mworrell** [comment]
So short answer: yes, we should try to get our changes merged upstream.

**Comment by mworrell** [comment]
In master we are now using our own MQTT broker and session management.

Closing this issue as it is not relevant anymore.
