### ISSUE TITLE
controller_static_pages won't search for index.html on the root folder

### ISSUE THREAD

**Issue by caiodark** [zotonic/zotonic#1261]
I have this dispatch rule:
`{newsletter, ["newsletter"], controller_static_pages,[ {root, "newsletter"} ]}`
the newsletter folder has a index.html file, if I browse for /newsletter I get a 404. If I add index.html the page will be displayed. If I add a subdirectory (e.g. /newsletter/foo) and move things there then the index.html page will be displayed even if I omitted it.

you can see things here: [http://clover-lab.com/newsletter/](without sub) and here: [http://clover-lab.com/newsletter/foo/](with sub)

I'm using the 1.0 version.

**Comment by arjan** [comment]
Can you try the following:

    {newsletter, ["newsletter", '*'], controller_static_pages,[ {root, "newsletter"} ]}

e.g. adding the `'*'` in the dispatch rule?

**Comment by mworrell** [comment]
We do not accept an empty path for `'*'`
So you need an alternative dispatch rule for the path `["newsletter"]`

The relevant tests of the `dispatch_compiler`:

```
wildcard_test() ->
    Rules = [
        {image, ["image", '*'], x, []}
    ],
    ok = dispatch_compiler:compile_load(?M, Rules),
    ?assertEqual({ok, {{image, ["image", '*'], x, []}, [{'*', [<<"foo">>, <<"bar">>]}]}},
                 ?M:match([<<"image">>, <<"foo">>, <<"bar">>], none)),

    ?assertEqual(fail,
                 ?M:match([<<"image">>], none)).
```

**Comment by caiodark** [comment]
That's ok to me, but that should be clearer in the documentation as sub-directories are called directory.

**Comment by ddeboer** [comment]
@caiodark Do you have a suggestion as to how we can improve the docs on this subject?

**Comment by arjan** [comment]
I think this is actually a regression. I can confirm that this used to work in older Zotonic versions. It must have been broken when the dispatch compiler was introduced.

**Comment by arjan** [comment]
"We do not accept an empty path for '*'" --> I think we used to do. @mworrell any idea why this was changed?

**Comment by mworrell** [comment]
We are now using the dispatch compiler, which doesn't accept an empty path for '*'. Which is quite logical if you look at it for the perspective of matching paths elements.

If this is really unwanted behavior then we could change the way the dispatch compiler works. Though the we also need to check how the URLs are generated if '*' is given an empty string as value.

An alternative is to add or inject a dispatch rule for the empty path if the controller is serving static content. This could be done during collection of the dispatch rules, before compiling them (similar how mod_ssl changes dispatch rule options).

**Comment by arjan** [comment]
I think the `*` should be allowed to be empty if it is the last part in the dispatch rule. And I think it used to work like this earlier as well.

Injecting a dispatch rule seems more like a stopgap solution. 

In other news I have trouble serving index.html using controller_file.

```
 %% this "stopgap" one does not work
 {bimrab,   ["archived", "bimrab"],   controller_file,   [ {path, "bimrab/index.html"}, {root, [static]} ] },

 %% this one works and also used to serve index.html ad /archived/bimrab
 {bimrab,   ["archived", "bimrab", '*'],   controller_static_pages,   [ {root, "static/bimrab"} ] },


```

**Comment by mworrell** [comment]
What is the `static` root?

**Comment by mworrell** [comment]
I will have a look at the dispatch_compiler for the empty `'*'`

**Comment by mworrell** [comment]
Fixed in https://github.com/zotonic/dispatch_compiler/issues/1
