### ISSUE TITLE
Mochiweb + Erlang 17 & 18 and IE9 and IE10 ssl problems

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1263]
The default cipher selection in mochiweb uses the wrong list of algorithms. 

This makes it impossible to use tls 1 and tls 1.1. The reason for this is that the default_prf algorithm should be used in the cipher specs instead of specific algorithms.

This causes ssl connection problems with IE9 and IE10.

**Comment by mmzeeman** [comment]
I updated mochiweb... 

https://github.com/zotonic/mochiweb/commit/7741d14003150d6873444f74467f3f4d1792fc32

This should fix this issue.

**Comment by mworrell** [comment]
Let's also merge this upstream in https://github.com/mochi/mochiweb , as we had our SSL changes merged.

**Comment by mmzeeman** [comment]
:+1:  Didn't know that.

**Comment by mmzeeman** [comment]
Looking at the code more closely... Maybe we should file a bug report for `ssl:cipher_suites/0` too. It returns an unusable list of ciphers if you want to support tls1, 1.1 and 1.2.

**Comment by mworrell** [comment]
This has been fixed and merged upstream.
