### ISSUE TITLE
Sanitize image/svg+xml files

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1265]
SVG files can contain references to external sources.
This can be problematic for ImageMagick convert.

We should sanitize uploaded SVG files for these references and refuse them as acceptable image files.

See also:
https://imagetragick.com
http://www.openwall.com/lists/oss-security/2016/05/03/18

**Comment by mmzeeman** [comment]
Don't we have to strip js attributes like `onclick` and friends too?

**Comment by mworrell** [comment]
@mmzeeman - you are right. So we need to add a specialized sanitizer for SVG.  What handlers are available, are they all called `on....` ?

**Comment by mworrell** [comment]
There also seems to be support for `<script/>` inside SVGs... so we need to pull any SVG through a XML sanitizer.

**Comment by mmzeeman** [comment]
We (channel.me) have a svg sanitizer which can be moved to zotonic. I have sent you the module.

**Comment by mworrell** [comment]
Added SVG sanitization to z_stdlib in https://github.com/zotonic/z_stdlib/commit/1f3b41ecb97fa44ff3f389a0e0a41721dcd01e0a

This uses the code provided by channel.me

We might want to consider if we want to sanitize uploaded SVG files or reject them when they contain dangerous content?  I am leaning towards sanitizing and then uploading the sanitized version.

**Comment by mworrell** [comment]
Now uploaded SVG files are sanitized.
