### ISSUE TITLE
HTML sanitization: check for <a/> tags with targets

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1268]
In case HTML is entered with a tag like:

```
<a href="http://example.com" target="_blank>...</a>
```

We should add `rel="noopener"` as an attribute.

More information: https://mathiasbynens.github.io/rel-noopener/

cc @ArthurClemens

**Comment by mworrell** [comment]
Also add this to the links generated in the comment sections.

**Comment by ArthurClemens** [comment]
For browser compatibility 2 attribute values are needed: `rel="noopener noreferrer"`
