### ISSUE TITLE
Vimeo embed code doesn't show preview

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1272]
```
<iframe src="https://player.vimeo.com/video/155936727?byline=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/155936727">Digital Art: Who Cares?</a> from <a href="https://vimeo.com/arttubevideo">ARTtube</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

**Comment by mworrell** [comment]
This was indeed a problem with the vimeo embed handling code. Vimeo now servers their videos from another domain.

**Comment by DorienD** [comment]
Hi! I have just updated the 0.x branch and tried to add a vimeo video again. I got this error in the shell: 

`17:50:36.041 [error] Error in process <0.22442.0> on node 'zotonic001@ginger' with exit value: {function_clause,[{mochijson,tokenize,["not found.",{decoder,utf8,null,1,11,trim}],[{file,"src/mochijson.erl"},{line,362}]},{mochijson,json_decode,2,[{file,"src/mochijson.erl"},{line,233}]},{mod_video_embed,preview_vimeo,3,[{file...`

Still no thumbnail.

**Comment by arjan** [comment]
Is it the same video? This looks like a 404. Maybe the video has embedding disabled?
If not, please reopen the ticket.

**Comment by mworrell** [comment]
That was indeed a 404.
I added better error handling and nicer default preview-images.

**Comment by DorienD** [comment]
But the video did work in my fancybox and also when i did api/base/export, so it can't be a 404. I will update 0.x again and test again with another video.

**Comment by mworrell** [comment]
The error you gave is a 404.
So we got a 404 back from Vimeo.
If you can reproduce it with some Vimeo video then post the embed code here.

**Comment by DorienD** [comment]
`09:56:17.091 [warning] [geheugenvanoost] Vimeo metadata fetch returns {"HTTP/1.1",404,"Not Found"} "164479194 not found."`

With this embed code: 

```
<iframe src="https://player.vimeo.com/video/164479194?title=0&byline=0&portrait=0&badge=0" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
<p><a href="https://vimeo.com/164479194">Wizard Mode</a> from <a href="https://vimeo.com/salazarfilm">Salazar</a> on <a href="https://vimeo.com">Vimeo</a>.</p>
```

**Comment by mworrell** [comment]
On this page there is the message:

> Unfortunately, this title is unavailable in your region.

Maybe the video you see is the trailer of the video you try to embed (the original).

**Comment by DorienD** [comment]
Allright, if i choose a dutch video it works without the warning in the shell. And i get a play thumbnail, not the thumbnail of the video.

**Comment by mworrell** [comment]
If the video thumbnail doesn't appear after a while, then paste the video embed code here.

**Comment by DorienD** [comment]
it works!!! 💃  thanks!!
