### ISSUE TITLE
Improve coding standards

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1275]
Our [current ones](http://zotonic.com/docs/latest/developer-guide/contributing.html#coding-standards) are very limited.

Questions:
1. order of `-spec` and `%% @doc` function header
2. indent for function bodies
3. explain how to enable [Editconfig plugins](http://editorconfig.org/#download) in editors ([Emacs](https://github.com/editorconfig/editorconfig-emacs), [Vim](https://github.com/editorconfig/editorconfig-vim)), as I see al lot of (e.g.) trailing whitespace in the code, which causes diffs to be unnecessarily large

Does anyone know of linting tools that can catch CS violations?

**Comment by mmzeeman** [comment]
What are there things you want to improve upon?

Personally I would love to use a tool like go fmt: https://blog.golang.org/go-fmt-your-code. Unfortunately such a tool does not (yet) exist for erlang.

**Comment by ddeboer** [comment]
See my list above: we need to elaborate more on the standards that we follow and make some decisions.

**Comment by mworrell** [comment]
Inaka also made a tool that can verify certain code style rules: https://github.com/inaka/elvis

**Comment by ddeboer** [comment]
Those are some good ideas, but in general I think we shouldn’t invent our own standards but to stay in keeping with existing standards. All we should do is:

* summarise those standards, in particular through one or two code examples
* fill gaps where existing standards don’t give a clear direction.

**Comment by arjan** [comment]
:+1: for using elvis as a pre-commit hook.

**Comment by mworrell** [comment]
@ddeboer most of the guidelines as http://www.erlang.se/doc/programming_rules.shtml and https://github.com/inaka/erlang_guidelines just hold. 

The (only?) differences with Inaka I see are:

 * 4 characters per tab (instead of 2)
 * 132 characters per line (instead of 80)  (we are not using punch cards)
 * some small layout things about horizontally lining up start/end of blocks
 * order of doc/spec/function-code

So nothing much to invent here :)

**Comment by mworrell** [comment]
@arjan won't we get a lot of syntax-cleanup-commit noise if we would Elvis as a pre-commit hook now.

**Comment by mworrell** [comment]
BTW please don't change anything till I have finished and merged https://github.com/zotonic/zotonic/pull/1355 (merge conflict problems ahead...)

**Comment by ddeboer** [comment]
Yep, let’s wait until that functionality lands in 1.0 

Added this issue to 1.0, as enforcing coding standards in (for instance) a pre-commit hook does cause a BC break of sorts.

**Comment by ddeboer** [comment]
By the way, we should prefer this (spaces between record key and value):

```erlang
set_content_policy(#z_file_info{acls = Acls, mime = <<"application/pdf">>}, ReqData) ->
```

over this:

```erlang
set_content_policy(#z_file_info{acls=Acls, mime=<<"application/pdf">>}, ReqData) ->
```

for the simple reason that the latter throws a `syntax error before: '=<'`.

**Comment by ddeboer** [comment]
Enabled the [Elvis webhook](https://github.com/inaka/elvis#webhook), which now comments on our pull requests! Pretty awesome. We can still tweak the config if we find Elvis is overly aggressive.
