### ISSUE TITLE
template_not_found at start

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1278]
Hi ,
I got a strange behaviour on my zotonic instance.
Sometime, when starting in debug I get an infinite (?) loop of those error messages 

```
10:19:40.976 [error] Error in process <0.461.0> on node zotonic001@cameleon with exit value:
{{nocatch,{error,{template_not_found,"_email_contact.tpl",enoent}}},[{z_template,maybe_render,4,[{file,"src/support/z_template.erl"},{line,97}]},{z_template,render_to_iolist,3,[{file,"src/support/z_template.erl"},{line,139}]},{z_email_server,optional_render,4,[{file,"src/smtp/z_email_server.erl"},{line,894}]},{z_email_server,encode_email,5,[{file,"src/smtp/z_email_server.erl"},{line,692}]},{z_email_server,spawned_email_sender,11,[{file,"src/smtp/z_email_server.erl"},{line,563}]}]}
```

So I need to Ctr+C to stop. Then when starting again, no issue.
the `_email_contact.tpl` is in `priv/skel/blog/templates/_email_contact.tpl`
but not in my own site.  
Do I need to copy this template in my own ? Do I miss something ?

zotonic 0.14

**Comment by ddeboer** [comment]
Hey Eric!

Did you create your site from the blog skeleton, as [explained in the documentation](http://zotonic.com/docs/0.x/ref/cli/cli-addsite.html?highlight=skeleton)? If so, the `_email_contact.tpl` template will have been copied over to the `templates/` dir in your site. If not, you need to copy that template yourself.

**Comment by crownedgrouse** [comment]
no I did not used it. My site is not a blog but wanted to use the email contact template in a contact page. I wrongly assumed that priv/skel contents are resources available for all sites (BTW could be nice to have directory for common resources ? it is maybe already the case ? sorry I'm not a zotonic specialist for now :>) ...).
So let me copy the template in my site and try again.

**Comment by ddeboer** [comment]
You can share templates between sites by [storing them in a module](http://zotonic.com/docs/0.x/developer-guide/templates.html#template-locations-and-the-lookup-system) that you then enable for both sites.

In your case, you just need to copy `_email_contact.tpl` to `yoursite/templates/`. Then remember to flush the site, to make sure the new template is picked up.

**Comment by crownedgrouse** [comment]
thanks for the share.
but actually the template is shown in my site, so I suspect a name clash between templates in skel and in my own. Should I rename the template ?

**Comment by ddeboer** [comment]
That is odd! Can you try renaming the template (and making sure that where you include it you change the name also)? Please let us know if that helps. If so, you definitely stumbled upon a bug.

**Comment by crownedgrouse** [comment]
yes , as far the email contact form was shown in my site, this puzzled me , so I though there was no need to add it in my own site. I need to do some more testing , then and will raise a bug with details if necessary. thanks

**Comment by ddeboer** [comment]
Please do! And welcome to Zotonic, hope you like it! :smile:

**Comment by crownedgrouse** [comment]
the best :>) !  I used  it years ago, but then give up for my own erlang projects. I come back for a personal website, with a lot of things to learn again  ! 
Only a remark : plugin documentation is too poor, an example might be great, for example for geo , social network (tweet and so on). But the doc is huge, I maybe not embrace the whole thing.

**Comment by ddeboer** [comment]
I agree, particularly the module documentation is rather lacking. For instance mod_twitter has [this chapter](http://zotonic.com/docs/latest/ref/modules/mod_twitter.html). For an overview, see the [modules page](http://zotonic.com/docs/latest/ref/modules/index.html). mod_geo is a separate module, currently not built-in to Zotonic, although we have some plans to change that: #1122.

Anyway, if you have some suggestions as to how we can improve the docs, please create an issue! Or even better, open a pull request. :wink:

**Comment by crownedgrouse** [comment]
Hi,
well after looking to the code more precisely, my bad. the _email_contact.tpl is in my site templates directory.
But this does not explain the problem.
I use this template in an event of a resource after a post of a form.
```
z_email:send_render(z_email:get_admin_email(Context), "_email_contact.tpl", Vars, Context)
```
At first start after some time stopped 
```
23:18:13.710 [info] Could not find template: _email_contact.tpl (enoent)
23:18:13.710 [error] Error in process <0.448.0> on node zotonic001@cameleon with exit value:
{{nocatch,{error,{template_not_found,"_email_contact.tpl",enoent}}},[{z_template,maybe_render,4,[{file,"src/support/z_template.erl"},{line,97}]},{z_template,render_to_iolist,3,[{file,"src/support/z_template.erl"},{line,139}]},{z_email_server,optional_render,4,[{file,"src/smtp/z_email_server.erl"},{line,894}]},{z_email_server,encode_email,5,[{file,"src/smtp/z_email_server.erl"},{line,692}]},{z_email_server,spawned_email_sender,11,[{file,"src/smtp/z_email_server.erl"},{line,563}]}]}
```
then after one or two start, no more errors.

**Comment by ddeboer** [comment]
@mworrell Does this have something to do with #1257, perhaps?

**Comment by crownedgrouse** [comment]
As site is currently in development,  the smtp is not working and there is many mails waiting in mnesia table, due to bounce errors probably. So maybe it is related.  BTW I got no errors in console that mail are not sent. I suspect the smtp process to try to send waiting mails while something no ready.

**Comment by crownedgrouse** [comment]
Hi, by doing `mnesia:clear_table(email_queue).`  it looks to solve the problem. (well I did several restart without issue). So it looks to be related to email waiting to be sent in mnesia table at start. I did not see issue after several start because all email was probably marked as retried, and therefore not handle for a while ?
