### ISSUE TITLE
Restart runs the skeleton in config, leading to unexpected module changes

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1279]
Case: site has this line:

```
 %% What skeleton site this site is based on; for installing the initial data.
 {
   skeleton, empty
 },
```

This also activates `mod_admin_only` (although not documented).

Now after a restart, the site config is read again and `mod_admin_only` gets enabled. This should not be happening:  a restart should always keep all modules enabled/disabled as before, regardless of the site.modules and the skeleton configuration.

**Comment by mworrell** [comment]
Set milestone to 0.17, hopefully we can fix this unexpected behavior in that release.

**Comment by ddeboer** [comment]
Do we still want `mod_admin_only` to be enabled on first boot? Or should it never be started at all?
