### ISSUE TITLE
500 Error on admin page

### ISSUE THREAD

**Issue by lohenzoo** [zotonic/zotonic#1288]
Hi, someone can help to figure out what is happening with my installation?

This happen only when try `http://zotonic.dev:8000/admin`

FYR:
OS: El Capitan
Erlang r18

```shell
14:22:18.859 [info] http://zotonic.dev:8000                        - running
:0: function identifier/1 undefined
14:22:26.295 [error] Error compiling template: <<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">> ({'EXIT',{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}})
14:22:26.296 [error] Error rendering template: <<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_admin/templates/admin_logon.tpl">> ({error,{template_compile_error,<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>,{'EXIT',{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}}}})
14:22:26.296 [error] Error in process <0.773.0> on node 'zotonic001@LORENZO-HERNANDEZ' with exit value:
{function_clause,[{lists,thing_to_list,[<<"/Users/lorenzo-hernandez/projects/hacking/zotonic/modules/mod_authentication/templates/_logon_login_support.tpl">>],[{file,"lists.erl"},{line,602}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{lists,flatmap,2,[{file,"lists.erl"},{line,1249}]},{erlydtl_compiler,compile_to_binary,3,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,141}]},{erlydtl_compiler,compile,5,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/erlydtl/erlydtl_compiler.erl"},{line,109}]},{z_template,compile_job,2,[{file,"/Users/lorenzo-hernandez/projects/hacking/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,338}]}]}
```
Screenshot:
<img width="1427" alt="screen shot 2016-05-22 at 2 27 53 pm" src="https://cloud.githubusercontent.com/assets/17766485/15456016/7d5daada-2029-11e6-9c7f-94936271cd2c.png">

**Comment by ddeboer** [comment]
Which version of Zotonic are you on?

**Comment by lohenzoo** [comment]
Not sure how to check the version, I cloned yesterday from master

**Comment by ddeboer** [comment]
The `:0: function identifier/1 undefined` must have something to do with #1150 where @willemdj introduced `erlydtyl_compiler:identifier`, but I fail to see how that caused the problem. 

@mworrell Any ideas?

**Comment by willemdj** [comment]
Indeed, there are calls to z_ids:identifier/0 in erlydtl_compiler.erl that I have missed. They now result in an error, because they return a binary instead of a string.

It is easy to fix, but I don't understand why I missed these calls. I'll try to identify if there are other things that I may have missed.

**Comment by ddeboer** [comment]
But the calls to `identifier()` in `erlydtl_compile` seem to be [properly wrapped](https://github.com/zotonic/zotonic/blob/master/src/erlydtl/erlydtl_compiler.erl#L1695) and the return value converted from binary to list.

**Comment by willemdj** [comment]
Hm, sorry, you are right, I have been looking in the wrong version of the
file. I'll see if I can find the real reason...

**Comment by willemdj** [comment]
I found it, I misunderstood how erl_syntax:application/2 works (line 254 in erlydtl_compiler.erl).

It should be:
```erlang
            BodyAutoIdAst = erl_syntax:match_expr(
                                    AutoIdVar,
                                    erl_syntax:application(
                                        erl_syntax:atom(binary_to_list),
                                        [erl_syntax:application(
                                                erl_syntax:atom(z_ids),
                                                erl_syntax:atom(identifier),
                                                [erl_syntax:integer(8)])
                                        ]
                                    )
                             ),
```

What is the best way to proceed now?

**Comment by arjan** [comment]
Could you verify that it works? And then create a new PR, we'll merge it.

**Comment by usrbinerl** [comment]
I have exactly the same issue in FreeBSD 10.3 and OpenSuse Leap 42 with zotonic 0.16. Zotonic compiles sucessfully and I can create sites - but the admin site shows the same error as mentioned above.

**Comment by ddeboer** [comment]
@usrbinerl If you’re on 0.16.0, your error must be unrelated to the one above (which is causes by changes only available on master). Could you please paste the exact error message you’re getting in your logs?

**Comment by usrbinerl** [comment]
Euh, sorry, my bad, I cloned from master zotonic -v says 1.0-dev. I thought I was cloning 0.16...

**Comment by ddeboer** [comment]
@usrbinerl No problem! Please enjoy Zotonic, and let us know if you find things that we can improve upon. :wink:

**Comment by usrbinerl** [comment]
I do indeed enjoy working with zotonic. 
Well, on OpenSuse there is an issue with postgresql, which is configured to use 'ident' for authorising local connection not 'trust'. Zotonic is not able to create databases unless you change settings in pg_hba.conf from ident to trust... I can raise this a separte issue, if you want.

**Comment by arjan** [comment]
Please do :)

**Comment by willemdj** [comment]
It solves this particular problem (Templates with ids are now compiled
correctly). The general tests also run without problems (but that was
already the case ...)

I'll create a new pull-request.

**Comment by ddeboer** [comment]
@lohenzoo This should now be fixed on master. Could you please check?

**Comment by usrbinerl** [comment]
Tested it on FreeBSD 10.3 and OpenSuse 42.1 -> Fixed.  Error no longer occurs, I can log in. 
On FreeBSD there seems to be a seperate issue though. I'll open a separate topic on that one.

**Comment by lohenzoo** [comment]
Thanks guys! that's an awesome support! I will test and let you know how is going in El Capitan.
