### ISSUE TITLE
zotonic not able to create site database on OpenSuse Leap 42.1

### ISSUE THREAD

**Issue by usrbinerl** [zotonic/zotonic#1291]
Zotonic 1.0-dev compiles well on OpenSuse Leap 42.1 and you can run and access the default site. However, creating new sites fails with error:
`[error][sitename] Cannot create database "databasename" because user "zotonic* cannot connect to the 'postgres' database: invalid_authorization_specification'.`

This issue is due to postgresql is by default using ident as authentication method for IP connections from localhost. The issue can be fixed by changing pga_hba.conf:
```
From:
host    all    all    127.0.0.1/32    ident
To:
host    all    all    127.0.0.1/32    trust
```

Same in IPv6 section, if you use that:

```
From:
host    all    all    ::1/128    ident
To:
host    all    all    ::1/128    trust

```
and then restart postgresql.
Than zotonic can create the database.

This fix will work, however, I do not know, if changing the settings in postgresql breaks anything on OpenSuse. So far, I haven't seen anything, but I only discovered the issue an hour ago, or so...

**Comment by ddeboer** [comment]
Thanks for sorting this out!

Would you suggest we add this to our documentation? Or is there something that we could change in Zotonic itself?

**Comment by usrbinerl** [comment]
For me, adding it to the documentation would be sufficient, as I do not use ident, but maybe other people would be interested in having this option.
