### ISSUE TITLE
Zotonic runtests returns 0 in case of failure

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1302]
We currently have (on 0.17.0):

```bash
bin/zotonic runtests

# …

3:55:59.757 [info] Starting reporters with []
13:55:59.758 [info] Application exometer_core started on node zotonic001_testsandbox@ginger
13:55:59.761 [info] Application exometer started on node zotonic001_testsandbox@ginger
13:55:59.763 [info] Application epgsql started on node zotonic001_testsandbox@ginger
** Found 0 name clashes in code paths
13:55:59.894 [error] Zotonic start error: no such file or directory: syslog.app
```

This still returns `0` (success) on Travis, probably due to https://github.com/zotonic/zotonic/blob/master/src/scripts/zotonic-runtests#L59.

**Comment by arjan** [comment]
I don't think `syslog` is meant to be on the 0.x branch at all, @mmzeeman ?

**Comment by ddeboer** [comment]
True, I’m fixing that as we speak! So that was a silly mistake I made. 😓

This issue is about our tests not reporting the mistake as they should have.

**Comment by ddeboer** [comment]
Tagged 0.17.1
