### ISSUE TITLE
Embedded video in tinymce

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1304]
When you add a embedded video trough the tinymce it does not immediately  in the editor, it does get connected as a depiction but it does not appear in the editor. If you click again on the add media button you can select it and then it appears in the editor.

![step1](https://cloud.githubusercontent.com/assets/5102362/15886774/19f1f2e2-2d5f-11e6-9eff-cb64c307450f.png)
![step2](https://cloud.githubusercontent.com/assets/5102362/15886777/19f8c1c6-2d5f-11e6-9dfd-9535e117d3ce.png)
![step3](https://cloud.githubusercontent.com/assets/5102362/15886776/19f43cc8-2d5f-11e6-95f5-9c64efceb9d4.png)
![step4](https://cloud.githubusercontent.com/assets/5102362/15886775/19f24454-2d5f-11e6-98cc-9d4867a8388a.png)

**Comment by ddeboer** [comment]
So the RTE field is not updated when embedding a video?

**Comment by DorienD** [comment]
Yep its not updating, and a page refresh also does not show it.
