### ISSUE TITLE
observe_acl_is_allowed is not always effective when it comes to updates

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1306]
I'm attempting to implement a custom ACL rule using observe_acl_is_allowed. Unfortunately in some cases this observer does not seem to have authority over who can update what.

Let's say for the sake of argument, I would allow everything using the following observer:

```
observe_acl_is_allowed(#acl_is_allowed{}, _Context) -> true.
```

It seems to me that you should now be able update any resource no matter who you are. This doesn't seem to apply for anonymous users even after the recent change to `z_acl:rsc_editable/2` that now no longer shuts anons out by default.

The following error is thrown when I try to do an update:

```
14:52:52.786 [error] Rsc update error: throw:{{error,eacces},[{m_rsc_update,update_transaction_fun_props,3,[{file,"/opt/zotonic/src/models/m_rsc_update.erl"},{line,365}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"src/db/z_db.erl"},{line,141}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,206}]},{z_db,transaction,3,[{file,"src/db/z_db.erl"},{line,95}]},{m_rsc_update,update_transaction,3,[{file,"/opt/zotonic/src/models/m_rsc_update.erl"},{line,303}]},{mod_ginger_edit,event,2,[{file,"/opt/zotonic/user/modules/mod_ginger_edit/mod_ginger_edit.erl"},{line,51}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,256}]}]} stacktrace: [{m_rsc_update,update_result,3,[{file,"/opt/zotonic/src/models/m_rsc_update.erl"},{line,349}]},{mod_ginger_edit,event,2,[{file,"/opt/zotonic/user/modules/mod_ginger_edit/mod_ginger_edit.erl"},{line,51}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,256}]},{z_transport,incoming_msgs,2,[{file,"src/support/z_transport.erl"},{line,193}]},{z_transport,incoming,2,[{file,"src/support/z_transport.erl"},{line,161}]},{controller_websocket,websocket_message,3,[{file,"modules/mod_base/controllers/controller_websocket.erl"},{line,108}]},{z_websocket,websocket_handle,3,[{file,"modules/mod_base/support/z_websocket.erl"},{line,54}]},{z_ws_request_adapter,websocket_handler_callback,5,[{file,"modules/mod_base/support/z_ws_request_adapter.erl"},{line,212}]}]
```

Allowing updates through an actual rule will fix the problem but that is not what I want. After all I'm trying to implement some custom logic.

Together with @ddeboer I traced the problem down to the `acl_user_groups_checks:can_rsc_ug/6` where we have another check against the rules that is unobservable.

What to do? To me this seems like a bug, but I am unsure where we should fix it.

**Comment by ddeboer** [comment]
Thanks @Dirklectisch for the perfectly clear problem description!

@mworrell Should we in `acl_user_groups_checks:can_rsc_ug`  just call `z_acl:is_allowed` again, which then will dispatch an observable `acl_is_allowed`?

**Comment by ddeboer** [comment]
Calling `m_rsc:update` will eventually trigger the `acl_rsc_update_check` notification. Even if an `acl_is_allowed` observer has already granted `true`, you need a second `acl_rsc_update_check` observer that does the same.

@mworrell Is this intentionally? Why the split between `is_allowed` versus `rsc_update_check`?

**Comment by mworrell** [comment]
The `rsc_update_check` is the moment that the ACL module can modify the properties of the to-be-updated resource. This is useful for sanity checks, defaults, and other modifications.

**Comment by ddeboer** [comment]
Right, but when mod_acl_user_groups is enabled, access will be denied (to edit an article, for instance) when the user has no permissions on the content group, even when an `is_acl_allowed` observer has already granted access (by returning `true`). It’s quite unpredictable behaviour to tell Zotonic: yes give access, and then still get an `{error, eacces}`.

**Comment by arjan** [comment]
This behaviour is indeed strange and has frustrated me in the past as well.
Can't we try to merge these notifications into one?

**Comment by ddeboer** [comment]
@arjan Yes. That’s exactly what I meant above:

> What’s currently missing in the ACL logic, is a single point of entry for checks. That single point should be z_acl:is_allowed.

**Comment by arjan** [comment]
And instead of `acl_rsc_update_check`, we already have the `rsc_update` notification, right?

**Comment by ddeboer** [comment]
Yes, we should use [rsc_update](sanity checks, defaults, and other modifications) for 

> sanity checks, defaults, and other modifications.

**Comment by mworrell** [comment]
The acl_rsc_update_check is to correct and modify the acl related properties of the resource before updating.

As such it has a different purpose than the update notification, and should be more restrictive.

We might want to check the logic in the acl module, to see if it is not too restrictive.

**Comment by mworrell** [comment]
I prefer to keep the acl related modifications separate from other modifications. In that way security is easier to check.

For the above issue we only need to check why the acl update check is so restrictive in the acl user groups module.

**Comment by arjan** [comment]
It is confusing that `acl_rsc_update_check` can actually deny updates; it should not do that because like David says that defeats the purpose of `acl_is_allowed`.

For just augmenting the props of the update I think it's OK to keep it.

**Comment by mworrell** [comment]
I have now checked the `mod_acl_user_groups` a bit more.

Observations:

 * Current `acl_rsc_update_check` does some real checks on the combination of content-group and category.
 * The insert check only checks on the category.

I think that we should change this.

 1. Only let the `acl_rsc_update_check` augment/normalize the ACL properties.
 2. Let the *can insert category* also take the content group into account.

This would be easier to understand.
We need then the to change the call on https://github.com/zotonic/zotonic/blob/master/src/models/m_rsc_update.erl#L631

```
z_acl:is_allowed(insert, #acl_rsc{category=CategoryName}, Context)
```

To also pass the content group id.

**Comment by arjan** [comment]
Yes and preferably change `acl_rsc_update_check` so that it no longer can cancel the update call?

**Comment by mworrell** [comment]
It is actually a *check*, so it think it is ok to be able to cancel the update.
But in this specific case it shouldn't check on the `eacces` permissions.

**Comment by arjan** [comment]
We can rename it to `acl_rsc_update`. For ACL checks, we have `is_allowed`.
If you really want to stop (when something is really really wrong) there's always `throw()` ... ;)

**Comment by ddeboer** [comment]
@mworrell Again: let’s try to get rid of checking the ACL in two places, and doing so in two different ways. We really only need `is_allowed`. 

> Only let the acl_rsc_update_check augment/normalize the ACL properties.

Can you give an example of what this augmentation/normalisation does?

If we really want to keep ACL checks in `acl_rsc_update_check` (which I don’t) it should just call `is_allowed`.

**Comment by mworrell** [comment]
@ddeboer Think of adding the default content group. In MaxClass it adds (and does sanity checks on) the school_id and class_id of all resources.

**Comment by arjan** [comment]
Couldn't this be done in the regular `rsc_update` hook?

**Comment by mworrell** [comment]
You need this for the ACL check itself, so it should be done before (or during) the *insert category* ACL check. The `rsc_update` hook is called when all is ok and the update will be running.

**Comment by arjan** [comment]
alternatively we could change or add to the `is_allowed` syntax so that it can augument the rsc properties?

**Comment by mworrell** [comment]
The `is_allowed` is used for all ACL checks, so it is just a direct notification and not a fold over the listeners.  If we allow it to start returning different properties then it would start returning:

 * `undefined`
 * `true` or `false`
 * `true` *if and only if you use these properties*

I think that would be a bit confusing.

**Comment by ddeboer** [comment]
What about simply adding the default content group id fallback to mod_acl_user_group’s `is_allowed` observer?

```erlang
m_rsc:p_no_acl(Id, content_group, DefaultContentGroupId, C)
```

Any custom things (`school_id`/`class_id`) can be checked in custom `is_allowed` observers.

**Comment by mworrell** [comment]
@ddeboer The content group should also be determined for resources that are inserted. This is currently done by taking the category and then checking into which content-groups this category can be inserted.

**Comment by ddeboer** [comment]
What’s wrong with having that lookup logic in `is_allowed` (or a helper function) as well?

**Comment by mworrell** [comment]
I am for letting the `acl_rsc_update_check` insert (or correct) any missing ACL related properties and then also pass the properties with the `is_allowed`.

I like to keep `is_allowed` a check and not have it update change the properties.

**Comment by ddeboer** [comment]
Agreed, `is_allowed` should be free from side-effects.

As @arjan observed, `m_rsc` already notifies `rsc_insert`/`rsc_update`, which are the right place to change the props that will be persisted:

```erlang
%% @doc Foldr for an resource insert, modify the insertion properties.
```

`mod_acl_user_groups` can add observers for these two notifications that then add the default content group. We then need to reverse the order: first notify `rsc_insert|update` and only then notify `is_allowed`.

**Comment by mworrell** [comment]
@ddeboer sounds reasonable. 

If this is changed then it needs to be documented extremely well, and we should even add deprecation errors if a module observes a deprecated notification.

**Comment by ddeboer** [comment]
Only the `acl_rsc_update_check` notification will disappear; adding the default group in `rsc_insert|update` will be a change internal to mod_acl_user_groups. So let’s:

1. Remove `observe_acl_rsc_update_check` from mod_acl_user_groups and mod_acl_adminonly.
2. Add deprecation warnings when `acl_rsc_update_check` is observed from any third-party code.
3. (Wait some months and then:) remove the `acl_rsc_update_check` notification entirely.

**Comment by mworrell** [comment]
Let's schedule a 1.0 issue for the removal, the *wait some months* will be near the end of the 0.x branch anyway.

**Comment by ddeboer** [comment]
Sure!

**Comment by mworrell** [comment]
`acl_rsc_update_check` has been removed.
