### ISSUE TITLE
Is there any way to create and download csv file in zotonic based website

### ISSUE THREAD

**Issue by tmadankumar** [zotonic/zotonic#1307]
It's not an issue, I am new to Zotonic, didn't find solution for my requirement, here is my problem, I have build a website using zotonic website, in my project i have requirement to insert erlang tuples list into csv file and need to download that file from UI, can anybody please guide me on my requirement.

**Comment by mmzeeman** [comment]
You can take a look at `mod_export`. It can be used to export data as csv.

**Comment by tmadankumar** [comment]
Hi Maas-Maarten Zeeman, 
Thank you very much for your response, 
i will look into mod_export module, i am facing issue with download file,

Csv file location: users/sites/mysite/sample.csv

and to download that file , i wrote code in .tpl file like below

<a href="http://MyIp:8000/sample.csv" download>{_ Download CSV _} </a>

but when i click on Download CSV on UI , it is throwing error like "no file"

please tell me ,how i can download file.

**Comment by mmzeeman** [comment]
Maybe you can look at mod_survey. It uses mod_export to export survey results in csv format.

I'm closing this issue for now. You can also ask for help on our gitter chatroom or on our mailinglist. See: http://zotonic.com/support

**Comment by ddeboer** [comment]
For future reference: I just updated the [mod_export doc chapter](http://docs.zotonic.com/en/latest/ref/modules/mod_export.html).
