### ISSUE TITLE
When adding to the hierarchy tree for menu/category/contentgroup a new resource doesn't show up

### ISSUE THREAD

**Issue by kathleenvw** [zotonic/zotonic#1309]
When editting the menu or another hierarchy item you can't directly add a new article/collection to the list.

Steps to reproduce:

- Log in on the admin
- Go to the menu
- Click on 'add menu item'
- Click on 'create page'
- Make a collection and add a title (and click publish)
- Click 'make'

The new item doesn't show in the list of menu items. If you then again click 'add menu item' and you look at the 'find page' you do see your new menu item and you can add it. Then it does show in the list of menu items.

**Comment by ddeboer** [comment]
Related to #1293?

**Comment by mworrell** [comment]
I think related to #1304 

Probably caused by the cleanup of the connection code (to more rely on the pubsub and less on javascript continuations)
