### ISSUE TITLE
Admin pages are always served via http even when https is enabled. 

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1314]
Admin pages are always served via HTTP, even when HTTPS is enabled.

It seems that the dispatch rules are missing the `{ssl, true}` directive. This will redirect the user to unsecured admin pages making all edits unsecured. This is not desirable as it makes using the admin over unprotected networks insecure.

**Comment by mmzeeman** [comment]
https://github.com/zotonic/zotonic/commit/71553f979bc8d8a7244f1b83869aefd932ee26f6

Did I miss any? 

@arjan, @ddeboer, @mworrell This should also be cherry-picked to the stable branch, and possibly backported to older releases.

**Comment by ddeboer** [comment]
Shouldn’t `{ssl, true}` be the default for dispatch rules? It seems we can already do this by [setting](http://zotonic.com/docs/latest/ref/modules/mod_ssl.html#configuration) `mod_ssl.is_ssl` to true.

**Comment by mmzeeman** [comment]
Good one, we should support secure defaults.

**Comment by mworrell** [comment]
Yes, the insecure ones are basically 2009 compatibility with (back then) non-https youtube embeds...

**Comment by ddeboer** [comment]
@mworrell This is fixed on master, right?

**Comment by mworrell** [comment]
Yes. The master is quite a bit more aggressive in choosing https over http.
