### ISSUE TITLE
Store Mnesia cache in Erlang node-specific directory

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1321]
When the node name changes (when switching between Zotonic branches or due to network changes) now causes the filezcache (and e-mail queue) application to fail to boot. So let’s give each node its own Mnesia subdirectory.

As discussed with @mworrell.

**Comment by mworrell** [comment]
This has been done on 0.x and master.

There is now a directory `priv/mnesia/nodename@host/...`
