### ISSUE TITLE
Race condition in CI test

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1325]
Sometimes the CI fails with some errors that are due to race conditions where modules are apparently not yet completely initialized before the test is running.

https://travis-ci.org/zotonic/zotonic/jobs/139836770#L1563

```
18:17:56.225 [info] [testsandboxdb] info @ z_datamodel:169  Creating new category 'content_group'
18:17:56.280 [info] [testsandboxdb] info @ z_datamodel:169  Creating new content_group 'system_content_group'
18:17:56.287 [info] [testsandboxdb] info @ z_datamodel:169  Creating new content_group 'default_content_group'
mod_acl_user_groups_tests: person_can_edit_own_resource_test (module 'mod_acl_user_groups_tests')...*failed*
in function mod_acl_user_groups_tests:person_can_edit_own_resource_test/0 (modules/mod_acl_user_groups/tests/mod_acl_user_groups_tests.erl, line 10)
**error:{badmatch,{error,not_active}}
```

**Comment by ddeboer** [comment]
So `activate/3` has returned, but according to `active/1` the module is [not active yet](https://github.com/zotonic/zotonic/blob/master/src/support/z_module_manager.erl#L125). 

Could this be a race condition against the database query in `active/1`?

**Comment by mworrell** [comment]
I think it might have something to do with the `memo` call.
The flush might actually be async, so memo will get an old version.

In general I think the check should be changed to checking of the module is actually running, and not if the module is activated in the database.

**Comment by mworrell** [comment]
Maybe check `whereis(Module, Context)` and see if we get a alive pid?

**Comment by ddeboer** [comment]
Yes!

**Comment by mworrell** [comment]
This didn't fix the issue.

https://travis-ci.org/zotonic/zotonic/jobs/139845060#L1181

**Comment by ddeboer** [comment]
It may have to do with dependent modules still booting?

```
18:51:50.692 [error] [testsandboxdb] Could not start mod_authentication: Missing dependencies: [acl]
18:51:50.692 [error] [testsandboxdb] Could not start mod_admin: Missing dependencies: [authentication]
18:51:50.693 [error] [testsandboxdb] Could not start mod_admin_identity: Missing dependencies: [admin]
18:51:50.693 [error] [testsandboxdb] Could not start mod_admin_category: Missing dependencies: [admin]
18:51:50.693 [error] [testsandboxdb] Could not start mod_admin_predicate: Missing dependencies: [admin]
18:51:50.693 [error] [testsandboxdb] Could not start mod_admin_modules: Missing dependencies: [admin]
18:51:50.693 [error] [testsandboxdb] Could not start mod_admin_config: Missing dependencies: [admin]
```

**Comment by mworrell** [comment]
Fixed

**Comment by mworrell** [comment]
BTW also got some a failed CI build due to some timeouts in the tests.  Let's keep an eye on it to see if that happens more often.
