### ISSUE TITLE
There should be a way to set HSTS headers

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1329]
It would be incredibly nice for TLS-enabled Zotonic websites to be able to set an HSTS (HTTP Strict-Transport-Security) headers.

The header should have a configurable max age and allow configuring other directives (such as includeSubDomains and preload) as required. If enabled, it should be included on every response served over HTTPS (taking into account possible TLS-offloading proxies.)

See also https://tools.ietf.org/html/rfc6797.

**Comment by ddeboer** [comment]
Skimming over the RFC, I see only two directives: `includeSubDomains` and `max-age`: is the latter the one you mean by preload?

**Comment by mworrell** [comment]
I am redoing `mod_ssl` a bit. My plan is to make it aware of any SSL terminator proxies in front of the site. In that case we can add these headers to mod_ssl, just like the *secure* flags for the cookies.

**Comment by mworrell** [comment]
BTW I will need a way to see if the request originated via SSL or not. Is there any information added in haproxy (or other SSL terminators) to derive this?

**Comment by CyBeRoni** [comment]
RFC7239 defines such a thing.

**Comment by ddeboer** [comment]
Exactly: what used to be `X-Forwarded-Proto` has now become `Forwarded: proto=https`. So then the logic becomes simple: when mod_ssl is enabled, set the `Strict-Transport-Security` header either
- if the current requests is oer HTTPS
- or if `Forwarded: proto=https` is set.

**Comment by mworrell** [comment]
Merge the changes in #2297 into master
