### ISSUE TITLE
Unable to update a resource with a new property using a list as its name

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1330]
When updating a resource with a new property, the name of that property can not be a list unless you set the is_import flag in the options. This prevents us from defining new props when posting a form (for example adding a field to one of the admin edit screens).

The easiest way to reproduce is on the shell with the following expressions.

````
(zotonic001@15fa29a530ac)13> m_rsc_update:update(1, [{"sapperdeflap", 0}], z_acl:sudo(z:c(somesitename))).
** exception error: bad argument
     in function  list_to_existing_atom/1
        called as list_to_existing_atom("sapperdeflap")
     in call from m_rsc_update:map_property_name/2 (src/models/m_rsc_update.erl, line 870)
     in call from m_rsc_update:'-normalize_props/4-lc$^0/1-0-'/2 (src/models/m_rsc_update.erl, line 511)
     in call from m_rsc_update:'-normalize_props/4-lc$^0/1-0-'/2 (src/models/m_rsc_update.erl, line 511)
     in call from m_rsc_update:update_normalize_props/3 (src/models/m_rsc_update.erl, line 297)
(zotonic001@15fa29a530ac)14> m_rsc_update:update(1, [{sapperdeflap, 0}], z_acl:sudo(z:c(somesitename))).  
{ok,1}
(zotonic001@15fa29a530ac)15> m_rsc_update:update(1, [{"sapperdeflap", 0}], z_acl:sudo(z:c(somesitename))).
{ok,1}
````

Do we really need to map each prop name to an atom?

**Comment by mworrell** [comment]
Just do one of the following:

 * use the atom in your template, for example by requesting the property

 * use the atom in one of your site or module erlang modules

And yes, we standardized on atoms, which are much more efficient and have far less memory overhead.

**Comment by ddeboer** [comment]
@Dirklectisch Did you have the custom value in your input already?

```html
<input type="text" name="custom_thingie" value="{{ custom_thingie }}" />
```

**Comment by mworrell** [comment]
@Dirklectisch we can't just randomly make new atoms from lists as that would exhaust the available atom space.

(hmmm, that sounds funny in non Erlang context...)

**Comment by Dirklectisch** [comment]
@ddeboer We had set the value to a static string. 
@mworrell I know there is a limited atom space and that they are not garbage collected. That last part sounds especially weird to me, since there is no way to clean them up manually right?

So I guess we decide to just keep this edge case in mind for now?

**Comment by ddeboer** [comment]
@Dirklectisch Would `value={{ custom_thingie|default:"your static string" }}` work?

**Comment by mworrell** [comment]
@ddeboer yes, that would define the atom during template compilation.

**Comment by mworrell** [comment]
@Dirklectisch garbage collecting atoms is a difficult problem, and I don't expect a solution to it.

**Comment by Dirklectisch** [comment]
Let's just consider this closed for now, because I fail to see what actions we can take.

**Comment by ddeboer** [comment]
Quick summary for future reference: this issue only occurs when trying to *write* a property from a template that is not being rendered. 

So this (the exception) fails:

```html
<input type="text" name="custom_thingie" value="{{ custom_thingie }}" />
```

While this (the usual case) works:

```html
<input type="text" name="custom_thingie" value="{{ custom_thingie|default:"some nice default" }}" />
```
