### ISSUE TITLE
What should we do with z_user_agent sniffing?

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1347]
Recently I tried to update the device classifier databases of our user agent classifier. What I found was that the project we based our classifier on has stopped and (sort of) merged with Apache.

See: https://issues.apache.org/jira/browse/DMAP-11

This means that we either have to move our device map to use the device data from apache or maybe stop using the user agent sniffer.

See also: 

http://devicemap-vm.apache.org/data/snapshot/

and 

https://github.com/zotonic/ua_classifier/issues/3

**Comment by mworrell** [comment]
Related #1346

**Comment by mworrell** [comment]
From #1346:

Do we want to continue sniffing the user agent and device type? If so then we need to fix the above ua_classifier issue.

If not then we should remove the device types from Zotonic. And probably expedite the img srcmap implementation.

**Comment by mworrell** [comment]
I am leaning towards removing the feature from the 1.0.

Reasoning:

 * Browsers are now a lot better than in 2012
 * Responsive designs work well nowadays
 * The srcmap for images can replace device dependent mediaclass configs
 * Some phones can now display on big screens, confusing device selection

This would mean that we should remove the text/phone/tablet/desktop directories and that people have to choose which templates they keep when moving to 1.0.

/cc @arjan @ddeboer @ArthurClemens

**Comment by ArthurClemens** [comment]
I agree.

**Comment by ddeboer** [comment]
So do I.

At Driebit we don’t use the text/phone/tablet/desktop division either. Perhaps our frontend experts @Devenwel @Dirklectisch @DorienD @gunnar-driebit can give some input to this question of dropping user agent sniffing and device selection.

**Comment by arjan** [comment]
I have always found this device class feature quite untransparent and have always used media queries instead, so :+1: from me. Simpler = better :)

**Comment by mworrell** [comment]
Looks like it is already decided 👍 ♻️

**Comment by mworrell** [comment]
Do we want to keep the sniffer?
I propose to just remove that one as well, as screen sizes change dynamically anyway.
