### ISSUE TITLE
Filewatcher sitetest regex is wrong

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1349]
The [regex](https://github.com/zotonic/zotonic/blob/master/src/filewatcher/z_filewatcher_handler.erl#L333) doesn’t actually work for the `example_administrator_name_sitetest.erl` from the [documentation](http://zotonic.com/docs/latest/developer-guide/testing.html#example-sitetest-module) because it extracts site name `example_administrator` instead of `example`. Removing one underscore (`example_name_sitetest.erl`) *does* work.

Unfortunately, site names (atoms) can contain underscores, so we have to include them in the match.

**Comment by arjan** [comment]
Hmm yes. The issue is that its not really possible to have both site and test name contain underscores. Clearly the documentation is wrong, fixing the documentation would be the easiest.

The pattern would then be: *sitename_testname_sitetest.erl* where 'testname' *cannot* contain underscores.

**Comment by ddeboer** [comment]
Yeah, apart from checking for each regex match whether it corresponds to an existing site, I guess that’s the only option.

**Comment by mmzeeman** [comment]
BTW, we also have this other filewatcher issue: #1120 It could be that the filewatcher doesn't pick up changes depending on how your sites and modules are setup. This is when fswatch is used.
