### ISSUE TITLE
SSL doesn't work on 0.18.0 with erlang 18

### ISSUE THREAD

**Issue by alvaropag** [zotonic/zotonic#1351]
I'm having problems with SSL on Zotonic 0.18.0 and erlang 18. I've read all the docs and tried many things, but it doesn't work. The same site run normally on zotonic 0.16.0. Version 0.17.1 also have problems with SSL.

It seems there is no available cipher to be used, but I was not able to pin point the problem. So I've attached the zotonic log and other information on this pastebin url [pastebin_log](http://pastebin.com/MjtpjLas) (it's a lot of information).

The error is  
16:29:36.228 [error] SSL: hello: ssl_handshake.erl:169:Fatal error: internal error
16:29:36.232 [error] SSL: hello: tls_handshake.erl:118:Fatal error: inappropriate fallback

and chrome show me this when I try to acess the site with ssl
This site can’t provide a secure connection

teste.dev sent an invalid response.
Try:
Reloading the page
Learn more about this problem.
ERR_SSL_PROTOCOL_ERROR

If more information is needed, please let me know.

**Comment by mmzeeman** [comment]
Did you enable `mod_ssl_self_signed`?

**Comment by mworrell** [comment]
And try the newest Erlang (I think 18.3?)

- M

**Comment by alvaropag** [comment]
Yep, it is erlang 18.3 and I hadn't noticed this new module. 
Activating mod_ssl_self_signed resolved it.
Thank you!

**Comment by ddeboer** [comment]
@alvaropag Good that you were able to solve this! Closing this issue, but if you think that we can improve the Zotonic docs on SSL, please let us know here!
