### ISSUE TITLE
Template per unique name

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1361]
As suggested by @loetie: we already have category-specific templates, but what about templates for a single resource, so `page.resource_unique_name.tpl`? This would come in handy for unique pages that need a custom template.

Currently, we:
* either create a category with only a single item in it, which is somewhat misleading in case of unique pages;
* or create a custom dispatch rule (``{bli, ["bli", "bla"], controller_template, [{template, "custom-template.tpl"}, {id, resource_unique_name}]}``), which moves the URL selection out of the admin (`page_path`) into dispatch rules that are invisible to editors.

**Comment by arjan** [comment]
I think this is already possible with the catinclude. It checks the `name` property of the rsc as well.

**Comment by arjan** [comment]
I often create pages like `page.page_home.tpl` for the `page_home` resource.

**Comment by arjan** [comment]
"When the resource has a unique name (the name property is set), this property is also considered for the catinclude lookup, before the category-based template names"

http://zotonic.com/docs/latest/ref/tags/tag_catinclude.html

**Comment by ddeboer** [comment]
Whoops, missed that, thanks @arjan!

**Comment by ddeboer** [comment]
Added a piece to the docs to clarify the current functionality a bit.
