### ISSUE TITLE
Document unique filter

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#1362]

**Comment by ddeboer** [comment]
Whoops, this is a Ginger, not a Zotonic filter:

```erlang
unique(List, _Context) ->
    lists:usort(List).
```

@mworrell Does this filter make sense for Zotonic? If so, we can add it here.

**Comment by mworrell** [comment]
Looks useful. Shouldn't it be called usort? Or is 'unique' consistent with some other tools?

**Comment by ddeboer** [comment]
`usort` is more Erlangy, so it depends on how much Erlang we want to expose templaters to. :wink:
