### ISSUE TITLE
Unbashify all the scripts

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1365]
Zotonic currently assumes bash is installed. This is not universally true, and is becoming less and less true with the push towards lightweight containers. We should make Zotonic work with only the POSIX shell (/bin/sh) installed.

**Comment by Dirklectisch** [comment]
There is a certain amount of bash bashing going on in this thread.

**Comment by ddeboer** [comment]
Let’s stop bashing around the bash then!

**Comment by arjan** [comment]
PR's welcome, @CyBeRoni  :P

**Comment by mworrell** [comment]
See also #1880
