### ISSUE TITLE
Completely disable SSL

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1367]
@CyBeRoni and I just discovered that Zotonic *always* listens on 8443 (by default) for SSL connections, even if mod_ssl is disabled. Is there currently a way to completely disable the SSL listener? This is useful for those who have an SSL terminator in frontend of Zotonic.

**Comment by mworrell** [comment]
You can now disable the ssl listener by setting the by setting `ssl_listen_port` to `none`.

/cc @CyBeRoni
