### ISSUE TITLE
Support building without a configuration file

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1372]
Zotonic builds currently require a zotonic.config somewhere, to check for any local dependencies (and perhaps other things?) If no config file is available, one is installed somewhere, which is a side-effect to building that many would consider unwanted. 

I think either the build should check for a config file and use it if available but ignore its unavailability, or local deps should be put in some other local config file (for which, the same.)

For reference the error you get when building without a config file is as follows:

```
===> Evaluating config script "rebar.config.script"
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: {badmatch,
                        {error,
                            {12,file,
                             {error,{badmatch,[]},[{erl_eval,expr,3,[]}]}}}}
```

(Reproduce by setting ZOTONIC_CONFIG_DIR to some directory with no config and trying to build.)

**Comment by ddeboer** [comment]
To give some context: we run into this problem when building Docker images. The base Zotonic image will not have a custom `zotonic.config` so should build well without one. 

The most predictable course of action is the first: just ignore the fact that no config file is to be found (and don’t create one, as `zotonic_setup` currently does). Many of the default config values are already available in the Erlang code anyway (for instance, db credentials), so we don’t have to rely on the setup script for them.

@CyBeRoni But what does other software do in this case? It’s a well-established pattern for (e.g.) Linux packages to install some default config file in `/etc/` that users can then go and change if needed.

**Comment by CyBeRoni** [comment]
>  It’s a well-established pattern for (e.g.) Linux packages to install some default config file in /etc/ that users can then go and change if needed.

Only when *installing* the software. *Building* it should not have side-effects outside of the build directory.

**Comment by arjan** [comment]
I think it's okay to change it like this: install the config file when Zotonic is first started (and if it doesn't find a config file), dont add any config files while it's being compiled.

**Comment by CyBeRoni** [comment]
That's reasonable; writing the config file can be prevented by setting ZOTONIC_CONFIG_DIR already.

**Comment by mworrell** [comment]
With 1.x you can use rebar config files.
