### ISSUE TITLE
translation_scan is broken in master

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1377]
* `scan_file` expects binary extension while it receives a string. This is because z_module_indexer returns strings
* `insert` receives different input than it expects

**Comment by alvaropag** [comment]
@ArthurClemens Did you fix it? If not I can give a look at it.

**Comment by ArthurClemens** [comment]
Please go ahead.

**Comment by alvaropag** [comment]
Ok!

**Comment by ddeboer** [comment]
I merged zotonic/template_compiler#7. @alvaropag Do you want to continue prepping `mod_translation` for #1371?

**Comment by alvaropag** [comment]
Yep, sorry, busy week, will send ASAP the pull request with the fixes.

**Comment by ddeboer** [comment]
No problem, Álvaro! Please let us know if you get stuck or have any questions when fixing the translation_scan.

**Comment by mworrell** [comment]
@alvaropag  I suspect the problem with the scan of `.erl` files is that we sometimes don't have the right include paths for the Erlang parser. This gives an error during the parsing of the source file.

There is a new parser in `syntax_tools` (Erlang 18+) that only parses and doesn't do any includes. We might want to give that one a try.

**Comment by alvaropag** [comment]
Thanks @ddeboer ! 
@mworrell Nice, I didn't know about this new parser, I'll give a look at it this weekend. Which versions of erlang are we supporting?

**Comment by mworrell** [comment]
In master we only support Erlang 18 and later.

**Comment by alvaropag** [comment]
Ok, so it's safe to use it :D

**Comment by ddeboer** [comment]
Just tried `translation_scan` and it’s (now) working fine. Can we close this issue or am I missing something?
