### ISSUE TITLE
mod_twitter and hashtag 

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1383]
Hi,
More question than issue.
Is there any smart way to list tweets from mod_twitter that match some hashtags ?
Did somebody did this ? 
Do not find any entries in issue history... 
Thanks !

**Comment by ddeboer** [comment]
Currently [mod_twitter](http://zotonic.com/docs/latest/ref/modules/mod_twitter.html) is more about importing tweets into Zotonic than being a fully-fledged Twitter API client. That said, you can use `oauth_twitter_client:request/4` to retrieve data through the Twitter [search API](https://dev.twitter.com/rest/public/search). Something like:

```erlang
Access = {
    z_convert:to_list(m_config:get_value(?MODULE, access_token, Context)),
    z_convert:to_list(m_config:get_value(?MODULE, access_token_secret, Context))
},
Args = [
    {"q", "%23some_hashtag"}
],
oauth_twitter_client:request(get, "searhc/tweets.json?", Args, Access, Context).
```

**Comment by crownedgrouse** [comment]
thanks David,
this is exactly what I needed.
Closing.

**Comment by crownedgrouse** [comment]
hum, something I do not understand.
I tried to set-up 'normal' use of mod_twitter for now , by follower related documentation, but do not work.
in mod_twitter documentation , i have to setup config entrie with `mod_twitter / api_login` and `mod_twitter / api_password` but I get : 
"Twitter: not configured for automatic tweet imports." in debug console.
By looking at code , some other entries are used : 
```
AccessToken = m_config:get_value(?MODULE, access_token, Context),
AccessTokenSecret = m_config:get_value(?MODULE, access_token_secret, Context),
```
by creating those entries, not better.
Are those entries the same ? Documentation does not mention thoses entries for twitter.
What do I miss ?

**Comment by mworrell** [comment]
You can set all necessary configuration keys in the admin (/en/admin/authentication-services).

Menu: **Auth** -> **App Keys & Authentication Services**

**Comment by crownedgrouse** [comment]
Hi Marc, work better : I now get "Twitter: following 1 users and 0 phrases"
but I do not see any tweets imported under category tweet. Are all past tweet imported or only new ones ? but, I added a tweet on the account after set-up , but nothing imported. Is it realtime streamed ?

**Comment by crownedgrouse** [comment]
I tried by adding some hashtags to follow in admin/authentication-services , but no more chance...
no error in console. I'm stuck in the mud.   Should I use a particular zotonic release to let it work ? Currently using 0.14.

**Comment by ddeboer** [comment]
If possible, please try to upgrade to the latest version (0.19.2). Does that help?

**Comment by crownedgrouse** [comment]
unfortunately not. 
Anyway, I'm up-to-date to  last release now...
when changing things in  "Auth -> App Keys & Authentication Services" I get : 
`[error] Twitter stream disconnect: {ok,terminate}`
so I suppose it was connected before, that said, I do not see any reconnect then.
Is it normal ?
No entry in tweet category while writing some more tweet matching the phrases I set-up...

Note : In select box in menu Auth there is htmlentity not evaluated :  "App Keys &amp; Authentication Services" . Is it something I should open a ticket ?

**Comment by crownedgrouse** [comment]
is there some twitter settings to set-up on listened twitter account ? (privacy and son on ?)

**Comment by crownedgrouse** [comment]
alive, it's alive ! :) 

I found the issue : twitter account must have tweet unprotected https://support.twitter.com/articles/20169886# , i.e public.
it might be useful to precise it in documentation.

**Comment by ddeboer** [comment]
> I found the issue : twitter account must have tweet unprotected 
> it might be useful to precise it in documentation.

Done: #1387.

> In select box in menu Auth there is htmlentity not evaluated : "App Keys & amp ; Authentication Services"

Thanks, I’ll fix that as well.

**Comment by crownedgrouse** [comment]
Thanks, 
Feel free to close, then.
There is however something to check: does the stream reconnect after changing tweet Auth settings ?
