### ISSUE TITLE
Don't exclude db tests

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1392]

**Comment by mmzeeman** [comment]
Indeed, adding unit,- and functional (db) tests should be easier. I think embedding them in the module itself should also be possible. That way adding new tests for new functionality becomes simpler.

**Comment by ddeboer** [comment]
> embedding them in the module itself should also be possible

I do like having the tests in module separate from the implementation code itself. When #1393 is merged, you can just add tests by creating `*anything*_tests.erl` in `src/tests`.

**Comment by ddeboer** [comment]
Fixed.
