### ISSUE TITLE
Update documentation for 1.0

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1399]
- [x] check chapters like directory structure that are not updated with the rebar3 changes.
- [x] update Upgrading section ([example with before and after headers](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md))
- [x] Document model changes (in upgrading section)
- [x] document datamodel list type that was removed
- [x] document Let’s Encrypt (#1502)
- [x] document relation between `lib-src` and `lib`
- [x] document `Makefile` usage for `lib-src`
- [x] Consistent terminology for SSL/TLS/HTTPS
- [x] Cherry-pick [Custom controller cookbook](http://docs.zotonic.com/en/0.x/cookbook/custom-controller.html) from 0.x

**Comment by mworrell** [comment]
We might want to add an example controller in the documentation, showing all possible callbacks.

**Comment by ddeboer** [comment]
Good idea, I’m definitely in favour of examples. :wink:
