### ISSUE TITLE
Structure is_allowed checks

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1401]
Supply `is_allowed` arguments as either tuples or records, so it’s easier for developers to plug in their own custom ACL checks (other than `view resource id`). We can then also re-add a `m_rsc:rid` to allow both resource ids and resource names to be passed as arguments. E.g.:

``` erlang
#acl_rsc{action = view, object = resource_name_or_id}.
#acl_module{action = use, object = module_name}.
#acl_custom{action = weird_permission, object = some_custom_id_thingie}.
```

See also #1398.

**Comment by ddeboer** [comment]
Apparently we already have some of these: `#acl_rsc{}`, `#acl_edge{}` and `#acl_media{}`: https://github.com/zotonic/zotonic/blob/master/include/zotonic.hrl#L170-L177.

**Comment by mworrell** [comment]
Indeed, they can be supplied to the `z_acl` routines.

We just have the convention that an integer is assumed to be a resource id, unless stated otherwise.

**Comment by ddeboer** [comment]
I don’t think so. Closing.
