### ISSUE TITLE
Make acl_user_groups_checks:is_owner a notification

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1403]
So client sites can have some custom logic as to when a user is a owner, for instance if the user has an author edge to the article in question.

**Comment by mworrell** [comment]
#1404 also changes the view rule of unpublished content inside collaboration groups. 
Now you can see unpublished content if you have rights to see content in the collaboration group.
For non-collaboration groups the content is only viewable iff it is published or the user has update rights.

**Comment by ddeboer** [comment]
> For non-collaboration groups the content is only viewable iff it is published or the user has update rights.

This is the old behaviour, right?

**Comment by mworrell** [comment]
Yes, that is the old behavior, so it is unchanged for non-collaboration groups.

**Comment by mworrell** [comment]
Closing issue, as the merge has been done.

@ddeboer Thanks!
