### ISSUE TITLE
Re-add error and access logs

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1406]
Now Cowboy has been merged in master (#1355). See also #1067.

Ideas from @mmzeeman and @mworrell:
- [ ] Only log interesting errors (4xx, 5xx), 2xx and 3xx are not so interesting and just fill up the logs
- [ ] Also log 500 errors due to crashes
- [ ] Exometer stats for request http status code (histogram)
- [ ] Exometer stats for request duration (95 and 99 percentile) (histogram)
- [ ] Possibility to log slow (duration) requests
- [ ] Connection with security monitors (frequency, ip-address etc)

**Comment by ddeboer** [comment]
@mworrell Is this something you want to work on or do you prefer some help? :wink:

**Comment by mworrell** [comment]
I assign it to me and @mmzeeman, we have some ideas.

**Comment by mworrell** [comment]
@CyBeRoni I guess you want this to be hooked up into your logging systems as well?  We can maybe hook it into exometer and push those periodically to your systems?

**Comment by CyBeRoni** [comment]
A network log destination (syslog, tcp, udp) and some sort of filtering ability would be nice, yes. I don't myself care very much about 2xx/3xx but I can imagine others would.

**Comment by mworrell** [comment]
I think per default we should drop 2xx/3xx. Do we have some simple overview of formats to push? Especially the logs, there are already exporter for exometer stats.

**Comment by mmzeeman** [comment]
For us the 2xx/3xxx responses are interesting. We mainly use them for (offline) counting the usage of our service for our clients (referrer). We currently currently have around 7M hits daily... 

I have to check, but we may have to store 2xx/3xx for a couple of days for accountability reasons.

What would be nice to have is exometer stats per dispatch rule. The overall stats of the entire machine are not that interesting (IMHO). The thing is that some dispatch rules are slower than others for a good reason. For instance controller_comet also messes up the 95 percentile of the site. ;-)

**Comment by mmzeeman** [comment]
The old master logged its access log via `syslog(3)`.Then you can use the local machine to distribute the data elsewhere if needed. That is probably the most efficient way to deal with this @CyBeRoni?

**Comment by mworrell** [comment]
@mmzeeman for the usage counting per referrer - do you need to have proof of that usage for accounting or are just the running statistics good enough?

I envision a custom logger for this, but one which receives aggregated results and can decide what to log.

**Comment by mmzeeman** [comment]
@mworrell Some clients want accountability logging, but this is more on the application level then the http level I think. Tomorrow I have a meeting with the security and accountability department of one of our clients on this subject.

**Comment by ddeboer** [comment]
Let’s also standardise the log messages by *always* adding the current site name.

**Comment by mworrell** [comment]
For the error log, yes.

For the access logs, if we log to a file then it is better to have a file per site.

**Comment by mworrell** [comment]
BTW for lager logs, there is a lager metadata set, we need to show it in the logs

**Comment by mmzeeman** [comment]
For the access logs it might be handy to implement it as a cowboy middleware solution so other cowboy users can use it as well.

**Comment by mmzeeman** [comment]
This is a writeup on what I learned when investigating this issue during the Hackday.

We run on a pre 2.0 version of cowboy. This version lacks the `onresponse` hook the 1.1 and 1.0 version of cowboy. The reason for this is that cowboy 2.0 is completely restructured to implement http2.

It is possible to use middleware modules, but by implementing logging this way we will not be able to log error 500 and 400 responses handled by cowboy.

For cowboy 2.0 there will be a configurable list of `stream_handlers` similar to the middleware handlers. This is an excellent point to add logging, especially when combined with middleware hooks.

The idea is now to implement a module which acts as stream handler and middleware which can be used to log and collect statistics. The stream handler hook is planned for cowboy 2.0.0-pre-5. But we can start with this by implementing our own stream handler which delegates calls to cowboy's default stream handler.

**Comment by ddeboer** [comment]
Thanks for this summary. Sounds like a good plan. Do you have some time to start working on the Zotonic stream handler?

**Comment by mmzeeman** [comment]
Not really, but I see what I can do. That is why I wrote it down.

**Comment by mmzeeman** [comment]
Cowboy 2.7.0 has a usable way to handle logging, so we can add this. 

With this it is possible to add metric values which make sense for us, like the site, dispatch name etc.

```
cowboy_req:cast({set_options, #{metrics_user_data, #{foo => "bar"}}}, Req}
```

A metrics callback has to be passed in the listener. It will be called when the request finishes.

It is also possible to filter the items passed to the metrics callback https://ninenines.eu/docs/en/cowboy/2.7/manual/cowboy_metrics_h/
