### ISSUE TITLE
Remove visible_for/can see

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1407]

**Comment by mworrell** [comment]
This actually might be an issue for systems running the `acl_admin_only` or other (older or own developed) ACL modules. So, in retrospective, we might want to keep this in the system and just disable it for the modern `acl_user_groups` module.

**Comment by ddeboer** [comment]
But then we end up with a bunch of unused code. Why not keep it in 0.x and only remove it in master?

**Comment by mworrell** [comment]
It is not so much unused code... we can actually remove some fallbacks etc, and make sure that the can_see behavior is incorporated in the acl_admin_only module (and friends).

We should keep the database field and support in the update routines.

The panel in the admin could be moved to the ACL modules.

**Comment by mworrell** [comment]
I know of some systems where this is used to hide content from the public, if those are upgraded then they have a major security problem.

**Comment by ddeboer** [comment]
Have a look at #1408 for the code that went right out of the window. :wink:

> We should keep the database field and support in the update routines.

Right, let’s not drop BC without reason. However, I think we have a good reason here: it improves code maintainability to not have too much legacy stuff in there. 

> This actually might be an issue for systems running the acl_admin_only or other (older or own developed) ACL modules.

Are those systems that will likely be upgraded to 1.0? If so, let’s encourage their maintainers to switch to mod_acl_user_groups. That relieves us from the burden of having to move the visible_for logic to that module and keep maintaining it.

**Comment by mworrell** [comment]
@ddeboer Yes, they will be upgraded and are quite big.  As in: MaxClass, Women on Web etc :)

I propose to:

 * Keep the `visible_for` db field, make clear it is for ACL modules
 * Keep the update routines in `m_rsc_update`
 * Move the *can_see* functionality and the default visible-for admin templates to the respective ACL modules

This will clean up the core and still provide support for different kind of ACL modules.

**Comment by ddeboer** [comment]
Okay! What about this variant?

* Remove the `visible_for` db column but add an `ALTER TABLE` to the ACL modules where we add the column (if it doesn’t yet exist). That way, fresh 1.0 sites that don’t use mod_acl_user_groups don’t have the obsolete `visible_for` column, but older sites (on admin_only, or simple_roles) do.

**Comment by mworrell** [comment]
I really don't like to ALTER the rsc table because we enable some module.
Just keep the column, as it is very useful for different ACL modules.

Those other custom ACL modules also don't use the content_group column ;)

/cc @arjan -- your opinion?

**Comment by mworrell** [comment]
And, actually, I can also see use for the visible_for column to differentiate content within a single content-group.

**Comment by ddeboer** [comment]
> I really don't like to ALTER the rsc table because we enable some module.

Why? Sounds like a good separation of concerns to me.

**Comment by mworrell** [comment]
Because updating a rsc table with a million records takes a very very long time.

**Comment by mworrell** [comment]
Proposal: keep it for now, and schedule possible removal together with a more major cleanup of the rsc table for the 1.1 or 2.0

**Comment by ddeboer** [comment]
Right, Postgres will then rebuild the whole table.

Okay, let’s keep the column and only remove the semantics (integers 0–3) from the core.

**Comment by mworrell** [comment]
Yes, only keep the column as-is, remove all interpretation of the column (except the notion that it should be an integer)
