### ISSUE TITLE
Update spec definitions

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1410]
From `@spec` to `-spec`, so Dialyzer (#1322) can spot errors and hopefully spits out less errors. :wink:

**Comment by mworrell** [comment]
Maybe this is interesting for type checks:

https://github.com/josefs/gradualizer

It might make the spec work more gradual instead of having a big bang moment with Dialyzer

**Comment by mworrell** [comment]
We are now using Dialyzer.
