### ISSUE TITLE
Rename use_absolute_url to absolute

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1416]
[`use_absolute_url`](http://zotonic.com/docs/latest/ref/tags/tag_url.html#generate-absolute-urls) (for `url`, `image` and `lib`) is needlessly verbose, in my opinion; besides, the URL is not ‘used’, but generated.

**Comment by mworrell** [comment]
Also, the tag `{% url ... %}` could have an additional one: `{% url_abs ... %}` which covers most of the use cases for the `use_absolute_url` flag.

**Comment by ddeboer** [comment]
Yeah, that’s another possibility. I think I prefer the `absolute` option for a more generic `{% url %}` tag, as that’s what devs will look for first when they want to generate URLs.

**Comment by mworrell** [comment]
Should we name it `is_absolute` instead?

**Comment by ddeboer** [comment]
See #1532: I decided to keep `url`, so `absolute_url`, because for `{% lib %}` and `{% image %}` it may be unclear that it’s the URL that you’re making absolute. We could change it to `is_absolute_url`, of course.

**Comment by mworrell** [comment]
For boolean values it is good use to use prefixes as `is_` and `has_`. That makes the usage clearer. /cc @mmzeeman

**Comment by ddeboer** [comment]
Makes sense. Particularly for (ex-)OO people, though, `is_` may sound a bit weird: it’s not about *asking* whether the URL is absolute but about *telling* to make the URL absolute.

**Comment by mworrell** [comment]
We are using the `is_` prefix on quite some different places to pass flags.

In this case it is a property of the generated URL, not necessarily an instruction to the the algorithm generating the URL.

**Comment by ddeboer** [comment]
> We are using the is_ prefix on quite some different places to pass flags.

Can you give an example?

For boolean params in template tags, a quick search yields `{% button disabled %}`, `{% pager hide_single_page %}`, `{% script nostartup|nostream %}`, `{% validate only_on_submit %}`.

**Comment by mworrell** [comment]
The `disabled` in the button is a HTML attribute. For programmatic variables we have quite some `is_` variables (and template arguments).

Searching in the templates on master I see (among others): `is_nocatselect`, `is_editable`, `is_cg_reload`, `is_active`, `is_connected`, `is_linkable`.

In scomps we only have `is_superfish`.

**Comment by ddeboer** [comment]
Right, but the tags are what users interact with primarily (instead of builtin templates). Moreover, `absolute_url` is itself a tag param. So while I’m okay with changing to `is_`, we should then also change the other tag params, such as `only_on_submit`, `hide_single_page` etc. When considering this, the imperative nature of scomps (‘render this thing here in such and such a way’) feels different from params in templates.

**Comment by mworrell** [comment]
:) I am ok with both solutions.

Of course if we use `absolute_url` then we could also assign some other value to it, like a base-url for the url generation. So just go with what you have now.

**Comment by ddeboer** [comment]
Yeah, heated discussion this, on a relatively minor issue. Although naming things is one of the important things in computer science, of course. :wink:

Okay, I’ll just keep `absolute_url` for now (so #1532 can be merged). We can always deprecate and rename the properties later (even on 1.* as long as we keep the old ones), if we really want to.

**Comment by mworrell** [comment]
Naming and caching - the two most important things in Computer Science 👍

**Comment by mmzeeman** [comment]
No encoding and decoding! ;-)

Verstuurd vanaf mijn iPhone
