### ISSUE TITLE
Save and view button cmd clickable

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1418]
Hi!

Is it possible to make the save and view button cmd clickable so it can open in an new tab? Would be super awesome.

~ Dorien

**Comment by ddeboer** [comment]
The ‘Save and view’ will be removed: #1353.

**Comment by mworrell** [comment]
And also, it is a form submit, with server side redirect.  Option/command-click won't work on those.

**Comment by DorienD** [comment]
No particular reason to keep it, but could the next version have cmd clickable features?

**Comment by ddeboer** [comment]
Cmd clickable features for which buttons? Do you see any buttons that could be links (and be Cmd clickable) but aren’t?
