### ISSUE TITLE
Badmatch in postback controller.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1421]
Sometimes I see these crashes in the postback controller.

```
webmachine_mochiweb:119 stop_request 500 (reason {{badmatch,{more,#Fun<z_ubf.1.117479611>}},[{controller_postback,process_post_ubf,2,[{file,"modules/mod_base/controllers/controller_postback.erl"},{line,76}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,206}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,501}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,100}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]})
```

**Comment by mworrell** [comment]
Seems to be an incomplete post of some UBF data?

Maybe log the posted UBF at that point in the postback controller and see what is happening.

**Comment by mmzeeman** [comment]
Will do that. This weekend we have maintenance update.

**Comment by ddeboer** [comment]
Were you able to resolve this, @mmzeeman?

**Comment by mmzeeman** [comment]
No, not yet. It still happens, but not very often.

**Comment by mworrell** [comment]
I think it might be a half packet, could happen if the line is dropped halfway the transmission.
Maybe just add some error handling and return a `400 Bad Request`?

**Comment by mmzeeman** [comment]
I think I'll collect some crashes I see in practice. Maybe we can solve them all with a simple error handling routine.
