### ISSUE TITLE
E-mail address for reporting security issues

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1422]
It’s a good OSS [practice](https://docs.djangoproject.com/en/dev/internals/contributing/bugs-and-features/) to have a dedicated e-mail address where security vulnerabilities can be reported; usually you don’t want these sensitive issues to be visible in the tracker.

@mworrell Can you create `security[at]zotonic.com` and forward all e-mails to the Zotonic team?

**Comment by mworrell** [comment]
I will configure my email server to also handle @zotonic.com email, then we can add *security* and relay it to wherever.

Any other recipients that we should have?

**Comment by ddeboer** [comment]
@mworrell Thanks. Do you already have proper spam protection in place?

I’d say forward to [these folks](https://github.com/orgs/zotonic/people), unless any of them has some objection. @zotonic/developers Please tell us here if you’d *not* like to receive any security reports.

**Comment by mworrell** [comment]
I am adding it to my existing mail server, which has the usual spam protection (aka not much coming through).

Will setup any forwarding rules later, we can also share the account, so that people can reply from that account.

**Comment by mworrell** [comment]
Added the forwarding account.
