### ISSUE TITLE
Directories like "log.zotonic@localhost"

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1424]
These are created by *setup* and creation can be disabled by adding something like this to the erlang.config:

```
   {setup, [
       {data_dir, "priv/data"},
       {log_dir,  "priv/log"}
   ]},
```

(As mentioned by Karolis Petrauskas on the Erlang mailing list)

**Comment by ddeboer** [comment]
Yes, please fix that! My disk will be eternally grateful. :wink:
