### ISSUE TITLE
Automatic compilation of Sass files

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1431]
Zotonic [automatically compiles LESS to CSS](http://zotonic.com/docs/latest/ref/modules/mod_development.html?highlight=inotify#automatic-recompilation). At Driebit we happen to use [Sass](http://sass-lang.com/).

Would adding Sass support to the automatic compilation be useful for others, as well?

**Comment by mworrell** [comment]
+1 Sass is used by quite some people and adding support is easily done by handling the `.sass` extension.  I would suggest to handle it in a similar was (config etc) as we do with Less.

**Comment by mworrell** [comment]
BTW maybe we could handling files extensible? Using a first notifier would be enough, as that would create a new file, which triggers another file-change notification.

**Comment by ddeboer** [comment]
A notification is a good idea. We also need to account for some config (e.g. inclusion paths, minification flags). It seems the LESS support already does so.

**Comment by mworrell** [comment]
LESS support works smoothly, so indeed just copy the behavior, but then for SASS.

**Comment by arjan** [comment]
I uses SASS all the time already with Zotonic, although I use the `.scss` variants and not the weird yaml sass syntax. SCSS works fine, all files in `lib/scss` automatically get compiled into `lib/css`.

**Comment by ddeboer** [comment]
Lol, Zotonic [already compiles `.scss`](https://github.com/zotonic/zotonic/blob/master/src/filewatcher/z_filewatcher_handler.erl#L148). I’ll have a look at the current functionality and see if anything is missing there.

**Comment by Devenwel** [comment]
We do use some npm packages in gulp to transform the output in our sites, like postCSS/Lost, autoprefixer, so that would have to keep working as well.
