### ISSUE TITLE
Wrong dialog language

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1432]
If I open a dialog from a Dutch URL, the dialog contents are displayed in English.

Assume I’m on `http://example.com/nl/page/363/some-title` and open a dialog with:

```erlydtl
{{ z_language }}   {# prints nl #}
<a id="{{ #bla }}" href=""" title="{_ Bli _}">{_ Bli _}</a>
{% wire id=#bla action={dialog_open title=_"Translate me" template="dialog.tpl" id=id} %}
```

Inside `dialog.tpl`, the title is not translated (even though a translation is available), and:

```erlydtl
{{ z_language }}   {# prints en #}
```

I guess without the context of a (translated) page, the dialog falls back to my browser’s locale. The question is whether this behaviour makes sense: after all, I’m opening a dialog from a Dutch page, so I expect the dialog’s contents to be in Dutch, too.

**Comment by mworrell** [comment]
Zotonic uses the language set in your session, it only falls back on another language if there is an explicit language in the url or if there is no session at all.

Are you sure your session is alive when making the request?

**Comment by mmzeeman** [comment]
Also watch the "Set initial language to the default language." on the admin translation page. If this is checked the session will use the default language from the site and not select one based on the accept-language header of the browser.

**Comment by mworrell** [comment]
I can't reproduce this problem. Tried it with and without the *Set initial language to the default language* setting.

**Comment by mworrell** [comment]
@ddeboer Please re-open if your problem persists.
