### ISSUE TITLE
Hide temporary resources

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1438]
### Problem

Temporary resources flooding the (admin) resource list. See https://github.com/driebit/ginger/issues/183.
### Proposal
1. Set a pivoted property `is_temporary_rsc` when persisting a temporary resource.
2. Exclude `is_temporary_rsc` from all searches. 
3. Unset `is_temporary_rsc` when the resource has become definite. Where does this happen, exactly?

**Comment by Dirklectisch** [comment]
When your session ends, your resource is checked for modification. If it is not modified it is cleaned up. See:

https://github.com/zotonic/zotonic/blob/master/modules/mod_admin/filters/filter_temporary_rsc.erl#L139

**Comment by ddeboer** [comment]
@mworrell Do you agree with the above approach?

**Comment by mworrell** [comment]
Wouldn't it be better to just place them in some temp content group?

**Comment by mworrell** [comment]
See also https://github.com/driebit/ginger/issues/183#issuecomment-247966908

**Comment by ddeboer** [comment]
But sometimes you want to create the temporary resource with a specific content group, i.e. the group that the final resource should have. So if you place temporary resources in a temporary content group, you would still need to store the future content group somewhere.

**Comment by Dirklectisch** [comment]
Both needed by JHM en AHM.

**Comment by mworrell** [comment]
This is an artifact of the way comments are made at JHM and AHM. You should only create a temporary resource iff there is actual editing of content.

**Comment by ddeboer** [comment]
True. 

But in general it makes sense to be able to recognise temporary resource (and differentiate them from real ones). What about adding an `is_temporary_rsc` or `is_temporary` property? 

Subsequently indexing that property in a pivot table is too specific and should be done in Ginger instead.

**Comment by mworrell** [comment]
It should be logical reasoning or another administration, as an update won't delete that property.

And if you create a temporary resource iff there is actual editing going on, then it won't be that many resources that they will be a big problem.

**Comment by mworrell** [comment]
Other option: just change the standard query for the overview to exclude *remarks* (as they are called by Driebit) and add a button to view them in a separate list.

**Comment by ddeboer** [comment]
> Other option: just change the standard query for the overview to exclude remarks (as they are called by Driebit) and add a button to view them in a separate list.

**Comment by ddeboer** [comment]
Closing this. The solution as it now stands:

1. Wake sure temporary resources are only created when necessary, so not when displaying a form but only when editing has really started.
2. If many concurrent edits swamp the admin interface with temporary resources, exclude them from the admin query.
