### ISSUE TITLE
Stub generation on Read the Docs

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1452]
Following #1446 we started hosting the docs on readthedocs.io. However, it seems Read the Docs [doesn’t allow custom steps](https://docs.readthedocs.io/en/latest/builds.html#understanding-what-s-going-on), so the stubs (`meta*.rst`) files are not generated. Neither do they allow users to push generated docs to their servers (we already build the docs on Travis, so we could do that).

### Solutions

1. See whether we can add [custom steps](https://github.com/rtfd/readthedocs.org/issues/2423) to our Read the Docs build.
2. Unignore and check in the `meta*.rst` files.
3. Relocate back to our own hosting (in which case I’d prefer to keep the `docs.zotonic.com` subdomain that we now have).

**Comment by mmzeeman** [comment]
Is this the reason why the lists of all filters and models have disappeared?

The titles of the filter documentation pages are blank.

http://docs.zotonic.com/en/latest/ref/filters/filter_make_list.html

BTW: is it possible to place the next and previous buttons at the top too? That would make browsing through the documentation easier.

**Comment by ddeboer** [comment]
This was the fix for that problem. The filter names look okay now; I’ll keep an eye on them.

**Comment by mmzeeman** [comment]
The live documentation is now also updated I see :-)

**Comment by mmzeeman** [comment]
Oh, the title is still empty I see.

![screenshot from 2016-09-28 15 57 14](https://cloud.githubusercontent.com/assets/1024972/18916289/3ffbca7a-8594-11e6-94fd-ccd920653498.png)

**Comment by ddeboer** [comment]
That’s probably browser cache. Try Cmd+Shift+R.

**Comment by mmzeeman** [comment]
At the moment I am a linux user. ;-)

But indeed, the titles are also visible now.
