### ISSUE TITLE
acl_is_allowed_prop is not called when updating or deleting props

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1456]
The acl_is_allowed_prop observer does not seem te be called for update and delete actions. This is easy to reproduce by setting the following observer in a site, logging in as an editor, editing something and observing the debug messages.

``` erlang
observe_acl_is_allowed_prop(#acl_is_allowed_prop{action=view}, _Context) ->
    undefined;
observe_acl_is_allowed_prop(#acl_is_allowed_prop{}, Context) ->
    ?DEBUG("is allowed update / delete?"),
    undefined.
```

**Comment by mworrell** [comment]
Yes, its current use is to restrict the view of certain properties.

Use the update notifications to check for updates on properties.
