### ISSUE TITLE
Merge core translation files

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1460]
Add a function that calls `msgmerge` to merge the language files with the core template `zotonic.pot` (see #1459) when that template has changed.
- Add a separate `mod_translation:merge(Context)` that iterates over all languages and merges each of them.
- Add a `mod_translation:update(Context)` that calls both `mod_translation:generate` (which updates the `.pot` file) and `mod_translation:merge` (which updates the `.po` files).

**Comment by mworrell** [comment]
In master we use a single core .po from merged .pot files.

Merging the pot is done manually, which is good enough as you will also need to handle issues when merging.
