### ISSUE TITLE
Optimise database connection pool

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1469]
On production systems, we’re sometimes running into the maximum number of database connections limit. It seems Zotonic doesn’t properly handle this situation, even after the number of connections has again dropped below the limit. Only restarting the site(s) fixes this. In the logs, we’re getting ‘remaining slots are reserved’:

```
{function_clause,[{m_hierarchy,tree_to_menu,[{error,{{error,{error,fatal,<<"53300">>,<<"remaining connection slots are reserved for non-replication superuser connections">>,[]}},[{z_db,'-q/4-fun-2-',5,[{file,"src/db/z_db.erl"},{line,289}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,206}]},{m_hierarchy,'-tree/2-fun-0-',2,[{file,"src/models/m_hierarchy.erl"},{line,100}]},{depcache,memo,5,[{file,"src/depcache.erl"},{line,100}]},{m_hierarchy,menu,2,[{file,"src/models/m_hierarchy.erl"},{line,187}]},{acl_user_groups_rules,expand,2,[{file,"modules/mod_acl_user_groups/support/acl_user_groups_rules.erl"},{line,57}]},{acl_user_group_rebuilder,rebuild,3,[{file,"modules/mod_acl_user_groups/support/acl_user_group_rebuilder.erl"},{line,49}]}]}},[]],[{file,"src/models/m_hierarchy.erl"},{line,189}]},{acl_user_groups_rules,expand,2,[{file,"modules/mod_acl_user_groups/support/acl_user_groups_rules.erl"},{line,57}]},{acl_user_group_rebuilder,rebuild,3,[{file,"modules/mod_acl_user_groups/support/acl_user_group_rebuilder.erl"},{line,49}]}]}
```

https://github.com/zotonic/zotonic/pull/1455#issuecomment-251786407

@mworrell Please summarise here what you have in mind. :wink:

**Comment by mworrell** [comment]
Currently we have a database pool per site. This pool can grow from 1 to 10 connections (and more during peaks). Unused connections are closed, though one connection is always left open.

These pools function independently from each other. Especially at system start all sites need a couple of database connections, this maxes out the amount of database connections allowed by the PostgreSQL database.

Proposal is to make a single pool, sharing database connections between sites.

The selection of a connection is done by:

 * Same user/database/schema
 * Same user/database, switching schema
 * A new connection (possibly closing an existing connection)

Next is to make the polling of various queues better, using the following options:

 * Aggressive back-off from polling on empty queues
 * Coalesce polling, so the system is not closing/opening connections for the various polling
 * Use PostgreSQL push connections (preferably per user/database) for interesting events

**Comment by mworrell** [comment]
BTW, I think we should add the `53300` error to the retry-connect code, which is now only reacting on refused connections (ie. PostgreSQL is down or unreachable).

**Comment by krista-ramakers** [comment]
@CyBeRoni any thoughts on this issue?

**Comment by CyBeRoni** [comment]
> Proposal is to make a single pool, sharing database connections between sites.

Would this do anything if you use a different database per site? You would have to reconnect, no?

**Comment by mworrell** [comment]
If you can't find another candidate and no more connections can be made, then yes you need to close and reconnect.

**Comment by mworrell** [comment]
Merged this into the 0.x https://github.com/zotonic/zotonic/commit/8a747af1c4af352d713ade6721cb933e86188578

I needed to make some small changes, so we need to test this.

**Comment by ddeboer** [comment]
Closing this. Please reopen if testing turns up anything.

**Comment by ddeboer** [comment]
Tested this on our test instance. Seems to work well, even for the large nummer of sites that instance is running. Found that at least ~15 conns are needed to be able to boot Zotonic, which is fine, as PostgreSQL’s default is 100.
