### ISSUE TITLE
Making a resource only linkable hides link buttons

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1476]
Configuring the ACL module in such a way that a resource is linkable but not editable, hides the actual buttons to link in the admin screen. See screenshot:

![screen shot 2016-10-12 at 11 34 06](https://cloud.githubusercontent.com/assets/542192/19305174/0b3ced6e-9070-11e6-9c57-a9d961926b44.png)

It seems the linking rights are handed out correctly since disconnecting the resources works as expected. 

I'll look into fixing the relevant templates.

**Comment by ddeboer** [comment]
Fixed.
