### ISSUE TITLE
Blog site skeleton has problem on master.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1485]
After starting a site made from the blog skeleton it returns this page.

I'm not sure if this is a problem with the skeleton or with zotonic itself.

![screenshot from 2016-10-18 13 04 45](https://cloud.githubusercontent.com/assets/1024972/19475317/c201d38a-9533-11e6-966d-a1ee1139f49e.png)

**Comment by ddeboer** [comment]
Yep, I’m seeing this error, too.

**Comment by mmzeeman** [comment]
It looks like an error from the template compiler was returned as render result.
