### ISSUE TITLE
mod_filestore - delete failures are repeated forever. 

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1488]
At Driebit we use the same files on dev/test/prod so the filestore is configured to not allow deletion. Deletions are marked in the database but continuously queued for actual deletion which fails. The log is getting very full with the same error messages.
Is it possible to add a config setting that prevents the delete queuing?

**Comment by ddeboer** [comment]
@mworrell Or why retry failed deletions at all?

**Comment by mworrell** [comment]
Simple, because it is a distributed system you have temporary errors. Retrying is the best strategy to solve them. The filestore is now defined as being read/write, so this is a new use case which needs some consideration.

**Comment by ddeboer** [comment]
Right, so retrying makes sense.

What about solving this by either *detecting* (preferred) whether the filestore is read-only or adding a *configuration option* to mark it thus and not deleting any files on read-only filestores?

**Comment by mworrell** [comment]
As the fix is merged I close this issue.
