### ISSUE TITLE
Make mod_multi_upload suitable for users without admin rights

### ISSUE THREAD

**Issue by krista-ramakers** [zotonic/zotonic#1494]
We would like to use mod_multi_upload for some of our websites and I tested it, but it needs a little adjustment before we can activate it on live. There are two buttons that redirect to the admin log on screen, which doesn't really add to the (regular) user's convenience.

- The 'advanced upload' button redirects to the admin log on screen.
- The 'edit' button redirects to admin log on screen.

(I marked them both in the added screenshot)

![edit__met_article](https://cloud.githubusercontent.com/assets/20204550/19811709/ddd45a7c-9d32-11e6-944b-b6d25efddc1a.png)

**Comment by mworrell** [comment]
They do redirect to the admin log on screen because they redirect to pages in the admin.

**Comment by mworrell** [comment]
By the way, the module is tracked here: https://github.com/zotonic/mod_admin_multiupload

**Comment by krista-ramakers** [comment]
Obviously. Can we not to show them since they don't add value for the non-admin-users?
