### ISSUE TITLE
Add support for more Google Analytics parameters

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1495]
As suggested by @loetie in https://github.com/driebit/ginger/issues/208:
- add support for extra fields; see https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference
- move GA creation into a template block.

**Comment by ddeboer** [comment]
@loetie Is this something that you have time to work on?

**Comment by loetie** [comment]
@ddeboer I think that should be possible this week.

**Comment by mworrell** [comment]
Fixed in #1518
