### ISSUE TITLE
Globally disable search engine indexing 

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1500]
It’s currently possible to disable search indexing for a site (`seo_noindex`). However, in some cases it makes sense to disable indexing globally (per Zotonic instance). We want to have our live production sites indexed, but not those on (public) acceptance or test servers.

So let’s add a `zotonic.config` parameter that (if enabled) checks and disables the ‘Do not index’ checkbox in the admin. This then causes all content to be excluded for search engines.

**Comment by mworrell** [comment]
If I understand correctly, you are now going to use a per-site configuration and not a global configuration?

Shouldn't it be better to also add a global overrule for the seo-noindex?

**Comment by ddeboer** [comment]
That’s correct. 

A global override could be added, but is not strictly necessary for us as long as the `noindex` param can be set in the site configs (which is possible). Using our provisioning tools, we propagate that flag to all sites based on the server they’re hosted on.
