### ISSUE TITLE
Simplify logging

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1507]
There are now too many different ways to log a message in Zotonic. This results in inconsistent log messages: they are formatted differently and some of them have metadata (e.g., the site name) while others don’t. This is confusing both when reading and writing log messages.

### Example

For comparison: `?zWarning("lib file not found: ~s", [File], Context)` gives us (hardly any structured metadata; site name is implicit in the message):

```json
{"line":228,"module":"z_lib_include","message":"[some_site] warning @ z_lib_include:228  lib file not found: js/some-file.js","@timestamp":"2016-11-10T08:24:02.150","level":"warning","type":"lager_logstash"}
```

while `lager:info("lib file not found: ~s", [File])` yields:

```json
{"req_id":764834185,"page_id":"xbOhxyXP3EfECmmtkc7O","session_id":"gPbm8qSj5ie52rCofdKZguEO7KPTeLVa","is_ssl":"false","remote_ip":"XXX.XXX.XXX.XXX","method":"GET","dispatch":"home","controller":"controller_template","site":"some_site","node":"zotonic001@da846db902e2","pid":"<0.11784.1>","line":226,"function":"checksum","module":"z_lib_include","application":"zotonic","message":"lib file not found: js/some-file.js","@timestamp":"2016-11-10T08:24:02.150","level":"info","type":"lager_logstash"}
```

### Proposal

- Offer *one* interface for logging messages and get rid of the others.
- In all code, log only through that interface. The interface should be a small wrapper around the `lager:info|warning|etc` functions, that should nowhere else be called directly. The wrapper offers some Zotonic integration such as notifications.
- In the docs, clearly explain how to log messages.
- Set (or pass?) lager metadata (`lager:md`) consistently so a log message’s context becomes predictable.

### Questions

1. Is `z_logger` still used? If not, can we remove it?
2. Do you agree with adding a separate module (e.g. `z_log`) for the wrapper? If necessary, we can keep some of the convenience functions in the `z` module, but they then forward to `z_log`.
3. Should we print the metadata on the console? If not, we should keep a default log message format that contains the most important metadata, such as site name, in the message string itself.

See also #1406, and #922.

**Comment by mmzeeman** [comment]
z_logger is from the webzmachine dep, so it is not available in master and 1.0. 

As far as I can tell it is used in the request tracer of webzmachine, which is not very useful in practice.

**Comment by ddeboer** [comment]
> z_logger is from the webzmachine dep, so it is not available in master and 1.0.

Good point, thanks!

> Set (or pass?) lager metadata (lager:md) consistently so a log message’s context becomes predictable.

Just [found](http://erlang.org/download/OTP-19.0-rc1.README) that Erlang 19 has introduced `?FUNCTION_NAME` and `?FUNCTION_ARITY` macros, so let’s add those to the Lager metadata.

**Comment by mmzeeman** [comment]
That is what the parse transform of lager is for. This transform is probably not enabled everywhere. 

```erlang
-compile([{parse_transform, lager_transform}]).
```

**Comment by ddeboer** [comment]
It seems that in all places where macros (like `zWarning`) or the `z` functions are used (e.g. `z:warning/2–4)`, the parse transform is bypassed. This is because [we use `lager:log`](https://github.com/zotonic/zotonic/blob/master/src/support/z.erl#L205), which according to the lager source, [doesn’t use the parse transform](https://github.com/basho/lager/blob/master/src/lager.erl#L167).

So we would gain a lot by using the `lager:SEVERITY()` (`lager:warning` etc.) functions instead of `lager:log`.

**Comment by mmzeeman** [comment]
Indeed, the parse transform only works if lager is called directly from the code.

**Comment by crownedgrouse** [comment]
Hi,
What about using a gen_event for logging ?
A default handler can use lager, but it might be usefull to allow users to add other handlers if needed, or even replace default. MHO...

**Comment by crownedgrouse** [comment]
I precise my thoughts. It could allow to send mail or sms to admins depending severity by adding a custom handler.

**Comment by ddeboer** [comment]
An interesting idea! However, lager already handles the log events (including severity levels etc.) for us, so I'm not sure about the need for a separate gen_event server. You can always add lager handlers or write your own.

**Comment by crownedgrouse** [comment]
Yes lager use this approach too. But lager is not alpha and omega.  Using a gen_event let you, or users,  decide what logging frameworks using. Easy to migrate if in future another logging framework than lager is in the air.

**Comment by ddeboer** [comment]
True. Actually, I too prefer having one layer of abstraction between Zotonic and the logging framework. However, you do lose some lager functionality if you don’t call it directly: for instance having the MFA and line number of the code location that triggered the log message. So you’d have to redo that work in the abstraction layer, as it doesn’t make sense if lager tells you that all log messages come from the gen_event process. :wink:

@mmzeeman Should we also drag the (Cowboy) HTTP logs into this (#1406)? Or is that a separate issue?

**Comment by crownedgrouse** [comment]
Yep make sens on this point. If Zotonic team have to rewrite something like lager, this is not smart.
I will think if a workaround is possible for such issue.

**Comment by ddeboer** [comment]
By the way, Lager’s handlers are [themselves](https://github.com/basho/lager/blob/master/src/lager_console_backend.erl#L22) already gen_event processes.

**Comment by crownedgrouse** [comment]
So they probably deal with Mfa and line number in the calling function and pass theses info to the gen_event.  I will try to see this when a little time. 
So for the need of a custom handler I suppose we can add it to lager gen_event. 
However the abstract layer between zotonic and logging framework is something to keep in mind anyway ?

**Comment by ddeboer** [comment]
Just discussed this with @mworrell: we’ve decided to remove the layer of abstraction between Zotonic and lager for now:

- all lager metadata data is set *before* logging (cowmachine, Zotonic context, when a user logs in etc.) so we don’t need an abstraction layer for that
- customising the logging output should be done on the Lager level, by adding Lager handlers
- replacing Lager with a different logging library is not something that we see happen quickly.
