### ISSUE TITLE
z_search, some queries are wrongly parsed

### ISSUE THREAD

**Issue by caiodark** [zotonic/zotonic#1508]
I've cloned zotonic master.
I've created a site with base_site skeleton.
In the home page I placed:
`<ul>
{% for id in m_search[{latest cat='news' is_published='all'}] %}
<li>{{id.slug}}</li>
{% endfor %}
</ul>`

The error log shows this:
`<0.5889.0>@z_db:q:297 [clover] z_db error {error,error,<<"42601">>,<<"syntax error at or near \"and\"">>,[{position,<<"35">>}]} in query "select rsc.id from rsc rsc where  and rsc.is_published and rsc.publication_start <= now() and rsc.publication_end >= now() and rsc.pivot_category_nr = 93000000  order by rsc.modified DESC offset $1 limit $2" with [0,1000]
`

**Comment by mworrell** [comment]
Fixed in 1.x
