### ISSUE TITLE
Zotonic 0.17.1

### ISSUE THREAD

**Issue by caiodark** [zotonic/zotonic#1509]
I get the following error each time I try to log on in an admin panel.
`'error'>!{'z_msg_ack',1,24~6L0IIMw3Ejq4a7pXSQEL-z-0~,'page','undefined',20~6L0IIMw3Ejq4a7pXSQEL~,{!,!}}$`

Strange thing, I followed the same steps in my dev machine:
git clone ....
git checkout tags/0.17.1
make
I copy my old site in user/sites
make again

This works in my machine, but fails in production.
The only differences are:
erl version (7.3 in my machine, 7.2 on server)
nginx as a proxy in production.

**Comment by ddeboer** [comment]
Is there a specific reason for you to be on version 0.17.1? We’re currently on 0.22.1.

**Comment by caiodark** [comment]
I tried to migrate my old site to the last one version but:
- the acl functionality doesn't start (mod_acl_user_groups misses a dependency: mod_content_groups)
- the admin panel doesn't start as a consequence
- tried several way to activate modules through database, with bad luck

My sites are down since yesterday when my collegue upgraded the server. I really need to get it up and running asap, so I tought I could use the closest version it was installed in my server before, which was working.

**Comment by ddeboer** [comment]
Have you tried to add `mod_content_groups` to the `install_modules` section of your site config?

**Comment by caiodark** [comment]
Yep, I also tried to empty the module table, add mod_content_groups and mod_acl_user_groups to install_modules and removed any of the old acl modules. Yet if I look the log the acl function doesn't start. I can go to the logon form, my password is correctly checked but i get a fail message.

I also tried to remove acl as a dependency from mod_authentication. It worked in my dev machine but not on production.

**Comment by caiodark** [comment]
Anyway if it can help, with 0.17.1 I have this log:
`@z_transport:incoming_msgs:205 Error 'function_clause'`
In that line (which is already in a catch block, so no good) there's a call to lagger:error but I didn't find that function in that module.

**Comment by caiodark** [comment]
I'm also trying with 0.22.1. With your suggestions if I insert wrong credential I get a wrong credential error and that's ok. If I give the right ones I get back a 
(failed) net::ERR_EMPTY_RESPONSE

**Comment by caiodark** [comment]
I will close this issue and open a new one about site migration.
