### ISSUE TITLE
Site migration from 0.13 to master

### ISSUE THREAD

**Issue by caiodark** [zotonic/zotonic#1511]
I have these problems:
- comet calls gets 406 error.
- Old sites don't work, following your guide it should be enough to activate the mod_acl_user_groups.
Once I've done that the admin panel returns an empty response, no errors on log.

**Comment by mworrell** [comment]
Hi,

Two questions:

 1. Do you have any other javascript errors?
 2. Do you use a special comet subdomain?  (We removed support for that)

- Marc

**Comment by caiodark** [comment]
1. No, the admin logon page has no error until it makes the first attempt to make a comet message. Even the manage servers page has the same error.
2. No.

I think it is something related to the fact the production server is behind nginx. I noticed that your suggested configuration changed, but even if I adopt them I get the same error. No error if I connect to 8000 port directly.

This is the error that I less worried about. The fact is that older sites has so much problems that I don't know where to start to write about. The most disappoint thing is that there's no turning back, if I try to check out to an older version of zotonic through git checkout it still won't work. Old sites front-ends works nice but the admin panel still throws error (ack errors, function_clause on z_transport 205 line).

**Comment by mworrell** [comment]
Can you give me the precise error you get from z_transport line 205?  (And also the stack trace logged on line 208)

**Comment by caiodark** [comment]
I hope this is what you asked me for:
`2016-11-10 20:25:15.915 [error] <0.9056.0>@z_transport:incoming_msgs:205 Error 'function_clause' for transport message {z_msg_v1,1,false,<<"R7J6RABmKy5cu3vsMjDS-z-3">>,1478805915851,ubf,postback,undefined,desktop,undefined,<<"R7J6RABmKy5cu3vsMjDS">>,{postback_event,<<"p-xe7xh9q46wtjDJqmQaaUSmghWDaAVrAAZzdWJtaXRrAApsb2dvbl9mb3JtawAKbG9nb25fZm9ybWgCZAAFbG9nb25qZAASbW9kX2F1dGhlbnRpY2F0aW9u">>,<<"logon_form">>,undefined,<<>>,{q,[{<<"z_v">>,<<"username:eU79eaUPqXVTwg5nnDVCci2XFT6DaANrAAh1c2VybmFtZWsACHVzZXJuYW1lbAAAAAFoA2QACHByZXNlbmNlZAAXdmFsaWRhdG9yX2Jhc2VfcHJlc2VuY2Vqag">>},{<<"z_v">>,<<"password:EAaFIxzMSaLPjFYlPhSfJVXlhUSDaANrAAhwYXNzd29yZGsACHBhc3N3b3JkbAAAAAFoA2QACHByZXNlbmNlZAAXdmFsaWRhdG9yX2Jhc2VfcHJlc2VuY2Vqag">>},{<<"page">>,<<"%2Fadmin">>},{<<"handler">>,<<"username">>},{<<"username">>,<<"admin">>},{<<"password">>,<<"Cl@veR159753!">>},{<<"rememberme">>,<<>>}]}}}
2016-11-10 20:25:15.915 [error] <0.9056.0>@z_transport:incoming_msgs:208 Stack: [{proplists,get_value,[fallback,undefined,undefined],[{file,"proplists.erl"},{line,226}]},{mod_translation,do_set_language,2,[{file,"modules/mod_translation/mod_translation.erl"},{line,375}]},{lists,foldl,3,[{file,"lists.erl"},{line,1262}]},{z_auth,logon,2,[{file,"src/support/z_auth.erl"},{line,96}]},{controller_logon,logon_user,3,[{file,"modules/mod_authentication/controllers/controller_logon.erl"},{line,293}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,256}]},{z_transport,incoming_msgs,2,[{file,"src/support/z_transport.erl"},{line,193}]},{z_transport,incoming,2,[{file,"src/support/z_transport.erl"},{line,161}]}]
root@Clover-Produz:/home/zotonic/zotonic/priv/log# C
`

**Comment by ddeboer** [comment]
The cause seems to be [mod_translation:get_language_config/1](https://github.com/zotonic/zotonic/blob/0.x/modules/mod_translation/mod_translation.erl#L373) returning an empty list.

Can you log in if you disable mod_translation? If you cannot do this from the admin, try editing the database directly, remove mod_translation from the site `config` file and restarting the site.

**Comment by caiodark** [comment]
After those modification the mod_translation got disabled, I can now log on even if both the site and the translation module are disabled. Can I enable a different language by editing the db?

**Comment by ddeboer** [comment]
That’s good news!

It would help us a lot if you could add the `?DEBUG` statements I mentioned above and paste the output you get from them. That way, we can fix the bug in the next version of Zotonic. Of, if you prefer to use the Zotonic shell:

```erlang
Context = z:c(name_of_your_site).
m_config:get(i18n, language_list, Context).
%% What is the output of this?

m_rsc:p_no_acl(IdOfTheUserThatCannotLogIn, pref_language, Context).
%% What is the output of this?
```

**Comment by ddeboer** [comment]
Okay, I was able to reproduce the problem. 

1. Check the list of default languages: `m_config:get(i18n, language_list, Context)`.
2. Update a user with a language code that is not on that list: `m_rsc:update(UserId, [{pref_language, br}], z_acl:sudo(Context))`.
3. Try to log in as that user: throws the error pasted above by @caiodark.

@caiodark Please try to re-enable mod_translation, then run this in your Zotonic shell:

```erlang
Context = z:c(name_of_your_site).
m_rsc:update(IdOfTheUserThatCannotLogIn, [{pref_language, en}], z_acl:sudo(Context))`.
```

Can you then log in with the user?

**Comment by caiodark** [comment]
I have sites I only have the admin user. What id does it have?

**Comment by ddeboer** [comment]
That's easy: is 1. :wink:

**Comment by caiodark** [comment]
I thought so but I preferred asking. Nice job! All got running again.

**Comment by caiodark** [comment]
Thanks for you help. That saved my day, and something else!!
