### ISSUE TITLE
Move SSL to core

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1517]
SSL will be the default in Zotonic 1.0. 

1. Remove current mod_ssl. 
2. Move SSL handling to the core.
    - For SSL termination in front of Zotonic (e.g., HAProxy), add a ‘proxy whitelist’ configuration parameter that contains a list of trusted proxies’ IP addresses. 
    - If a request comes in and its request IP matches the whitelist, process its `Forwarded` header to overwrite the request’s IP (to be the client’s IP) and protocol (`https`); see https://github.com/zotonic/zotonic/issues/1329#issuecomment-259076893.
    - Add HSTS support (see #1329).
2. Create two new modules that manage SSL *certificates* (ordered by priority):
    * mod_ssl_ca (‘certificate authority’, i.e. paid certs)
    * mod_ssl_letsencrypt (see #1218)
    * mod_ssl_self_signed already exists, but needs to be fixed (see #1502) 

As discussed with @mworrell today. @CyBeRoni Makes sense?

Is there any compelling reason to support the outdated `X-Forwarded` header?

**Comment by CyBeRoni** [comment]
> Makes sense?

Seems reasonable to me.

> Is there any compelling reason to support the outdated X-Forwarded header?

I say go with the standardised one. Another option (which can both be supported at the same time) is the PROXY protocol, which would use a dedicated listener and prefix any transactions with the same information. This protocol is supported by many other projects like HAProxy (where it came from), nginx, stud, varnish (incoming), hitch, etc.

http://www.haproxy.org/download/1.5/doc/proxy-protocol.txt

**Comment by mworrell** [comment]
Status:

 * mod_ssl is being renamed to mod_ssl_ca in #1502 
 * mod_ssl_letsencrypt is being added in #1502 
 * `Forwarded` header handling has been added to #1502 
 * Whitelist handling for proxies has been added to #1502

**Comment by ddeboer** [comment]
> mod_ssl_self_signed already exists, but needs to be fixed (see #1502)

Isn’t this being fixed in #1502 as well?

**Comment by mworrell** [comment]
Yes, self-signed certs are now default (in #1502)

You need to enable `mod_ssl_ca` or `mod_ssl_letsencrypt` to provide "real" certificates.
