### ISSUE TITLE
z_sanitize - error on fb-like code

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1524]
During an anymeta import we see a crash while sanitizing a text with:

`<div class="fb-like" data-href="http://www.communityjoodsmonument.nl/250216" data-send="false" data-width="300" data-show-faces="true" data-font="arial"></div>
`
error is:

`
{{nocatch,{function_clause,[{z_sanitize,'-cleanup_microsoft_attrs/1-fun-1-',[<<"fb-like">>],[{file,"src/support/z_sanitize.erl"},{line,133}]},{lists,'-filter/2-lc$^0/1-0-',2,[{file,"lists.erl"},{line,1285}]},{z_sanitize,sanitize_element_opts,3,[{file,"src/support/z_sanitize.erl"},{line,126}]},{z_html,'-sanitize/5-lc$^1/1-0-',5,[{file,"src/z_html.erl"},{line,561}]},{z_html,'-sanitize/5-lc$^1/1-0-',5,[{file,"src/z_html.erl"},{line,561}]},{z_html,sanitize,5,[{file,"src/z_html.erl"},{line,561}]},{z_html,sanitize1,4,[{file,"src/z_html.erl"},{line,519}]},{z_html,'-sanitize/2-lc$^0/1-0-',2,[{file,"src/z_html.erl"},{line,507}]}]}},[{m_rsc_update,update_result,3,[{file,"src/models/m_rsc_update.erl"},{line,354}]},{mod_import_anymeta,rsc_update,3,[{file,"/opt/zotonic/user/modules/mod_import_anymeta/mod_import_anymeta.erl"},{line,1584}]},{mod_import_anymeta,write_rsc,6,[{file,"/opt/zotonic/user/modules/mod_import_anymeta/mod_import_anymeta.erl"},{line,1401}]},{mod_import_anymeta,import_thing,5,[{file,"/opt/zotonic/user/modules/mod_import_anymeta/mod_import_anymeta.erl"},{line,623}]},{mod_import_anymeta,import_loop_1,4,[{file,"/opt/zotonic/user/modules/mod_import_anymeta/mod_import_anymeta.erl"},{line,460}]}]}
`

**Comment by mworrell** [comment]
#1526 fixes this.

@ddeboer This problem will be problematic with copy/pasting html in 0.22, shall we make a 0.22 patch release?

**Comment by fredpook** [comment]
Yes please, I need it before importing mediamatic

**Comment by mworrell** [comment]
Fixed in the 0.x

Made issue #1527 for a 0.22.2 release

**Comment by ddeboer** [comment]
Is this a problem only on Erlang 16?

**Comment by ddeboer** [comment]
Fixed in 0.22.2.
