### ISSUE TITLE
Create 0.22.2 - with sanitizer fix

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1527]
This should be merged into the 0.22.2:

- [x] https://github.com/zotonic/zotonic/commit/24cfa9452a093dd96005a47bdce8886c3e8d4554

**Comment by mworrell** [comment]
See also issue #1524

**Comment by mworrell** [comment]
I made a draft release https://github.com/zotonic/zotonic/releases 0.22.2 on branch https://github.com/zotonic/zotonic/tree/release-0.22.2

/cc @ddeboer

**Comment by mworrell** [comment]
Is there anything else that we want in this patch release?

**Comment by ddeboer** [comment]
Tagged 0.22.2.

**Comment by mmzeeman** [comment]
Did you also upgrade mochiweb? It has some html parsing fixes for singletons? BTW, how do you do that?

**Comment by mworrell** [comment]
No, i didn't upgrade it. @ddeboer shall we add it, or did we release already?

**Comment by ddeboer** [comment]
Like I said above, I already tagged 0.22.2. We can always tag 0.22.3, of course. However, I’d first like to know what bugs that Mochiweb upgrade would solve.

**Comment by mmzeeman** [comment]
Possibly strange sanitize results for pages containing `embed`, `wbr`, `picture` and `source` tags. Those are all singleton tags, usually written without a closing tag. The parser will currently put nodes which are placed after these elements in the wrong place.

It will probably not add dangerous things in the sanitize result, only delete more stuff than it should. But I'm not entirely sure. It may also lead to wrong html output.

**Comment by mmzeeman** [comment]
There is no need to hurry. 0.23 is fine. We don't wait for the releases anyway.

**Comment by ddeboer** [comment]
@mmzeeman Can you try to upgrade Mochiweb and see whether it solves your issues? It if does, let’s make it part of 0.23.

**Comment by mmzeeman** [comment]
We already use it. The update was required to get something working. We run mochiweb master and don't use the locked dep.

I will upgrade the dep later today.
