### ISSUE TITLE
Should 'PageId without page session' be logged?

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1528]
The ‘PageId without page session’ is logged from several places in [z_transport](https://github.com/zotonic/zotonic/blob/master/src/support/z_transport.erl#L378). It’s filling up our logs. 

* Does the message have any value?
* If not, can we remove it? If it does, what about reducing its level to `debug` (it’s `info` now)?

**Comment by mmzeeman** [comment]
It can be removed I think. 

Other entries which fill the logs are:

[info] <0.2212.623>@z_session_page:websocket_attach:194 Websocket attach to non-existing page undefined
[error] <0.22648.623> SSL: hello: ssl_handshake.erl:169:Fatal error: internal error

The last one is marked as an error, and fills the crash log.

**Comment by ddeboer** [comment]
```[info] <0.2212.623>@z_session_page:websocket_attach:194 Websocket attach to non-existing page undefined
```

Definitely one we’re seeing too and that doesn’t seem to add real value. @mworrell Do you agree?

```
[error] <0.22648.623> SSL: hello: ssl_handshake.erl:169:Fatal error: internal error
```

@mmzeeman Isn’t this something you should be warned about?

**Comment by mmzeeman** [comment]
It is caused by

```erlang
certificate(OwnCert, CertDbHandle, CertDbRef, server) ->
    case ssl_certificate:certificate_chain(OwnCert, CertDbHandle, CertDbRef) of
        {ok, _, Chain} ->
            #certificate{asn1_certificates = Chain};
        {error, _} ->
            ?ALERT_REC(?FATAL, ?INTERNAL_ERROR)
    end.
```

The server wants to respond, but can't return a certificate chain. This is probably a request made directly to the ip address instead of the host. In that case zotonic can't return ceritificates.

**Comment by mmzeeman** [comment]
It could also be a non SNI compatible request.

**Comment by ddeboer** [comment]
Ah, just found https://github.com/zotonic/zotonic/commit/91bc07e34d2c4f7254140f23c22ad01fe1f3e971. @mworrell Ok if I cherry-pick that commit onto 0.x and master?

**Comment by ddeboer** [comment]
Turns out that commit *was* cherry-picked to master and 0.x. So from 0.22.0 onwards this message is no longer logged.
