### ISSUE TITLE
mod_search - filter "unfinished_or_nodate" should consider "date_is_all_day"

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1530]
I think the "all day" period setting means the date_end is 23:59 on the same day it is started if no date_end is given.
Yet I can't find any pivoting for this.

The use-case is an event of 1 day in the past, no end date entered but still appearing in a query with the unfinished_or_nodate filter while you expect the event to be finished and not show up.

**Comment by mworrell** [comment]
No, the 'all day' setting just means that there is no start/end time.
It also disables the timezone conversion.

If your resource doesn't have an end-date then it is ongoing since the start-date.
Examples of resources with missing end-dates are birth-dates or a opening date for a building.
