### ISSUE TITLE
From-date behaviour when only entering Till-date on resource

### ISSUE THREAD

**Issue by Devenwel** [zotonic/zotonic#1536]
When I leave the 'From' date blank for a resource and I enter a 'Till' date, today's date is saved as the From date. This is not visible untill the admin page is refreshed. I might not know a person's date of birth or an event's start date, so I would expect the field to stay either blank or get an error message.

**Comment by ddeboer** [comment]
> today's date is saved as the From date

I agree, that doesn’t make sense from the user’s perspective. Let’s change this behaviour by keeping the ‘from’ date empty. We may have to check the date [search filters](http://docs.zotonic.com/en/latest/developer-guide/search.html) for compatibility with this change.
