### ISSUE TITLE
Included application and zotonic modules

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1553]
Hi,
I'm looking to create a zotonic module that handle a service given by a plain Otp application. 
Is there some examples existing ?
Documentation give example for gen_server modules,  but not for otp application. Is a simple application:start in gen_server module sufficient or should it be started another way as an included application ?

**Comment by mworrell** [comment]
Good question. 

We made it possible to mix in extra dependencies using rebar. I am not sure what the best way is to actually start these dependencies.

As they are global to the beam, maybe they could best be started from a zotonic extension?

@arjan any suggestions?

**Comment by mworrell** [comment]
Thinking a bit further it should be ok to add a `application:ensure_all_started(your_app)` to the module init.

**Comment by crownedgrouse** [comment]
Yes, that was my first idea, but I wanted to be sure there was no other 'official' way.

**Comment by ddeboer** [comment]
@crownedgrouse Please let us know how you did it, so we can add it to the docs for the next person that has the same question. :wink:

**Comment by crownedgrouse** [comment]
yep.  Need to write a first zotonic module before  :>)

**Comment by crownedgrouse** [comment]
but I think this module may exite you ... I will come back to you once the otp application validated and a module ready.
