### ISSUE TITLE
Page block error

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1561]
See https://github.com/driebit/ginger/issues/245.

**Comment by mworrell** [comment]
Can you try this with a vanilla 0.x Zotonic?  
I couldn't reproduce the issue.

**Comment by DorienD** [comment]
This also happens when trying to make a connection on the menu page

**Comment by mworrell** [comment]
@DorienD can you try with a vanilla 0.x Zotonic (i.e. without the Ginger changes)?
I can't reproduce the problem with my install here.

**Comment by DorienD** [comment]
Hi Marc,

I've turned off all the ginger modules (base, foundation and admin) updated the zotonic version (0.x) compiled and flushed and i still get errors: 

`zotonic_1        | 12:02:10.094 [error] Error in memo error:{badmatch,{error,{unknown_predicate,undefined}}} in [{m_predicate,name_to_id_check,2,[{file,"src/models/m_predicate.erl"},{line,139}]},{m_edge,get_id,4,[{file,"src/models/m_edge.erl"},{line,148}]},{depcache,memo,5,[{file,"src/depcache.erl"},{line,102}]},{template_metakids__desktop_opt_zotonic_modules_mod_admin_templates__action_dialog_connect_tab_find_results_item_tpl,render2,2,[]},{template_metakids__desktop_opt_zotonic_modules_mod_admin_templates__action_dialog_connect_tab_find_results_item_tpl,render,2,[]},{z_template,render1,5,[{file,"src/support/z_template.erl"},{line,115}]},{scomp_base_catinclude,render1,5,[{file,"modules/mod_base/scomps/scomp_base_catinclude.erl"},{line,51}]},{z_scomp,render_scomp_module,5,[{file,"src/support/z_scomp.erl"},{line,70}]}]
zotonic_1        | 12:02:10.094 [error] Error rendering template: "/opt/zotonic/modules/mod_admin/templates/_action_dialog_connect_tab_find_results_item.tpl" ({badmatch,{error,{unknown_predicate,undefined}}})
zotonic_1        | 12:02:10.094 [error] Error rendering template: "/opt/zotonic/modules/mod_admin/templates/_action_dialog_connect_tab_find_results.tpl" ({error,{template_rendering_error,"/opt/zotonic/modules/mod_admin/templates/_action_dialog_connect_tab_find_results_item.tpl",{badmatch,{error,{unknown_predicate,undefined}}}}})
zotonic_1        | 12:02:10.097 [error] Throw '{error,{template_rendering_error,"/opt/zotonic/modules/mod_admin/templates/_action_dialog_connect_tab_find_results.tpl",{error,{template_rendering_error,"/opt/zotonic/modules/mod_admin/templates/_action_dialog_connect_tab_find_results_item.tpl",{badmatch,{error,{unknown_predicate,undefined}}}}}}}' for transport message {z_msg_v1,0,false,<<"-z-12">>,1482494530089,ubf,postback,undefined,desktop,undefined,<<"FV18zyzbkYI1a9O0xoNx">>,{postback_event,<<"8BgVz5MArxoKjrLqEX1KTrPSODODaAVkAAl1bmRlZmluZWRtAAAAAGsAFGRpYWxvZy1jb25uZWN0LWZvdW5kaARkAAZyZW5kZXJkAAZ1cGRhdGVoBGQABnJlbmRlcmsAK19hY3Rpb25fZGlhbG9nX2Nvbm5lY3RfdGFiX2ZpbmRfcmVzdWx0cy50cGxkAAl1bmRlZmluZWRsAAAABmgCZAAGdGFyZ2V0awAUZGlhbG9nLWNvbm5lY3QtZm91bmRoAmQACHRlbXBsYXRlawArX2FjdGlvbl9kaWFsb2dfY29ubmVjdF90YWJfZmluZF9yZXN1bHRzLnRwbGgCZAAKc3ViamVjdF9pZGIAAAHIaAJkAANjYXRqaAJkAAlwcmVkaWNhdGVqaAJkAAR0ZXh0ampsAAAABmgCZAAGdGFyZ2V0awAUZGlhbG9nLWNvbm5lY3QtZm91bmRoAmQACHRlbXBsYXRlawArX2FjdGlvbl9kaWFsb2dfY29ubmVjdF90YWJfZmluZF9yZXN1bHRzLnRwbGgCZAAKc3ViamVjdF9pZGIAAAHIaAJkAANjYXRqaAJkAAlwcmVkaWNhdGVqaAJkAAR0ZXh0ampkABJhY3Rpb25fYmFzZV91cGRhdGU">>,<<>>,undefined,<<>>,{q,[]}}}
zotonic_1        | 12:02:10.098 [error] Stack: [{z_template,render1,5,[{file,"src/support/z_template.erl"},{line,122}]},{z_template,render_to_iolist,3,[{file,"src/support/z_template.erl"},{line,139}]},{z_render,render_html_opt_all,4,[{file,"src/support/z_render.erl"},{line,441}]},{z_render,update_context,5,[{file,"src/support/z_render.erl"},{line,367}]},{action_base_update,render_inline,5,[{file,"modules/mod_base/actions/action_base_update.erl"},{line,65}]},{action_base_update,event,2,[{file,"modules/mod_base/actions/action_base_update.erl"},{line,103}]},{z_transport,incoming_with_session,2,[{file,"src/support/z_transport.erl"},{line,250}]},{z_transport,incoming_msgs,2,[{file,"src/support/z_transport.erl"},{line,193}]}]`

**Comment by DorienD** [comment]
Should i have a 'undefined' predicate in the predicate list?

**Comment by ddeboer** [comment]
@DorienD Could it be that you have a resource with unique name ‘undefined’? Please search for `id:undefined` in the admin.

**Comment by mworrell** [comment]
0e298fe fixed this issue.
