### ISSUE TITLE
Deprecate mod_atom and mod_atom_feed in favor or mod_export

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1577]
`mod_export` can now export in the XML Atom format.

As `mod_export` can export individual items and feeds, I propose to remove `mod_atom` and `mod_atom_feed` from the core.

**Comment by ddeboer** [comment]
The only thing we would lose by removing mod_atom_feed is exporting a collection of items as atom.

Does mod_export currently export all items in a collection or query?

**Comment by mworrell** [comment]
mod_export is more generic and can indeed export queries and collections.

I think for longer term it is better and easier to settle on mod_export. So if we miss something we can add it there.

Mod_atom has some logic to parse atoms to resources. But that is nowhere used, as far as I can see. (And json-ld is better for that anyway)
