### ISSUE TITLE
Handle empty unique names correctly

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1579]
When a resource is created with an – admittedly ludicrous – title like `_` (single underscore), the unique name becomes an empty string (“”). This causes the unique name validation (#1504) to fail on resources that have no unique name, as their name (empty) is equal to the weird resource’s name.

Should we fix this by never writing an empty unique name (`_` could just stay `_` right?), or by changing the validation to skip checking the name when it’s empty?

**Comment by mworrell** [comment]
I am all for handling an empty unique name as no unique name.

**Comment by mworrell** [comment]
Question:  on updates, should we ignore an empty name (and also '_') or map it to `undefined` and remove the name (which makes sense for such names, they are kind of non-defined anyway).

**Comment by mworrell** [comment]
Should also consider the validation. Reopening.
