### ISSUE TITLE
Special symbols in image caption cause page to crash

### ISSUE THREAD

**Issue by krista-ramakers** [zotonic/zotonic#1585]
When you add symbols like an en dash –, em dash — and € (virtually any symbol you create using a keyboard shortcut involving the option key on mac) in an image caption and try to save your page after doing so, a 500 error occurs.

![edit_ assignment_3__governance_of_change_towards_wood_circularity _ _tu_delft_openresearch_net_admin](https://cloud.githubusercontent.com/assets/20204550/22022467/7fa2e2dc-dcc2-11e6-9f27-b722eae6eaf1.png)

**Comment by mworrell** [comment]
Which version is this?

And do you mean that the admin page crashes?

**Comment by mworrell** [comment]
Just tried on the newest master and 0.x, on both I can't reproduce the issue.

**Comment by krista-ramakers** [comment]
It happens in Zotonic 0.23, tested it on two of our sites. 
At TUDelft the article is visible in the workspace, but when you click it, you get the 500 error. If you look up the article's id in admin, you can access it, but when you click 'view' or 'save and view', you get the error again.
In the Geheugen sites, when you add the image and caption front end and click save afterwards, you get the 500 error.

**Comment by mworrell** [comment]
There have been changes in the utf-8 handling of captions. See https://github.com/zotonic/zotonic/issues/1572

I assume these will fix the issues you encountered.
If you still see these issues with the 0.x, then please reopen.
