### ISSUE TITLE
wire and postback

### ISSUE THREAD

**Issue by niinortey** [zotonic/zotonic#1586]
I am following the tutorial on [implementing simple contact form](http://docs.zotonic.com/en/latest/cookbook/frontend-contactform.html?highlight=contacts).

In the template i have the wire 
```
{% wire id="contact-form" type="submit" postback={contact} delegate="my_contactform" %}
```
and in the my_contactform.erl i hve the event
```
event(#submit{message={contact, []}}, Context) ->
  ?DEBUG(z_context:get_q_all(Context)),
  Context.
```
The problem is when i click on the submit button I expect to see the form imputs dumped on the zotonic debug console but i dont see that. Rather  I see **#$** in the browser

I followed the tutorial down to emailing the contents of the contact form. There also the email template is not rendered. All I see in the browser is **#$**

What am I missing or what am I doing wrong?
I am working on the master branch

**Comment by mworrell** [comment]
Are you sure nothing crashes?
As you have “contacts” (with an s) in the template and “contact” in the event handler.

Might be a typo in your report though.

**Comment by niinortey** [comment]
Was a typo in the report.

Is the user needed to be logged in for wire to work?

**Comment by mworrell** [comment]
User doesn't need to be logged on.

You do need a session for the transport.
The session should have been started (and kept alive) when you have a `{% script %}` tag on your page (near the bottom).

No javascript errors and no information on the erlang console?

**Comment by niinortey** [comment]
No there are no errors. 
None on the console 
![selection_007](https://cloud.githubusercontent.com/assets/2520579/22072757/40081636-dd9b-11e6-9e58-b1d1f1e770ee.png)

And none the webpage. (I am guessing javascript errors will show on the google-chrome console or the webpage itself?)

The template is extending base.tpl so I think theres no need for the `{% script %}` again in my template.
It contains 
```
{% extends "base.tpl" %}

{% block content %}
<h1>Contact page</h1>
{% wire id="contact-form" type="submit" postback={contact} delegate="my_contactform" %}
<form id="contact-form" method="post" action="postback">

    <label for="name">Name</label>
    <input type="text" name="name" id="name" />

    <label for="email">E-mail</label>
    <input type="text" name="mail" id="email" />
    {% validate id="mail" type={presence} type={email} %}

    <label for="message">Message</label>
    <textarea name="message" id="message" cols="60" rows="8"></textarea>
    {% validate id="message" type={presence} %}

    <input type="submit" value="Send" />
</form>
{% endblock %}
https://github.com/niinortey```

Handler contains
```
%%%-------------------------------------------------------------------
%%% @author enoch
%%% @copyright (C) 2017, <COMPANY>
%%% @doc
%%%
%%% @end
%%% Created : 18. Jan 2017 3:48 PM
%%%-------------------------------------------------------------------
-module(my_contactform).
-author("enoch").

%% API
-export([event/2]).

-include_lib("zotonic.hrl").

event(#submit{message={contact, []}}, Context) ->
  ?DEBUG(z_context:get_q_all(Context)),
  Context.
```
And dispatch contains
```
[
    {mycontact_url,      ["mycontact"],	controller_template,  	[ {template, "my_contact.tpl"} ]}
].
```

I believe its somethiing I am not doing right. Not necessarily a bug in zotonic.

**Comment by mworrell** [comment]
Which "base.tpl" are you extending.

I see that the one in mod_base is a bit too basic for its own good.

@ddeboer and @ArthurClemens  Shall we add basic javascript and the `{% script %}` tag to the mod_base base.tpl?

**Comment by niinortey** [comment]
Interesting... I see base.tpl in mod_base and mod_base_site and I have no idea which one my template is extending.
Is there a way to be explicit on which template in the extends tag?

**Comment by mworrell** [comment]
You can see in the admin development menu (enable mod_development).
There you can request a template and see which one is selected.

**Comment by niinortey** [comment]
Ok got it..
Its extending the one from mod_base.

**Comment by niinortey** [comment]
You were right about the base.tpl being too basic in mod_base.
For a quick test I replaced the content with the one from mod_base_site and the wire worked!

**Comment by mworrell** [comment]
Ah, good. Then i think we need to add the missing parts to that too simplistic base.tpl as this is quite confusing.
