### ISSUE TITLE
Reindex notification popup is displayed too often

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1588]
This popup keeps popping up on my development machine... It is even visible after I turn off zotonic, so I guess these popups are queued somewhere. The only obvious way I can get rid of them is logging off and logging in again. Very annoying.

![screenshot from 2017-01-20 10 08 58](https://cloud.githubusercontent.com/assets/1024972/22142944/81c821c0-def8-11e6-8f80-3885dfa8b0f6.png)

**Comment by mmzeeman** [comment]
BTW. They are also visible when the development module is disabled.

**Comment by mmzeeman** [comment]
Note: It looks like the filewatcher is triggered by changes made in zotonics priv directory. This is probably not what we want.

``` 
{"/home/channel/Work/git/zotonic/zotonic/_build/default/lib/zotonic/priv/log/console.log",
 "Reindexed sites due to changed lib file."}
```

**Comment by mworrell** [comment]
oops, those directories should be excluded.

Maybe exclude anything with `/log/` in the path.

**Comment by mworrell** [comment]
We currently have a regexp to exclude certain files. I will add `/log/` directories to that pattern.
