### ISSUE TITLE
The problem with the user's login name

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1589]
If username = email, you can not change the password. Admin crashes when you try to change your password. There is a restart. I am using the latest version 1.0

**Comment by mworrell** [comment]
Where do you try to change the password?  On the page where you edit the person or on the page with the list of usernames?

**Comment by heiheshang** [comment]
I tried both options

**Comment by mworrell** [comment]
Do you have the newest master?  I just tried and can't reproduce the problem.

**Comment by heiheshang** [comment]
I use postgresql 9.4 can be a problem?

**Comment by mworrell** [comment]
Shouldn't be a problem, if it was then you should get sql errors.
I asked @ddeboer to check if he can reproduce the problem on his dev env.

**Comment by heiheshang** [comment]
I see a problem in the module mod_admin_identity action action_admin_identity_dialog_set_username_password.erl.
message
`{submit,set_username_password,<<"u4t9mpfuobc7-form">>,<<"u4t9mpfuobc7-form">>}`
`event(#submit{message=set_username_password},Context)`
It leads to a drop node

**Comment by mworrell** [comment]
Do you have a longer traceback of the error?

**Comment by heiheshang** [comment]
nor any error does not occur, I tried to put ?DEBUG, but the message does not appear in the console.probably need to do debugging for another

**Comment by mworrell** [comment]
If the message does not appear then the crash might be at a different spot.

We still couldn't reproduce the issue :(

**Comment by heiheshang** [comment]
docker can give way to test

**Comment by mworrell** [comment]
Docker?  Might it be that you are having this issue? https://github.com/zotonic/zotonic/issues/1490

**Comment by heiheshang** [comment]
how I can help?
I'm using vps 1cpu

**Comment by mworrell** [comment]
@heiheshang can you try with a 2 cpu instance?

**Comment by heiheshang** [comment]
what for ? I want to save money

**Comment by mworrell** [comment]
I think this is an issue with the scheduler and only having a single scheduler/cpu.

@heiheshang if you can't up the core count, then maybe start erl with more than 1 scheduler (`erl +S 2`)

@ddeboer and @mmzeeman do you know the status of #1490 and if that might explain what is reported here?

**Comment by mmzeeman** [comment]
The bcrypt nif can't be used with a non-smp erlang. It won't compile. There is a port version of the same algorithm which should work though.

**Comment by mmzeeman** [comment]
For the above, see: https://github.com/smarkets/erlang-bcrypt#configuration 

Setting mechanism to 'port' might work.

**Comment by mworrell** [comment]
Should that be standard or is using the NIF better?

**Comment by mmzeeman** [comment]
Good one. The NIF has no limit on the number of simultaneous bcrypt operation, the port version does. 

We don't have to do it for speed, because bcrypt was designed to be slow anyhow.

**Comment by heiheshang** [comment]
in zotonic you can set the parameters without changing the container docker ? I can use for this purpose erlang.config ?

**Comment by mmzeeman** [comment]
Yes, if you put this in your erlang.config

```erlang
{bcrypt,
    [{mechanism, port}, {pool_size, 4}]
 },
```
It will use the port version. This worked fine over here on zotonic stable.

**Comment by mworrell** [comment]
@mmzeeman what is the throughput of the port version? We might want to make it the default option if there is not problem with Erlang 19 (or later) and the overall performance.

**Comment by mmzeeman** [comment]
Bcrypt is designed to be slow. The pool size defines how many bcrypt operations can be done in parallel. This must be proportional to the expected traffic. The nif version starts an os-level thread and queues bcrypt operations to a single thread. My guess is that the port version is better for a busy server.

**Comment by mworrell** [comment]
That was also the gut-feeling I got. Good to have some back-pressure by limiting the number of parallel operations. I will change this default in the master and 0.x

**Comment by mworrell** [comment]
Assuming the issue is indeed bcrypt, the issue is further discussed in #1490
