### ISSUE TITLE
Missing debugging in docker image

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1590]
The docker image uses the alpine packages to build Erlang in many different parts. We are missing many debugging utils like observer and etop. I suggest we add the following packages:

erlang-observer
erlang-debugger

Alternatively we can look into using the full blown package from Erlang Solutions.

**Comment by mworrell** [comment]
Should we use the Alpine packages?  To me it is strange that they split Erlang into many sub-packages. The package from Erlang Solutions might be easier and more complete.

**Comment by ddeboer** [comment]
Which [Dockerfile](https://github.com/zotonic/zotonic/find/master) are you referring to? All of them are based on [zotonic/erlang](https://github.com/zotonic/docker-erlang), which builds Erlang from source.

**Comment by Dirklectisch** [comment]
This is supremely weird, @mworrell and me traced this back to a docker file that I can't seem to find anymore! I'll try to retrace my steps tomorrow.

The actual problem here is that a lot of build in Erlang modules like `etop` and `observer` are not included in the build we are using. But maybe that has a different reason after all.

**Comment by ddeboer** [comment]
Ah, you were referring to the 0.x Dockerfile. We were already building Erlang from source on master, and now on 0.x, too.

> The package from Erlang Solutions might be easier and more complete.

Unfortunately Erlang Solutions offers no Alpine packages. But building from source works pretty well.
