### ISSUE TITLE
invalid byte sequence for encoding error (UTF8 special characters)

### ISSUE THREAD

**Issue by niinortey** [zotonic/zotonic#1599]
On a line in a module I am working on I have
```
z_db:equery("insert into ec_polling_centre (id, elect_area_id, code, name)values ($1,$2,$3,$4)",[8495,1266,"C100909A","Silent Café"], Context)
```
It throws the error
```
{error,{error,error,<<"22021">>,
              <<"invalid byte sequence for encoding \"UTF8\": 0xe9">>,[]}}
```
Complaining about the special character ```é``` in the word ```Café```

I tried it from the zotonic erlang shell as
```
(zotonic001@pwgh)1> z_db:equery("insert into ec_polling_centre (id, elect_area_id, code, name)values ($1$2,$3,$4)",[8695, 1266,"C100909A","Silent Café"], z:c(mpwebsite)).
```
Got the same error. 
Tried directly with ```epgsql:squery``` 
No luck
But when I try it on the postgress client psql shell it succeeds.
```
zotonic=# insert into mypeople.ec_polling_centre (id,elect_area_id,code, name)values (8695, 1266, 'C100909A','Silent Café');
INSERT 0 1
```
I think the problem is with epgsql. How do I fix this?

**Comment by alvaropag** [comment]
Hello Enoch,

I also have special characters on Portuguese like é ã and others. For this
you need to pass the parameters as binaries, so "Silent Café" needs to be
<<"Silent Café"/utf8>>.
You can do this conversion with the function list_to_binary/1.

Cheers,

--
Álvaro Pagliari


Em sex, 3 de fev de 2017 às 09:23, Enoch jr. Nii Nortey Wilson <
notifications@github.com> escreveu:

**Comment by niinortey** [comment]
Great!!! 
Thanks a lot for the pointer.

**Comment by alvaropag** [comment]
;)

**Comment by mworrell** [comment]
You can also use `unicode:characters_to_binary` if the string (list) contains code points above 255.

But I agree with @alvaropag, I most often use the binary (`/utf8`) notation, making things less ambiguous.
