### ISSUE TITLE
Menu items overflow hidden

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1603]
Hi!

On the menu rsc edit page when you click on the cog icon you don't see the ul that is normally visible there because of an overflow hidden. See screenshots

![screen shot 2017-02-08 at 14 39 56](https://cloud.githubusercontent.com/assets/5102362/22739650/ca775954-ee0c-11e6-80e6-35e2f755b61d.png)
![screen shot 2017-02-08 at 14 40 11](https://cloud.githubusercontent.com/assets/5102362/22739649/ca76fcd4-ee0c-11e6-84bb-a4ddcbfd9feb.png)

**Comment by mworrell** [comment]
I think this was added in https://github.com/zotonic/zotonic/issues/1570 1dd35cb0e61ca5d9e96bf07f29aab2439cce9498

Could you check if without the overflow hidden the problem from 1570 doesn't come back?

**Comment by mworrell** [comment]
@mmzeeman this fixes the problem you reported in the menu editor.
