### ISSUE TITLE
Tables in documentation have a scrollbar.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1608]
Tables with long explanations have a scrollbar. This makes them hard to read.

See image below:

![screenshot from 2017-02-15 16 12 11](https://cloud.githubusercontent.com/assets/1024972/22980400/a002f664-f399-11e6-8fe0-54d8b9704d32.png)

**Comment by mworrell** [comment]
We are using a standard Sphinx theme, can we influence that theme?

/cc @ddeboer
