### ISSUE TITLE
erl_crash.dump

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#1610]
Just completed a fresh Zotonic install following Docs, using Erlang 19.2.2 and Zotonic 0.25. After creating a site and recompiling Zotonic, this message is returned when restarting: 

`Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:true]`

`{"init terminating in do_boot",{undef,[{zotonic,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()`

`Crash dump is being written to: erl_crash.dump...done`

File is attached. Has something changed with Erlang 19.2.2?

[erl_crash.txt](https://github.com/zotonic/zotonic/files/784782/erl_crash.txt)

**Comment by seannaswell** [comment]
Think I have answered my own question...looks like Erlang 18 is required, not tested with version 19 yet?

**Comment by mworrell** [comment]
I actually use 19.x on my development machine. No problems. But maybe because it is a Mac, didn't try on Linux. Though I think that David uses 19 on a Linux machine.

- Marc

**Comment by seannaswell** [comment]
Understand. I am using it on DragonFlyBSD, which uses slightly modified FreeBSD ports and packages. That is likely the root of the issue...

The base install compiles dependencies until it gets to deps/proper, where "proper_internal.hrl" looks for but can't find "compile_flags.hrl". Looking at the Proper code both on GitHub and in deps folder, seems the version pulled in via rebar is older than current release and does not look for Erlang 19, which may be why "compile_flags.hrl" is not created. When I comment out the requirement in "proper_internal.hrl" for the compile flags file, the compile finishes and I have a working base Zotonic install.

However, when I setup a site and recompile Zotonic, I get the error referenced in the original attachment. Thought it may be related to Erlang versions... 

Anyway, I am in over my head, was just hoping to get Zotonic working on my server. Thanks for the response.

**Comment by ddeboer** [comment]
So your problem is that manopapad/proper does not compile. It seems our 0.x branch (including the 0.25.0 that you’re running) is on a slightly outdated version of that dependency. While it compiles perfectly fine on Erlang 19 Linux and Mac OS, the situation may be different for DragonFlyBSD.

Can you try this?

```bash
$ git clone https://github.com/manopapad/proper.git
$ cd proper
$ make
```

Alternatively, you can run Zotonic in an isolated [Docker container](http://docs.zotonic.com/en/latest/developer-guide/docker.html).

**Comment by seannaswell** [comment]
Thanks for the suggestion. Unfortunately, even after updating manopapad/proper the compile flags were still not being generated.

The solution, based on [this commit](https://github.com/manopapad/proper/commit/09f9f82d05edfa5c825d5cdb26e8bcf274c7d14e), was to append "dragonfly" after "openbsd|solaris", which allowed the compile_flags to be generated proper-ly...

I can now compile Zotonic and create a new site without error. However, the site still fails to start, giving the message below and creating the erl_crash.dump that is attached:

`Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:2:2] [async-threads:10] [kernel-poll:true]`

`{"init terminating in do_boot",{undef,[{zotonic,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()`

There are no error messages logged, and I am unable to decipher the erl_crash file, so if there are further suggestions, let me know. 

While I do understand the reason for using Docker as a reference platform, Dragonfly is what I am working with. Therefore, since using a non-standard OS falls outside of your supported use cases, unless there are further suggestions, feel free to close this ticket. I will tinker a bit and see if I can get it to work, and will inform if successful. Thanks.

[erl_crash.txt](https://github.com/zotonic/zotonic/files/786419/erl_crash.txt)

**Comment by seannaswell** [comment]
Update: attempted installation at default Erlang lib directory /usr/local/lib/erlang/lib/zotonic-0.25.0, after reading [this thread](https://lists.freebsd.org/pipermail/freebsd-ports/2013-November/088112.html).  

I then ran "bin/zotonic debug" and got the Welcome site. Then I setup a new site, stopped Zotonic and recompiled, verified the config file at /usr/local/zotonic/user/sites, ran "bin/zotonic debug" again, and was greeting with the same error message as above. Will look into it a bit more tomorrow, and close the issue if not resolved.

**Comment by ddeboer** [comment]
Thanks! Your findings will help people run Zotonic on as many different systems as possible. :wink:

**Comment by seannaswell** [comment]
Thanks for the thanks. So, it is now working, and the process is documented here: https://gist.github.com/seannaswell/a50a28f1fd10806d46c49218627109c2

The 2 key issues were adding a symlink of bin/zotonic to the /usr/local/bin directory, and properly setting the $ZOTONIC path statement in bin/zotonic. I am not sure why it doesn't work in DragonFly, assuming it does in FreeBSD, but the documented changes resolve the issue, and simply require reapplying after updates.

Thanks David. And, thank you Marc, a great project.

**Comment by ddeboer** [comment]
> adding a symlink of bin/zotonic to the /usr/local/bin directory

**Comment by seannaswell** [comment]
At the moment I am simply wanting to evaluate Zotonic for use in a couple of projects, to make sure it will handle our requirements. Ultimately I may either modify [this effort](https://github.com/mvw/freebsd-ports-www-zotonic) to create a Zotonic pkg, or pay someone to do so, but for now, I am in good shape. Thanks again.
