### ISSUE TITLE
Doccumentation on datamodel fields

### ISSUE THREAD

**Issue by niinortey** [zotonic/zotonic#1614]
Hello, is there any doccumentation that clearly sets out the structure/format of the fields contained in ```#datamodel``` manage_shcema/2? I mean categories, resources, predicates, edges, etc.

**Comment by niinortey** [comment]
I think I understand it now. spent some time looking at z_datamodel.erl 

Erlang is quite new to me and took me some time to grasp the list comprehension in manage/3 and understand whats going on in manage_category/3, manage_resource/3 and the like. 

The fields of record #datamodel are being used as the second parameter (tuple) in the various manage functions. And the Props parameter of the tuple actually refers to the properties of the [resource model ](http://docs.zotonic.com/en/latest/ref/models/model_rsc.html#properties-of-the-resource-model).

I am closing this ticket but if I am wrong in my understanding please help with the right explanation.
Obviously I have a long learning curve ahead of me when it comes to Erlang.

**Comment by ddeboer** [comment]
I added more documentation at http://docs.zotonic.com/en/latest/developer-guide/modules.html#module-versioning. Does that help?
