### ISSUE TITLE
Words sticking together

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1619]
1. some "words" here
2. select "words"
3. replace with "letters"
4. Result: some letters[nbsp]here
5. On the front end you see: Some lettershere

![screen shot 2017-01-13 at 10 46 12](https://cloud.githubusercontent.com/assets/5102362/23398501/10c7043c-fd9d-11e6-8ab2-ffd7644e9c51.png)

**Comment by ddeboer** [comment]
Probably a TinyMCE ‘feature’. Could you paste the HTML generated by TinyMCE here?

**Comment by DorienD** [comment]
`<p>woei&nbsp;words</p>`

**Comment by mworrell** [comment]
A `&nbsp;` has a width, funny that it sticks together.
(And also weird that tinymce puts that there in the first place)

**Comment by mworrell** [comment]
Old (2012) stackoverflow entry discussing a similar issue:

http://stackoverflow.com/questions/12247681/tinymce-is-adding-nbsp-instead-of-the-space-when-using-the-word-paste

**Comment by mworrell** [comment]
Closing, as this is more a tinymce issue than a zotonic issue.
