### ISSUE TITLE
Subscribe on ~pagesession does not work

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1622]
This JS:

```
pubzub.subscribe("~pagesession/bla", function (topic, msg) {
    alert("SUBSCRIBED");
});
```

is not triggered when you run

```
z_mqtt:publish(…)
``` 

on the server (while the `page_id` is available in Context and identical to JS `z_pageid`). Using `~session/bla` works perfectly fine because when the server-side session process is started, that process relays `~session/#` to the client.

Proposed solution: 

1. on-demand relay topic for pagesession notifications: only subscribe to that when user is subscribing to some `~pagesession` topic
2. later: look into two-way relay from server to client.

**Comment by mworrell** [comment]
In master we have a new topic tree.

Not fixing this for the 0.x
