### ISSUE TITLE
Use |summary in mod_seo

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1628]
Can we change the way the meta description is being used in the _html_head.tpl from mod_seo. I would prefer to use the |summary filter so it will take the body text into account if there is no summary.

**Comment by ddeboer** [comment]
Good idea! Could you open a PR?

**Comment by mworrell** [comment]
I am doubting a bit about the summary filter, as that filter is quite inefficient for resources without a summary.

If this is done then the summary-filter result should also be cached in the memo cache, as the summary is used at least three times: for Twitter, Facebook and the SEO description.

**Comment by mworrell** [comment]
Another option is to always fill the *SEO description*  in the resource. This could be used for Twitter and Facebook as well.

It is quite straight forward to make this description multi-lingual. And when we are on it: maybe also the slug, title, and seo keywords?

**Comment by DorienD** [comment]
Isn't the summary filter meant to create a summary even if the summary isn't filled in? Cause it checks if there is a summary, if not uses a part of the body. I think if we would fill the SEO description field it would only add more complexity.

Scenario's:
1. Summary or body text changes, the automatically filled SEO description field gets updated?
2. If the SEO description field is manually filled in, the SEO description field should be left alone if the above is activated. 

I'm not so familiair with the memo caching thingy.

**Comment by robvandenbogaard** [comment]
I think I am in favor of not copying the data into the SEO description field, and caching the summary.

**Comment by mworrell** [comment]
I agree to use the `|summary`, the performance should be fixed in some other way.
