### ISSUE TITLE
Warning about missing when only mod_content_groups is enabled

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1632]
When you enable mod_content_groups without enabling mod_acl_user_groups you get warnings about a missing category.

```
(zotonic001@Edo)2> 11:06:14.220 [warning] Query: unknown category 'acl_collaboration_group'
```

The admin interface probably uses the category somewhere without checking that the acl user groups module is enabled.

**Comment by mworrell** [comment]
This is also a bit of a problem with generic software.

On the one hand we want to show this kind of errors as it is useful for debugging, on the other we don't want to spam our log files with these.

Should we show these errors or not?

**Comment by mmzeeman** [comment]
This is a problem in an admin template in mod_content_groups. It adds things to a menu which uses mod_acl_user_groups. 

https://github.com/zotonic/zotonic/blob/master/modules/mod_content_groups/templates/_admin_button_dropdown_content_groups.tpl#L12

It is fixable with an all include, although that might mess up the current order in the menu as both modules have the same prio.
