### ISSUE TITLE
mod_acl_simple_roles and mod_acl_adminonly no longer work in master

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1633]
The old acl modules no longer work in master because macro's are missing and some observers are changed.

Wasn't it the idea to move these modules out of the core but still have them functional for backwards compatibility?

**Comment by mworrell** [comment]
Yes, we wanted to move them outside the core.

We might need to add some extra support for those modules.
Maybe we can make those external modules *1.0 only*?
(Or have two branches there, 0.x and 1.x ?)

**Comment by ddeboer** [comment]
We [decided](https://github.com/zotonic/zotonic/pull/1328) to drop BC for these modules. This is [documented](http://docs.zotonic.com/en/latest/developer-guide/upgrading.html#acl) in our upgrading guide.

**Comment by mmzeeman** [comment]
This issue is related to #1634

**Comment by mmzeeman** [comment]
If those modules no longer work in 1.0 it will be a harsh experience when people want to move form 0.x to master.

**Comment by mmzeeman** [comment]
We can also use macro's in the old acl modules. That shouldn't be too problematic for `mod_acl_adminonly`. 

I think it is important to have at least one other acl implementation hooked to core zotonic. At the moment I have a hard time reading through the acl code. It is hard time figuring out what acl call is done when. For instance, when I trace back the current code in master for inserting new resources, I don't see any check made check that a user is allowed to create a resource of a specific category in a specific content-group. In the 0.x branch this is not done in the is_allowed call but in a separate call.

**Comment by ddeboer** [comment]
> When those modules no longer work in 1.0 it will be a harsh experience when people want to move form 0.x to master.

True, but a major version is the time to introduce BC breaks. We decided that mod_acl_user_groups will be the default ACL implementation in 1.0. So do you agree with dropping support for the other modules on 1.0? That makes maintenance much easier.

**Comment by mmzeeman** [comment]
The thing is that we can't use `mod_acl_user_groups`. It leads to an unworkable administration load for our multi-tenant system.

**Comment by ddeboer** [comment]
You can enable mod_acl_user_groups and customise for your situation by creating [acl_is_allowed](http://docs.zotonic.com/en/latest/ref/notifications/acl.html?highlight=acl_is_allowed#acl-is-allowed) observers.

**Comment by mworrell** [comment]
What are the main reasons that they don't work anymore?  The `visible_for` flag that has been removed?  It is innocent to keep that one around, as we also use it for privacy levels in other ACL systems.

**Comment by mmzeeman** [comment]
From what I remember, some imports are gone so some things do not compile anymore. That is probably fixable with some strategically placed ifdefs.
