### ISSUE TITLE
Remove exceptions

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1641]
In the resource routines some exceptions are thrown.

There are a couple of problems with that:

 1. This is against the principle of non-local returns in Erlang
 2. Code becomes harder to reason with
 3. The *throw* looks different after a `z_db:transaction/2` call, as it is rethrown but with the original stack trace tagged on

I propose to replace most throws with simple `{error, …}` return values.

**Comment by mmzeeman** [comment]
👍

**Comment by mmzeeman** [comment]
FYI, quote from "Learn You Some Erlang": 

> As a rule of thumb, try to limit the use of your throws for non-local returns to a single module in order to make it easier to debug your code. It will also let you change the innards of your module without requiring changes in its interface

**Comment by mmzeeman** [comment]
See also test added for fix of: #1639
