### ISSUE TITLE
Not possible to add Date range

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#1642]
I tried to add an Event with a date range. The event gets added but the From and Till dates are not saved. Used Firefox or Chromium. Erlang 19 (erts 8.2). Zotonic 1.0-dev-62520f4

**Comment by karlsson** [comment]
I tested a bit more. The models/m_rsc_update:to_int/1 function need to handle binary strings.
```
diff --git a/src/models/m_rsc_update.erl b/src/models/m_rsc_update.erl
index 9d9e544..c9a5d47 100644
--- a/src/models/m_rsc_update.erl
+++ b/src/models/m_rsc_update.erl
@@ -1124,6 +1124,8 @@ to_int("") ->
     undefined;
 to_int(<<>>) ->
     undefined;
+to_int(<< A/binary >>) ->
+    to_int(binary_to_list(A));
 to_int(A) ->
     try
         list_to_integer(A)
```

**Comment by mworrell** [comment]
Ahh, remnants from our *binaryfication* of all arguments.
Thanks!
