### ISSUE TITLE
Embed twitter js removed

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#1646]
Currently a twitter embed looks like this:
`<blockquote class="twitter-tweet" data-lang="en"><p lang="nl" dir="ltr">Onze Dorien coachte haar groep CMD-studenten en hun &#39;Ready, Set, Match&#39; naar overwinning op de <a href="https://twitter.com/DDA_NL">@DDA_NL</a> Talentendag! <a href="https://t.co/ozuN9GJtxc">https://t.co/ozuN9GJtxc</a> <a href="https://t.co/cscofsja18">https://t.co/cscofsja18</a></p>&mdash; Driebit (@driebit) <a href="https://twitter.com/driebit/status/846344481276416000">March 27, 2017</a></blockquote>
<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>`

The script is removed when it is saved to the database.
Is it possible to add `//platform.twitter.com/widgets.js` to z_sanitize.erl ?

**Comment by ddeboer** [comment]
Please open a PR! :wink:
