### ISSUE TITLE
mod_export - Query export of type atom doesn't use the actual query

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1648]
The result of dispatch ["export", "query", type, id]
results in a atom list of the latest created resources not the result of query with the id.
check:
https://hart.amsterdam/export/query/atom/361
which should have the same results as
https://hart.amsterdam/nl/page/361/amsterdam-museum-blog
But it doesn't.

**Comment by mworrell** [comment]
What is the query in rsc 361?

**Comment by krista-ramakers** [comment]
It's 
cat=article
hasobject=[361,blogposting]
sort=-publication_start

**Comment by mworrell** [comment]
If I look at the feed and the page then the first couple of items are the same.
What is the difference between them?

**Comment by mworrell** [comment]
The complete feed is *exactly* the same as the articles on the *amsterdam-museum-blog* page.
Please reopen if there is a clear description of the problem.

**Comment by mworrell** [comment]
Upon closer inspection the cause of the confusion is clear.

In the source of the page there is a feed mentioned.
But this is the default *article* feed provided by `mod_atom_feed`.
This should be replaced by the page feed itself.

Note that `mod_atom_feed` has been removed from the master.

**Comment by fredpook** [comment]
I don't understand why this issue is closed.
https://hart.amsterdam/export/query/atom/361
is not the same as
https://hart.amsterdam/nl/page/361/amsterdam-museum-blog
can we reopen this or do you need additional info?

**Comment by mworrell** [comment]
I have looked at https://hart.amsterdam/export/query/atom/361 and it shows the same articles as https://hart.amsterdam/nl/page/361/amsterdam-museum-blog

In the HTML `<head/>` there is a link to an Atom feed, but that is a feed of all *article* feeds.

To get the correct the Atom feed on the page the mod_atom_feed needs to be disabled and new link element with the correct feed needs to be included.

**Comment by fredpook** [comment]
ok, i understand now. I switched off the module mod_atom_feed. Thanks
