### ISSUE TITLE
Remove whitespace email address in mailto: links

### ISSUE THREAD

**Issue by yorivanloo** [zotonic/zotonic#1653]
If you place a white space between a link for example in a href="mailto: test@test.nl" the html won't be vaild then. (https://validator.w3.org)

<img width="513" alt="screen shot 2017-04-06 at 11 48 23" src="https://cloud.githubusercontent.com/assets/7078817/24748515/272d2c2a-1ac0-11e7-9ea6-e41ee5c4224d.png">

Is it possible that we could remove the whitespace's by force?

**Comment by mworrell** [comment]
Fixed in https://github.com/zotonic/z_stdlib/issues/15

**Comment by mworrell** [comment]
Fixed in e164150

**Comment by mworrell** [comment]
Upgraded z_stdlib in 207bce4c112d60e769527e7a9d8ab01dfc4a9428
