### ISSUE TITLE
mod_video_embed - iframe embed code should not have frameborder

### ISSUE THREAD

**Issue by yorivanloo** [zotonic/zotonic#1654]
it should be in the css 'border: none'.

https://github.com/zotonic/zotonic/blob/master/modules/mod_video_embed/mod_video_embed.erl

line 300.

**Comment by mworrell** [comment]
Should that not be in the CSS?

**Comment by yorivanloo** [comment]
Yes i can do that, but could it be removed in the .erl?

**Comment by mworrell** [comment]
Ah, you meant that the `iframeborder` is not supported in HTML anymore...

**Comment by yorivanloo** [comment]
No it is supported, but it is obselete.

**Comment by yorivanloo** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/7078817/24754100/5967c078-1ad5-11e7-8266-e4ea10db6e6b.png)

**Comment by mworrell** [comment]
You can make a merge-request, if you like.
