### ISSUE TITLE
re:run error after upgrade to 1.0

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1658]
Hi,
I upgraded from 0.19 to 1.0 (master) .
When trying to see any News I get a 500 error with below error in console.
Looks like it is linked to an issue in a .tpl using :  
{% if m.rsc[id].short_title|match:"fa fa" %}

is there something I missed ?

`cowmachine:72 stop_request 500 (reason {badarg,[{re,run,[{trans,[{fr,<<"Erlang/OTP : Add process SASL log view in observer">>},{en,<<>>}]},<<"fa fa">>],[]},{filter_match,match,3,[{file,"modules/mod_base/filters/filter_match.erl"},{line,27}]},{tpl_a057aaa7c3adcdd08e1d8712b49b3c2251a3b7be,render,3,[]},{template_compiler,render,4,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,105}]},{z_template,render_block,4,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/support/z_template.erl"},{line,98}]},{controller_page,provide_content,1,[{file,"modules/mod_base/controllers/controller_page.erl"},{line,99}]},{cowmachine_decision_core,controller_call,3,[{file,"/usr/local/zotonic/_build/default/lib/cowmachine/src/cowmachine_decision_core.erl"},{line,55}]},{cowmachine_decision_core,decision,3,[{file,"/usr/local/zotonic/_build/default/lib/cowmachine/src/cowmachine_decision_core.erl"},{line,570}]}]})`

**Comment by mworrell** [comment]
Hi Eric,

I pushed a fix.

This is a consequence of the new template compiler.
Filters can now also receive raw data, like {trans, …} tuples.

ErlyDTL converted this before the filter was called, which gave problems for filters wanting to work on those values.

A pull should fix this.

Thanks,  Marc

**Comment by mworrell** [comment]
Fixed in f93207aac5621cd6a9a839d29445c53762f2c0ca

**Comment by crownedgrouse** [comment]
Hello Marc, thanks for your quick reaction, but unfortunately it crashes elsewhere : 

`cowmachine:72 stop_request 500 (reason {function_clause,[{z_string,trim,[{trans,[{fr,<<"Debian package framework for Erlangers">>}]}],[{file,"/usr/local/zotonic/_build/default/lib/z_stdlib/src/z_string.erl"},{line,78}]},{search_query,parse_query,3,[{file,"modules/mod_search/support/search_query.erl"},{line,473}]},{search_query,search,2,[{file,"modules/mod_search/support/search_query.erl"},{line,42}]},{z_notifier,first1,3,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/support/z_notifier.erl"},{line,204}]},{z_search,search,3,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/support/z_search.erl"},{line,102}]},{m_search,search,2,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/models/m_search.erl"},{line,83}]},{m_search,m_find_value,3,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/models/m_search.erl"},{line,57}]},{z_template_compiler_runtime,find_nested_value_1,4,[{file,"/usr/local/zotonic/_build/default/lib/zotonic/src/support/z_template_compiler_runtime.erl"},{line,251}]}]})`

**Comment by mworrell** [comment]
Seems you a {trans, _} record is passed as a search term.
I have modified the text search to allow such a term.

- Marc

**Comment by crownedgrouse** [comment]
I got now two kind of errors : 
1) some pages are displayed but an error in console :  
` m_search:91 Error in m.search[{query,[{cat,<<"tweet">>},{pagelen,3},{text,{trans,[{en,<<"Geas">>},{fr,<<"Geas">>}]}},{pagelen,1}]}] error: {error,{unknown_query_term,{text,{trans,[{en,<<"Geas">>},{fr,<<"Geas">>}]}}}}`
2) other pages with 500 error (crash) and this error in console :  
`cowmachine:72 stop_request 500 (reason {function_clause,[{z_convert,to_list,[{trans,[{en,<<"Gear Rebar3">>},{fr,<<"Gear Rebar3">>}]}],[{file,"/usr/local/zotonic/_build/default/lib/z_stdlib/src/z_convert.erl"},{line,66}]},{template_compiler_operators,to_values,2,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,191}]},{template_compiler_operators,eq,4,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,165}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,'-render/3-fun-10-',2,[{file,[]},{line,94}]},{template_compiler_runtime_internal,'-forloop_fold/7-fun-0-',9,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,70}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{template_compiler_runtime_internal,forloop_fold,7,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,54}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,render,3,[{file,[]},{line,389}]}]})`

**Comment by crownedgrouse** [comment]
looks like {trans, _} tuple create many trouble. When is the language chosen ? does it mean the template does not receive the right language, but all translation entries ? Is the goal to compile template once for any language ?

**Comment by mworrell** [comment]
There was still a *when*  restriction in the code, should work better now.

And indeed, the `{trans, ...}` terms are now passed to filters and other places, before it was selected just before calling a filter.

The template is translated once and includes all translations. During runtime the correct translations are selected.

**Comment by crownedgrouse** [comment]
indeed it was the issue. It is solved now by adding the default rule. Note, I did not used ACL before upgrading, and I added incrementally missing modules for the upgrade, one by one, compiling and trying to start. It is maybe the cause of this issue.

**Comment by crownedgrouse** [comment]
Work much better now, but below issue on some pages : 

`cowmachine:72 stop_request 500 (reason {function_clause,[{z_convert,to_list,[{trans,[{en,<<"Gear Rebar3">>},{fr,<<"Gear Rebar3">>}]}],[{file,"/usr/local/zotonic/_build/default/lib/z_stdlib/src/z_convert.erl"},{line,66}]},{template_compiler_operators,to_values,2,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,191}]},{template_compiler_operators,eq,4,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,165}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,'-render/3-fun-10-',2,[{file,[]},{line,94}]},{template_compiler_runtime_internal,'-forloop_fold/7-fun-0-',9,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,70}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{template_compiler_runtime_internal,forloop_fold,7,[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,54}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,render,3,[{file,[]},{line,389}]}]})`

**Comment by crownedgrouse** [comment]
Marc, could you please re-open this ticket, as the upper issue is not fixed ? in order not to forget .

**Comment by mworrell** [comment]
I opened a new ticket for that, see issue #1669
