### ISSUE TITLE
Upgrade to 1.0 need a first login to admin

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1660]
Hi, 
I get a strange behavior when upgrading from 0.19 to 1.0, as well when pulling master branch and recompile. My Web site is available but without any entries, I mean no articles,  no news, on the website skeleton.  My first fear was having lost all entries in database but a manual connection to database show me that issue was another. 
I tried to see what happens when logging to /admin.  I saw all my articles,  good. And strangely the website was OK then once a first login to admin. Looks like there is a need of a first login in order the cache or access to resources to be OK.

**Comment by mworrell** [comment]
I think you are missing a ACL module.

With the master we are moving to `mod_acl_user_groups` (with `mod_content_groups`) instead of the older `mod_admin_only` and `mod_acl_simple_roles`.

Try to enable the new ACL module (and mod_content_groups).

**Comment by crownedgrouse** [comment]
Marc, I already added those modules in config files while upgrading. Zotonic refused to start otherwise and complained in console for those modules to be added.
```
 {install_modules,
  [
   mod_content_groups,
   mod_acl_user_groups,
```

**Comment by crownedgrouse** [comment]
note, I do not know if it is relevant but I get this warning in console : 
```
10:43:01.388 [info] zotonic:147 Web server listening on IPv4 any:8000, SSL any::8443
10:43:02.519 [warning] lager_error_logger_h dropped 36 messages in the last second that exceeded the limit of 50 messages/sec
10:43:03.048 [warning] lager_error_logger_h dropped 52 messages in the last second that exceeded the limit of 50 messages/sec
```
unfortunately no clue to know who is flooding lager.

**Comment by mworrell** [comment]
The lager is always a bit busy when starting up :-)

You can check if the ACL rules are set up correctly. I have seen once that it didn't go wel during an upgrade... didn't figure out why yet.

Check `/admin/acl/rules`

It should say something like that *Anonymous users* have *view* permission on all *normal content groups*

If you change anything here, don't forget to use the *Publish* button on the top right.

**Comment by crownedgrouse** [comment]
(sorry confusing both ticket number) indeed it was the issue. It is solved now by adding the default rule. Note, I did not used ACL before upgrading, and I added incrementally missing modules for the upgrade, one by one, compiling and trying to start. It is maybe the cause of this issue.

**Comment by crownedgrouse** [comment]
well; in fact my first though seems to be true. it was not the fact to add a rule for anonymous user , but the fact I was logged as admin while add he rule that allow to see my content in the web site. 
tonight I stopped the zotonic node, restart it and same problem. no content in the web site. I log as admin, and check the ACL rule, still there. I look at web site, content is now visible !

**Comment by crownedgrouse** [comment]
(a parte) ACL menu entry in french is not correct :   Auth/Acceder au control   should be Auth/Contrôle d'accès

**Comment by mworrell** [comment]
That you can see it after logging in as admin is because the admin can see everything.

Do you have a screenshot of the your rules?

Also check if you published your rules (big button upper right).
We have two sets of rules, the edit and the publish version.
This so that you can first test before publishing a new set.

**Comment by crownedgrouse** [comment]
![image](https://cloud.githubusercontent.com/assets/4357695/25304423/132d037c-2767-11e7-89dd-36f437e9633c.png)

I'm pretty sure that last time I pushed the 'Publish' button , as you asked. Unfortunately I cannot reproduce now the issue. Either the push was not effective, or there is subtle issue I cannot understand for now.

**Comment by crownedgrouse** [comment]
BTW do you accept PR for i18n or is there official translators for french ?

**Comment by mworrell** [comment]
PRs and merge-requests for translations are welcome!  (especially for the 1.0/master)

**Comment by crownedgrouse** [comment]
Hi Marc, just to say I'm in process to do a PR for French i18n. Reserving this in case someone else wanted to do as well.

**Comment by ddeboer** [comment]
Closing this as the issue seems to be resolved.

@crownedgrouse We’re looking forward to your French translations!
