### ISSUE TITLE
Status site no longer accessible on 0.x

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1668]
When logging in I get this network response:

```
{'z_msg_ack',1,4~-z-1~,'page','undefined',20~c6sAmqax2u38GjmdeVuE~,{'error',{'checksum_invalid',114~hgj5aVEhNZb4HsWh9h8qvUr4ywKDaAVrAAZzdWJtaXRkAAl1bmRlZmluZWRkAAl1bmRlZmluZWRqZAAZY29udHJvbGxlcl96b3RvbmljX3N0YXR1cw~}}}$
```

No error message, just keeps showing the sign in form.

**Comment by mworrell** [comment]
Still a problem?

If so then the page is generated using a different *sign key* than the receiving routines.
Am not sure what the cause could be.

**Comment by ddeboer** [comment]
Closing due to lack of feedback. Please feel free to re-open if you’re still encountering the issue.
