### ISSUE TITLE
Crash in template loop

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1669]
From issue #1658, as reported by @crownedgrouse

"Work much better now, but below issue on some pages :" 

```
cowmachine:72 stop_request 500 (reason {function_clause,[{z_convert,to_list,[{trans,[{en,<<"Gear Rebar3">>},{fr,<<"Gear Rebar3">>}]}],
[{file,"/usr/local/zotonic/_build/default/lib/z_stdlib/src/z_convert.erl"},{line,66}]},{template_compiler_operators,to_values,2,
[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,191}]},{template_compiler_operators,eq,4,
[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_operators.erl"},{line,165}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,'-render/3-fun-10-',2,[{file,[]},{line,94}]},{template_compiler_runtime_internal,'-forloop_fold/7-fun-0-',9,
[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,70}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{template_compiler_runtime_internal,forloop_fold,7,
[{file,"/usr/local/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,54}]},{tpl_5152b898bc54cc2c016bc33d9ed75825af60ebd9,render,3,[{file,[]},{line,389}]}]})
```

**Comment by mworrell** [comment]
@crownedgrouse are you looping of a body or other translation tag?  Maybe you can post the temple code here, that would help in coming up with a strategy how the for-loop should handle `{trans, [...]}` tags.

**Comment by mworrell** [comment]
I have updated the expression handling in template_compiler.

https://github.com/zotonic/template_compiler/commit/62d8fa82c23c8195b30795bc22fb48e18b81fd88

Can you check again with these changes?

**Comment by crownedgrouse** [comment]
I did a git pull and recompiled but I got those errors now : 

`m_search:91 Error in m.search[{query,[{cat,<<"news">>},{is_published,true},{hassubject,360},{is_public,true},{sort,<<"-rsc.publication_start">>}]}] error: {error,{unknown_query_term,{is_public,true}}}`

Should I remove {is_public, true} or replace for another tuple, since ACL is used ?

**Comment by mworrell** [comment]
The `is_public` term was indeed removed, as the current ACL model doesn't have such a simple test anymore.

**Comment by crownedgrouse** [comment]
Could this tuple being ignored and a console warning done instead ? This would help people to migrate to 1.0...

**Comment by mworrell** [comment]
I have removed it from the list of known terms, so now there should be a lager error and the term will be ignored.

**Comment by crownedgrouse** [comment]
Fair enough,  thanks !

**Comment by mworrell** [comment]
Closing this (for now :) )

**Comment by crownedgrouse** [comment]
just to notice that I get the lager log, but  entries using this tuple for search are not shown. I needed to remove it from templates to let it see. I though this tuple would be ignored and have no impact in the code, but it don't. I do not know if it is intentional, I maybe not well understood.
