### ISSUE TITLE
Collect process statistics

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1670]
Add a way for Zotonic to collect statistics on processes it supervises. Each process should maintain its own statistics, but be able to hand them over to Zotonic (z_stats) for displaying in the admin web interface and perhaps further notifications. 

One way to link Zotonic to the individual processes is a simple function convention:

```erlang
handle_cast({z_stats, info}, State) ->
    ...
```

z_stats will then periodically call this function on all processes to collect their stats. 

Useful examples include:

- number of depcache cleanups (due to depcache size limit)
- …

**Comment by CyBeRoni** [comment]
These statistics should be collectable externally somehow so they can go into a TSDB for graphing and alerting.

**Comment by mmzeeman** [comment]
That is what exometer is for... It acts as a middleware between the stats and the stat collection.

**Comment by mmzeeman** [comment]
BTW, I was working on a stats collection to a sql database, but I had to stop due to other prio's. 

The thing is that TSDB solutions usually downsample the data via nth point or averaging functions. By doing this you loose the meaningful peaks in your data. I was working on an exometer solution which uses the (beautiful) algorithm explained in this thesis: 
http://skemman.is/stream/get/1946/15343/37285/3/SS_MSthesis.pdf

**Comment by CyBeRoni** [comment]
> By doing this you loose the meaningful peaks in your data.

I'm sure that's true, but I don't see that as a reason to not have the ability to do it. Not having this data at all is worse.

**Comment by mmzeeman** [comment]
You can hook up external tsdb's like opentsdb, graphite and more. I didn't need the data so far. :-)

**Comment by CyBeRoni** [comment]
I'm looking at using exometer to send my data out to a tsdb but I'm running into a problem.

I have put the following in my erlang.config:

```
 {exometer, [{report, [
        {subscribers, [                
                {select, {[{ {[zotonic, '_', '_', '_'], 'gauge', '_'}, [], ['$_'] }], exometer_report_tty, value, 10000, false}}
        ]},
        {reporters, [
            {exometer_report_tty, []},
        ]}
    ]}
 ]},
```

The idea being to gather such metrics as the number of sessions per site, without having to put each site and metric in the config explicitly. Unfortunately, that does not seem to work. It does work if I instead do put in an explicit metric to send:

`{exometer_report_tty, [zotonic,sitename,session,sessions], value, 10000},`

which nets me:

`Apr 27 23:08:01 ginger-test zotonic[27722]: exometer_report_tty: zotonic_sitename_session_sessions_value 1493327281:0 (unknown)`

in my console. I can run the select manually, and see that it returns all the right metrics:
```
(zotonic001@ginger-test)1> exometer:select([{ {[zotonic, '_', '_', '_'], 'gauge', '_'}, [], ['$_'] }]).
[{[zotonic,sitename,session,sessions],gauge,enabled},
(a bunch more metric names snipped)
```

I expect this is because the init (and thus the select) is done before the metrics are known, and thus the select returns nothing at that time. 

Should I be configuring exometer somewhere else?

**Comment by mmzeeman** [comment]
Both are possible. 

If it are things which are known run-time only I usually put it in a module, which can configure it when the module starts. Otherwise I put it in the erlang.config file. Then de metric definitions and the reporter subscriptions are in the same file.

**Comment by CyBeRoni** [comment]
I don't really see how I can put reporters and subscriptions in a module without modifying the module source which is of course not a good idea.

It should be possible to configure exometer in one place and have that configuration apply to every part of the system. It seems to me like the static configuration in erlang.config is the place to do that. 

I think that the {select{}} and {apply{}} mechanisms should be periodically re-run (for example when a new metric is created) as right now even if zotonic only initialises the exometer reporters after the sites are started, it wouldn't pick up new metrics when you add a site later on.

**Comment by mmzeeman** [comment]
That is what I currently do.

eg.

https://github.com/zotonic/zotonic/blob/master/src/support/z_stats.erl#L35

That way the configuration stays up to date with the system.

I know it is possible to let the reporter behave in the way you want. Reporters get notified when new entries are defined, so they can implement auto subscription.

**Comment by mmzeeman** [comment]
FYI, the influxdb reporter supports auto subscription. It is not very hard to make generic autosubscribe functionality which can be used to ease configuration.

https://github.com/travelping/exometer_influxdb

**Comment by CyBeRoni** [comment]
Yeah but that isn't quite the same idea. Nor does it work generically.

I've sent the exometer guys a PR to fix this: https://github.com/Feuerlabs/exometer_core/pull/93

**Comment by mmzeeman** [comment]
Aha, we will see :-)

**Comment by mmzeeman** [comment]
Hmm, looking at the exometer code, it looks like it should automatically add new datapoints.

https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_report.erl#L1184

**Comment by CyBeRoni** [comment]
Yes, and it does but only if the datapoint is subscribed before it exists. Which is why the manual configuration above works. The thing is that {select, {}} does exometer:select(), which does a lookup in the ets, in which those metrics are not yet known at that time. So the metrics are never subscribed to.

**Comment by mmzeeman** [comment]
But it does a period select here.

https://github.com/Feuerlabs/exometer_core/blob/master/src/exometer_report.erl#L1404

**Comment by CyBeRoni** [comment]
Doesn't that only get called from do_report which pulls the metrics from the ets table (which our select isn't in?)

**Comment by mmzeeman** [comment]
No, I think the select should be in the ets table (a select subscription), which is called in do_report. That way unsubscribe is also easier... I think I can check later this evening. I have to do some cooking right now. :-)

**Comment by CyBeRoni** [comment]
The select is set-up only in the exometer environment variable and not copied (so far as I can tell) to the ets table. Perhaps that could be changed, but then it would do exometer:select() on every report which can be quite often which sounds like a potential performance problem.

**Comment by CyBeRoni** [comment]
I just tried the other way which does also work:

`exometer_report:subscribe(exometer_report_tty, {select, [{ {[zotonic, '_', '_', '_'], 'counter', '_'}, [], ['$_'] }]}, value, 1000).`

Now exometer:subscribe() does put the metric in the ets table of course, which is not where static entries end up. So as it is now, you'd have to do this programmatically somehow or configure it separately from exometer so zotonic can do the subscription.

**Comment by mmzeeman** [comment]
You can also put that in the erlang.config file.
```
 28 {subscribers, [
 29
 30         {exometer_report_tty, {select, [{ {[zotonic, '_', '_', '_'], 'counter', '_'}, [], ['$_'] }]}, value, 1000},
 31
...
```

**Comment by CyBeRoni** [comment]
I was literally trying that right this second.

**Comment by mmzeeman** [comment]
You can use other types of match specifications. This for example matches all entries of arbitrary length which starts with zotonic.

```erlang
 {subscribers, [
 29         {exometer_report_tty, {select, [
 30             {{[zotonic|'_'], '_', '_'}, [], ['$_']}
 31         ]}, value, 1000},
```

**Comment by ddeboer** [comment]
@CyBeRoni @mmzeeman Thanks for ‘hijacking’ the issue! We now have some extremely useful stats in our Grafana (based on Graphite).

I agree that exometer is the way to go. A built-in solution (such as dashboards shown on Zotonic’s status and site admin pages) is a separate issue.

Would be great to add a basic exometer configuration example to the Zotonic [cookbooks](http://docs.zotonic.com/en/latest/cookbook/index.html). No need to duplicate exometer’s docs, but just some pointers as to how to configure it (in `erlang.config`) for Zotonic. @CyBeRoni Do you feel like writing that?

**Comment by mmzeeman** [comment]
Maybe it is better to put the basic configuration in an erlang module. The we can attach our own dashboard to the metrics. Otherwise everybody will have a slightly different exometer setup.

**Comment by CyBeRoni** [comment]
> Otherwise everybody will have a slightly different exometer setup.

That is the point. I already have a system for collecting and reporting on metrics. I really don't need a second one that is specific only to zotonic. Being able to configure this myself to integrate into my existing systems is imperative.

**Comment by mmzeeman** [comment]
When we create our own on-server dashboard we will have to know the names of the metrics. For the basic metrics (vm memory stats, and core zotonic stuff)I want to have defined names. Otherwise it is impossible to create a meaningful dashboard. A DIY solution for everybody is not very zotonic like.

**Comment by CyBeRoni** [comment]
> For the basic metrics (vm memory stats, and core zotonic stuff)I want to have defined names.

These are [already defined by code](https://github.com/zotonic/zotonic/blob/c9840585f5b068ed019bd21ec427ae944180da93/priv/sites/zotonic_status/modules/mod_zotonic_statistics/mod_zotonic_statistics.erl#L58). The current solution is, so far as I can tell, great both for external reporting and if you were to create a zotonic-internal dashboard of sorts.

I would not advocate for a change in behaviour here at this point, only for adding more metrics.

**Comment by mmzeeman** [comment]
👍 

More meaningful metrics for the requests would be great. It is probably handy to make separate issues for different metric categories? Requests, pubsub, etc?

**Comment by CyBeRoni** [comment]
I've added some example usage to the documentation. Please have a look and see if it's reasonably understandable.

**Comment by ddeboer** [comment]
Closing this issue as we decided exometer is the way to go for collecting stats in Zotonic and the new doc chapter now points users in that direction.
