### ISSUE TITLE
ErlyDTL compiler creates too many atoms

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1673]
One of our servers just crashed with `no more index entries in atom_tab (max=1048576)`. As it turns out, the number of atom entries is very high on other servers as well. @mworrell reports nearly 1M entries on one of his servers.

The culprit seems to be [this line](https://github.com/zotonic/zotonic/blob/0.x/src/erlydtl/erlydtl_compiler.erl#L158) in erlydtl_compiler.

**Comment by ddeboer** [comment]
I propose that we raise the maximum number of atoms in tomorrow’s release by adding `-t 2000000` to the Zotonic boot scripts. When the bug has been fixed, we can revert that workaround.

**Comment by mworrell** [comment]
There are actually a couple of places in (our version of) the ErlyDTL compiler where variables are dynamically made using random postfixes.  A solution is to replace those with an incremental number, as this variable can then be reused between multiple compiled templates.

**Comment by mworrell** [comment]
The fix seems to hold up well.  Closing this issue.
