### ISSUE TITLE
Send depcache cleanups to exometer

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1677]
This is an important metric to monitor how often the depcache memory limit is reached.

**Comment by mmzeeman** [comment]
What shall we do? Create a ```depcache:info()``` call which returns a proplist with interesting depcache values?  That would allow us to hook exometer to the depcache without making it dependent on it.

**Comment by ddeboer** [comment]
Yes, that’s one way, with the advantage that `depcache:info()` can be useful without exometer, too.

Another way that @mworrell and I discussed yesterday is to pass a callback from z_depcache to depcache. Depcache calls the callback when some event happens (e.g. a depcache eviction). Z_depcache handles the call and does an `exometer:update()`. This is okay, as Zotonic itself is already dependent on Exometer. 

@mmzeeman @CyBeRoni Do you have any preference between having Exometer *poll* data or have the app *push* (`exometer:update()`) data into Exometer?

**Comment by mmzeeman** [comment]
I would like to know the max, the current size, the number of waiting pids. That can be displayed in graphs and when one gets close to the other draw attention to it as the configuration of the depcache probably has to change.

A callback which is called when forced cache eviction is done would be nice too. That would allow us to hook an alarm to it because the configuration is wrong (or values are kept too long).

I guess both are needed.

**Comment by mmzeeman** [comment]
FYI, currently I mainly use the shell to monitor zotonic... Mainly by counting the number of tcp connections by calling `length(recon:tcp())`, and monitoring the ram used. This week we hit a connection limit (on the nat layer of linux) which was not monitored of course. :-)

**Comment by ddeboer** [comment]
> which was not monitored of course. :-)

This sounds familiar. ;)

**Comment by CyBeRoni** [comment]
> Do you have any preference between having Exometer poll data or have the app push data (exometer:update()) into Exometer?

From my point of view I don't think there's much of a difference. Either exometer polls a function every X ms or it polls an ets entry every x ms. So it's pretty much the same to me so long as the function called isn't very expensive.

I think code-wise exometer:update() is easier to maintain though.

**Comment by mworrell** [comment]
I agree, better push to exometer.  That is easier for maintenance and will scale better in case of calls to processes etc.

**Comment by mmzeeman** [comment]
Yep, just checking every once in a while with sysctl. We Increased the hash size and increased the max... The default value for `nf_conntrack_tcp_timeout_established` is also strange... 5 days! Who waits for 5 days for a tcp connection?

**Comment by mworrell** [comment]
@mmzeeman could you write down your config changes, it is interesting for me (and others) as well.

**Comment by ddeboer** [comment]
Please do, I’ll add them to a new doc chapter on configuring the OS for Zotonic!

**Comment by mmzeeman** [comment]
It is all very ubuntu specific. It also depends on how zotonic is hooked to port 80 and 443. Does this matter? Sometimes I wonder wether it is better to move to a BSD variant, especially now that systemd is the default on the more recent debians.

**Comment by mworrell** [comment]
Unbuntu specific is ok - as it is a very popular distribution

**Comment by CyBeRoni** [comment]
> It is all very ubuntu specific. It also depends on how zotonic is hooked to port 80 and 443. Does this matter? 

If other people use the same way to put Zotonic on ports 80/443 (I don't but I believe Marc does), then it is useful for them. Any such document should also contain generic advice though -- such as to increase the max number of open files Zotonic can use and then with examples of how to do that.

> Sometimes I wonder wether it is better to move to a BSD variant

Would probably help with Zotonic's portability if you did :P I used to run Zotonic on straight Solaris which has required a couple of patches to the scripting mostly.

> especially now that systemd is the default on the more recent debians.

Systemd being default is a *good* thing. Also some of the BSDs are either already using a similar system (NextBSD uses launchd for instance) or are contemplating it. Other OSes (notably OSX, Solaris) have been using a more modern init system for well over a decade.

**Comment by mmzeeman** [comment]
In this case it was the default `net.nf_conntrack_max` of 65k connections which hit us. This is a bit off topic, but I think bsd's do not have limits for settings like these, but they grow automatically depending on the available memory.

**Comment by CyBeRoni** [comment]
> In this case it was the default net.nf_conntrack_max of 65k connections which hit us.

That's still useful information for people who don't use NAT because that is also the limit for open connections if you're using iptables in a stateful manner (i.e., using -m state).

@ddeboer perhaps you should make an issue or PR for that document you were intending to make so we can discuss these things in the appropriate place?

**Comment by mmzeeman** [comment]
I smell another snag :-)

**Comment by ddeboer** [comment]
See https://github.com/zotonic/zotonic/pull/1680.

**Comment by ddeboer** [comment]
Added in #1682.
