### ISSUE TITLE
problem in z_media_preview

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1688]
`z_media_preview:convert_2:113 convert cmd "'/usr/bin/convert' '/home/zotonic/user/sites/skl/modules/mod_base/lib/images/placeholder.png[0]' -background \"white\" -layers \"flatten\"   -gravity NorthWest -thumbnail 20x20\\!  -colorspace \"sRGB\" -set units PixelsPerInch -density 72   -quality 99 '/home/zotonic/user/sites/skl/files/preview/lib/img/account_slogan.png(250x20)(E1C53B2D73E3DB44221DC6600116BC4E).jpg'" failed, result {error,convert_error}
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-05-08 13:25:20.934 [info] <0.5977.0>@z_file_locate:convert_error_part:278 [skl] Error {error,convert_error} generating fallback preview for <<"/home/zotonic/user/sites/skl/files/preview/lib/img/account_slogan.png(250x20)(E1C53B2D73E3DB44221DC6600116BC4E).jpg">> with filters [{width,250},{height,20}]
zotonic      | 2017-05-08 13:25:20.936 [error] <0.5977.0> gen_fsm {{z_file_entry,<<108,105,98,47,105,109,103,47,97,99,99,111,117,110,116,95,115,108,111,103,97,110,46,112,110,103,40,50,53,48,120,50,48,41,40,69,49,67,53,51,66,50,68,55,51,69,51,68,66,52,52,50,50,49,68,67,54,54,48,48,49,49,54,66,67,52,69,41,46,106,112,103>>},{context,#{cowmachine_resp_body => undefined,resp_headers => #{<<99,97,99,104,101,45,99,111,110,116,114,111,108>> => <<110,111,45,115,116,111,114,101,44,32,110,111,45,99,97,99,104,101,44,32,109,117,115,116,45,114,101,118,97,108,105,100,97,116,101,44,32,112,111,115,116,45,99,104,101,99,107,61,48,44,32,112,114,101,45,99,104,101,99,107,61,48>>,<<101,120,112,105,114,101,115>> => <<87,101,100,44,32,49,48,32,68,101,99,32,50,48,48,56,32,49,52,58,51,48,58,48,48,32,71,77,84>>,<<112,51,112>> => <<67,80,61,34,78,79,73,32,65,68,77,32,68,69,86,32,80,83,65,105,32,67,79,77,32,78,65,86,32,79,85,82,32,79,84,82,111,32,83,84,80,32,73,78,68,32,68,69,77,34>>},cowmachine_resp_transfer_encoding => undefined,cowmachine_resp_content_encoding => <<105,100,101,110,116,105,116,121>>,cowmachine_disp_path => <<108,105,98,47,105,109,103,47,97,99,99,111,117,110,116,95,115,108,111,103,97,110,46,112,110,103,37,50,56,50,53,48,120,50,48,37,50,57,37,50,56,69,49,67,53,51,66,50,68,55,51,69,51,68,66,52,52,50,50,49,68,67,54,54,48,48,49,49,54,66,67,52,69,37,50,57,46,106,112,103>>,cowmachine_forwarded_host => ...,...},...}} in state locate terminated with reason: no case clause matching {error,convert_error} in z_file_locate:locate_source/5 line 90
`

**Comment by mworrell** [comment]
Preview generation currently working well, closing the issue
