### ISSUE TITLE
mod_import_csv - Handle incoming edges

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1690]
Currently only outgoing edges can be imported. This used to be very handy for handling user import and assigning them to usergroups (with hasusergroup). But since the addition of collaboration groups we would like to assign them with hascollabgroup (an incoming edge to the user).
Is it possible to check the predicate definition for the direction?

**Comment by mworrell** [comment]
Added support for incoming and outgoing edges.  Use `> author` or `< author` (where *author* can be any predicate name) as column headers.  In the field there should be a resource name or id.

**Comment by mworrell** [comment]
In testing with @fredpook, if ok then we merge this into master as well.

**Comment by fredpook** [comment]
Works perfect!

this is an example of importing persons and assigning them to collaboration groups
[import_persons_in_collabgroups.txt](https://github.com/zotonic/zotonic/files/1227655/import_persons_in_collabgroups.txt)

**Comment by mworrell** [comment]
Good example, I will add it to the documentation.

**Comment by ddeboer** [comment]
Created a separate issue for the docs: #1810.
