### ISSUE TITLE
Malformed objects in git repository

### ISSUE THREAD

**Issue by mbbx6spp** [zotonic/zotonic#1692]
I searched the issues for `hasDotgit` and found nobody reporting this issue yet.

I expected to be able to clone this git repository from Github but was unable to with the `transfer.fsckobjects` option set to true. When fetching objects from a remote this option will make `git-fetch-pack` check all fetched objects and abort when a malformed object or a broken link is encountered. See https://github.com/git/git/blob/d10e2cb9d0299a26f43d57dd5bdcf2b3f86a30b3/Documentation/config.txt#L2691-L2694 for information on `transfer.fsckobjects` option.

I tried to clone using the https, git and SSH methods of cloning from your organization's public repository URL. I also attempted to clone from a fork I created.

Here is an example of a failure. It fails on the same object SHA each time (`031eba227fde3d82b8962537678701ac0cefbda6`).

```
$ git clone git://github.com/zotonic/zotonic
Cloning into 'zotonic'...
remote: Counting objects: 86634, done.
error: object 031eba227fde3d82b8962537678701ac0cefbda6: hasDotgit: contains '.git'
fatal: Error in object
fatal: index-pack failed
```

I suggest you run the following to report all of the malformed objects or broken links in the repository since this option will only fail on the first problematic object in the git database.

```
$ git fsck --full                                      
Checking object directories: 100% (256/256), done.    
warning in tree 031eba227fde3d82b8962537678701ac0cefbda6: hasDotgit: contains '.git'
warning in tree 0c8472159b917c6e472a0f65b26be31a57021499: hasDotgit: contains '.git'
warning in tree 14a5cae41e98f08fd2f6d807283f07fc6141e8e9: hasDotgit: contains '.git'
Checking objects: 100% (86634/86634), done.
```

For reference here is the pertinent git config information for this problem:

```
$ git config transfer.fsckobjects
true
$ git --version
git version 2.12.2
```

The git config option `fetch.fsckobjects` set to `true` will also cause this error to surface.

When I searched for this tree SHA I found the following reference to it: http://chatlogs.jabber.ru/erlang-talks@conference.jabber.ru/2013/01/11.html

It lists the tree object looking like:
```
$ git ls-tree 031eba227fde3d82b8962537678701ac0cefbda6
040000 tree cd78065b172904253f823ac55e3210370af1cda1    .git
100644 blob a961122cf332c52bee5e678dd6243515a376c554    Emakefile
100644 blob 08b71726713a5840d2fbe9f671486f1468ddc8f9    License.txt
100644 blob f6aedc90f44016ba45ee6c4b012511cab194a638    Makefile
100644 blob d2ff5f9beb73303a38c88c6be7291bd56ff6a4ce    README.txt
040000 tree 6532097400540586342df1748ae64f3456b21652    ebin
040000 tree 0d4e2865bd5c984d6563701231b3b2b9bc58fcec    src
```
It appears as if the reason this tree object is malformed is because it contains a `.git` tree (aka directory) which is a little inception-like.

The date on the chat references is from 2012, so the commit is definitely not new.

I am not sure what can be done here but thought I would let you know that this will impact more and more people as checking git object integrity and links becomes more important from a security perspective.

**Comment by mworrell** [comment]
Thanks for checking out Zotonic :)

I am trying to figure out *where* in the tree this commit is hiding.

As I can't find it by simply grepping 031eba227fde3d82b8962537678701ac0cefbda6 on the git log of master, I suspect it is in another branch.  Which, if true, could mean that we can just remove that whole branch.

/cc @arjan @ddeboer

**Comment by ddeboer** [comment]
```bash
$ git log --all --reverse 031eba227fde3d82b8962537678701ac0cefbda6 
commit a6d8e2efeb4c0872361c8bf2c0c5165c42893883
Author: marc@zoo.local <marc@zoo.local>
Date:   Thu Nov 12 19:52:25 2009 +0100

    Added r1392 from Zotonic svn

$ git show a6d8e2efeb4c0872361c8bf2c0c5165c42893883 --name-only|grep .git
deps/erlang-oauth/.git/HEAD
deps/erlang-oauth/.git/config
deps/erlang-oauth/.git/description
...
```

**Comment by mworrell** [comment]
So it was part of the move from svn to git.  Which makes sense, as svn doesn't find .git directories very special.  Wondering if we can prune some old history, given that git is really just a database.

**Comment by mworrell** [comment]
Looks like a *shallow clone* might do the trick?

http://stackoverflow.com/a/34829535/457795

**Comment by ddeboer** [comment]
Discussed this with @mworrell yesterday. 

Unfortunately, even a shallow clone requires a complete history rewrite of the Zotonic repository, thus changing the commit hashes. This means everyone with a local clone will have to reset it or – more easily – create a fresh clone. Also, open pull request will be screwed up.

So we will wait with this operation until the PRs that are currently open have been merged. When doing the rewrite, I propose to remove the whole `deps/` dir that existed previously, as this will not only get rid of the `.git` dirs but make the repo a bit smaller, too.

**Comment by mbbx6spp** [comment]
I apologize for leaving this open. I meant to reply much earlier and say that the shallow clone worked wonders, thanks! :)
