### ISSUE TITLE
Inserting/deleting an edge does not trigger a pivot on the resource

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1698]
Should it? Quickly looking over m_edge I don’t find any calls to `z_notifier`.

**Comment by mworrell** [comment]
The m_edge routines call `m_rsc:touch/2` on edge insertion/deletion.
This will trigger the re-pivot.

The *touch* can be disabled by adding `no_touch` to the m_edge options.

**Comment by ddeboer** [comment]
Ah, I now see what caused the confusion: while inserting an edge indeed triggers a touch on the edge’s _subject_, it doesn’t on the _object_. 

@mworrell Are you okay with triggering a touch on the object, too? My use case is that I’m indexing incoming edges with objects (for search purposes) and they are now not updated when an edge is added.

Alternatively, I could observe `edge_insert|delete|update` but that feels somewhat laborious.

**Comment by ddeboer** [comment]
See https://github.com/zotonic/zotonic/issues/1722.
