### ISSUE TITLE
Drop database before running tests

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1701]
Drop and re-create the testsandbox db between `make test` or `zotonic rumtests` to make the test runs more deterministic. This is already done for site tests in `z_sitetest`.

**Comment by mworrell** [comment]
I propose to drop the `testsandboxdb` before the the site is started.
This could be done by the sites manager by checking a special attribute in the site configuration.

This would also recreate the db on every (manual) restart.

**Comment by mworrell** [comment]
See #1909
