### ISSUE TITLE
Compiled user files in two places

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1706]
When `user_ebin_dir` is configured (on master), and some file in the user dir is compiled, e.g. `zotonic/user/sites/yoursite.erl`, the compiled version ends up in two places, with one of course hiding the other:

- `zotonic/user/ebin/yoursite.beam`
- `zotonic/_build/default/lib/zotonic/ebin/yoursite.beam` (the Rebar dir).

**Comment by mworrell** [comment]
Why do we have the `user_ebin_dir` directory?

And in the OTP 19 (20?) notes I saw that an option is being added to recompile a `.erl` file with the options that have been given before. Apparently those options are saved in the generated `.beam` file. That is worth investigating.

**Comment by mmzeeman** [comment]
It is needed to be able to install a site on a server without also giving the erlang sources of the site.

**Comment by ddeboer** [comment]
We use it to separate the core Zotonic files from our own site and module files. In theory, it should be possible to compile files locally and then deploy only the .beams to a running Zotonic server. That way, you wouldn’t have to compile on a live system. 

We’re also using it in our Docker builds (build a custom container based on a Zotonic one, which already includes the .beams), but I’m not sure the directories need to be separated there, or do they @CyBeRoni?

**Comment by mworrell** [comment]
If you want to ship the files to a customer, maybe you also want to use the option to encrypt debug information?

**Comment by mmzeeman** [comment]
For us this is enough for now... I think it is also possible to decompile beam files without debug_info if you look around.

**Comment by mworrell** [comment]
Example for compile_info:

```Erlang
(zotonic001@Lamma)11> z_url_metadata:module_info(compile).
[{options,[{outdir,"/Users/marc/Sites/zotonic-master/_build/default/lib/z_stdlib/ebin"},
           debug_info,debug_info,warn_unused_vars,warn_shadow_vars,
           warn_unused_import,
           {i,"/Users/marc/Sites/zotonic-master/_build/default/lib/z_stdlib/include"},
           {i,"/Users/marc/Sites/zotonic-master/_build/default/lib/z_stdlib"}]},
 {version,"7.0.4"},
 {source,"/Users/marc/Sites/zotonic-master/_build/default/lib/z_stdlib/src/z_url_metadata.erl"}]
```

If we are re-compiling an existing beam, then we need to use this information for the compilation options.

**Comment by mworrell** [comment]
@ddeboer shall I add the above to your branch (cq. merge request) ?

**Comment by ddeboer** [comment]
@mworrell Sure, go ahead: #1706.

**Comment by mmzeeman** [comment]
Nice...

**Comment by CyBeRoni** [comment]
> We’re also using it in our Docker builds (build a custom container based on a Zotonic one, which already includes the .beams), but I’m not sure the directories need to be separated there, or do they @CyBeRoni?

Not to my knowledge.
