### ISSUE TITLE
problem in mod_admin

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1709]
The admin does not open resources for editing, in mod_admin the function ensure_id always returns {context, undefined}

**Comment by mworrell** [comment]
Seems this problem is introduced in a2f27ddfe2f44a7bbdc9007e1860bc7c8c3538e8

There the `name_to_id` function is made more strict.
In this case the `rid` function should be used, as the argument is a (binary) resource id.

**Comment by mworrell** [comment]
Ref issue #1699

**Comment by mworrell** [comment]
@heiheshang thanks for reporting this!

It should work again now. The issue was indeed introduced with the changes for #1699

**Comment by ddeboer** [comment]
Thanks @mworrell for fixing this!
