### ISSUE TITLE
Replace mochijson2 with jsx

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1716]
Advantage: Erlang maps instead of hard-to-match `{struct, List}` structures.

**Comment by crownedgrouse** [comment]
Coming soon ;-) 

https://github.com/crownedgrouse/jason

As records still have some real interests in particular when wanting to compose deeply nested json objects....

**Comment by ddeboer** [comment]
Ah, very interesting! We’re now in the process of moving to JSX (#1745).

**Comment by crownedgrouse** [comment]
Yes, was only for memory.

**Comment by crownedgrouse** [comment]
For what is worth jsx does not look to be as efficient than expected,  by doing my own benchmark to compare to my project. jsone is maybe a better alternative...  https://github.com/crownedgrouse/jason/wiki/Benchmark
