### ISSUE TITLE
Publish Zotonic modules to Hex.pm

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1718]
1. Publish all Zotonic _core_ modules as packages to Hex.pm, so they can be used separately. This depends on #1717. I’ve already published [one example](https://hex.pm/packages/zotonic_mod_acl_user_groups). This allows users to build their own Zotonic distribution, picking the modules they need.
2. Introduce some naming convention for _third-party_ Zotonic modules. Perhaps `mod_zotonic_thing` or (probably better) `namespace_mod_zotonic_thing`, so we get `ginger_mod_zotonic_foundation`, `ginger_mod_zotonic_github`, `arjan_mod_zotonic_geo` etc. I know these names are longer (and less elegant) than we’re used to, but they have the advantage of being very clear. We can [search for these conventionally named packages on the Hex API](https://hex.pm/api/packages?search=mod_zotonic).
3. We can then replace the (probably outdated) module repository at http://modules.zotonic.com with our Hex integration, showing the module name, description, maintainer(s) and latest version. Even better, we can add a ‘Search for Zotonic modules’ in the admin that will automatically use Hex to add the module as a dependency (write to `rebar.config` deps or `zotonic.config`) and install it.

Depends on #1717.

**Comment by mworrell** [comment]
We need to establish the new naming convention.

Right now we use `zotonic_mod_...` for zotonic core modules, and `mod_...` for user modules.

Sites are currently recognized by the presence of a `priv/zotonic_site.config` file.

All this has to be fixed for #1743, #1742, and #1737

**Comment by mworrell** [comment]
I like the thinking of `namespace_mod_zotonic_thing`,  especially as ejabberd also uses `mod_something`

As we are now using `zotonic_mod_thing` for the core modules, shouldn't we use `namespace_zotonic_mod_thing` ?  Where *namespace* is empty for core or Zotonic published modules.

**Comment by ddeboer** [comment]
Agreed (that closes my point 2 above).

**Comment by mworrell** [comment]
Ok, will take incorporate the new naming scheme in the otp branch.

What shall we do with existing Zotonic modules?

 1. Rework in situ. Keeps history, name of repo doesn't match app name.
 2. Clone & rename.  Keeps the old one around.

/cc @arjan @mmzeeman

**Comment by mworrell** [comment]
@ddeboer Question: if we strip the namespace from `namespace_mod_thing` then we can run into module name collisions.  Shall we keep the namespace in the module names and only strip it for the core modules?

We can also strip it *if and only if* there is a bare `mod_thing.erl` in the src directory.

**Comment by mworrell** [comment]
Added the behaviour:

> We can also strip it if and only if there is a file namespace_zotonic_mod_thing/src/mod_thing.erl.

**Comment by ddeboer** [comment]
> What shall we do with existing Zotonic modules?

I prefer to rework in situ because keeping history is really important. We can create a `0.x` branch before making any changes to keep BC with Zotonic 0.x.

How many external modules are we talking about, actually?

**Comment by mworrell** [comment]
We have to check, but is probably not too bad.
I think ± 10-20 that we want to keep around.

And then of course the Driebit Ginger modules.
(And closed source modules, but that is not an issue right now)

**Comment by ddeboer** [comment]
I propose we use [Hexpub](http://github.com/zotonic/hexpub) to publish all built-in modules to Hex.

**Comment by mworrell** [comment]
👍 

I also want to add this to cowmachine, template_compiler, and dispatch_compiler.

**Comment by ddeboer** [comment]
We have a problem in that Hex only allows publishing packages that have all their dependencies listed on Hex (as opposed to GitHub). For instance the Cowmachine currently fails: https://github.com/zotonic/cowmachine/issues/3.

**Comment by mworrell** [comment]
Proposal for the releases:

 - 1.0 Release as an umbrella app
 - 1.1 (or 2.0?) Release core as separate Hex modules

This makes sure that don't delay the 1.0 release because of some external package problem.

**Comment by mworrell** [comment]
All dependencies are now on Hex

https://github.com/zotonic/zotonic/pull/2731

**Comment by mworrell** [comment]
Moving this back to the 1.0 milestone.
