### ISSUE TITLE
ec_semver_parser.erl failed

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1719]
`===> Compiling erlware_commons
===> Compiling _build/default/lib/erlware_commons/src/ec_semver_parser.erl failed
_build/default/lib/erlware_commons/src/ec_semver_parser.erl:15: export_all flag enabled - all functions will be exported

GNUmakefile:30: recipe for target 'compile' failed
make: *** [compile] Error 1
`
Can not compile in debian jessie

**Comment by ddeboer** [comment]
Do you happen to be on one of the OTP 20 RCs?

**Comment by heiheshang** [comment]
I just put the package erlang

**Comment by heiheshang** [comment]
This problem is in debian jessie, wheezy no problems

**Comment by ddeboer** [comment]
We switched to erlware_commons 1.0 (#1733) so this should be resolved now. Please let us know if you’re still having trouble.

**Comment by bgrace** [comment]
I just downloaded zotonic 0.30.0 and tried to build with Erlang 20.0 and rebar 2.6.4 on a Mac (10.12.5) and got the same error. Switching to Erlang 19 fixed it. Not a big deal, just FYI.

**Comment by ddeboer** [comment]
Correct: #1733 was only applied to master (1.0), on which our development efforts are currently focused.
