### ISSUE TITLE
Can't login in to admin area of new site

### ISSUE THREAD

**Issue by jeremiasalmeida** [zotonic/zotonic#1720]
Just created a new site using `/bin/zotonic -s <<sitename>>` and I am unable do login into the admin area of this new site.

I have tried admin:admin and had no success. Proceed to change the `{admin_password, "admin"},` to `{admin_password, "something_else"},` and try do login with admin:something_else and I am still unable to login at the admin area.

Not sure If I am missing something or this is a bug, I took a look at https://github.com/zotonic/zotonic/issues/93 and admin:<empty> can't even send the request.

**Comment by ddeboer** [comment]
Are you on master or on a 0.x version?

**Comment by jeremiasalmeida** [comment]
@ddeboer I am running this on a docker image with 1.0-dev version. Just got the latest version available on the docker hub.

**Comment by jeremiasalmeida** [comment]
Just figured it out how to solve the issue. I have used the content on https://groups.google.com/forum/#!msg/zotonic-developers/8XPliuWBXws/KWeUjnbhCgAJ to solve it. I guess this content should be documented with some highlight on the official documentation.


Thanks,,

**Comment by ddeboer** [comment]
@jeremiasalmeida Glad you were able to resolve your issue!

So that I can improve our docs for further users: what exactly was your problem? Was mod_authentication not enabled?

**Comment by jeremiasalmeida** [comment]
What solved my issue was the followings steps:

1. Download [mod_acl_simple_roles](https://github.com/zotonic/mod_acl_simple_roles) and [mod_acl_adminonly](https://github.com/zotonic/mod_acl_adminonly)
2. Add the downloaded modules to the modules page
3. Enable the downloaded module for the created site on the `config` file.

I saw on the docker container that a `admin` and a `acl` module existed but enabling them did not worked, no specific errors was outputted tho.

**Comment by ddeboer** [comment]
Did you create a new site, or did you try to use a site that was previously developed on Zotonic 0.x?
