### ISSUE TITLE
On edge insert/delete, pivot both subject and object

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1722]
Now only the _subject_ is touched, which actually isn’t necessary. Only re-pivoting (instead of touching) the subject is more efficient. If we do this, we can also re-pivot the object, to make sure we have [consistent data](https://github.com/zotonic/zotonic/issues/1698#issuecomment-307908358).

As discussed with @mworrell.

**Comment by mworrell** [comment]
Ported to 0.x in ebea452
