### ISSUE TITLE
Make HTTPS the default

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1723]
Currently, when creating a new site from the status site, its URL is http://newsite/admin (absolute_url). 

As we create HTTPS certificates for all sites now by default, it would be better to default the sites’ URLs to HTTPS as well. This way, we only have to care about exposing the HTTPS port (and mapping only that port in our Docker container).

**Comment by CyBeRoni** [comment]
> This way, we only have to care about exposing the HTTPS port (and mapping only that port in our Docker container).

You forget the http->https redirect that users will be expecting.

**Comment by ddeboer** [comment]
True. While the default can be HTTPS, we should still map the HTTP port.

**Comment by mworrell** [comment]
Master is now https only.
