### ISSUE TITLE
Problem email send

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1724]
`zotonic      | 2017-06-15 03:01:00 =SUPERVISOR REPORT====
zotonic      |      Supervisor: {local,zotonic_sup}
zotonic      |      Context:    child_terminated
zotonic      |      Reason:     {function_clause,[{string,strip_left,[<<"123@mail.ru">>,32],[{file,"string.erl"},{line,380}]},{string,strip,2,[{file,"string.erl"},{line,367}]},{z_email,split_name_email,1,[{file,"/srv/zotonic/_build/default/lib/zotonic/src/smtp/z_email.erl"},{line,197}]},{z_email_server,is_valid_email,1,[{file,"/srv/zotonic/_build/default/lib/zotonic/src/smtp/z_email_server.erl"},{line,1079}]},{z_email_server,spawn_send_check_email,6,[{file,"/srv/zotonic/_build/default/lib/zotonic/src/smtp/z_email_server.erl"},{line,483}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_email_server,handle_info,2,[{file,"/srv/zotonic/_build/default/lib/zotonic/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,601}]}]}
zotonic      |      Offender:   [{pid,<0.6744.47>},{id,z_email_server},{mfargs,{z_email_server,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]
zotonic      | 
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-06-15 03:01:00.165 [error] <0.6744.47> CRASH REPORT Process z_email_server with 0 neighbours exited with reason: no function clause matching string:strip_left(<<"123@mail.ru">>, 32) line 380 in gen_server:terminate/7 line 812
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/error.log <==
zotonic      | 2017-06-15 03:01:00.165 [error] <0.6744.47> CRASH REPORT Process z_email_server with 0 neighbours exited with reason: no function clause matching string:strip_left(<<"123@mail.ru">>, 32) line 380 in gen_server:terminate/7 line 812
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-06-15 03:01:00.165 [error] <0.305.0> Supervisor zotonic_sup had child z_email_server started with z_email_server:start_link() at <0.6744.47> exit with reason no function clause matching string:strip_left(<<"123@mail.ru">>, 32) line 380 in context child_terminated
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/error.log <==
zotonic      | 2017-06-15 03:01:00.165 [error] <0.305.0> Supervisor zotonic_sup had child z_email_server started with z_email_server:start_link() at <0.6744.47> exit with reason no function clause matching string:strip_left(<<"123@mail.ru">>, 32) line 380 in context child_terminated`

**Comment by mworrell** [comment]
Thanks! 

Fixed in fcd79396b193e12e6456a2d4b1539dbc5cbf151c
