### ISSUE TITLE
Inconsistent naming of caching options.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1730]
controller_file uses max_age and controller_template uses maxage to configure the cache parameter. For 1.0 we should probably make them the same.

**Comment by mworrell** [comment]
There are also some other max_age/maxage confusions:

* cache_anonymous_maxage
* max_age with cookies / session

As cowboy also uses `max_age` I propose to standardize on that spelling.

**Comment by ddeboer** [comment]
Agreed with `max_age`.
