### ISSUE TITLE
Nginx & SSL

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#1738]
I seem to have an issue with the `{ssl, true}` directive in dispatcher rules, and `{ssl_only, true}` in _zotonic.config_ when using Nginx as a proxy in front of Zotonic 1.0. Using the site as an anonymous user works fine, but when Zotonic attempts to redirect for an https connection, the page doesn't load. 

I have Nginx (1.13) configured for HTTP2, and followed the Zotonic cookbook reference for using Nginx with SSL termination. Regardless of whether the _proxy_pass_ directive in Nginx is set to `http://zotonicip:8000` with `ssl_listen_port` set to _none_ and `ssl_port` set to _443_, or `https://zotonicip:8443` with `ssl_listen_port` set to _8443_ and `ssl_port` set to _443_, any attempt by Zotonic (Cowboy?) to force an https connection breaks things. 

Any suggestions on what I am overlooking, and how to properly handle https redirects gracefully when using Nginx, other than editing all dispatch rules in all modules to be` {ssl, any}`?

**Comment by seannaswell** [comment]
Ok, it seems there is an easy answer...

I am still testing the optimum settings, but what works is _zotonic.config_ `listen_port` set to _8000_, `ssl_listen_port` set to _8443_, and both `port` and `ssl_port` are commented out. 

In _nginx.conf_ two things are required. First is `proxy_pass https://zotonicip:8443/;`. If set to `http://zotonicip:8000/`, when redirecting to https, the site breaks. The way to overcome non-standard ports were two redirects: `proxy_redirect https://website.net:8443 https://website.net;` and `proxy_redirect http://website.net:8000 https://website.net;`.

In this instance Nginx and Zotonic are on two different machines, and despite contradicting the Port Configuration section of the docs, it does seems to work as intended. If I am missing something obvious, please let me know.  Otherwise, while not sure what the root of the problem with redirecting is, I will consider this mystery solved...

**Comment by seannaswell** [comment]
This post helped resolve a configuration issue I had with Nginx and Websockets: https://groups.google.com/forum/#!topic/zotonic-users/GEEhQvmgSvo

All is working with Nginx and HTTP2 now.

**Comment by ddeboer** [comment]
Hey Seann, great you were able to resolve this issue by yourself! 

To help us improve our documentation, could you briefly summarise any differences from http://docs.zotonic.com/en/latest/developer-guide/deployment/nginx.html (if any) that you had to apply to your config?

**Comment by seannaswell** [comment]
Yes, and apologies for the wordiness. In summary, in nginx.conf the bits required are as follows:

change: `proxy_pass https://zotonic.ip:8443/;`  (note difference with existing example)
    
And add the following redirects:
```
        proxy_redirect https://website.net:8443 https://website.net;
        proxy_redirect http://website.net:8000 https://website.net;
```
My impression is that a difference between Cowboy and Mochiweb causes a glitch in Nginx, but am not familiar with headers and such to say what or why. The above changes resolved the issue, but if the source of the problem is discovered and resolved, these redirects for 8443 and modification of _zotonic.config_ in a non-standard way may not be needed going forward.

Also, remove the `proxy_set_header Upgrade` & `Connection` directives from the `location /` block, and added the following blocks:
```
        location /websocket {
                proxy_pass https://zotonic.ip:8443/websocket;
                proxy_set_header Host      $host;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
        }
        location /comet {
                proxy_pass       https://zotonic.ip:8443/comet;
                proxy_set_header Host      $host;
                proxy_buffering           off;
                proxy_next_upstream error;
        }
```
Of course there are other differences, as I am using HTTP2 and various other options, but the above allowed Zotonic to work behind Nginx. You can refer to this discussion for a good reference nginx.conf: https://groups.google.com/forum/#!topic/zotonic-users/GEEhQvmgSvo

**Comment by mworrell** [comment]
@karlsson updated the nginx documentation for master.

See http://docs.zotonic.com/en/latest/developer-guide/deployment/nginx.html

**Comment by karlsson** [comment]
Thanks @mworrell,
I terminate SSL in my nginx but I can see that the documentation also may need some update as per @seannaswell comments above when SSL is not terminated (in nginx), and also how to set things in zotonic.config. I can have a look at that.
