### ISSUE TITLE
If default admin user password is admin you can login with any password

### ISSUE THREAD

**Issue by jeremiasalmeida** [zotonic/zotonic#1740]
If the password of the default admin password is admin you can login into the admin page with any password.

I am using the 1.0-dev version running on docker.

If any further information is required, please let me known.

**Comment by mworrell** [comment]
"admin/admin" was not very secure, but this is even a bit more open :)

**Comment by jeremiasalmeida** [comment]
Completely intended, I was demoing the system to some people at my college and the simples the users the better.

**Comment by mworrell** [comment]
This has been changed back to a check for `"admin"` in 4d8a67c4b8dc982c51d970cac7c6fb9c8920e579

(As some people were complaining, though I agree with your simpler-is-better...)
