### ISSUE TITLE
OTP-ification: use hex for module installation

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1742]
~This can be done after #1717 has been merged~

Remove the *install module* scripts and use *hex* instead

**Comment by ddeboer** [comment]
Alternatively, let’s ditch install module and create site and document how to use Rebar directly.

**Comment by mworrell** [comment]
Removing the "install module" functionality is a good idea.
I agree to document how to perform this manually, as it is just doing the OTP app thing.

We have a "create site" in the `zotonic_status` site.
Also documenting this would remove the need of the command line scripts.

Currently we have these commands:

addsite compile compilefile configfile copysite createdb createschema debug dropschema etop generate-edoc logtail modules restart restartsite rpc runtests shell sitedir sitetest snapshot start start-nodaemon startsite status stop stopsite update wait

Which ones do we want to keep?

**Comment by ddeboer** [comment]
Well, I think we still need most of them except the `add*`s.

**Comment by mworrell** [comment]
Merge request #2184 cleans up the shell scripts and replaces them with erlscript.
