### ISSUE TITLE
Action documentation no longer accessible

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#1751]
The following page no longer links to pages that have any content on them:

http://docs.zotonic.com/en/latest/ref/actions/index.html

**Comment by Dirklectisch** [comment]
Filters page also broken:

http://docs.zotonic.com/en/latest/ref/filters/index.html

**Comment by DorienD** [comment]
**+1**

**Comment by mworrell** [comment]
@ddeboer any idea?  maybe something with the new OTP build?

**Comment by ddeboer** [comment]
Definitely related to that.

**Comment by mworrell** [comment]
I guess the build script can't find the relevant filters etc anymore (as they were moved)
