### ISSUE TITLE
There may be a bug in directive "listen 10.0.0.1:8080 ssl http2 ?

### ISSUE THREAD

**Issue by lioncfliu** [zotonic/zotonic#1752]
Sorry,my English is pool , I try my best to descripe problem I had encountered.

```Some descriptions from  Changes with nginx 1.9.7 .
Changes with nginx 1.9.7                                         17 Nov 2015
*) Bugfix: if nginx was built with the ngx_http_v2_module it was
       possible to use the HTTP/2 protocol even if the "http2" parameter of
       the "listen" directive was not specified
```
Even this bug is fixed in 1.9.7 , But in 1.10.1 , I encountered a strange case : 
I have two virtual  server tom.aa.com and tina.aa.com ,I  just want to eable http2 on tom.aa.com .
tom.aa.com and tina.aa.com listen on the same port 443.
so I configured nginx.conf like this:
```
#server 1
server {
      listen 127.0.0.1:443 ssl http2 ;
      server_name tom.aa.com;
      ...
} 
#server 2
server {
     listen 127.0.0.1:443 ssl;
     server_name tina.aa.com;
      ... 
}
```

Then ,I test tom.aa.com ,it gose on well with http2 .but tina.aa.com gose on well with http2, too.
 (Client adds ssl extension "ALPN: h2,http1.1"   when ssl handshake ) .
I got puzzled  ,I just  enable http2 on tom.aa.com ,why http2 goes well on tina.aa.com ?  
then I read the code : 

![image](https://user-images.githubusercontent.com/16104565/28120867-e6db89f4-674b-11e7-833e-87ee69ea3086.png)

**Comment by mworrell** [comment]
This is a Nginx issue, not a Zotonic issue.

@CyBeRoni Any ideas/comments? (as you have experience with nginx setups)

**Comment by CyBeRoni** [comment]
Indeed this is the wrong project. As for why that happens, it's probably because the response to the ALPN sent by the client includes http2, so the client has been told that you support http2 and will use it to talk to you. If you don't want that, don't use the same ip/port.

**Comment by lioncfliu** [comment]
maybe I made a mistake,sorry to trouble you

**Comment by mworrell** [comment]
Closing for now!
