### ISSUE TITLE
Duplicate identity logon box gets wrong classname

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1755]
When registering when you already have an account the error message doesn't get shown because the error on the z-logon-box is wrong. The classname is error_duplicate_username instead of the error_duplicate_identity. 

```
<div id="signup_logon_box" class="z-logon-box error_duplicate_username" style="width: 300px;">
    
        <h2 class="z-logon-title">Sign up</h2>

        <div id="signup_error_duplicate_identity" class="alert alert-danger">
            Sorry, there is already an account coupled to your account at your service provider. Maybe your account here was suspended.
        </div>
    <form></form>
    
</div>
```

**Comment by ddeboer** [comment]
Thanks for reporting! Do you want to submit a PR?

**Comment by mworrell** [comment]
There is a `username_unique` validator which performs a quick check if the username has been taken already.  (Of course this can also be used to check which usernames exists.. see #1802)

How do you register?  By filling in the form or using an external identity provider (like Facebook)?

**Comment by mworrell** [comment]
See #1908

**Comment by DorienD** [comment]
Filling in the form
