### ISSUE TITLE
mod_facebook - image is no longer handled since the deprication of facebook api v2.3

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1758]
The picture parameter probably has to be passed.
See: https://developers.facebook.com/docs/facebook-login/permissions/

**Comment by mworrell** [comment]
To receive, we need to add `picture` on this API call:

https://developers.facebook.com/docs/graph-api/reference/user/

Though the resulting image is very small.

**Comment by fredpook** [comment]
I looks like it is working after all
