### ISSUE TITLE
Have the option to get the original image file in {% image_url %}

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#1761]
**Problem**
There doesn't seem to be a way to get the actual uploaded file when using {% image_url %}. This will return an image that has been processed.

**Current solution**
This could be solved by using `/image/{{ m.rsc.some_image.depiction.filename }}`.

**Proposed solution**
It might be nice to be able to get the url with an **original** attribute `{% image_url m.rsc.some_image.depiction.id original %}`.

**Comment by rl-king** [comment]
This will return the same processed image file as {% image_url %} does.

**Comment by mworrell** [comment]
The `media_...` dispatch rules serve the file as-is from disk.

Why do you think that they are processed?

**Comment by rl-king** [comment]
No you're right, I was looking at the wrong location.

**Comment by mworrell** [comment]
Good, thanks for checking!
