### ISSUE TITLE
Trouble ticket with zotonic

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1764]
Hi team,
More a question than an issue.
Are you aware of any trouble ticket system  done with zotonic ?
I'm looking for one, but find php or java ones only, open source obviously. 
As zotonic have features with inbound email,  could be possible that someone did it already. 
Thanks for your ideas on this

**Comment by karlsson** [comment]
I think someone started on a tracker many years ago but it seems to be halted: https://github.com/kaos/trackz
Maybe you will get better response if you try the [zotonic-users](https://groups.google.com/forum/#!forum/zotonic-users) forum.

**Comment by crownedgrouse** [comment]
thanks, I will give a try on forum. closing.
