### ISSUE TITLE
More gracefully handle postgresql unavailability

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#1776]
If postgres is unavailable for a moment, zotonic will stop random sites (depending on which have activity during that time problably) and never restart them. 

Database connections should be retried indefinitely instead of simply crashing permanently; the unavailability could just be temporary for an update or something.

**Comment by mworrell** [comment]
That the site stops after repeated connect attempts is the expected behavior.

After it has been stopped we do try to restart the site automatically, with an increasing back off.

I am wondering if you can see anything in the logs that is preventing the restarts?

**Comment by CyBeRoni** [comment]
> That the site stops after repeated connect attempts is the expected behavior.

I disagree with this fully. Something *external* to Zotonic should not *ever* cause a Zotonic site to be stopped. Once the external thing start working again, I expect the site to be available again almost immediately. 

Zotonic should not assume availability of external services for its functioning. Of course, if a page is dependent on that service being available, an error should be returned. Also, if there is some sort of internal error in Zotonic that cannot be solved that is another matter. 

Stopping the site also prevents requests that do not need database access from working which is another thing that I would consider ongewenst.

Another problem with stopping the site is that if a site is stopped, the default Zotonic status page is rendered (asking to log in) rather than an error page from the site in question.

> After it has been stopped we do try to restart the site automatically, with an increasing back off.

The incident that prompted me to create this issue was a security update of postgresql at about 6:30 which required most of our sites to be manually restarted, which someone did at about 8:30. This has happened before, but that time I happened to be awake the exact moment it happened myself.

I don't know what the back-off algorithm is but if a postgres outage measured in minutes causes hours worth of downtime, it needs to back off more slowly.

**Comment by mworrell** [comment]
Could you check your logfiles?

This has been tested by turning on/off psql, then it worked as expected.

Though on one server I have seen (once) an error where psql returned a kind of authentication error whilst being updated. I am interested if you see something similar in your logs.  If so then we can add logic to handle that kind of errors into the quick-retry-because temp problem logic.

Regarding the *show a nice page when down*.  What we could do is:

 1. For every site, also start a temp site as fallback (with no db connection, so no crashes).
 2. This temp site returns 503 on all calls.
 3. The temp site will use templates/css from the real site (and some local fallback tpls/css in other cases).

**Comment by CyBeRoni** [comment]
> I am interested if you see something similar in your logs.

All I see is connection refused to postgres like so:

`Aug 11 06:33:00 host zotonic[11029]: 06:33:00.205 [error] dispatch_host for sitename returned {'EXIT',{{{badmatch,{error,econnrefused}},[{pgsql_sock,command,2,[{file,"src/pgsql_sock.erl"},{line,163}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629`

> For every site, also start a temp site as fallback

Honestly that sounds like a hodge-podge solution for a problem that can be solved by simply not stopping the site. I don't see why that would be a problem? And if something prevents that, perhaps *that* should be fixed instead. 

> This temp site returns 503 on all calls.

This would prevent requests that don't rely on the external component from being correctly served.


I reiterate that to create a highly available product, failures of external components need to be assumed to occur and handled properly. Crashing permanently is not proper handling of a failure. Crashing and restarting automatically (and quickly) is acceptable but ideally the condition simply throws (and logs) an error for requests that are affected while still processing requests that don't need the external component.

**Comment by ddeboer** [comment]
The core problem here is that to create a highly available system, one has to compartmentalise system failures by writing code that handles them. This is defensive programming. Erlang programmers are told not do this, but to ‘let it crash’ instead. 

Of course, a single PostgreSQL server is a single point of failure, which makes the system unreliable to begin with. Still, just bailing out on a database failure by stopping the site (the current behaviour) doesn’t seem right, even if the site gets (incrementally) restarted after that.

@mworrell Are there any compelling reasons to stop the site? How much work would be involved in making the crash more local, i.e. keep the site running but only show error pages for requests that really need the database connection?
