### ISSUE TITLE
zotonic-heavy hangs on creation of container

### ISSUE THREAD

**Issue by kunthar** [zotonic/zotonic#1777]
- root@dc02 /var/container_data/zotonic # docker run -v \`pwd\`:/opt/zotonic/user/sites -p 8443:8443 zotonic/zotonic-heavy
Unable to find image 'zotonic/zotonic-heavy:latest' locally
latest: Pulling from zotonic/zotonic-heavy
783a6ba2188d: Pull complete
Digest: sha256:d57ebf6d55ea95298b345854abe011359341c9385525b94e8b196f1261547ae9
Status: Downloaded newer image for zotonic/zotonic-heavy:latest
`/opt/zotonic/docker/docker-entrypoint.sh: exec: line 24: start-nodaemon: not found`

container hangs in this point.  `docker kill`  `docker stop` `docker pause` can't help.
killing the process with kill -9 can't help.
docker becomes unstable, restart of service needed. 
docker logs is dead.

Docker version 1.9.1, build a34a1d5
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

**Comment by CyBeRoni** [comment]
That is because someone moved the relevant scripts around and then didn't bother to check if anything depended on their location.

Unfortunately the entrypoint script has those locations hard-coded and does some other things so it's not easily worked around.

I've created a PR with a patch for this problem, along with a method to workaround this problem should it occur again the future.

**Comment by kunthar** [comment]
all the running docker containers screwed. the only solution for now is reboot :(

**Comment by CyBeRoni** [comment]
If you're in a hurry, you can build the docker images yourself by using the branch with my fixes:

```
git clone git@github.com:CyBeRoni/zotonic.git -b fix-docker
cd zotonic
docker build -t zotonic/zotonic:latest .
docker build -t zotonic/zotonic-heavy:latest -f Dockerfile.heavy .
```

I will also talk to the Zotonic guys about making Docker tags so you don't have to rely on 'latest' not being broken.

**Comment by ddeboer** [comment]
I’m looking into a zotonic-heavy tagged image built from a tagged zotonic/zotonic image. However, does maintaining zotonic-heavy really make sense? An alternative would be to ditch zotonic-heavy and explain how to start zotonic and a postgres container separately (optionally using Docker Compose).
