### ISSUE TITLE
Include a template as anonymous user

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1780]
It can be useful to do ACL checks anonymously, e.g. to make sure any user can access some template. `{% include %}` already has a [sudo](http://docs.zotonic.com/en/latest/ref/tags/tag_include.html) argument. What about adding an `anon` or `anonymous` argument too? Any `m.acl.is_allowed…` checks in the included template are then executed against the anonymous user. The extra argument can call `z_acl:anondo/1`.

**Comment by mworrell** [comment]
In the master this is supported but (apparently) not yet documented.

From the `z_template_compiler_runtime.erl`:

```erlang
-spec set_context_vars(map()|list(), term()) -> term().
set_context_vars(Args, Context) when is_map(Args); is_list(Args) ->
    Lang = z_context:language(Context),
    Context1 = case get(z_language, Args, Lang) of
            undefined -> Context;
            Lang -> Context;
            NewLang -> z_context:set_language(NewLang, Context)
    end,
    Context2 = case z_convert:to_bool(get(sudo, Args, false)) of
            false -> Context1;
            true -> z_acl:sudo(Context1)
    end,
    Context3 = case z_convert:to_bool(get(anondo, Args, false)) of
            false -> Context2;
            true -> z_acl:anondo(Context2)
    end,
    Context3.
```
