### ISSUE TITLE
I can not get into admin panel

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1790]
`zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-08-21 02:22:42.028 [error] <0.2281.0>@z_transport:incoming_msgs:234 Error '{badmatch,{<<"username">>,<<"CFp45qtr7wJGlyA_ZTrG0mpT7WuDaANtAAAACHVzZXJuYW1lbQAAAAh1c2VybmFtZWwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>}}' for transport message {z_msg_v1,1,false,<<"-z-2">>,1503282161974,ubf,postback,undefined,undefined,<<"cuCPGIVPvf3h6M7hTkFt">>,{postback_event,<<"VPmJIdZPZ32Hz7MnTy3eqgmkq6qDaAVtAAAABnN1Ym1pdGQACXVuZGVmaW5lZGQACXVuZGVmaW5lZG0AAAAAZAAQY29udHJvbGxlcl9sb2dvbg">>,<<"logon_form">>,undefined,<<>>,{q,[{<<"z_v">>,<<"username:CFp45qtr7wJGlyA_ZTrG0mpT7WuDaANtAAAACHVzZXJuYW1lbQAAAAh1c2VybmFtZWwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>},{<<"z_v">>,<<"password:mixmJWXBmfrMqAZEM6rfFTAdDImDaANtAAAACHBhc3N3b3JkbQAAAAhwYXNzd29yZGwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>},{<<"page">>,<<"/admin/modules">>},{<<"handler">>,<<"username">>},{<<"username">>,<<"admin">>},{<<"password">>,<<"123123">>},{<<"rememberme">>,<<>>}]}}}
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/error.log <==
zotonic      | 2017-08-21 02:22:42.028 [error] <0.2281.0>@z_transport:incoming_msgs:234 Error '{badmatch,{<<"username">>,<<"CFp45qtr7wJGlyA_ZTrG0mpT7WuDaANtAAAACHVzZXJuYW1lbQAAAAh1c2VybmFtZWwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>}}' for transport message {z_msg_v1,1,false,<<"-z-2">>,1503282161974,ubf,postback,undefined,undefined,<<"cuCPGIVPvf3h6M7hTkFt">>,{postback_event,<<"VPmJIdZPZ32Hz7MnTy3eqgmkq6qDaAVtAAAABnN1Ym1pdGQACXVuZGVmaW5lZGQACXVuZGVmaW5lZG0AAAAAZAAQY29udHJvbGxlcl9sb2dvbg">>,<<"logon_form">>,undefined,<<>>,{q,[{<<"z_v">>,<<"username:CFp45qtr7wJGlyA_ZTrG0mpT7WuDaANtAAAACHVzZXJuYW1lbQAAAAh1c2VybmFtZWwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>},{<<"z_v">>,<<"password:mixmJWXBmfrMqAZEM6rfFTAdDImDaANtAAAACHBhc3N3b3JkbQAAAAhwYXNzd29yZGwAAAABaANkAAhwcmVzZW5jZWQAF3ZhbGlkYXRvcl9iYXNlX3ByZXNlbmNlamo">>},{<<"page">>,<<"/admin/modules">>},{<<"handler">>,<<"username">>},{<<"username">>,<<"admin">>},{<<"password">>,<<"123123">>},{<<"rememberme">>,<<>>}]}}}
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-08-21 02:22:42.028 [error] <0.2281.0>@z_transport:incoming_msgs:235 Stack: [{z_validation,validate,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,133}]},{z_validation,'-validate_query_args/1-fun-0-',2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,85}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_validation,validate_query_args,1,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,83}]},{z_transport,incoming_with_session,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,288}]},{z_transport,incoming_msgs,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,225}]},{z_transport,incoming,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,194}]},{controller_postback,process_post_ubf,1,[{file,"/srv/zotonic/_build/default/lib/zotonic_mod_base/src/controllers/controller_postback.erl"},{line,78}]}]
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/error.log <==
zotonic      | 2017-08-21 02:22:42.028 [error] <0.2281.0>@z_transport:incoming_msgs:235 Stack: [{z_validation,validate,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,133}]},{z_validation,'-validate_query_args/1-fun-0-',2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,85}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_validation,validate_query_args,1,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_validation.erl"},{line,83}]},{z_transport,incoming_with_session,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,288}]},{z_transport,incoming_msgs,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,225}]},{z_transport,incoming,2,[{file,"/srv/zotonic/_build/default/lib/zotonic_core/src/support/z_transport.erl"},{line,194}]},{controller_postback,process_post_ubf,1,[{file,"/srv/zotonic/_build/default/lib/zotonic_mod_base/src/controllers/controller_postback.erl"},{line,78}]}]`

**Comment by mworrell** [comment]
@heiheshang thanks for the report, a fix should be in now.
