### ISSUE TITLE
Livereload for templates, CSS and JS

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1793]
I propose an out-of-the-box solution for reloading the page when templates, CSS and/or JS files have changed. 

### Solution

We can either run some minimal JS in the browser when files change (`location.reload(true);`) or rely on a more fully-fledged [LiveReload](https://github.com/livereload/livereload-js#what-is-livereloadjs) solution. LiveReload has a [simple WebSocket protocol](http://livereload.com/api/protocol/).

Zotonic [already watches](https://github.com/zotonic/zotonic/blob/f4fef7f95233f00fdb39a913742a947c3b076430/apps/zotonic_launcher/src/filewatcher/z_filewatcher_handler.erl) templates, CSS and JS files, so this should not be hard to add. Add this functionality to mod_development, so it can easily be enabled/disabled depending on the environment (development vs. production).

### Separation of concerns

- Have Zotonic only watch _compiled_ assets.
- Other tools (such as Webpack or Gulp) take care of compiling SCSS and JS to CSS and (minified) JS. This way, developers keep full control over their frontend stack.

### Alternatives

- Document how IDEs can be configured to enable Livereload. 

### To do

- [ ] update [docs](http://docs.zotonic.com/en/latest/ref/modules/mod_development.html)

**Comment by ddeboer** [comment]
As discussed in #1808:

> We decided not to adopt Livereload but create a simpler solution instead (on master) that works well with Zotonic’s concatenated files.

**Comment by mworrell** [comment]
Currently the file watcher is part of `zotonic_launcher`.  This module also handles the recompilation of changed files.

It seems more logical to me to move the recompilation to `zotonic_mod_development`, at least if it concerns handling of *lib* files.  The recompilation of Erlang files could stay in the `zotonic_launcher`.

**Comment by mworrell** [comment]
Moving the file watcher to its own app.

I saw in the inotify code a `killall inotifywait`. I suspect this is because on a close of the beam.smp the started process does not terminate.

I propose to remove this and start using https://github.com/saleyn/erlexec instead.
It is also on hex.pm: https://hex.pm/packages/erlexec

**Comment by mworrell** [comment]
The refactoring of the filewatcher takes place here https://github.com/zotonic/zotonic/issues/1812

**Comment by mworrell** [comment]
I have added a simple live reload to th mod_development (0.x only for now).
See merge request #1924 

/cc @rl-king

**Comment by mworrell** [comment]
Added the live reload code to master as well in 05393ab8b135930c6a0e9fd51da0acc97ba877d8

**Comment by mworrell** [comment]
Livereload has now been added to master and 0.x

The current solution can be optimized, at the moment:

 * The page is reloaded if any .tpl file is changed. This could be restricted to .tpl files in use by the current page.
 * Concatenated lib files are not unpacked, so the *use separate lib files* option is automatically checked when live reload is enabled.
 * Minified lib files are not recognized, it is assumed the non-minified lib urls are used

However, the basic reloading works and those points can be addressed in a new issue.

Closing this issue.
