### ISSUE TITLE
translation does not work

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1797]
![translate](https://user-images.githubusercontent.com/111087/29806753-ea373bca-8ccb-11e7-94eb-29689335a124.png)

**Comment by ddeboer** [comment]
What exactly doesn’t work?

**Comment by heiheshang** [comment]
The picture is clearly visible, the language is exposed, but only English is shown

**Comment by mworrell** [comment]
Just checked on the current master.

If I set the default language to *Russian* and then fetch a page with `curl` (to prevent any browser cookies with my language) then I do get a Russian page.

Though if I open the site in my browser, I get the English version. I guess the content negotiation selected `en` as `ru` is not in the list of languages my browser accepts.

As new visitors should have gotten `ru` this is indeed an error.

**Comment by mworrell** [comment]
Ah, also found a problem where the translations in `zotonic_core` were not loaded.
This will be merged as part of #1825
