### ISSUE TITLE
Google analytics cookie and ip address anonymization

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#1800]
Zotonic currently defaults to saving the full ip address and setting a cookie in the visitors browser handled by Google analytics. There is an option to anonimyze the ip address and prevent setting of a cookie by using the following the following code. 

`ga('send', 'pageview', {'anonymizeIp': true});` or `ga('set', 'anonymizeIp', true);`
`ga('create', 'UA-000000',  {'storage': 'none'});`

Information on how the ip address is anonymized can be found: https://support.google.com/analytics/answer/2763052?hl=en , https://developers.google.com/analytics/devguides/collection/analyticsjs/ip-anonymization

Information on disabling cookies can be found here: https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#disabling_cookies

I would consider to default to as little tracking as possible without losing useful features Google analytics provides.

**Comment by ddeboer** [comment]
> how the ip address is anonymized can be found

**Comment by ddeboer** [comment]
To comply with GDPR, we probably only need `{'anonymizeIp': true}`, so let’s begin with that.

**Comment by mworrell** [comment]
Fixed with #1905 and #1906
