### ISSUE TITLE
Editing username also changes password

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1801]
When editing a user in the admin (through Users > Account > Edit username/password) the password is always reset with a fixed value – which I won’t post here – always filled in by default.

**Comment by mworrell** [comment]
This is the autocomplete of the browser. The behavior depends on the browser.

**Comment by ddeboer** [comment]
Ah, well we could at least `autocomplete="false"`. The current behaviour is quite confusing for admins.

**Comment by ddeboer** [comment]
It’s not autocomplete; this seems to be the culprit: https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_admin_identity/priv/templates/_action_dialog_set_username_password.tpl#L32

**Comment by mworrell** [comment]
Password_regex? That is new to me :)

Note that there is a separate include to prevent autocomplete of pw and/or username. This used to work well and was added especially for Safari.
