### ISSUE TITLE
Reset password form should not disclose whether account exists

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1802]
https://github.com/driebit/ginger/issues/331

This protects against the [user enumeration](https://www.owasp.org/index.php/Testing_for_Account_Enumeration_and_Guessable_User_Account_(OTG-IDENT-004)) vulnerability.

**Comment by mworrell** [comment]
This is an UX problem. You can't say you sent something iff the user was known as email gets often lost or caught in the spam folder (especially tends to happen with people that don't sign in often, so don't know their password).

**Comment by ddeboer** [comment]
We could rephrase the message:

> We sent an e-mail (to bli@bla.com). If you don’t receive it within a few minutes, please check your spam folders.

**Comment by ArthurClemens** [comment]
You have to support users that either:
1. Forgot their account name
1. When using email as account name: have multiple email accounts and cannot remember which one they've used
1. When using email as account name: mistyped their email (happens a lot)

Mailchimp is an example with a quite nice flow with informative but not revealing messages.

**Comment by ddeboer** [comment]
1. Account names are easily forgotten (especially as they may have been amended to make them unique). So users prefer to use their e-mail address for resetting their password, making this a non-issue.
2. In this case, I do prefer users  to go through the support desk, which adds a layer of indirection and security.
3. We can at least make sure a syntactically valid e-mail address is submitted, preventing _some_ typos.

Which part of Mailchimp, exactly? Showing the partial e-mail address `t***@h*********.com` doesn’t make much sense, as users remember their e-mail address much more easily then some username (that may have been amended to make it unique).

**Comment by mworrell** [comment]
@ArthurClemens have you some screenshots or example from MailChimp?  I personally don't like the message "We might have sent you some email, or might not, it might also be lost somewhere in a spam folder, or not, just look around and be lucky, or not."

Do we have other examples?

Maybe @michielklonhammer has some ideas as well?

**Comment by mmzeeman** [comment]
We use email addresses as our account names. 

In practice the password reset is not used very often because most users are afraid of them. They usually call their user support to help them. They can add new users to their accounts themselves and reset passwords.

**Comment by michielklonhammer** [comment]
Our users use the password reset all the time so it's super important.
I had a look at both our own procedure and mailchimp.

We (old Zotonic) only say that a mail has been sent or that we don't 
know you.

Mailchimp gives more information. they say:
"Success! We've sent an email to s******@m**********.com with password 
reset instructions."
or if they don't know you "A user with this username does not exist"










So, if you want to make our procedure safer, you could say:  "If this 
account exists, we will send an e-mail with instructions".
but I expect it will lead to more support calls as it takes much longer 
to try out a few email addresses or account names.

Michiel





------ Original Message ------

**Comment by mworrell** [comment]
An option is to:

 * Only allow email address input for the reset
 * Always send an email, in the email tell if the user is known or not

An example is shown at:

https://www.troyhunt.com/everything-you-ever-wanted-to-know/

**Comment by ddeboer** [comment]
I think that’s the best trade-off between security (no user enumeration) and user experience (clear instructions). Does everyone agree?

**Comment by michielklonhammer** [comment]
yes I think the "
Only allow email address input for the resetAlways send an email, in the 
email tell if the user is known or not
option is best (excellent article by the way!). It reminded me that we 
would love 2-factor athentication, perhaps starting with a code in mail 
(with a link to speed things up). This should be optional (we need it 
for admin accounts in LearningStone).





------ Original Message ------

**Comment by mworrell** [comment]
Then it looks like we all agree.

BTW for the 2FA we could use the standard apps that generate a time limited code. These apps are free, so with a low(er) threshold for users.  (Also don't need SMS codes, so no additional subscriptions and charges)

**Comment by mworrell** [comment]
@michielklonhammer the *code in email* could also be *log on via email*?  That is an use case that @mmzeeman has been looking into.
