### ISSUE TITLE
Limit access to status site by IP

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1803]
We should limit access to the status site. The easiest way is through an IP whitelist. We already have a `ip_whitelist` config param that protects logins to `/admin` with the default admin password. I propose we add a separate `status_ip_whitelist`, which defaults to `ip_whitelist`.

**Comment by ddeboer** [comment]
Additionally, we could add an option that further restricts access to `/admin` to the same whitelist. Currently, `ip_whitelist` is only about allowing the default admin password.

**Comment by mworrell** [comment]
For me it is quite convenient to be able to go to the status site whilst on the road.

You could think of adding a whitelist, though that might run into complexities soon.

Maybe it is good to start thinking of what you generally want to do, and what kind of user roles you have. Then use that classification to limit access to certain services.

**Comment by mworrell** [comment]
The Zotonic status site has now a IP whitelist on master and 0.x
