### ISSUE TITLE
Anonymize Google Analytics userId property

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#1804]
In #1249 we added the Google Analytics `userId` property. [According to Google](https://developers.google.com/analytics/devguides/collection/analyticsjs/cookies-user-id#user_id):

> The USER_ID value should be a unique, persistent, and non-personally identifiable string identifier that represents a user or signed-in account across devices.

However, as we use the person’s resource id, that can be related back to a user (by looking up the id in the admin, for instance). Should we hash the id to make it at least a bit harder to find the user behind it?

**Comment by mworrell** [comment]
Or should we remove it all together?  For what is it used?

**Comment by ddeboer** [comment]
Mainly to [get a more accurate user count](https://support.google.com/analytics/answer/3123663) by tracking them across devices.

**Comment by ddeboer** [comment]
To comply with GDPR, let’s
- remove `userId` altogether
- document how users can override the GA template to supply the `userId` if they want to do so (and advising them to tell their users in the application’s privacy policy).
