### ISSUE TITLE
Failed to get page url path. Is the 'page' dispatch rule missing?

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#1809]
Is there a way to get rid of this warning? It clutters my log files. I have a site where not all resources have a public page; it is a bit of a strong assumption, I think.

**Comment by mworrell** [comment]
This warning is generated if the URL for the page is requested.
So there is a place where the page URL is shown, is this coming from the admin?

My personal opinion is that every resource should have a HTML presentation.  Even if that presentation is a dummy page that says "nothing to see here, please continue" (with a noindex for bots).

**Comment by mworrell** [comment]
Closing for now.
