### ISSUE TITLE
Move source (less/sass/etc) files out of public lib directory

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1812]
Currently the `.less`, `.sass` and build-tool configs for generated css/js files are placed in the *lib* directory.

These source files should not be loadable by the client, so should be moved to another directory.

I propose to add a `lib-src` directory on the same level as the `lib` directory.

```
priv/
       lib/
       lib-src/
...
```

The *changed file handler* could then watch changes in these directories to know that a build tool must be called.

**Comment by mworrell** [comment]
Please add your remarks @ArthurClemens @rl-king @ddeboer

**Comment by ddeboer** [comment]
I agree. Alternatively, we can
* consider `lib/` the private directory
* add a `public/` or `web/` directory that makes very explicit that its contents will be visible to the outside world.

**Comment by mworrell** [comment]
I like the `web` name, as it is easy enough to remember and the link to the served content is clear. 

Making the `lib` private is a change that needs some getting used to for current Zotonic users, though it is clear enough when you see that nothing is loaded anymore :)

I am not sure that the connection `lib` -> `web` is clear enough though. I think the directory name for sources used for the `web` directory should have a clear link to target directory.

**Comment by mmzeeman** [comment]
We do something similar with js sources. We take some js sources from a private directory at module level and minify them and move them to the lib directory.

Currently the `lib` directory has been the public directory.. Having a `lib-src` which contains static files which must be processed before going to `lib` sounds logical to me.

**Comment by mworrell** [comment]
This has now been addressed in #1828 

That merge request now checks for the presence of a `Makefile`.  If found then that Makefile is executed, and it should build the appropriate files in the `lib` directory.
