### ISSUE TITLE
branch 0.32.0 not compiled

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1813]
`Compiling /srv/zotonic/deps/erlware_commons/src/ec_semver_parser.erl failed:
ERROR: compile failed while processing /srv/zotonic/deps/erlware_commons: rebar_abort
GNUmakefile:56: recipe for target 'compile' failed
make: *** [compile] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2`

**Comment by ddeboer** [comment]
Duplicate of your issue #1719. Our 0.x is currently not compatible with Erlang/OTP 20, which I guess you’re running on?

**Comment by heiheshang** [comment]
yes, erlang 20 in debian jessie
