### ISSUE TITLE
the page signup is not displayed

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1816]
`zotonic      | 2017-09-30 09:42:19.847 [warning] <0.1571.0> webmachine_mochiweb:221 caught error {stop_request,500,{function_clause,[{filter_stringify,stringify_1,[{undef,[{controller_signup,ping,[{wm_reqdata,#Port<0.33210>,{dict,4,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[[ua_class|desktop],[ua_props,{is_user_select,true},{has_pointer,true},{is_desktop,true},{is_crawler,false},{is_wireless_device,false},{is_tablet,false},{ajax_support_javascript,true},{device_os,<<"-">>},{displayWidth,1366},{displayHeight,768},{inputDevices,<<"-">>},{parentId,<<"generic-">>},{model,<<"browser">>},{vendor,<<"desktop">>},{id,<<"desktopDevice">>}]],[[zotonic_host|skl]],[[controller_module|controller_signup]],[],[],[],[],[],[],[],[],[],[]}}},undefined,"172.17.0.4",undefined,{wm_log_data,873733064,undefined,{1506,764539,473391},'GET',{8,{"connection",{'Connection',"upgrade"},{"accept",{'Accept',"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"},nil,{"accept-encoding",{'Accept-Encoding',"gzip, deflate, sdch, br"},nil,{"accept-language",{'Accept-Language',"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"},nil,nil}}},{"host",{'Host',"skl.anriya.ru"},{"cookie",{'Cookie',"z_ua=c%3Ddesktop%26u%3D1%26t%3D1%26w%3D1366%26h%3D768; z_logon=; z_sid=KtAMioTpKzLpGR9B11URl4hsFSsg4zcQ"},nil,nil},{"upgrade-insecure-requests",{"Upgrade-Insecure-Requests","1"},nil,{"user-agent",{'User-Agent',"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.635"},nil,nil}}}}},"172.17.0.4","/signup",{1,1},404,0,undefined,undefined,undefined},'GET',http,{1,1},"/signup","/signup","/signup",{dict,3,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[[zotonic_host|skl]],[],[],[],[[zotonic_dispatch|signup],[zotonic_dispatch_path,"signup"]],[],[],[],[],[],[],[]}}},["signup"],".",500,1073741824,[{"z_ua","c%3Ddesktop%26u%3D1%26t%3D1%26w%3D1366%26h%3D768"},{"z_logon",[]},{"z_sid","KtAMioTpKzLpGR9B11URl4hsFSsg4zcQ"}],[],[{"accept","text/html,application/xhtml+xml,application/xml;q=0...."},...],...},...],...},...]},...],...},...]}} (stacktrace [{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,37}]},{webmachine_mochiweb,render_error,4,[{file,"src/webmachine_mochiweb.erl"},{line,211}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,104}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}])`

**Comment by mworrell** [comment]
Currently working on both 0.x and master. Closing issue.
