### ISSUE TITLE
site falls

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1817]
`zotonic      | 2017-10-01 07:04:01.561 [error] <0.331.0> {mochiweb_socket_server,307,{request_error,{timeout,{gen_server,call,['z_template$skl',{compile,"home.tpl","/home/zotonic/user/sites/skl/templates/home.tpl",template_skl__desktop_home_zotonic_user_sites_skl_templates_home_tpl,{context,skl,{wm_reqdata,#Port<0.40467>,{dict,4,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[[ua_class|desktop],[ua_props,{is_user_select,true},{has_pointer,true},{is_desktop,true},{is_crawler,false},{is_wireless_device,false},{is_tablet,false},{ajax_support_javascript,true},{device_os,<<"-">>},{displayWidth,1366},{displayHeight,768},{inputDevices,<<"-">>},{parentId,<<"generic-">>},{model,<<"browser">>},{vendor,<<"desktop">>},{id,<<"desktopDevice">>}]],[[zotonic_host|skl]],[[controller_module|controller_template]],[],[],[],[],[],[],[],[],[],[]}}},undefined,"172.17.0.4",undefined,{wm_log_data,818233305,undefined,{1506,841405,883983},'GET',{10,{"connection",{'Connection',"upgrade"},{"cache-control",{'Cache-Control',"max-age=0"},{"accept",{'Accept',"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"},nil,{"accept-encoding",{'Accept-Encoding',"gzip, deflate, sdch, br"},nil,{"accept-language",{'Accept-Language',"ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"},nil,nil}}},nil},{"host",{'Host',"skl.anriya.ru"},{"cookie",{'Cookie',"z_ua=c%3Ddesktop%26u%3D1%26t%3D1%26w%3D1366%26h%3D768; z_logon=; z_sid=xW51p92DqA0VAhD8toSR5HF8eIL4QQgo"},nil,nil},{"upgrade-insecure-requests",{"Upgrade-Insecure-Requests","1"},{"referer",{'Referer',"https://skl.anriya.ru/"},nil,nil},{"user-agent",{'User-Agent',"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.635"},nil,nil}}}}},"172.17.0.4","/",{1,1},404,0,undefined,undefined,undefined},'GET',http,{1,1},"/","/","/",{dict,3,16,16,8,80,48,{[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]},{{[],[],[],[],[[zotonic_host|skl]],[],[],[],[[zotonic_dispatch|home],[zotonic_dispatch_path]],[],[],[],[],[],[],[]}}},[],".",500,1073741824,[{"z_ua","c%3Ddesktop%26u%3D1%26t%3D1%26w%3D1366%26h%3D768"},{"z_logon",[]},{"z_sid","xW51p92DqA0VAhD8toSR5HF8eIL4QQgo"}],[],[{"accept","text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"},{"accept-encoding","gzip, deflate, sdch, br"},{"accept-language","ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4"},{"cache-control","max-age=0"},{"connection","upgrade"},{"cookie","z_ua=c%3Ddesktop%26u%3D1%26t%3D1%26w%3D1366%26h%3D768; z_logon=; z_sid=xW51p92DqA0VAhD8toSR5HF8eIL4QQgo"},{"host","skl.anriya.ru"},{"referer","https://skl.anriya.ru/"},{"upgrade-insecure-requests","1"},{"user-agent","Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36 OPR/45.0.2552.635"}],not_fetched_yet,false,{5,{"set-cookie",{"Set-Cookie","z_sid=kE8UAyzMCx8r2NUmNHRAxWYm7ReXCItj; Version=1; Path=/; HttpOnly"},{"cache-control",{"Cache-Control","no-store, no-cache, must-revalidate, post-check=0, pre-check=0"},nil,{"expires",{"Expires","Wed, 10 Dec 2008 15:30:00 GMT"},{"content-type",{"Content-Type","text/html; charset=utf-8"},nil,nil},{"p3p",{"P3P","CP=\"NOI ADM DEV PSAi COM NAV OUR OTRo STP IND DEM\""},nil,nil}}},nil}},"identity",undefined,"text/html","utf-8",<<>>,true,[],none,[{last_modified,undefined},{generate_etag,undefined},{content_encodings_provided,["identity"]},{charsets_provided,[{"utf-8",#Fun<controller_template.0.81623595>}]},{content_types_provided,[{"text/html",provide_content}]}]},undefined,<0.2992.15>,undefined,<0.2993.15>,undefined,undefined,'z_depcache$skl','z_notifier$skl','z_session_manager$skl','z_dispatcher$skl','z_template$skl','z_scomp$skl','z_dropbox$skl','z_pivot_rsc$skl','z_module_indexer$skl',190976099,undefined,{'z_db_pool$skl',z_db_pgsql},[ru],<<"Asia/Yakutsk">>,undefined,undefined,[],[],[],[],[],[],[],[{set_session_id,true},{q,[{"zotonic_host","skl"},{"zotonic_dispatch_path",[]},{"zotonic_dispatch","home"}]},{template,"home.tpl"},{zotonic_dispatch,home}]}},30000]}}}}
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/console.log <==
zotonic      | 2017-10-01 07:04:01.674 [info] <0.13943.14>@z_transport:maybe_logon:343 PageId without page session (session_id <<"xW51p92DqA0VAhD8toSR5HF8eIL4QQgo">>)
zotonic      | 2017-10-01 07:12:09.744 [error] <0.2991.15> Error in memo exit:{timeout,{gen_server,call,[<0.2686.15>,{equery,"select category_id,content_group_id,created,creator_id,id,is_authoritative,is_dependent,is_featured,is_protected,is_published,modified,modifier_id,name,page_path,pivot_geocode,pivot_geocode_qhash,pivot_location_lat,pivot_location_lng,props,publication_end,publication_start,slug,uri,version,visible_for from rsc where id = $1",[326]},30000]}} in [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{z_db,assoc1,5,[{file,"src/db/z_db.erl"},{line,856}]},{z_db,'-assoc_props/4-fun-0-',5,[{file,"src/db/z_db.erl"},{line,273}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,210}]},{z_db,assoc_props_row,3,[{file,"src/db/z_db.erl"},{line,231}]},{m_rsc,get_raw,3,[{file,"src/models/m_rsc.erl"},{line,269}]},{m_rsc,'-get/2-fun-0-',2,[{file,"src/models/m_rsc.erl"},{line,223}]}]
zotonic      | 
zotonic      | ==> /srv/zotonic/priv/log/crash.log <==
zotonic      | 2017-10-01 07:12:09 =ERROR REPORT====
zotonic      | Error in memo exit:{timeout,{gen_server,call,[<0.2686.15>,{equery,"select category_id,content_group_id,created,creator_id,id,is_authoritative,is_dependent,is_featured,is_protected,is_published,modified,modifier_id,name,page_path,pivot_geocode,pivot_geocode_qhash,pivot_location_lat,pivot_location_lng,props,publication_end,publication_start,slug,uri,version,visible_for from rsc where id = $1",[326]},30000]}} in [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{z_db,assoc1,5,[{file,"src/db/z_db.erl"},{line,856}]},{z_db,'-assoc_props/4-fun-0-',5,[{file,"src/db/z_db.erl"},{line,273}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,210}]},{z_db,assoc_props_row,3,[{file,"src/db/z_db.erl"},{line,231}]},{m_rsc,get_raw,3,[{file,"src/models/m_rsc.erl"},{line,269}]},{m_rsc,'-get/2-fun-0-',2,[{file,"src/models/m_rsc.erl"},{line,223}]}]
zotonic      | ==> /srv/zotonic/priv/log/error.log <==
zotonic      | 2017-10-01 07:12:09.744 [error] <0.2991.15> Error in memo exit:{timeout,{gen_server,call,[<0.2686.15>,{equery,"select category_id,content_group_id,created,creator_id,id,is_authoritative,is_dependent,is_featured,is_protected,is_published,modified,modifier_id,name,page_path,pivot_geocode,pivot_geocode_qhash,pivot_location_lat,pivot_location_lng,props,publication_end,publication_start,slug,uri,version,visible_for from rsc where id = $1",[326]},30000]}} in [{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{z_db,assoc1,5,[{file,"src/db/z_db.erl"},{line,856}]},{z_db,'-assoc_props/4-fun-0-',5,[{file,"src/db/z_db.erl"},{line,273}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,210}]},{z_db,assoc_props_row,3,[{file,"src/db/z_db.erl"},{line,231}]},{m_rsc,get_raw,3,[{file,"src/models/m_rsc.erl"},{line,269}]},{m_rsc,'-get/2-fun-0-',2,[{file,"src/models/m_rsc.erl"},{line,223}]}]
`

**Comment by mworrell** [comment]
Hi,

A compile timeout can happen, especially if the template is complex or the server is busy.

A new request, a bit later, will find the template compiled and well.

In the master we are using a different template compiler where this will happen much less often.

- Marc
