### ISSUE TITLE
sitemap.xml always empty

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1819]
`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
<url>
<loc>http://xn--80aiqern0aa.xn--p1ai/</loc>
<lastmod>2017-10-08T18:59:46+09:00</lastmod>
<changefreq>daily</changefreq>
<priority>1.0</priority>
</url>
</urlset>`

**Comment by mworrell** [comment]
This depends on the category of your pages.
And if they are publicly viewable.

It uses the following query:

```erlang
{latest cat="text" cat="event" cat="location" cat="collection" cat="person" pagelen=20000}
```

See https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_seo_sitemap/priv/templates/sitemap.xml.tpl
