### ISSUE TITLE
Minification of javascript and css

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1823]
Our clients are calling us constantly that we should minify our javascript and css files. They do this because they use the Google Pagespeed insights tool and look at the "tips" google gives them.

Personally I hate this tool, because it doesn't even measure the speed of the page, but all clients use it.

This is what it looks like when you run the pagespeed insight tool on zotonic.com

<img width="1163" alt="screen shot 2017-10-12 at 08 28 29" src="https://user-images.githubusercontent.com/1024972/31482160-60f35db6-af27-11e7-9d97-696c518cd0b2.png">

From the looks of it things look really bad.

When you use a tool which really measures the speed of your page things look very different.

<img width="1119" alt="screen shot 2017-10-12 at 08 31 54" src="https://user-images.githubusercontent.com/1024972/31482505-ea65ee3c-af28-11e7-8429-10093dd997e3.png">

Some clients think they get a fast site and a higher pagerank by fixing all the tips mentioned by the Google pagespeed insights tool. How are you dealing with this? Sometimes I think we should just minify the javascript and css in the lib tags to prevent them from calling us.

**Comment by mmzeeman** [comment]
Oh, the tool which really measures your pagespeed is: https://tools.pingdom.com

**Comment by mworrell** [comment]
Luckily I don't have customers that blindly follow tools. Maybe Driebit has some experience with this?  /cc @ddeboer @CyBeRoni

**Comment by CyBeRoni** [comment]
Some of our clients ask the same thing. We bill them for the time spent making these changes.

**Comment by crownedgrouse** [comment]
Could a zotonic plugin do this ? I could do this... But some would préfère bill it ;-)

**Comment by mmzeeman** [comment]
It could probably be added as extra functionality to the lib tag.

**Comment by crownedgrouse** [comment]
minifying is a huge collection of regexps to apply on css and js files. what is your though on lib tag ?

**Comment by mmzeeman** [comment]
It could support automatic minification via `z_file_entry`. It already supports async compression. It would also be possible to add minification here.

**Comment by mworrell** [comment]
Yes, we can give it to some notifier for preprocessing, then you can add a module that knows of minifying (or just checks if a minifier is installed).

**Comment by crownedgrouse** [comment]
You mean even non Erlang ? BTW I'm not aware of   any Erlang minifier. Please give your though about what tool to support, so that I can look at this.

**Comment by mworrell** [comment]
I also am not aware of any Erlang minifiers, there are some installable ones. @ArthurClemens do you have any recommendations?  Or maybe Driebit has a preferred tool?

I prefer an easy to install standalone tool, that doesn't require installation of complete Node or other tool chains. If it is standalone we could ship it with a minifying module.

**Comment by mworrell** [comment]
For Javascript I found https://github.com/douglascrockford/JSMin/blob/master/jsmin.c which seems easy enough to translate to Erlang. It might be good enough.

We could do something similar for CSS (as the comment tokens are almost the same)

**Comment by mmzeeman** [comment]
On the CLI I currently use yui-compressor, which is a separate linux package. I'm also a bit hesitant to have node as a dependency.

If jsmin is a c program it could also be transformed into a port or nif implementation.

**Comment by mmzeeman** [comment]
Oh, js-min is really really simple. I wonder if that is enough to silence google pagespeed insights.

**Comment by mworrell** [comment]
I guess (hope) they will see that it is kind-of-minified and then stop complaining.
Just stripping comments and trimming lines is very simple and could also be applied to CSS.

**Comment by mmzeeman** [comment]
That is easy enough to test.

**Comment by crownedgrouse** [comment]
high evoluated minifiers are doing much more, like replace variable name to short hash, stuff like that. doing simple may not solve the google issue. but this need a test as already mentioned.

**Comment by crownedgrouse** [comment]
for memory https://developers.google.com/speed/docs/insights/rules

**Comment by crownedgrouse** [comment]
https://github.com/mishoo/UglifyJS2  look nice , found in upper URL

**Comment by mmzeeman** [comment]
I've tried a simple python jsmin implementation. (`sudo apt-get install python-jsmin`) 

And tried it on zotonic.js and jquery.. This simple tool already reaches around 50% reduction.

It is probably not hard to implement that basic algorithm in erlang (Strip comments and whitespace). The nice thing is that it works without external dependencies, and you don't have to run an external program which parses and manipulates things.

FYI Drupal also uses the jsmin algorithm (it implements several so people can choose). http://cgit.drupalcode.org/advagg/tree/ So I guess it will work...

**Comment by mmzeeman** [comment]
We are now working on adding automatic minification for js. It is working via a new module in z_stdlib. I will need to add configuration to turn it on and off (default off), a heuristic to not touch js files which are already minified, and add documentation.

Branch: https://github.com/zotonic/zotonic/tree/wip-jsmin

**Comment by mworrell** [comment]
@mmzeeman I was under the impression this was done?  Was it also merged into the master branch?

**Comment by mworrell** [comment]
This has been added to both 0.x and master.

Closing the issue.
