### ISSUE TITLE
User edit page: Add connection to user group does not show any options

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#1833]
After clicking the Add link:

<img width="436" alt="add-user-group" src="https://user-images.githubusercontent.com/350303/31610036-d99213e6-b276-11e7-8bb3-a194cc8a4b5d.png">

I get this error in the terminal:
```
13:33:08.709 [error] template_compiler_runtime_internal:211 Error {error,{{<<"/Users/arthur/code/Erlang/zotonic-master/_build/default/lib/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_find.tpl">>,52,32},template_compiler_parser,["syntax error before: ",[[60,60,"\"endfor\"",62,62]]]}}
```

**Comment by mworrell** [comment]
We should also try to flatten the iolist with the error message.

**Comment by mworrell** [comment]
Made separate issue for the readability https://github.com/zotonic/template_compiler/issues/10

@ArthurClemens can you check if the error has been resolved now?
