### ISSUE TITLE
[z_url_metadata.erl] get the site name

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#1835]
The site name is an essential property of the scraped meta data.
It is usually in og:site_name or twitter:site
Can it be added? Or is there a workaround?

**Comment by mworrell** [comment]
What would be the default?
Maybe the hostname without `www`?

**Comment by mworrell** [comment]
BTW z_url_metadata is part of https://github.com/zotonic/z_stdlib, can you add an issue there?

**Comment by fredpook** [comment]
moved to https://github.com/zotonic/z_stdlib/issues/28
