### ISSUE TITLE
Error 403 page shows logon box on insecure connection.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1836]
For some reason, the error 403 page shows a logon box when ssl is enabled, but the request is served from http. The logon box should not be shown in this case because users can accidentally enter their credentials which will be validated over an insecure connection.

The following line causes this. I'm not sure how to resolve this as there are many settings and parameters resulting in this behaviour.

https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_authentication/priv/templates/error.403.tpl#L14

The expression which causes this is: `not m.config.mod_ssl.is_ssl.value or m.req.is_ssl)`

This expression resolves to `true` when `mod_ssl.is_ssl` is `undefined` (meaning that dispatch rules are not forced to ssl automatically) and `m.req.is_ssl` is `false`.

I think this expression should be made simpler. When the ssl module is enabled and the request is not https, the logon box should never be shown. The other settings like `m.config.site.protocol` shouldn't matter. Or am I missing something?

**Comment by mmzeeman** [comment]
`m.config.site.protocol` is used for sites running behind a proxy. Does `m.req.is_ssl` work correctly then?

**Comment by mmzeeman** [comment]
On 0.x `m.req.is_ssl` returns `false` when the proxy handles ssl traffic.

**Comment by mmzeeman** [comment]
I think this should be the expression.

When the site is http only, show the logon box, and otherwise check if the request is secure or not.

```django
{% with m.req.is_ssl or m.config.site.protocol.value|default:"http" /= 'http' as is_show_login %}
```

**Comment by mworrell** [comment]
Master is now https only, so this problem won't happen there.

Closing.
