### ISSUE TITLE
Javascript z_event error while adding media item in tinymce

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#1838]
If you add a media item in the tinymce editor this error will be logged in the console. `z_event: no registered event named: 'links-_some id_-depiction'`

Although it logs this error, it doesn't seem to break anything.

Steps to reproduce
- Login the admin 
- Create new page
- add 'zotonic media item'
- select/upload item

Also, once you have the selected item present in the 'Attached media' block, the error won't be logged. So the event seems to be registered at that point.

**Comment by mworrell** [comment]
I think this is from before we had the *live* connection lists in the admin.
This was needed to force an update of the list with depictions.

 I think this can be removed from the javascript.

**Comment by DorienD** [comment]
@mworrell Could this be fixed in milestone 0.53?

**Comment by mworrell** [comment]
Isn't this only on the Javascript console?  So doesn't log on the server?

**Comment by mworrell** [comment]
Was already removed in master, now also (partly) in 0.x
