### ISSUE TITLE
Lots of log messages. Close websockets more carefully.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1840]
After inspecting the logs I found a lot of crashes.

```
2017-11-06 08:18:11.363 [error] <0.404.0> {mochiweb_socket_server,307,{request_error,killed}}
```

These are caused by the following code in `z_session_page.erl`

Instead of bluntly killing the websocket it should be closed more carefully.

```erlang
%% @doc Close the websocket if there is one.
opt_close_websocket(undefined) ->
    ok;
opt_close_websocket(Pid) ->
    % erlang:exit(Pid, kill).
    ok.
```

**Comment by mworrell** [comment]
Is this also an issue on master?

**Comment by mmzeeman** [comment]
Oh, forgot about that one. It probably is.

This happens when the page session gets a websocket attach, but there is still an old zombie websocket attached which is still open.

I have to look how that works on master.

**Comment by mmzeeman** [comment]
Master is already ok. It already carefully closes websockets instead of killing them.
