### ISSUE TITLE
FTB on Debian stable

### ISSUE THREAD

**Issue by JiffB** [zotonic/zotonic#1841]
Debian stable + Erlang 20.1-1 ES pkgs
.
Hi folks,
.
first compiling of release 34.0 failed with:
.
Compiled src/ec_cnv.erl
/src/ERLANG/TESTS/zotonic-0.34.0/deps/erlware_commons/src/ec_semver_parser.erl:15: export_all flag
   enabled - all functions will be exported
Compiling /src/ERLANG/TESTS/zotonic-0.34.0/deps/erlware_commons/src/ec_semver_parser.erl failed:
ERROR: compile failed while processing /home/niff/ERLANG/TESTS/zotonic-0.34.0
   /deps/erlware_commons: rebar_abort
GNUmakefile:56: recipe for target 'compile' failed
make: *** [compile] Error 1
.
a try to directly compile erlware_commons in its directory also failed with:
.
$ rebar co
==> erlware_commons (compile)
Dependency not available: cf-.* ({git,"https://github.com/project-fifo/cf",
                                      {tag,"0.2.0"}})
ERROR: compile failed while processing /src/ERLANG/TESTS/zotonic-0.34.0/deps/erlware_commons:
   rebar_abort
.
so, erlware_commons has a problem :/
is there a way to compile zotonic without this git or any other solution ?

**Comment by JiffB** [comment]
On the other hand, git compiled like a charm ; could it be that doc isn't up to date and it is now git the preferred way to go ?
And is git acceptable for a production system ?

**Comment by mworrell** [comment]
What did you use instead of the git version?

On my production machines I often use git to checkout a new version and compile.  Mostly without restarting the beam process, using `z:compile()` to load the new beams.

Only with changed deps we might need to restart the node.

On a side note, having inotify running on production is currently not advisable.
Though we are about to merge changes to master for addressing that issue.

**Comment by ddeboer** [comment]
Our current 0.x branch (including 0.34) is currently not compatible with Erlang 20 (cf.  https://github.com/zotonic/zotonic/issues/1813).

**Comment by JiffB** [comment]
On Wed, 08 Nov 2017 09:34:58 +0000 (UTC)
David de Boer <notifications@github.com> wrote:

> Our current 0.x branch (including 0.34) is currently not compatible
> with Erlang 20 (cf.  https://github.com/zotonic/zotonic/issues/1813).
 
OK, thanks for the information, I'll stay w/ git.
