### ISSUE TITLE
New zotonic release causes unnessary recompilations

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1842]
When we bump the version number of zotonic we update zotonic.hrl. This causes a recompilation of all code which is not nice when you do live code upgrades.

Could we move the version number to a separate header file?

**Comment by ddeboer** [comment]
Or just remove it? Where is it used, anyway? Only for the HTTP responses?

**Comment by mworrell** [comment]
See 2360411037eb7c161460aa8b5342cbebf08448bb

Now also changing it for master (will be merge request)

Accompanying merge request for mod_github:
https://github.com/arjan/mod_github/pull/5
