### ISSUE TITLE
DISCUSS: ACL checks in models

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#1849]
In #1226 we are working on making the `m_rsc` model safer to use.

I think we might want to tighten other models as well. 
Just think what `m_identity` and `m_config` can do...

Problem with m_config is that it contains a mix of public, harmless, and very sensitive settings.

What could be a good way of separating the settings, so that templates (and APIs) can only access configurations if and only if they have the appropriate access rights?

We could apply one or more of the following:

 1. Heuristics (anything with 'secret', 'password' or 'account' needs admin rights)
 2. List of known *sensitive* configs
 3. Special 'is_secret' flag per config

What do you think?

In the same manner we can add extra security to the other models.

I am especially thinking of this as I want to:

 1. Open the models via HTTP and MQTT APIs (per model opt-in).
 2. Make rendering any template safe (to render random templates via APIs)

/cc @ddeboer @mmzeeman @arjan

**Comment by ddeboer** [comment]
> We could apply one or more of the following:
> 
> 1. Heuristics (anything with 'secret', 'password' or 'account' needs admin rights)
> 2. List of known *sensitive* configs
> 3. Special 'is_secret' flag per config

I’m against 2, as people may forget to add new config params to the list of secret ones, thus opening up a security hole. Between the other two options, 1 seems the more transparent to Zotonic users.

**Comment by mworrell** [comment]
I was also leaning towards 1 (heuristics).
Will check what we have, and maybe rename some configuration.

For the names we should at least force admin rights for:

 * `.*secret.*`
 * `.*password.*`
 * `.*account.*`
 • `(.*_)?key(_.*)?`

I think we can rename config names to fit in the above patterns.

Maybe we also should do something with:

 • `(.*_)?ur[il]`
 * `(.*_)?id` (like appid)
 
But I think if an uri or (app-)id is secret than we should change the config name to include `..secret..` or `...account...`.  And it is best to keep the secret-patterns-list as short as possible.

**Comment by mmzeeman** [comment]
Still checked via `z_acl:is_allowed/3` I assume?

**Comment by mworrell** [comment]
I think it should be handled by `z_acl:is_admin/1`, which in turn checks for the `use:mod_admin_config` right.

This is not completely ideal, as it enables r/w access, and not only r access.

That could be fixed by adding module rights?  Maybe `use` and `view`?

**Comment by mmzeeman** [comment]
Aha... I thought where going to extend it with `z_acl:is_allowed(view, {m_config, prop}, Context)` calls.

**Comment by mmzeeman** [comment]
It is more upto the active security policy to do the `z_acl:is_admin/1` check or something else I guess.

**Comment by mworrell** [comment]
That is also possible and more flexible, and we should add a sensible default based on the config name (if the ACL module doesn't handle the new acl check).

Might actually be a general approach to handle model access checks (for `m_get`).

It would then be something like:

```erlang
z_acl:is_allowed(view, #acl_model{ model = m_config, object = TheProp }, Context)
```

(and for other other model methods we can then use `update` and `delete` permissions)

Though this would double the ACL lookups for models that have their own ACL logic (like `m_rsc`).
Maybe we could add an exported model function?  Like `m_foobar:m_is_allowed/3` ?

If it is missing we could assume two things:

 1. assume user needs admin rights
 2. check `use.mod_foobar`  (we can find the module for the model).
 3. the model is checking itself

Where I am against (3), as we normall err on the safe side.

**Comment by mworrell** [comment]
Of course, the ACL checks would only be applied in calls to `m_get`.
Other functions need to apply their own restrictions.

Though future callbacks like `m_update` and `m_delete` will also have their permissions checked.

**Comment by mmzeeman** [comment]
Is it doubled? Or do you have a cascaded check? First on model level, and then later on resource level?

**Comment by mworrell** [comment]
It feels a bit over the top to do a cascaded check, I am not sure what the best is there.

If it is on the model / module level then we could just apply (which is very cacheable):

```erlang
z_acl:is_allowed(view, #acl_model{ model = m_config, module = zotonic_core }, Context)
```

And let the model do the finesses.

But of course this wouldn't help in the use case of those configs, as the model would then apply the heuristics on the per-config level, and not the ACL.

To be able to do the per-config level we need to pass the request path, but that would also move knowledge of the request path to the ACL module, which will create confusion and errors.

So per model/module is not too bad, actually ... especially with the fallback to `use.module`

**Comment by ddeboer** [comment]
`#acl_model{}` would be most consistent with the ACL records [that we already have](https://github.com/zotonic/zotonic/issues/1401#issuecomment-252604239).

**Comment by ddeboer** [comment]
As discussed with @mworrell, an even simpler solution is to have _all_ `m_config:m_get` only available to admin users. 

E.g.

```
m.config.mod_editor_tinymce.version.value
```

will then be wrapped/abstracted by the module in question to:

```
m.config.mod_editor_tinymce.version
```
