### ISSUE TITLE
Check box 'send welcome e-mail' doesn't work on resource

### ISSUE THREAD

**Issue by krista-ramakers** [zotonic/zotonic#1852]
When creating a new user by using the button in Auth --> Users, and you check the box 'send welcome e-mail', I receive an e-mail accordingly.

When I go to the resource for that person/account I just created and I click 'set username/password' and check 'send welcome e-mail' in that modal, then I don't receive an e-mail.

**Comment by mworrell** [comment]
I just checked on the latest 0.x branch and it works there (with a bare zotonic).

In the admin, can you check the email log, and also the console.log if there are any messages?

**Comment by krista-ramakers** [comment]
@fredpook can you check console.log for me? Thanks!
