### ISSUE TITLE
Custom pivot filter in admin query

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1854]
Hi!

Tried to do this in de admin query box:

```
cat=story
is_published=false
custompivot=geheugen
filter=[“is_pending”, true]
```

And it gave this error:

`16:47:49.586 [error] Rsc update error: throw:{function_clause,[{search_query,add_filters,[<<"[\"pivot1.is_pending\", \"true\"]">>,{search_sql,"rsc.id","rsc rsc left join pivot_geheugen pivot1 on (rsc.id = pivot1.id)","(not rsc.is_published or rsc.publication_start > now() or rsc.publication_end < now())",[],[],undefined,[{rsc,"rsc"},{<<"geheugen">>,"pivot1"}],[],[{"rsc",[<<"story">>]}],[],[],undefined,[no_publish_check,[]],false}],[{file,"modules/mod_search/support/search_query.erl"},{line,826}]},{search_query,parse_query,3,[{file,"modules/mod_search/support/search_query.erl"},{line,183}]},{search_query,search,2,[{file,"modules/mod_search/support/search_query.erl"},{line,44}]},{m_rsc_update,preflight_check,3,[{file,"src/models/m_rsc_update.erl"},{line,596}]},{m_rsc_update,update_transaction_fun_props,3,[{file,"src/models/m_rsc_update.erl"},{line,377}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"src/db/z_db.erl"},{line,135}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,210}]}]}`

**Comment by mworrell** [comment]
Fixed, see history above.
