### ISSUE TITLE
compile z_media_import.erl failed

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#1875]
after a .rebar3 upgrade, 

```./rebar3  compile
===> Verifying dependencies...
===> Compiling zotonic
===> Compiling _build/default/lib/zotonic/src/support/z_media_import.erl failed
_build/default/lib/zotonic/src/support/z_media_import.erl:31: can't find include lib "z_stdlib/include/z_url_metadata.hrl"

_build/default/lib/zotonic/src/support/z_media_import.erl:94: record url_metadata undefined
_build/default/lib/zotonic/src/support/z_media_import.erl:100: record url_metadata undefined
_build/default/lib/zotonic/src/support/z_media_import.erl:102: record url_metadata undefined

GNUmakefile:30: recipe for target 'compile' failed
```
./bin/zotonic -v
Zotonic 1.0-dev

**Comment by crownedgrouse** [comment]
After adding record url_metadata in z_media_import.erl, compiles but fails to start : 

`[error] zotonic:80 Zotonic start error: "no such file or directory: z_stdlib.app"`

**Comment by crownedgrouse** [comment]
I fixed by changing application name in `src/z_stdlib.app.src`
 otherwise compiled failed with 
```ERROR: Invalid ebin/z_stdlib.app: name of application (zotonic_stdlib) must match filename.```
but now : 
```{"init terminating in do_boot",{undef,[{cowboy,start_clear,[zotonic_http_listener_ipv4,100,[inet,{port,8000},{backlog,500}],#{env=>#{},middlewares=>[cowmachine_proxy,z_sites_dispatcher,z_cowmachine_middleware],request_timeout=>60000}],[]},{zotonic,start_http_listeners_ip4,2,[{file,"/home/zotonic/www/zotonic/_build/default/lib/zotonic/src/zotonic.erl"},{line,167}]},{zotonic,start_http_listeners,0,[{file,"/home/zotonic/www/zotonic/_build/default/lib/zotonic/src/zotonic.erl"},{line,144}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ()

```

**Comment by mworrell** [comment]
Interesting as z_stdlib should be checked out as zotonic_stdlib. @ddeboer did some name changing to make the name more consistent.

Can you try a complete new rebuild of the master?

**Comment by ddeboer** [comment]
@crownedgrouse It looks like you either have an old version of the Zotonic master or an outdated `_build` dir (`_build/default/lib/zotonic/src` no longer exists). So, like @mworrell suggested, can you try this?

```bash
cd zotonic
rm -r _build
make
```

**Comment by crownedgrouse** [comment]
hi,
no way.  It finally worked by removing... (and the winner is...) rebar3.
a check of the rebar3 version would maybe usefull when upgrading.

**Comment by mworrell** [comment]
Ah, there was an old(er) rebar3 sitting in the directory?

Thanks for figuring this out, I made an issue for the rebar3 version check: https://github.com/zotonic/zotonic/issues/1876
