### ISSUE TITLE
Signup form fields surname prefix

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1879]
In _signup_form_fields_email.tpl the surname prefix has a different 'name' in comparison to the name it gets in the cms: surprefix vs. name_surname_prefix. Could that be changed so it matches? 

Sidenote to this, the field does not save when you've activated this field in the _signup_config.tpl.

**Comment by mworrell** [comment]
We have to look into that, I remember that it might actually be called `surprefix` to prevent browsers to autofill the `surname` of the user. In either case, we should then map it from the form to the correct `name_surname_prefix` property.

**Comment by ddeboer** [comment]
> to prevent browsers to autofill the surname of the user.

We have `autocomplete="off"` for that, right?

**Comment by mworrell** [comment]
There is still a mixup between *last* and *surname* in the signup forms. I propose to not fix that in 0.x but move it to the 1.0

**Comment by mworrell** [comment]
The best way to have the autofill behave turns out to be to tell what to fill, turning autocomplete off doesn't turn off autofill.

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#inappropriate-for-the-control

**Comment by mworrell** [comment]
See https://github.com/zotonic/zotonic/pull/1907
