### ISSUE TITLE
FreeBSD 11.1-RELEASE setresuid(3) not supported

### ISSUE THREAD

**Issue by gpatrickb** [zotonic/zotonic#1887]
I am attempting to build Zotonic, the Erlang CMS, but it errors out when compiling exec.cpp.

```
~/zotonic/_build/default/lib/erlexec/c_src/exec.cpp:454:14: error: #error setresuid(3) not supported!
             #error setresuid(3) not supported!
                        ^~~~~
~/zotonic/_build/default/lib/erlexec/c_src/exec.cpp: In function 'void initialize(int, bool, bool)':
~/zotonic/_build/default/lib/erlexec/c_src/exec.cpp:456:9: error: 
expected primary-expression before '<' token
                < 0) {
                ^

gmake:  *** [GNUmakefile:27: compile] Error '1'
```

Reading the man page for setresuid looks like it is correct. 

I tried changing 
`setresuid(-1, userid, geteuid())`
to
`setresuid(-1, 1001, 0)`
Then it complained about the same error in exec_impl.cpp.

**Comment by mworrell** [comment]
@CyBeRoni do you have a (Free)BSD machine available?

**Comment by mworrell** [comment]
According to erlexec docs at https://github.com/saleyn/erlexec the following OSs are supported:

Linux, Solaris, FreeBSD, MacOS X

So we should be able to get it compiled on FreeBSD.

**Comment by mworrell** [comment]
Ah, digging through the commits I see that the erlexec on Hex is older than the commit for FreeBSD support.

We either change to the git version or see if @saleyn is able to make a new release to Hex.
I will add an issue with erlexec for this.

**Comment by mworrell** [comment]
Issue at erlexec https://github.com/saleyn/erlexec/issues/103

**Comment by mworrell** [comment]
@saleyn released a new version of erlexec. I will update our dependencies.

**Comment by mworrell** [comment]
@gpatrickb I have pushed an erlexec upgrade. Can you check if this works for you?

**Comment by gpatrickb** [comment]
Marc,
I will check later today and let you know the results.  Thank you for your extremely fast action on this issue!
Regards,
Gary
    On Thursday, March 15, 2018, 9:43:02 AM CDT, Marc Worrell <notifications@github.com> wrote:  
 
 
@gpatrickb I have pushed an erlexec upgrade. Can you check if this works for you?

**Comment by gpatrickb** [comment]
Marc,
I was able to successfully compile Zotonic on FreeBSD 11.1-RELEASE with the changes.  Thank you again for your quick response and action.
Regards, Gary
 

    On Thursday, March 15, 2018, 11:02:48 AM CDT, G B <g_patrickb@yahoo.com> wrote:  
 
  Marc,
I will check later today and let you know the results.  Thank you for your extremely fast action on this issue!
Regards,
Gary
    On Thursday, March 15, 2018, 9:43:02 AM CDT, Marc Worrell <notifications@github.com> wrote:  
 
 
@gpatrickb I have pushed an erlexec upgrade. Can you check if this works for you?

**Comment by mworrell** [comment]
Thanks for testing this!
