### ISSUE TITLE
crash pg_sql

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#1893]
`zotonic    | 2018-03-26 22:00:34.802 [error] <0.328.0> gen_server <0.328.0> terminated with reason: bad argument in pgsql_binary:encode/2 line 15
zotonic    | 
zotonic    | ==> /srv/zotonic/priv/log/crash.log <==
zotonic    | 2018-03-26 22:00:34 =ERROR REPORT====
zotonic    | ** Generic server <0.328.0> terminating 
zotonic    | ** Last message in was {equery,{statement,[],[{column,<<"id">>,int4,4,-1,1}],[int4,{array,int4}]},[{int4,245500},{{array,int4},[false,{true,3223},{true,1523}]}]}
zotonic    | ** When Server state == {state,gen_tcp,#Port<0.17769>,<<>>,{27,1930746071},on_message,{[],[]},undefined,[{<<"application_name">>,<<>>},{<<"client_encoding">>,<<"UTF8">>},{<<"DateStyle">>,<<"ISO, MDY">>},{<<"integer_datetimes">>,<<"on">>},{<<"IntervalStyle">>,<<"postgres">>},{<<"is_superuser">>,<<"off">>},{<<"server_encoding">>,<<"UTF8">>},{<<"server_version">>,<<"9.5.5">>},{<<"session_authorization">>,<<"zotonic">>},{<<"standard_conforming_strings">>,<<"on">>},{<<"TimeZone">>,<<"UTC">>}],[],[],[],[],[],undefined,84}
zotonic    | ** Reason for termination == 
zotonic    | ** {badarg,[{pgsql_binary,encode,2,[{file,"src/pgsql_binary.erl"},{line,15}]},{pgsql_binary,'-encode_array/4-fun-0-',3,[{file,"src/pgsql_binary.erl"},{line,66}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},{pgsql_binary,encode_array,4,[{file,"src/pgsql_binary.erl"},{line,67}]},{pgsql_binary,encode_array,2,[{file,"src/pgsql_binary.erl"},{line,56}]},{pgsql_wire,encode_parameter,1,[{file,"src/pgsql_wire.erl"},{line,189}]},{pgsql_wire,encode_parameters,4,[{file,"src/pgsql_wire.erl"},{line,181}]},{pgsql_sock,command,2,[{file,"src/pgsql_sock.erl"},{line,195}]}]}
zotonic    | 2018-03-26 22:00:34 =CRASH REPORT====
zotonic    |   crasher:
zotonic    |     initial call: pgsql_sock:init/1
zotonic    |     pid: <0.328.0>
zotonic    |     registered_name: []
zotonic    |     exception exit: {{badarg,[{pgsql_binary,encode,2,[{file,"src/pgsql_binary.erl"},{line,15}]},{pgsql_binary,'-encode_array/4-fun-0-',3,[{file,"src/pgsql_binary.erl"},{line,66}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},{pgsql_binary,encode_array,4,[{file,"src/pgsql_binary.erl"},{line,67}]},{pgsql_binary,encode_array,2,[{file,"src/pgsql_binary.erl"},{line,56}]},{pgsql_wire,encode_parameter,1,[{file,"src/pgsql_wire.erl"},{line,189}]},{pgsql_wire,encode_parameters,4,[{file,"src/pgsql_wire.erl"},{line,181}]},{pgsql_sock,command,2,[{file,"src/pgsql_sock.erl"},{line,195}]}]},[{gen_server,terminate,7,[{file,"gen_server.erl"},{line,812}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
zotonic    |     ancestors: [<0.314.0>,<0.304.0>,'z_db_pool$amurasso','z_site_sup$amurasso','z_sites_manager$supervisor',z_sites_manager,z_sites_sup,zotonic_sup,<0.253.0>]
zotonic    |     messages: []
zotonic    |     links: [<0.314.0>,#Port<0.17769>]
zotonic    |     dictionary: [{datetime_mod,pgsql_idatetime}]
zotonic    |     trap_exit: false
zotonic    |     status: running
zotonic    |     heap_size: 4185
zotonic    |     stack_size: 27
zotonic    |     reductions: 94695
zotonic    |   neighbours:
zotonic    |     neighbour: [{pid,<0.314.0>},{registered_name,[]},{initial_call,{z_db_pgsql,init,['Argument__1']}},{current_function,{gen,do_call,4}},{ancestors,[<0.304.0>,'z_db_pool$amurasso','z_site_sup$amurasso','z_sites_manager$supervisor',z_sites_manager,z_sites_sup,zotonic_sup,<0.253.0>]},{messages,[]},{links,[<0.304.0>,<0.328.0>,<0.302.0>]},{dictionary,[]},{trap_exit,false},{status,waiting},{heap_size,6772},{stack_size,25},{reductions,17667}]
zotonic    | 2018-03-26 22:00:34 =ERROR REPORT====
zotonic    | ** Generic server 'z_pivot_rsc$amurasso' terminating 
zotonic    | ** Last message in was poll
zotonic    | ** When Server state == {state,amurasso,true,false}
zotonic    | ** Reason for termination == 
zotonic    | ** {{noproc,{gen_server,call,[<0.314.0>,{squery,"ROLLBACK"},30000]}},[{gen_server,call,3,[{file,"gen_server.erl"},{line,212}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"src/db/z_db.erl"},{line,150}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"src/db/z_db.erl"},{line,210}]},{z_db,transaction1,2,[{file,"src/db/z_db.erl"},{line,126}]},{z_db,transaction,3,[{file,"src/db/z_db.erl"},{line,95}]},{z_pivot_rsc,do_poll_queue,1,[{file,"src/support/z_pivot_rsc.erl"},{line,410}]},{z_pivot_rsc,do_poll,1,[{file,"src/support/z_pivot_rsc.erl"},{line,356}]}]}
zotonic    | 2018-03-26 22:00:34 =SUPERVISOR REPORT====
zotonic    |      Supervisor: {<0.304.0>,poolboy_sup}
zotonic    |      Context:    child_terminated
zotonic    |      Reason:     {badarg,[{pgsql_binary,encode,2,[{file,"src/pgsql_binary.erl"},{line,15}]},{pgsql_binary,'-encode_array/4-fun-0-',3,[{file,"src/pgsql_binary.erl"},{line,66}]},{lists,mapfoldl,3,[{file,"lists.erl"},{line,1354}]},{pgsql_binary,encode_array,4,[{file,"src/pgsql_binary.erl"},{line,67}]},{pgsql_binary,encode_array,2,[{file,"src/pgsql_binary.erl"},{line,56}]},{pgsql_wire,encode_parameter,1,[{file,"src/pgsql_wire.erl"},{line,189}]},{pgsql_wire,encode_parameters,4,[{file,"src/pgsql_wire.erl"},{line,181}]},{pgsql_sock,command,2,[{file,"src/pgsql_sock.erl"},{line,195}]}]}
zotonic    |      Offender:   [{pid,<0.314.0>},{id,z_db_pgsql},{mfargs,{z_db_pgsql,start_link,undefined}},{restart_type,temporary},{shutdown,5000},{child_type,worker}]
`

**Comment by mworrell** [comment]
Seems like a wrong type of arguments was given to a query.
Do you know the query that crashed?

**Comment by heiheshang** [comment]
How to find out what kind of request?

**Comment by heiheshang** [comment]
I do not do any requests

**Comment by mworrell** [comment]
Check when it crashes.
The `245500` in the trace might also be a hint, maybe a resource id?

**Comment by mworrell** [comment]
BTW is this the 0.x or the master?

**Comment by heiheshang** [comment]
0.32

**Comment by heiheshang** [comment]
figured out, thanks

**Comment by mworrell** [comment]
That is quick, thank you!
