### ISSUE TITLE
Urls don't translate

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1897]
Hi!

On this page: https://www.immaterieelerfgoed.nl/nl/page/1129/cow-market-in-woerden. English and Dutch is enabled but the url when switching does not change, it keeps the english title. Page was first made in Dutch and later translated to English. 

Default language is set on dutch. Is there a way to fix this?

**Comment by mworrell** [comment]
I assume you mean the *slug* in the url.

The slug is currently not translatable, but you can change it on resource edit page in the admin.

See also #1095

**Comment by mworrell** [comment]
Closing for now, as we have issue #1095 

Feel free to discuss priority of that issue with @ddeboer

**Comment by ddeboer** [comment]
@mworrell #1095 is not about translating slugs, is it?

**Comment by mworrell** [comment]
It is added as an extra todo on that issue.

It is related. If you translate then you also need Unicode.
