### ISSUE TITLE
Issue in editing contact and about page on admin

### ISSUE THREAD

**Issue by fossbalaji** [zotonic/zotonic#1914]
Hi,
  I am little bit familiar with erlang. I am trying to create a  blog for me in zotonic. I have installed as per docuemtation. But login into admin and trying to edit about page and contact and about this blog , both looks like this 
![screen shot 2018-06-07 at 3 24 01 pm](https://user-images.githubusercontent.com/994268/41092622-e990ed46-6a66-11e8-8182-583530ff6031.png)

Any help will be much appreciated . 

in debug console this is the error i'm getting
error] gbala cowmachine:72 stop_request 500 (reason {function_clause,[{search_query,parse_edges,[hassubject,[page_contact,<<"haspart">>]

**Comment by mworrell** [comment]
Looks like we have a problem with the search terms.

@ddeboer do you know if all 0.x changes are merged into master?

**Comment by mworrell** [comment]
@fossbalaji Can you check against #1925 ?  I expect it fixes your problem.
