### ISSUE TITLE
Home directory .erlang file (which contains io:format statements) causes zotonic scripts not to work. 

### ISSUE THREAD

**Issue by tonywallace64** [zotonic/zotonic#1919]
I have had a .erlang file in my home directory for a long time.  Unfortunately I have found that it conflicts with /bin/zotonic scripts.   Fortunately the solution is easy.  An empty .erlang file in the zotonic directory.

**Comment by mworrell** [comment]
So when you start `erl` then there is some extra output to stdout?

**Comment by tonywallace64** [comment]
The problem is that the management scripts for zotonic get corrupted.  For example bin/zotonic start will work, but bin/zotonic stop will then fail.  Internally scripts such as zotonic_setup fail when they execute

**Comment by tonywallace64** [comment]
This does not work.
``ERL_CALL=$($ERL -noshell -noinput  -eval "io:format(\"~s\", [code:priv_dir(erl_interface)])" -s erlang halt|sed 's~priv$~bin/erl_call~')
export ZOTONIC_CALL="$ERL_CALL $NAME_ARG $NODENAME@$NODEHOST"

My .erlang file (home directory) is:
% -*-erlang-*-
io:format(standard_error,"~s~n",["running .erlang in home directory"]).

code:add_paths(["./ebin","./untested","./test/ebin"]).
Deps = filelib:wildcard("*","deps").
io:format(standard_error,"~s ~p~n",["Dependencies: ",Deps]).
code:add_paths(
   [filename:join(["deps",X,"ebin"]) || X <- Deps]).
Apps = filelib:wildcard("*","apps").
code:add_paths(
   [filename:join(["apps",X,"ebin"]) || X <- Apps]).
Tools = filelib:wildcard("*","tools").
code:add_paths(
   [filename:join(["tools",X,"ebin"]) || X <- Tools]).
Priv = filelib:wildcard("*","priv").
code:add_paths(
   [filename:join(["priv",X,"ebin"]) || X <- Priv]).

%% Use build tools in sasl examples
LibDir = filename:join([os:getenv("ROOTDIR"),"lib"]).
{ok,Libs} = file:list_dir(LibDir).
SaslList = lists:filter(fun(X) -> lists:prefix("sasl-",X) end,Libs).
io:format("LibDir ~s~n",[LibDir]).
%io:format("Current Sasl ~s~n",[CurrentSasl]).

%% Add dependency install_tools to the project instead.
%code:add_paths([filename:join([LibDir,CurrentSasl,"examples/ebin"])]).

io:format(standard_error,"~s~n",[".erlang completed"]).

My suggested .erlang file (zotonic directory) is:

%% This file required to protect scripts from site/personal .erlang files

**Comment by mworrell** [comment]
Closing this for now - don't see a standard way of fixing this.

Please reopen if there are suggestions and/or ideas.

**Comment by mworrell** [comment]
Reopening: the solution was already suggested:

>  Fortunately the solution is easy. An empty .erlang file in the zotonic directory.

We can add this file to the Zotonic.

**Comment by mworrell** [comment]
@tonywallace64 thanks for the report!

I followed your suggestion and added an `.erlang` file to the Zotonic directory.
