### ISSUE TITLE
bear downloading from wrong repository use https://github.com/folsom-project/bear.git instead

### ISSUE THREAD

**Issue by tonywallace64** [zotonic/zotonic#1920]
Current clone downloads a version that has native compile.  This does not work on my machine.  Looking into this I found that this was because zotonic was downloading an unmaintained repository.

**Comment by mworrell** [comment]
It seems `bear` is coming in via `folsom`.

We might need to update folsom in the 0.x

The folsom version we use in master uses the Hex package for bear.

What kind of OS are you using?

**Comment by mworrell** [comment]
Fixed in 67e9c6bb5
