### ISSUE TITLE
Ancient version of jQuery included with Zotonic

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#1922]
We currently include have jQuery 1.11.1 released in may 2014. Since then we didn't need to update it.

Our customers sometimes do code reviews and find this.
 
- Do we still need to support older versions of IE (6 and 8)? 
- Is it hard to give zotonic a more recent supported version of jQuery?
- Can we do this in a backward compatible way so old sites don't have to be update?

@ddeboer I can imagine your clients sometimes mention this too. Do we wait for the removal of jQuery, or just add a newer version and do a little bit of work?

**Comment by mmzeeman** [comment]
This is the message we got in an audit.

``` 
Beveiligingsrisico; gedateerd framework gebleken uit Logius audit; issue A-02. Ze gebruiken nu versie 1.11 JQuery is gedateerd.”
```

**Comment by mworrell** [comment]
I am ok with upgrading to something recent.

I guess we can't kill of old(er) IE yet, so the newest 1.x jQuery?

/cc @ArthurClemens

**Comment by DorienD** [comment]
+1 for ugrading jquery, the newest jquery supports from IE9 to above. They don't actively test in old browsers but i guess thats our job to think of something else if it doens't work.

**Comment by mworrell** [comment]
So we can go to 2.x?

**Comment by DorienD** [comment]
Why not go to 3.x, what do you think @mmzeeman ?

**Comment by mworrell** [comment]
@mmzeeman I propose you try out 3.x, and test against the oldest to-be-supported IE browser in your site stats.

**Comment by mmzeeman** [comment]
Ok, I'll try with zotonic admin then. We don't see lower then IE11, mostly used by our corporate clients. We see that these companies switch to FF.

**Comment by mworrell** [comment]
They are switching away from IE < 11 ?  That is good news.

On our most corporate website we see that of the IE users, 98% are using IE11. There are a very small number of people holding out on IE9 and IE8.  I think we can safely assume now that for IE we can only target IE11 and disregard all older versions.

**Comment by mmzeeman** [comment]
Yes, and when they switch away from IE11, they usually go to firefox. Sometimes the corporate users can't even open their own website with IE11.

**Comment by mworrell** [comment]
To Firefox?   Interesting that they don't switch to Chrome or Edge.  Maybe they are using old Windows versions?

**Comment by mmzeeman** [comment]
Yes, the same happened to my wife's corporate laptop. The administrators added firefox. I don't know why they don't add chrome instead. Probably because they have more control over what is installed with Firefox.

**Comment by mmzeeman** [comment]
I've tested with the newest version of jquery. Everything works as expected. Tested with newer browsers and IE11. Not much work expected.

**Comment by mmzeeman** [comment]
Here is a branch which upgrades our current jquery to 3.3.1 so you can try it yourself.

https://github.com/zotonic/zotonic/tree/jquery-upgrade

**Comment by mworrell** [comment]
Added a merge request here https://github.com/zotonic/zotonic/pull/1926

**Comment by ddeboer** [comment]
Fixed in 0.41.0.

**Comment by mmzeeman** [comment]
Oh, I wanted to write something about jquery migrate. It has a version number. If your site uses that in a template it is possible it will break.

**Comment by ddeboer** [comment]
@mmzeeman Feel free to add that to the 0.41.0 release notes.

**Comment by mworrell** [comment]
Normally we didn't have the migrate js file in our lib includes, don't we?

**Comment by mmzeeman** [comment]
We have it included in _js_include_jquery because it solves deprecated api problems for older sites.

**Comment by mmzeeman** [comment]
@ddeboer where are the 0.41 release notes? Are they in a special release, or can I just create a new rst file?

**Comment by ddeboer** [comment]
@mmzeeman I usually create them on the day of the release itself (to get the latest updates in there), but you can create the file right now.
