### ISSUE TITLE
zotonic make fails

### ISSUE THREAD

**Issue by fossbalaji** [zotonic/zotonic#1941]
I am trying to set up 0.40 on ubuntu 16.04 
 When i run ```make``` 

this is the error i am getting
==> cf (compile)
Compiled src/cf.erl
Killed
GNUmakefile:56: recipe for target 'compile' failed
make: *** [compile] Error 137

**Comment by fossbalaji** [comment]
Turns out Erlang Version is the issue here Erlang (0.20, 20) fails . Erlang 19 works fine . Please update this on documentation if it supports specific version of Erlang .

**Comment by mworrell** [comment]
Interesting.  We are running CI on version 20 as well, and don't see any problems happening there.

We have a compilation problem on 21, which being worked on by @ddeboer 

This was a clean build?

**Comment by fossbalaji** [comment]
Yes . It was a clean build .  I downgraded my erlang version to make it work .

**Comment by fossbalaji** [comment]
Ya i remember . 0.20 version has the compilation error @mworrell

**Comment by mworrell** [comment]
Current automated builds work well, closing the issue.
