### ISSUE TITLE
rebar3 compile

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#1949]
Attempting a fresh install of the development version but getting an error after initial make command:

`[zotonic@dragonflybsd ~/zotonic]$ gmake`
`./rebar3  compile`
`===> Package <<"pc">> not found. Fetching registry updates and trying again...`
`===> Updating package registry...`
`===> Plugin pc not available. It will not be used.`
`===> Verifying dependencies...`
`===> Package bcrypt-1.0.0 not found. Fetching registry updates and trying again...`
`===> Updating package registry...`
`===> Failed to write package index.`
`gmake: *** [GNUmakefile:27: compile] Error 1`

Have verified that a '/home/zotonic/.cache/rebar3' folder exists and that it's writable. Anything different since [Issue #1938](https://github.com/zotonic/zotonic/issues/1938) that would cause this?

**Comment by mworrell** [comment]
It might be a OS specific issue. Or (far fetched, I know) are you low on disk space?

On hex.pm I do see the 1.0.0 version of bcrypt (and also a newer one, we might want to upgrade).

https://hex.pm/packages/bcrypt

So that doesn't seem to be the issue.

**Comment by seannaswell** [comment]
Often it is the simple things, good to ask.

This issue appeared while attempting to install on my laptop, so I attempted a fresh install on a local server running the same OS, which was already running Zotonic. The server install worked, so the issue is something specific to my machine.

Apologies for the false alarm, should have taken that step before reporting an issue. Will look into it further. Thanks.

**Comment by mworrell** [comment]
Thanks for reporting back and finding the solution.

No problem with reporting, this issue will also help others who might bump into similar issues.
