### ISSUE TITLE
Increase twitter polling speed

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#1985]
Make the polling of twitter a bit smarter so tweets are faster imported in zotonic

**Comment by mworrell** [comment]
Request is to make it possible to have a shorter period between polls.
Especially for the configured users and/or tags.

**Comment by mworrell** [comment]
Must be in 0.46 due to customer request

**Comment by mworrell** [comment]
Proposal is to add a max delay for feeds/tags the are not part of the user records.

**Comment by mworrell** [comment]
Fixed in #2002
