### ISSUE TITLE
Flush cache admin action is flushing all sites, is that intended and desirable?

### ISSUE THREAD

**Issue by robvandenbogaard** [zotonic/zotonic#1995]
Pushing the Flush cache button in the admin interface of a specific site flushes caches of all sites, because the corresponding admin action uses `flush/0` instead of `flush/1` with site parameter. I would say that this is unexpected from the admin user's view. Other sites are unknowingly impacted while the intention is to flush caches only of the site at hand.

https://github.com/zotonic/zotonic/blob/012319f62d9c67f67bd95a97d482778d84ceeaf8/apps/zotonic_mod_admin/src/actions/action_admin_admin_tasks.erl#L24

**Comment by mworrell** [comment]
Maybe add an extra button?

**Comment by robvandenbogaard** [comment]
For manager group users I indeed made an extra button. My point is about the semantics of the existing button though: Even for an internal admin it is not clear this button clears all caches of *all sites* while pressing a button in the admin interface of one specific site. I'd propose to limit the button behaviour to `flush/1` for the corresponding site.

**Comment by mworrell** [comment]
Can you make a merge request for both buttons?

**Comment by mworrell** [comment]
Fixed in #2000
