### ISSUE TITLE
mod_development enhancements

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#200]
*From http://code.google.com/p/zotonic/issues/detail?id=195*

I want to redo mod_development a bit:

1. Move the 'reload .beams' switch from the site level to system level, as it is a system level process anyway.

2. Investigate a way of including https://github.com/rustyio/sync for the sites and zotonic code, to make development cycles a tad easier.  (tip of Andreas Stenius)

**Comment by mworrell** [comment]
Closing, we have quite some things done with mod development.
