### ISSUE TITLE
Tinymce bullist en numlist don't work anymore

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2009]
Since the release of the new tinymce editor we need a special plugin for the numlist en bullist, lists. This has to be added to the tiny-init.js of the new version.

**Comment by mworrell** [comment]
Is that plugin included, or do we need to add it?

**Comment by DorienD** [comment]
We need to add it to the tiny-init.js 

`plugins: "compat3x advlist code paste table link zlink zmedia autosave directionality autoresize lists",`

**Comment by DorienD** [comment]
I'm going to test this and make a pull request

**Comment by mworrell** [comment]
Fixed in #2010
