### ISSUE TITLE
New/find dialog change requests

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2027]
Change requests:

- [ ] Make it more clear that the preview is an overlay
- [ ] Click on the list item in the suggestions will result in an edge in stead of preview
- [ ] Change on category will result in category filter in suggestions on the right
- [ ] Add a helper text above the search result
- [ ] We will make a sketch for a design proposal

**Comment by mworrell** [comment]
@DorienD do you have the design proposal?

**Comment by mworrell** [comment]
Fixed in #2034
