### ISSUE TITLE
Better error messages for missing templates.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2032]
<img width="1303" alt="Screenshot 2019-04-01 at 09 45 23" src="https://user-images.githubusercontent.com/1024972/55311379-1312b780-5463-11e9-9610-c3d62c5cafb7.png">

Couple of questions I have as a programmer are:

- What is the name of the template that is missing?
- From what template (or erlang module) was it included.

**Comment by mworrell** [comment]
I think this is straight from `controller_template`, as I don't see any templates in the stack trace.

On the master (with the new `template_compiler` we have a trace inside the templates (tpl filename and line nr).

I agree we should show a better error message, and at least include the basic template. Is there a log entry?

**Comment by mmzeeman** [comment]
Yes... 

```
[info] Could not find template: undefined (enoent)
```

🙃

**Comment by mworrell** [comment]
Ah, then there is an include where the template is passed using a variable... which is `undefined` in this case....

**Comment by mmzeeman** [comment]
There is no special dispatch or anything. It happens when I click on the View button in the admin.

**Comment by mworrell** [comment]
Can you check in the admin/development where the url directs to? It might explain which dispatch rule is used.

**Comment by mmzeeman** [comment]
There was a file named `dispatch~` in my `dispatch` directory which caused the problem. Wow.

**Comment by mworrell** [comment]
I guess we need to suppress all files ending with a `~` ...  ooops

**Comment by mmzeeman** [comment]
It is strange because I have this in my vimrc.

```
set nobackup
set noswapfile
```

**Comment by mworrell** [comment]
Zo we should suppress the following extensions:

 * `~`
 * `.bck`
 * `.swp`  (also this one?)

Others as well?
