### ISSUE TITLE
mod_admin uses a separate Bootstrap version

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#2033]
Bootstrap was recently upgraded (#2021, #1991) but mod_admin has its own, outdated, version in `admin-bootstrap3/js/bootstrap.min.js`. @mworrell Is this on purpose? I suggest we make mod_admin depend on mod_bootstrap and use that version instead.

**Comment by mworrell** [comment]
Good question, maybe the colors are different in the `mod_admin` version?

@ArthurClemens do you know the reasoning behind the separate bootstrap version?

In general I would be for less code, so having one version should be better.

**Comment by mworrell** [comment]
BTW am delaying the 0.48 to include a change to the new/connect dialog. So we could ship this with the 0.48.

**Comment by seannaswell** [comment]
Curious, would this impact those who choose to not use Bootstrap for their sites? Assuming mod_bootstrap would be automatically installed during installation, since mod_admin will now require it?

**Comment by ddeboer** [comment]
@seannaswell No, this will not change anything for those who don’t use Bootstrap, as as mod_bootstrap itself does not contain templates; it is included in `mod_admin/templates/_admin_js_include.tpl` and some other places (`mod_base_site`) instead.

**Comment by mworrell** [comment]
This would need an entry in the release notes, as people might expect to overrule the "frontend" bootstrap version without affecting the admin bootstrap version.
