### ISSUE TITLE
No connect button when adding a page to menu

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2038]
Since the new tab for new/find it is not possible anymore to select a page when creating or editing a menu resource.

Currently there is a check on:
- is_zlink
- predicate & is_linkable 

These are false or undefined.

**Comment by mworrell** [comment]
Fixed in 6cd6b3e

**Comment by mworrell** [comment]
Is now in the 0.48.0 release branch, which will be merged into the 0.x
