### ISSUE TITLE
Page block new dialog

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2039]
When you add a page block "page" the new modal does not show the link button in the 'new-find-results'. I've added a screenshot:

![Screenshot 2019-04-11 at 09 48 56](https://user-images.githubusercontent.com/5102362/55939819-06e6e100-5c3f-11e9-8e0e-7aa90d14ce09.png)

**Comment by DorienD** [comment]
I've found out that the `editor.tpl` uses a `is_zlink` parameter, if i add that to the wire for the page blocks the connect button shows and works.

**Comment by mworrell** [comment]
Fixed in #2040
