### ISSUE TITLE
Failed to fetch and copy dep: diffy-1.0.0

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2044]
`===> Compiling rebar3_hex
===> Fetching diffy ({pkg,<<"diffy">>,<<"1.0.0">>})
===> Failed to fetch and copy dep: diffy-1.0.0
make: *** [GNUmakefile:27: compile] Error 1
Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [hipe] [kernel-poll:true]

{"init terminating in do_boot",{undef,[{zotonic,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
init terminating in do_boot ({undef,[{zotonic,start,[],[]},{init,start_em,1,[]},{init,do_boot,3,[]}]})

Crash dump is being written to: erl_crash.dump...done
`

**Comment by mworrell** [comment]
Hi,

Maybe a problem with hex?

Diffy 1.0.0 is available https://hex.pm/packages/diffy <https://hex.pm/packages/diffy>

- M

**Comment by heiheshang** [comment]
How can I manage this?
`===> Fetching dh_date ({pkg,<<"dh_date">>,<<"1.0.0">>})
===> Downloaded package, caching at /tmp/.cache/rebar3/hex/hexpm/packages/dh_date-1.0.0.tar
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"6.5.0">>})
===> Downloaded package, caching at /tmp/.cache/rebar3/hex/hexpm/packages/rebar3_hex-6.5.0.tar
===> Fetching hex_core ({pkg,<<"hex_core">>,<<"0.5.0">>})
===> Downloaded package, caching at /tmp/.cache/rebar3/hex/hexpm/packages/hex_core-0.5.0.tar
===> Fetching verl ({pkg,<<"verl">>,<<"1.0.1">>})
===> Downloaded package, caching at /tmp/.cache/rebar3/hex/hexpm/packages/verl-1.0.1.tar
===> Compiling verl
===> Compiling hex_core
===> Compiling rebar3_hex
===> Fetching diffy ({pkg,<<"diffy">>,<<"1.0.0">>})
===> Failed to fetch and copy dep: diffy-1.0.0
`

**Comment by mworrell** [comment]
Maybe try to remove rebar3 and let the Makefile re-download rebar3?

Something seems to be wrong with Hex.

- M

**Comment by heiheshang** [comment]
Yes it works

**Comment by mworrell** [comment]
Good to hear that it works again, thanks for reporting back!
