### ISSUE TITLE
crypto:rand_bytes/1 still used ?

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#2045]
Hi,
by wanting to check zotonic project on possible release window, I found that

`mochiweb/src/mochiweb_session.erl` (mochiweb 2.15.0)  is using crypto:rand_bytes/1 which  is not existing anymore since 19.3 ...

I do not see if code in mochiweb is really still used for that, but is this state known ?

**Comment by mworrell** [comment]
We are not using that code in mochiweb, so won’t be an immediate problem.

For OTP-21+ compat we need to upgrade our version of mochiweb anyway, then that code might be gone (didn’t check the current master of mochiweb)

- Marc

**Comment by mworrell** [comment]
Adding this as a reminder to the 1.0 milestone.
