### ISSUE TITLE
undefined macro 'DEBUG/1

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2046]
`===> Compiling apps/zotonic_core/src/zotonic_core.erl failed
apps/zotonic_core/src/zotonic_core.erl:64: undefined macro 'DEBUG/1'

apps/zotonic_core/src/zotonic_core.erl:56: function ensure_mnesia_schema/0 undefined
apps/zotonic_core/src/zotonic_core.erl:59: spec for undefined function ensure_mnesia_schema/0

apps/zotonic_core/src/zotonic_core.erl:73: Warning: function mnesia_dir/0 is unused
apps/zotonic_core/src/zotonic_core.erl:83: Warning: function mnesia_dir_config/0 is unused
apps/zotonic_core/src/zotonic_core.erl:96: Warning: function mnesia_dir_append_node/1 is unused
`

**Comment by mworrell** [comment]
Weird error, the build in Travis-CI works (https://travis-ci.org/zotonic/zotonic/builds/517716465).

I also don't see a call to the `?DEBUG` macro on that line here https://github.com/zotonic/zotonic/blob/master/apps/zotonic_core/src/zotonic_core.erl#L64

Might it be that you have local edits?
Which branch did you check out?

**Comment by heiheshang** [comment]
git branch -v
* master 416c1e5 0.48.1 release notes

**Comment by heiheshang** [comment]
I'm sorry, he wrote
