### ISSUE TITLE
already_exists,zotonic001@9e483e84a766 ?

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2047]
```
13:10:00.028 [error] Supervisor zotonic_launcher_sup had child zotonic_core started with zotonic_core_sup:start_link([{user_ebin_dir,"/opt/zotonic/user/ebin"},{dbhost,"postgres"},{user_modules_dir,"/opt/zotonic/us..."},...]) at undefined exit with reason {'EXIT',{{badmatch,{error,{zotonic001@9e483e84a766,{already_exists,zotonic001@9e483e84a766}}}},[{zotonic_core,ensure_mnesia_schema,0,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core.erl"},{line,65}]},{zotonic_core_sup,start_link,1,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core_sup.erl"},{line,41}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"superviso..."},...]},...]}} in context start_error
13:10:00.029 [error] CRASH REPORT Process <0.321.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,zotonic_core,{'EXIT',{{badmatch,{error,{zotonic001@9e483e84a766,{already_exists,zotonic001@9e483e84a766}}}},[{zotonic_core,ensure_mnesia_schema,0,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core.erl"},{line,65}]},{zotonic_core_sup,start_link,1,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core_sup.erl"},{line,41}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},...]}}}},...} in application_master:init/4 line 134
13:10:00.030 [error] zotonic:49 Zotonic start error: {{shutdown,{failed_to_start_child,zotonic_core,{'EXIT',{{badmatch,{error,{zotonic001@9e483e84a766,{already_exists,zotonic001@9e483e84a766}}}},[{zotonic_core,ensure_mnesia_schema,0,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core.erl"},{line,65}]},{zotonic_core_sup,start_link,1,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core_sup.erl"},{line,41}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},{supervisor,init_children,2,[{file,"supervisor.erl"},{line,314}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,365}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,333}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}}},{zotonic_launcher_app,start,[normal,[]]}}
13:10:00.030 [info] Application zotonic_launcher exited with reason: {{shutdown,{failed_to_start_child,zotonic_core,{'EXIT',{{badmatch,{error,{zotonic001@9e483e84a766,{already_exists,zotonic001@9e483e84a766}}}},[{zotonic_core,ensure_mnesia_schema,0,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core.erl"},{line,65}]},{zotonic_core_sup,start_link,1,[{file,"/opt/zotonic/apps/zotonic_core/src/zotonic_core_sup.erl"},{line,41}]},{supervisor,do_start_child,2,[{file,"supervisor.erl"},{line,365}]},{supervisor,start_children,3,[{file,"supervisor.erl"},{line,348}]},...]}}}},...}```

**Comment by mworrell** [comment]
The error `{error,{zotonic001@9e483e84a766,{already_exists,zotonic001@9e483e84a766}}}}` means that there is already a node with that name running.

**Comment by heiheshang** [comment]
this is strange because it is the only node that I am trying to run

**Comment by mworrell** [comment]
Check `ps -aux` for any "lost" beam.smp processes. And otherwise kill `epmd`

**Comment by heiheshang** [comment]
`/opt/zotonic $ ps aux
PID   USER     TIME   COMMAND
    1 zotonic    0:00 sh
  462 zotonic    0:00 /usr/local/lib/erlang/erts-9.2.1/bin/epmd -daemon
  977 zotonic    0:00 ps aux`

**Comment by mworrell** [comment]
Weird. Maybe `epmd` is confused (it holds the registry of all Beam nodes).

**Comment by mworrell** [comment]
hmm, what might also be the case (looking at the stack trace) is that the `zotonic001@9e483e84a766` is in fact the directory for the mnesia files and that there is a permission issue. Check `apps/zotonic_core/priv/mnesia/` for the per-node directories and their permissions.

**Comment by heiheshang** [comment]
`zotonic001@4ccc7b48a453# ls -l
total 20
-rw-r--r-- 1 zotonic zotonic  163 Apr 16 17:12 DECISION_TAB.LOG
-rwxrwxrwx 1 zotonic zotonic    8 Apr 16 08:36 filezcache_log_entry.DCD
-rw-r--r-- 1 zotonic zotonic  102 Apr 16 17:12 LATEST.LOG
-rwxrwxrwx 1 zotonic zotonic 7374 Apr 16 17:11 schema.DAT`

**Comment by mworrell** [comment]
You can remove the whole `priv/mnesia` directory and then try again.

It only holds temp data and email administration.

**Comment by heiheshang** [comment]
I tried it many times

**Comment by mworrell** [comment]
The weird thing is that the following test should return `true`.

```erlang
case filelib:is_dir(Dir) andalso filelib:is_regular(filename:join(Dir, "schema.DAT")) of
```

In zotonic_core.erl, line 63.

Could you check the results of those tests?

**Comment by heiheshang** [comment]
Hm
`filename:join(Dir, "schema.DAT")`
return 
/opt/zotonic/_build/default/lib/zotonic_core/priv/mnesia/zotonic001@4ccc7b48a453/zotonic001@4ccc7b48a453/schema.DAT

**Comment by heiheshang** [comment]
`mnesia_dir()`
return
`/opt/zotonic/_build/default/lib/zotonic_core/priv/mnesia/zotonic001@4ccc7b48a453/zotonic001@4ccc7b48a453`

**Comment by mworrell** [comment]
Twice?

That is interesting. I will check.

**Comment by mworrell** [comment]
I am not sure why you get the error, it might be a symptom of another error (zotonic_core app restarting). I have made a change that should prevent adding the node name twice.

Could you try with this change (pull master)?

**Comment by heiheshang** [comment]
fine, everything works

**Comment by mworrell** [comment]
Thanks!
