### ISSUE TITLE
Fontawesome and material design paths to fonts are wrong.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2050]
We bumped on a similar bug to #939 with font-awesome. 

The css file contains relative paths to font files which do not work when the css files are concatenated.

The url below will 404 because the path to the font is relative.

```
https://gotokoala.com/lib-min/css/main~logon~/font-awesome-4/css/font-awesome.min~/material-design/fonts/fontawesome-webfont.woff?v=4.2.0
```

Should a similar update procedure like the one in bootstrap be put in place?

**Comment by mworrell** [comment]
I tend to update the source files for font awesome and then let the css files be rebuilt. Did we for an update which didn't do this?

**Comment by mmzeeman** [comment]
There was a relative path in the css file somewhere. So I guess not.

**Comment by mmzeeman** [comment]
The following css files contain relative pathnames.

`font-awesome-4/css/font-awesome.css` and `material-design/css/material-design-iconic-font.css`

Fontawesome 3 looks fine.
