### ISSUE TITLE
Moreresults shows double results (sometimes)

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2053]
So there is a strange bug in the showmoreresults action. I two of our production sites (that we are aware of) it gives a result back with one or two resources that are already in the loaded results before loading in the new ones. I have an example array from a debug in the action:

`14:59:06.582 [info] DEBUG: action_base_moreresults:113 [17245,17548,17559,17567,17521,17634,17562,17563,17677,17560]`
And the next one
`14:59:08.431 [info] DEBUG: action_base_moreresults:113 [17560,17678,17565,17642,17556,17549,17645,17669,17644,17633]`

Here you can see that the last one in the array is the first one in the next array. It is not always the first one, seems to be random.

**Comment by mworrell** [comment]
This might also be an artifact of an *unstable* order for the underlying SQL query.

If two or more records return the same score (or have the same sort key), then the order of those records will be undetermined.

What query is the source of these results?

**Comment by DorienD** [comment]
```
{% with m.search[{query
    cat_exact="news"
    page=q.page
    sort="-rsc.publication_start"
    pagelen="6"
}] as result %}
```

**Comment by DorienD** [comment]
For a client, it happens from 5th time we click the button, but sometimes this also changes.

**Comment by mworrell** [comment]
Probably there are articles with the same publication start date.
This happens with automatic batch imports, or manually set dates.

You can add an additional sort term:

```
{% with m.search[{query
    cat_exact="news"
    page=q.page
    sort="-rsc.publication_start"
    sort="-rsc.id"
    pagelen="6"
}] as result %}
```

This places the newest of the same batch on top.
This will be stable, as the `id` is unique.

`rsc.created` should be quite unique too, except if there are imported items, which have lower resolution of the creation date and might cluster around the same date as well.

**Comment by DorienD** [comment]
I will check this

**Comment by DorienD** [comment]
This works, should't we make this standard? So always add en extra sort on `rsc.id`? @ddeboer

**Comment by mworrell** [comment]
If there are no sort terms then *query* adds the `-rsc.id`:

```
            case z_utils:is_empty(S#search_sql.order) of
                true -> add_order("-rsc.id", S);
                false -> S
            end;
```

We might want to consider always adding this term (if there is no sort on rsc.id yet).  /cc @ddeboer

**Comment by mworrell** [comment]
Closing for now, you can file a change request for the order, if you want.
