### ISSUE TITLE
Secure storage for server side secrets on client

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2064]
We need a method to securely store server side secrets for the client.

Proposal is:

 * Use the client's `sessionStorage`
 * Store encrypted information
 * Mirror the information on the server (client is authoritative)
 * Lifetime of server storage depends on regular *keep-alive* pings from the client

Questions:

 * Use a CRDT or always update *via* the client?

Example:

 * mod_signup xprops (session thing, might need storage on client or passing using url)

**Comment by onnet** [comment]
Hi @mworrell 
Here is my use case to continue zotonic-users group's thread:

I do not use CMS functionality of Zotonic, nor Postgres db.
I use Zotonic as a framework so far.

Therefore it is not about Zotonic users, but users logged in with third party API creds:
- on sign in client posts user credentials;
- Zotonic receives creds;
- using these creds Zotonic obtains auth token, user role and other ids at third party API and stores it in session;
- using ids and auth token Zotonic takes data from third party apis and dbs (mysql) and exposes it at dashboard;
- on sign out Zotonic flushes auth_token and ids from sesion and finishes this session.

Regards,
Kirill

**Comment by mworrell** [comment]
@onnet that is indeed a bit different use case. So you don't use the authentication modules at all?

The *secure client storage* method above could work, except that you want to have the client information on page load. Which seems to be more compatible with the way mod_authentication uses the authentication cookie.

Your user credentials, are they a username/password combination?

Maybe we can hook into mod_authentication and use the provided mechanisms to store special authentication attributes in the session cookie.

**Comment by mworrell** [comment]
BTW, do you use the psql db at all or are you running without db connection (like zotonic_status et al)

**Comment by onnet** [comment]
@mworrell 

It is username/password/account_name in the very beginning.
And md5('username:pasword)/account_name Posting to this API https://github.com/2600hz/kazoo/blob/master/applications/crossbar/doc/user_authentication.md

Here is the actual code of sign-in: https://github.com/onnet/zotonic_mod_kazoo/blob/master/src/kazoo_util.erl#L527-L569

I do not use Db at all, just take variables from vars file.
https://github.com/onnet/zotonic_mod_kazoo/blob/master/src/kazoo_util.erl#L533

**Comment by mworrell** [comment]
Cool. Am checking the mod_authentication, we should be able to use the authentication cookie methods.

The authentication cookie is a `SameSite=strict` cookie though.  So navigating to the site from another site will not pass the cookie, only navigating (and requests within) will pass the cookie to the server.

Is this compatible with your usage?

**Comment by onnet** [comment]
@mworrell lgtm :)

**Comment by mworrell** [comment]
Am looking at a solution to the generic case:

 * Secrets used by the server
 * Client and server share some settings (id's etc)
 * Server needs secrets & settings on page navigation and mqtt requests

Either:

1. pass the data with every request (we will need a cookie), or
2, use a _session like_ storage solution that is replicated on the client and the server, possibly using a CRDT and a token on a cookie
3. Set some data in cookies from/on the server (m_client_cookie_storage). This can behave differently on page requests (set-cookie) and MQTT requests (call client code to update cookie).

Solution (3) would work quite well in this particular use case as it is not much data.  For secure storage of secrets, the cookie values could be encoded and signed by the server.

I personally like a cookie like solution as it still places all state on the client and keeps the server stateless.

/cc @mmzeeman

**Comment by mworrell** [comment]
Of course, the current authorization cookie is also a client-stored secret that is signed by the server. Option (3) generalizes this kind of storage.
