### ISSUE TITLE
Add comet / SSE fallback for MQTT connections

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2067]
Add comet/post fallback for MQTT connection  (if the websocket fails to connect)

**Comment by mworrell** [comment]
Maybe use: https://github.com/Yaffle/EventSource

**Comment by mworrell** [comment]
We investigated the Websocket responses in our logs.

Between 0.1 and 0.4% of the connections fail with a 200 http result (instead of 101 upgrade).

These are from:

 * Opera Mini browsers
 * Facebook IP addresses, maybe some proxy?
 * Corporate firewall/security solutions
 * Some other proxy at some educational institution

As Opera Mini is not functional anyway we can safely skip supporting that browser. The FB seems to have some connection with Opera, so we disregard that one as well.

Leaves the corporate firewalls and non-functional proxies.

As those are an extreme minority of the requests we propose to do **nothing** and only show a message that we have connectivity issues and fall back to anonymously browsing of the statically served HTML.

**Comment by mworrell** [comment]
@arjan en @ddeboer, what is your opinion and/or experience?

**Comment by mmzeeman** [comment]
I <3 the ostrich algorithm (when applicable)

**Comment by mworrell** [comment]
Closing, as we will only use the ws connection
