### ISSUE TITLE
Embedding vimeo video with url restrictions doesnt import preview

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2082]
The embed url option doesn't import a preview when there are url restrictions. 

Steps:

1. Vimeo video add site to where can this be embedded (privacy settings)
2. Embed url on that domain
3. Video gets embedded but doesn't' show a preview.

I think this is a bug because we are embedding from the url where the video is restricted to.

**Comment by mworrell** [comment]
It looks like some funny edge case.

The server is fetching the image, not the browser. 
Apparently Vimeo doesn't like us fetching the image if there are restrictions.

Maybe it could work if we set a referrer in the request.

Could you send me (privately) an example?
Then I can test if setting the referrer would help.

**Comment by mworrell** [comment]
Just tested it with the details @DorienD provided.

The video info api gives a 404 for the example video.
With the `Referer` header set to the website embedding the video it als returns a 404.

I assume that only with an API key associated with the account that owns the video we can fetch the information.

**Comment by mworrell** [comment]
@DorienD can you send me (privately) the age that embeds the video?  Then we can check there in more detail.

**Comment by mworrell** [comment]
Ping @DorienD

**Comment by DorienD** [comment]
We can close this issue

**Comment by mworrell** [comment]
ok, closing :)
