### ISSUE TITLE
Getting the upload button in the new modal

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2084]
The new new_find modal now provides the upload button only when the category or predicatie is media (or its children). But there are some scenario's where you do want to upload a file when it's not a child of media.

**Comment by mworrell** [comment]
Yes, this is a known issue.

There are some assumptions in the admin about the fields possible with some categories.
You will see the same problem if you make a new page in that category, on the edit page there won't be a _media_ section where you can upload (or embed).

Other examples of assumed domain knowledge are `person` and `media`.

We could do two things:

 1. Allow overrule of the template (sounds messy, is fragile, and will result in lots of overruled templates).
 2. Add some capabilities/configuration to the categories and let the UI decide what to show using that information.

@ddeboer I think you would also prefer option 2?

I am a bit unsure how option 2 should be done.  I think we should make it possible to extend these capabilities, examples that come to my mind are:

 * Medium yes/no
 * Password (aka logon) identity possible
 * Custom properties (and their types)
 * Start and end date
 * Name fields

This could have some defaults for standard categories.
It should also be inherited using the category hierarchy.

**Comment by mworrell** [comment]
@ddeboer @DorienD ping for comments on the above

**Comment by DorienD** [comment]
I agree with option 2, i've been thinking if there is another option but i think making some configs available in the category is the best setup. About your list.

1. Medium yes/no - agree
2. Password - agree
3. Custom properties - Why would this be needed in the new_find modal?
4. Start/End date - Why would this be needed in the new_find modal?
5. Name fields - I guess this is applied when you have option 2 already?

**Comment by mworrell** [comment]
I was also thinking of more radical approach and redo-ing that"new resource" dialog once again.

Basic idea is that we want:

1. Show that other content with the same title/filename/contents exists
2. Make it easy to create a new resource with what has been searched for

My current thinking is:

1. In a "new" tab: list content with the same title, within the selected category
2. In an "upload" tab: list content with same filename or title
3. In a "find" tab: list content matching search string, add button to create new resource in the selected category with the search term as title

What do you think of this option?

/cc @michielklonhammer

**Comment by mworrell** [comment]
And also accept more drag/drop files - like for adding depictions or uploading new media in the media overview.

**Comment by DorienD** [comment]
I've played a bit with the modal in sketch. What do you think about this setup. The new and file upload tab is a very similar in my example, i think it could be the same tab depends a bit on the extra fields needed when uploading multiple files. So i think its nice to have the existing content always on the right side, since i would expect when i'm creating something new the focus is on the new thing you're creating (so its on the left for the LTR readers, maybe this could be the other way around for the RTL readers). 

**New tab**
![new-tab](https://user-images.githubusercontent.com/5102362/108633558-283cc900-7475-11eb-9b00-a949589343e7.png)

**Find tab**
![find-tab](https://user-images.githubusercontent.com/5102362/108633513-dd22b600-7474-11eb-8be9-d41ddb26728f.png)

**Upload tab**
![file-upload-tab](https://user-images.githubusercontent.com/5102362/108633562-2c68e680-7475-11eb-9d73-7c146aabed38.png)

**Comment by mworrell** [comment]
I like it.

Actually, we were thinking alike.  In the current master I have already swapped the create/existing columns.
Your suggestion to make a separate file upload is also welcome. It is almost the same as the other one, but people are looking for the _upload_ functionality, as that is what they are used to.

<img width="915" alt="Screenshot 2021-02-23 at 09 19 43" src="https://user-images.githubusercontent.com/38268/108817534-50811080-75b8-11eb-947c-8f8c30e77fec.png">

ping @michielklonhammer

**Comment by mworrell** [comment]
Ideally I would also like to match on the filename to see if a file has been uploaded before.

**Comment by DorienD** [comment]
Filename matching would be an awesome improvement. Maybe it could even show an growl message with "_this file has already been uploaded before_". I would like to see the title in the left bar, not over the whole width of the modal.
