### ISSUE TITLE
tinymce doesn't work when zotonic is setup with sub-domain-comet

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#209]
The problem is cross-(sub)domain javascript. To enable it you need to edit modules/mod_base/lib/js/modules/tinymce3.4.3.2/tiny_mce_popup.js

and change the line containing document.doman = "your-domain-name"

It would be nice it was done automatically.

**Comment by mworrell** [comment]
Sub domain comet is removed, closing this issue,
