### ISSUE TITLE
Upgrade postgres driver

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2096]
Our current postgres driver is five years old now. 

I would like to upgrade it because I want to use the JSONB datatypes for a side project I'm working on. The JSONB datatypes are now supported by Postgres 9.5 and up. (Basically all maintained versions of Postgres). The current driver we have (`2.0.0`) does not support this datatype.

`epgsql` supports the JSONB datatype from version `3.2.0` which is 3 years old already.

**Comment by mworrell** [comment]
There is a new release coming up as well.

But please, do upgrade to the 3.x 👍

**Comment by mworrell** [comment]
Has been upgraded.
