### ISSUE TITLE
I have repented from the repository and now my code is not working I can not understand how what happened?

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2104]
`17:33:41.607 [error] stop_request 500 (reason {function_clause,[{cowmachine_util,normalize_content_type,[{<<"text/html">>,provide_content}],[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_util.erl"},{line,146}]},{cowmachine_util,'-normalize_provided/1-lc$^0/1-0-',1,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_util.erl"},{line,144}]},{cowmachine_util,choose_media_type_provided,2,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_util.erl"},{line,55}]},{cowmachine_decision_core,decision,3,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_decision_core.erl"},{line,319}]},{cowmachine_decision_core,handle_request,2,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine_decision_core.erl"},{line,36}]},{cowmachine,request_1,5,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine.erl"},{line,72}]},{cowmachine,request,4,[{file,"/opt/zotonic/_build/default/lib/cowmachine/src/cowmachine.erl"},{line,55}]},{cowboy_stream_h,execute,3,[{file,"/opt/zotonic/_build/default/lib/cowboy/src/cowboy_stream_h.erl"},{line,249}]}]})
`

**Comment by mworrell** [comment]
Hi @heiheshang,

We are a bit in flux now, merging in all the changes for MQTT and Cotonic (frontend) integration.

I assume the above request came from one of your own controllers?
One of the changes is a simplification of controllers.

See for example this controller:

https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_base/src/controllers/controller_template.erl#L30

You can see the `content_types_provided` now just returns a list of mime types.  They can be binary or already be split like `{<<"text">>,<<"plain">>,[{<<"charset">>,<<"utf8">>}]}`

The new function `process` is called to process the request, it is passed the selected content-type and the content-type of the payload (if any).

This makes it easier to write controllers that accept and provide different kinds of content.

**Comment by heiheshang** [comment]
Yes, I am processing a post request, how should I work now?

**Comment by mworrell** [comment]
If you want to continue on the tip of master, then you need to change your controllers.

This version is considered unstable at the moment (we are working on some issues, see issue tracker).

You can also use the version just before we merged 'cotonic' in and wait a bit. That should be at f5c0f63be9c720cf7bcc0f13675cf254fb9525de

**Comment by heiheshang** [comment]
I understand what needs to be changed, but I don’t know how

**Comment by mworrell** [comment]
You could do:

     git checkout f5c0f63be9c720cf7bcc0f13675cf254fb9525de

Then you are at the point just before we merged cotonic and with it the changes to the controllers.

Though the master will stabilize in the coming days/weeks. So you could also think of changing your controller to the new callbacks.  I will write a short guide to the new controller structure.

**Comment by heiheshang** [comment]
I'm completely confused, I worked in the master, now I switched to the 0.49.2 branch, everything is not the same, the site and the controllers are not being made the same, in which branch I cannot work better

**Comment by mworrell** [comment]
If you were on master and it worked, then stay on master.

As then you managed to cover most changes for the 0.x -> master upgrade already.

The hash I gave above is on the master branch, just before we merged cotonic in.

**Comment by heiheshang** [comment]
well, I'm waiting for a stable branch, cotonic is really an interesting technology

**Comment by mworrell** [comment]
Closing for now - the master is building and we are running test sites.
