### ISSUE TITLE
Easy removal for images within RTE

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2105]
Currently when you want to delete an image from an RTE field you need to click behind the image and use backspace to delete it.
Sometimes when the html is not really "clean" this shows strange behaviour, because the backspace actually remove an empty element which cannot be seen.
Therefore the user does not understand what is happening.

For some users it seemed more logical to click on the image to delete it, something you now only do for editing.
Maybe it would be a good idea to add a delete button to the media properties popup for that?

**Comment by mworrell** [comment]
Makes complete sense to me.

Let's go for a  _Remove_ button in the properties dialog.

**Comment by mworrell** [comment]
@loetie I have added a 'delete' button in the zmedia properties dialog.  If you test then you will need to force-reload the plugin code (as it is cached a bit longer in your browser).

**Comment by DorienD** [comment]
This is a really nice small tweak to make it easier for the users!
