### ISSUE TITLE
Uploaded images in depiction first in list in RTE

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2106]
With the previous connect dialog you had the attached media tab, media that was already linked to the resource. Would it be possible to add those resources on the top of the find list in the new dialog connect modal?

![Screenshot 2019-06-21 at 14 00 17](https://user-images.githubusercontent.com/5102362/59921118-003dcc80-942d-11e9-90ce-5e0c97e7206e.png)

**Comment by mworrell** [comment]
This is especially an issue for attaching known images (and connections) in the RTE editor, I assume it is not an issue for any other connection list?

**Comment by mworrell** [comment]
If it is only for RTE then we can (per default) the list of current connections insert at the top of the connection dialog (if not searching on text).

**Comment by mworrell** [comment]
Actually, in master i have now the extra tab, as pictured above.
Will check if we can merge that back into the 0.x

**Comment by mworrell** [comment]
See #2152

**Comment by mworrell** [comment]
Merged #2152 - issue resolved.
