### ISSUE TITLE
Application zotonic_launcher exited with reason: shutdown

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2108]
`20:46:17.259 [info] Config files used:
20:46:17.268 [info] - /etc/zotonic/erlang.config
20:46:17.268 [info] - /etc/zotonic/zotonic.config
20:46:17.268 [info] ================
20:46:17.869 [info] HTTP server listening on IPv4 any:8000
20:46:17.878 [info] SMTP server listening on 127.0.0.1:2525
20:46:17.935 [info] [inotify] Starting inotify file monitor.
20:46:17.999 [error] gen_server zotonic_listen_http terminated with reason: call to undefined function ranch:start_listener/5 from zotonic_listen_http:start_http_listeners_ip4/2 line 136
20:46:18.000 [error] CRASH REPORT Process zotonic_listen_http with 0 neighbours crashed with reason: call to undefined function ranch:start_listener(zotonic_http_listener_ipv4, ranch_tcp, [{connection_type,supervisor},inet,{port,8000},{backlog,500},{num_acceptors,100}], cowboy_clear, #{connection_type => supervisor,env => #{},middlewares => [cowmachine_proxy,z_sites_dispatcher,...],...})
20:46:18.009 [info] gen_smtp_server starting at zotonic001@ca51bd0d5f1f
20:46:18.109 [info] gen_smtp_server listening on {127,0,0,1}:2525 via tcp
Terminating due to shutdown
20:46:18.111 [error] Supervisor zotonic_launcher_sup had child zotonic_listen_http started with zotonic_listen_http:start_link() at <0.365.0> exit with reason call to undefined function ranch:start_listener(zotonic_http_listener_ipv4, ranch_tcp, [{connection_type,supervisor},inet,{port,8000},{backlog,500},{num_acceptors,100}], cowboy_clear, #{connection_type => supervisor,env => #{},middlewares => [cowmachine_proxy,z_sites_dispatcher,...],...}) in context child_terminated
20:46:18.112 [info] Application zotonic_launcher started on node zotonic001@ca51bd0d5f1f
20:46:18.118 [info] HTTP server listening on IPv4 any:8000
20:46:18.118 [error] gen_server zotonic_listen_http terminated with reason: call to undefined function ranch:start_listener/5 from zotonic_listen_http:start_http_listeners_ip4/2 line 136
20:46:18.118 [error] CRASH REPORT Process zotonic_listen_http with 0 neighbours crashed with reason: call to undefined function ranch:start_listener(zotonic_http_listener_ipv4, ranch_tcp, [{connection_type,supervisor},inet,{port,8000},{backlog,500},{num_acceptors,100}], cowboy_clear, #{connection_type => supervisor,env => #{},middlewares => [cowmachine_proxy,z_sites_dispatcher,...],...})
20:46:18.119 [error] Supervisor zotonic_launcher_sup had child zotonic_listen_http started with zotonic_listen_http:start_link() at <0.373.0> exit with reason call to undefined function ranch:start_listener(zotonic_http_listener_ipv4, ranch_tcp, [{connection_type,supervisor},inet,{port,8000},{backlog,500},{num_acceptors,100}], cowboy_clear, #{connection_type => supervisor,env => #{},middlewares => [cowmachine_proxy,z_sites_dispatcher,...],...}) in context child_terminated
20:46:18.119 [error] Supervisor zotonic_launcher_sup had child zotonic_listen_http started with zotonic_listen_http:start_link() at <0.373.0> exit with reason reached_max_restart_intensity in context shutdown
20:46:18.216 [info] Application zotonic_launcher exited with reason: shutdown`

**Comment by mworrell** [comment]
Is this a clean build?

Be careful not to upgrade ranch to the newest version beyond what is in our lock file.

**Comment by heiheshang** [comment]
the zotonic build is still not that simple

**Comment by mworrell** [comment]
Yes, ranch changed an (quite essential) API in one of their 1.x releases.

We will adapt our calls when we upgrade the Cowboy version we are using.
Hope that also fixes some issues we had with http2 connectivity.
