### ISSUE TITLE
Compile-Error on mqtt_sessions

### ISSUE THREAD

**Issue by carusoe11** [zotonic/zotonic#2109]
**make produces compiling error:**

Compiling _build/default/lib/mqtt_sessions/src/mqtt_sessions.erl failed
_build/default/lib/mqtt_sessions/src/mqtt_sessions.erl:84: syntax error before: ':='

_build/default/lib/mqtt_sessions/src/mqtt_sessions.erl:94: type session_options() undefined

-------------------------------------------------------------
Erlang 18.3 OTP_VERSION [erts-7.3]
Kernel Version: 4.15.0-51-generic
Operating System: Linux Mint 18.3
OSType: linux
Architecture: x86_64

**Comment by mworrell** [comment]
I have just merged an update to the MQTT handling.

Could you try again?

BTW we are now requiring OTP 19 or later and stopped testing on 18.

**Comment by mworrell** [comment]
On a separate note: the current master is a bit in flux whilst we are merging in all changes to the MQTT handling and other issues.

**Comment by mworrell** [comment]
Closing for now, please reopen if you still experience the problem.
