### ISSUE TITLE
zotonic does not see the site, but it works

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2112]
`16:58:58.621 [error] gen_server 'z_module_manager$nahodka' terminated with reason: {{badmap,{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}},[{maps,keys,[{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}],[]},{z_module_manager,handle_upgrade,1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,849}]},{z_module_manager,handle_cast,2,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,630}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{...}]},...]}
16:58:58.621 [error] CRASH REPORT Process 'z_module_manager$nahodka' with 0 neighbours crashed with reason: {{badmap,{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}},[{maps,keys,[{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}],[]},{z_module_manager,handle_upgrade,1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,849}]},{z_module_manager,handle_cast,2,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,630}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{...}]},...]}
16:58:58.623 [error] Supervisor 'z_site_sup$nahodka' had child z_module_manager started with z_module_manager:start_link([{title,"nahodka"},{enabled,true},{dbschema,"public"},{dbhost,"postgres"},{install_modules,[mod_base,...]},...]) at <0.638.0> exit with reason {{badmap,{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}},[{maps,keys,[{module_status,nahodka,nahodka,<0.690.0>,restarting,1562224693,1562224693,undefined,0}],[]},{z_module_manager,handle_upgrade,1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,849}]},{z_module_manager,handle_cast,2,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_module_manager.erl"},{line,630}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{...}]},...]} in context child_terminated`

**Comment by mworrell** [comment]
Thanks for the report!

Is this on the newest master?

**Comment by heiheshang** [comment]
* (detached from f5c0f63) f5c0f63 docs: 0.49.1 release notes

**Comment by mworrell** [comment]
That is a quite recent one, thanks!

**Comment by mworrell** [comment]
I think this has been fixed on the newest master.

**Comment by heiheshang** [comment]
which branch can I watch?

**Comment by mworrell** [comment]
The tip of master is stable now. It is now running on the newest Cowboy 2, and passes the type checks of Dialyzer.

We are working there to get all the 1.0 milestone issues fixed.

**Comment by mworrell** [comment]
Installed new sites using the new escripts.

Didn't see re-occurences of this error, so I assume it is now fixed.
