### ISSUE TITLE
Check number of schedulers on startup

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2113]
If there is only a single scheduler then the beam crashes.

We need to check for >= 2 schedulers on startup.

This might also be checked in the startup shell scripts, which could add a `+S 2:2` or `+S 4:4` flag.

```=erl_crash_dump:0.5
Fri Jul  5 15:10:53 2019
Slogan: erl_child_setup closed
System version: Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [hipe] [kernel-poll:true]
Compiled: Fri Feb 23 20:13:12 2018
Taints: erl_tracer,zlib
Atoms: 2257
Calling Thread: scheduler:1
=scheduler:1
Scheduler Sleep Info Flags: 
Scheduler Sleep Info Aux Work: 
Current Port: #Port<0.0>
Run Queue Max Length: 0
Run Queue High Length: 0
Run Queue Normal Length: 1
Run Queue Low Length: 0
Run Queue Port Length: 0
Run Queue Flags: NONEMPTY_NORMAL | NONEMPTY | EXEC
Current Process: 
=memory
(...)
```

**Comment by mworrell** [comment]
Looks like a crash of the BEAM.

In the top I see `smp:1:1`, so you are running with a single scheduler only.  This is problematic for the password verification (which uses some heavy calculation).  It is better to run with at least two schedulers.

**Comment by mworrell** [comment]
Can you try again with more schedulers and see if that helps.

Also, is there a crash log?

**Comment by heiheshang** [comment]
I can not anymore. I have already encountered this problem, I do not remember how I solved it. Probably need to change the options at the start of the Erlang

**Comment by mworrell** [comment]
I remember that we once discussed the SMP settings, try to set those.

The `erl` command line option is (for example) `+S 4:4`  which sets 4 active schedulers.

**Comment by heiheshang** [comment]
I think you can fix it in the zotonic_launcher in the zotonic-debug

**Comment by mworrell** [comment]
Problem is that on bigger machines (6+ cores) we want to be able to use all cores.
Only on single core machines we should force this, so it will need some extra scripting.
