### ISSUE TITLE
Add the possibility to configure CSRF option on the session cookie.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2114]
I would like to have the possibility to change the CSRF option (same-site) for a site.

The current setting is a great default. But I would like to override it does not set the same-site property.

Does anyone want an option to set it to strict?

**Comment by mworrell** [comment]
`Strict` is a bit tricky for the 0.x Zotonic.  As we set a `sid` cookie the moment you arrive without one. With `strict` the cookie wouldn't be present on any cross-site navigation to the Zotonic site, and we would override any existing cookie with a new fresh one.

If the site is only used for `admin` like activities then it might actually be good security.

On the master we are already using `Strict` as the page will reload itself if it finds a cookie. And the cookie is set by the page calling into the `controller_authentication`, so the normal page controllers are no setting any cookies.

**Comment by mworrell** [comment]
@mmzeeman do you want this for 0.x or also for master?

**Comment by mmzeeman** [comment]
At the moment just for 0.x. We have no plans to move our site to master (yet).

The problem for us is that the current setting (lax) can cause a login loop. Especially when the user has a rememberme cookie. This is specific to our situation.

**Comment by mmzeeman** [comment]
This issue can be closed. For 0.x it makes sense to only support samesite: lax.
