### ISSUE TITLE
Access mod_admin_config makes user full admin

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2117]
If you want to give a user group access to the configuration. (aka mod_admin_config) they also get treated as full admin user. This does not seem a logical consequence from giving access to the config.

Why does it work like this and is there a option to only give access to de config screen without making them admin?

**Comment by mworrell** [comment]
No it is not possible to give someone full access to the site configuration and not owner of the system.

It is too easy to get access to other parts of the system via the various configuration options, so best is to make it clear that _if_ you can change the configuration _then_ you are an administrator of the site.

**Comment by mworrell** [comment]
If you want to enable someone to edit some parts of the configuration then you can make a specific interface where you can edit those (_and only those_) options. This should be guarded by code checking white lists of the options allowed to be changed.

**Comment by mworrell** [comment]
Hope this answered your question, closing for now.
