### ISSUE TITLE
mod_development doesn't show whole project path

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2118]
When showing paths in the mod_development module the paths are correct for zotonic modules but when the template is from the project it hides some parts. I've included a screenshot:

![Screenshot 2019-07-19 at 12 31 18](https://user-images.githubusercontent.com/5102362/61529440-990e3a80-aa21-11e9-8c9c-62508f674903.png)

**Comment by DorienD** [comment]
There was no f in the projectname :)

**Comment by mworrell** [comment]
Mysterious `f` it is 🙃

**Comment by mworrell** [comment]
The path is always truncated to remove the zotonic root, this is wrong if the template is not located in the zotonic directory.

```erlang
relpath(FilePath) ->
    Base = os:getenv("ZOTONIC"),
    lists:nthtail(1+length(Base), FilePath).
```

**Comment by DorienD** [comment]
I still see only a part of the path?
![Screenshot 2019-11-06 at 11 45 05](https://user-images.githubusercontent.com/5102362/68291806-e5da5780-008a-11ea-8b38-333cb0dfd5b7.png)

**Comment by mworrell** [comment]
There was another occurrence of the same function. Should be ok now.
Can you test again with the 0.x?

**Comment by DorienD** [comment]
Yes! Works :D
