### ISSUE TITLE
When filtering on pages overview you cannot create a new resource

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2119]
Steps:

1. Filter on a category on the pages overview
2. Create a new rsc
3. Error because i cannot select a category

Screenshot:

![Screenshot 2019-07-19 at 13 42 05](https://user-images.githubusercontent.com/5102362/61532756-2e61fc80-aa2b-11e9-8c14-ce8e767d4d68.png)

**Comment by mworrell** [comment]
I failed to reproduce this problem.

Maybe you can't select a category because you are not allowed to insert into the selected content group?

**Comment by DorienD** [comment]
I'm the admin user, i will send you a video to proof this issue :)

**Comment by mworrell** [comment]
From the video I see that this site apparently doesn't use ACL User Groups and Content Groups.

Which ACL does the site use?
