### ISSUE TITLE
Pagination with id.o.haspart

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2124]
We would like to have pagers with the `id.o.haspart` (or other edges). The `moreresults` action seems to be able to handle `id.o.haspart` results as `m.search` results. But the pager does not.

**Comment by mworrell** [comment]
If I understand correctly, then your request is to let the pager handle as well:

 * A list of integers (resource ids)
 * A `{rsc_list, list()}` tuple

**Comment by DorienD** [comment]
Exactly!

**Comment by mworrell** [comment]
If you are doing the paging manually then you will also need to:

 * Supply the `page` number and `pagelen` to the pager
 * Slice the result yourself (using the `split` filter) for displaying the current page

**Comment by mworrell** [comment]
@DorienD does this fix your problem?
