### ISSUE TITLE
Self-Signed Certificates and switch Zotonic versions

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2131]
Safari (and other browsers) have become more sensitive about arbitrary self-signed certificates.

Currently we generate these separately for every site.

Which means that switching between Zotonic versions, cleaning the site, etc. might cause a re-generation of the self-signed certificate.

This gives a problem, as the browser now thinks (rightfully) that the certificate doesn't match the site anymore.

We might be able to reduce this problem by having a single self-signed certificate for all the sites.

This might be placed in `~/.zotonic/ssl/...` (or whatever the Zotonic config directory is).

/cc @ddeboer @arjan @mmzeeman

**Comment by mworrell** [comment]
Possibility:

 1. Add a self-signed certificate in `~/.zotonic/security/ssl/self-signed/...`
 2. Use this self-signed certificate as the root certificate for all self-signed site certificates.

Now each site can have the correct common name and we only need to add this single root certificate to the trust chain of the browser

**Comment by ddeboer** [comment]
What are the arguments against the simplest solution, i.e. to use a single self-signed cert for all sites?

Security shouldn’t really be an issue, because browsers will still give a warning about using self-signed certs, so production sites will not be using them.

**Comment by mworrell** [comment]
The same cert for all sites?  I am ok with that.  @mmzeeman mentioned something about that he prefers the *common name* fits the name of the site.  If we would like to have that then we need a cert per site (of per hostname?).

In principle it is ok to have the same self-signed certificate for all sites on a server. The main issue is switching the certificate when switching Zotonic versions.  Especially on development machines.

**Comment by mworrell** [comment]
Would we like to store all certificates together in a single directory, or use the current setup with a sub-directory in the `priv` directory?

**Comment by mmzeeman** [comment]
I don't know if it will work if you have a certificate with no common name or alternatives in it. My guess was that browsers use the domain-name of the site to select a certificate from the keychain tool.

The main problem is that Safari currently doesn't show the [Yes] [No] dialog anymore. This means that you have to manually add the certificate to your keychain with the Keychain Access Tool.

This is now the error message Safari displays:

<img width="403" alt="Screenshot 2019-07-30 at 10 19 55" src="https://user-images.githubusercontent.com/1024972/62113012-1e141200-b2b4-11e9-92a0-93b1d8cd74ff.png">

As developer you now have to locate the crt file, and drag to the keychain access window. After this, the certificate is not trusted. (red cross)

<img width="549" alt="Screenshot 2019-07-30 at 10 20 30" src="https://user-images.githubusercontent.com/1024972/62113090-40a62b00-b2b4-11e9-8e81-6db199545e09.png">

You have to open the Trust tab in the keychain tool, and select it to trust for SSL connections.

<img width="494" alt="Screenshot 2019-07-30 at 10 20 48" src="https://user-images.githubusercontent.com/1024972/62113155-60d5ea00-b2b4-11e9-86a0-4723d975f0c4.png">

**Comment by mworrell** [comment]
We should document this (using your examples).

Also, this is very doable on a local development server.
It is a problem to fetch the .crt from a remote server.

Either we should encourage to use a real domain name for a server (and certificate, possibly via LetsEncrypt module), or we should have some method of fetching or installing the self-signed certificate. 

By having a fixed path for the self-signed certificate, and sharing it between sites, we can make this process easier. (As adding a site doesn't add a new self-signed certificate.)

**Comment by mworrell** [comment]
Here is an article about how to install a self-signed certificate in Chrome. We might want to check against the newest Chrome build.

https://deliciousbrains.com/https-locally-without-browser-privacy-errors/

Also need to check if we correctly add the SAN for self-signed certificates (and if not then add it).

**Comment by mmzeeman** [comment]
I just updated firefox on my development machine in the office. This was the warning I got when I tried to access the local site with a self signed certificate.

![Screenshot from 2019-07-31 16-21-19](https://user-images.githubusercontent.com/1024972/62220870-0f5f5500-b3b1-11e9-8c76-ee3dc90418b5.png)

I don't know how to accept the self-signed certificate at this moment.

**Comment by mmzeeman** [comment]
Oh, this is because the security on `.local` is upgraded. When the test site is on the `.test` domain it works as expected.

**Comment by mworrell** [comment]
That is strange.  `.local` is also used for _Bonjour_ urls.  Or is that the reason, that Firefox checks if the `.local` maps to a bonjour IP?

**Comment by mworrell** [comment]
I discussed this issue with @CyBeRoni and we got to the following conclusion:

 * Add a single self-signed CA in `~/.zotonic/security/ca-self-signed/`
 * Use this to sign all self-signed certificates for the sites

With this setup you only need to add the CA once to the Keychain.
This CA is then used to identify all Zotonic (1.x and later) servers running on that particular machine (and OS user account).

Open for discussion is if we want to store the site certificates in that store as well.
It might be useful to add them there per hostname, so that you can re-use a previous certificate after re-cloning an old project.

Only problem is then with moving a site between machines, as these certificates need to be copied as well and are not contained in the site folder. Moving sites between machines without moving the whole `~.zotonic` folder seems a rather rare event to me, so I am ok with having all security stuff in one place.

**Comment by karlsson** [comment]
I think I found a workaround for Firefox to be able to make an exception for https://mysite.dev:8443/ and accept the self-signed certificate by setting "network.stricttransportsecurity.preloadlist" to false in about:config. Not a final solution maybe, but it helps to access the test site on my localhost.

**Comment by mworrell** [comment]
Now I see it is a “.dev” site.

Google owns that top level domain and added extra security on it.

Try a “.test”, those are still ok.

**Comment by karlsson** [comment]
Thanks. That works.
The command ./bin/zotonic addsite -s blog yoursite will add yoursite.dev.
Shall that be changed to creating yoursite.test? And update of documentation: http://docs.zotonic.com/en/latest/developer-guide/sites.html#guide-create-site .

**Comment by mworrell** [comment]
Good catch, I made a small update at https://github.com/zotonic/zotonic/pull/2149

**Comment by mworrell** [comment]
For using a local CA, see also this blog post https://blog.process-one.net/using-a-local-development-trusted-ca-on-macos/

**Comment by mworrell** [comment]
Guide for openssl CA https://jamielinux.com/docs/openssl-certificate-authority/

**Comment by mworrell** [comment]
After further testing and consideration we concluded:

 * Having a root CA  on dev machines and installed in the keychain is too big risk
 * We will make use of self-signed certificates
 * The certs are stored in the zotonic security directory
 * The self-signed cert MUST have the hostname as CN, otherwise Safari will not start the ServiceWorker
