### ISSUE TITLE
HTTP/2 cipher suite problem

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2135]
It looks like we have to specifiy a cipher suite list which is allowed for http2. Both firefox and chrome are not happy about the provided security.

Running on OTP-20.3

![Screenshot from 2019-08-01 14-31-08](https://user-images.githubusercontent.com/1024972/62299298-f7e9a000-b474-11e9-9a22-86cd10587d05.png)

![Screenshot from 2019-08-01 14-22-30](https://user-images.githubusercontent.com/1024972/62299287-f4561900-b474-11e9-8f78-0282d51f9721.png)

**Comment by mworrell** [comment]
I guess we have to provide a list of ciphers.
This code might be already in Cowboy, just not used by us due to our extra options etc.

**Comment by mworrell** [comment]
I have made a hack in #2136 

It hard-codes a list of allowed ciphers for all tls connections.
This is very rough and temporarily and definitely needs some refinement ...

Could you check this branch for the connectivity problems?

**Comment by mworrell** [comment]
I got the list from http://ezgr.net/increasing-security-erlang-ssl-cowboy/

But I am sure that there should be a more "standard" solution to this problem.

**Comment by mworrell** [comment]
Actually this whole issue might be a specific OTP-20.3 issue:

http://erlang.org/pipermail/erlang-questions/2018-March/095087.html

If so, and if the above patch works, then we might want to hard code the cipher list only on 20.3.

**Comment by mworrell** [comment]
Tested the patch on 20.3, and there it works fine.
