### ISSUE TITLE
Logging in as user check

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2153]
What does this check mean:

`{% if m.acl.is_admin and m.identity[id].is_user and id != m.acl.user and id != 1 %}`

We have to allow the use of `mod_admin_config` to allow editors to log in as another user. And i don't really get that from the if statement above. Is the use of `mod_admin_config` really necessary?

**Comment by mworrell** [comment]
The current user has to be:

 * An administrator (that is user `1`, `sudo`, or an user with `mod_admin_config` permissions)

The resource being edited (`id`) has to be:

 * An user (has username/pw)
 * Not the current user
 * Not the site admin user `1`

**Comment by mworrell** [comment]
So you have to be an administrator to log in as another user, which can't be user 1.

**Comment by mworrell** [comment]
If we would relax this condition then we need to check that the target user has equal or less permissions than the current user. By just allowing administrators perform this action we don't need to check for permission escalation.

**Comment by mworrell** [comment]
I assume you got all the information you needed?

Closing for now.
