### ISSUE TITLE
gen_smtp 0.13.0 has name conflict with OTP 22

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#2160]
zotonic_core uses gen_smtp version 0.13.0 in master branch.
OTP 22 has added a socket module which will shadow gen_smtp (version 0.13.0) application module with the same name. In version 0.14.0 the conflict is resolved.
In order to support OTP 22 eventually, version needs to be updated to at least 0.14.0 in apps/zotonic_core/rebar.config for gen_smtp.

**Comment by mworrell** [comment]
Good catch.

And a bit embarrassing, as I myself made that change and initiated the 0.14 gen_smtp release...

**Comment by mworrell** [comment]
Upgraded and locked the new gen_smtp.
