### ISSUE TITLE
How can I decode mqqt messages from zotonic?

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2162]
How can I decode mqqt messages from zotonic?

**Comment by mworrell** [comment]
In master?

We use the binary encoding of MQTT v5 and for the web pages tunnel that through a websocket connection.

There is also an MQTT connection possible, with and without SSL encryption.

There are Erlang and Javascript decoders for the binary packages.

**Comment by heiheshang** [comment]
which module for Erlang ?

**Comment by mworrell** [comment]
If you have the binary, then you can use `mqtt_packet_map`.
It packs and unpacks MQTT messages from/to Erlang maps.

**Comment by heiheshang** [comment]
does not work 
`mqtt_packet_map:decode(Payload)` 
`<<"{'z_mqtt_payload','am',7143,13~8593838982621~}$">>`
`{error,invalid_packet}`

**Comment by mworrell** [comment]
Ah, you are decoding a packet from the 0.x.
There we use UBF-A encoding of the records.
You can use `z_ubf` to decode those packets.

In the master we switched to MQTT on the wire, i.e. binary encoded MQTT messages. Where in the 0.x we used a serialization of the internal record format.  Your example would decode as a `#z_mqtt_payload{}` record.

**Comment by heiheshang** [comment]
I could not find the z_ubuf file to include in my project

**Comment by mworrell** [comment]
`z_ubf.erl` is inside `z_stdlib`

**Comment by mworrell** [comment]
@heiheshang I hope your question was answered.
