### ISSUE TITLE
docker base /etc/zotonic/erlang.config error

### ISSUE THREAD

**Issue by paladim** [zotonic/zotonic#2166]
<img width="835" alt="Снимок экрана 2019-08-21 в 12 04 05" src="https://user-images.githubusercontent.com/7988473/63410047-d3e20480-c40b-11e9-833b-59193c7477e5.png">

**Comment by mworrell** [comment]
Hi @paladim, could you paste the line 1..20 of the config file here?  Then we can check what is wrong.

**Comment by paladim** [comment]
hi
➜ git clone https://github.com/zotonic/zotonic
➜ cd zotonic 
➜ docker-compose run --service-ports zotonic sh
bin/zotonic debug
compile ...
{"could not start kernel pid",application_controller,"error in config file \"/etc/zotonic/erlang.config\" (19): syntax error before: '['"}
could not start kernel pid (application_controller) (error in config file "/etc/zotonic/erlang.config" (19): syntax error before: '[')

Crash dump is being written to: erl_crash.dump...done
<img width="1580" alt="Снимок экрана 2019-08-21 в 18 19 39" src="https://user-images.githubusercontent.com/7988473/63435533-83d16500-c440-11e9-8ea7-44c84ffcf3c6.png">

**Comment by mworrell** [comment]
Interesting, that looks different from the default `erlang.config.in` file.

Was it edited?

```erlang
 {lager,
  [{handlers,
    [
      {lager_console_backend, [
        {level, info},
        {formatter, lager_default_formatter},
        {formatter_config, [time, color, " [", severity, "] ", {site, [site, " "], ""}, {module, [module, ":", line, " "], ""}, message, "\n"]}
      ]},
      {lager_file_backend, [
        {file, "priv/log/error.log"},
        {level, error},
        {formatter, lager_default_formatter},
        {formatter_config, [date, " ", time, " [", severity, "] ", {site, [site, " "], ""}, {pid, ""}, {module, [{pid, ["@"], ""}, module, {function, [":", function], ""}, {line, [":", line], ""}], ""}, " ", message, "\n"] }
      ]},
      {lager_file_backend, [
        {file, "priv/log/console.log"},
        {level, info},
        {formatter, lager_default_formatter},
        {formatter_config, [date, " ", time, " [", severity, "] ", {site, [site, " "], ""}, {pid, ""}, {module, [{pid, ["@"], ""}, module, {function, [":", function], ""}, {line, [":", line], ""}], ""}, " ", message, "\n"] }
      ]}
    ]},
   {crash_log, "priv/log/crash.log"}
  ]},
```

**Comment by paladim** [comment]
bug in this line of code
https://github.com/zotonic/zotonic/blob/master/Dockerfile.base#L17

**Comment by paladim** [comment]
> Интересно, что он отличается от `erlang.config.in`файла по умолчанию .
> 
> Это было отредактировано?
> 
> ```erlang
> { Лагер , 
>   [{ обработчики , 
>     [ 
>       { lager_console_backend , [ 
>         { уровень , информация }, 
>         { форматировщик , lager_default_formatter }, 
>         { formatter_config , [ время , цвет , " [ " , тяжесть , " ] " , { сайт , [ сайт , "  " ], " " }, { module, [ module , " : " , line , "  " ], " " }, message , " \ n " ]} 
>       ]}, 
>       { lager_file_backend , [ 
>         { file , " priv / log / error.log " }, 
>         { level , ошибка }, 
>         { форматировщик , lager_default_formatter }, 
>         { formatter_config , [ дата , " " , time , " [ " , серьезность , " ] " , { site , [ site , "  " ], " " }, { pid , " " }, { module , [{ pid , [ " @ " ], " " }, модуль , { функция , [ " : " , функция ], " " },{ строка , [" : " , line ], " " }], " " }, "  " , message , " \ n " ]}
>       ]},
>       { lager_file_backend , [
>         { file , " priv / log / console.log " },
>         { level , информация },
>         { форматировщик , lager_default_formatter },
>         { formatter_config , [ дата , " " , time , " [ " , серьезность , " ] " , { site , [ site , "  " ], " " }, { pid , " " }, { module , [{ pid , [ " @ " ], " " }, модуль , { функция , [ " : " , функция ], " " },{ строка , [" : " , строка ], " " }], " " }, "  " , сообщение , " \ n " ]}
>       ]}
>     ]},
>    { crash_log , " priv / log / crash.log " }
>   ]},
> ```

nothing has changed or added to the source code
followed the instructions http://docs.zotonic.com/en/latest/developer-guide/docker.html#zotonic-dev

**Comment by paladim** [comment]
> Interesting, that looks different from the default `erlang.config.in` file.
> 
> Was it edited?
> 
> ```erlang
>  {lager,
>   [{handlers,
>     [
>       {lager_console_backend, [
>         {level, info},
>         {formatter, lager_default_formatter},
>         {formatter_config, [time, color, " [", severity, "] ", {site, [site, " "], ""}, {module, [module, ":", line, " "], ""}, message, "\n"]}
>       ]},
>       {lager_file_backend, [
>         {file, "priv/log/error.log"},
>         {level, error},
>         {formatter, lager_default_formatter},
>         {formatter_config, [date, " ", time, " [", severity, "] ", {site, [site, " "], ""}, {pid, ""}, {module, [{pid, ["@"], ""}, module, {function, [":", function], ""}, {line, [":", line], ""}], ""}, " ", message, "\n"] }
>       ]},
>       {lager_file_backend, [
>         {file, "priv/log/console.log"},
>         {level, info},
>         {formatter, lager_default_formatter},
>         {formatter_config, [date, " ", time, " [", severity, "] ", {site, [site, " "], ""}, {pid, ""}, {module, [{pid, ["@"], ""}, module, {function, [":", function], ""}, {line, [":", line], ""}], ""}, " ", message, "\n"] }
>       ]}
>     ]},
>    {crash_log, "priv/log/crash.log"}
>   ]},
> ```

nothing has changed or added to the source code
followed the instructions http://docs.zotonic.com/en/latest/developer-guide/docker.html#zotonic-dev

**Comment by mworrell** [comment]
Thanks for the explanations, turns out there is a `sed` script that modifies the config file.  I have removed this in #2173.

**Comment by paladim** [comment]
ok,
@mworrell, please, check http://demo.zotonic.com/ - not working

**Comment by mworrell** [comment]
Thanks, should move that one to master and on a stable VPS instead of this Amazon thing.

@arjan can you kick demo again?

**Comment by mworrell** [comment]
Re-opened as we are still fixing this in #2173
