### ISSUE TITLE
Easier zotonic translation (via crowdin)

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#217]
With the help of the online service http://crowdin.net/ we could make it much easier for translaters to contribute to zotonic.

Crowdin supports free accounts for open-source projects.  

We can upload the pot files, and translators can contribute translations online. They also have an api to manage the technical stuff.

We have set it up for channel for some time now. It is amazingly easy for translators to contribute. This is our howto: http://channel.me/translate/how_to

Useful?

**Comment by mworrell** [comment]
We are now using Crowdin for the Zotonic .po file
