### ISSUE TITLE
g++

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2174]
While compiling 1.0 on FreeBSD I received this error: 

`===> Compiling erlexec`
`===> Compiling /usr/home/zotonic/zotonic/_build/default/lib/erlexec/c_src/ei++.cpp`
`===> exec: g++: not found`

A search revealed that gcc was needed, so a quick `pkg install gcc` resolved the issue.

Maybe worth adding to the documentation as a required dependency for FreeBSD?

**Comment by mworrell** [comment]
I am now adding this to the docs:

```rst
Preparation
^^^^^^^^^^^

First prepare your system for running Zotonic. Zotonic needs:

* Erlang 18 or higher
* PostgreSQL 8.4 or higher
* ImageMagick 6.5 or higher for image resizing
* Git for pulling in external dependencies
* C++ compiler (gcc) for erl_exec and other dependencies

.. seealso::
    a more extensive discussion of
    :ref:`all requirements <installation-preinstall>`

Linux
"""""

For instance on Debian you can install the dependencies by running::

    $ sudo apt-get install gcc g++ build-essential git erlang imagemagick postgresql
```

What would the equivalent FreeBSD command?  `sudo pkg install ...` ?

**Comment by seannaswell** [comment]
Yes, `sudo pkg install` is correct. 

The base FreeBSD system only comes with essential tools for the OS to run, everything extra has to be installed, including sudo. Here is my complete list:

`# pkg install sudo zip wget git bash gcc gmake erlang ImageMagick7-nox11 postgresql10-server`

Some packages, like Postgresql, need the version specified as multiple versions are available to be installed, whereas others, like erlang, default to the most recent if not specified. 

Perhaps a simple listing of required packages might be the easiest way to show in the documentation, so as to avoid being quickly dated or appear to imply that a specific version is needed.

`FreeBSD packages required: zip, wget, git, bash, gcc, gmake, erlang, ImageMagick, postgresql server`
