### ISSUE TITLE
Cotonic compile failed

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2175]
Compile of cotonic on FreeBSD failed:

` - Installing cotonic from https://github.com/cotonic/cotonic.git`
`Cloning into 'cotonic'...`
`Done`
`make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 4: Need an operator`
`make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 13: Missing dependency operator`
`make[1]: "/usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic/Makefile" line 43: Need an operator`
`make[1]: Fatal errors encountered -- cannot continue`
`make[1]: stopped in /usr/home/zotonic/zotonic/apps/zotonic_mod_base/priv/lib-src/cotonic`
`===> Hook for compile failed!`

`gmake: *** [GNUmakefile:27: compile] Error 1`

Is this something platform specific, or is master still in flux?

**Comment by seannaswell** [comment]
Looks like it may be related to Makefile syntax. I am using gmake...

**Comment by seannaswell** [comment]
Ok, mystery solved. It appears that [cotonic-fetch.sh](https://github.com/zotonic/zotonic/blob/3266f7ed6633601c0c64d31b0f634febe8edd2b9/apps/zotonic_mod_base/cotonic-fetch.sh#L22) is calling _make_, which is obviously fine on systems that use Gnu make.

After changing to _gmake_, it compiles properly. 

Read recently about the OpenZFS project using a lot of ifdefs to determine which OS is in use. Not sure how many people currently or will use Zotonic on non-Linux platforms in the future, or what a good solution might be, but for now I will manually fix as needed.

**Comment by mworrell** [comment]
I assume that for Zotonic you are using `gmake`.
Do you have an example of these ifdefs?
Would be nice to have everything building without running into problems.

Also because we now support Makefiles for building `lib` files from `lib-src`.
There the Erlang code is calling `make` and assumes all is ok.

We might want to use `gmake` for those dependencies if we are on a BSD platform.
(What is returned by `os:type().` on your system?)

**Comment by seannaswell** [comment]
I am using gmake, yes.

> Eshell V10.3.5.3  (abort with ^G)
> 1> os:type().
> {unix,freebsd}
> 2> 

The ifdef  reference made related to OpenZFS, which is written in C. Not sure what an equivalent would be in Erlang.

**Comment by seannaswell** [comment]
To clarify: [cotonic-fetch.sh](https://github.com/zotonic/zotonic/blob/3266f7ed6633601c0c64d31b0f634febe8edd2b9/apps/zotonic_mod_base/cotonic-fetch.sh#L22) is a script. So, in this case it's a script calling `make`, not Erlang.

**Comment by mworrell** [comment]
@seannaswell I think this will fix this issue: https://github.com/cotonic/cotonic/pull/14  Can you check if you can run `make` in that Cotonic branch?

**Comment by mworrell** [comment]
This has been fixed in Cotonic, should be better now.

**Comment by mworrell** [comment]
Build on FreeBSD works now (with the recent changes in cotonic)
