### ISSUE TITLE
TLS error

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2177]
Getting this when starting a new site:

> 02:05:29.985 [info] zotonic_core_sup:96 zotonic_site_status - running
> 02:05:29.985 [info] zotonic_core_sup:99 ================
> 02:08:46.413 [info] TLS server: In state connection received CLIENT ALERT: Fatal - Bad Certificate

And here is a screenshot of the Firefox error message: [TLS.jpg](https://app.box.com/s/tyzjsqeulvol0622pu1mlxkeihnbglaq)

**Comment by mworrell** [comment]
Is your site, by any chance, a ".dev" site?

**Comment by seannaswell** [comment]
Using master, it was created as a .test site.

I created a few new sites using addsite, changed the database and domain settings in zotonic_site.config, then restarted Zotonic, and they worked as expected.

Therefore, I must have done something wrong the first time. Not sure what I could have done differently, but it is working for new sites that are created.
