### ISSUE TITLE
Cowboy2 and http redirect

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2178]
The master branch is now issuing a self-signed certificate, has removed the listen_port and port options from the zotonic_site.config file, and is automatically redirecting from port 8000 to port 8443.

I would like to try using Cowboy2 directly, have given the zotonic user access to bind ports 80/443, and have set the `port` and `ssl_port` options in `zotonic.config`. However, I do not see an option to reconfigure the 8000 to 8443 redirect, and make it an 80 to 443 redirect instead. Where can the http to https redirect options be configured? 

In addition, is it possible to add an option to remove the self-signed certificate @ site.com:8443/en/admin/ssl, in order to allow using SSL termination with Nginx or HAProxy?

**Comment by mworrell** [comment]
You can set the `port` and `ssl_port` in the zotonic.config file.

The internal listen and external ports are now separate.

Before it was a bit messy, that was a historical artifact from the times that SNI did not work yet and you needed to configure a separate https port per site. With SNI working we have a single http and https port per site and you don't need to configure it per site (or add it to the site's hostname) anymore.

See the config template here:

https://github.com/zotonic/zotonic/blob/master/apps/zotonic_launcher/priv/config/zotonic.config.in#L83

**Comment by seannaswell** [comment]
Understand. I have `port` and `ssl_port` options in `zotonic.config` set to 80/443 already. 

> 15:46:41.693 [info] zotonic_core_sup:84 ================             
> 15:46:42.495 [info] zotonic_core_sup:93 testsite running https://testsite.com/                           
> 15:46:42.497 [info] zotonic_core_sup:96 zotonic_site_status - running
> 15:46:42.497 [info] zotonic_core_sup:99 ================

However, when connecting to http://testsite.com it automatically redirects to https://testsite.com:8443. The redirect function needs to be changed or disabled, but it is not obvious where that is configured, and I don't see an option in the web admin pages.

In addition, in order to use Nginx or HAProxy in front of Cowboy, the self-signed certificate needs to be removed, but there is no way to do that on the admin/ssl page, and it is not clear where that is configured.

**Comment by seannaswell** [comment]
My apologies, when doing a fresh install of master and creating a new site with `listen_port, 80` and `ssl_listen_port, 443` defined in `zotonic.config`, it appears the https redirect works properly. 

If the self-signed certificate can't be disabled, and the port 8000 to 8443 redirect can't be disabled, the [Ngnix section of the Port Configuration documentation](http://docs.zotonic.com/en/latest/ref/configuration/port-ssl-configuration.html#server-behind-a-proxy-like-nginx-or-haproxy) might need to be updated.

I will be using Cowboy2 directly, so feel free to close this issue.

**Comment by mworrell** [comment]
We shouldn't be redirecting to https if the proxy already terminated the ssl connection.

There is cowmachine code that is checking for that:

https://github.com/zotonic/cowmachine/blob/master/src/cowmachine_proxy.erl#L67

If there is a problem then we have to adapt the test set and fix it.

Can you have a look what headers your proxy is sending along?

**Comment by seannaswell** [comment]
Previously I used Nginx to proxy an older version of Zotonic, but am using Zotonic directly now. 

I was not aware that cowmachine now automatically adjusts the port configuration. If that is the case, disregard my comments.

**Comment by mworrell** [comment]
Yes, we put some logic into cowmachine.

We also use a whitelist for trusted proxies, to prevent people sending along random proxy headers.

**Comment by seannaswell** [comment]
Setup Nginx in front of master branch following the example in documentation, works as expected.
