### ISSUE TITLE
Is it possible to add an list of ids to the id_exclude search

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2180]
Could we make this work:

`id_exclude=m.rsc.mix_featured.o.haspart|make_list`

**Comment by DorienD** [comment]
Some examples of usage in our codebase:

`id_exclude=id.id`
`id_exclude=first[1]`
`id_exclude=m.rsc.search_filters.id`

**Comment by DorienD** [comment]
Is this issue pending on a reply on my part?

**Comment by mworrell** [comment]
The exclude-with-a-list is easier to add in the 1.x, as there we use binaries for all strings (some small exceptions).

Will add this to the 1.1.
