### ISSUE TITLE
site stopped

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2186]
Testing master on personal site, started with `bin/zotonic debug` and let it run for a few days. Went to site yesterday and was down, found the following messages in terminal:

> 13:40:58.463 [error] z_mqtt_sessions_runtime:205 gen_server <0.27587.15> terminated with reason: no function clause matching z_mqtt_sessions_runtime:reauth(#{clean_start => false,client_id => <<"y6lfA0PxytxzeidJEQcN">>,keep_alive => 300,password => <<>>,...}, {context
,undefined,undefined,seannaswell,undefined,<<"y6lfA0PxytxzeidJEQcN">>,[<<"bridge">>,<<"y6l...">>],...}) line 205
13:40:58.464 [error] z_mqtt_sessions_runtime:205 CRASH REPORT Process <0.27587.15> with 0 neighbours crashed with reason: no function clause matching z_mqtt_sessions_runtime:reauth(#{clean_start => false,client_id => <<"y6lfA0PxytxzeidJEQcN">>,keep_alive => 300,passwo
rd => <<>>,...}, {context,undefined,undefined,seannaswell,undefined,<<"y6lfA0PxytxzeidJEQcN">>,[<<"bridge">>,<<"y6l...">>],...}) line 205
13:40:58.464 [error] z_mqtt_sessions_runtime:205 Supervisor 'seannaswell$sesssup' had child session_process started with {mqtt_sessions_process,start_link,undefined} at <0.27587.15> exit with reason no function clause matching z_mqtt_sessions_runtime:reauth(#{clean_st
art => false,client_id => <<"y6lfA0PxytxzeidJEQcN">>,keep_alive => 300,password => <<>>,...}, {context,undefined,undefined,seannaswell,undefined,<<"y6lfA0PxytxzeidJEQcN">>,[<<"bridge">>,<<"y6l...">>],...}) line 205 in context child_terminated
13:40:58.464 [error] CRASH REPORT Process <0.28417.15> with 0 neighbours exited with reason: {{function_clause,[{z_mqtt_sessions_runtime,reauth,[#{clean_start => false,client_id => <<"y6lfA0PxytxzeidJEQcN">>,keep_alive => 300,password => <<>>,properties => #{session_e
xpiry_interval => 1800},protocol_name => <<"MQTT">>,protocol_version => 5,type => connect,username => <<>>,will_flag => false,will_payload => undefined,will_properties => #{},will_qos => 0,will_retain => false,will_topic => undefined},{context,undefined,undefined,sean
naswell,undefined,<<"y6lfA0PxytxzeidJEQcN">>,[<<"bri...">>,...],...}],...},...]},...} in gen_server:call/2 line 215
13:40:58.464 [error] Ranch listener zotonic_http_listener_ipv4 terminated with reason: {{function_clause,[{z_mqtt_sessions_runtime,reauth,[#{clean_start => false,client_id => <<"y6lfA0PxytxzeidJEQcN">>,keep_alive => 300,password => <<>>,properties => #{session_expiry_
interval => 1800},protocol_name => <<"MQTT">>,protocol_version => 5,type => connect,username => <<>>,will_flag => false,will_payload => undefined,will_properties => #{},will_qos => 0,will_retain => false,will_topic => undefined},{context,undefined,undefined,seannaswel
l,undefined,<<"y6lfA0PxytxzeidJEQcN">>,[<<"bri...">>,...],...}],...},...]},...}
/home/zotonic/zotonic/apps/zotonic_launcher/bin/zotonic-debug: line 31: 23023 Killed                  $ERL $ERLOPTS -smp enable -env ERL_MAX_PORTS $MAX_PORTS +P $MAX_PROCESSES +K $KERNEL_POLL -pa $PA $NAME_ARG $NODENAME@$NODEHOST -boot start_sasl $(find_config_arg erl
ang.config) $(find_config_arg zotonic.config) -sasl errlog_type error -s zotonic
                                                                                   
> [zotonic@zotonic ~/zotonic]$

Not sure how long it ran before going down, but restarted with `bin/zotonic start` and now monitoring with Pingdom. 

Maybe there is something helpful in the report, if not, feel free to close. Just an FYI.

**Comment by seannaswell** [comment]
Likely relevant... Zotonic running behind Nginx, setup following the docs: http://docs.zotonic.com/en/latest/developer-guide/deployment/nginx.html

**Comment by mworrell** [comment]
Thanks for the report.

I think I can see where it goes wrong.
It has something to do with the client reconnecting with a `session_present` flag, and then there is some error.

This probably happens just a bit too often and then a supervisor gives up.

**Comment by mworrell** [comment]
Found the problem with the crash in the MQTT code, working on a solution.

**Comment by seannaswell** [comment]
Will update, thanks.

**Comment by mworrell** [comment]
Thanks for reporting, without such clear reports we won't be able to make Zotonic as good as it is!
