### ISSUE TITLE
lib file not found

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2190]
I put the latest release, now I can not get into the admin panel
`23:54:44.413 [info] No scomp enabled for "wire"
23:54:44.416 [warning] lib file not found: js/apps/zotonic-wired.js
23:54:44.416 [warning] lib file not found: js/modules/livevalidation-1.3.js
23:54:44.416 [info] No scomp enabled for "script"`

**Comment by mworrell** [comment]
Do you have mod_base enabled?

**Comment by heiheshang** [comment]
I don’t know yet, I just added a new site

**Comment by heiheshang** [comment]
I activated two modules mod_wires and mod_base, everything worked fine.

**Comment by mworrell** [comment]
Ah, could be mod_wires. That one holds all the parts for *wire* based web sites.

We decided to start splitting the front end technologies into separate modules.

So in due time you can choose to build with Elm or whatever, and not worry about the "wires" part in your templates.

Good to hear that it works again.
