### ISSUE TITLE
Bad install of the blog test site on a fresh zotonic stable 0.x

### ISSUE THREAD

**Issue by JiffB** [zotonic/zotonic#2200]
Debian buster (stable)
erlang pkgs version: 1:21.2.6+dfsg-1
____________________
Hi,

I wanted to give a try to zotonic, so I : 
```
* createdb -O zotonic zotonic

* Added: "127.0.0.1   zotblog.test"  into /etc/hosts

* tar xvzf zotonic-0.51.2.tar.gz

* Modified: zotonic-0.51.2/src/scripts/zotonic-addsite
   according to answer into bug #2131 

* make

* Modified: ~/.zotonic/0/zotonic.config 3 parms : 
   1- Timezone: "Europe/Paris"
   2- DB password: zotonic
   3- admin password: "admin"

* ./start.sh, which threw an error about lager:

[losts of clashes between Erlang zotonic and system, normal]

=CRASH REPORT==== 17-Oct-2019::02:20:05.149188 ===
  crasher:
    initial call: lager_handler_watcher:init/1
    pid: <0.169.0>
    registered_name: []
    exception exit: noproc
      in function  gen:do_for_proc/2 (gen.erl, line 228)
      in call from gen_event:rpc/2 (gen_event.erl, line 239)
      in call from lager_handler_watcher:install_handler2/3 (src/lager_handler_watcher.erl, line 117)
      in call from lager_handler_watcher:init/1 (src/lager_handler_watcher.erl, line 51)
      in call from gen_server:init_it/2 (gen_server.erl, line 374)
      in call from gen_server:init_it/6 (gen_server.erl, line 342)
    ancestors: [lager_handler_watcher_sup,lager_sup,<0.154.0>]
    message_queue_len: 0
    messages: []
    links: [<0.157.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 234
  neighbours:

[losts of clashes between Erlang zotonic and system, normal]

=INFO REPORT==== 17-Oct-2019::02:20:05.586004 ===
gen_smtp_server listening on {127,0,0,1}:2525 via tcp

02:20:05.622 [info] z_sites_manager:276 Site started: zotonic_status (<0.315.0>)
02:20:05.652 [info] z_filewatcher_inotify:114 [inotify] Starting inotify file monitor.
02:20:05.763 [info] z_site_startup:82 [zotonic_status] info @ z_site_startup:82  Site zotonic_status started, modules loaded
02:20:09.574 [info] zotonic_sup:165 
02:20:09.574 [info] zotonic_sup:166 Zotonic started
02:20:09.574 [info] zotonic_sup:167 ===============
02:20:09.574 [info] zotonic_sup:168 Config files used:
02:20:09.575 [info] zotonic_sup:169 - /home/niff/.zotonic/0/erlang.config
02:20:09.575 [info] zotonic_sup:169 - /home/niff/.zotonic/0/zotonic.config
02:20:09.575 [info] zotonic_sup:170 
02:20:09.575 [info] zotonic_sup:183 Web server listening on IPv4 any:8000, IPv6 ::8000, SSL :8443
02:20:09.575 [info] zotonic_sup:186 

* bin/zotonic addsite -s blog zotblog , checked all parms ok, enter
   Puzzling end of creation msg: user/sites/zotblog/SITE.ERL no such user or directory

* Stop zotonic
* make
   even though I had inotify-tools warning about some recompilations, just in case,
* Start zotonic

* Point FF to: htpp://localhost:8000
* login
* Site zotblog stopped => hit start, show running

* Point FF to: http://zotblog.test:8000
```
But instead of the real page, I just have the black top line with "Your first blog", 2 empty grey blocks at the right of the page (Archive & Keyworks) and a nice: "This page does not exist" line on the left of the page, followed by a link: "Return to the home page" that points to: http://zotblog.test:8000.
 
So my questions are:
 
1- why isn't the bad (.dev) extension corrected into the zotonic-addsite script of the tar.gz ?
 
1b- why isn't it corrected either in the "0.x" branch of the git?
 
1c- does this lack of maintenance mean that the 1.x dev version is ready for production?
 
2- why didn't the blog application install &| isn't working correctly?
 
2b- what shall I do to have the blog app correctly working?

Jean-Yves

**Comment by mworrell** [comment]
Hi Jiff,

Thanks for trying Zotonic and reporting back.

The 0.x is indeed stable and in active maintenance. It is in active use by all parties.

First: what name clashes do you see?  I only know of some timezone modules for which we needed to include two, because of dependency trees.

Which OTP version do you use?

Then you questions:

> 1- why isn't the bad (.dev) extension corrected into the zotonic-addsite script of the tar.gz ?
> 1b- why isn't it corrected either in the "0.x" branch of the git?

I guess we overlooked that one, the documentation was changed to remove the `.dev` and replace it with `.test`.  Thanks to Google for making .dev unusable.

> 1c- does this lack of maintenance mean that the 1.x dev version is ready for production?

We use 0.x in production, as do many others.

The 1.x is nearing completion, as you can see on the milestones list. Actually right now we are working on the `addsite` functionality for the 1.x. In the 1.x we are using new code and removing the use of the shell scripts, in favor of using escript and the Erlang code.
 
> 2- why didn't the blog application install &| isn't working correctly?

We have to check that script. Might need some TLC.
I schedule this issue to be resolved for the 0.52.

> 2b- what shall I do to have the blog app correctly working?

I think the database content was not correctly installed.
Check in the `/admin` if the page with the name `page_home` is present.

If not then the default data was not installed. Will check what the reason is.

For our own development we don't use these scripts (anymore) as we have internal templates to work from when we start a new project.  It will be good to have the `addsite` command as part of the automatic tests to prevent this kind of problems.

**Comment by JiffB** [comment]
Hi Marc,

> First: what name clashes do you see? I only know of some timezone
> modules for which we needed to include two, because of dependency trees.

This is a long list:
```
=INFO REPORT==== 17-Oct-2019::02:00:12.278349 ===
    msg: Starting reporters with []

    options: []
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/qdate_localtime/ebin/ibuild.beam hides /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/erlang_localtime/ebin/ibuild.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/qdate_localtime/ebin/localtime_dst.beam hides /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/erlang_localtime/ebin/localtime_dst.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/qdate_localtime/ebin/localtime.beam hides /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/erlang_localtime/ebin/localtime.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_util.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_util.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_matcher.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_matcher.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_ret_spec.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_ret_spec.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_expect.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_expect.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_history.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_history.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_cover.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_cover.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_code.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_code.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_code_gen.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_code_gen.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_args_matcher.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_args_matcher.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck.beam 
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/meck/ebin/meck_proc.beam hides /usr/lib/erlang/lib/meck-0.8.7/ebin/meck_proc.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_param_sup.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_param_sup.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_sup.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_sup.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_manager_sup.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_manager_sup.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gre.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gre.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_counter_sup.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_counter_sup.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_manager.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_manager.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_context.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_context.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_param.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_param.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_app.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_app.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/gr_counter.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/gr_counter.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/glc_ops.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/glc_ops.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/glc.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/glc.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/glc_lib.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/glc_lib.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/goldrush/ebin/glc_code.beam hides /usr/lib/erlang/lib/goldrush-0.2.0/ebin/glc_code.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/cf/ebin/cf.beam hides /usr/lib/erlang/lib/cf-0.3.1/ebin/cf.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/cf/ebin/cf_term.beam hides /usr/lib/erlang/lib/cf-0.3.1/ebin/cf_term.beam
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/ebin/base64url.beam hides /usr/lib/erlang/lib/base64url-1.0/ebin/base64url.beam
** Found 31 name clashes in code paths 
```
and it is repeated a 2nd time below:
```
=INFO REPORT==== 17-Oct-2019::02:00:12.438122 ===
filezcache: scanning cache directory for unknown files.
** /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/qdate_localtime/ebin/ibuild.beam hides /usr/local/src/ERLANG/FRAMEWORKS/ZOTONIC/zotonic-0.51.2/deps/erlang_localtime/ebin/ibuild.beam
[…]
```

> Which OTP version do you use?
Seems to be  10.2.4
```
$ la /usr/lib/erlang
drwxr-xr-x  2 root root  269 2019-10-11 21:52 bin
lrwxrwxrwx  1 root root   30 2019-02-18 14:09 doc -> ../../share/doc/erlang-doc/doc
drwxr-xr-x  6 root root   77 2019-10-11 21:52 erts-10.2.4
drwxr-xr-x 49 root root 4096 2019-10-12 15:18 lib
lrwxrwxrwx  1 root root   15 2019-02-18 14:09 man -> ../../share/man
drwxr-xr-x  3 root root   74 2019-10-11 21:52 releases
drwxr-xr-x  4 root root   32 2019-10-11 21:51 usr
```

>  Actually right now we are working on the addsite functionality for the 1.x.
I saw that as it was my 1st try.
1.x looks interesting, do you have an rough idea about when it'll be out? (as there's a big change of paradigm, I'd better start w/ 1.x, unless you tell me that some scripts will make sure to smoothly transition any app from 0.x to 1.x or it will be _very_ easy to do by hand.)

> We have to check that script. Might need some TLC.
> I schedule this issue to be resolved for the 0.52.
Hmm, when will it be out? I need to test thoroughtly to fully understand how the zotonic guts work and then, I have to try to adapt OnsenUI on it, so the faster I begin, the better it is.
Disclaimer: I'm not a real programmer, much more a sunday one, not to mention Erlang's hard to me as I formerly used imperative languages (Assembly, Basic, C, a bit of C++ and Python, a looong time ago.)

> Check in the /admin if the page with the name page_home is present.
Site zotblog » BTN Admin » Dashboard BTN All Pages » I see a lot of lines, here is the first:
```
Site Administrator | Person | 17 Oct 2019, 02:27 | 17 Oct 2019, 13:42 | Site Administrator
-- | -- | -- | -- | --
```
but I do not see any "page_home".
Searching it by the front bar search input zone returns: "No pages found" :(

> For our own development we don't use these scripts […]
For quite a good time, I was testing programs and web applications to see if they could fit to our needs.
My mod'op was simple: give it a maximum of 1h30 to be operational (last max 1h45) and, if possible, start without any knowledge other than the software main purpose - install it, if possible, without reading the doc or just reading the strict minimum of it, then test it to see if it was written with the end user needs and ergonomy (the user's one, not the programmer's…) in mind.
I rejected almost 87% of them, even one of the french leading ERP software (sage), as after 1h45 I had painfully created a customer, a supplier, an article, an order slip, a reception slip but was never able to insert a single line into a customer invoice (still without reading any doc)…

So, from my point of view and IMHO, Zotonic should:
need the user to create a DB, modify the /etc/hosts files, whatever (no change),
then fully install, (re)compile, etc
and be fully ready to be used at the end of the installation procedure,
including tests apps like "blog", plus one to be invented showing almost all it's possibilities,
! which mean, it actually miss some important delete function: "remove test app" (just delete it from the running path, but of course not from the "reserve path")
! and "remove myapp", removing it from the running path BUT sparing it in another path to make sure nothing was lost.
User's responsability to fully remove any of them manually (+doc on how to do that or a clear message on the console at the end of the procedure.)

Of course, people already knowing it and ready to program/install their own app would have to get rid of test apps (may be all in once with a special button‽), but testers/beginners would get a fully functional bunch of test sites at the end of the installation procedure (once again, including one that shows almost all possibilities of zotonic - _All thourougly commented_, because it is the Erlang programmers plague to almost never take time to do so!!)

From my point of view, this is a very useful manner to hook the tester an give him the desire to keep going on and as you're actually quite close to that, why not pushing it a bit further?!

Jean-Yves

**Comment by mworrell** [comment]
Just to be sure, when you write:

> including tests apps like "blog", plus one to be invented showing almost all it's possibilities,

You mean to have it pre-installed?  With an option to un-install it again?

If I understood that correctly then I actually like that idea, as it really gives a nice starting point.

**Comment by JiffB** [comment]
Yup Marc, absolutely !
 
As I always try to place myself as a perfect newbee¹, my first question is : 
What is better for a new comer, may be not 100% sure about what he needs, but anyway needing a demo full of comments and many practical cases² to see what's possible, than a software supplied with less than a page of clear requirements and manipulations to do and controls to perform, such as a command line connection to Pg³ - then once done, issue a make, ./start.sh and find fully functional tests sites online !?
 
This enhance the first glance way beyond what others are usually doing.
 
To be absolutely candid, before arriving here, I lost a full afternoon and a part of the night to try to understand how N2O was working, but docs are South (neither of what they describe to launch a test site actually works, be it either in N2O or mad docs), after investigations, the sample test site code had visibly been stripped out of the current code, docs are missing many of the most important things to know, etc.
So, after a looong lost time, I removed the git and edited a savage note-to-myself.txt to remember never to come back to this software that mistreat so much the newbie user when he's is not a fully seasonned Erlang programmer.
It MAY be the best there is, but IMHO, the first glance also gives a good appreciation of what kind of support you'll find afterwards, as you can imagine, it was far from a good experiment and the chances I come back to it one day are close to null.
 
BTW, thanks for your quick and accurate answers ;)

Jean-Yves
________
¹ - Which, in this case, is true.
² - So he'll see and get very good bases to be able to correctly develop his own app and understand how the software is really working, which, with Erlang, is often a challenge.
³ - To be added, as it is missing from Zotonic docs: psql -U zotonic -h localhost -p 5432 -d zotonic + what to change into /etc/postgresql/<Ver.Nb>/main/pg_hba.conf to be able to do so (and at which place to put it in this sensitive file, depending on if the permission is valid for all DBz & all users or only limited to one DB and one user - a cut/paste from the official Pg site being much better than an hyperlink.)

**Comment by JiffB** [comment]
Note that I choosed the JS framework the same way, browsing the 5 or 10 best frameworks pages along the web, learn what is a hybrid app and visit their sites.
OnsenUI had the best site, clear explanations, wonderful WYSIWYG examples (with excellent explanations attached) that you can modify online from their advises to immediately see the results and very easy (and short !) code to get a professional final look on smartphones or little tablets.
 
This is why I'd like to take the chances to adapt it to Zotonic 'cos the both will make a tremendous combination - BTW, do you think this kind of adaptation will be quite easy or not?

Jean-Yves

**Comment by JiffB** [comment]
> OnsenUI? I have to check that one.

Quite a new competitor from opinion sites, but nice, see: https://onsen.io/ and https://onsen.io/samples/ (my only hope is it will not turn to a paying software in the next months/years &| 2 versions, stripping the community version of all it's interesting features as it is seen too often.)
What strucked me is the small quantity of lines needed to achieve a real pro app and the quality of it's examples and docs.

> Another idea I had is that we could install the demo site on localhost, that is one step less in the installation.

Why not, as my contention is  you often develop your own site with a hosts|DNS name that loops internally or on the machine beside - the most important thing is, it must be available anytime to be able see it working and be able to read it's files for people like me to extrapolate the code from it (remember, I'm a Sunday programmer, much more a brick assembler than a kreator;) and on the other hand, it must be very easy to get rid if it for other people.

> The zotonic status site could also be running on a separate port.

Excellent idea !
I use Netdata that have lots of plugins to inform you about the health of Pg, nginx, etc, so a direct connection to this port would be very nice to make a new plugin that also controls Zotonic's intrinsic health and by extension, all sites it is running.

> We didn't settle on a JS framework, we just added the plumbing and other infrastructure for robust user interfaces.

Oh, I missed that one, I believe it is a good thing to leave it JS' agnostic, provided there are some important examples in the test site to show how the best way to achieve the integration with Zotonic - this way, there won't be people getting mad because you push one framework further than another and users have all latitude to do whatever they want - a typical win-win way :)

**Comment by mworrell** [comment]
I like your fresh approach, it is really helpful.

Distilling from the ideas I see some concrete things for the 0.52 (release first Monday of nov):

 - Fix the skel install of 'blog'
 - Check again on mentions of `.dev`, replace with `.test`

And for the 1.x / master:

 - Finish the replacement of `bash` for the skel installs with `erlscript`
 - Also check on `.dev` occurrences, replace with `.test`
 - Add a documented website to the code base, link to it from the `apps_user` (that is the user modules & sites directory for the 1.0)
 - Investigate running the _zotonic status_ site on its own port, making it possible to use `localhost` for the default demo site
 - Fix documentation for the installation process, maybe restructure some parts of the install manual

And on a related track:

 - Check how OnsenUI could work with our infrastructure and web/service workers

> And the MQTT part should be easy to disable, as it takes memory for nothing for people that do not use it (I've seen it is in project w/ 1.x, but my test showed that the primitive to stop it had no effect.)

You mean on the server? Or on the client?

**Comment by mworrell** [comment]
@mmzeeman @ddeboer @arjan @AlainODea @michielklonhammer  Could you guys have a look at this thread and see if you have anything to comment on it?

**Comment by JiffB** [comment]
> I like your fresh approach, it is really helpful.

Thanks, you're very welcome.

> Check how OnsenUI could work with our infrastructure and web/service workers

Whoo, this one's very nice (I cross fingers:)

I have another suggestion that can or cannot be adapted to Zotonic ; I can't say, as I failed to test N2O, so it is only based upon the docs I read.

IIUC, they use a bert.js file the client download to encode it's data into a comprehensible Erlang format + a JS Erlang small interpreter (500 LOC) to send data back through websocket directly to server's Erlang functions that'll process the data returned.

As the whole process doesn't seem to need lots of files (wild guess, I'm not tough enough in Erlang to be sure about that), it may be a good thing to incorporate this feature into Zotonic to get a translation layer from JS to Erlang, making it "more complete" and easier to use with JS that is the actual leading language.

This, of course, needs to be investigated from a seasoned programmer's perspective, but it seems a real good idea because (the way I understood N2O docs) that would allow almost any kind of JS framework/code to run, translate smoothly and return to the server where Erlang would do the processing job.

> You mean on the server? Or on the client?

I meant on the server, MQTT is a plus but isn't a requirement for many apps &| people and it may be a hidden threat leaving it open, either for data privacy or security.

**Comment by mworrell** [comment]
Re: JSON <-> Erlang

We currently use `jsxrecord` which has knowledge of the Erlang records and maps them to/from JSON. It also maps `null` to `undefined` and vice versa. The idea is to add more heuristics when they are needed.

We have also UBF-A encoding/decoding (as used in the 0.x), but are not using that at the moment. We gave priority to interaction using JSON, as most Javascript functions like that format.

Re: message routing

The _wired_ system uses _delegates_ to tell to which module's event handler a message has to be sent. The new 1.x topic based system routes messages using topics. You can easily let a module listen to a topic by adding (an exported) function:

```erlang
-spec 'mqtt:test/#'(mqtt_packet_map:mqtt_packet(), z:context()) -> ok.
'mqtt:test/#'(Msg, _Context) ->
    lager:debug("mod_mqtt test topic: ~p", [Msg]),
    ok.
```

The function above subscribes the module to the topic `test/#`.

Re: MQTT server

In the configuration the MQTT listen ports can be set to `none`, which disables the MQTT listeners. 

We use the MQTT topic trees and MQTT session processes for all communication between the server and the client, so the internal MQTT handling can't be switched off.

**Comment by AlainODea** [comment]
@mworrell I think you have covered the issues extremely well here. Thank you!

@JiffB, a refresh of the getting started content in the cookbook is very worthwhile. If you're feeling up to it, it would be a major contribution for the community.

The out of the box experience can definitely be challenging. A lot of effort went into streamlining that over the years, but the product and the getting started docs have drifted apart a bit. Some of this is that I had very opinionated ways of handling that that didn't reflect the way the majority of the community uses Zotonic.

Aside from decoding the occasional error message, you don't need to know Erlang to use Zotonic for most sites or blogs. It doesn't hurt, but it isn't required. You can get extremely far with ErlyDTL (the template language) and page connections. You can do a surprising amount without writing a single line of Erlang.

**Comment by JiffB** [comment]
> We currently use jsxrecord

ok, I'm just beginning to read the zotonic doc so I did not reach already this section.

> Re: message routing

I'm already lost :/
I really need to read attentively the doc to be able to understand all about the zotonic underlying mechanic - so my week-end will be dedicated to do so.

> Re: MQTT server

Arf, trivial and efficient :)

> We use the MQTT topic trees and MQTT session processes for all communication

Funny, 'cos I very recently read an article about why APIs are often not as good as protocols, where the writer was ranting against today's all-is-an-API culture instead of writing well designed minimal spec for good protocols.

**Comment by JiffB** [comment]
On Fri, 18 Oct 2019 09:23:51 -0700
AlainODea <notifications@github.com> wrote:

Hi Alain,

> @JiffB, a refresh of the getting started content in the cookbook is
> very worthwhile. If you're feeling up to it, it would be a major
> contribution for the community.

Why not, but I may need directions, depending on which version it is
written for (see below).

I also don't know if you mean today's document or the future one,
including the test application automatically installed we talked about
with Marc.

> The out of the box experience can definitely be challenging. A lot of
> effort went into streamlining that over the years, but the product and
> the getting started docs have drifted apart a bit.

Ok, so you meant the actual getting started doc.

To make absolutely sure I do not mistake you :
this will be a rewrite of the 0.x "getting started" section,
including things Marc and I talked about,
such as how to modify the Pg 'pg_hba.conf' config file to either be able
to only connect to the Zotonic DB or to any other DB, provided it stays
from localhost to localhost ?

> Some of this is
> that I had very opinionated ways of handling that that didn't reflect
> the way the majority of the community uses Zotonic.

Hu? For my own information, please develop this a bit further as it is
always interesting to know philosophical differences of concepts about a
project.

> Aside from decoding the occasional error message, you don't need to
> know Erlang to use Zotonic for most sites or blogs. It doesn't hurt,
> but it isn't required. You can get extremely far with ErlyDTL (the
> template language) and page connections. You can do a surprising
> amount without writing a single line of Erlang.

This is what I suspected reading here and there about Zotonic - my
contention is, it is a very good thing 'cos it leaves the "real work"
to the developer without a headache about the mechanic (well, for me
headache there will be, as I also don't know a jack about JS, but I
learn quite fast when I'm concerned.)

Jean-Yves

**Comment by mworrell** [comment]
If you don't want to write JS, then (for now) you can just use the "deprecated" (but fully functional, and also supported for the foreseeable future) _wires_.

It enables to hook actions to buttons etc.

And for the normal publishing stuff you can come very far with the `search` model and the template language constructs.

I recommend to check the content structure and how we use categories and connections.

From there you can construct pages and other views of the data. You can have search boxes, share buttons, etc. All without any Erlang code or Javascript. Just templates.

**Comment by JiffB** [comment]
> If you don't want to write JS, […] _wires_ .

I think I'll do that while also needing some JS to feed some dynamic tables to display and statistics graphic plotting - I've good confidence I'll find some fine snippets to do that on the web, which will help me to comprehend how JS is articulated and finally cooked it with my own sauce.

> And for the normal publishing stuff you can come very far with the search model and the template language constructs.

As I usually proceed through views, functions and now procedures (Pg V.11) to avoid any direct data access, I think I'll stay on templates with included queries unless passing through search is mandatory to reach the DB connection.

> From there you can construct pages and other views of the data. […]

Good, I need that for the desktop part of my project.

Thanks for the tips.

**Comment by mworrell** [comment]
@JiffB the site install on 0.x has been fixed, and it is now using `.test` instead of `.dev`.
The site install on 1.x is completely different from the 0.x install so no changes were made there.

Will move the example site idea to a separate 1.0 issue.

**Comment by mmzeeman** [comment]
@JiffB For graphics, you can also use SVG of course. That can be put in a template. Otherwise, js is the way to go. For a side project I'm looking at http://dygraphs.com right now.

**Comment by JiffB** [comment]
> @JiffB the site install on 0.x has been fixed, and it is now using `.test` instead of `.dev`.

Thanks.

**Comment by JiffB** [comment]
> @JiffB For a side project I'm looking at http://dygraphs.com right now.

Very nice, I love the detailed points appearing when the mouse is hoverring the curves.

**Comment by mworrell** [comment]
Fixed the 0.x install issue in #2201 

Made a separate issue for the demo site in #2220 - to be added for the 1.x
