### ISSUE TITLE
After merge incoming edge resources are not notified of change

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2204]
Because edge resources are not notified the data is not always fully processed by modules or site while it is updated in the database.

Example:

Page A
Page B
Page C with edge connection to Page B

Page A and Page B are merged. Page A remains and Page B is deleted.
Page C is now connected to Page A in the database.
Page C is still connected to Page B in (for example) elasticsearch since Page C has not been written to elasticsearch index by an observer.

**Comment by mworrell** [comment]
If an edge is updated then a row is added to the `edge_log`.

This row is then read by the edge_log_server and emitted as an `#edge_update{}` notification.

Which notifications does your elastic search indexer use for updating the index?

**Comment by mworrell** [comment]
Solution: trigger a pivot of all affected subject and objects.  The edge merge routines should return the affected resource ids, so that the resource merge routine can emit the pivot requests after the merge has been completed.

**Comment by mworrell** [comment]
Applied fix:  Insert new edges instead of patching the existing edges with a new subject or object id. This ensure correct edge-log entries and with that notifications for the subjects and objects of the winner resource.
