### ISSUE TITLE
Make setting the session cookie optional

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2205]
We have a fallback mechanism in place which allows us to pick up the session id from something else. For some situations, like support for embedded iframes on external sites, it makes sense to use this fallback mechanism. 

A lot of browsers block third party cookies for iframes, so it makes no sense to rely on that mechanism in those situations.

I would like to make setting the session cookie optional via a new, backward compatible flag called `set_session_cookie`. This flag can then be used in dispatch rules like this:

```erlang
{embedded_frame, ["some", "frame"], controller_template, [
     {allow_frame, true},
     {anonymous, true}, 
     {template, "embedded_frame.tpl"}, 
     {ssl, any},
     {set_session_cookie, false}
]}
```

The `set_session_cookie` flag has to be explicitly set to `false`, omitting the flag will set the cookie.

**Comment by mworrell** [comment]
I am ok with this.

Though for the master we need a different strategy, as the session cookie is set by the authentication controller, on request of the client. So there we might want to parametrize the authentication worker to pass a flag to the authentication controller.

You are ok with other cookies, like the language preference?

**Comment by mmzeeman** [comment]
We don't use the other cookies in this special case, so that is fine.

**Comment by mworrell** [comment]
All connected issues are either closed or merges, is this still open?

**Comment by mmzeeman** [comment]
No, I'll close it.
