### ISSUE TITLE
zotonic_fileindexer_cache  error

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2209]
`18:51:46.488 [error] gen_server zotonic_fileindexer_cache terminated with reason: bad argument in call to re:run([1057,1050,1051,1040,1044,1054,1060,1060,46,1056,1060,32,83,86,71,32,40,116,101,120,116,43,101,108,...], {re_pattern,0,0,0,<<69,82,67,80,108,0,0,0,0,0,0,0,1,0,0,0,255,255,255,255,255,255,255,255,0,0,0,...>>}) in zotonic_fileindexer_scan:scan_filename/6 line 55`

**Comment by mworrell** [comment]
Just to be sure: is that really the filename?

When I dump the filename, I see something like: `СКЛАДОФФ.РФ SVG (text+el`

**Comment by mworrell** [comment]
@heiheshang could you check if #2210 fixes your problem?

**Comment by heiheshang** [comment]
`22:27:00.619 [error] gen_server zotonic_fileindexer_cache terminated with reason: bad argument in call to re:run([1057,1050,1051,1040,1044,1054,1060,1060,46,1056,1060,32,83,86,71,32,40,116,101,120,116,43,101,108,...], {re_pattern,0,0,0,<<69,82,67,80,108,0,0,0,0,0,0,0,1,0,0,0,255,255,255,255,255,255,255,255,0,0,0,...>>}) in zotonic_fileindexer_scan:scan_filename/6 line 53
`
it's still a problem

**Comment by mworrell** [comment]
Thanks, also fixed that spot. Can you check on your system?

**Comment by heiheshang** [comment]
strange but i don't see the changes

**Comment by heiheshang** [comment]
confirm this works for me

**Comment by mworrell** [comment]
@heiheshang unicode filename fixes have been merged into master
