### ISSUE TITLE
I can not get into the admin panel

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2211]
`09:15:24.460 [info] UI event: {"type":"error","message":"Uncaught ReferenceError: z_transport_delegate_register is not defined","file":"https://devskl.anriya.ru:8443/admin","line":575,"col":5,"stack":"ReferenceError: z_transport_delegate_register is not defined\n    at window.zotonicPageInit (https://devskl.anriya.ru:8443/admin:575:5)\n    at z_jquery_init (https://devskl.anriya.ru:8443/lib/js/modules/jstz.min~/cotonic/zotonic-wired-bundle~/js/apps/zotonic-wired~z.widgetmanager~/js/modules/z.notice~z.imageviewer~z.dialog~z.clickable~livevalidation-1.3~jquery.loadmask~/bootstrap/js/bootstrap.min~/js/modules/responsive~1108108132.js:8591:16)\n    at z_jquery_init_await (https://devskl.anriya.ru:8443/lib/js/modules/jstz.min~/cotonic/zotonic-wired-bundle~/js/apps/zotonic-wired~z.widgetmanager~/js/modules/z.notice~z.imageviewer~z.dialog~z.clickable~livevalidation-1.3~jquery.loadmask~/bootstrap/js/bootstrap.min~/js/modules/responsive~1108108132.js:8583:9)\n    at https://devskl.anriya.ru:8443/lib/js/modules/jstz.min~/cotonic/zotonic-wired-bundle~/js/apps/zotonic-wired~z.widgetmanager~/js/modules/z.notice~z.imageviewer~z.dialog~z.clickable~livevalidation-1.3~jquery.loadmask~/bootstrap/js/bootstrap.min~/js/modules/responsive~1108108132.js:8578:5","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","url":"https://devskl.anriya.ru:8443/admin"}`

**Comment by mworrell** [comment]
Interesting, that `z_transport_delegate_register` is indeed removed from the zotonic.js file.
I see a reference to it in Pubzub.js but nowhere else.  And Pubzub is being removed.

Do you have any modules that extend the admin or is this a _vanilla_ install?

I will do some more digging.

**Comment by heiheshang** [comment]
I transfer the site from version 0.32 to 1.0

**Comment by heiheshang** [comment]
`11:41:58.634 [error] at: "cowmachine:request_1:97", class: throw, code: 500, dst: #{ip4 => "172.18.0.3",port => 8443}, in: cowmachine, level: error, path: <<"/admin">>, reason: function_clause, src: #{ip4 => "10.28.0.14",port => 37970}, stacktrace: [{depcache,memo,5,[{file,"/opt/zotonic/_build/default/lib/depcache/src/depcache.erl"},{line,153}]},{m_admin_menu,m_get,3,[{file,"/opt/zotonic/apps/zotonic_mod_admin/src/models/m_admin_menu.erl"},{line,41}]},{tpl_a6aa2379dfddb6acca63f10056a0e9194ce338c9,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/_admin_menu.tpl"},{line,18}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,105}]},{template_compiler_runtime_internal,include_1,7,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,202}]},{tpl_7d3fc3e3fcbb1501ce0097a19b7f86b53a39b7b6,render_block,4,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/admin_base.tpl"},{line,42}]},{tpl_7d3fc3e3fcbb1501ce0097a19b7f86b53a39b7b6,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/admin_base.tpl"},{line,41}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,105}]}], text: "Unexpected throw"
11:41:58.637 [error] CRASH REPORT Process <0.2120.0> with 0 neighbours crashed with reason: {stop_request,500,{function_clause,[{filter_force_escape,force_escape,[{"/opt/zotonic/_build/default/lib/depcache/src/depcache.erl","153"},{context,#{bindings => #{zotonic_dispatch => admin,zotonic_dispatch_path => [<<"admin">>],zotonic_site => skl},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"gzip, defl...">>,...},...},...}],...},...]}} in cowmachine_decision_core:handle_request/2 line 41
11:41:58.638 [error] Cowboy stream 243 with ranch listener zotonic_https_listener_ipv4 and connection process <0.1802.0> had its request process exit with reason: {nocatch,{stop_request,500,{function_clause,[{filter_force_escape,force_escape,[{"/opt/zotonic/_build/default/lib/depcache/src/depcache.erl","153"},{context,#{bindings => #{zotonic_dispatch => admin,zotonic_dispatch_path => [<<"admin">>],zotonic_site => skl},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3">>,<<"accept-encoding">> => <<"g...">>,...},...},...}],...},...]}}} in cowmachine_decision_core:handle_request/2 line 41`

**Comment by heiheshang** [comment]
switched to master branch today

**Comment by heiheshang** [comment]
I think the problem is Unicode support. The second site launches to the admin panel without any problems

**Comment by heiheshang** [comment]
i found a problem
`observe_admin_menu(admin_menu`
need to change but it's hard to look
`observe_admin_menu(#admin_menu{}`

**Comment by mworrell** [comment]
Good catch.  I see one in the 2FA module (which was copied from the 0.x).  Did you find other places?

**Comment by heiheshang** [comment]
I use in my module

**Comment by mworrell** [comment]
I updated the `mod_auth2fa` module and also added a note to the upgrade docs.

Thanks!!!
