### ISSUE TITLE
Observe edge insert/delete with current user

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2213]
When you observe an edge insert or delete within a site and try to get the current user it always returns the admin id. So there is no way to know who is inserting of deleting an edge within that function. I would expect that it should be possible to do that.

Currently in z_edge_log_server.erl:do_check() the context is made as an admin. Would it be possible to take the context with the current user in it?

**Comment by mworrell** [comment]
The information about the edge comes from the database edge log table.
That table does not have information about the user performing the action, as it is filled using triggers.

This is a known issue for edge deletions, and tracked in #2115

The user inserting an edge can be derived from the `creator_id` in the edge record.

**Comment by mworrell** [comment]
Closing, as a solution to #2115 should cover this use case as well.
