### ISSUE TITLE
email server crashes

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2215]
```19:33:45.261 [error] gen_server z_email_server terminated with reason: no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008
19:33:45.307 [error] CRASH REPORT Process z_email_server with 0 neighbours crashed with reason: no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008
19:33:45.307 [error] Supervisor zotonic_core_sup had child z_email_server started with z_email_server:start_link() at <0.381.0> exit with reason no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008 in context child_terminated
19:33:50.309 [error] gen_server z_email_server terminated with reason: no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008
19:33:50.309 [error] CRASH REPORT Process z_email_server with 0 neighbours crashed with reason: no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008
19:33:50.309 [error] Supervisor zotonic_core_sup had child z_email_server started with z_email_server:start_link() at <0.1751.0> exit with reason no match of right hand value {aborted,{no_exists,email_queue}} in z_email_server:delete_sent_messages/2 line 1008 in context child_terminated
```

after restarting the docker container, the email server crashes if you do not empty the mnesia file folder

**Comment by mworrell** [comment]
Are there any earlier mnesia or smtp server related error messages?

**Comment by mworrell** [comment]
I have made a branch that should prevent the crash, but it doesn't address the root cause.

Questions:

 * Any earlier mnesia errors?
 * Any earlier email related errors (any email / smtp module)
 * How did you stop / start the container?

**Comment by heiheshang** [comment]
`2019-11-03 19:33:39 =CRASH REPORT====
  crasher:
    initial call: filezcache_entry_manager:-handle_cast/2-fun-0-/0
    pid: <0.256.0>
    registered_name: []
    exception exit: {{aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,351}]},{mnesia,dirty_all_keys,1,[{file,"mnesia.erl"},{line,1886}]},{filezcache_entry_manager,repopulate,0,[{file,"/opt/zotonic/_build/default/lib/filezcache/src/filezcache_entry_manager.erl"},{line,380}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,232}]}]}
    ancestors: [filezcache_entry_manager,filezcache_sup,<0.246.0>]
    message_queue_len: 0
    messages: []
    links: [<0.255.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 207
  neighbours:
    neighbour: [{pid,<0.255.0>},{registered_name,filezcache_entry_manager},{initial_call,{filezcache_entry_manager,init,['Argument__1']}},{current_function,{gen_server,loop,7}},{ancestors,[filezcache_sup,<0.246.0>]},{message_queue_len,0},{links,[<0.247.0>,<0.256.0>]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,10},{reductions,126},{current_stacktrace,[{gen_server,loop,7,[{file,"gen_server.erl"},{line,381}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}]
2019-11-03 19:33:39 =SUPERVISOR REPORT====
     Supervisor: {local,filezcache_sup}
     Context:    child_terminated
     Reason:     {aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}}
     Offender:   [{pid,<0.255.0>},{id,filezcache_entry_manager},{mfargs,{filezcache_entry_manager,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-11-03 19:33:39 =CRASH REPORT====
  crasher:
    initial call: filezcache_entry_manager:-handle_cast/2-fun-0-/0
    pid: <0.259.0>
    registered_name: []
    exception exit: {{aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,351}]},{mnesia,dirty_all_keys,1,[{file,"mnesia.erl"},{line,1886}]},{filezcache_entry_manager,repopulate,0,[{file,"/opt/zotonic/_build/default/lib/filezcache/src/filezcache_entry_manager.erl"},{line,380}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,232}]}]}
    ancestors: [filezcache_entry_manager,filezcache_sup,<0.246.0>]
    message_queue_len: 0
    messages: []
    links: [<0.258.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 207
  neighbours:
    neighbour: [{pid,<0.258.0>},{registered_name,filezcache_entry_manager},{initial_call,{filezcache_entry_manager,init,['Argument__1']}},{current_function,{gen_server,loop,7}},{ancestors,[filezcache_sup,<0.246.0>]},{message_queue_len,0},{links,[<0.247.0>,<0.259.0>]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,10},{reductions,126},{current_stacktrace,[{gen_server,loop,7,[{file,"gen_server.erl"},{line,381}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}]
2019-11-03 19:33:39 =SUPERVISOR REPORT====
     Supervisor: {local,filezcache_sup}
     Context:    child_terminated
     Reason:     {aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}}
     Offender:   [{pid,<0.258.0>},{id,filezcache_entry_manager},{mfargs,{filezcache_entry_manager,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-11-03 19:33:39 =CRASH REPORT====
  crasher:
    initial call: filezcache_entry_manager:-handle_cast/2-fun-0-/0
    pid: <0.262.0>
    registered_name: []
    exception exit: {{aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,351}]},{mnesia,dirty_all_keys,1,[{file,"mnesia.erl"},{line,1886}]},{filezcache_entry_manager,repopulate,0,[{file,"/opt/zotonic/_build/default/lib/filezcache/src/filezcache_entry_manager.erl"},{line,380}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,232}]}]}
    ancestors: [filezcache_entry_manager,filezcache_sup,<0.246.0>]
    message_queue_len: 0
    messages: []
    links: [<0.261.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 207
  neighbours:
    neighbour: [{pid,<0.261.0>},{registered_name,filezcache_entry_manager},{initial_call,{filezcache_entry_manager,init,['Argument__1']}},{current_function,{gen_server,loop,7}},{ancestors,[filezcache_sup,<0.246.0>]},{message_queue_len,0},{links,[<0.247.0>,<0.262.0>]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,10},{reductions,126},{current_stacktrace,[{gen_server,loop,7,[{file,"gen_server.erl"},{line,381}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}]
2019-11-03 19:33:39 =SUPERVISOR REPORT====
     Supervisor: {local,filezcache_sup}
     Context:    child_terminated
     Reason:     {aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}}
     Offender:   [{pid,<0.261.0>},{id,filezcache_entry_manager},{mfargs,{filezcache_entry_manager,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-11-03 19:33:39 =CRASH REPORT====
  crasher:
    initial call: filezcache_entry_manager:-handle_cast/2-fun-0-/0
    pid: <0.265.0>
    registered_name: []
    exception exit: {{aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}},[{mnesia,abort,1,[{file,"mnesia.erl"},{line,351}]},{mnesia,dirty_all_keys,1,[{file,"mnesia.erl"},{line,1886}]},{filezcache_entry_manager,repopulate,0,[{file,"/opt/zotonic/_build/default/lib/filezcache/src/filezcache_entry_manager.erl"},{line,380}]},{proc_lib,init_p,3,[{file,"proc_lib.erl"},{line,232}]}]}
    ancestors: [filezcache_entry_manager,filezcache_sup,<0.246.0>]
    message_queue_len: 0
    messages: []
    links: [<0.264.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 610
    stack_size: 27
    reductions: 207
  neighbours:
    neighbour: [{pid,<0.264.0>},{registered_name,filezcache_entry_manager},{initial_call,{filezcache_entry_manager,init,['Argument__1']}},{current_function,{gen_server,loop,7}},{ancestors,[filezcache_sup,<0.246.0>]},{message_queue_len,0},{links,[<0.247.0>,<0.265.0>]},{trap_exit,false},{status,waiting},{heap_size,233},{stack_size,10},{reductions,126},{current_stacktrace,[{gen_server,loop,7,[{file,"gen_server.erl"},{line,381}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}]
2019-11-03 19:33:39 =SUPERVISOR REPORT====
     Supervisor: {local,filezcache_sup}
     Context:    child_terminated
     Reason:     {aborted,{no_exists,[filezcache_log_entry,[{{filezcache_log_entry,'$1','_','_','_'},[],['$1']}]]}}
     Offender:   [{pid,<0.264.0>},{id,filezcache_entry_manager},{mfargs,{filezcache_entry_manager,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-11-03 19:33:39 =SUPERVISOR REPORT====
     Supervisor: {local,filezcache_sup}
     Context:    shutdown
     Reason:     reached_max_restart_intensity
     Offender:   [{pid,<0.264.0>},{id,filezcache_entry_manager},{mfargs,{filezcache_entry_manager,start_link,[]}},{restart_type,permanent},{shutdown,2000},{child_type,worker}]

2019-11-03 19:33:45 =ERROR REPORT====
** Generic server z_email_server terminating 
** Last message in was poll
** When Server state == {state,false,[],false,false,undefined,undefined,[],240}
** Reason for termination == 
** {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-11-03 19:33:45 =CRASH REPORT====
  crasher:
    initial call: z_email_server:init/1
    pid: <0.381.0>
    registered_name: z_email_server
    exception error: {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [zotonic_core_sup,zotonic_launcher_sup,<0.359.0>]
    message_queue_len: 0
    messages: []
    links: [<0.195.0>,<0.377.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 1017
  neighbours:
2019-11-03 19:33:45 =SUPERVISOR REPORT====
     Supervisor: {local,zotonic_core_sup}
     Context:    child_terminated
     Reason:     {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.381.0>},{id,z_email_server},{mfargs,{z_email_server,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]

2019-11-03 19:33:50 =ERROR REPORT====
** Generic server z_email_server terminating 
** Last message in was poll
** When Server state == {state,false,[],false,false,undefined,undefined,[],240}
** Reason for termination == 
** {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
2019-11-03 19:33:50 =CRASH REPORT====
  crasher:
    initial call: z_email_server:init/1
    pid: <0.1751.0>
    registered_name: z_email_server
    exception error: {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
    ancestors: [zotonic_core_sup,zotonic_launcher_sup,<0.359.0>]
    message_queue_len: 0
    messages: []
    links: [<0.195.0>,<0.377.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 983
  neighbours:
2019-11-03 19:33:50 =SUPERVISOR REPORT====
     Supervisor: {local,zotonic_core_sup}
     Context:    child_terminated
     Reason:     {{badmatch,{aborted,{no_exists,email_queue}}},[{z_email_server,delete_sent_messages,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1008}]},{z_email_server,poll_queued,1,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,1121}]},{z_email_server,handle_info,2,[{file,"/opt/zotonic/apps/zotonic_core/src/smtp/z_email_server.erl"},{line,311}]},{gen_server,try_dispatch,4,[{file,"gen_server.erl"},{line,616}]},{gen_server,handle_msg,6,[{file,"gen_server.erl"},{line,686}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}
     Offender:   [{pid,<0.1751.0>},{id,z_email_server},{mfargs,{z_email_server,start_link,[]}},{restart_type,permanent},{shutdown,5000},{child_type,worker}]`

**Comment by heiheshang** [comment]
`docker-compose run --service-ports zotonic bash`

**Comment by heiheshang** [comment]
`docker-compose stop
docker-compose rm`

**Comment by mworrell** [comment]
Thanks, will do some testing this week.
Weird problem.

**Comment by mworrell** [comment]
@ddeboer do you recognize this Docker problem?  Seems mnesia is not happy on Docker?

**Comment by mworrell** [comment]
Similar to #2245
