### ISSUE TITLE
log-client-event dispatch is optional but built-in into core.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2226]
The dispatch to log client event is located in `mod_logging`, this module is optional. But the logging itself is built into core `zotonic.js`. This will result in `404` responses when client errors are logged.

Is it ok to make a dispatch for this path in `mod_base` which just returns `204` no-content?

<img width="611" alt="Screenshot 2019-11-07 at 15 21 50" src="https://user-images.githubusercontent.com/1024972/68418423-7d799c00-0198-11ea-9d79-e62f0ab7e994.png">

<img width="797" alt="Screenshot 2019-11-07 at 15 20 24" src="https://user-images.githubusercontent.com/1024972/68418447-879b9a80-0198-11ea-865b-8c36abc441c2.png">

**Comment by mworrell** [comment]
Good one. I propose to add a _black hole_ controller and a dispatch rule to that controller.

**Comment by mworrell** [comment]
So, yes, go ahead 👍

**Comment by mmzeeman** [comment]
👍

**Comment by mmzeeman** [comment]
Needs to be implemented for 1.0 as well

**Comment by mworrell** [comment]
Moving issue to 1.0, as it if fixed on the 0.x
