### ISSUE TITLE
addsite escript in latest master

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2227]
While attempting to setup test site, I updated to latest master, recompiled and performed the following:

> [zotonic@zotonic ~/zotonic]$ bin/zotonic addsite -s blog testsite
escript: exception error: not_implemented
  in function  zotonic_cmd_addsite:run/1 (/usr/home/zotonic/zotonic/apps/zotonic_launcher/src/command/zotonic_cmd_addsite.erl, line 59)
  in call from erl_eval:local_func/6 (erl_eval.erl, line 567)
  in call from escript:interpret/4 (escript.erl, line 788)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1 
  in call from init:do_boot/3 
[zotonic@zotonic ~/zotonic]$ 

However, adding a site using the status page works as expected.

**Comment by mworrell** [comment]
This is correct, I am adding the `addsite` escript in https://github.com/zotonic/zotonic/pull/2199
That branch also contains more changes and fixes, especially for handling config files and compiling/loading new applications.

**Comment by mworrell** [comment]
Good to hear that adding a site on the status page worked well for you.

Closing this as it will be fixed in #2199
