### ISSUE TITLE
z_controller_helper does not consider json encoding

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2237]
maybe I'm wrong, but from_json does not account for the encoding in the header
`{Body, Context1} = req_body(Context),                                                                                              
    Data = jsxrecord:decode(Body),                                                                                                     
    {Data, Context1}. `
I get data in utf-8 and I have to convert it myself since there is Cyrillic

**Comment by mworrell** [comment]
It should just accept utf8 as the character set:

```
(zotonic@PoToi)1> jsxrecord:decode(<<"{ \"a\":\"éüç\" }"/utf8>>).
#{<<"a">> => <<"éüç"/utf8>>}
```

We don't accept any other character set.

**Comment by mworrell** [comment]
Can you give an example of your data?

**Comment by heiheshang** [comment]
`#{<<"agreement">> => <<>>,<<"primer">> => <<208,191,209,128,208,19
0,208,178,208,181,209,128,208,186,208,176>>,<<"queryText">> => <<"Ð´Ð°">>}`

**Comment by heiheshang** [comment]
`unicode:characters_to_list(maps:get(<<"queryText">>,Payload))`
I do the conversion myself in my code

**Comment by mworrell** [comment]
Was the queryText coming from the user or from Erlang?

If you use Erlang then you have to add `/utf8` to the binary, like this:  `<<"Grün"/utf8>>`

**Comment by mworrell** [comment]
Afaik `unicode:characters_to_list/1` consumes iodata with `unicode` (alias for `utf8`) encoding and translates it to a list with unicode code points.  Might it be that you need a list and not an utf-8 binary?

**Comment by heiheshang** [comment]
message comes from another program

**Comment by heiheshang** [comment]
I want to make a match << "Да" >> with << ""Ð´Ð°"" >>

**Comment by mworrell** [comment]
` <<"Да"/utf8>>` is equal to `<<208,148,208,176>>`.

I think the `<<"Ð´Ð°">>` you are seeing is actually the latin1 representation of `<<208,148,208,176>>`

**Comment by mworrell** [comment]
Closed issue due to inactivity.
