### ISSUE TITLE
docker start_nodaemon vs start-nodaemon: cannot start

### ISSUE THREAD

**Issue by jontow** [zotonic/zotonic#2242]
In various places, there is mixed use of "start-nodaemon", but the actual command is "start_nodaemon" (hyphen vs underscore).  This prevents docker images from starting.

Known places this can be found:
* Dockerfile
* Dockerfile.heavy
* apps/zotonic_launcher/bin/zotonic
* docker/s6-service/zotonic/run

There is a related bug in docker/docker-entrypoint.sh which checks for a .erl file being executable, but does not directly execute that file, it simply needs to check if it exists.

To reproduce, attempt to start a docker container (either built yourself or published at dockerhub): specifically zotonic-heavy is the one in use here.  I am using git master and building images myself, on Ubuntu Linux/x86-64.

**Comment by mworrell** [comment]
Thank you for fixing this problem, great work!
