### ISSUE TITLE
Create site command not working

### ISSUE THREAD

**Issue by sujankumar4593** [zotonic/zotonic#2246]
I am new to zotonic, I installed the zotonic and tried to create the sample site and I follow the doc but it showing the error (commit - a1b4ef6a586c34d11dcece3fe1459e25248b07fc)
[Doc link http://docs.zotonic.com/en/stable/developer-guide/sites.html]
erlang OTP version -- 20

ERROR
```
$bin/zotonic addsite -s blog bloglocal
Please specify the hostname, for example: -H yoursite.test
```
Please help

**Comment by mworrell** [comment]
Did you try to supply the hostname?

> $bin/zotonic addsite -s blog -H bloglocal.test bloglocal

**Comment by mworrell** [comment]
Be advised that this will work with the `0.x` brach.  On the master (1.x) branch we are reworking the addsite command.

**Comment by sujankumar4593** [comment]
Thanks for the update:)

**Comment by mworrell** [comment]
Closing for now.
