### ISSUE TITLE
Add site via status site

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2250]
When attempting to add a new site using the Zotonic status site, the following is reported:

> 02:06:17.854 [info] mod_zotonic_site_management:52 [zotonic_site_status] Creating site test with [{hostname,<<"test.test">>},{skeleton,<<"blog">>},{dbdatabase,<<"zotonic">>},{dbschema,<<"test">>},{dbhost}<<"localhost">>},{dbport,<<"5432">>},{dbuser,<<"zotonic">>},{dbpassword,<<"password">>}]
02:06:17.863 [error] z_db:721 Cannot create database "zotonic" because user "zotonic" cannot connect to the 'postgres' database: invalid_authorization_specification

Using Postgresql 12.1 and the latest master.

**Comment by mworrell** [comment]
Postgres doesn't allow you to connect.
Did you allow connections in your `pg_hba.conf` file?

http://docs.zotonic.com/en/latest/ref/installation/requirements.html?highlight=pg_hba#enabling-trust-authentication-in-postgresql

It might be an idea to add this to the installation screens. What do you think?

**Comment by seannaswell** [comment]
Yes, `pg_hba.conf` has been modified, and when executing `psql -U zotonic` the database connection is made. Also get the same error when using the addsite command:

> [zotonic@zotonic ~/zotonic]$ bin/zotonic addsite -s blog -H test.seannaswell.com test
Resolving the hostname ...
Checking database ...
Error: Could not connect to 'postgres' database or create the database.

Will do a but more looking on my end, seems others would be reporting, so must be something going on locally.

**Comment by seannaswell** [comment]
Issue resolved, had to modify `pg_hba.conf`:
> host    all         zotonic     10.x.x.x/24      md5

Related to running in a jail on FreeBSD.

**Comment by mworrell** [comment]
Great that you figured this out, and thanks for coming back with the solution.

**Comment by mworrell** [comment]
I remember seeing some work on pipe support in epgsql.  If that is done then we can start connecting locally using pipes, removing the need for this config change.
