### ISSUE TITLE
Name clashes in code paths

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#2253]
There are a couple of beam files with the same name on a fresh install of 0.x. 

I'm not experiencing any issues though.

```
** /zotonic/deps/qdate_localtime/ebin/localtime_dst.beam hides /zotonic/deps/erlang_localtime/ebin/localtime_dst.beam
** /zotonic/deps/qdate_localtime/ebin/ibuild.beam hides /zotonic/deps/erlang_localtime/ebin/ibuild.beam
** /zotonic/deps/qdate_localtime/ebin/localtime.beam hides /zotonic/deps/erlang_localtime/ebin/localtime.beam
```

**Comment by mworrell** [comment]
Yes, it seems we get the two via different dependencies.
We should have a look where/how they are included in the rebar.config files, and if one is really more modern that the other.

**Comment by rl-king** [comment]
So qdate_localtime is a fork of erlang_localtime with the intend to support qdate.

**localtime_dst.erl** is identical
* https://github.com/dmitryme/erlang_localtime/blob/master/src/localtime_dst.erl
* https://github.com/choptastic/qdate_localtime/blob/master/src/localtime_dst.erl

**ibuild.erl**, `qdate_localtime`has one change, which seems to be a formatting thing. https://github.com/choptastic/qdate_localtime/commit/67b61c8f9414bea13338da85faae4bf282e87457#diff-7d560fe7a29ec7ce11a618b94a9293b4
* https://github.com/dmitryme/erlang_localtime/blob/master/src/ibuild.erl
* https://github.com/choptastic/qdate_localtime/blob/master/src/ibuild.erl

**localtime.erl** `qdate_localtime` adds `fmt_shift/1` and has `get_timezone` throw if not supplied with string or binary.
* https://github.com/dmitryme/erlang_localtime/blob/master/src/localtime.erl
* https://github.com/choptastic/qdate_localtime/blob/master/src/localtime.erl

Just some info about the files that clash.

**Comment by mworrell** [comment]
Weird, this duplication of code, we do need qdate for its extra functionality.

I do see that we both include `erlang_localtime` and `qdate` in our central rebar file.
I will remove `erlang_localtime` and push a branch to check.
