### ISSUE TITLE
loading csv files does not work

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2260]
`09:16:28.847 [info] Could not decode multipart (<<"----WebKitFormBoundaryK3BjUAwKsWVyMomR">>) chunk: <<>>`
in console
`z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z.cropcenter~z.popupwindow~z.zeditor~livevalidation-1.3~jquery.loadmask~jquery.timepicker.min~2693510684.js:8357 Uncaught ReferenceError: z_transport_ensure is not defined
    at HTMLIFrameElement.cb (z.adminwidget~z.live~z.notice~z.tooltip~z.dialog~z.feedback~z.formreplace~z.datepicker~z.menuedit~z.cropcenter~z.popupwindow~z.zeditor~livevalidation-1.3~jquery.loadmask~jquery.timepicker.min~2693510684.js:8357)`

**Comment by heiheshang** [comment]
the problem is observed in opere, chrome everything is OK

**Comment by mworrell** [comment]
Just to be sure that I can replicate this:

 * Which form do you use?
 * What version of Opera do you use?

There seems to be two unrelated issues here, one reference to `z_transport_ensure` and something with the format of the multipart message by Opera.

**Comment by heiheshang** [comment]
64.0.3417.83
openSUSE Tumbleweed (x86_64; XFCE)

**Comment by mworrell** [comment]
Removed the old `z_transport_ensure` call in d7fb5a78d

**Comment by mworrell** [comment]
Looking at the code, the upload error seems to happen when a multipart message without body is sent.

**Comment by mworrell** [comment]
I just tried with Opera 65 and the newest master and could upload a CSV file.

**Comment by heiheshang** [comment]
`Looking at the code, the upload error seems to happen when a multipart message without body is sent.`
in console opera

**Comment by mworrell** [comment]
Can you check what kind of frame that is?

**Comment by heiheshang** [comment]
how ?

**Comment by mworrell** [comment]
No message in Opera?  Or a list of frames?

We do use an `iframe` to post the form to. But that particular iframe is on the the same origin, so shouldn't give any error.

It might also be that a 403 page or some other error page is loaded in the iframe and that it tries to autofocus on the login fields.

**Comment by heiheshang** [comment]
Request URL: https://xn--80aaxhsfwd4b8e.xn--p1ai/mqtt-transport/zotonic-transport/postback
Request Method: POST
Status Code: 400 Bad Request (from ServiceWorker)
Referrer Policy: origin-when-cross-origin

allow: GET, HEAD
Connection: keep-alive
Content-Length: 0
Date: Tue, 03 Dec 2019 09:51:44 GMT
referrer-policy: origin-when-cross-origin
Server: nginx/1.14.2
x-content-type-options: nosniff
x-dtap-environment: production
x-frame-options: sameorigin
x-permitted-cross-domain-policies: none
x-xss-protection: 1


Provisional headers are shown
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryC4vcr83yrducegWA
Origin: https://xn--80aaxhsfwd4b8e.xn--p1ai
Referer: https://xn--80aaxhsfwd4b8e.xn--p1ai/cargo/load
Sec-Fetch-Mode: nested-navigate
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.83

**Comment by heiheshang** [comment]
Request URL: https://xn--80aaxhsfwd4b8e.xn--p1ai/mqtt-transport/zotonic-transport/postback
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 195.208.32.39:443
Referrer Policy: origin-when-cross-origin

allow: GET, HEAD
Connection: keep-alive
Content-Length: 0
Date: Tue, 03 Dec 2019 09:51:44 GMT
referrer-policy: origin-when-cross-origin
Server: nginx/1.14.2
x-content-type-options: nosniff
x-dtap-environment: production
x-frame-options: sameorigin
x-permitted-cross-domain-policies: none
x-xss-protection: 1

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3
Accept-Encoding: gzip, deflate, br
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 0
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryC4vcr83yrducegWA
Cookie: z.lang=ru; z.auth=37nyJHU5PAzXt09LWAzw5fnfiwWQBwjYKtgQJHJk_hi57TvpNxx8CL8-zOReuLsl3uK2K2ppdCHYuk4TN-PzUGIQUJ_BXXnOeWVF5HaMq0GtaB0-eSvzMT-jKc1TiAfLiP5B4AWlmo4pRf4; z.tz=UTC
Host: xn--80aaxhsfwd4b8e.xn--p1ai
Origin: https://xn--80aaxhsfwd4b8e.xn--p1ai
Pragma: no-cache
Referer: https://xn--80aaxhsfwd4b8e.xn--p1ai/cargo/load
Sec-Fetch-Mode: same-origin
Sec-Fetch-Site: same-origin
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.83

**Comment by mworrell** [comment]
I think the key here is `Content-Length: 0`
Somehow Opera is sending an empty message, which is illegal for multipart messages (should have at least one boundary)

Because the message is illegal the server returns a `400 Bad Request`.

**Comment by mworrell** [comment]
Closing for now, as it seems to be a non reproducible Opera issue.
