### ISSUE TITLE
Cowmachine Error 500

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2261]
When logging into admin on test site, see the error below. 

> 00:59:09.201 [error] at: "cowmachine:request_1:82", code: 500, dst: #{ip4 => "10.x.x.x",port => 8000}, in: cowmachine, level: error, path: <<"/en/admin/edit/page_home">>, reason: {badarg,[{erlang,integer_to_binary,[none],[]},{z_context,abs_url,2,[{file,"/usr/home/zotonic/zotonic/apps/zotonic_core/src/support/z_context.erl"},{line,383}]},{z_dispatcher,abs_url,4,[{file,"/usr/home/zotonic/zotonic/apps/zotonic_core/src/support/z_dispatcher.erl"},{line,218}]},{z_dispatcher,opt_abs_url,4,[{file,"/usr/home/zotonic/zotonic/apps/zotonic_core/src/support/z_dispatcher.erl"},{line,212}]},{z_dispatcher,url_for,3,[{file,"/usr/home/zotonic/zotonic/apps/zotonic_core/src/support/z_dispatcher.erl"},{line,100}]},{tpl_e32d15eee9193c8ee2108d6bc3cdd9694a74d84b,render,3,[{file,"/home/zotonic/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/_admin_navbar_brand.tpl"},{line,1}]},{template_compiler,render,4,[{file,"/usr/home/zotonic/zotonic/_build/defaul..."},...]},...]}, src: #{ip4 => "10.x.x.x",port => 57160}, text: "Stop request"

Pic related:

![zotonic-500](https://user-images.githubusercontent.com/17067735/70024610-49f41c80-1560-11ea-818f-961f44847510.png)

**Comment by mworrell** [comment]
I think I have a fix in #2262, could you give it a try?

**Comment by mworrell** [comment]
@seannaswell if the problem persists, can you reopen this issue?

**Comment by seannaswell** [comment]
Problem resolved, thanks.
