### ISSUE TITLE
Extremely slow SQL query

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2264]
`22:27:15.857 [error] Error in memo exit:{timeout,{gen_server,call,[<0.862.0>,{equery,"\n                                select *\n                                from rsc r\n                                    join hierarchy c\n                                    on r.category_id = c.id and c.name = '$category'\n                                where $1 <= c.nr\n                                  and c.nr <= $2\n                                order by r.name",[92000000,92000000]},30000]}} in [{gen_server,call,3,[{file,"gen_server.erl"},{line,214}]},{z_db,assoc1,5,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,941}]},{z_db,'-assoc_props/4-fun-0-',5,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,308}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,227}]},{m_predicate,'-all/1-fun-2-',1,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_predicate.erl"},{line,162}]},{depcache,memo,5,[{file,"/opt/zotonic/_build/default/lib/depcache/src/depcache.erl"},{line,134}]},{m_predicate,get,2,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_predicate.erl"},{line,134}]}]
22:27:15.857 [error] Error in process <0.3257.0> on node zotonic@2b3d5ed5623e with exit value:
{{nocatch,{timeout,{gen_server,call,[<0.862.0>,{equery,"\n                                select *\n                                from rsc r\n                                    join hierarchy c\n                                    on r.category_id = c.id and c.name = '$category'\n                                where $1 <= c.nr\n                                  and c.nr <= $2\n                                order by r.name",[92000000,92000000]},30000]}}},[{depcache,memo,5,[{file,"/opt/zotonic/_build/default/lib/depcache/src/depcache.erl"},{line,153}]},{m_predicate,get,2,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_predicate.erl"},{line,134}]},{m_predicate,m_get,3,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_predicate.erl"},{line,61}]},{tpl_4bfe8237c0d09563be5fb438773deb5e084036e4,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/_action_dialog_new_rsc_tab.tpl"},{line,43}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,105}]},{template_compiler_runtime_internal,include_1,7,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,202}]},{tpl_b45ecbcd8c39ccc47253ec71cb201967051ba750,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/_action_dialog_connect_tab_findnew.tpl"},{line,2}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,105}]}]}`

**Comment by mworrell** [comment]
That is a timeout. The query lasted longer than 30 seconds. I think it is the query that fetches the list of categories, which is quite short.

Is the machine where your db is running very busy or swapping?

**Comment by heiheshang** [comment]
I would not say that she is busy, but I write intensively resources

**Comment by heiheshang** [comment]
I stopped everything, the problem is still observed

**Comment by heiheshang** [comment]
maybe the base is too big, not enough indexes?

**Comment by mworrell** [comment]
How large is your `rsc` table?

I have never seen this query time out, as 30 seconds should be more than enough to fetch the list of predicates.

**Comment by heiheshang** [comment]
I counted the size of the rsc table 5942249, size is not big but everything is very slow

**Comment by heiheshang** [comment]
`Gather Merge  (cost=338208.82..360430.24 rows=190456 width=1782) (actual time=141780.091..141837.823 rows=11 loops=1)
   Workers Planned: 2
   Workers Launched: 2
   ->  Sort  (cost=337208.79..337446.86 rows=95228 width=1782) (actual time=141760.795..141760.796 rows=4 loops=3)
         Sort Key: r.name
         Sort Method: quicksort  Memory: 33kB
         Worker 0:  Sort Method: quicksort  Memory: 25kB
         Worker 1:  Sort Method: quicksort  Memory: 25kB
         ->  Hash Join  (cost=0.80..296755.97 rows=95228 width=1782) (actual time=94509.001..141760.749 rows=4 loops=3)
               Hash Cond: (r.category_id = c.id)
               ->  Parallel Index Scan using fki_rsc_name on rsc r  (cost=0.43..289196.85 rows=2475937 width=1739) (actual time=1.555..141059.109 rows=1980750 loops=3)
               ->  Hash  (cost=0.36..0.36 rows=1 width=34) (actual time=0.030..0.030 rows=1 loops=3)
                     Buckets: 1024  Batches: 1  Memory Usage: 9kB
                     ->  Index Scan using hierarchy_nr_key on hierarchy c  (cost=0.14..0.36 rows=1 width=34) (actual time=0.021..0.032 rows=1 loops=3)
                           Index Cond: (((name)::text = '$category'::text) AND (92000000 <= nr) AND (nr <= 92000000))
 Planning Time: 53.778 ms
 Execution Time: 141839.406 ms
(17 rows)
`

**Comment by heiheshang** [comment]
`Gather Merge  (cost=48926.72..71148.13 rows=190456 width=1782)
   Workers Planned: 2
   ->  Sort  (cost=47926.69..48164.76 rows=95228 width=1782)
         Sort Key: r.name
         ->  Merge Join  (cost=0.81..7473.87 rows=95228 width=1782)
               Merge Cond: (r.category_id = c.id)
               ->  Parallel Index Scan using fki_rsc_category on rsc r  (cost=0.43..824487.20 rows=2475937 width=1739)
               ->  Sort  (cost=0.37..0.38 rows=1 width=34)
                     Sort Key: c.id
                     ->  Index Scan using hierarchy_nr_key on hierarchy c  (cost=0.14..0.36 rows=1 width=34)
                           Index Cond: (((name)::text = '$category'::text) AND (92000000 <= nr) AND (nr <= 92000000))
(11 rows)
`

**Comment by heiheshang** [comment]
added two indexes by name and category_id then it starts working fine

**Comment by heiheshang** [comment]
`select r.id from rsc r where r.pivot_category_nr = 98006000 and (publication_start  <  '2019-12-04T13:45:06') and r.id <> 5967007  order by publication_start DESC, id DESC limit 1`

`Limit  (cost=847795.99..847796.11 rows=1 width=12)
   ->  Gather Merge  (cost=847795.99..1420952.61 rows=4912428 width=12)
         Workers Planned: 2
         ->  Sort  (cost=846795.97..852936.50 rows=2456214 width=12)
               Sort Key: publication_start DESC, id DESC
               ->  Parallel Seq Scan on rsc r  (cost=0.00..834514.90 rows=2456214 width=12)
                     Filter: ((publication_start < '2019-12-04 13:45:06+09'::timestamp with time zone) AND (id <> 5967007) AND (pivot_category_nr = 98006000))
`
`Limit  (cost=0.67..0.67 rows=1 width=12)
   ->  Sort  (cost=0.67..0.67 rows=1 width=12)
         Sort Key: publication_start DESC, id DESC
         ->  Index Scan using rsc_pivot_date_start_key on rsc r  (cost=0.43..0.66 rows=1 width=12)
               Index Cond: (pivot_date_start < '2019-12-04 13:45:06+09'::timestamp with time zone)
               Filter: ((id <> 5967007) AND (pivot_category_nr = 98006000))
(6 rows)
`

after adding publication_start indexes

**Comment by heiheshang** [comment]
fine tuning postgresql is needed, it just doesn’t work with such volumes

**Comment by mworrell** [comment]
How many rows do you have with `pivot_category_nr = 98006000` ?   2.4M ?

**Comment by heiheshang** [comment]
`zotonic=# select count(*) from rsc where pivot_category_nr=98006000;
  count  
---------
 5890109
(1 row)`

**Comment by mworrell** [comment]
On the `rsc` table we indeed miss an index on `category_id`, that should be added.
There is already a key on name `rsc_name_key` that is a unique constraint.

Maybe we need have a combine key on `pivot_category_nr` and `publication_start`?  That would enable fetching all keys within a certain publication date range.  Could you check if that would help in your case?  I am wondering if it would be good enough, as we might have a range for the category_nr.

**Comment by mworrell** [comment]
Or maybe `(category_id, publication_start)` and then we only do the range by joining the rsc table with the hierarchy table (like in your first example). In that case we also don't need to have the `pivot_category_nr` on the rsc table.

**Comment by heiheshang** [comment]
`create index fki_pivot_category_pub_id on rsc(id,publication_start,pivot_category_nr);`
I tried to make a combination key and it works for me

**Comment by mworrell** [comment]
Great, thanks for trying this out.

Why did you include `id` in the key?

**Comment by mworrell** [comment]
I am wondering if it is better to have (category, pubstart) or (pubstart, category)

**Comment by heiheshang** [comment]
> I am wondering if it is better to have (category, pubstart) or (pubstart, category)

I tried indexing the whole condition in the query

**Comment by mworrell** [comment]
Thanks for checking this, I will check with some other systems which have > 1M rows as well and then add some extra indices.

**Comment by mworrell** [comment]
I tried on a system with 2M rows an I see that (pubstart, category) and similar indices give the best performance boost.  Need to do some additional checks to see how psql nowadays selects the indices to decide which indices we keep and which ones we will remove.

**Comment by mworrell** [comment]
@heiheshang which version of psql do you use?

**Comment by heiheshang** [comment]
`psql (11.2)`
