### ISSUE TITLE
problem slug

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2265]
`{{case_clause,{error,{{badmatch,{error,{error,error,<<"42601">>,syntax_error,<<"multiple assignments to same column \"slug\"">>,[{file,<<"rewriteHandler.c">>},{line,<<"1001">>},{routine,<<"process_matched_tle">>},{severity,<<"ERROR">>}]}}},[{m_rsc_update,update_transaction_fun_db,7,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_rsc_update.erl"},{line,631}]},{m_rsc_update,update_transaction_filter_props,4,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_rsc_update.erl"},{line,503}]},{z_db,'-transaction1/2-fun-0-',3,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,150}]},{timer,tc,2,[{file,"timer.erl"},{line,181}]},{z_db,with_connection,3,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,227}]},{z_db,transaction1,2,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,141}]},{z_db,transaction,3,[{file,"/opt/zotonic/apps/zotonic_core/src/db/z_db.erl"},{line,110}]},{m_rsc_update,update_transaction,3,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_rsc_update.erl"},{line,420}]}]}}},[{controller_admin_edit,event,2,[{file,"/opt/zotonic/apps/zotonic_mod_admin/src/controllers/controller_admin_edit.erl"},{line,105}]},{z_transport,incoming_postback_event,6,[{file,"/opt/zotonic/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,127}]},{z_transport,transport,3,[{file,"/opt/zotonic/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,63}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]}]}
`

**Comment by heiheshang** [comment]
`z_db error {error,error,<<"42601">>,syntax_error,<<"multiple assignments to same column \"slug\"">>,[{file,<<"rewriteHandler.c">>},{line,<<"1001">>},{routine,<<"process_matched_tle">>},{severity,<<"ERROR">>}]} in query update "rsc" set "props" = $2, "pivot_date_start" = $3, "pivot_date_end" = $4, "pivot_date_start_month_day" = $5, "pivot_date_end_month_day" = $6, "pivot_title" = $7, "modifier_id" = $8, "modified" = $9, "version" = $10, "publication_start" = $11, "publication_end" = $12, "page_path" = $13, "name" = $14, "slug" = $15, "slug" = $16, "is_published" = $17, "is_featured" = $18, "is_protected" = $19, "is_dependent" = $20 where id = $1 with [5967008,{term,[{title_slug,{trans,[{ru,<<208,176,208,178,209,130,208,190,208,188,208,176,209,130,209,139>>}]}},{title,{trans,[{ru,<<208,144,208,178,209,130,208,190,208,188,208,176,209,130,209,139>>}]}},{tz,<<"UTC">>},{phone,<<>>},{phone_mobile,<<>>},{phone_alt,<<>>},{phone_emergency,<<>>},{website,<<>>},{is_website_redirect,false},{email,<<>>},{address_country,<<>>},{address_street_1,<<>>},{address_street_2,<<>>},{address_city,<<>>},{address_postcode,<<>>},{address_state,<<>>},{mail_email,<<>>},{mail_country,<<>>},{mail_street_1,<<>>},{mail_street_2,<<>>},{mail_city,<<>>},{mail_postcode,<<>>},{mail_state,<<>>},{is_page_path_multiple,false},{custom_slug,true},{seo_noindex,true},{seo_desc,<<>>},{privacy,0},{date_is_all_day,false},{language,[ru]},{summary,{trans,[{ru,<<>>}]}},{short_title,{trans,[{ru,<<>>}]}},{body,{trans,[{ru,<<>>}]}},{date_remarks,{trans,[{ru,<<>>}]}},{blocks,[]}]},undefined,undefined,undefined,undefined,<<208,176,208,178,209,130,208,190,208,188,208,176,209,130,209,139>>,1,{{2019,12,5},{4,51,24}},4,{{2019,12,5},{2,13,0}},{{9999,8,17},{12,0,0}},undefined,<<"automats">>,<<208,176,208,178,209,130,208,190,208,188,208,176,209,130,209,139>>,<<208,176,208,178,209,130,208,190,208,188,208,176,209,130,209,139>>,true,false,false,false]
`

**Comment by mworrell** [comment]
Just to be sure, this is when you checked the "custom slug" option?

**Comment by heiheshang** [comment]
yes

**Comment by mworrell** [comment]
Thanks for reporting this.

In the 0.x we made the slug translatable, but the adapted 0.x admin template was not properly merged into the master.
