### ISSUE TITLE
Javascript error in admin for crop centered images as depiction

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2269]
For example:

A text page has a couple of images linked as depictions and one of those images has a specified crop_center value. If you then link or unlink any of the other images there is a growl/javascript error. After that you need to refresh page to do any editing.

This is because the crop_center that is being searched by javascript is id `#crop_center` and not id `#crop_center_(id)`. The value of id `#crop_center` is undefined and then the regex does not work and the javascript error occurs in function setCropFromValue in z.cropcenter.js .
The value in config.hiddenInput is then `#crop_center` instead of `#crop_center_(id)` .

**Comment by mworrell** [comment]
They are only in the "depiction" list?
Or also in TinyMCE?

**Comment by loetie** [comment]
Tested only in depiction list. Did not test it with images in TinyMCE.

**Comment by mworrell** [comment]
Looking at the edge_media template.  To me it doesn't make much sense to have the `do_cropcenter` there anyway.  The crop center should only be edited on the main media page.
