### ISSUE TITLE
Zotonic onerror handler can crash.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2276]
It is possible that the error object is null when the window onerror handler is called. When that happens the error hander crashes, and the error is not sent to the server.

![Screenshot 2019-12-11 10 25 56](https://user-images.githubusercontent.com/1024972/70609353-eb830a00-1c01-11ea-9f7c-7d0a28b0da06.png)

![Screenshot 2019-12-11 10 26 09](https://user-images.githubusercontent.com/1024972/70609360-efaf2780-1c01-11ea-8336-8abc3c0fb971.png)

**Comment by mworrell** [comment]
Should also be fixed on master.

If there is no error object, shall we then ignore the error and not send it to the ui log?
Knowing that there are errors is nice, but not knowing what the error is about doesn't help at all.

**Comment by mmzeeman** [comment]
The error handler also uses the `let` keyword. Maybe something to avoid on `0.x`? This now fails to run on old iOS safari browsers. Like the iPhone 5s simulator on BrowserStack.

**Comment by mworrell** [comment]
Browserstack runs the original iOS that came with the phone. 5s users should now be on iOS 12 or 13.

So I think of it runs on their iPhone 8 then it should be ok.

**Comment by mmzeeman** [comment]
it is on iOS 7 from 2013... ancient

**Comment by mmzeeman** [comment]
Was working on the live updating template solution with zotonic master. I could reproduce it there. Safari and Chrome do not have a stack object when a worker is started, but the url can't be found. It is still useful to log the error I think. There are probably more edge cases where the stack is not set.

<img width="1149" alt="Screenshot 2019-12-20 at 22 46 08" src="https://user-images.githubusercontent.com/1024972/71295094-d8e3a000-237a-11ea-91eb-c9b97f614448.png">
