### ISSUE TITLE
Warn when running as root [was: erlang 22.0 cannot run]

### ISSUE THREAD

**Issue by SummerGaoPlus** [zotonic/zotonic#2279]
[root@SummerGao zotonic]# ./bin/zotonic debug
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V10.4  (abort with ^G)
(zotonic@SummerGao)1> 08:54:43.720 [info] Setup running ...
08:54:43.720 [info] Directories verified. Res = ok
08:54:43.720 [info] Setup finished processing hooks (Mode=normal)...
08:54:44.253 [info] msg: "Starting reporters with []\n", options: []
08:54:44.910 [info] filezcache: repopulating cache with 0 keys
08:54:44.910 [info] filezcache: scanning cache directory for unknown files.
Starting keyserver supervisor08:54:46.681 [error] gen_server:366 CRASH REPORT Process exec with 0 neighbours exited with reason: bad return value: "Port program /mnt/h/ErlangWorkSpace/GitHub/zotonic/_build/default/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!" in gen_server:init_it/6 line 366
08:54:46.682 [error] Supervisor exec_app had child exec started with exec:start_link([]) at undefined exit with reason bad return value: "Port program /mnt/h/ErlangWorkSpace/GitHub/zotonic/_build/default/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!" in context start_error
08:54:46.682 [error] CRASH REPORT Process <0.360.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,exec,{bad_return_value,"Port program /mnt/h/ErlangWorkSpace/GitHub/zotonic/_build/default/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!"}}},{exec_app,start,[normal,[]]}} in application_master:init/4 line 138
08:54:46.683 [error] zotonic:49 Zotonic start error: {{shutdown,{failed_to_start_child,exec,{bad_return_value,"Port program /mnt/h/ErlangWorkSpace/GitHub/zotonic/_build/default/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!"}}},{exec_app,start,[normal,[]]}}
08:54:46.683 [info] Application erlexec exited with reason: {{shutdown,{failed_to_start_child,exec,{bad_return_value,"Port program /mnt/h/ErlangWorkSpace/GitHub/zotonic/_build/default/lib/erlexec/priv/x86_64-unknown-linux-gnu/exec-port with SUID bit set is not allowed to run without setting effective user!"}}},{exec_app,start,[normal,[]]}}
[root@SummerGao zotonic]#

**Comment by mworrell** [comment]
Can you try to run with another user than root?

**Comment by mworrell** [comment]
Should emit an error and refuse to run when started as root.

Affected are the `start` and `debug` commands.
The other commands should be ok.
