### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by yumminova** [zotonic/zotonic#2280]
Hi, i followed the instructions on http://docs.zotonic.com/en/latest/developer-guide/getting-started.html#installation

Getting Zotonic
Download the latest Zotonic release ZIP file from the GitHub releases page. For instance:

$ wget https://github.com/zotonic/zotonic/archive/1.0-dev.zip
Then unzip the file and rename the directory:

$ unzip 1.0-dev.zip //// changed to 0.53.0.zip
$ mv zotonic-1.0-dev zotonic
Alternatively, clone the latest development version using Git:

$ git clone https://github.com/zotonic/zotonic.git
You then need to compile the Zotonic sources:

$ cd zotonic
$ make
Then start Zotonic in debug mode:

$ bin/zotonic debug
Now point your browser to: https://localhost:8443/. You should see a welcome message, ‘Powered by Zotonic’. This is the so-called status website. So far, so good! Now it’s time to create your first site.
Im on centos 8
But when running the final make command i get tbhis error:

/zotonic-0.53.0/deps/edown/src/edown_doclet.erl:31: can't find include lib "edoc/include/edoc_doclet.hrl"

**Comment by mworrell** [comment]
Which OTP version are you running?

**Comment by mworrell** [comment]
The automated builds work well, assuming this was an issue with a local erlang installation. Closing issue.
