### ISSUE TITLE
`mod_geoip` is broken

### ISSUE THREAD

**Issue by g-andrade** [zotonic/zotonic#2282]
Due to very recently [announced](https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/) changes by MaxMind, the [public GeoLite2 URLs](https://github.com/zotonic/zotonic/blob/c38157ff74ede9be692cb42f81746f81e868bc68/apps/zotonic_mod_geoip/src/mod_geoip.erl#L24-L25) used by `mod_geoip` stopped working on December 30 - individual (free) license keys are now required to download the databases.

This matter is being [tracked](https://github.com/g-andrade/locus/issues/9) on `locus`, the library used for parsing the MMDB data; a new version, `1.9.0-beta`, [introduces support](https://github.com/g-andrade/locus/tree/1.9.0-beta#1-configure-your-license-key) for license keys, which nevertheless need to be explicitly configured by the consumer.

On a more positive note, the database edition identifiers can now be used instead of HTTP URLs, as `locus` will build the URL internally in those cases.

**Comment by mworrell** [comment]
Thanks for this information. Will make changes to `mod_geoip`, so that we can use the newer locus and a configured license key. And document the method to obtain that key.

**Comment by mworrell** [comment]
Changes have been merged into the 0.x branch.

**Comment by mworrell** [comment]
@g-andrade Thanks!  The license key is now supported in 0.x and master.
