### ISSUE TITLE
Make it possible for pages to tell the session to stay active

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2290]
We use zotonic as the basis of a chat system. We have one page where agents pick up incoming chats. Currently the agents are automatically logged off after being inactive for one hour. Some of the agents are very specialised and are not contacted regularly. They usually have the page open minimized and receive the incoming chat request via a desktop notification.

The current way the sessions is kept active can't be influenced from the page. I would like to add a mechanism to make it possible that pages can tell the session to stay active.

**Comment by mmzeeman** [comment]
Side note.

It looks like the current way the session is kept active is not entirely fool proof. There is a function `z_is_active` which returns true if the user was active the last 5 seconds. This function is used by the ping mechanism and adds a flag. But pings are sent with 20 second intervals. In theory they could miss that a user was active, and destroy the session too soon.

**Comment by mworrell** [comment]
This has been merged, so I assume we can close the issue?
