### ISSUE TITLE
Use of custom DHE key exchange parameters is marked as "insufficient" (SSL)

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2293]
Zotonic uses custom DHE key exchange parameters. Automatic checking tools mark the use of parameters like these as insufficient. RFC7919 mentions that clients are allowed to drop the connection if they find that servers use parameters which they can't check, or are not known strong.

I would like to change zotonic so it doesn't generate DHE parameters anymore, and uses known strong DHE parameters. I would like to make it possible that zotonic can easily switch between parameters because of security reasons.

RFC7919 - https://tools.ietf.org/html/rfc7919#section-3.1

Screenshot from a site review done by https://internet.nl

<img width="688" alt="Screenshot 2020-01-16 at 14 25 42" src="https://user-images.githubusercontent.com/1024972/72589789-75f31380-38fc-11ea-8fac-f4b776b7978f.png">

**Comment by mworrell** [comment]
To my feeling this is a bit of "security theatre", but as it is the only way to pass these tests I agree to not generate the DH key ourselves anymore.

**Comment by mmzeeman** [comment]
Yes it is... Our customer used some tools to be able to be compiant for a new law which comes into effect the 1st of july this year in the Netherlands. They specifically demanded HSTS and this.

https://www.digitaleoverheid.nl/overzicht-van-alle-onderwerpen/wetgeving/wet-digitale-overheid/

**Comment by mmzeeman** [comment]
I want to embed a couple of known good DHE parameters into zotonic, so it is possible to switch whenever they go out of fashion again.

**Comment by mworrell** [comment]
Would be so good if all the theatre was stopped and real security and privacy issues were addressed.

+1 to include the known DHE parameter files.

**Comment by mworrell** [comment]
Needs to be merged into master.
