### ISSUE TITLE
New Chrome 80 behaviour conflicts with zotonic transport logic

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2294]
Chrome 80 now errors when sending synchronous ajax requests in page unloading state.

Normally all zotonic's ajax requests are done asynchrounously to prevent blocking in the user interface. But when the page goes to unload state, because of a `beforeunload` event being triggered, zotonic drops the websocket connection, and only sends synchronous ajax requests. We did this to reliably send data data to the server at this stage, and also to prevent requests from being cancelled. This was introduced in zotonic version `0.13.6`

https://github.com/zotonic/zotonic/commit/62956bfe839e500fe55d70d7b51c58bacf784368

However, Chrome 80 now errors when you try to send synchronous ajax requests at this stage. My Chrome 79 browser somehow had this feature enabled.

https://www.chromestatus.com/feature/4664843055398912

How to fix this?

  1) Just send async ajax requests, and take the cancelled requests for granted.
  2) It might also be possible to queue the messages, and send them together with the unload beacon message. This is sent asynchrounously and can also carry extra data.

**Comment by mworrell** [comment]
I am for using the Beacon, as that is meant to run on the page unload anyway.

**Comment by mworrell** [comment]
Is this issue serious enough that it should be addressed in the upcoming release?

**Comment by mmzeeman** [comment]
What I saw on a particular page which sends messages when the page unloads was that the red zotonic growl messages appeared on the screen, and that client side code not completely ran because an exception now happens in an unexpected place.

When where you planning the new release?

**Comment by mworrell** [comment]
Coming week, but we can delay.  This is serious enough.

**Comment by mworrell** [comment]
Let's include it in the coming release.  I will postpone it one more week.

**Comment by mmzeeman** [comment]
Ok... going to fix this by:

  - Stop sending ajax request when the page is unloading
  - When the page unloads, place all queued messages in the asynchronous beacon message.

Note: The page can't react to responses anymore.

**Comment by mmzeeman** [comment]
It may also be possible to postpone the websocket/comet connection close to the `unload` event. This keeps the connection alive longer.
