### ISSUE TITLE
Can't run on erlang 22.2 because mochiweb does not start

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2301]
There has been an api change in the ssl application, but there is a conditional compile available for that part of the code.

It looks during compilation the wrong set of defines are selected from the `rebar.config` when you compile with erlang 22.

**Comment by mworrell** [comment]
Maybe check the mochiweb project, they probably have a fix in place.

Do we want to support 0.x on OTP 22 and later?

**Comment by mmzeeman** [comment]
Good question. I have to think about that one.

**Comment by testexplode** [comment]
On the master branch (1.0-pre) it works, if in /home/zotonic/zotonic/apps/zotonic_core/rebar.config the version of mochiweb will be updated to {mochiweb, "2.20.1"}.
I didn' t tried it on a 0.x tag. 
The latest mochiweb 2.20.1 seems downwards compatible with  2.18: https://github.com/mochi/mochiweb/releases

**Comment by mworrell** [comment]
@testexplode Thanks for the info, we will upgrade Mochiweb on master.  For the 0.x we have merged some changes from upstream Mochiweb in our branch. The 0.x branch should be running fine on OTP-22 now.

**Comment by mworrell** [comment]
Fixed in #2420
