### ISSUE TITLE
Remove x-dtap-environment header

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2302]
Request from @CyBeRoni to remove this header, so that eventual auditors won't start arguing about it.

@mmzeeman are you ok?

**Comment by CyBeRoni** [comment]
Is there a way to set custom headers per site? Because if so, one could use that to achieve the same effect if desired. I'm just arguing against having it be sent by default.

**Comment by mworrell** [comment]
You can add extra headers in the `#security_headers{}` notification.

**Comment by mmzeeman** [comment]
Fine with that... I just documented it in the documentation of mod_site I believe.

**Comment by mworrell** [comment]
Indeed, removed that from the 0.x docs

**Comment by mmzeeman** [comment]
I was wondering where it was used for.

If we want to be able to set configurable headers for the whole site it might be worth investigating to configure this in the site config. Maybe allow a list of entries for m.site.custom_header or something?

**Comment by mworrell** [comment]
Main idea is that you can see what the site is, people sometimes confuse the dev/test/prod sites.

You can also use it to set a class in the html and so make a visual distinction between versions of the site.
