### ISSUE TITLE
File upload shows in new find/add dialog, even if category is a query or text.

### ISSUE THREAD

**Issue by loetie** [zotonic/zotonic#2305]
File upload shows in new find/add dialog, even if category is a query or text.

1. goto: /admin/overview
2. example: select query category
3. Click make a new page
4. File upload shows (should not be there). Select a image.
5. Save. (creates a query item with a image)

**Comment by mworrell** [comment]
Looks like an initialization issue when there is a pre-checked category.

**Comment by mworrell** [comment]
@loetie can you checked the merge request #2322?  It should fix your problem.
