### ISSUE TITLE
width/height on generated img tags

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2306]
In the past we removed the width/height from the generated `<img>` tags. This to accommodate to the css implementation of browsers from that time.

Now browsers are (will) be using the width/height, in connection to the css, to calculate the size (aspect ratio) of the image and reserve the correct placeholder, even if the image didn't load yet.

Explanation video:
https://www.youtube.com/watch?v=4-d_SoCHeWE

**Proposal 1:** Set the calculated width/height on the img tags.

**Proposal 2:** Use a template to generate the img tag.

The last proposal is more something for master.

**Comment by mworrell** [comment]
@DorienD especially your comments please!

**Comment by seannaswell** [comment]
Very helpful to know, will soon be adding a photo section to a site and would be nice to implement...

**Comment by mworrell** [comment]
If @DorienD is ok then we can add this back in (it used to be there).

**Comment by DorienD** [comment]
Im gonna dig into this

**Comment by mworrell** [comment]
@DorienD I have made a 0.x branch in #2318

You can play around with this branch and see the effects.

I did change the admin css to add:

```css
img {
    max-width: 100%;
    height: auto;
}
```

For the admin this seems to be enough to make everything work again as expected.

**Comment by mworrell** [comment]
Reopened, as we need to merge into the 0.x as well.

**Comment by mworrell** [comment]
Has been merged
