### ISSUE TITLE
Make sure admin runs from ssl

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2308]
Currently only the logon resource has `{ssl, true}` set in the dispatch rules.

When the site has ssl setup all the admin pages should be visited via ssl only.

This is already setup for `master`, but not for `0.x`

**Comment by mworrell** [comment]
I am ok with forcing all admin dispatch rules to `ssl` (just like the authentication urls).
This takes effect if there is SSL available.

On master we only serve https, so there this is not an issue.
