### ISSUE TITLE
Make it the difference between meta/system and normal content clearer

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2309]
In Zotonic everything is a resource. 

The admin page to edit resources also look the same for site and meta (categories/predicates/etc) content looks exactly the same as normal content.

In order to clarify the special nature of the meta content it would be nice that these resources are a little bit special. That would prevent accidental editting.

- [x] Clear visual indicator when you are editting meta content in page admin/edit/<id>
- [ ] Remove "System Content" from the admin/pages when 
<img width="416" alt="Screenshot 2020-02-24 at 14 25 49" src="https://user-images.githubusercontent.com/1024972/75156053-94c1a280-5711-11ea-9d7e-afe1f7a955a5.png"> is in effect. Only normal content should be shown here.

**Comment by OldhamMade** [comment]
On the edit page it would be good to have something attention-grabbing near the title that explains that this is a meta resource, and what kind of meta resource it is. An "info banner" would work, or some kind of "label".

**Comment by mworrell** [comment]
Proposal:

 * Add the name of the content group as class on the body or edit-form
 * Add the name(s) of the categories as classes on the body or edit-form
 * Add an optional header include for all warnings etc. This should be a `catinclude`
 * Add css to make the admin look different (red warnings, borders etc) depending on the body/form classes

Need to decide on which tag we should place the classes, though the body seems to be a logical place for them.

**Comment by mworrell** [comment]
Something like this:

![Screenshot 2020-02-25 at 12 08 59](https://user-images.githubusercontent.com/38268/75242166-d44ac600-57c7-11ea-933c-7d18080716e5.png)

**Comment by OldhamMade** [comment]
That's great, although could be made better by presenting the "what".

Maybe:

> **Proceed with care:** You are editing a {thing} which is system content. [Click here for more information…]

**Comment by mworrell** [comment]
I just changed it into:

![Screenshot 2020-02-25 at 12 12 55](https://user-images.githubusercontent.com/38268/75242465-723e9080-57c8-11ea-9822-04c3e08cf1be.png)

**Comment by mworrell** [comment]
That "click here" link is good, do you have a suggestion where that should go?  A documentation page?

**Comment by mworrell** [comment]
@OldhamMade I like your text, taking that one.

**Comment by mworrell** [comment]
@mmzeeman For the _selected categories_ filter, you mean exclude anything in the `meta` category?

**Comment by mworrell** [comment]
I now also add red labels in the content overview if the content is system content.

**Comment by mworrell** [comment]
@mmzeeman for filtering the list you can make a stored query page with the name `admin_overview_query`, here you can select the categories that are interesting.

**Comment by mmzeeman** [comment]
@mworrell There are not that many anyway, and you can easily get to them via the "Structure" menu. Of are is there also system content which does appear in that menu.

Maybe red is a bit too much. Red is more "game over, you are dead", nothing can be done anymore. Orange or yellow is better for warnings I think.

**Comment by OldhamMade** [comment]
> Maybe red is a bit too much. Red is more "game over, you are dead", nothing can be done anymore. Orange or yellow is better for warnings I think.

Agreed.

**Comment by mworrell** [comment]
Changing it to the warning color.

**Comment by mmzeeman** [comment]
It also looks nice against zotonic blue ;-)

**Comment by mworrell** [comment]
@mmzeeman  Done!  You can check the branch - if ok then merge - I will copy the changes over to the master.

**Comment by mmzeeman** [comment]
Yes, will do.

**Comment by mmzeeman** [comment]
Looks very good! One suggestion from @OldhamMade. He suggests to put in a link to the documentation in the warning, as this is an opportunity to educate people about Zotonic's data model.

This maybe a nice page: http://docs.zotonic.com/en/latest/user-guide/domain-model.html, but it is not fleshed out right now. Maybe the next best page is: http://docs.zotonic.com/en/latest/user-guide/data-model.html

**Comment by mworrell** [comment]
Maybe those pages should be merged into the `domain-model` page?

**Comment by mmzeeman** [comment]
Yes, why not... Then the maintainers of a site can more easily get to the zotonic docs, and jump to the right place and learn what a predicate/category is.

When we have everything fleshed out, we could even deeplink to the documentation of the category/predicate/etc itself.

**Comment by mworrell** [comment]
I have added the link (to the first page).

Also added the warning to the predicates/categories/content-group-hierarchy pages.

Maybe we want to add this to more system config pages?

**Comment by mworrell** [comment]
(of course we can do that only on master as well)

@mmzeeman @OldhamMade  If you are ok - then we can merge this and make a separate branch for master (where we can also merge the two docs pages).

**Comment by mmzeeman** [comment]
We could add links to the relevant documentation in the resources maybe?

**Comment by mworrell** [comment]
In #2312 the domain and data model doc pages are merged into one.
