### ISSUE TITLE
Documentation explaining template selection needs clarification

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2315]
The template selection documentation at:

http://docs.zotonic.com/en/latest/ref/tags/tag_catinclude.html#tag-catinclude

explains that template selection goes like this.

First `name` -> `cat` ->   `parent-cat` -> `parent-parent-cat` ...

But this works different when the resource itself is a category. Then the `name` selection does not work as described.

**Comment by mworrell** [comment]
I think in the 1.x (master) we should change this behavior. Also to remove any confusion between name and category.

I propose for a catinclude of `foo.tpl` with name `bar` and category:  `article`, parent category `text`:

  1. `foo.name.bar.tpl`
  2. `foo.article.tpl`
  3. `foo.text.tpl`
  4. `foo.tpl`

Changing this in the 0.x will break too many existing systems.  Though we could implement the above in the 0.x and then add between 1 and 2:  `foo.name.tpl` for compatibility.

**Comment by mworrell** [comment]
@mmzeeman I think this fits what we discussed. Can you have a look?

**Comment by mworrell** [comment]
I only want to change it there, so that we can prepare sites for the new include behavior.  The old method will still work in 0.x
