### ISSUE TITLE
Admin area should globally indicate what "environment" the user is working in

### ISSUE THREAD

**Issue by OldhamMade** [zotonic/zotonic#2319]
### User Story

_In order to_ feel safe when editing in non-production environments
_As_ an Admin user
_I need_ the admin area to indicate the current deployment environment

### Rationale

When switching between test, stage, and production environments where the content is often the same, it would be useful if the Zotonic admin screens could display differently so it is quick and easy to identify whether the operation I'm about to undertake is "safe".

For example, I know that some other CMS software uses header background colours to show environment. Eg, testing is purple, staging is orange, production is red.

**Comment by mworrell** [comment]
That was indeed one of the basic ideas.

In the base templates we now add a class to reflect the current environment.

You proposal is:

 - development = ?
 - testing = purple
 - staging = orange
 - production = red
 - backup = ?

Or should we _not_ show any extra colour bar on production? As that is the usual state of most systems and editors might find it confusing to see a coloured bar.

We could add the bar on the top of the window, fixed position so it is always visible. For example a 4px heigh colored line?

**Comment by OldhamMade** [comment]
> Or should we _not_ show any extra colour bar on production?

This is agreeable.

> We could add the bar on the top of the window, fixed position so it is always visible. For example a 4px heigh colored line?

It should be more prominent than that: the background colour for entire primary navigation bar.

> Your proposal is:

Maybe:

* dev: (dark) green
* test: purple
* staging: orange
* production: standard zotonic blue
* backup: grey

Could also be useful to have a config setting for `navigation-background-color` so developers can set whatever colour they feel appropriate.

**Comment by OldhamMade** [comment]
> It should be more prominent than that: the background colour for entire primary navigation bar.

Or if not this, the bar should be large enough to display the name of the environment.

**Comment by mworrell** [comment]
> the bar should be large enough to display the name of the environment.

Agreeing completely with this, otherwise it is always a guess, especially for people not working regularly with the system.

**Comment by mworrell** [comment]
Agreeing with the colours.

>  the background colour for entire primary navigation bar.

Or maybe a colored background?  Currently the background of the admin is white, we could have that differently.

Or maybe a colored line on the left side of the screen, with a vertically positioned name of the env?

Of course all in the admin - if it shows up in the frontend is up to the frontend dev.

We can easily generate a couple of .css files to have the colors and selectors available for frontend systems.

**Comment by mworrell** [comment]
@OldhamMade can you give #2320 a test drive?

**Comment by mworrell** [comment]
BTW. if you change the environment setting in the zotonic.config file then you can reload the zotonic.config file using `z:load_config()` in the Erlang shell.

**Comment by mworrell** [comment]
Example:

![Screenshot 2020-02-28 at 16 46 45](https://user-images.githubusercontent.com/38268/75563071-fb182f00-5a49-11ea-8060-9bcfd947635a.png)
