### ISSUE TITLE
problem permission

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2328]
install last release from git
`./start-docker.sh
Starting zotonic_postgres_1 ... done
+ HOME=/opt/zotonic
+ ZOTONIC_PIDFILE=/run/zotonic.pid
+ ZOTONIC_CONFIG_DIR=/etc/zotonic
+ SHELL=/bin/sh
+ export HOME ZOTONIC_PIDFILE ZOTONIC_CONFIG_DIR SHELL
+ touch /run/zotonic.pid
+ chown zotonic /run/zotonic.pid
+ mkdir -p /etc/zotonic/security
+ chown -R zotonic /etc/zotonic/security
+ mkdir -p /etc/zotonic/config.d
+ chown -R zotonic /etc/zotonic/config.d
+ '[' '!' -f /etc/zotonic/config.d/docker.config ']'
+ '[' '!' -f /etc/zotonic/erlang.config ']'
+ '[' '!' -f /opt/zotonic/_build/default/lib/zotonic_core/ebin/zotonic_core.app ']'
+ /usr/bin/gosu zotonic make
make: stat: GNUmakefile: Permission denied
make: stat: makefile: Permission denied
make: stat: Makefile: Permission denied
make: *** No targets specified and no makefile found.  Stop.
+ '[' -e /opt/zotonic/apps/zotonic_launcher/src/command/zotonic_cmd_sh.erl ']'
+ '[' -n '' ']'
+ printf '\n\n####\n#### Usage: bin/zotonic [options] [command]\n####\n#### To rebuild zotonic run make\n####\n\n'

####
####
####

+ exec /usr/bin/gosu zotonic /bin/bash`

**Comment by mworrell** [comment]
You started Docker from a normal user?

Can you see your local directory mounted in `/opt/zotonic` ?
And if so, with which permissions?

And do you see in your local filesystem the directory `./docker-data/etc-zotonic` ?

**Comment by heiheshang** [comment]
start from root
I can not watch /opt/zotonic permission denied 
`bash-4.4$ cd /opt/zotonic
bash: cd: /opt/zotonic: Permission denied`

**Comment by heiheshang** [comment]
how do you add a zotonic user?

**Comment by mworrell** [comment]
What do you see if you try `ls -ld /opt/zotonic` ?

**Comment by heiheshang** [comment]
`bash-4.4$ ls -ld /opt/zotonic
drwxr--r--   16 1001     users         4096 Mar  5 09:51 /opt/zotonic`

**Comment by mworrell** [comment]
I see this (older) remark when I search on this issue:

https://stackoverflow.com/a/24334000/457795

Seems to be a SELinux problem.

Maybe we should switch to another Linux, @ddeboer what do you think?

**Comment by heiheshang** [comment]
Now I do it - it saves me
` volumes:
            - ./:/opt/zotonic:delegated
            - ./docker-data/etc-zotonic:/etc/zotonic:delegated
            - "/etc/localtime:/etc/localtime"
            - "/etc/passwd:/etc/passwd:ro"
            - "/etc/group:/etc/group:ro"
            - "/etc/hosts:/etc/hosts:ro"`

**Comment by mworrell** [comment]
Interesting that mapping your system directories fixes the permission problem.

In the meantime I am building a debian version, to see if that works.

**Comment by heiheshang** [comment]
I got a zotonic user in the target system and gave him the rights to /opt/zotonic, then it works, if you don’t have a local zotonic user, this also will not help

**Comment by mworrell** [comment]
So Docker and the local system are sharing users?  That is a weird implementation (by Docker).

**Comment by heiheshang** [comment]
how do you grant user rights to files if the user is not on the host system?

**Comment by mworrell** [comment]
I thought that is something that Docker should handle - it is mounting those volumes after all, so could make some mapping that makes sense.

**Comment by heiheshang** [comment]
In any case, these are host system files and there may be many containers that want to access these files, if each container tries to do this under its own user, then what happens?

**Comment by mworrell** [comment]
I would guess use the user which started the container in the first place?

**Comment by heiheshang** [comment]
on different systems, the same users may have different uid and gid groups, the target host machine and containers may have different distributions, everything will break

**Comment by mworrell** [comment]
I see the mount as requested by the user starting the container. So Docker could safely use the credentials of that user, and map everything. The user that started the container should also be responsible for correct rights inside the container.

This mixing of users between two different systems makes no sense to me.  Surely someone has a solution somewhere.

**Comment by heiheshang** [comment]
this works for volumes inside the container itself, but not for external volumes

**Comment by mworrell** [comment]
Fixed in #2714
