### ISSUE TITLE
I can not get into the admin panel to install a new site

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2329]
`
13:07:49.182 [error] at: "cowmachine:request_1:103", class: exit, code: 500, dst: #{ip4 => "172.18.0.3",port => 8443}, in: cowmachine, level: error, path: <<"/zotonic-auth">>, reason: {aborted,{no_exists,['ratelimit_event-zotonic_site_status',{auth,<<"wwwadmin">>}]}}, src: #{ip4 => "31.129.16.218",port => 50746}, stacktrace: [{mnesia,abort,1,[{file,"mnesia.erl"},{line,355}]},{m_ratelimit,is_event_limited,4,[{file,"/opt/zotonic/apps/zotonic_mod_ratelimit/src/models/m_ratelimit.erl"},{line,87}]},{mod_ratelimit,observe_auth_precheck,2,[{file,"/opt/zotonic/apps/zotonic_mod_ratelimit/src/mod_ratelimit.erl"},{line,65}]},{zotonic_notifier_worker,first_1,3,[{file,"/opt/zotonic/apps/zotonic_notifier/src/zotonic_notifier_worker.erl"},{line,188}]},{m_identity,check_username_pw,4,[{file,"/opt/zotonic/apps/zotonic_core/src/models/m_identity.erl"},{line,514}]},{mod_authentication,observe_logon_submit,2,[{file,"/opt/zotonic/apps/zotonic_mod_authentication/src/mod_authentication.erl"},{line,105}]},{zotonic_notifier_worker,first_1,3,[{file,"/opt/zotonic/apps/zotonic_notifier/src/zotonic_notifier_worker.erl"},{line,188}]},{controller_authentication,logon,2,[{file,"/opt/zotonic/apps/zotonic_mod_authentication/src/controllers/controller_authentication.erl"},{line,90}]}], text: "Unexpected exception"

`

**Comment by mworrell** [comment]
Can you check if there is an earlier error about mnesia?

This looks like the mnesia table is missing, maybe also a permission error.

**Comment by mworrell** [comment]
The mnesia tables are created in `./priv/mnesia/<nodename>/...`

**Comment by heiheshang** [comment]
yes, after deleting the files in the directory and restarting the zotonic, I was able to get into the panel

**Comment by mworrell** [comment]
Thanks for checking!

Guess it has something to do with those permission errors.
Working on the Debian version - missing some SSL stuff there, so it seems from other vague errors.

**Comment by heiheshang** [comment]
Now the problem is with the creation of the site, the directory is created and that's it
`14:21:08.857 [info] mod_zotonic_site_management:52 [zotonic_site_status] Creating site nahodka with [{hostname,<<"424111.ru">>},{skeleton,<<"basesite">>},{dbdatabase,<<>>},{dbschema,<<"nahodka">>},{dbhost,<<>>},{dbport,<<>>},{dbuser,<<>>},{dbpassword,<<>>}]
14:21:08.934 [error] Error in process <0.2089.0> on node zotonic@695d7ccad155 with exit value:
{{case_clause,undefined},[{zotonic_status_addsite,addsite_compile,3,[{file,"/opt/zotonic/apps/zotonic_mod_zotonic_site_management/src/zotonic_status_addsite.erl"},{line,190}]},{mod_zotonic_site_management,event,2,[{file,"/opt/zotonic/apps/zotonic_mod_zotonic_site_management/src/mod_zotonic_site_management.erl"},{line,53}]},{z_transport,incoming_postback_event,6,[{file,"/opt/zotonic/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,127}]},{z_transport,transport,3,[{file,"/opt/zotonic/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,63}]},{lists,foreach,2,[{file,"lists.erl"},{line,1338}]}]}
`

**Comment by mworrell** [comment]
Thanks, found that one, can indeed occur when compiling from the web-ui. I fixed it and pushed it to master

**Comment by heiheshang** [comment]
nothing changed
