### ISSUE TITLE
Unhandled file event 'modify'

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2331]
`02:28:40.111 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-service-worker-bundle.js'
02:28:40.174 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/zotonic-wired-bundle.js'
02:28:42.338 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-worker-bundle.js'
02:28:42.378 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-bundle.js'
02:28:42.406 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-service-worker-bundle.js'
02:28:42.480 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/zotonic-wired-bundle.js'
02:28:44.504 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-worker-bundle.js'
02:28:44.504 [info] zotonic_filehandler_mapper:70 Unhandled file event 'delete' on 'cotonic/cotonic.mqtt_session.js'
02:28:44.540 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-bundle.js'
02:28:44.566 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/cotonic-service-worker-bundle.js'
02:28:44.628 [info] zotonic_filehandler_mapper:70 Unhandled file event 'modify' on '/opt/zotonic/_build/default/lib/zotonic_mod_base/priv/lib-src/cotonic/dist/zotonic-wired-bundle.js'
`

**Comment by mworrell** [comment]
This is just some logging, should indeed suppress that.

For now you can ignore the 'unhandled file event' log messages.
