### ISSUE TITLE
Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2336]
I don’t understand what the problem is? I can not add a category
`Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.`

**Comment by mworrell** [comment]
Was just fixing this problem - Cotonic was changed and Zotonic was not updated yet.

I can add the categories again - can you as well?

**Comment by mworrell** [comment]
Also fixed a problem in Cotonic - please pull the newest one in:

```
apps/zotonic_mod_base/priv/lib-src/cotonic
```

**Comment by heiheshang** [comment]
strange, but now I began to block the loading of resources from scripts, the pictures that the script loaded were no longer given by the server, fonts from css were not loading

**Comment by mworrell** [comment]
Using scripts?  Might be CORS headers, which weren't changed in the last commit, but could you check the Browser tools for errors or other messages?

**Comment by heiheshang** [comment]
there is this
`A cookie associated with a cross-site resource at https://ogs.google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and 

if there is a link to a file on disk in my css, it immediately stops working, the download goes on endlessly.
`https://www.chromestatus.com/feature/5633521622188032.`

`lib/fonts/fontawesome-webfont.woff2?v=4.7.0`

**Comment by mworrell** [comment]
You load that file file `file:...`  or with the lib tag?

**Comment by heiheshang** [comment]
into css
`@font-face{font-family:'FontAwesome';src:url('/lib/fonts/fontawesome-webfont.eot?v=4.7.0');`

**Comment by mworrell** [comment]
And if you load that file direct in your browser?  Does it show?

Like:

`https://example.com/lib/fonts/fontawesome-webfont.eot?v=4.7.0`

**Comment by heiheshang** [comment]
it works without problems, the file is downloaded

**Comment by mworrell** [comment]
We have a similar url in the mod_artwork font-awesome css.  (4.2 - maybe upgrade to 4.7)
That one seems to download fine.

**Comment by heiheshang** [comment]
this does not solve the problem, then images are downloaded, they also do not load

**Comment by heiheshang** [comment]
after the last update it stopped working

**Comment by mworrell** [comment]
We did upgrade Cowboy, maybe there is a problem there.

**Comment by heiheshang** [comment]
don't you have filters for file size?

**Comment by mworrell** [comment]
To display the size in text?  There is the filter `filesizeformat` for that.

**Comment by heiheshang** [comment]
no, the problem is only with files after a certain size, if the files are less than 50K there are no problems

**Comment by mworrell** [comment]
Interesting, I have .js files that > 50KB and they load fine.

**Comment by heiheshang** [comment]
wrong, I understand further

**Comment by heiheshang** [comment]
the problem is in {% lib%}, when any file is not accessible, everything is blocked, because all files are combined, it is not visible which one is not available. 404 does not return, but pending occurs. I don’t understand why, but bootstrap is not available for me

**Comment by heiheshang** [comment]
[https://yadi.sk/i/gop5eueGn_b_Ig](url)

**Comment by heiheshang** [comment]
`[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://424111.ru:8443/lib/css/z.icons/fonts/icomoon.woff?v=3`

**Comment by mworrell** [comment]
I separated the lib issue here #2346
