### ISSUE TITLE
after installation error mod_translation

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2344]
`06:16:23.402 [error] at: "cowmachine:request_1:82", code: 500, dst: #{ip4 => "172.18.0.3",port => 8443}, in: cowmachine, level: error, path: <<"/">>, reason: {{case_clause,undefined},[{mod_translation,valid_config_language,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,492}]},{mod_translation,set_language,2,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,143}]},{mod_translation,observe_request_context,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,165}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_context,ensure_qs,1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_context.erl"},{line,492}]},{z_cowmachine_middleware,'-execute/2-fun-0-',1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_cowmachine_middleware.erl"},{line,47}]},{cowmachine_decision_core,decision,3,[{file,"/opt/zotonic/_build/default/lib/..."},...]},...]}, src: #{ip4 => "159.255.18.219",port => 52408}, text: "Stop request"
06:16:23.409 [error] CRASH REPORT Process <0.1568.0> with 0 neighbours crashed with reason: {stop_request,500,{{case_clause,undefined},[{mod_translation,valid_config_language,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,492}]},{mod_translation,set_language,2,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,143}]},{mod_translation,observe_request_context,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,165}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_context,ensure_qs,...},...]}} in cowmachine_decision_core:handle_request/2 line 41
06:16:23.411 [error] Cowboy stream 1 with ranch listener zotonic_https_listener_ipv4 and connection process <0.1567.0> had its request process exit with reason: {nocatch,{stop_request,500,{{case_clause,undefined},[{mod_translation,valid_config_language,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,492}]},{mod_translation,set_language,2,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,143}]},{mod_translation,observe_request_context,3,[{file,"/opt/zotonic/apps/zotonic_mod_translation/src/mod_translation.erl"},{line,165}]},{lists,foldl,3,[{file,"lists.erl"},{line,1263}]},{z_context,...},...]}}} in cowmachine_decision_core:handle_request/2 line 41
`

**Comment by mworrell** [comment]
Thanks for the report!  I have pushed a fix.
