### ISSUE TITLE
I can not change the language

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2347]
set the language, but still everything is in English

**Comment by mworrell** [comment]
What are the steps to reproduce this?

**Comment by heiheshang** [comment]
I just unchecked the English language, and everything fell into Russian. You can switch the language unless you use English, leave only one language and make it the main one, then you can switch to Russian

**Comment by mworrell** [comment]
We do remember the last language setting of the user (in a cookie) - maybe that is the problem?

**Comment by heiheshang** [comment]
https://yadi.sk/i/AFMinrBC5tO0Aw
As you can see, there is no change in language
if I change the main language, redirecting /ru/admin/ translation is done incorrectly
`/ru/admin/translation`

**Comment by mworrell** [comment]
And if you check _For new visitors, set the language to the default language (русский язык)_?

[Just fixes a problem with this setting, please pull]

**Comment by heiheshang** [comment]
it’s not a big problem for me, I don’t need two or more languages

**Comment by mworrell** [comment]
Ok, thanks.

I will keep an eye on it when I am redoing this part (need to add some options from the 0.x)

**Comment by mworrell** [comment]
Closing for now - we will have automated tests as well after the language handling changes.

**Comment by mmzeeman** [comment]
@mworrell I think that `z_reload` from `zotonic-wired.js` should also adapt the existing `z.lang` cookie, just like it rewrites the url when the `z_language` arg is set.
