### ISSUE TITLE
mod_ssl_letsencrypt does not work

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2348]
mod_ssl_letsencrypt does not work

**Comment by mworrell** [comment]
Any errors?

**Comment by heiheshang** [comment]
I do not see anything, the green button is not lit in the list of modules

**Comment by heiheshang** [comment]
you changed the logging, now I see nothing but crash

**Comment by mworrell** [comment]
What is the crash?

**Comment by heiheshang** [comment]
only crash_log, I can not understand where console.log is now
` {lager, [                                                                                                                             
    {handlers, [                                                                                                                       
      {lager_console_backend, [                                                                                                        
        {level, info},                                                                                                                 
        {formatter, lager_default_formatter},                                                                                          
        {formatter_config, [time, color, " [", severity, "] ", {site, [site, " "], ""}, {module, [module, ":", line, " "], ""}, message
, "\n"]}                                                                                                                               
      ]}                                                                                                                               
    ]},                                                                                                                                
    {crash_log, "/opt/zotonic/priv/log/crash.log"}                                                                                     
  ]}, `

**Comment by mworrell** [comment]
You should see the log on the Docker terminal.

Indeed, we removed the logs in the Docker container, maybe we should just keep them as we are logging to the host file system anyway.

**Comment by mworrell** [comment]
I have re-enabled the log files in the `erlang.config` in the docker directory.

**Comment by heiheshang** [comment]
how does mod_ssl_letsencrypt work if workers do not work with a self-signed certificate? I can not open fill in the settings on the admin/ssl page

**Comment by heiheshang** [comment]
can I get certificates without zotonic and give them to the module?

**Comment by mworrell** [comment]
Yes, you can have certificates from other suppliers using `mod_ssl_ca`.

Docs are here: http://docs.zotonic.com/en/latest/ref/modules/mod_ssl_ca.html

**Comment by heiheshang** [comment]
you don’t understand, I received a certificate through certbot, how now to make mod_ssl_letsencrypt  see it?

**Comment by mworrell** [comment]
In this case certbot is your CA supplier, so you can copy the certificates and keys into the place that `mod_ssl_ca` expects.  Just make sure that you have a .pem file for the key, in the manual is described how to use openssl to make a .pem from a .key file.

**Comment by mworrell** [comment]
Also ensure that the names of the files match what mod_ssl_ca expects, all described in the manual page.

**Comment by heiheshang** [comment]
yes, i see
`sitename.pem
This holds the private key for the encryption. The key must be unlocked and in PKCS#1 format (see below).
sitename.crt`
letsencrypt letsencrypt provides 4 files
I renamed cert.pem to sitemane.crt, privkey.pem to sitename.key, but the module does not see the certificates, although if you slip the wrong files there will be an error
am i doing right?

**Comment by mworrell** [comment]
You should replace _sitename_ with the name of your own site.

So for the Zotonic site, which is called `zotonicwww` it is:  `zotonicwww.crt`

**Comment by heiheshang** [comment]
hm
`Use SSL Certificate from a Certificiate Authority.

This module doesn’t supply a certificate.`
something is missing

**Comment by heiheshang** [comment]
I realized is_file does not work for symbolic links

**Comment by mworrell** [comment]
Hard link of soft link?

Just tested on macOS and Ubuntu, there `filelib:is_file/1` return true on a soft link.

**Comment by heiheshang** [comment]
soft link
