### ISSUE TITLE
Failed to register a ServiceWorker for scope 

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2349]
`An SSL certificate error occurred when fetching the script.
(index):1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://424111.ru:8443/') with script ('https://424111.ru:8443/cotonic-service-worker.js'): An SSL certificate error occurred when fetching the script.
2(index):1 Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by mworrell** [comment]
Are you using the current master? I just pushed an issue were the SNI function would crash on unknown hostnames.

**Comment by heiheshang** [comment]
yes i use master

**Comment by mworrell** [comment]
Self-signed certs?  Or Let's Encrypt?

**Comment by heiheshang** [comment]
Self-signed certs

**Comment by heiheshang** [comment]
Let's Encrypt does not work

**Comment by heiheshang** [comment]
[https://deanhume.com/testing-service-workers-locally-with-self-signed-certificates/](url)

**Comment by mworrell** [comment]
Thanks, in Cotonic I added a catch for the error and a link to updated docs at https://cotonic.org/#model.serviceWorker
