### ISSUE TITLE
administrator does not have permission to view editing categories

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2354]
after opening the category page, I see the categories, after which they disappear

**Comment by mworrell** [comment]
Could you check with the newest master?  We fixed an issue where _wired_ style postbacks could be lost if they were sent too early, before the bridge was started. I can imagine that that could cause the problem you describe.

**Comment by mworrell** [comment]
BTW if you say _administrator_ do you mean the `admin` account?

**Comment by heiheshang** [comment]
yes

**Comment by mworrell** [comment]
Thanks for the quick reply - I just tested here locally with the `admin` account on my setup and here it worked (tip of master).

**Comment by heiheshang** [comment]
Yes, on another site everything works for me, but here I have a problem
`Proceed with care: You are editing a: Predicate. This is system content.`

**Comment by mworrell** [comment]
That is just a warning that you are editing something that is basic to the system.

We added that warning as people accidentally were editing categories when they thought they were editing a document.

**Comment by mworrell** [comment]
@heiheshang can I close this issue or do you still have the original problem?
