### ISSUE TITLE
Unable to set new category of a resource if the prior category has been removed.

### ISSUE THREAD

**Issue by OldhamMade** [zotonic/zotonic#2360]
### Problem
Given resource "Ocean" is assigned to category "Blue"
When the category "Blue" is removed from the database (through error, or programatically)
Then the resource "Ocean" has no category defined
And the admin interface does not allow a new category to be assigned.

### Screenshot
<img width="713" alt="Screenshot 2020-03-18 at 08 30 43" src="https://user-images.githubusercontent.com/111193/76936185-c41f9580-68f2-11ea-91ab-5ab4ea59737f.png">

### Affected versions
Latest `0.x` branch

**Comment by mworrell** [comment]
Ah yes, I think this was an issue with a missing foreign key constraint on category_id that allows this to happen in the first place.

In the second place you are right that you should be able to change the category if this happens.

**Comment by mworrell** [comment]
@OldhamMade if you are able to, could you check if #2389 fixes your problem?

**Comment by mworrell** [comment]
Next: Merge 0.x changes into master.
