### ISSUE TITLE
z_db:update It does not support the scheme

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2369]
I can not update the table in another schema

**Comment by mworrell** [comment]
That is true - we are assuming the whole site is using a single database and schema in psql.

Currently we don't have any support for using different schemas for different tables.

What are you trying to do?

**Comment by heiheshang** [comment]
I work with tables outside the same schema

**Comment by mworrell** [comment]
If the `src` table is only present in the other schema, then you could set your psql search path. Per default, if we open a connection, we set it to the configured schema.

**Comment by heiheshang** [comment]
My zotonic is part of a large project, I have 4 circuits that I work with, I have to duplicate zotonic functions

**Comment by mworrell** [comment]
Do you have a `rsc` table in multiple schemas?  Or one in a specific schema and different tables in the other schemas?

**Comment by heiheshang** [comment]
there is a scheme for zotonic and there are schemes for other tables

**Comment by mworrell** [comment]
Thinking aloud here: what if we would add an (optional) configuration to set the `search_path` for new connections.  Per default we are using the schema name for the search_path, having a configuration means you can change it (or set it to something like `default` and then use the psql user or database configuration so set the default search path)

**Comment by heiheshang** [comment]
why I just can’t specify the name of the scheme in the request, if I do z_db:q, then I just specify the name of the scheme through "." and everything works

**Comment by mworrell** [comment]
We have also different processes that access the `rsc` table - think of the pivoting process and the normal `m_rsc` routines.

They all should know how and where to find their tables.

I understood you put the _zotonic_ tables in a separate schema, which is not the configured schema.

Alternatively you could configure the schema of the Zotonic db connection to be the schema where the Zotonic tables are residing, and then use the `schema.table` notation to access the other tables?

**Comment by heiheshang** [comment]
I think it is necessary to give the opportunity to specify the scheme, if there is no scheme, use the default

**Comment by mworrell** [comment]
That could be done for the update, but what about all the other queries?

Do you have a single `rsc` table in all the schemas, or are there multiple?

**Comment by heiheshang** [comment]
no, rsc alone, zotonic lives in his scheme

**Comment by mworrell** [comment]
This only affects the table name sanitizer, to have it allow a dot.
