### ISSUE TITLE
INSTALLATION step 3: create a new Zotonic site, based on the ‘blog’ skeleton site

### ISSUE THREAD

**Issue by noargs** [zotonic/zotonic#2400]
I have added my site name to '/etc/hosts' lets say **127.0.0.1   rabbit.test**

i have been trying to run this on my terminal **$ bin/zotonic addsite -s blog rabbit**  its says _Please specify the hostname, for example: -H rabbit.test_

i have tried using -H arg like **$ bin/zotonic addsite -s blog -H rabbit.test** or **$ bin/zotonic addsite -s blog -H rabbit** and all sort of stuff and its not letting me create skeleton site

**Comment by mworrell** [comment]
Are you using the master version?

**Comment by noargs** [comment]
i have used [git clone https://github.com/zotonic/zotonic.git] as stated in developer guide's getting started section

**Comment by mworrell** [comment]
Thanks, will check, I see that the handling of the argument is in the code.

You always get that particular error?

**Comment by noargs** [comment]
its my first time using zotonic. but im stuck at this point as it doesnt put me through. according to installation guide it only needs one argument '-s' for type of template i want to create i.e. blog, emptysite etc AND mysite name

**Comment by noargs** [comment]
i have seen 'status website' running fine. its 'create your first site' where i'm stuck at.

**Comment by mworrell** [comment]
Yes, that is the way it should be, I am checking.

In the meantime you could also go to the zotonic status site and use the GUI to add a site.

The password is visible using `bin/zotonic config`  (at the top)  the username for that site is `wwwadmin`

**Comment by mworrell** [comment]
@noargs I fixed an issue with the generation of the default hostname from the supplied site name.

**Comment by mworrell** [comment]
Thanks for reporting!
