### ISSUE TITLE
Add toggle to ignore template caching in development menu

### ISSUE THREAD

**Issue by OldhamMade** [zotonic/zotonic#2408]
In most cases, it is preferable to develop locally with caching disabled, especially when working on templates.

Zotonic should have a toggle under the `System > Development` menu which disables all caching in templates, so that `{% cache … %}` tags have no effect. 

This toggle should be set to `caching=false` by default for the "development" environment.

**Comment by mworrell** [comment]
Good idea, can indeed be a simple switch in the config.
