### ISSUE TITLE
Missing dependencies: [cron]

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#2409]
Using latest master, attempting to start Zotonic, and a number of modules not started due to missing dependency:

`03:34:16.902 [error] z_module_manager:995 [seannaswell] error @ z_module_manager:995  Could not start module mod_logging, reason Missing dependencies: [cron]`

Modules not started: mod_ratelimit, mod_logging, mod_twitter

As a result, I am not able to login. See example behavior here by trying to login: [login page](https://testing.seannaswell.com)

Running on FreeBSD, obviously the OS level cron functionality is available. Is this a missing Erlang module, or if it's the OS level cron, how is it being referenced?

**Comment by mworrell** [comment]
You can enable `mod_cron` with:

```erlang
z_module_manager:activate(mod_cron, z:c(yoursite)).
```

Maybe we need some automatic starting of dependent modules. As these dependencies do change in time.

**Comment by seannaswell** [comment]
You are correct, this is a restored database that was backed up a few months ago. It seems some changes have been made in that time which are causing this.

**Comment by mworrell** [comment]
@ddeboer and @mmzeeman what do you think, should we activate/deactivate modules automatically depending on their dependencies?

**Comment by mmzeeman** [comment]
Maybe the error message should be more descriptive. Now it mentions a missing dependency, which sounds very serious when you don’t know how zotonic works. Is it possible to find out what modules are available to provide “cron”?

**Comment by mworrell** [comment]
Yes, we can easily build an index of all module _provides_ and _depends_.

We do build a dependency graph for the activated modules (used for the start order of the modules).
We can make a complete graph for all modules as well. From that graph we can answer all questions about dependencies and which extra modules needs to be activated to activate a module.

**Comment by mmzeeman** [comment]
Isn't it better then to write this:

```
reason Dependencies not started: [cron], please start mod_cron or mod_also_providing_cron. See: <manual entry> on how to start modules.
```

**Comment by mworrell** [comment]
Definitely :-)

Should also be in a dialog when you try to enable a module, maybe with checkboxes to enable the other modules?

**Comment by mworrell** [comment]
This is really one of those things that can help new people (and people upgrading).
