### ISSUE TITLE
Cannot add site from wwwadmin

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#2410]
Hi,
running zotonic from master (85a8ca) on Debian 10, postgresql 11 and Erlang/OTP 21 [erts-10.2.4].
I have problems to add a new site from the web admin. Zotonic can create the database zotonic so postgresql connection seems fine, but no schema for the site (basesite template) is created.
I have not tried to use the addsite command from the shell.

15:22:03.578 [info] zotonicker z_installer:110 Installing database with db options: [{dbdatabase,"zotonic"},{dbdriver,z_db_pgsql},{dbdropschema,false},{dbhost,"localhost"},{dbport,5432},{dbschema,"zotonicker"},{dbuser,"zotonic"}]
15:22:03.621 [info] z_module_manager:1285 [zotonic_site_status] Skipping schema for mod_base as zotonic_site_status does not use a database ('nodb').
15:22:03.688 [error] z_module_manager:995 [zotonic_site_status] error @ z_module_manager:995  Could not start module mod_ratelimit, reason Missing dependencies: [cron]
15:22:03.689 [info] z_site_startup:74 [zotonic_site_status] info @ z_site_startup:74  Site zotonic_site_status started, modules loaded
15:22:03.999 [error] z_install:52 gen_server <0.1288.0> terminated with reason: no match of right hand value {rollback,{{badmatch,{error,{error,error,<<"42601">>,syntax_error,<<"syntax error at or near \"identity_type_key_unique\"">>,[{file,<<"scan.l">>},{line,<<"1133">>},{position,<<"15">>},{routine,<<"scanner_yyerror">>},{severity,<<"ERROR">>}]}}},[{z_install,'-install_sql_list/2-lc$^0/1-0-',2,[{file,"/home/erlang/zotonic/apps/zotonic_core/src/install/z_install.erl"},{line,63}]},{z_install,install_sql_list,2,[{file,"/home/erlang/zotonic/apps/zotonic_core/src/install/z_install.erl"},{line,63}]},{z_install,...},...]}} in z_install:install/1 line 52

**Comment by mworrell** [comment]
Hi @karlsson, can you check the branch in #2411 ?

**Comment by karlsson** [comment]
It works with that branch thanks.
I got some error in the log, but I suspect it was me entering a bad host name first that could not be resolved. I will check some more later, but the site is created sucessfully.

**Comment by karlsson** [comment]
I tried with a clean database and site is created but I see the following error records in the console (starting as debug):
```
19:42:57.352 [error] z_db:474 z_db error {error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"pivot_task_queue_module_funcion_key_key\"">>,[{constraint_name,<<"pivot_task_queue_module_funcion_key_key">>},{detail,<<"Key (module, function, key)=(m_category, renumber_pivot_task, m_category:renumber) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"534">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"zotonicker">>},{severity,<<"ERROR">>},{table_name,<<"pivot_task_queue">>}]} in query insert into "pivot_task_queue" ("props", "module", "function", "key", "due") values ($1, $2, $3, $4, $5) returning id with [{term,[{args,[]}]},m_category,renumber_pivot_task,<<"m_category:renumber">>,{{2020,4,16},{19,43,7}}]```

**Comment by mworrell** [comment]
Ah, I think I have to catch that one - that comes from a race condition by the modules adding their own categories in different threads.

**Comment by mworrell** [comment]
Will take a look at the race conditions in another issue, so that we can merge the fix for your original problem.
