### ISSUE TITLE
Race condition scheduling tasks

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2412]
As reported by @karlsson:

I tried with a clean database and site is created but I see the following error records in the console (starting as debug):

```
19:42:57.352 [error] z_db:474 z_db error {error,error,<<"23505">>,unique_violation,<<"duplicate key value violates unique constraint \"pivot_task_queue_module_funcion_key_key\"">>,[{constraint_name,<<"pivot_task_queue_module_funcion_key_key">>},{detail,<<"Key (module, function, key)=(m_category, renumber_pivot_task, m_category:renumber) already exists.">>},{file,<<"nbtinsert.c">>},{line,<<"534">>},{routine,<<"_bt_check_unique">>},{schema_name,<<"zotonicker">>},{severity,<<"ERROR">>},{table_name,<<"pivot_task_queue">>}]} in query insert into "pivot_task_queue" ("props", "module", "function", "key", "due") values ($1, $2, $3, $4, $5) returning id with [{term,[{args,[]}]},m_category,renumber_pivot_task,<<"m_category:renumber">>,{{2020,4,16},{19,43,7}}]
```

**Comment by mworrell** [comment]
This problem is not a big problem, as the error is just signifying that there two rows are inserted at the same time in two parallel transactions. As both rows are the same (and it is quite arbitrary who should win anyway) it is ok to ignore the error.

We can change the `z_db:insert/3` routines to be less noisy about this situation and just emit a info message that we did run into a duplicate key. Being silent might be problematic with other kind of erroneous inserts.

**Comment by karlsson** [comment]
Unique constraint violation is now logged as info - thanks.
When I create and empty site now with basesite skeleton it shows up very [empty](https://zotonicker.creado.se/) though.

**Comment by karlsson** [comment]
Before I think all different kinds of categories showed up in the recent content column...

**Comment by mworrell** [comment]
At least the articles should show up there.... something to test tomorrow.

**Comment by mworrell** [comment]
Might be something with the initial content.

**Comment by karlsson** [comment]
Well actually the text I added shows up in the top item. But I think there used to be some default text before, as for the other items.
Actually I am running 2 sites (2 schemas) and in this case it was the 2nd site that I added. The [first site](https://creado.se/) was not created by templates but from a backup.
Before adding the 2nd site I cleaned the previous instance (of 2nd site) by stopping zotonic, removing the site dir in apps_user and under _build and  DROP SCHEMA sitename CASCADE; in postgres.
I can test tomorrow with a completely empty database and see what happens in case there is some interference when you have several schemas.

**Comment by mworrell** [comment]
Might be that the default content insert is not working anymore, as those are also fed into the rsc routines and I needed to change some code in the module installation.

**Comment by karlsson** [comment]
OK - I tested with an empty database ( DROP DATABASE zotonic; ) and added a basesite with the same result, so I think your assumption is probably right.

**Comment by karlsson** [comment]
Thanks @mworrell, seems that content insert is working now. After commit 7cc1c44a67072a90d25632dbe943074ebcc32870 ?

**Comment by mworrell** [comment]
Yes, that fixes the module content initialization. Couldn’t find the issue to report it.
