### ISSUE TITLE
Zotonic command line somewhat detached

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#2418]
Seems the Zotonic command line is not working properly.
I can start the zotonic server instance by `./bin/zotonic start` even if the command response indicates other. Any other command fails, if I issue a stop the server keeps on running,
```
erlang@creado-se-3:~/zotonic$ ./bin/zotonic start
Waiting for zotonic: .... No response after 30 seconds
erlang@creado-se-3:~/zotonic$ ./bin/zotonic stop
Stopping zotonic 'zotonic@creado-se-3' .. Not running
erlang@creado-se-3:~/zotonic$ ./bin/zotonic shell
Zotonic node at 'zotonic@creado-se-3' is not running
erlang@creado-se-3:~/zotonic$ ./bin/zotonic start
Waiting for zotonic: .... No response after 30 seconds
erlang@creado-se-3:~/zotonic$ ./bin/zotonic status
Zotonic node at 'zotonic@creado-se-3' is not running
erlang@creado-se-3:~/zotonic$ ./bin/zotonic shell
Zotonic node at 'zotonic@creado-se-3' is not running
```
When checking with a browser I can connect to the site after the first start and also after the stop.

**Comment by mworrell** [comment]
Could this be something with `epidemic and/or name resolution?

**Comment by mworrell** [comment]
Seems it starts normal, and then we can’t connect to it using Erlang distribution.

**Comment by karlsson** [comment]
Oops! Sorry my bad.
I needed to add 127.0.1.1 to be accepted in the firewall filter rules on my VPS since the local hostname (creado-se-3) is pointing to this in /etc/hosts.
