### ISSUE TITLE
Users which have set their tz to Asia/Tehran can't logon

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2423]
Due to a problem in `qdate_localtime` it is not possible for users in this timezone to logon. The reason is that there is an omission in the tz database for this timezone. See: https://github.com/choptastic/qdate_localtime/issues/2

I have forked `qdata_localtime` and made a rule of the thumb rounding rule.

**Comment by mworrell** [comment]
Jesse has merged @mmzeeman 's changes to qdate_localtime, so we can use their repo again.
