### ISSUE TITLE
problem open /admin/ssl

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2435]
`17:31:33.790 [error] at: "cowmachine:request_1:82", code: 500, dst: #{ip4 => "172.26.0.4",port => 8443}, in: cowmachine, level: error, path: <<"/ru/admin/ssl">>, reason: {function_clause,[{z_ssl_certs,decode_sans,[asn1_NOVALUE],[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_ssl_certs.erl"},{line,359}]},{z_ssl_certs,decode_cert,1,[{file,"/opt/zotonic/apps/zotonic_core/src/support/z_ssl_certs.erl"},{line,321}]},{m_admin_config,self_signed,1,[{file,"/opt/zotonic/apps/zotonic_mod_admin_config/src/models/m_admin_config.erl"},{line,83}]},{m_admin_config,ssl_certificates,1,[{file,"/opt/zotonic/apps/zotonic_mod_admin_config/src/models/m_admin_config.erl"},{line,56}]},{m_admin_config,m_get,3,[{file,"/opt/zotonic/apps/zotonic_mod_admin_config/src/models/m_admin_config.erl"},{line,34}]},{tpl_1474b67a6c7fb4b290fa7e15c02d5bb48a2aa7d8,render_block,4,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin_config/priv/templates/admin_config..."},...]},...]}, src: #{ip4 => "159.255.23.114",port => 53646}, text: "Stop request"`

**Comment by mworrell** [comment]
hi!  Looks like there is something wrong with the self-signed certificate.  Of course still no reason to crash, so will resolve that one.

**Comment by heiheshang** [comment]
the page does not open at the same time, I can’t configure it because of this  Let's Encrypt.

**Comment by mworrell** [comment]
Could you send me (via encrypted email or another secure channel) your self-signed certificate?

You can find secure credentials at https://keybase.io/mworrell

**Comment by mworrell** [comment]
I expect your problem to be fixed, please let me know.
