### ISSUE TITLE
characters_to_binary/2	[ [...], unicode ]	 z_model	maybe_binary/1

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2438]
I don’t understand what kind of mistake ? Before the update, everything worked fine. Even if the template is empty
`
Модуль | Функция / шаблон | Аргументы | Файл
-- | -- | -- | --
unicode | characters_to_binary/2 | [ [...], unicode ] |  
z_model | maybe_binary/1 |   | /opt/zotonic/_build/default/lib/zotonic_core/src/support/z_model.erl:231
z_model | -binarize/1-lc$^0/1-0-/1 |   | /opt/zotonic/_build/default/lib/zotonic_core/src/support/z_model.erl:226
z_model | -binarize/1-lc$^0/1-0-/1 |   | /opt/zotonic/_build/default/lib/zotonic_core/src/support/z_model.erl:226
z_model | model_call/5 |   | /opt/zotonic/_build/default/lib/zotonic_core/src/support/z_model.erl:209
print_organisacion.tplzotonic_mod_lk | render/3 |   | /opt/zotonic/_build/default/lib/zotonic_mod_lk/priv/templates/print_organisacion.tpl:30
template_compiler | render/4 |   | /opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl:107
z_template | render_block/4 |   | /opt/zotonic/apps/zotonic_core/src/support/z_template.erl:98

`

**Comment by mworrell** [comment]
Apparently a list that was not a unicode string was passed to the model routines.

I have removed the list-to-unicode-binary mapping in #2439

Can you check if that branch works well for you?

I am running some tests - my local tests are all ok (for now, not finished yet).

**Comment by heiheshang** [comment]
yes, this solves the problem

**Comment by mworrell** [comment]
Thanks for checking!  Merging the changes.
