### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by lukascernohorsky** [zotonic/zotonic#2463]
Branch master
Gentoo with Erlang/OTP 23

Few day ago, i updated from git. From this day I cannot build zotonic. Only what i see is: 
```

==> Verifying dependencies...
===> Compiling syslog
===> Compiling c_src/syslog_drv.c
===> Linking priv/syslog_drv.so
make: *** [GNUmakefile:36: compile] Error 1
```

**Comment by mworrell** [comment]
I am running in some rebar3 problem in combination with Jiffy on OTP 23.0
Also seems to be related to building C code.

Testing a bit further.

**Comment by mworrell** [comment]
Now patched letsencrypt-erlang and removed jiffy, so testing a bit further on my branch.

**Comment by mworrell** [comment]
Merged OTP23 compatibility, which removes compatibility with OTP20 and earlier.
