### ISSUE TITLE
DKIM problem

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2470]
`17:27:43.715 [info] z_model:129 Publish to unknown model <<"notifier">>`

I can’t get DKIM because no one provides the model
template use `{% with m.notifier.first.dkim_admin_info as info %}`
who provides the model m.notifier ?

**Comment by mworrell** [comment]
Good one, we have removed that model as we don't want to have external API access to the internal notification bus.

This needs to be replaced with a dkim model providing these services.

**Comment by mworrell** [comment]
Should be fixed now. Thanks for the report!
