### ISSUE TITLE
I can not compile bcrypt

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2472]
`cc -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes -fPIC -I /usr/local/lib/erlang/erts-11.0.2/include/ -I /usr/
local/lib/erlang/lib/erl_interface-4.0/include  -c -o /opt/zotonic/_build/default/lib/bcrypt/c_src/bcrypt.o /opt/zotonic/_
build/default/lib/bcrypt/c_src/bcrypt.c                                                                                   
In file included from /opt/zotonic/_build/default/lib/bcrypt/c_src/bcrypt.c:54:                                           
/opt/zotonic/_build/default/lib/bcrypt/c_src/erl_blf.h:62:5: error: unknown type name 'u_int32_t'                         
   62 |     u_int32_t S[4][256]; /* S-Boxes */                                                                            
      |     ^~~~~~~~~                                                                                                     
/opt/zotonic/_build/default/lib/bcrypt/c_src/erl_blf.h:63:5: error: unknown type name 'u_int32_t'                         
   63 |     u_int32_t P[BLF_N + 2]; /* Subkeys */                                                                         
      |     ^~~~~~~~~                                                                                                     
/opt/zotonic/_build/default/lib/bcrypt/c_src/erl_blf.h:72:35: error: unknown type name 'u_int32_t'                        
   72 | void Blowfish_encipher(blf_ctx *, u_int32_t *, u_int32_t *);                     `

**Comment by heiheshang** [comment]
`/* Solaris compatibility */                                                                                               
ifdef __sun                                                                                                          
#define u_int8_t uint8_t                                                                                                  
#define u_int16_t uint16_t                                                                                                
#define u_int32_t uint32_t                                                                                                
#define u_int64_t uint64_t                                                                                                
#endif`
this block is also needed for Linux

**Comment by mworrell** [comment]
What Linux distribution are you using?
And could you try to build https://github.com/erlangpack/bcrypt from scratch?

Our CI and production systems are running on Linux (mainly Ubuntu) and we don't have problems there.

**Comment by mworrell** [comment]
Also wondering, I see `cc` is used. Though on Linux I would expect `gcc`

https://github.com/erlangpack/bcrypt/blob/master/c_src/Makefile#L32

Which C compiler do you have installed?  Maybe something different that gcc?

**Comment by heiheshang** [comment]
alpine linux , use docker from github zotonic

**Comment by heiheshang** [comment]
I do make as after starting start-docker.sh

**Comment by mworrell** [comment]
Thanks, will check.

**Comment by mworrell** [comment]
Fixed in https://github.com/erlangpack/bcrypt/pull/15

Will make a new bcrypt release (after some additional testing)
