### ISSUE TITLE
Category hierarchy not reflected in admin screens

### ISSUE THREAD

**Issue by OldhamMade** [zotonic/zotonic#2473]
As I understand it, a category is simply an entity in a collection with a type of "category". However, the admin allows some type of hierarchy to be created, as is evident when viewing `Structure > Categories`.

This lack of hierarchy context causes issues in a number of places. For example, when editing a resource in the admin area, the section under the title simply states `Category: {name}`. However, category names can be duplicated. So, seeing (for example) `Category: Feature` isn't very useful when it can have vastly different meaning: `Articles > Feature` is very different to `Software > My Product > Feature` and `Documentation > Feature`.

**Comment by mworrell** [comment]
![Screenshot 2020-07-02 at 14 23 11](https://user-images.githubusercontent.com/38268/86358358-a0991480-bc6f-11ea-9dc8-7eebd76e78df.png)

Something like this?

**Comment by mworrell** [comment]
Thanks!
