### ISSUE TITLE
problem mqtt_session

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2478]
`mqtt_sessions:get_user_context(z_context:site(Context), Remote)` return notfound for any user other than administrator

`is_allowed(Action, Topic, Packet, Context) when Action =:= subscribe; Action =:= publish ->
    z_acl:is_admin(Context) orelse is_allowed_acl(Action, Topic, Packet, Context).`
administrator can always work with messages

ordinary user has problems with client_id & routing_id 
mqtt_session does not save id_routing in ets

**Comment by heiheshang** [comment]
user needs permissions on mod_admin_config

**Comment by mworrell** [comment]
The main check is actually above:

```erlang
            case       Context#context.routing_id =:= Remote
                orelse Context#context.client_id  =:= Remote
            of
```

There we check if the current user (identified by the Context) has the routing or client id of the MQTT session set.
If so, then we can conclude that this context "belongs" to the same session as the user.

With the call:

```erlang
mqtt_sessions:get_user_context(z_context:site(Context), Remote)
```

We try to check if the user of the remote client-id (from `bridge/Remote/...` is the same as the user in the current context.

If this all fails (the context does not belong to the current MQTT session, and it is not the same user) then only an administrator is allowed to send the package to the remote client (via the MQTT bridge).

This is to prevent that random messages are sent to non public topics on the client.

You _can_ send message to `bridge/Remote/reply` and `bridge/Remote/public`. The MQTT code on the client will know that messages arriving on those topics need extra scrutiny and can't be trusted by default.

The _reply_ topic is used for responses. The topics are generated by the client and passed in the MQTT request. That makes the response topics controlled by the client and (as they are arbitrary randomly generated) safe to use.

**Comment by heiheshang** [comment]
How is it that I get a message from a client, but I can’t answer myself? Context comes in the message, how would I get a different context?

**Comment by mworrell** [comment]
There are two contexts:

1. The context of the caller (in this case the client)
2. The context of the subscriber

It depends a bit how you subscribed to the topic.

You can see how it is handled in `mod_mqtt` for subscriptions using exported functions:

```erlang
maybe_subscribe({<<"mqtt:", TopicFilter/binary>>, Function}, Module, ModulePid, Context) ->
    SubscriberContext = z_acl:sudo( z_context:new( z_context:site(Context) ) ),
    Callback = {?MODULE, module_callback, [ Module, Function ]},
    z_mqtt:subscribe(TopicFilter, Callback, ModulePid, #{ qos => 0 }, SubscriberContext);
maybe_subscribe(_, _M, _Pid, _Context) ->
    ok.

%% @doc Call the module subscription function using the context of the publisher
-spec module_callback(module(), atom(), map()) -> any().
module_callback(Module, Function, #{ message := Msg, publisher_context := Context }) ->
    Module:Function(Msg, Context).
```

An example of an exported function that is subscribed by `mod_mqtt`:

```erlang
-spec 'mqtt:model/+/delete/#'(mqtt_packet_map:mqtt_packet(), z:context()) -> ok | {error, term()}.
'mqtt:model/+/delete/#'(#{
            type := publish,
            topic := [ <<"model">>, Model, <<"delete">> | Path ]
        } = Msg, Context) ->
    handle_model_request(Model, delete, Path, Msg, Context).
```

The context passed here is the publisher's context.

Like the `observe_...` functions, these MQTT subscription functions _must_ be defined in the main module (like `mod_foobar.erl`) of your module or app.

**Comment by heiheshang** [comment]
I’m obviously not subscribing to anything. I get a submit message, then z_render:wire

**Comment by mworrell** [comment]
So this is just a `event(#submit{....}, Context)` handler?

**Comment by mworrell** [comment]
What are the values for `client_id` and `routing_id` in the received context?

And did the form have a file input?  Or just "normal" inputs?

**Comment by heiheshang** [comment]
yes,4 files input

**Comment by heiheshang** [comment]
yes,event(#submit{....}, Context)

**Comment by heiheshang** [comment]
> What are the values for `client_id` and `routing_id` in the received context?
> 
> And did the form have a file input? Or just "normal" inputs?

client_id,routing_id = undefined

**Comment by mworrell** [comment]
My current guess is that there is no websocket/mqtt connection started.
Can you check if there is a connection?

If there is no connection, then the system doesn't have a client-d (or routing-id).

As the submit contains files the HTTP API is used to transport the form to the server.
Any response needs to come via the MQTT connection.

**Comment by heiheshang** [comment]
how can this be checked?

**Comment by karlsson** [comment]
When I test with my browser client (Firefox) I do Ctrl-Shift-E to activate the Network console and then load the page that should activate the websocket connection. I think one should see a status 101 Switching Protocols for the mqtt-transport path.

**Comment by mworrell** [comment]
Indeed there should be a `mqtt-transport` connection active.

**Comment by mworrell** [comment]
I think I could reproduce the problem described.

Could you check with #2480 if it fixes the issue?

**Comment by mworrell** [comment]
I think your problem has been fixed with #2480 - please reopen if you still encounter these problems.

**Comment by heiheshang** [comment]
some pages have stopped opening, maybe this is due to an update
`14:48:20.525 [error] at: "cowmachine:request_1:82", code: 500, dst: #{ip4 => "172.18.0.3",port => 8443}, in: cowmachine, level: error, path: <<"/ru/admin/edit/909">>, reason: {{case_clause,{ok,{context,#{bindings => #{id => <<"909">>,z_language => <<"ru">>,zotonic_dispatch => admin_edit_rsc,zotonic_dispatch_path => [<<"admin">>,<<"edit">>,<<"909">>],zotonic_site => custom},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>,<<"cache-control">> => <<"max-age=0">>,<<"connection">> => <<"upgrade">>,<<"cookie">> => <<"z.lang=ru; z.tz=UTC; _ym_uid=1593738188772616496; _ym_d=1593738188; z_rldid=6Yn0pXWlN2kSVyzHcR94hhNpEsGkROULdWhKoAnS71OWVZgQfxAH9qZpJVYFaFk4l1lrIk49swO0tcXlePorgApm3kQZxoQD304jgWWs4bXENO1Qh_ZJN9HepZuV0ZU...">>,...},...},...}}},...}, src: #{ip4 => "192.168.1.1",port => 26958}, text: "Stop request"`

**Comment by heiheshang** [comment]
`14:53:13.347 [error] cowboy_http:954 Ranch listener zotonic_https_listener_ipv4 terminated with reason: no function clause matching cowboy_http:commands({state,<0.1550.0>,zotonic_https_listener_ipv4,{sslsocket,{gen_tcp,#Port<0.281>,tls_connection,[{...},...]},...},...}, 1, [{response,500,#{<<"content-length">> => <<"0">>,<<"date">> => <<"Sat, 11 Jul 2020 11:53:12 GMT">>,...},...}]) line 954
`

**Comment by mworrell** [comment]
Do you have a longer crash log for the first error?  Maybe where we can the function where the error was triggered?

**Comment by heiheshang** [comment]
`2020-07-12 04:56:04 =ERROR REPORT====
[{at,"cowmachine:request_1:82"},{code,500},{dst,#{ip4 => "172.18.0.3",port => 8443}},{in,cowmachine},{level,error},{path,<<"/ru/admin/edit/910">>},{reason,{{case_clause,{ok,{context,#{bindings => #{id => <<"910">>,z_language => <<"ru">>,zotonic_dispatch => admin_edit_rsc,zotonic_dispatch_path => [<<"admin">>,<<"edit">>,<<"910">>],zotonic_site => custom},body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>,<<"connection">> => <<"upgrade">>,<<"cookie">> => <<"z.lang=ru; z.tz=UTC; _ym_uid=1593738188772616496; _ym_d=1593738188; z_rldid=ysYZh3iUvQpki1TjszyX-FJwk7zGKNK1wY3rXQHj2YyBy-eYbzASSEW84004AfwD2X4gY3iqygfpx9USL3u7ZhS8XuR46U2YwsHjMq1oeX9gTvOSYeGD_VQvANuCnqA; z.auth=zMSU0eP0rr8cphaGgojIV6WHzrWtGFAxDGQ_1PsfswLyeb-Qqdl8UlPws9bobFQlvzWNHBZDxNDLWgcS7r4WEbB1N2d2Gf0z5txzZgPEeVtMgP1CHf_ln7n9YytBG8hspDnZGsZPtLBNlaBxrHTuo67oXyJCWqRDMJPATQ7JW3Q9TNJlkcTV46FX; _ym_isad=2">>,<<"host">> => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,<<"referer">> => <<"https://xn--80aaxhsfwd4b8e.xn--p1ai/ru/admin/overview?qs=&qquery=&qgroup=&qcat=express_freight_register&qpagelen=20">>,<<"upgrade-insecure-requests">> => <<"1">>,<<"user-agent">> => <<"Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0">>,<<"x-forwarded-for">> => <<"46.16.10.249">>,<<"x-forwarded-proto">> => <<"https">>,<<"x-real-ip">> => <<"46.16.10.249">>},host => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,method => <<"GET">>,path => <<"/ru/admin/edit/910">>,peer => {{192,168,1,1},61552},pid => <0.15837.2>,port => 443,qs => <<>>,ref => zotonic_https_listener_ipv4,resp_headers => #{<<"content-type">> => <<"text/html;charset=utf-8">>,<<"referrer-policy">> => <<"origin-when-cross-origin">>,<<"x-content-type-options">> => <<"nosniff">>,<<"x-frame-options">> => <<"SAMEORIGIN">>,<<"x-permitted-cross-domain-policies">> => <<"none">>,<<"x-robots-tag">> => <<"noindex">>,<<"x-xss-protection">> => <<"1">>},scheme => <<"https">>,sock => {{172,18,0,3},8443},streamid => 1,version => 'HTTP/1.1'},#{bindings => #{id => <<"910">>,z_language => <<"ru">>,zotonic_dispatch => admin_edit_rsc,zotonic_dispatch_path => [<<"admin">>,<<"edit">>,<<"910">>],zotonic_site => custom},cowmachine_context => {context,#{body_length => 0,cert => undefined,has_body => false,headers => #{<<"accept">> => <<"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8">>,<<"accept-encoding">> => <<"gzip, deflate, br">>,<<"accept-language">> => <<"ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3">>,<<"connection">> => <<"upgrade">>,<<"cookie">> => <<"z.lang=ru; z.tz=UTC; _ym_uid=1593738188772616496; _ym_d=1593738188; z_rldid=ysYZh3iUvQpki1TjszyX-FJwk7zGKNK1wY3rXQHj2YyBy-eYbzASSEW84004AfwD2X4gY3iqygfpx9USL3u7ZhS8XuR46U2YwsHjMq1oeX9gTvOSYeGD_VQvANuCnqA; z.auth=zMSU0eP0rr8cphaGgojIV6WHzrWtGFAxDGQ_1PsfswLyeb-Qqdl8UlPws9bobFQlvzWNHBZDxNDLWgcS7r4WEbB1N2d2Gf0z5txzZgPEeVtMgP1CHf_ln7n9YytBG8hspDnZGsZPtLBNlaBxrHTuo67oXyJCWqRDMJPATQ7JW3Q9TNJlkcTV46FX; _ym_isad=2">>,<<"host">> => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,<<"referer">> => <<"https://xn--80aaxhsfwd4b8e.xn--p1ai/ru/admin/overview?qs=&qquery=&qgroup=&qcat=express_freight_register&qpagelen=20">>,<<"upgrade-insecure-requests">> => <<"1">>,<<"user-agent">> => <<"Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0">>,<<"x-forwarded-for">> => <<"46.16.10.249">>,<<"x-forwarded-proto">> => <<"https">>,<<"x-real-ip">> => <<"46.16.10.249">>},host => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,method => <<"GET">>,path => <<"/ru/admin/edit/910">>,peer => {{192,168,1,1},61552},pid => <0.15837.2>,port => 443,qs => <<>>,ref => zotonic_https_listener_ipv4,scheme => <<"https">>,sock => {{172,18,0,3},8443},streamid => 1,version => 'HTTP/1.1'},#{cowmachine_forwarded_host => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,cowmachine_forwarded_port => 443,cowmachine_forwarded_proto => <<"https">>,cowmachine_proxy => true,cowmachine_remote => <<"46.16.10.249">>,cowmachine_remote_ip => {46,16,10,249}},custom,undefined,undefined,undefined,undefined,undefined,false,undefined,undefined,{'z_db_pool$custom',z_db_pgsql},undefined,[ru],<<"Asia/Yakutsk">>,#{},'z_depcache$custom','z_dispatcher$custom','z_template$custom','z_scomp$custom','z_dropbox$custom','z_pivot_rsc$custom','z_module_indexer$custom','z_trans_server$custom'},cowmachine_controller => controller_admin_edit,cowmachine_controller_options => [seo_noindex],cowmachine_cookies => [{<<"z.lang">>,<<"ru">>},{<<"z.tz">>,<<"UTC">>},{<<"_ym_uid">>,<<"1593738188772616496">>},{<<"_ym_d">>,<<"1593738188">>},{<<"z_rldid">>,<<"ysYZh3iUvQpki1TjszyX-FJwk7zGKNK1wY3rXQHj2YyBy-eYbzASSEW84004AfwD2X4gY3iqygfpx9USL3u7ZhS8XuR46U2YwsHjMq1oeX9gTvOSYeGD_VQvANuCnqA">>},{<<"z.auth">>,<<"zMSU0eP0rr8cphaGgojIV6WHzrWtGFAxDGQ_1PsfswLyeb-Qqdl8UlPws9bobFQlvzWNHBZDxNDLWgcS7r4WEbB1N2d2Gf0z5txzZgPEeVtMgP1CHf_ln7n9YytBG8hspDnZGsZPtLBNlaBxrHTuo67oXyJCWqRDMJPATQ7JW3Q9TNJlkcTV46FX">>},{<<"_ym_isad">>,<<"2">>}],cowmachine_disp_path => undefined,cowmachine_forwarded_host => <<"xn--80aaxhsfwd4b8e.xn--p1ai">>,cowmachine_forwarded_port => 443,cowmachine_forwarded_proto => <<"https">>,cowmachine_proxy => true,cowmachine_range_ok => true,cowmachine_remote => <<"46.16.10.249">>,cowmachine_remote_ip => {46,16,10,249},cowmachine_resp_body => undefined,cowmachine_resp_chosen_charset => <<"utf-8">>,cowmachine_resp_code => 500,cowmachine_resp_content_encoding => <<"identity">>,cowmachine_resp_content_type => {<<"text">>,<<"html">>,[]},cowmachine_resp_redirect => false,cowmachine_resp_transfer_encoding => undefined,cowmachine_site => custom,dispatch_rule => admin_edit_rsc,path_tokens => [<<"admin">>,<<"edit">>,<<"910">>]},custom,controller_admin_edit,undefined,undefined,undefined,{aclug,[344,327],[],publish},false,1,undefined,{'z_db_pool$custom',z_db_pgsql},undefined,[ru],<<"UTC">>,#{auth_expires => 14390,auth_options => #{sid => <<"0uVbsUCUMwsQ7m1PCbIX">>},id => 910,q => [{<<"id">>,<<"910">>},{<<"z_language">>,<<"ru">>},{<<"zotonic_dispatch">>,admin_edit_rsc},{<<"zotonic_dispatch_path">>,[<<"admin">>,<<"edit">>,<<"910">>]},{<<"zotonic_site">>,custom}],seo_noindex => true},'z_depcache$custom','z_dispatcher$custom','z_template$custom','z_scomp$custom','z_dropbox$custom','z_pivot_rsc$custom','z_module_indexer$custom','z_trans_server$custom'}}},[{tpl_4146ae85982e8966d34ca4a24472c44d481a4598,render_block,4,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_cargo/priv/templates/_admin_edit_content_express_freight_register.tpl"},{line,26}]},{tpl_4bcff49acc59122b9601d17b4c95c5c99ccb32af,render_block,4,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/admin_edit_widget_std.tpl"},{line,16}]},{tpl_4bcff49acc59122b9601d17b4c95c5c99ccb32af,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_admin/priv/templates/admin_edit_widget_std.tpl"},{line,3}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,107}]},{template_compiler_runtime_internal,include_1,7,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,202}]},{tpl_aac3ef981bb862bca9e9d7c8882c4271dff5825c,render,3,[{file,"/opt/zotonic/_build/default/lib/zotonic_mod_cargo/priv/templates/_admin_edit_main_parts.express_freight_register.tpl"},{line,5}]},{template_compiler,render,4,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,107}]},{template_compiler_runtime_internal,include_1,7,[{file,"/opt/zotonic/_build/default/lib/template_compiler/src/template_compiler_runtime_internal.erl"},{line,202}]}]}},{src,#{ip4 => "192.168.1.1",port => 61552}},{text,"Stop request"}]
`

**Comment by heiheshang** [comment]
Now I see that the get / mqtt-transport request has stopped passing

**Comment by heiheshang** [comment]
`Host: xn--80aaxhsfwd4b8e.xn--p1ai
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: */*
Accept-Language: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://xn--80aaxhsfwd4b8e.xn--p1ai
Sec-WebSocket-Protocol: mqtt.cotonic.org, mqtt
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: 7j+BYPefTawTi4ZiUDLfEg==
Connection: keep-alive, Upgrade
Cookie: z.lang=ru; z.tz=UTC; _ym_uid=1593738188772616496; _ym_d=1593738188; z_rldid=ysYZh3iUvQpki1TjszyX-FJwk7zGKNK1wY3rXQHj2YyBy-eYbzASSEW84004AfwD2X4gY3iqygfpx9USL3u7ZhS8XuR46U2YwsHjMq1oeX9gTvOSYeGD_VQvANuCnqA; z.auth=KA7Kxoti_zYzFrWSpr_LT48_vP7RNNQnMfR0GRzmenUxo908Nts5ECrdYMFeKPTDn6sdtWKh2w0xeiJSOS2nilEKFVpHmlm3yGO01Zbr5Kw9V6nS3WFipcXq90gXNW242QvoooAApHAvZun8UzykS__dJIpRDfGie77MzGseb2awreyYL5R7Ri3n; _ym_isad=2
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket`

**Comment by heiheshang** [comment]
it was a firefox problem

**Comment by mworrell** [comment]
That first error came from `_admin_edit_content_express_freight_register.tpl` on line 26.
Is it an error in custom code or some zotonic function?

**Comment by heiheshang** [comment]
I can’t understand what is happening, even if I delete the code, the error still leads to this line in the template

**Comment by mworrell** [comment]
@heiheshang even after a stop/start of zotonic?

Could you mail me the offending template, I am thinking of:

1. An unexpected `{ok, Context}` result from some callback
2. An omission in the generated code
