### ISSUE TITLE
Have 0.x depend on jsx 3.0.0 instead of 2.8.2

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#2482]
#2450 adds `jsx` as a dependency, currently [Ginger](https://github.com/driebit/ginger) uses a fork of `jsx` so this causes some conflicts. In a private conversation Marc mentioned the release of `jsx` 3.0.0 which adds the same defaults as our fork did. 

Would it be possible for Zotonic to depend om 3.0.0 instead? I think this means updating https://github.com/zotonic/jsxrecord/issues as well.

**Comment by mworrell** [comment]
It seems that the 3.0 only changed the default return format.

https://github.com/talentdeficit/jsx/blob/v3.0.0/CHANGES.md

Looking how we use it, that shouldn't be a problem in the 0.x and the master.
As we "inherit" jsx from jsxrecord, the change should be made there.

/cc @mmzeeman

**Comment by mworrell** [comment]
After a new jsxrecord has been released we can update the dependencies in 0.x and 1.0
