### ISSUE TITLE
Problem if one language

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2487]
if you set 1 language, then there is no way to edit the title of the page

**Comment by mworrell** [comment]
Can you give an example?  I am not sure about how I can try to reproduce this.

**Comment by heiheshang** [comment]
![title](https://user-images.githubusercontent.com/111087/87758651-d0d3dc00-c847-11ea-82f6-3a5b1c842022.png)

**Comment by heiheshang** [comment]
![language](https://user-images.githubusercontent.com/111087/87758775-0c6ea600-c848-11ea-81fc-61e54f1083ed.png)

**Comment by mworrell** [comment]
I could reproduce your problem.

I have added a fix and better language tab switching in #2488, can you check if that branch also fixes the problem for you?
(You will need to switch default language back & forth to force the language config to be written correctly).
