### ISSUE TITLE
unknown mediaclass <<"facebook-og">>

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#2495]
Hi,
my console.log is full of : 

`@z_media_tag:props2url:409 unknown mediaclass <<"facebook-og">>`.
By doing a grep in code it seems to be related to mod_twitter or mod_facebook ...

```
apps/zotonic_mod_twitter/priv/templates/_html_head_twitter.tpl:        <meta name="twitter:image" content="http://{{ m.site.hostname }}{% image_url id.depiction mediaclass="facebook-og" %}">
apps/zotonic_mod_facebook/priv/templates/mediaclass.config:    {"facebook-og", [
apps/zotonic_mod_facebook/priv/templates/_html_head_facebook.tpl:	<meta property="og:image" content="http://{{ m.site.hostname }}{% image_url id.depiction mediaclass="facebook-og" %}"/>
```
Am I missing something to let it silent ?
is it a known issue ?

**Comment by crownedgrouse** [comment]
I fixed the issue by doing 
`cp apps/zotonic_mod_facebook/priv/templates/mediaclass.config apps/zotonic_mod_twitter/priv/templates/`
is it due I'm using mod_twitter but not mod_facebook ?

should I do a PR to fix this in code ?

**Comment by mworrell** [comment]
I think we should add a more basic mediaclass for "meta-tag-image-links"  (or however we want to name them).  Maybe in mod_seo.

**Comment by crownedgrouse** [comment]
not sure I understand what you mean, but I understand you want to fix this elsewhere.

**Comment by mworrell** [comment]
Should be ok now :-)
