### ISSUE TITLE
mnesia error

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2504]
`Eshell V10.7.2.1  (abort with ^G)
(zotonic@33cdf2c0046f)1> Mnesia(zotonic@33cdf2c0046f): Data may be missing, Corrupt logfile deleted:
"/opt/zotonic/priv/mnesia/DECISION_TAB.TMP", {file_error,
                                                                                                                          "/opt/zotonic/priv/mnesia/DECISION_TAB.TMP",
                                                                                                                          enospc}
05:46:24.583 [error] Mnesia(zotonic@33cdf2c0046f): ** ERROR ** (could not write core file: enospc)
 ** FATAL ** Cannot open log file "/opt/zotonic/priv/mnesia/DECISION_TAB.TMP": {file_error,"/opt/zotonic/priv/mnesia/DECISION_TAB.TMP",enospc}
05:46:34.578 [error] Mnesia(zotonic@33cdf2c0046f): ** ERROR ** mnesia_event got unexpected event: {'EXIT',<0.179.0>,killed}
05:46:34.578 [error] CRASH REPORT Process mnesia_event with 0 neighbours exited with reason: killed in gen_event:terminate_server/4 line 354
05:46:34.578 [error] CRASH REPORT Process <0.172.0> with 0 neighbours exited with reason: {killed,{mnesia_app,start,[normal,[]]}} in application_master:init/4 line 138
05:46:34.579 [error] zotonic:50 Zotonic start error: {killed,{mnesia_app,start,[normal,[]]}}
05:46:34.579 [info] Application mnesia exited with reason: {killed,{mnesia_app,start,[normal,[]]}}
`

**Comment by mworrell** [comment]
Hi, I see `enospc`, could it be that the disk is full?

**Comment by heiheshang** [comment]
really

**Comment by mworrell** [comment]
It is a bit silly that mnesia gives that error internally.
It doesn't seem that we get that error as a return value when starting mnesia :-(
