### ISSUE TITLE
Calling mod_translation:set_language when a query string exists breaks the query format

### ISSUE THREAD

**Issue by OldhamMade** [zotonic/zotonic#2508]
## Scenario

1. The user is on a page with the URL: `http://zotonic.org/en/news?year=2020`.
2. The user triggers a change to a new language, Nederlands, via a postback, eg: 
`{% wire postback={set_language code=code} delegate="mod_translation" %}`

## Expectation

The page URL should reflect only the change to the new language: 
`http://zotonic.org/nl/news?year=2020`

## Result

The page URL does reflect the change to the new language, but now contains 2 `?` markers which breaks the querystring: 
`http://zotonic.org/nl/news??year=2020`

**Comment by mworrell** [comment]
Fixed in #2509

**Comment by mworrell** [comment]
Thanks @OldhamMade !
