### ISSUE TITLE
make: *** [compile] Error 1

### ISSUE THREAD

**Issue by noargs** [zotonic/zotonic#2513]
downloaded new copy through 'git clone https://github.com/zotonic/zotonic.git' ran 'make' while inside zotonic folder and it gave me this error 

===> Compiling template_compiler
===> Compiling syslog
===> Compiling c_src/syslog_drv.c
===> Linking priv/syslog_drv.so
**make: *** [compile] Error 1** 

any solution would be appreciated please

**Comment by crownedgrouse** [comment]
Try 'rebar3 compile' instead.

**Comment by noargs** [comment]
Thanks word like a charm

**Comment by mworrell** [comment]
That is funny - the Makefile also does a `./rebar3 compile` - wondering why the one works and the other doesn't.

**Comment by crownedgrouse** [comment]
Error is while linking a C shared object. Probably an issue with make, not erlang

**Comment by noargs** [comment]
probably because `rebar3 compile` uses my system rebar3 while `./rebar3 compile` comes bundled with zotonic app

**Comment by mworrell** [comment]
The rebar3 in the zotonic directory is downloaded, and should be the newest version.
You can update that rebar3 to the newest version using `make pull`
