### ISSUE TITLE
Site installation error: {badarg,[{ets,lookup,['slots$mod_signal$zotonicwww',log_message]}

### ISSUE THREAD

**Issue by arcusfelis** [zotonic/zotonic#252]
<code lang="erlang">
(zotonic001@delta.local)1> ** Found 0 name clashes in code paths 
** Found 0 name clashes in code paths 
** Found 0 name clashes in code paths 
opening log file: "/home/user/erlang/zotonic/priv/log/access.log.2011_11_04_16"

=INFO REPORT==== 4-Nov-2011::20:50:42 ===
gen_smtp_server starting at 'zotonic001@delta.local'

=INFO REPORT==== 4-Nov-2011::20:50:42 ===
listening on {0,0,0,0}:2525 via tcp

=INFO REPORT==== 4-Nov-2011::20:50:42 ===
Installing database "zotonic"@"127.0.0.1":5432 "zotonic"
=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:35  {zotonicwww,"Install start."}

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:48  "Inserting config keys"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:57  "Inserting modules"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:95  "Inserting categories"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:255  "Sorting the category hierarchy"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:174  "Inserting base resources (admin, etc.)"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:191  "Inserting username for the admin"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:203  "Inserting predicates"

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
DEBUG: z_install_data:42  {zotonicwww,"Install done."}

=INFO REPORT==== 4-Nov-2011::20:50:45 ===
[zotonicwww] info @ z_datamodel:148  Creating new resource 'menu'

=INFO REPORT==== 4-Nov-2011::20:50:47 ===
[zotonicwww] info @ z_datamodel:148  Creating new resource 'zotonic_news_test1'

=ERROR REPORT==== 4-Nov-2011::20:50:47 ===
** Generic server <0.356.0> terminating 
** Last message in was {'$gen_cast',
                           {log,
                               {log_message,info,1,
                                   <<"Creating new resource 'zotonic_news_test1'">>,
                                   [{module,z_datamodel},{line,148}]}}}
** When Server state == {state,
                            {context,undefined,undefined,undefined,undefined,
                                undefined,zotonicwww,'z_depcache$zotonicwww',
                                'z_notifier$zotonicwww',
                                'z_session_manager$zotonicwww',
                                'z_dispatcher$zotonicwww',
                                'z_template$zotonicwww','z_scomp$zotonicwww',
                                'z_dropbox$zotonicwww',
                                'z_pivot_rsc$zotonicwww',
                                'z_module_indexer$zotonicwww',106551,
                                undefined,en,admin,1,[],[],[],[],[],[],[],[]},
                            []}
** Reason for termination == 
** {badarg,[{ets,lookup,['slots$mod_signal$zotonicwww',log_message]},
            {mod_signal,slots,2},
            {mod_signal,emit,2},
            {mod_logging,handle_cast,2},
            {gen_server,handle_msg,5},
            {proc_lib,init_p_do_apply,3}]}
</code>

**Comment by mworrell** [comment]
Modules have now dependencies, so this kind of startup errors are now prevented,
