### ISSUE TITLE
Logon problem when user has multiple open tabs

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2524]
There is a logon problem when the user has two open tabs and is not authenticated.

Steps to reproduce:

1) Open two tabs
2) Go to `/admin` in both tabs
3) Logon to admin on one of the tabs and wait.
4)  Now two things can happen.
     1) Both tabs go to `/admin` *expected behaviour*
     2) One tab stays on the logon window, the other briefly logs in and then logs out again.

In Safari one of the tabs will reload because the session got invalidated, but it uses the old `z_sid` cookie value causing a reloa (because the session is no longer there and a new one will be started).
This will overwrite the `z_sid` value of the authenticated tab, causing it to logoff.

I can't reproduce this on Chrome, but both Firefox and Safari sometimes have this behaviour. It looks like it is slow to synchronise the new cookie value with other tabs.

**Comment by mworrell** [comment]
Is this now solved by the above merges?

**Comment by mmzeeman** [comment]
Yes it was fixed.
