### ISSUE TITLE
Crash MQTT session

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2526]
`2020-09-26 21:45:06.404 [error] <0.5090.2>@mqtt_sessions_incoming:send_connack_error:62 CRASH REPORT Process <0.5090.2> with 0 neighbours crashed with reason: fun called with wrong arity of 2 instead of 1 in mqtt_sessions_incoming:send_connack_error/3 line 62                                                                                                  
2020-09-26 21:45:06.405 [error] <0.5090.2>@mqtt_sessions_incoming:send_connack_error:62 Ranch listener zotonic_mqtts_liste
ner_ipv4 terminated with reason: fun called with wrong arity of 2 instead of 1 in mqtt_sessions_incoming:send_connack_error/3 line 62   `
after that the model stops working

**Comment by mworrell** [comment]
Fixed in https://github.com/zotonic/mqtt_sessions/commit/4128d789935254d7eea0dc38a7807f28ab059b6e
