### ISSUE TITLE
Make media width/height attribute opt-in not opt-out

### ISSUE THREAD

**Issue by rl-king** [zotonic/zotonic#2527]
The feature implemented in [this](https://github.com/zotonic/zotonic/pull/2318/files) pull request has some undesirable consequences, images get stretched if you don't apply the right css corrections to the default width and height attributes. We're observing this issue in multiple sites.

A `yeswh` instead of `nowh` would fix this issue.

**Comment by mworrell** [comment]
After discussion with @rl-king and others we have decided to add an option to disable the width/height generation.

This option is a global Zotonic option and only available for 0.x versions.

The option will be called `media_tag_nowh`, must have a boolean (`true` or `false`) value and must be defined in the `zotonic.config` file.
