### ISSUE TITLE
TLS issue

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#2528]
Hi,
I'm currently having an issue while trying to start Zotonic.
I get those errors : 

2020-09-30 16:44:54.408 [error] <0.18929.0> SSL: hello: tls_handshake.erl:191:Fatal error: protocol version
2020-09-30 16:45:04.945 [error] <0.18955.0> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers
2020-09-30 16:45:19.583 [error] <0.18980.0> SSL: hello: tls_handshake.erl:178:Fatal error: insufficient security - no_suitable_ciphers

Looks like it is a ciphers suite issue, but I do not understand why suddently if fails.
My hosting service did a maintenance and since, cannot start. 
I do not know if this could be related to an openssl matter  .

Any clue ?

**Comment by mmzeeman** [comment]
I assume you are running zotonic 0.x. In this case mochiweb tries to collect all available ciphers from openssl. You could try upgrading mochiweb and check if that works. This depends on your OTP version and indeed your OpenSSL version. 

If this does not work, you can try a mochiweb branch which I made in juli to beef up the security. https://github.com/zotonic/mochiweb/pull/12. (I run that one in production)

**Comment by mmzeeman** [comment]
FYI..   busy bringing that mochiweb branch into `0.x`

**Comment by crownedgrouse** [comment]
Hum... It was an Erlang version issue while using kerl. My 1.x version was tried to be started with a erlang version 19...
Took me some time to find the issue. 
Now running on 22.3.
