### ISSUE TITLE
lib scomp does not always add a code for client side caching

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2530]
When I use the full path in zotonic 1.0

`{% lib "lib/css/site.css" %}` zotonic generates the filename `"/lib-min/css/site~0.css"`, but when I use the shorter version `{% lib "css/site.css" %}` it produces  `"/lib-min/css/site~150997032.css"`

It looks like the code looks in the wrong place when the full path is used.

**Comment by mworrell** [comment]
The `~0` is added if the file could not be found.

**Comment by mmzeeman** [comment]
Exactly... but shouldn't both "lib/css/site.css" and "css/site.css" in the lib tag find the same css file on disk?
