### ISSUE TITLE
Travis-ci.org is closing down

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2539]
At the moment builds are queued a very long time. After a bit of searching I discovered Travis-CI is closing down their `travis-ci.org` domain. This is what is causing the long waits. (See: https://travis-ci.community/t/builds-hang-in-queued-state/10250/5)

We can do a couple of things.

1. Move zotonic builds to travis-ci.com, which is still free for open-source projects.
2. Or move to Github Actions.
3. Other ideas?

What shall we do? @mworrell @arjan @ddeboer?

Some articles about moving to GH Actions:

[Mark Phelps: Migrating From Travis to Github Actions](https://markphelps.me/2019/09/migrating-from-travis-to-github-actions/)
[Migrate From Travis CI To Github Actions](https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions)
[From TravisCI to GitHub Actions](https://technology.customink.com/blog/2019/09/02/from-travis-ci-to-github-actions/)

Affected repositories (checked are now moved to GH Actions):

 - [x] zotonic master
 - [ ] zotonic 0.x
 - [x] template_compiler
 - [x] dispatch_compiler
 - [x] cowmachine
 - [x] z_stdlib
 - [x] jsxrecord
 - [x] depcache
 - [x] mqtt_sessions
 - [x] mqtt_packet_map
 - [x] diffy
 - [x] router
 - [x] eiconv
 - [ ] letsencrypt_erlang (this is a fork, so maybe wait for upstream)
 - [x] erlangpack/sidejob
 - [x] erlangpack/mimetypes
 - [x] erlangpack/bcrypt

**Comment by ddeboer** [comment]
I use GitHub Actions and am quite happy with it. There are two main advantages:

- well-integrated into GH (unsurprisingly), so fewer moving parts
- reusable third-party actions keep CI manageable.

**Comment by mworrell** [comment]
I am also for moving to GH actions.

That gives us some experience and we can also use it on private repos.

**Comment by arjan** [comment]
:+1:  for GH actions as well, although I don't have any experience with it yet.

**Comment by mmzeeman** [comment]
So it is probably a good idea to start using GH Actions with one of the smaller zotonic repositories before setting it up for zotonic itself.

**Comment by mworrell** [comment]
Yes, maybe `template_compiler`?

That one has some real test coverage that needs to run.

**Comment by mworrell** [comment]
Moving quite some repos over to GH Action, based on the action file by @mmzeeman

**Comment by mworrell** [comment]
Almost done, except for a database connect error.

https://github.com/zotonic/zotonic/runs/1619165958?check_suite_focus=true#step:6:17

@ddeboer do you have any idea what the reason for the `econnrefused` could be?

**Comment by mworrell** [comment]
@ddeboer fixed it, unlike the documentation which states 'localhost' the psql container is at 'postgres'.

**Comment by mworrell** [comment]
What shall we do with the 0.x branch?
Only add a compile action?

**Comment by mworrell** [comment]
We need to decide what to do with the 0.x branch and builds there.
I think we have two options:

 1. Don't do any GH actions for 0.x
 2. Only a minimal compilation check

Full tests need quite a bit of maintenance which we should use for the master.

**Comment by mworrell** [comment]
0.x is now also building on GH actions.
