### ISSUE TITLE
badmap error when submitting a survey on master

### ISSUE THREAD

**Issue by udanieli** [zotonic/zotonic#2589]
I think I found a bug in the `zotonic_mod_survey`. When submitting a poll I get a `badmap` error:
```
10:50:06.467 [error] Error in process <0.25213.0> on node zotonic@bsdi516v with exit value:
{{badmap,[{block,<<"yesno1">>},{answer,<<"yes">>}]},[{maps,get,[<<"block">>,[{block,<<"yesno1">>},{answer,<<"yes">>}],undefined],[{file,"maps.erl"},{line,207}]},{survey_test_results,count_points,5,[{file,"/zroot/progetti/erlang/zotonic.git/_build/default/lib/zotonic_mod_survey/src/support/survey_test_results.erl"},{line,44}]},{m_survey,insert_survey_submission_1,5,[{file,"/zroot/progetti/erlang/zotonic.git/_build/default/lib/zotonic_mod_survey/src/models/m_survey.erl"},{line,358}]},{mod_survey,do_submit,4,[{file,"/zroot/progetti/erlang/zotonic.git/apps/zotonic_mod_survey/src/mod_survey.erl"},{line,563}]},{mod_survey,render_next_page,7,[{file,"/zroot/progetti/erlang/zotonic.git/apps/zotonic_mod_survey/src/mod_survey.erl"},{line,307}]},{mod_survey,event,2,[{file,"/zroot/progetti/erlang/zotonic.git/apps/zotonic_mod_survey/src/mod_survey.erl"},{line,80}]},{z_transport,incoming_postback_event,6,[{file,"/zroot/progetti/erlang/zotonic.git/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,127}]},{z_transport,transport,3,[{file,"/zroot/progetti/erlang/zotonic.git/apps/zotonic_mod_wires/src/support/z_transport.erl"},{line,63}]}]}
```
Steps to reproduce the problem:

- Enable `mod_survey`
- Create a test poll page with a single yes/no question
- View and submit the poll

Zotonic version: Master, d26ea6298
Operating system: FreeBSD 12.2-RELEASE-p3 GENERIC  amd64
Erlang release: Erlang/OTP 21 [erts-10.3.5.14]  (binary FreeBSD package `erlang-21.3.8.18_1,4`)

I see that somewhere you use maps and somewhere proplists, so I've made a little change in [survey_test_results.erl](apps/zotonic_mod_survey/src/support/survey_test_results.erl) (4edbf4f) and the error disappeared.

**Comment by mworrell** [comment]
Thanks! We indeed changed proplists to maps. Guess some of that is only partially done, even with Dialyzer being happy.

**Comment by mworrell** [comment]
Btw, did you ask for an Italian translation on crowdin? I did see an email about that, but seem to have misplaced it. At least can't find it now. I have added a machine translation of all strings in Italian to Crowdin.

**Comment by udanieli** [comment]
> Btw, did you ask for an Italian translation on crowdin? [...]
Yes I did, I can see the Italian section you added on crowdin. I will review and fix the translations soon.
About this issue, do you want me to open a PR? Should I do something else before opening it?

**Comment by mworrell** [comment]
@udanieli Thanks! I made some small additional changes and merged them into master.

**Comment by udanieli** [comment]
Many thanks to you and all the contributors that share their knowledge with the community

**Comment by udanieli** [comment]
Sorry for reopening this, but editable surveys has badmap error too when changing the answer.
- First time you fill a survey, the answer is written with a `z_db:insert()` [here](https://github.com/zotonic/zotonic/blob/81ee8d253299977d7eca2225f426060305c31595/apps/zotonic_mod_survey/src/models/m_survey.erl#L362) which inserts a map;
- When you try to change you answer, things are saved by a manual update with `z_db:q()` [here](https://github.com/zotonic/zotonic/blob/81ee8d253299977d7eca2225f426060305c31595/apps/zotonic_mod_survey/src/models/m_survey.erl#L249), which inserts a proplist and then you get the `badmap` error when the page tries to update itself.

Changing from the manual update to `z_db:update()` seems to do things correctly, quickfix [here](https://github.com/udanieli/zotonic/commit/d17225cab5fe6ddb4d5962f6d23b66992494f192) (hope I did it correctly).

**Comment by mworrell** [comment]
Good find - maps and prop lists beating each other again....

**Comment by mworrell** [comment]
Indeed, we should just migrate to using the maps of z_db:insert in the survey_answers table.
