### ISSUE TITLE
Compile error OTP 23.2.5 on http_uri in tls_certificate_check.erl

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#2608]
When compiling on OTP 23.2.5 i get this error:

```
===> Compiling _build/default/lib/tls_certificate_check/src/tls_certificate_check.erl failed
_build/default/lib/tls_certificate_check/src/tls_certificate_check.erl:99: http_uri:parse/1 is deprecated and will be removed in OTP 25; use use uri_string functions instead
make: *** [compile] Error 1
```

**Comment by mworrell** [comment]
@DorienD can you check if the branch `2608-compile-error` does compile on your machine?

**Comment by DorienD** [comment]
```===> Compiling tls_certificate_check
===> Compiling _build/default/lib/tls_certificate_check/src/tls_certificate_check.erl failed
_build/default/lib/tls_certificate_check/src/tls_certificate_check.erl:99: http_uri:parse/1 is deprecated and will be removed in OTP 25; use use uri_string functions instead
```
Same error on that branch, but i see you haven't changed the `http_uri` to `uri_string`?

**Comment by mworrell** [comment]
I updated the dependencies (which contain this call) to the newest versions.

Also added 23.2.5 to the build targets for CI. It passes CI now. Maybe you have an even newer version?

**Comment by mworrell** [comment]
Your `erts-11.1.8` is indeed 23.2.5

Can you delete your `_build` directory and try again compiling the `2608-compile-error` branch?

**Comment by mworrell** [comment]
On CI in 23.2.5 it compiles well:

https://github.com/zotonic/zotonic/pull/2609/checks?check_run_id=1980636748#step:5:305

**Comment by mworrell** [comment]
I am going to merge the changes, and then we can have a look at your install, as it doesn't seem to be an inherent issue with the OTP version and the libraries.
