### ISSUE TITLE
address widget always visible + wrong address feature checkbox in category page

### ISSUE THREAD

**Issue by udanieli** [zotonic/zotonic#2613]
Address widget is always visible on an edit page, even if its category has the  `Show address on edit page` flag disabled.

Steps to reproduce the problem:

- Create a page in any category which has not the `Show address on edit page` flag enabled (e.g. `Text`).

Zotonic version: current master.

First of all, in the category page you will see a wrong value for the `Show address on edit page` checkbox, because of this default value which makes the flag always checked:

https://github.com/zotonic/zotonic/blob/041419f2042a178cef4001f05003aad9a3d1cf71/apps/zotonic_mod_admin/priv/templates/_admin_features.category.tpl#L6

Moreover, here is another default value which makes the widget always visible:
https://github.com/zotonic/zotonic/blob/041419f2042a178cef4001f05003aad9a3d1cf71/apps/zotonic_mod_admin/priv/templates/_admin_edit_main_parts.tpl#L7

Removing the `` |if_undefined:`true` `` filter seems to fix this issue.

**Comment by mworrell** [comment]
Thanks for the PR!

I will have a fresh look at this to see if we should rename these to `is_feature_` ... so that a boolean value is always saved.
