### ISSUE TITLE
Occasional psql_connection crash during rollback

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#262]
Sometimes I get a strange psql_connection crash during a rollback:

Looks like some function is missing. 

Crashing process                                                               
   initial_call                         {pgsql_connection,init,['Argument__1']}
   pid                                                            <6741.7350.0>
   registered_name                                                           []
   error_info
         {exit,
            {undef,
                [{pgsql_connection,parsing,
                     [{squery,"ROLLBACK"},
                      {<6741.7349.0>,#Ref<6741.0.0.34360>},
                      {state,undefined,<6741.7351.0>,#Port<6741.10568>,
                          [{<<"client_encoding">>,<<"UTF8">>},
                           {<<"DateStyle">>,<<"ISO, MDY">>},
                           {<<"integer_datetimes">>,<<"on">>},
                           {<<"IntervalStyle">>,<<"postgres">>},
                           {<<"is_superuser">>,<<"off">>},
                           {<<"server_encoding">>,<<"UTF8">>},
                           {<<"server_version">>,<<"8.4.4">>},
                           {<<"session_authorization">>,<<"xxxxxxxxx">>},
                           {<<"standard_conforming_strings">>,<<"off">>},
                           {<<"TimeZone">>,<<"UTC">>}],
                          true,"channel",undefined,
                          {<6741.7349.0>,#Ref<6741.0.0.34289>},
                          {11500,515446170},
                          {statement,[],undefined,undefined},
                          73}]},
                 {gen_fsm,handle_msg,7},
                 {proc_lib,init_p_do_apply,3}]},
            [{gen_fsm,terminate,7},{proc_lib,init_p_do_apply,3}]}
   ancestors
         [channelwww,<6741.133.0>,<6741.130.0>,z_sites_manager,zotonic_sup,
         <6741.73.0>]
   messages
         [{'$gen_event',{49,<<>>}},
         {'$gen_event',{116,<<0,1,0,0,0,25>>}},
         {'$gen_event',{84,
                        <<0,1,99,111,117,110,116,0,0,0,0,0,0,0,0,0,0,20,0,
                          8,255,255,255,255,0,0>>}}]
   links                                           [<6741.135.0>,<6741.7351.0>]
   dictionary                                                                []
   trap_exit                                                               true
   status                                                               running
   heap_size                                                               2584
   stack_size                                                                24
   reductions                                                             12524

**Comment by mworrell** [comment]
We are now using epgsql deps, closing this issue.
