### ISSUE TITLE
Some assets not found

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#2633]
Hi,
I updated my zotonic install  to master pre-transport-2987-g4bdac68 and got below warning : 

zotonic@crownedgrouse)1> 15:46:58.672 [warning] lib file not found: font-awesome-4/css/font-awesome.min.css

And many assets (images) are not found by navigator. I try to flush, no way.

Any idea ?
I got also warning that modules dependancies was missing while written in the zotonic_site.config file. I needed to activate them in shell ...

Any idea to fix ?

**Comment by mworrell** [comment]
That should be part of `mod_artwork`, is it enabled?

The modules in the config file are only enabled when installing the site. This to prevent the situation where you can't disable a module in production without changing the config file (and restarting the site).

**Comment by mworrell** [comment]
On what commit sits the `pre-transport-2987-g4bdac68` ?  It sounds quite old.

**Comment by crownedgrouse** [comment]
I clone a new git as "git clone https://github.com/zotonic/zotonic"
linked my site code in app_user/sites/
Compiled with OTP-22.2 .
Still having : 

```
(zotonic@crownedgrouse)1> z_module_manager:activate(mod_artwork, z:c(crownedgrouse)).
09:40:07.949 [info] [crownedgrouse] info @ z_module_manager:299  Module mod_artwork activated by undefined ()
ok
(zotonic@crownedgrouse)2> 09:46:43.478 [warning] lib file not found: font-awesome-4/css/font-awesome.min.css
```
I can see some few more pictures, but javascript image flip does not work.

In browser's web console I got below error : 
"Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js”"

I got below warning too on all cookies (only one sample below): 
Cookie “z_ua” will be soon treated as cross-site cookie against “...(my site)...” because the scheme does not match.

**Comment by crownedgrouse** [comment]
hum, ok .
I fixed the javascript issue. Firefox was blocking as a security exception  (the new self signed certificate was not trustable ).

Look is better, but still missing some pictures, and still same issue on font-awesome.

**Comment by crownedgrouse** [comment]
I removed browser's cache and cookies, and now all pictures are missing.
web console says : 

```
Loading mixed (insecure) active content “http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js” on a secure page
contact
Loading failed for the <script> with source “https://www.x:8443/lib/js/cufon~cufon-config~font~2979797190.js”. contact:18:1
Loading failed for the <script> with source “https://www.x.com:8443/lib/js/apps/jquery-latest.min~jquery-ui-latest.min~/js/modules/jquery.ui.touch-punch.min~2920224894.js”. contact:104:1
Loading failed for the <script> with source “https://www.x:8443/lib/js/modules/jstz.min~/cotonic/zotonic-wired-bundle~/js/apps/zotonic-wired~z.widgetmanager~/js/modules/z.notice~z.imageviewer~z.dialog~z.clickable~livevalidation-1.3~jquery.loadmask~/bootstrap/js/bootstrap.min~/js/modules/responsive~246899197.js”. contact:107:1
Uncaught ReferenceError: cotonic is not defined
    <anonymous> https://www.x:8443/fr/page/325/contact:118
contact:118:1
    <anonyme> https://www.x:8443/fr/page/325/contact:118
Uncaught TypeError: $.widgetManager is not a function
    <anonymous> https://www.x:8443/fr/page/325/contact:114
    jQuery 4
contact:114:8
```
I do not understand if the issue comes from server or client for obscure secutity reasons ?

**Comment by mworrell** [comment]
HTTP and https don't mix well. What you can do is check with curl (and the -k flag) if the files are really not there or if it is just the browser complaining about hosts and protocols.

The cookies in Zotonic are now secure and bound to the domain. So if you are mixing domains, then that can also explain quite a bit.

The z_ua cookie is not used anymore, we removed the user-agent sniffing in favor of generic sites for all devices.

**Comment by crownedgrouse** [comment]
```
$> curl -k  https://www.x.com:8443/image/2016/5/15/brainstorming_1_tiny.png%28200x126%29%28crop%29%28B53505A02B8C7C0F96F317BED491C76A%29.jpg
curl: (56) OpenSSL SSL_read: error:1408F0C6:SSL routines:ssl3_get_record:packet length too long, errno 0
```
this error is generally when talking SSL to a non SSL endpoint.
I dig further.

**Comment by crownedgrouse** [comment]
I tried to stop ssl use in config :
 ```
 # grep -r ssl *  | grep -v '%'
 1/zotonic.config:    {ssl_listen_port, none},
1/zotonic.config:   {ssl_port, none},
1/zotonic.config:   {ssl_only, false},
zotonic.config:    {ssl_listen_port, none},
zotonic.config:    {ssl_port, none},
zotonic.config:    {ssl_only, false},

```
I do not have any https/ssl mention in nginx config  but it is *still redirecting*  to https://www.x.com   while asking for http://www.x.com .
I do not see any ssl port listening with netstat ...
Why it is redirecting ?

**Comment by crownedgrouse** [comment]
Uh `none` is used as a port number ...
```
$ wget http://www.x.com
--2021-03-20 14:08:15--  http://www.x.com/
Résolution de www.x.com (www.x.com)… 95.142.167.140
Connexion à www.x.com (www.x.com)|95.142.167.140|:80… connecté.
requête HTTP transmise, en attente de la réponse… 301 Moved Permanently
Emplacement : https://www.x.com:none/ [suivant]
https://www.x.com:none/: Mauvais numéro de port.
```

**Comment by mworrell** [comment]
Zotonic always redirects to https, with the ports as configured. Unless the request has 1) proxy forward headers, 2) the proxy says that the original request was https, and 3) the proxy is on a trusted IP address (LAN addresses are trusted by default)

**Comment by crownedgrouse** [comment]
ok so almost impossible to test without SSL. 
Thanks I try to figure out by going further...

**Comment by mworrell** [comment]
Yes, for service workers and secure cookies you need https. And as Google et al now always complain if a site is not https, we made it the default.

Zotonic always installs a self signed certificate. And if you are on a routable address with a real domain name then you can use mod_letsencrypt to obtain a free certificate.

**Comment by crownedgrouse** [comment]
OK site is working in https again ( I followed the documentation but 'none' did not work for me ).

Now  having those errors for any link on site... 

```
17:07:36.060 [warning] lib file not found: font-awesome-4/css/font-awesome.min.css
17:08:16.978 [error] at: "cowmachine:request_1:82", code: 500, dst: #{ip4 => "95.142.167.140",port => 8443}, in: cowmachine, level: error, path: <<"/fr/page/387/wip-diagonal">>, reason: {function_clause,[{z_convert,to_binary,[{trans,[{en,<<"Diagonal">>},{fr,<<"Diagonal">>}]}],[{file,"/srv/data1/zotonic/www/zotonic/_build/default/lib/zotonic_stdlib/src/z_convert.erl"},{line,99}]},{filter_match,match,3,[{file,"/srv/data1/zotonic/www/zotonic/apps/zotonic_mod_base/src/filters/filter_match.erl"},{line,29}]},{tpl_b6593d68df5e981a4c9e60c41c2c66c21aee58b0,render,3,[{file,"/srv/data1/zotonic/www/zotonic/_build/default/lib/crownedgrouse/priv/templates/default.tpl"},{line,51}]},{template_compiler,render,4,[{file,"/srv/data1/zotonic/www/zotonic/_build/default/lib/template_compiler/src/template_compiler.erl"},{line,107}]},{z_template,render_block,4,[{file,"/srv/data1/zotonic/www/zotonic/apps/zotonic_core/src/support/z_template.erl"},{line,98}]},{controller_page,...},...]}, src: #{ip4 => "82.121.251.45",port => 54838}, text: "Stop request"
```
Is there something changed on translation handling ?

**Comment by mworrell** [comment]
Looks like something in the match filter, getting a trans record. I think we need to change that filter to allow it receiving a trans record as input.

Might be something that was already changed in 0.x and we missed when merging all changes into master. Will check.

**Comment by mworrell** [comment]
I have added support for allowing `#trans{}` records for the subject in the match filter.

**Comment by crownedgrouse** [comment]
Thansk, work again !
I found the font-awesome issue : 
```
./www/zotonic/apps/zotonic_mod_artwork/priv/lib/font-awesome/css/font-awesome.min.css
./www/zotonic/apps/zotonic_mod_artwork/priv/lib-src/font-awesome-4/css/font-awesome.min.css
```
In my templates I was referring to `lib/font-awesome-4/css/font-awesome.min.css`   . See the missing "-4" between lib-src and lib ...
Is it intentional ?

**Comment by mworrell** [comment]
I am not sure about the '-4', could be that we didn't want to have the version in the URL anymore, as 5 is a superset of 4.
