### ISSUE TITLE
Missing clause in z_dispatcher.erl

### ISSUE THREAD

**Issue by crownedgrouse** [zotonic/zotonic#2634]
https://github.com/zotonic/zotonic/blob/4bdac684c870eb6d684c069c8a8407058c7bc0bb/apps/zotonic_core/src/support/z_dispatcher.erl#L301

My site crash due to this function. By adding a fallback clause, and a trace, I see my hostname coming character by character in this fallback.

looks like a string is not provided but a list content, character by character instead.

By adding a fallback, site is starting but is it safe ?

**Comment by mworrell** [comment]
It might be that the `hostalias` in your config is a single string, and not a list of strings.

**Comment by crownedgrouse** [comment]
ah, indeed true.
Strangely start was not failing with older code.
Anyway the crash trace was not very helpful to find the issue. 
Is there somewhere in code where quality of config could be checked ?

**Comment by mworrell** [comment]
Yes, we should add a preflight check on the contents of the configuration. At least for these known and critical ones.

That also gives better error messages.

We have also an open issue where we are removing lager in favor of more semantic logger errors. That could also help in determining error causes and more readable errors.

**Comment by crownedgrouse** [comment]
Thanks Marc.
I let decide to open a todo on config checking.
Closing.
