### ISSUE TITLE
'bin/zotonic stop' not always stops the beam.smp

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2668]
There are instances where after `bin/zotonic stop` the `beam.smp` keeps running on quite high CPU.

If this happens then it can only stopped by a brute kill of the beam and heart processes.

**Comment by alvaropag** [comment]
This happens to me quite frequently on the latest 0.x released, after some minutes it does kill beam.smp. I can help test it if needed.

**Comment by mworrell** [comment]
I saw it only on master. Let's investigate first what is happening.

**Comment by mworrell** [comment]
First local tests show the beam.smp jumping to high CPU and after some moments stopping.

That high CPU is suspicious.... testing further.

**Comment by alvaropag** [comment]
How are you inspecting the VM? are you using a specific command or log output?

**Comment by mworrell** [comment]
Just poking and trying - it is not doing much I/O, so it is internal bookkeeping bij `init:stop()`.

I suspect that `init:stop()` does more than what we need. We can just kill stop some of our own apps and kill open ports.
After gracefully stopping our essential processes we can use `erlang:halt()` to stop the VM.

**Comment by alvaropag** [comment]
Are you going to backport it to 0.x?

**Comment by mworrell** [comment]
Didn't plan it - but might do.
Is it needed?

**Comment by alvaropag** [comment]
It's happening on 0.x but it's not an impeditive to use Zotonic....
