### ISSUE TITLE
0.x Build fails with OTP23 due to erl_interface

### ISSUE THREAD

**Issue by FBSD4** [zotonic/zotonic#2675]
Hi, 

does the stable branch support OTP23? Trying to build 0.60.0 release fails with the following error:

Compiling c_src/eiconv_nif.c
ld: error: unable to find library -lerl_interface
cc: error: linker command failed with exit code 1 (use -v to see invocation)
ERROR: sh(cc c_src/eiconv_nif.o  -liconv -L/usr/local/lib -shared  -L"/usr/local/lib/erlang23/lib/erl_interface-4.0.2/lib" -lerl_interface -lei -o priv/eiconv_nif.so)
failed with return code 1 and the following output:
ld: error: unable to find library -lerl_interface
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Thank you guys in advance :)

**Comment by mworrell** [comment]
Hi,

Yes, there was a breaking change in OTP 23.
For NIFs it is either >= 22.3 or =< 22.3.
The same problem applies to the bcrypt NIF.

There are two reasons we didn't move 0.x to OTP >= 23:

1. We have 0.x customers on OTP < 22.3 we need to keep compatibility.
2. We concentrate our development effort now on the master

For new projects we encourage you to use the master branch.
Though untagged it is stable and used in production for important sites.

Hope this is not too inconvenient for you.

**Comment by FBSD4** [comment]
Hi Marc,

those are valid points. 

Unfortunately our project is not new and quite big, so the transition to the master branch won't be an easy task, considering the incompatibilities between the two branches. But, I guess sooner or later we will need to take this path, even more so now that OTP24 brings all these goodies to the table.

Thank you guys for this amazing project :)

**Comment by mworrell** [comment]
Thanks!

Closing this for now.
