### ISSUE TITLE
m_rsc:940 Failed to get page url path. Is the 'page' dispatch rule missing?

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#2713]
after release update. How to fix ?

**Comment by mworrell** [comment]
You are probably using `zotonic_mod_base_site`.

You can now install this module by doing a `git clone` inside the apps_user directory:

```shell
cd apps_user
git clone https://github.com/zotonic/zotonic_mod_base_site.git
cd ..
make
```

Then it should be available again.

**Comment by mworrell** [comment]
I assume the problem is resolved now?
