### ISSUE TITLE
Articles changed to Collections do not show Contains relationship until system cache is flushed

### ISSUE THREAD

**Issue by vincentjacobs** [zotonic/zotonic#2791]
When changing an article to a collection, the admin interface fails to show the now-relevant _Contains_ relationship. This confuses the user. Flushing system caches is a workaround.

Steps to reproduce:

1. Create new Article
2. Change Article to Collection
3. Observe: no _Contains_ relationship is shown
4. Flush system caches
5. Observe: _Contains_ relationship is now shown

**Comment by mworrell** [comment]
Is this on 0.x or 1.0?

**Comment by vincentjacobs** [comment]
Observed it on 0.x. Unable to test on 1.0.

**Comment by mworrell** [comment]
Confirmed on master branch.

**Comment by mworrell** [comment]
Fixed in master and 0.x

Will be part of 0.64
