### ISSUE TITLE
iconv_drv will fail on R15B

### ISSUE THREAD

**Issue by helllamer** [zotonic/zotonic#284]
erl_driver API changed: http://groups.google.com/group/erlang-programming/browse_thread/thread/9bcd23ed628ef5e6

Possible iconv fixes here: https://github.com/mihawk/erlang-iconv but gcc fails due to useless/wrong function declaration at iconv_drv.c:89

**Comment by mworrell** [comment]
Closing, gen_smtp dependency has been removed, clearing the way to use any icons library with the correct API
