### ISSUE TITLE
Memory usage - default number of processes / atoms

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#2848]
Currently we have these defaults:

 * Processes: 10M
 * Ports: 100K
 * Atoms: 1M

I think the process and atom limits are a bit high.
We could put them lower and use less memory.

What would be good defaults?

In general we should check if there are processes holding memory when they don't need to.

/cc @mmzeeman @arjan @CyBeRoni

**Comment by mmzeeman** [comment]
```erlang
channelme@hall3)10> erlang:system_info(port_count).
19694
(channelme@hall3)11> erlang:system_info(atom_count).
86141
(channelme@hall3)12> erlang:system_info(process_count).
84116
```
