### ISSUE TITLE
Level of ?DEBUG() macro logs is notice instead of debug.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2863]
When you place debug messages in your code during developement, messages they are logged with the new logging framework. The level of messages generated by the `?DEBUG` macro is `notice`. I think this should become `debug`

See: https://www.erlang.org/doc/man/logger.html#type-level

Generated log entry.

```
2022-02-04 10:46:36 NOTICE  site=site_cafe  user_id=336 <0.6208.0> [mod_invitation:observe_rsc_update/3:47] ▸ text="DEBUG: {#{<<\"c
```

**Comment by mworrell** [comment]
It used to be an info message.

As the default logger level is notice, I changed it to notice.

Idea is that you can just add `?DEBUG` without changing the debug level of the logger.

**Comment by mworrell** [comment]
I propose to keep it at notice, as the `?DEBUG` is more meant for development and experimental code.
