### ISSUE TITLE
Documentation of rsc_update notifications needs clarification

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2864]
The documentation tells the `IsModified` part in the accumulator of the notification should be a bool, but when I check what it actually is in practice I see that I get the tuple `{ok, Props}` is passed around. What should it be?

https://github.com/zotonic/zotonic/blob/master/doc/ref/notifications/notification/rsc_update.rst

**Comment by mworrell** [comment]
It should be `{ok, Props}`.

The documentation was not up to date.

The meta file is also not up to date. Have to check that.
