### ISSUE TITLE
The unique name attribute of resources is missing from its admin form.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#2865]
![Screenshot from 2022-02-04 11-19-34](https://user-images.githubusercontent.com/1024972/152512431-a48f5d6f-6c90-4ce0-83e3-39297f7d849b.png)

**Comment by mworrell** [comment]
The unique name is only visible if you have `m.acl.use.mod_admin_config` permission.

**Comment by mworrell** [comment]
This might be a bit too restrictive, as in the update code we have:

```erlang
    case z_acl:is_allowed(use, mod_admin, Context) of
```

**Comment by mworrell** [comment]
Changed it to `m.acl.use.mod_admin` in the template.

**Comment by mmzeeman** [comment]
It looked like a bug to me. It was completely confusing. Maybe it should be visible but not editable?

**Comment by mworrell** [comment]
At least admin users can now see and edit it.
