### ISSUE TITLE
Conflicting erlexec dependency on zotonic_filehandler

### ISSUE THREAD

**Issue by robvandenbogaard** [zotonic/zotonic#2915]
Zotonic_filehandler requires erlexec 1.9.3, whereas filewatcher requires 1.18.11 - should the filehandler dependency be updated to this version? Found this while trying to add zotonic_apps as a mix dep to a Nerves project - not sure how far it can be taken :)

https://github.com/zotonic/zotonic/blob/2e392805da562791324e1d43351e31f271d43535/apps/zotonic_filehandler/rebar.config#L13

**Comment by mworrell** [comment]
The newest is the best.
