### ISSUE TITLE
Issue with id in controller_template

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#2958]
Hi!

The [controller_template:process/4](https://github.com/zotonic/zotonic/blob/cc382f408517309034a28a59bf242aea827d2af6/apps/zotonic_mod_base/src/controllers/controller_template.erl#L60) always checks for a rsc_id. My question is, why?
Shouldn't this be only valid for controllers like [controller_id](https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_base/src/controllers/controller_id.erl) or [controller_page](https://github.com/zotonic/zotonic/blob/master/apps/zotonic_mod_base/src/controllers/controller_page.erl)?
I'm using custom database tables and I don't wanna check for the id in rsc table in the controller template.
I created a custom controller as a workaround, but I think the controller_template does not need to check for an id.

**Comment by alvaropag** [comment]
Yep, we are facing these issues with ids from our custom table being checked against rsc.id and ACLs that are not related. Would remove the rsc id check on controller_template break existing code?

**Comment by mworrell** [comment]
I think it is used to be able to pass an _optional_ id in the controller options.

I don't think it should do anything with an id in the path or query args.
We could check it a bit more and then change it to only check for an `id` in the controller options.

Would that help with the problems you are encountering?
