### ISSUE TITLE
Mod signup sudo issues

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#2964]
Hi!

I added in `zotonic_site.config` the `mod_signup` and `mod_server_storage`, but accessing the signup page and submitting the form, the page stuck, and I receive this error in the console:

```shell
{{nocatch,{error,eacces}},
 [{mod_signup,ensure_identity,3,
              [{file,"/home/williamthome/Projects/z_umbrella/apps/zotonic_mod_signup/src/mod_signup.erl"},
               {line,260}]},
```

Changing the context to sudo in `mod_signup:ensure_identity/3`, the error is gone, and the signup is done.
```diff
ensure_identity(Id, {username_pw, {Username, Password}, true, true}, Context) ->
-    case m_identity:set_username_pw(Id, Username, Password, Context) of
+    case m_identity:set_username_pw(Id, Username, Password, z_acl:sudo(Context)) of
        ok -> ok;
        Error -> throw(Error)
    end;
```

Makes sense to change the context to sudo in this case? Or what I've missed in the signup?

**Comment by mworrell** [comment]
In your access control, is the user allowed to update itself?

We perform the following check to see if the user is allowed to set an username/password:

```erlang
%% @doc Check if the user is allowed to change the username of a resource.
-spec is_allowed_set_username( m_rsc:resource_id(), z:context() ) -> boolean().
is_allowed_set_username(Id, Context) when is_integer(Id) ->
    z_acl:is_admin(Context)
    orelse z_acl:is_allowed(use, mod_admin_identity, Context)
    orelse (z_acl:is_allowed(update, Id, Context) andalso Id =:= z_acl:user(Context)).
```

I guess the user does not have `update` permission on their own person resource.

Is this on purpose in your ACL?

**Comment by williamthome** [comment]
I've just created a new site and enabled the `mod_signup`. These are the Zotonic ACL defaults:
![image](https://user-images.githubusercontent.com/35941533/168076035-797536ad-5fcc-49e9-858f-5b16d109ebdb.png)

Now I resolved the issue so in `mod_signup:do_signup/5`:
```diff
%% @doc Insert or update a new user, return the user id on success. Assume all args are ok as we did
%% a preflight check and users sign up slowly (ie. no race condition)
do_signup(UserId, Props, SignupProps, RequestConfirm, Context) ->
    IsVerified = not RequestConfirm orelse has_verified_identity(SignupProps),
+    RscProps = props_to_rsc(Props, IsVerified, Context),
-    case insert_or_update(UserId, props_to_rsc(Props, IsVerified, Context), Context) of
+    case insert_or_update(UserId, RscProps, Context) of
        {ok, NewUserId} ->
-            ContextUser = z_acl:logon(NewUserId, Context),
+            ContextUser =
+                case maps:find(<<"creator_id">>, RscProps) of
+                    {ok, self} -> z_acl:sudo(Context);
+                    _ -> z_acl:logon(NewUserId, Context)
+                end,
            ensure_identities(NewUserId, SignupProps, ContextUser),
            z_notifier:map(#signup_done{id=NewUserId, is_verified=IsVerified, props=Props, signup_props=SignupProps}, ContextUser),
            case IsVerified of
                true -> z_notifier:map(#signup_confirm{id=NewUserId}, ContextUser);
                false -> nop
            end,
            maybe_add_depiction(NewUserId, Props, ContextUser),
            {ok, NewUserId};
        {error, Reason} ->
            {error, Reason}
    end.
```

Perhaps this makes sense? Or should I change something in Admin ACLs?

**Comment by mmzeeman** [comment]
I think both 1) and 2) should be done. It is logical to have a default rule "edit own stuff", but I also think the call `do_signup` should just work the module is allowed to do its own checks. (Although it now becomes  hard coded ACL routine. We currently just don't have `signup_allowed` acl checks where you can configure things)

**Comment by mworrell** [comment]
I have changed the pull request to do both:

 * Add ACL rule to let users update themselves
 * Add a sudo if user being updated has itself as the creator_id

**Comment by mmzeeman** [comment]
This is one of the reasons why I'm looking at a policy system. Where there is a sudo in the zotonic code, there is a hard-coded acl decision trying to get out.

**Comment by williamthome** [comment]
> Could you have a look at #2965 ?
> 
> It should add, on installation, the acl rule from (2) in the comment above.

Yes, this works!
