### ISSUE TITLE
Logoff via controller_logoff does not notify

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#2978]
The [dispatch](https://github.com/zotonic/zotonic/blob/2361d27ae43ecfd27fc43e4b1e26710373c6edac/apps/zotonic_mod_authentication/priv/dispatch/dispatch#L3) of the `zotonic_mod_authentication` has the `logoff` path using the [`controller_logoff`](https://github.com/zotonic/zotonic/blob/2361d27ae43ecfd27fc43e4b1e26710373c6edac/apps/zotonic_mod_authentication/src/controllers/controller_logoff.erl), but the controller just resets the cookies and does not emit any notification like [`z_auth:logoff/1`](https://github.com/zotonic/zotonic/blob/2361d27ae43ecfd27fc43e4b1e26710373c6edac/apps/zotonic_core/src/support/z_auth.erl#L140).
The site I created uses the Zotonic defaults and the `mod_signup` and `mod_server_storage` enabled.
This solved the issue for me:
```diff
% -module(controller_logoff).
% ...
resource_exists(Context) ->
-    {false, z_authentication_tokens:reset_cookies(Context)}.
+    Context1 = z_authentication_tokens:reset_cookies(Context),
+    Context2 = z_auth:logoff(Context1),
+    {false, Context2}.
```
Make sense? Or how to get notified?

**Comment by mworrell** [comment]
This is not an ensured method of being notified, but then what is....  I for this change, as it will shorten waiting for a timeout when the user does an explicite log off.

**Comment by mmzeeman** [comment]
Logon and logoff is a bit weird in websites anyway. Good change I think.
