### ISSUE TITLE
Bump Zotonic Docker images and Gthub CI

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#2985]
Zotonic `Dockerfile.dev` uses the `erlang:24-alpine`, but `erlang:25-alpine` was released.
Locally all green running tests in `Erlang 25.0`.

I also think the `Postgres` version could be bumped. The `docker-compose.yml` uses the `postgres:11.6-alpine`, but the latest is `postgres:14.3-alpine`.

`Github workflows` also use earlier versions:
* `dialyzer.yml`: otp_version: [22.3]
* `docs.yml`: otp_version: [23]
* `elvis.yml`: otp_version: [23]
* `publish.yml`: otp_version: [24.0.5]
* `test.yml`: otp_version: [22, 23.2.5, 24.0.5]

The `elvis.yml` run elvis by the `0.2.12`, latest is `1.1.0`.

**Comment by mworrell** [comment]
@mmzeeman is also doing some tests with OTP25

**Comment by mmzeeman** [comment]
Works like a charm, as far as I can see. I'm on an M1, it feels like recompiling templates got a bit of boost in speed. Maybe the speed of the compiler improved because of the jit.

**Comment by mworrell** [comment]
25.0.1 was released, but not yet available in the GH Actions, so we have to wait a bit.

**Comment by mmzeeman** [comment]
Still using 25.0 locally... Everything else seems to work fine... Going to build 25.0.1.

**Comment by williamthome** [comment]
OTP 25.0.1 is now available in [Docker](https://hub.docker.com/_/erlang/) and ready to use with GH Actions.
