### ISSUE TITLE
Page hangs if subscribed to auth-changing topic

### ISSUE THREAD

**Issue by abensoft-williamthome** [zotonic/zotonic#2994]
Hi!

I'm subscribing to the topic `model/auth/event/auth-changing`, but on logon submit the user is not redirected to the logged in page.
My `js` file contains this:
```js
cotonic.ready.then(function () {
    cotonic.broker.subscribe("model/auth/event/auth-changing", function (authChangingEvent) {
        console.log({ authChangingEvent })
    })
})
```
![z_topic_issue](https://user-images.githubusercontent.com/94546997/171167092-3c044719-7d9c-45e4-a7e5-0769dae41c6b.gif)

Without this subscription the redirect occurs as expected.
![z_topic_issue2](https://user-images.githubusercontent.com/94546997/171168262-a673388e-2707-4841-9924-3e63fc65cffe.gif)

Others auth topics are not causing troubbles.

**Comment by vkatsuba** [comment]
Hi. Could you please also share the `network` tab?

**Comment by mworrell** [comment]
Hi, I think this is a problem that @mmzeeman already told me about, where a new subscription on a topic overwrites an existing subscription, due to their similar 'wid'.

In this case the subscription of `cotonic.model.location.js` is overwritten, which disables the page reload.

Looking into it.

**Comment by mworrell** [comment]
I was thinking of this change:

```diff
diff --git a/src/cotonic.broker.js b/src/cotonic.broker.js
index 9273cb4..4aeaf39 100644
--- a/src/cotonic.broker.js
+++ b/src/cotonic.broker.js
@@ -154,7 +154,7 @@ var cotonic = cotonic || {};
 
     function indexOfSubscription( v, thing ) {
         let index = v.indexOf(thing);
-        if (index === -1) {
+        if (index === -1 && thing.wid !== null) {
             for(index = v.length-1; index >= 0; index--) {
                 const sub = v[index];
                 if (thing.type === sub.type && sub.wid === thing.wid) {
@@ -281,7 +281,7 @@ var cotonic = cotonic || {};
      */
     function subscribe(topics, callback, options) {
         options = options || {};
-        if(options.wid === undefined) options.wid = 0;
+        if(options.wid === undefined) options.wid = null;
 
         let subtopics = [];
```

**Comment by mmzeeman** [comment]
@abensoft-williamthome A quick workaround is to set an explicit `wid` in the options of your subscription.

**Comment by mworrell** [comment]
You can run `make update-cotonic` to update cotonic.

**Comment by mmzeeman** [comment]
We have fallen into the same trap (multiple times). Sorry that we let you fall into it too.

**Comment by abensoft-williamthome** [comment]
No problems. Some bugs make us dig into the code, which is a good thing, especially when we are learning.
