### ISSUE TITLE
Single quotes in .tpl

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#2999]
Hi!

Are single quotes in templates considered atoms or strings?
There is, for example in `_block_view_survey_short_answer.tpl`,   `{% if blk.validation == "email" %}` and also in the same template `{% if blk.validation == 'email' %}`. I think all are strings, but I decided to clarify this in favor of the [Zotonic Language Server](https://github.com/williamthome/zotonic-ls) that I'm implementing.

Thanks in advance!

**Comment by mworrell** [comment]
Indeed, `'` and `"` are both string delimiters.

You can define atoms using backticks:

```
`atom`
```

**Comment by williamthome** [comment]
@mworrell thank you!
