### ISSUE TITLE
[email / mod_signup] Sending of signup verification emails breaks when email_override set

### ISSUE THREAD

**Issue by robvandenbogaard** [zotonic/zotonic#3007]
In a recent update (0.65.0 -> 0.66.0) the full user name was added as label to the recipient field (TO:), to reduce spam scores for signup verification emails sent by zotonic. In its current form, if the site/zotonic email_override config is set, the following error is raised:

```
    exception error: no case clause matching {ok,[]}
      in function  z_email:split_name_email/1 (src/smtp/z_email.erl, line 198)
      in call from z_email_server:recipient_email_address/1 (src/smtp/z_email_server.erl, line 190)
```

```
DEBUG: z_email:197  "Test person <test-at-example.com> (override) <override@example.com>"
DEBUG: z_email:198  {error,{0,smtp_rfc822_parse, ["syntax error before: ","\"(override)\""]}}
```

The error occurs because now, with the override, the recipient contains two clauses with <> (or anything beyond the first <..> actually). Putting quotes `\"` around the email-escaped recipient mitigates this (" (override)" can be inside or outside the quote):

```
z_email_server.erl:973:
            "\"" ++ escape_email(z_convert:to_list(EmailAddr)) ++ " (override)\" <" ++ z_convert:to_list(UseOverride) ++ ">"
```

**Comment by mworrell** [comment]
The email address needs to be parsed and then put together with the correct RFC functions.

**Comment by mworrell** [comment]
@robvandenbogaard can you check if #3018 fixes your problem?
