### ISSUE TITLE
Tune CSS of quick search result

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#3011]
- [ ] Bit smaller font

**Comment by michielklonhammer** [comment]
![Image](https://user-images.githubusercontent.com/1306897/173039058-38a46eb0-97ae-4711-ba1b-aa914f187ab0.png)

**Comment by mworrell** [comment]
See #3023 for a first change

**Comment by mworrell** [comment]
![Image](https://user-images.githubusercontent.com/38268/175946752-e1a49853-98c4-41a9-b798-ff3b55365f0c.png)
