### ISSUE TITLE
Get real client IP behind a reverse proxy?

### ISSUE THREAD

**Issue by FBSD4** [zotonic/zotonic#3012]
Hi, 

been using Zotonic Stable behind a nginx reverse proxy. In nginx.conf, I have set the following directives:

```
proxy_set_header     X-Real-IP                 $remote_addr;
proxy_set_header     X-Forwarded-For    $proxy_add_x_forwarded_for;
```

How do I get a client's  real IP on Zotonic's side? Any clues? Nothing that I 've tried so far seems to work.

**Comment by mworrell** [comment]
You mean the 0.x?

You can try to use: `m_req:get(peer, Context)`

Note that the on 0.x the `x-forwarded-for` header is only considered iff the proxy is a non routable address (10, 172, 192.168 or 127.0.0.1)

On 1.x (master) there is an allow list for whitelisting additional proxies.

**Comment by FBSD4** [comment]
Hi Marc,

yes, I mean the 0.x branch. As for your suggestion, I have used m_req:get/2 so far and everything worked as expected, as long Zotonic acted as a standalone web server. After adding nginx as a reverse proxy, putting Zotonic behind it, m_req:get/2 results always to "127.0.0.1".

Is there a way to print all request headers in the console, as the request arrives from nginx to Zotonic? This way I could at least verify that the header is successfully added by nginx.

Thank you.

**Comment by mworrell** [comment]
You can add this to your template:

```django
{% print m.req.headers %}
```

Then you should be able to see all the request headers.
