### ISSUE TITLE
Javascript not executed in overrided logon template

### ISSUE THREAD

**Issue by abensoft-williamthome** [zotonic/zotonic#3017]
## `Zotonic` version
[1.0.0-rc.7](https://github.com/zotonic/zotonic/releases/tag/1.0.0-rc.7)

## `OS` / `Browser` version
Browser

## Steps to reproduce
Enable the signup module adding `mod_signup, mod_server_storage` to modules in `priv/zotonic_site.config`, override the **_logon_login_form_fields.tpl** creating it in the site templates with some javascript, e.g.:
```html
<p><strong>_logon_login_form_fields.tpl</strong> overrided.</p>
<p>No javascript is executed.</p>

<script>
    console.log("script")
</script>

{% javascript %}
    console.log("javascript")
{% endjavascript %}
```

## Current behavior
None of the javascript code is executed.
In dev tools, the `console.log("script")` inside the `<script>` is found, but not executed, and the `console.log("javascript")` inside the `{% javascript %}` is not found and not executed.

## Expected behavior
Javascript be executed.

**Comment by mworrell** [comment]
Hi, that is true.

Currently the authentication flow uses the new Cotonic html element updaters.
Those do not pass any javascript to the client, only the HTML.

This was on purpose, as the Auth-UI web worker handles the updates and the Auth worker handles the state.
Goal here is to make the HTML more declarative, without any Javascript, and this was the first spot where it is being applied.

**Comment by abensoft-williamthome** [comment]
Got it.
I resolved my issue using the `{% lib %}` tag.
Is there another way to accomplish/solve this?

**Comment by mworrell** [comment]
Depends on what you want to do.

In Cotonic there are declarative click handlers that publish to topics etc.

Also the Auth templates are re-rendered if the Auth state changes, those changes are now applied incrementally (think error messages and one-time passcodes). Just re-running all JS code would not work on incrementally updated DOM parts.

**Comment by abensoft-williamthome** [comment]
Generally, we set up components in the page, e.g., applying masks to fields.
Maybe adding a `<script>` tag via `Cotonic` does the trick, but I think it is better to do this in a js file.

**Comment by abensoft-williamthome** [comment]
I am closing this issue as my issue has been resolved.
Thanks @mworrell.
