### ISSUE TITLE
"Other Issues" github template

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#3019]
The `Other Issues` issue template contains this:
```
<!-- Please consider opening a discussion if this is not really an issue -->
```
But discussions are not enabled for this repo.
Should discussions be enabled or the template be changed?

**Comment by williamthome** [comment]
Now I see the [gitter](https://gitter.im/zotonic/zotonic?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) badge in the Zotonic readme. Discussions referes to it?

**Comment by mworrell** [comment]
Maybe we should remove the Gitter references, much prefer the Erlang forum or Slack

**Comment by mworrell** [comment]
Is Discussions now enabled?

I clicked on a button "to get started"

**Comment by williamthome** [comment]
Yes, it's available o/
