### ISSUE TITLE
Make desktop notifications from file updates configurable

### ISSUE THREAD

**Issue by cdfa** [zotonic/zotonic#3056]
## `Zotonic` version
0.67

## `OS` version
5.18.12-zen1-1-zen GNU/Linux

## Description
* **Motivation**
At the moment, when I have `inotify-tools` installed, Zotonic watches the filesystem for updates. Every time a file updates, I get a desktop notification. Personally, I find these notifications quite distracting, especially because I have my editor set to save files automatically.

* **Proposal**
Either remove the desktop notifications (as seems to have happened for 1.0) or make a configuration option to turn them off. I can make a PR for removing them if you like :)

## Current behavior
Many distracting notifications. I think they're coming from here: https://github.com/zotonic/zotonic/blob/2d37fafe336ae62d908fb09984b17a2ef8741d14/src/filewatcher/z_filewatcher_handler.erl#L356

## Expected behavior
Peace and quiet 🌳🧘.

**Comment by mworrell** [comment]
There is no real difference between the master and 0.x with respect to the notifications.

I personally like the feedback after saving. If you want to make it optional then we could add a configuration to suppress the messages. This could be a system wide setting (z_config).

**Comment by cdfa** [comment]
Ah, okay, I couldn't find the code for desktop notifications in 1.0. I usually get my feedback from the language server and the live reloading is something I expect to work anyway, so then de notifications don't really add anything. A config option would be great! :+1:
