### ISSUE TITLE
Proposal: remove the persistent APIs from 0.x 

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#3103]
## `Zotonic` version

0.68

## Description

* **Motivation**

The persistent APIs can be used to set/get persistent data connected with the persistent id cookie.
This opens the server as a possible store of information, as the cookie is just a random id token.

I am not aware of any site that is depending on this persistent API.

The API is not present on 1.x

* **Proposal**

Remove the API on 0.69.0, where we have some additional security updates.

/cc @mmzeeman @arjan @ArthurClemens @vkatsuba @robvandenbogaard @alvaropag @karlsson

**Comment by alvaropag** [comment]
Hello, we have used it as a small cache before, but we already migrated our system to 1.0. 
So, I approve the removal.

**Comment by ArthurClemens** [comment]
I've also migrated to 1.0

**Comment by mworrell** [comment]
In private chat @mmzeeman also sent me an ok.

My sites don't use this feature as well, or have been migrated to 1.x

**Comment by mworrell** [comment]
Merged the changes, the persistent API will be gone in 0.69
