### ISSUE TITLE
CAPS cause wrong password reset to be sent

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#3118]
If you use an email like michiel@LEARNINGSTONE.com - you get an email saying you don't have an account while the michiel@learningstone.com will send the correct reset email.

**Comment by michielklonhammer** [comment]
You've requested a new password for [www.learningstone.com](https://www.learningstone.com/).

However this email address does not belong to one of our registered users so you will not be able to change the password.

If you think you have an account and were expecting this email, please try again using the email address you gave when signing up.

If you didn't request a password reset, you can safely ignore this email. Maybe someone made an error typing his or her email address.

**Comment by mworrell** [comment]
Hi, I just checked with `marc@MAXIMONSTER.COM` and that works.  I can't reproduce this issue.  Can you try again?
