### ISSUE TITLE
Partially requesting huge files causes zotonic to eat up huge amounts of memory

### ISSUE THREAD

**Issue by hce** [zotonic/zotonic#319]
I have a 900 MB file that is served through resource_file_readonly. Requesting the whole file works just fine. Doing a partial request causes zotonic to eat up all available memory, until it finally crashes and is restarted by heart. (Tested on latest commit (0a1ac1eee6552b1a2f9a5368ff62bc92501910aa))

**Comment by mworrell** [comment]
The send file behavior of webzmachine has been redone, this should now be fixed.
