### ISSUE TITLE
Missing controller_logon

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#3315]
The dispatch of `zotonic_mod_admin`  have the `admin_logon` rule and uses the `controller_logon`, but the controller does not exist. Also, the `logon_confirm_form.tpl` form delegates the submit to the `controller_logon`.
Going to "/admin/logon" an empty page is shown.

**Comment by mworrell** [comment]
Ah, that dispatch needs to be removed.

The controller logon was removed after we added the new authentication flow via the auth (js) worker.
