### ISSUE TITLE
It is possible to insert duplicate rsc_id, type and key entries into the identity table

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#3319]
## `Zotonic` version
[1.0.0-rc.15](https://github.com/zotonic/zotonic/tree/1.0.0-rc.15)

## `OS` / `Browser` version
MacOS / Safari

## Steps to reproduce
Enter two entries in the identity table with the same rsc_id, type and key in parallel. (I'll try to catch it in a unit-test.)

## Current behavior
Two entries are created.

## Expected behavior
There should be one entry.

## Config
N/A

**Comment by mmzeeman** [comment]
The problem is that there is no constraint on the `rsc_id`, `type` and `key` in the identity table. The function inserting the entry does a sql select before inserting, trying to prevent this from happening. But the function is not in a transaction. Note that doing this in a transaction will also not prevent this from happening, because there is no constraint, so the database will happily add multiple entries.

**Comment by mworrell** [comment]
Maybe just add a constraint and then catch the constraint error?

**Comment by mmzeeman** [comment]
I'll first try to catch this in a unit-test. I was thinking about adding the constraint, and add put the insertion itself in a transaction. I don't know how postgres will handle this.

**Comment by mmzeeman** [comment]
It was possible to catch it in a unit-test. Added the constraint, which is working.

I will have to add code to update the schema of an existing database, but... there could be duplicate entries in the table. I'm a bit reluctant to automatically remove double entries. 

Branch: https://github.com/zotonic/zotonic/tree/fix-3319
