### ISSUE TITLE
Add aarch64 docker images

### ISSUE THREAD

**Issue by geoidesic** [zotonic/zotonic#3330]
## `Zotonic` version
N/A

## `OS` version
Mac OS 13.2.1

## Description
* **Motivation**
The dockerised version of Zotonic does not run on new generation Macs because M1 chip is not Intel-based but rather ARM-based. It would be very useful to have a `docker-compose-aarch64.yml` config for running the docker images on M1 chip. 
* **Proposal**
Create a docker tag for ARM

## Current behavior
Does not run on new generation of Macs

## Expected behavior
Should have an option to run on M1 chips. E.g. for mysql there is [mysql/mysql-server:latest-aarch64](https://hub.docker.com/layers/mysql/mysql-server/8.0.32-aarch64/images/sha256-b966c2c0c643c5c35a21e03fa0e49d5f8bf1177d39b35aba86cb12715fd824da?context=explore)

## Config
N/A

**Comment by mworrell** [comment]
Are there aarch64 images for Erlang?

**Comment by geoidesic** [comment]
> Are there aarch64 images for Erlang? (I am still using Intel for macOS)

I believe the standard Erlang docker image offers multi-arch support as it is built on Debian which offers support for both architectures.

**Comment by mmzeeman** [comment]
I have an M1 MacBook, but I'm not a Docker user. I use kerl to switch between Erlang versions. Zotonic is pretty low on external dependency requirements. 

Kerl compiles to arm64 out of the box from R23 or 24 and up, depending on the arch setting of your terminal (see man arch). At the moment I'm testing the 26.0-rc1.

**Comment by mworrell** [comment]
We have revamped the Docker images. The system is now build when needed.
