### ISSUE TITLE
mod_base does not have a manifest.json template/dispatch

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#3339]
## `Zotonic` version

1.0.0-rc.15

## Description
* **Motivation**

Cotonic likes to have a service worker installed. We usually do that from the template of the site. It would be nice though to have a base manifest file, which can be overridden, to keep things uniform, and serve as an example.

* **Proposal**

Add a manifest template file to `mod_base`

## Current behavior

No manifest template provided.

## Expected behavior

A manifest file/template is provided, so a service worker is started by default.

## Config

What kind of things must be configured?

**Comment by mworrell** [comment]
Agree, this is a good addition.

Do you have an example that could be added as a bare bones default?

**Comment by mmzeeman** [comment]
Yes, we have a pretty bare bones one. I'll put in in a PR.
