### ISSUE TITLE
CMS infinitely encodes custom URL with ' ' in their name with every save

### ISSUE THREAD

**Issue by EdwardAbboud** [zotonic/zotonic#3349]
## `Zotonic` version

0.74.0

## `OS` / `Browser` version

macOS 13.2.1 and Chrome 111.0.5563.64

## Steps to reproduce

- Create a new page (or media) in CMS
- scroll down to advanced
- add a custom path to the page
- leave an empty space in the custom path i.e. '/page/file/test file'
- click 'save' and watch the space change to %20
- now on every save the url will change

## Current behavior

Every time the user clicks on save the URL is encoded as if it still contains a space even after it was replaced by %20 this means that he url will keep changing every time the user saves the page and so defeats the purpose of a custom path.

## Expected behavior

Once the space has been changed to %20 it should recognise the newly update path and not keep encoding it.

## Config

![Screenshot 2023-03-24 at 09 23 51](https://user-images.githubusercontent.com/97112418/227464548-3138626a-c5fc-4001-842c-7b71f1fc7fc6.png)

**Comment by mworrell** [comment]
Fixed in #3363
