### ISSUE TITLE
z_html:sanitize/2 eats whitespace.

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#335]
When you pull something like:

```html
<a href='#'>a</a> <a href='#'>b</a>
```

Through `z_html:sanitize/2` then the space between the two anchor tags is removed.
This seems to be a problem within `mochiweb_html:parse/1`

**Comment by mworrell** [comment]
@mmzeeman do you know if this is pushed upstream?

**Comment by mmzeeman** [comment]
No sorry. Some of our fixes are pushed upstream, some not.

**Comment by mworrell** [comment]
Closing - we need to do a complete check on the upstream push anyway,
