### ISSUE TITLE
Error sending email on zotonic master + Erlang 26

### ISSUE THREAD

**Issue by abensoft-alvaro** [zotonic/zotonic#3481]
## `Zotonic` version
[Release Version](https://github.com/zotonic/zotonic/commit/8ff6379e06198712d42904fff3302e07dedf5691)

## `OS` / `Browser` version

Ubuntu 20.04.6

## Steps to reproduce

Configure a zotonic site with or without relay (in our production server, relay is enabled)
Trying to send an email with the command
`z_email:send(<<"YOUR_GMAIL_USER@gmail.com">>, <<"test">>, <<"mensagem">>, Context).`

If the relay is enabled the error message is
`2023-07-24 14:11:53 ERROR  site=ommited <0.2025.0> [z_email_server:spawned_email_sender_loop/13:920] ▸ failure_type=network_failure recipient=USER@gmail.com relay=email-smtp.us-east-1.amazonaws.com result=error text="Error sending email" host=0.0.0.0 (ommited) reason=retries_exceeded message={error,{options,incompatible,[{verify,verify_peer},{cacerts,undefined}]}} in=zotonic_core `

If relay option is not enabled then the error message is
`2023-07-24 14:19:09 ERROR  site=ommited <0.1777.0> [z_email_server:spawned_email_sender_loop/13:920] ▸ failure_type=network_failure recipient=USER@gmail.com relay=gmail.com result=error text="Error sending email" host=gmail-smtp-in.l.google.com reason=send message={error,closed} in=zotonic_core`

I've tested with gen_smtp master and the error persists.
Returning to Erlang 25 the sending process is working.

It seems something changed on SSL library in Erlang 26 that breaks the sending function. I was unable to find how to change verify_peer to verify_none or to inform the cacerts for the SMTP server. Maybe it should use the same cert of the HTTP?

## Config
Enable/disable the relay options.

**Comment by mworrell** [comment]
See also https://github.com/gen-smtp/gen_smtp/issues/328#issuecomment-1638095057

Could you check this solution and maybe make a pull request?

**Comment by abensoft-alvaro** [comment]
I've tried the solution at the link (and a lot of possible combinations), but none of them worked. 
We rolled back our production server to Erlang 25 for the moment. 
I'll keep investigating the issue.

**Comment by mworrell** [comment]
I just saw this bit of Elixir code passing by:

```
In case anyone needs to get this working for AWS SES, this seems to be the minimal config...

    smtp_relay = System.get_env("AWS_SMTP_RELAY") # e.g. "[email-smtp.us-east-1.amazonaws.com](http://email-smtp.us-east-1.amazonaws.com/)"
    config = [
      relay: smtp_relay,
      port: 587,
      username: System.get_env("AWS_SMTP_USERNAME"),
      password: System.get_env("AWS_SMTP_PASSWORD"),
      tls: :always,
      tls_options: :tls_certificate_check.options(smtp_relay)
    ]
```

**Comment by abensoft-alvaro** [comment]
Thanks for the tip, I'll give it a go.

**Comment by abensoft-alvaro** [comment]
Hello, sorry for the delay, using the tip [above](https://github.com/zotonic/zotonic/issues/3481#issuecomment-1658038604) it worked.

```erlang
A = {"noreply@YOUR_DOMAIN", ["YOUR EMAIL@gmail.com"],
   "Subject: Emails are working\r\nFrom: MY WEBSITE <noreply@YOUR DOMAIN>\r\nTo: YOUR NAME <YOUR EMAIL@gmail.com>\r\n\r\nLooks like emails are working"}.

B = [{versions, ['tlsv1.2']}, {log_level, debug}] ++ tls_certificate_check:options("email-smtp.us-east-1.amazonaws.com").

C = [
    {auth, always},
    {relay, "email-smtp.us-east-1.amazonaws.com"},
    {port, 587},
    {tls, always},
    {username, "YOUR_USERNAME"},
    {password, "YOUR_PASSWORD"},
    {ssl, false},
    {retries, 0}
].

gen_smtp_client:send_blocking(A, [{tls_options, B} | C]).
```

I've also tried with ssl, true on port 465, but it didn't worked. 

The possible modifications are:

- Add support for option smpt_tls on zotonic config
- Call tls_certificate_check:options if the relay option is set to true and smpt_tls is set to true

If you think these modifications are enough I can send a patch.

**Comment by mworrell** [comment]
Ah, cool. So it seems we might want to add the extra TLS options in the core.

And yes, please send a patch! Thanks!

**Comment by mworrell** [comment]
@abensoft-alvaro Could you check this potential fix?  https://github.com/zotonic/zotonic/pull/3652

**Comment by abensoft-alvaro** [comment]
Hi @mworrell, I'll check it out and get back to you

**Comment by abensoft-alvaro** [comment]
Hello @mworrell!

This PR is working for me.
I've tested it with erlang 26.0.1 and 26.2.1, with both global and site relay options, both of them are working correctly!

Sorry for the delay ;)
