### ISSUE TITLE
Block emails being sent unless conditions are met

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#3490]
## `Zotonic` version
[0.x](https://github.com/zotonic/zotonic.git)

## Description
* **Motivation**
For various reasons it is often the case that people have testing/staging environments with (semi-)live data, including user accounts with real e-mail addresses. While it is necessary to be able to test functionality involving e-mail, actually sending e-mail to real people's email addresses from such environments is unwanted.

* **Proposal**
Proposed is a server-wide setting to block sending of *all* e-mails unless certain conditions are met. Such conditions could be:
  - The destination address matches a list (only allowing e-mails to be sent to specific e-mail addresses)
  - The destination domain matches a list
  - The e-mail was sent to the site's configured override address 
  - The site's environment setting is "production"

**Comment by mworrell** [comment]
I would propose that email that is not matching the allow-list would be sent to the override address (if any).

**Comment by mworrell** [comment]
In 1.x we have the zotonic config to set an override address.
This override address can't be changed in the site config.

Also added is now a list of exceptions to which the email is sent, regardless of the override address. This to ease testing with certain domains or email addresses.

This config can be set in the admin.
