### ISSUE TITLE
foo.app - no such file or directory

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#3611]
Currently using the master branch of Zotonic running a few sites. I just updated Zotonic, then added a new site using the wwwadmin gui.

Addsite foo.com

The setup completes with an error notification saying foo.app is not found. Zotonic is running in debug mode, and terminal is currently repeating "no such file or directory\","\foo.app\" every second.

Apparently a change has been made, but I must have missed the Github change notification. 

If I restart Zotonic will the currently running sites report the same issue? Where can I find documentation on the new "site.app" functionality?

**Comment by seannaswell** [comment]
Please disregard this issue, and apologies for the noise... Not sure what I did to cause the problem, but a fresh update and compile seemed to resolve the issue.

**Comment by mworrell** [comment]
Thanks for coming back with the update! 👍
