### ISSUE TITLE
I can't update the release

### ISSUE THREAD

**Issue by heiheshang** [zotonic/zotonic#3642]
I'm trying to upgrade from release 0.34.0 to 0.76.0
I encountered a strange problem. A lot has changed between releases, I don’t understand what needs to be done
`error @ z_module_manager:507  Module mod_admin start error: {error,
                               {schema_init,
                                {error,
                                 {"Module downgrades currently not supported.",
                                  mod_admin}}}}
=ERROR REPORT==== 15-Dec-2023::13:13:43.246020 ===
Error in memo error:{case_clause,#{<<"custom_slug">> => false,
                                   <<"date_is_all_day">> => false,
                                   <<"default_printer">> => <<"EPSON_LX-300">>,
                                   <<"destination">> => <<"397">>,
                                   <<"document_type">> => <<"99">>,
                                   <<"flight">> => <<"51578">>,
                                   <<"is_page_path_multiple">> => false,
                                   <<"is_website_redirect">> => false,
                                   <<"name_surname">> =>
                                       <<152,208,178,208,176,208,189,208,
                                         190>>,
                                   <<"pref_language">> => ru,
                                   <<"pref_tz">> => <<"Asia/Yakutsk">>,
                                   <<"seo_noindex">> => <<"1">>,
                                   <<"title">> =>
                                       {trans,[{ru,<<"Site Administrator">>}]},
                                   <<"tz">> => <<"Asia/Yakutsk">>}} in [{z_db,
                                                                         merge_props,
                                                                         2,
                                                                         [{file,
                                                                           "src/db/z_db.erl"},
                                                                          {line,
                                                                           995}]},
                                                                        {timer,
                                                                         tc,2,
                                                                         [{file,
                                                                           "timer.erl"},
                                                                          {line,
                                                                           181}]},
                                                                        {z_db,
                                                                         with_connection,
                                                                         3,
                                                                         [{file,
                                                                           "src/db/z_db.erl"},
                                                                          {line,
                                                                           220}]},
                                                                        {z_db,
                                                                         assoc_props_row,
                                                                         3,
                                                                         [{file,
                                                                           "src/db/z_db.erl"},
                                                                          {line,
                                                                           241}]},
                                                                        {m_rsc,
                                                                         get_raw,
                                                                         3,
                                                                         [{file,
                                                                           "src/models/m_rsc.erl"},
                                                                          {line,
                                                                           271}]},
                                                                        {m_rsc,
                                                                         '-get/2-fun-0-',
                                                                         2,
                                                                         [{file,
                                                                           "src/models/m_rsc.erl"},
                                                                          {line,
                                                                           225}]},
                                                                        {depcache,
                                                                         memo,
                                                                         5, 
                                                                         [{file,
                                                                           "src/depcache.erl"},
                                                                          {line,
                                                                           150}]},
                                                                        {m_rsc,
                                                                         p_cached,
                                                                         3,
                                                                         [{file,
                                                                           "src/models/m_rsc.erl"},
                                                                          {line,
                                                                           584}]}]`

**Comment by mworrell** [comment]
Normally this shouldn't happen as we don't downgrade between releases.
The version on 1.x is newer though, maybe a master version of Zotonic did upgrade the database?
