### ISSUE TITLE
site.app - No such file or directory

### ISSUE THREAD

**Issue by seannaswell** [zotonic/zotonic#3673]
## `Zotonic` version
git master

## `OS` / `Browser` version
FreeBSD 14

## Steps to reproduce
Create new site

## Current behavior
After the creation of a new site using the "Add Site" function on the Zotonic admin, the process creates an Error dialog stating that "newsite.app" directory cannot be found, and site does not start.

When running `zotonic debug` an Error displays every second saying:

`2024-01-21 18:23:58 NOTICE  site=test <0.466.0> [z_sites_manager:do_start_site/1:730] ▸ text="Site starting" in=zotonic_core action=starting`
`2024-01-21 18:23:58 ERROR  site=test <0.466.0> [z_sites_manager:do_start_site/1:753] ▸ text="Site start failed" result=error reason="{test,{\"no such file or directory\",\"test.app\"}}" in=zotonic_core`

Assuming this is new functionality currently in the process of being developed?  Can I rename a directory or file to silence the warning and start the new site, or is there more involved?

**Comment by seannaswell** [comment]
Please disregard, user error...closing this issue. Updating, recompiling and restarting resolved the issue.  It seems something was out of sync.

Just to clarify, does "Rebuild Zotonic" in the web admin page do the same thing as "(g)make" on the command line?

**Comment by mworrell** [comment]
Hi!  Good that it is fixed.

The _Rebuild Zotonic_ does a call to `./rebar3 compile`.  Looking at the makefile, that should be the same as running`make`.
