### ISSUE TITLE
Live tag is not posting to server side

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#3684]
## `Zotonic` version
[1.0.0-rc15-cd8741899](https://github.com/zotonic/zotonic/tree/cd8741899a962e3898373451516935b1a9b2da4c)

## `OS` / `Browser` version
Firefox 122.0.1-1

## Steps to reproduce
As in "[Building a live updating search page](https://zotonic.com/page/2389/building-a-live-updating-search-page)"

## Current behavior
The target div is not updated when any field/box in the form is modified.
The URL field in the browser is updated with the new query part but it is never sent to the server side.

## Expected behavior
As described in the instruction. It has worked "before" :slightly_smiling_face:

**Comment by karlsson** [comment]
Update: I cannot see any network communication in the browser debug console when updating form fields but this is also true when I check against my [working site](https://skolan.creado.se/sv/page/340/skolor), running on an older version, where the page is truly updated anyway! (The form is in the side-bar under the breadcrumb.)

**Comment by mworrell** [comment]
All comms should go over the websocket - so that you don't see anything is no surprise.

Questions:

 * Do you see any errors in the browser console?
 * Did you update to the newest Cotonic?  (`make update-cotonic`)

**Comment by karlsson** [comment]
I checked with tcpdump and I do have traffic... :blush:  Also latest cotonic from master.
It is my query that (silently) goes wrong so I just dumped what is coming in with `{% debug %}` tag in the template and it seems some things have changed. Before I got some field called payload, but now everything comes in the "q" part.
The q part is a list of key/value tuples but I cannot pipe q directly to a filter. Instead I can only access fields with q.fieldname. This is a problem when I have multiple check boxes as I get several values for the same name.
q = 
```
[{<<"qfacet_su_status">>,<<"Aktiv">>},
 {<<"qfacet_su_status">>,<<"Vilande">>},
 {<<"qfacet_su_status">>,<<"Planerad">>},
 {<<"qfacet_su_typ">>,<<"Kommun">>},
 {<<"qfacet_su_typ">>,<<"Enskild">>},
 {<<"qfacet_su_typ">>,<<"Region">>},
 {<<"qfacet_su_typ">>,<<>>},
 {<<"qfacet_su_typ">>,<<>>},
 {<<"qfacet_kommun">>,<<"1489">>},
 {<<"qfacet_kommun">>,<<"0764">>},
 {<<"qfacet_kommun">>,<<"0604">>},
 {<<"qfacet_kommun">>,<<"1984">>},
 {<<"qfacet_kommun">>,<<"2506">>},
 {<<"qfacet_kommun">>,<<"2505">>},
 {<<"qgyr_weighted">>,<<"none">>},
 {<<"qgyrr_weighted">>,<<"25">>},
 {<<"qfacet_is_salsa">>,<<>>},
 {<<"qsu_title">>,<<>>},
 {<<"triggervalue">>,<<>>}]
```

I only get the first value for a name when I access q.fieldname. Before I had my "own" filter that assembled the query like:
```
{% with m.search.facets::%{
           'facet.su_status':qpayload|make_filter:'facet_su_status',
```
and assembled a list of all selections. m.req.qs is also empty since it is not a http request. I guess there is a way to get hold of the complete "q" list since the "debug" tag prints it nicely in the template, but I cannot figure out how.

**Comment by mworrell** [comment]
First quick hint, before I have more time to check this. For values with multiple answers you can also use a name like `qfacet_su_status[]`  This will make the checkboxes a list, the transformation to a nested structure is done by the search model.

**Comment by karlsson** [comment]
Thanks Marc, it looks much better now. qargs and trailing [] seems to do the trick! Seems the search model takes care of stripping the "q" from the name and handle the "." in facet.name. I think I can remove a lot of my own filters now. I have some value "slider" that I will need to fix manually I think, might come back on that.

**Comment by karlsson** [comment]
Hi again Marc,
I think you can close this. Everything works fine using qargs and qfacet.xxxx[] names. I might have some issue with multiple select ( I can also see some comment i z.forminit.jz in zotonic_mod_base ) but I will come back to this in such case.
