### ISSUE TITLE
`erljwt` deprecated

### ISSUE THREAD

**Issue by maennchen** [zotonic/zotonic#3687]
Since `oidcc` has moved on from `erljwt` to `jose` and it was the largest consumer of the library, the decision has been made to deprecate the library.

The package has been retired on hex, archived on GitHub and will yield warnings on installation via hex.

It seems that `zotonic_mod_authentication` requires `erljwt` in the rebar config. I however don't see any mention of the library in the code. I therefore assume that it should be safe to just drop the library.

```bash
$ git grep erljwt
apps/zotonic_mod_authentication/rebar.config:  {erljwt, "~> 2.0"}
doc/developer-guide/releasenotes/rel_1.0.0-rc.9.rst: * mod_authentication: add erljwt (#3134)
rebar.lock: {<<"erljwt">>,{pkg,<<"erljwt">>,<<"2.0.7">>},0},
rebar.lock: {<<"erljwt">>, <<"15C76E9E17B3DB2A1AA105EBA0AB384BA09D5C5742376F074DFF39A0CC67578C">>},
rebar.lock: {<<"erljwt">>, <<"61266D3D3CB35B3EA341916CE73B0AEFE0FACE260B402729AE7426EB8D5293C3">>},
```

Based on #3134 I assume that the library was brought in to do OpenID auth. If that is the case, I'd recommend using not using `jose` directly but rather `oidcc` (which I'm a maintainer of). I'd be happy to assist in the implementation.

**Comment by mworrell** [comment]
Hi @maennchen Thanks for you issue.  Indeed, including it was an artifact of work on OIDCC.  We are working on a new OIDCC module, based on your new `oidcc` package.  I think we can just remove the erljwt package from the rebar config and let any module or site that needs that functionality import a library themselves.

**Comment by mworrell** [comment]
Done, removed it.

Thanks @maennchen !
