### ISSUE TITLE
exec /usr/bin/dumb-init: exec format error

### ISSUE THREAD

**Issue by gfvh** [zotonic/zotonic#3735]
## `Zotonic` version
0.82.0

## `OS` version
ubuntu 22.04

## Steps to reproduce
git clone https://github.com/zotonic/zotonic.git
start-docker.sh

## Current behavior
./start-docker.sh
Starting zotonic_postgres_1 ... done
Creating zotonic_zotonic_run ... done
exec /usr/bin/dumb-init: exec format error
ERROR: 1

## Expected behavior
to build dockers and run dumb-init normally

**Comment by mworrell** [comment]
Do you want to run the 0.x or the (better) Zotonic master version.
If you want to run the master (1.x) version, could you give this branch a try:

https://github.com/zotonic/zotonic/pull/3723

**Comment by mworrell** [comment]
Closed due to inactivity
