### ISSUE TITLE
Bug uploading a file via `fileuploader` worker

### ISSUE THREAD

**Issue by williamthome** [zotonic/zotonic#3751]
## `Zotonic` version
[1.0.0-rc.15](https://github.com/zotonic/zotonic/releases/tag/1.0.0-rc.15)

## `OS` / `Browser` version
Operating system: Ubuntu 22.04.1 LTS
Browser: Google Chrome Version 125.0.6422.76 (Official Build) (64-bit)
Erlang version: Erlang/OTP 26 [erts-14.1]

## Steps to reproduce
Uploading a file using `fileuploader` worker, but it does not always occur, so I don't have a reproducible repo or code. I would say that out of 10 times, one error occurs.

## Current behavior
Sometimes, it stays in a loop with 1 `upload_count` remaining:
![image](https://github.com/zotonic/zotonic/assets/35941533/03c7170e-637d-45ef-96a8-cfd18c647fe7)

The JS code is from [zotonic.fileuploader.worker.js](https://github.com/zotonic/zotonic/blob/0a61d8ce5abd41d4cc7cf230b60273c11c690e1f/apps/zotonic_mod_fileuploader/priv/lib/js/zotonic.fileuploader.worker.js#L282).

Maybe the check could be the `progress_msg` that contains the percentage, but there is a bug somewhere, and I don't know where.
The `upload_count` var is defined and updated only in the worker file.

## Expected behavior
`upload_count` be zero when the upload percentage is 100%.

**Comment by mworrell** [comment]
You are uploading multiple files?

**Comment by williamthome** [comment]
Just one file.

**Comment by mworrell** [comment]
I suspect it has to do with failed uploads.

When we are filtering the files for failed ones, we do not decrement the upload count when removing the failed upload.

```erlang
    // Remove all files with failed req
    fs = [];
    for (let i = 0; i < model.files.length; i++) {
        let f = model.files[i];
        if (f.req.error_count == 0) {
            fs.push(f);
        } else if (f.status && f.status.name) {
            // Tell server to remove this upload
            self.publish("bridge/origin/model/fileuploader/post/delete/"+f.status.name, {});
            f.req.upload_count--;   // <<<< THIS
        } else {
            f.req.upload_count--;   // <<<<  THIS
        }
    }
```

What do you think?

**Comment by mworrell** [comment]
Can you see what the model state is when this happens?

**Comment by mworrell** [comment]
@williamthome Can you check if #3754 fixes the problem for you?

**Comment by williamthome** [comment]
Yes, I'll check.
