### ISSUE TITLE
erlexec 1.0 retired

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#3792]
## `Zotonic` version
1.0 (881ae081cd320c20c2dc071f6e9d28172718bf82)

## `OS` / `Browser` version
Erlang 27.0 / Linux

## Steps to reproduce
make clean / make

## Current behavior
When building (fetching dependencies) zotonic there is a printout that `erlexec` 1.0 is retired (deprecated).

## Expected behavior
Maybe bump version from 1.0 to 2.0 in `rebar.config` for `apps/file{handler,watcher}` ?
And bump from 1.21 to 2.0.6 in `rebar.lock`?

## Config
N/A

**Comment by mworrell** [comment]
Do we have a list of incompatibilities between the 1 and 2 version?

**Comment by karlsson** [comment]
"No breaking changes" :grin:
[CHANGELOG.txt](https://github.com/saleyn/erlexec/blob/master/CHANGELOG.txt)
I could check how it is used in filehandler/filewatcher but if you know the use cases right away I could do some testing...

**Comment by mworrell** [comment]
And upgraded.
