### ISSUE TITLE
Dropped stream connection

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#385]
If you have configured your site to use comet via sub-domain, browsers with websockets can experience a dropped stream connection. 

The problem is this. Say you have a site called mysite.com and have setup the comet stream to connect to  nnn.stream.mysite.com, the following can happen with a browser with websockets support. A lot of things happen in order to setup a stream connection. I hope the following will explain the failure scenario I found.

1) The browser sets up a websocket to mysite.com
2) Network glitch or something else which drops the websocket connection.

3) Zotonic.js sees the dropped websocket connection and tries to re-connect to mysite.com once. (If there is a temporary network glitch this is highly likely to fail again)

4) 3 failed. zotonic.js tries to setup a comet connection as a replacement for the failed websocket. This is configured via a subdomain.
5) Browser tries to retrieve the page 123.stream.mysite.com/comet/subdomain. 

6a) If 5 fails, due to the same network glitch, zotonic.js doesn't try again to reconnect. The stream is dropped and not retried.
  
How can we make the stream more robust?

Should we setup the websocket stream via the subdomain page? This would make it more robust because the browser can skip stage 5, and just switch over to comet, which will be retried.

**Comment by mworrell** [comment]
The streams are redone with z_transport, closing this issue.
