### ISSUE TITLE
Unicode string in config title not correctly mapped to unicode binary [was: Invalid byte error with jsxrecord 2]

### ISSUE THREAD

**Issue by karlsson** [zotonic/zotonic#3854]
## `Zotonic` version
[1.0.0-rc.15-e7ec46a](https://github.com/zotonic/zotonic/commit/e7ec46abbb1c6cdd38baa791f9fc3644fcaa8ba1)

## `OS` / `Browser` version
N/A (Firefox)

## Steps to reproduce
Getting the front page of my application (skolan.creado.se)

## Current behavior
I get a blank page.
Error log: text="Unexpected exception" level=error path=/sv/ at=cowmachine:request_1:136 reason={invalid_byte,110}
Complete log:
```
2024-09-11 10:10:00 ERROR  site=skolan  dispatch=home <0.2126.0> [cowmachine:log_report/2:230] ▸ dst_ip4=185.157.221.71 dst_port=8443 class=error src_ip4=89.253.86.44 src_port=37412 text="Unexpected exception" level=error path=/sv/ at=cowmachine:request_1:136 reason={invalid_byte,110} node=zotonic@localhost in=cowmachine code=500 
  Stack:
     json:invalid_byte/2 @ "/home/erlang/zotonic/_build/default/lib/json_polyfill/src/json.erl":527
     euneus_encoder:-encode_map/2-lc$^0/1-0-/3 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":528
     euneus_encoder:-encode_map/2-lc$^0/1-0-/3 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":529
     euneus_encoder:encode_map/2 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":529
     json:do_encode_list/2 @ "/home/erlang/zotonic/_build/default/lib/json_polyfill/src/json.erl":228
     euneus_encoder:-encode_map/2-lc$^0/1-0-/3 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":528
     euneus_encoder:-encode_map/2-lc$^0/1-0-/3 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":529
     euneus_encoder:encode_map/2 @ "/home/erlang/zotonic/_build/default/lib/euneus/src/euneus_encoder.erl":529
```

## Expected behavior
Page should show and no error in the log

## Config
When I change the jsxrecord version from ~> 2.0 to ~> 1.3 in apps/zotonic_core/rebar.config thereby removing euneus and json_polyfill apps and recompile it works again.

jsxrecord diff in rebar.lock:
```
- {<<"jsxrecord">>,{pkg,<<"jsxrecord">>,<<"2.2.0">>},0},
+ {<<"jsxrecord">>,{pkg,<<"jsxrecord">>,<<"1.3.2">>},0},
```

**Comment by mworrell** [comment]
Do yo know the input to `euneus_encoder:encode_map/2` that is tripping up the encoder?

**Comment by karlsson** [comment]
I will try and check. The only json that I can see is returned when it is working is some "zotonic_auth". 
`{"status":"ok","options":{},"user_id":null,"url":null,"username":null,"is_authenticated":false,"preferences":{"timezone":"Europe/Stockholm","language":"sv","languages":["sv","en"]}}`

And then similar in mqtt_transport.
`{"user_id":null,"options":{},"preferences":{"timezone":"Europe/Stockholm","language":"sv","languages":["sv","en"]}}`

**Comment by mworrell** [comment]
Interesting, maybe you can set a trace on the encode function, to see what passes there?

**Comment by mworrell** [comment]
Looking at `json.erl` it might be that there is an invalid UTF-8 sequence somewhere...

```erlang
%% - `error({invalid_byte, Byte})' if the binary contains invalid UTF-8 sequences.
```

But where....

**Comment by karlsson** [comment]
Hmm a Swedish "ä" maybe, the last I can see is:
```
#{<<"@id">> => <<"https://skolan.test:8443/#organization">>,
      <<"@type">> => <<"schema:Organization">>,
      <<"schema:description">> => <<"Skolan">>,
      <<"schema:name">> => <<"Skolor, huvudmän, lobbyister">>,
      <<"schema:url">> => <<"https://skolan.test:8443/">>}
```

**Comment by mworrell** [comment]
That is the JSON-LD in the head of the page.

Hmmm... shouldn't that be:

```erlang
<<"Skolor, huvudmän, lobbyister"/utf8>>
```

Is that coming from your config file?

**Comment by karlsson** [comment]
Yes, it is the site title set in the zotonic_site.config.
`{title, "Skolor, huvudmän, lobbyister"}`
The file buffer is set to utf-8-unix according to emacs...

**Comment by karlsson** [comment]
If I change in my config file to:
`{title, <<"Skolor, huvudmän, lobbyister"/utf8>>}`
it starts to work. :smile: 
Not sure if the original char list should be handled in some other way though?

**Comment by mworrell** [comment]
I guess there is probably some list-to-binary hiding in the config parsing routines.  That should become the unicode-to-binary.

**Comment by karlsson** [comment]
I think I found it in z_stdlib repository.
When I change in module z_convert:
the clause from
`to_binary(L) when is_list(L) -> iolist_to_binary(L);`
to
`to_binary(L) when is_list(L) -> unicode:characters_to_binary(L);`
it works fine again with utf characters.
https://github.com/zotonic/z_stdlib/blob/05d5f75d0da6c4b78af2a8e958dd39e28ada63dd/src/z_convert.erl#L105

**Comment by mworrell** [comment]
Good one.

I remember I have been thinking of swapping that `iolist_to_binary` for the `unicode` version.  Which _should_ be ok now that we are using Cowboy (Cowmachine) and are handling binaries almost everywhere. There are some places where there is still some binary -> list -> binary stuff going on (I remember some escape filters), need to check those.

**Comment by karlsson** [comment]
Thanks,
I can verify that it works fine for me too now. :man_dancing:
