### ISSUE TITLE
./start-docker.sh ./start-docker.sh: line 13: docker-compose: command not found

### ISSUE THREAD

**Issue by geoidesic** [zotonic/zotonic#3904]
Docker has changed the syntax from `docker-compose` to `docker compose`.

Please update the repo

**Comment by mworrell** [comment]
Always fun, those Docker containers.
I much prefer to run without Docker, but others swear by Docker, so that is why we have these containers.

**Comment by mworrell** [comment]
So the following command should work?

```bash
NO_PROXY=* docker compose -f ./docker-compose.yml run --service-ports zotonic sh
```

**Comment by geoidesic** [comment]
I managed to get it to work by editing ./start-docker.sh – just changed the `docker-compose` to `docker compose`. I'm suggesting that this change should be persisted to this repo.

**Comment by mworrell** [comment]
@geoidesic Should be fixed now.  Thanks!
