### ISSUE TITLE
Documentation doesn't show how to include JavaScript libs.

### ISSUE THREAD

**Issue by geoidesic** [zotonic/zotonic#3913]
https://zotonic.com/docs/1372/lib shows how to include css libs and also says that it can include javascript libs but doesn't show how to do the latter. 

What I found is that if I include css or javascript files in the `_build/default/lib/[site_name]/priv/lib/css` folder, then they will be included, e.g. by 

```django
{% lib
    "css/test.js
%}
```
 However, my assumption that I could create a `_build/default/lib/[site_name]/priv/lib/js` folder and use that to include js files... well that doesn't work e.g. by
 
```django
{% lib
    "js/test.js
%}
```

It seems a bit perverse to have to store one's site's JavaScript libs in the css folder. Am I missing something?

**Comment by geoidesic** [comment]
Ah... never mind. It started working after I Rescanned Modules and Recompiled Templates in `https://www.zotonic.localhost:8443/admin/development`

**Comment by mworrell** [comment]
Thanks for coming back with the solution.

Do you have `inotify` or `fswatch` installed?
They greatly help with picking up new files or changes.

**Comment by geoidesic** [comment]
No. I don't have those installed. Where would I install them – on the host OS or in the docker container? And what config would be necessary to link that to zotonic?

**Comment by mworrell** [comment]
hmmm good one... where Erlang is running.

I am wondering if `inotify` is working on volumes in a Docker container.

**Comment by geoidesic** [comment]
It should work on any linux kernel, so yes. Perhaps it should be added to the Dockerfile

**Comment by mworrell** [comment]
Interesting, we _are_ installing the required inotify-tools:

```
RUN apk add --no-cache bsd-compat-headers ca-certificates wget curl \
        make gcc musl-dev g++ libstdc++ \
        bash file gettext git openssl inotify-tools \
        imagemagick ffmpeg \
        dumb-init
```

**Comment by geoidesic** [comment]
From ChatGPT:
```
inotify can monitor both new files and new folders, but it requires explicit configuration to detect new folders. By default, inotify only watches existing files and directories. If a new subdirectory is created within a watched directory, inotify will not automatically start monitoring the new subdirectory unless configured to do so.
```

So the simple solution is add an js folder into the default site folder structure, parallel to the css folder, maybe with a default `project.js` file to mirror the `project.css` file, with just a `console.log('custom.js')` in the file and include that in the `base.tpl`.

And also update the documentation to show how to include js, not just css.

**Comment by mworrell** [comment]
Afaik inotify does find new files in new folders.
We pass a list of folders that it should be watching.

I should try running that container again to see how well everything works.

We do enable the file watcher per default (from zotonic.config):

```erlang
%%% Automatically compile and load changed files. You must have inotify or fswatch installed.
   %% {filewatcher_enabled, true},

%%% Scan for changed files beam files if inotify and fswatch are not enabled
%%% Enabling this will make the system slower, it is advised to use inotify and/or fswatch
   %% {filewatcher_scanner_enabled, true},
```
