### ISSUE TITLE
zotonic_mod_custom_redirect: hostname and path are limited to 80 chars

### ISSUE THREAD

**Issue by CyBeRoni** [zotonic/zotonic#3942]
## `Zotonic` version
1.x

## Steps to reproduce
- Enable mod_custom_redirect
- Add a redirect for a long hostname or long path, either 81 characters long or more.

## Current behavior
Update is rejected because db table has varchar(80) columns.

## Expected behavior
Update is not rejected.

Bost hostnames and URL paths can be decidedly longer than 80 characters, and while this chance is somewhat unlikely in the case of a hostname (though there is, in that case, a 63-character limit per label not including the period, multiple such labels can be strung together), the path can easily grow quite large if the module is used to redirect URLs from an old website which is a common use-case for me.

So far as I can tell postgres's limit for varchars is quite large (10MB) so I propose the limit simply be removed, or otherwise set to at least 255. According to the PostgreSQL documentation there is a slightly larger overhead for longer (> 126) strings than shorter ones but no ill effects are mentioned beyond that number and 126 is still too short. Additionally, they state:

> There is no performance difference among these three types, apart from [...] a few extra CPU cycles to check the length when storing into a length-constrained column.

so I feel like simply removing the length constraint is the most reasonable option.

**Comment by mworrell** [comment]
We still need to set a max length, as `character varying` does need a max length.

We can up it to ~500 for the path and ~250 for the hostname.

**Comment by mworrell** [comment]
Funny.  On the doc page it _looks_ like a limit is needed, but then in the text they say it is not needed.
For sanity I will keep limits, as I don't want to move 10MB strings around.

https://www.postgresql.org/docs/current/datatype-character.html
