### ISSUE TITLE
Rename scomps to "custom tags" in the code

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#425]
We agree that "custom tags" is a much easier to understand principle than "scomps".

I suggest renaming the `scomps/` folder to `custom_tags/` in each module, and have the module prefix be renamed from `scomp_base_foo` to custom_tag_base_foo`.

Discussion: use just `tag` instead of `custom_tag`?

**Comment by mworrell** [comment]
Still want to do this?
