### ISSUE TITLE
name_to_id does not work for resources which have names with all numbers

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#440]
m_rsc:name_to_id simply returns the passed number as the resource id. 

All uses of name_to_id should be checked, because some of those uses could expect this behaviour. If this is the case, m_rsc:rid should be used instead.

**Comment by mmzeeman** [comment]
Friendly reminder to myself to put this in master. Bumped into it again...

**Comment by ddeboer** [comment]
> we should untangle the use of m_rsc:rid/2 and m_rsc:name_to_id/2.

Is this what needs to be done for this issue? What about just ditching `rid` and keeping `name_to_id` and `name_to_id_check` (which crashes intentionally if the resource is not found).

**Comment by mworrell** [comment]
`rid` can have the current behavior, "if it looks like an id, assume it is an id"

`name_to_id` should be strict, if it is not a name, then it can't be mapped.

**Comment by ddeboer** [comment]
Okay, so we keep all three: `rid`, `name_to_id` and `name_to_id_check`.
