### ISSUE TITLE
Connecting to non-existing db schema

### ISSUE THREAD

**Issue by kaos** [zotonic/zotonic#478]
When the schema does not exist, erlang crashes.

`13:53:30.559 [info] pgsql_pool: could not connect to database "zotonic". Error: {error,error,<<"22023">>,<<"invalid value for parameter "search_path": "morpheus_dev"">>,[{detail,<<"schema "morpheus_dev" does not exist">>}]}

Terminating due to shutdown
{"init terminating in do_boot",{{badmatch,{error,{shutdown,{zotonic_app,start,[normal,[]]}}}},[{zotonic,start,1,[{file,"src/zotonic.erl"},{line,51}]},{init,start_it,1,[]},{init,start_em,1,[]}]}}

Crash dump was written to: erl_crash.dump
init terminating in do_boot ()
`

**Comment by mworrell** [comment]
The 0.12 version will try to create the schema.
