### ISSUE TITLE
Document or remove streamhost option

### ISSUE THREAD

**Issue by kaos** [zotonic/zotonic#480]
Ref. to #435 for details.

**Comment by mworrell** [comment]
With the new z_transport the streamhost config is not used anymore.

We should check the documentation.

**Comment by mworrell** [comment]
Checked the code - the support is still there.
Shall we remove it? 

With http/2 it is not needed anymore anyway, and with https it won't work due to the certificate.

**Comment by ddeboer** [comment]
Has been removed.
