### ISSUE TITLE
Web server: replace MochiWeb

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#533]
See #513  for discussion on this

**Comment by mworrell** [comment]
I am still leaning towards Elli. I am wondering if they will support http2 though,

**Comment by mmzeeman** [comment]
I send out a ping to @knutin

**Comment by ddeboer** [comment]
@mworrell  mailed:

> We have now two wiki pages with information about replacing MochiWeb in Zotonic.
>
> The discussion as part of our optimizations:
> 
>https://github.com/zotonic/zotonic/wiki/Improving-zotonic's-throughput#usage-of-mochiwebwebmachine-with-no-binaries
>
> And just added, specifically about Cowboy:
>
> https://github.com/zotonic/zotonic/wiki/Proposal-for-using-Cowboy-as-the-HTTP-server
>
> Please check and add your comments.

**Comment by mworrell** [comment]
Added a reference to this issue on the wiki page https://github.com/zotonic/zotonic/wiki/Proposal-for-using-Cowboy-as-the-HTTP-server

**Comment by mmzeeman** [comment]
Is this our wish list?

  * webmachine like request handling
  * comet
  * websockets
  * http2
  * sse possibility
  * file uploads
  * file downloads (chunked)
  * being able to work without hassles for corporate users with broken clients
  * ssl + sni
  * good access logging (our current log is broken for some edge cases)
  * measurability (how long do things take internally)
  * how does it handle things when process running out of sockets or when other things break?
  * debuggability

**Comment by mworrell** [comment]
And:

 * compatible (or almost...) with our current controllers

**Comment by ddeboer** [comment]
* In our meeting today, we decided to go for Cowboy.
* We will define a Controller behaviour that fits Zotonic well as is simpler than the current one.
* @mworrell will start working on making all request handling asynchronous, which is also a preparation for HTTP/2.

**Comment by mworrell** [comment]
Will also start mapping all query args to binaries, so that we can start adapting the code base.

**Comment by mworrell** [comment]
I will send an email to the mailing lists to warn about the incompatibilities we will be introducing in master.

**Comment by ddeboer** [comment]
To help the general understanding (including mine): 

```
HTTP request 
    ↓
Cowboy (HTTP server)
    ↓
```

**Comment by ddeboer** [comment]
To help the general understanding (including mine):

```       
HTTP request  → Cowboy             → z_sites_dispatcher
(handled by)    (calls middleware)   (returns Zotonic controller fun to Cowboy)
                                   ←
                (calls middleware) → cowmachine
                                     (returns controller response to Cowboy)
                                   ←
HTTP response ← 
(served by)
                                                            
```
