### ISSUE TITLE
Language and search (tsvector)

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#553]
We have a problem with searching text across languages.

The `tsvector` is calculated using the actual language of a text.
This give a problem when we are searching that text from another language.

This might show the problem directly:

    (zotonic009prod@miffy)17> iolist_to_binary(mod_search:to_tsquery("monique den boer", z_context:set_language(nl, z:c(maxclass)))).
    <<"monique & den & boer:*">>
    (zotonic009prod@miffy)18> iolist_to_binary(mod_search:to_tsquery("monique den boer", z_context:set_language(en, z:c(maxclass)))).
    <<"moniqu & den & boer:*">>

Depending on the mix of the indexing language and the search language we will find `Monique` or not.

I propose to index and search all texts using the default language of the system.

**Comment by ddeboer** [comment]
What is the path forward here? Concentrate on using dedicated search solutions, such as Solr and [Elasticsearch](https://github.com/driebit/mod_elasticsearch) for full-text search or do we want to fix this in Zotonic itself, too?

**Comment by mworrell** [comment]
We are uncertain about the "fix".

Definitely not require any external search engines.

I propose to index & search all texts in the default language of the site. If the default language changes then the texts need to be pivoted again.

**Comment by ddeboer** [comment]
Why not index in all content languages that are being used?

**Comment by mworrell** [comment]
@ddeboer Because we have sites with 10+ languages...  And then we have to index all N languages in N variations.

**Comment by ddeboer** [comment]
But isn’t that only a problem of data storage size? When searching, we could limit the index that is consulted to the searcher’s current language so performance suffers as little as possible.

**Comment by mworrell** [comment]
Not just data storage.  You need more tables and also joins to the full text index tables, so performance would suffer.  And of course pivoting will be much slower, with the increased number of pivot tables.
