### ISSUE TITLE
Problem with comet on iOS.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#570]
Comet on iOS has a problem. Calling $.ajax _before_ the document is loading will cause problems. The document stays on loading. Data will be received. The problem is that some parts of the api of the document will not be functional so things silently fail.

This will happen when websocket connections are switched to the fallback comet mechanism.

The fix is to wait with calling $.ajax until the document is fully loaded.

**Comment by mworrell** [comment]
Is still an issue with the new transport

**Comment by mmzeeman** [comment]
The main problem is that iOS can’t reliably do long-polling. That is important, because in some cases you need a fallback mechanism.

I’m not sure what the right solution is for this right now. Maybe we have to start long-polling in a web-worker on iOS.

**Comment by mworrell** [comment]
A web worker adds some interesting complexity. Is this compatible with other browsers?

**Comment by mmzeeman** [comment]
It probably will only work with newer browsers. To me it sounded like a new can of worms, so I’m applying the ostrich algorithm for now.
