### ISSUE TITLE
documentation error: rebar dependency not mentioned for installation usign deb package

### ISSUE THREAD

**Issue by arifishaq** [zotonic/zotonic#573]
In the installation instruction page:
http://zotonic.com/docs/0.9/tutorials/install.html
package installation does not start the server as the init script has a dependency on rebar
It would be useful (not putting off first time installers :)) to mention that you need rebar installed.
Best regards

**Comment by ddeboer** [comment]
Fixed: Zotonic now starts even if rebar(3) is not installed. For the initial compilation, of course, rebar3 is still required.
