### ISSUE TITLE
Zotonic z_notifier_tests.erl fails on detach_all_test 

### ISSUE THREAD

**Issue by vdoov** [zotonic/zotonic#592]
Based on the tests result for z_notifier I assume that z_notifier:detach_all/2 does not work in zotonic 0.9.2
Simple test like this one: 

z_notifier:detach_all(test_blaat, Context),
?assertEqual([], z_notifier:get_observers(test_blaat, Context)).

fails with:
**error:{assertEqual_failed,[{module,z_notifier_tests},
                     {line,39},
                     {expression,"z_notifier : get_observers ( test_blaat , Context )"},
                     {expected,[]},
                     {value,[{500,{z_notifier_tests,observer1}},
                             {500,{z_notifier_tests,observer2}}]}]}

**Comment by ddeboer** [comment]
This issues was filed some time ago, and it seems in the meantime this test started working again, both on master and 0.x :wink:
