### ISSUE TITLE
Survey bug

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#595]
I made the follwoing Survey
http://zotonic.com/admin/edit/1035 (broken)

and 
http://zotonic.com/admin/edit/1035 

Issues
The results button does nothing (can we take it away?)

![image](https://f.cloud.github.com/assets/1306897/782920/d00e64b4-ea43-11e2-83fd-6cac0e8f0f28.png)

And also the first survey broke after I removed a question and added one.

**Comment by mworrell** [comment]
This might have been a problem that is now fixed (we did some fixes for the prep_answers when there were multiple questions with the same name)
