### ISSUE TITLE
Refactor stats collection to use exometer instead of folsom

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#596]
When we add data sources of our internal Stats available to Panic Statusboard then we could have a nice visual display of stats from multiple sites/systems at one glance.

See: http://panic.com/statusboard/

**Comment by ddeboer** [comment]
@mworrell We’re now using exometer and we have a [doc chapter](http://docs.zotonic.com/en/latest/cookbook/exometer.html) on it. Anything else that needs to be done here, or can we close this issue?

**Comment by mworrell** [comment]
Sounds good, closing.
