### ISSUE TITLE
Add parameters to translation strings

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#608]
From another project I am used to write

```
maketext( 'Page [_1] has been updated', $pageName )
```

and in the po file:

```
msgid "Page %1 has been updated"
```

I am surprised this is not common in Erlang translations - the translation framework that Zotonic uses does not mention parameters. Still the benefit is obvious I think. You just cannot concatenate 2 translated strings and hope for the best.

**Comment by mworrell** [comment]
In https://github.com/zotonic/zotonic/issues/858#issuecomment-75670148 @ArthurClemens tested the `mochifmt` module. It seems to be able to do what we need.

I propose to:

1. Make some preprocessor, so that we don't need to parse the pattern for every invocation
2. Check if we can let it operate in binary mode
3. Define the exact format (filter?)

Re 3. We could make a filter:

```
   _"hello {name_first} your id is {id} "|maketext:id
   _"hello {name_first} your id is {id} "|maketext:{args name_first=... id=...}
```

Or add a special construct?

```
   {{{ _"hello {name_first} your id is {id} "  id=... name_first=... }}}
```

**Comment by ArthurClemens** [comment]
Note that translations in Erlang code can be updated too.

**Comment by mworrell** [comment]
In erlang we could use direct callbacks to our own interface functions.

**Comment by arjan** [comment]
We could also implement it like the original Erlydtl does, using `trans` and `blocktrans` tags.
https://github.com/erlydtl/erlydtl#render2

That way we stay more close to Django DTL.

**Comment by mworrell** [comment]
Yes, we could use `{% blocktrans ... %} ... {% plural %} ... {% endblocktrans %}`

It is powerful, but also harder to implement as there can be DTL instructions inside the blocktrans. That means that we have to compile all possible strings and then generate switches to select the correct translation-specific render function.

Do we want that?

**Comment by ArthurClemens** [comment]
This is an overly simplistic handling of plurals. Some languages have more than 1 plural form.

**Comment by mworrell** [comment]
And of course the male/female form...  maybe better to split it out with if statements.

I now see that the blocktrans is part of ErlyDTL - we could have a look at that implementation and see if it is compatible with the Zotonic translation lookups.

**Comment by mworrell** [comment]
*Note:* I and @mmzeeman are thinking of compiling to something else than Erlang code, as loading the code on a hot machine can be too much overhead for the machine. And most time (by far) is spent on generating the code and loading the code. Parsing and intermediate form construction is a very minor part of the template compilation.

**Comment by mworrell** [comment]
BTW I dislike the `{% trans ... %}` tags because basically *all* strings in a template are translatable, this makes the templates less readable then our `{_ ... _}` and `_"..."` constructs.

**Comment by mmzeeman** [comment]
Personally I think positional formatting is good enough. It is less error prone for translators because you can't misspell the {names} in the string, and it is also easier to implement. 

Does erlang's gettext allow for adding comments to the translatable strings? If so, that could be used to clarify what $1 means.

Another thing which is needed if you want a complete solution is handling numbers following the locale.

In the past I wrote Qt Gui's and we translated the gui in 10 different languages. Qt has its own internationalization api which was quite pragmatic and worked really well in practice. Maybe we could borrow something there too.

**Comment by mworrell** [comment]
I like the names, because it would make it possible to pass a resource id or a property list (dict/map) for the replacement values.

Do you have references to the Qt translation API?  If it works well, then we should at least consider it. I prefer a good solution, but only if it is significantly better than the compatible one.

**Comment by mmzeeman** [comment]
```c++

c++; // alert
```

http://qt-project.org/doc/qt-4.8/internationalization.html

**Comment by ArthurClemens** [comment]
@mmzeeman "handling numbers following the locale" - do you mean plural numbers? This is from the gettext documentation:

```
msgid "One file removed"
msgid_plural "%d files removed"
msgstr[0] "%d slika je uklonjena"
msgstr[1] "%d datoteke uklonjenih"
msgstr[2] "%d slika uklonjenih"
```

po files include a formula for each language:

```
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"
```

This can be parsed by most languages. I don't know if the erlang version uses it.
This syntax is not the end solution for translators, because they would have to know/remember what the numbers mean. But a translator UI could help out there.

**Comment by mmzeeman** [comment]
No, like formatting numbers with , or . Like 3,95 or 3.95.

**Comment by mworrell** [comment]
Good one. We should be able to have good number formatting. Some Europeans appreciate their ',' :)

We also use translatable date formats in MaxClass/LearningStone for that category of problems, so that in 'en' we have AM/PM and in other languages 24 hour date format.

**Comment by mworrell** [comment]
@ArthurClemens good information. Scanning through that qt page I get the impression that the formula per language are static.

How is the .po editor support for this singular/paucal/plural ?  Or (strange thought) can the Qt translator be used for the .po files?  (Or can we actually scan the Qt output?)
I think it might be a tad hard for people to know the three forms for each language, without good editor support.

**Comment by mmzeeman** [comment]
And indeed some languages, for example Polish, have quite complex pluralisation. Qt does this with an extra parameter added to the tr method.

Some pointers to the Qt documentation relevant for internationalisation.

http://doc.qt.io/qt-5/i18n-source-translation.html

http://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals

**Comment by mmzeeman** [comment]
Qt's format translator template format is entirely different.

**Comment by mworrell** [comment]
Reading here I see that the translation files are XML files: http://qt-project.org/doc/qt-4.8/internationalization.html#produce-translations

That should be parseable for Erlang.

**Comment by ArthurClemens** [comment]
Yes, the formula per language is static.

The list that I have used is http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms.

The human readable version (without the formulas) is https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals.

I have used this wording in the UI of my translation website. For example the Polish translators sees 3 input fields:

* is 1
* ends in 2-4, excluding 12-14
* everything else

This then gets written to a po file as:

```
some_key[0]
some_key[1]
some_key[2]
```

**Comment by mworrell** [comment]
Translation website?  We were just looking at https://crowdin.com which might make it easier to engage people in helping to translate. See also issue #217

**Comment by ArthurClemens** [comment]
My product is for 1 client currently, but I can make it work as general app, especially for people that are used to Zotonic. I am working on a new interface to allow creating and editing without Zotonic admin, but it will take a while. 

Features:

* Screen based editing: upload a screenshot and add numbers to the image so translators learn the context. This is optional but helpful.
* Plural forms (explained above).
* Max number of chars
* Handling of spaces in French (they write a space between last word and exclamation mark)
* Plain text, rich text
* Handling of URLs (URLs in rich text get resolved, so an update will automatically update the URL in the rich text)
* URL parts
* Warnings about missing periods, exclamation marks or placeholders
* Statistics
* Export to gettext, strings, json, txt, pdf

Caveats:

* Placeholder support: currently only generic ``%@``, I would need to work on `{num} or ``{var}` placeholders.
* Handling of duplicate keys could be better.
* Currently no social options such as suggestions.

**Comment by mworrell** [comment]
@ArthurClemens sounds like an almost complete translation system, very impressive!

**Comment by ArthurClemens** [comment]
## Requirements

### Plural forms

The po file contains a line:
```
"Plural-Forms: nplurals=1; plural=0;"
```
or
```
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;"
```

Part 2 of the line calculates the index of the string. Example of po strings with indices:

```
msgid "One file removed"
msgid_plural "%d files removed"
msgstr[0] "%d slika je uklonjena"
msgstr[1] "%d datoteke uklonjenih"
msgstr[2] "%d slika uklonjenih"
```

Obviously translators need some hint what the indices refer to (how to translate which index) but that is another feature.

The plural form is retrieved with `ngettext`:

```
printf (ngettext ("%2$d file removed from directory %1$s",
    "%2$d files removed from directory %1$s",
n), dir, n);
```

**Comment by ddeboer** [comment]
@ArthurClemens Can you start work on the changes that we need in gettext?

**Comment by ArthurClemens** [comment]
Library to check out: https://github.com/seriyps/gettexter

**Comment by ddeboer** [comment]
We can use that one, but it’s not very active. Do we need many changes in Zotonic’s current gettext implementation? Perhaps it’s easier to just do that.

**Comment by mworrell** [comment]
The template parameters are added to the new template_compiler, which is used in the master zotonic/template_compiler@f5c8e18

An example can be seen here: https://github.com/zotonic/template_compiler/blob/master/test/test-data/trans.tpl

```django
{% trans "Hello {foo} Bye" foo=v %}
```


Plurals were not added yet, I think that is why this ticket is still op.

**Comment by mworrell** [comment]
The above comments need to be moved to the documentation.

**Comment by mworrell** [comment]
Moved the plurals to a new issue #2171

**Comment by mworrell** [comment]
This has been documented in the master:

http://docs.zotonic.com/en/latest/developer-guide/translation.html#translation-sources
