### ISSUE TITLE
Cannot remove Zotonic installation

### ISSUE THREAD

**Issue by mesr** [zotonic/zotonic#680]
Under Ubuntu 12.04LTS, using either 'sudo apt-get remove zotonic' or 'sudo apt-get purge zotonic' or even 'sudo dpkg --force-all -P zotonic' always return the following errors, whether the server is already running or not:

Removing zotonic ...
erl_call: failed to connect to node zotonic001@dromadaire
Zotonic is not running. You need to start Zotonic first to use this command.

invoke-rc.d: initscript zotonic, action "stop" failed.
dpkg: error processing zotonic (--remove):
 subprocess installed pre-removal script returned error exit status 1
Starting Zotonic zotonic001@dromadaire
Errors were encountered while processing:
 zotonic
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by mworrell** [comment]
@arjan can this be closed or does it need some work?

**Comment by chumpalump** [comment]
The pre remove script still fails, but it's easy to hotwire to pass.  So, it's still an issue, but it's not in my way.

**Comment by mworrell** [comment]
Thanks @chumpalump for the feedback.  @arjan is it possible to fix, or out of our control?

**Comment by mworrell** [comment]
@arjan do we still support the packages?

**Comment by ddeboer** [comment]
We no longer maintain the Debian/Ubuntu packages. Please use [our Docker containers](http://docs.zotonic.com/en/latest/developer-guide/docker.html) instead.

**Comment by mworrell** [comment]
Can we remove those packages?

**Comment by ddeboer** [comment]
That should be done at https://github.com/zotonic/deb

**Comment by mworrell** [comment]
Added a note on top of the deb readme
