### ISSUE TITLE
_js_include.tpl adds bootstrap.js, conflicts with bootstrap-3 js

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#696]
Adding bootstrap 3 to a site is not plug and play, even if you add the files "manually":

{% lib
    "bootstrap-3/js/bootstrap.js"
%}

(CSS has a separate issue that it cannot be combined in one lib statement with other css files)

Problem is that bootstrap is included by default templates. For instance in phone/_js_include.tpl. From frontend perspective, removing that 1 line basically means copying that file to the site templates folder and delete the line from the local copy.

I think that the underlying libraries should be decoupled more. Or it should read a config setting which version to use.

**Comment by mworrell** [comment]
0.12 and later is now bs3
