### ISSUE TITLE
mod_ssl can overwrite previously created private key 

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#705]
During an installation of a new server I accidentally overwritten the private key. Big oops..

It goes wrong if you do this.
1. Run `openssl req -out sitename.csr -new -newkey rsa:2048 -nodes -keyout sitename.key`
2. Send csr to your ca
3. Start mod_ssl  **this step silently overwrites the `sitename.key`**
4. Install certificate
5. Pull out hair, if you have any :-p

**Comment by mworrell** [comment]
Maybe add a special directory for all SSL keys?
The self-signed key should be named differently from all other keys.
In fact, we could have a single self-signed key in a directory like `~/.zotonic/ssl/` and use that one across all sites (including zotonic_status)

**Comment by mworrell** [comment]
Splitting the `#ssl_options{}` handling for the keys over mod_ssl and mod_ssl_self_signed. They will have their own keys in the site's ssl directory.

**Comment by mworrell** [comment]
Adding:

 * `ssl/self-signed/...` directory for self-signed keys
 * `ssl/<hostname/...` directory for special certs per hostname
 * `priv/ssl/self-signed/...` directory with self-signed keys for zotonic_status and requests without host name

**Comment by mworrell** [comment]
#1502 fixes this
