### ISSUE TITLE
mod_ssl listeners are not stopped when module is stopped.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#706]
The ssl listener keep running when you stop/restart mod_ssl, so new certificates are only picked up after a restart of the site.

**Comment by mworrell** [comment]
I propose to redo some of the supervisor structure, as I think that the listeners are not supervised correctly.

**Comment by mworrell** [comment]
For the 1.0: move mod_ssl into the core and always start a listener using SNI of Erlang 18

**Comment by mmzeeman** [comment]
SSL has now moved into the core, the listeners are supervised.
