### ISSUE TITLE
Mod mailinglist error

### ISSUE THREAD

**Issue by 6aKa** [zotonic/zotonic#733]
<pre>
02:47:57.483 [info] [basesite_home] info @ z_datamodel:161  Creating new mailinglist 'mailinglist_test'

02:47:57.690 [error] z_db error {error,error,{integrity_constraint_violation,unique_violation},<<"duplicate key value violates unique constraint \"pg_type_typname_nsp_index\"">>,[{detail,<<"Key (typname, typnamespace)=(mailinglist_recipient_id_seq, 2200) already exists.">>}]} in query "\n        \t\t\t\tCREATE TABLE mailinglist_recipient (\n        \t\t\t\t\tid serial NOT NULL,\n        \t\t\t\t\tmailinglist_id INT NOT NULL,\n        \t\t\t\t\temail character varying (200) NOT NULL,\n        \t\t\t\t\tis_enabled boolean NOT NULL default true,\n                            is_bounced boolean NOT NULL default false,\n        \t\t\t\t\tprops bytea,\n        \t\t\t\t\tconfirm_key character varying (32) NOT NULL,\n        \t\t\t\t\ttimestamp timestamp with time zone NOT NULL DEFAULT now(),\n\n        \t\t\t\t\tCONSTRAINT mailinglist_recipient_pkey PRIMARY KEY (id),\n        \t\t\t\t\tCONSTRAINT mailinglist_recipient_mailinglist_id_email_key UNIQUE (mailinglist_id, email),\n        \t\t\t        CONSTRAINT confirm_key_key UNIQUE (confirm_key),\n        \t\t\t\t\tCONSTRAINT fk_mailinglist_id FOREIGN KEY (mailinglist_id)\n        \t\t\t\t      REFERENCES rsc (id)\n        \t\t\t\t      ON UPDATE CASCADE ON DELETE CASCADE\n        \t\t\t\t)" with []
02:47:57.710 [error] z_module_manager:571 [basesite_home] Error starting module mod_mailinglist, Schema initialization error:
{'EXIT',{{badmatch,{rollback,{{error,{error,error,{integrity_constraint_violation,unique_violation},<<"duplicate key value violates unique constraint \"pg_type_typname_nsp_index\"">>,[{detail,<<"Key (typname, typnamespace)=(mailinglist_recipient_id_seq, 2200) already exists.">>}]}},[{z_db,'-q/4-fun-1-',4,[{file,"src/dbdrivers/postgresql/z_db.erl"},{line,285}]},{timer,tc,2,[{file,"timer.erl"},{line,179}]},{z_stats,timed_update,4,[{file,"src/support/z_stats.erl"},{line,81}]},{z_db,with_connection,3,[{file,"src/dbdrivers/postgresql/z_db.erl"},{line,199}]},{mod_mailinglist_schema,manage_schema,2,[{file,"modules/mod_mailinglist/support/mod_mailinglist_schema.erl"},{line,63}]},{z_module_manager,'-manage_schema/4-fun-0-',4,[{file,"src/support/z_module_manager.erl"},{line,709}]},{z_db,transaction1,2,[{file,"src/dbdrivers/postgresql/z_db.erl"},{line,128}]},{z_db,transaction,3,[{file,"src/dbdrivers/postgresql/z_db.erl"},{line,83}]}]}}},[{z_module_manager,manage_schema,4,[{file,"src/support/z_module_manager.erl"},{line,717}]},{z_module_manager,'-start_child/5-fun-0-',5,[{file,"src/support/z_module_manager.erl"},{line,566}]}]}}
</pre>

**Comment by mworrell** [comment]
Looks like this was a problem with multiple sites on a single db schema.

Closing for now.
