### ISSUE TITLE
A search is limited to 1000 results because that is the default page size

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#745]
On a site with more than 1000 text pages:

```
count = {{ m.search[{query cat='text'}]|length }}
```

Count will always be 1000.

Reason: in `m_search:get_optional_paging_props` the page size is set to 1000 if it has not been set.

Solution: set page params to undefined so do a search without a page limit.

**Comment by mworrell** [comment]
We are now estimating the total number of rows in queries.
