### ISSUE TITLE
Document how models work

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#748]
Currently there is a big TODO in the models documentation,

"Write how to implement a model and how the `m_find...` functions work"

It would be nice to have this documented properly, as it is the basis of Zotonic's data retrieval mechanism.

When this is done, we can also fix #517.

**Comment by ddeboer** [comment]
By looking at http://zotonic.com/docs/latest/manuals/templates/models.html#implementing-your-own-model, it seems this has been solved in the meantime. @arjan Or would you still like a more elaborate explanation of `m_find...`?
