### ISSUE TITLE
z_media_preview sets a default image quality of 50, overriding quality setting in {magick ...} instruction

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#756]
If I have a mediaclass entry:

```
{"1col", [
   {magick, "-quality 92 -resize 276x276"}
]}
```

Zotonic will produce an image with JPEG quality 50.
`z_media_preview` sets a default quality for smaller image sizes, but ignores the fact that the quality is already set. 

I think that z_media_preview should set no defaults at all if {magick} is used, because that is the responsibility of the user.

**Comment by mworrell** [comment]
Closing	due to inactivity. I think the quality flag should be used.
