### ISSUE TITLE
Installation with the one-line script for Debian-based systems fails

### ISSUE THREAD

**Issue by mch0lic** [zotonic/zotonic#761]
Installation with the one-line script for Debian-based systems fails with Ubuntu 12.04 and Ubuntu 14.04.

The main issue is that install script not specifying software versions to be installed and then assumptions are being made of what was installed, for example, updating config postgresql-8.4 while `apt-get install postgresql` install postgresql-9.x

**Comment by ddeboer** [comment]
The one-liner has been removed. We now provide [Docker images](http://zotonic.com/docs/latest/developer-guide/docker.html) instead.
