### ISSUE TITLE
Comet controller & push connections

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#762]
The comet controller can create new users sessions if the original users session timed out or something else has happened to it.

The comet controller will then be attached to a newly created session and page process then the original page was rendered with. 

This can lead to all sorts of subtle problems.

The controller should respond with a 403, and the stream code in zotonic.js should handle that response. Currently zotonic.js retries to setup a comet connection every second, which can potentially generate millions of requests. (tried that in practice :p)

What should happen when the stream code notices the ```{% stream %}``` is no longer working?

**Comment by mworrell** [comment]
This has been fixed in the new transport,
