### ISSUE TITLE
Annoying warning about missing 'page' dispatch rule

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#765]
I have a site without a frontend. It does not needs the `page` dispatch rule... what do we do about it?

![image](https://cloud.githubusercontent.com/assets/24722/3064043/1737b8e4-e24c-11e3-87ef-6f41e89f6d06.png)

**Comment by mworrell** [comment]
@arjan that could be done :)

**Comment by mworrell** [comment]
@arjan what to do with this issue? I concur with @kaos about users being very confused for this missing rule.  An option for you could be to add some css to your site to remove the vie button?

**Comment by mworrell** [comment]
Closed due to inactivity
