### ISSUE TITLE
Database name cannot be specified in config

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#769]
Each site has a `dbdatabase` config entry. This entry is missing, however, from the generic Zotonic config (`zotonic/priv/config` and `zotonic/priv/config.in`). 

When I have [multiple sites using one database](http://zotonic.com/docs/0.9/manuals/site-anatomy.html#tip-multiple-sites-using-one-database) it makes sense to configure the database name only once, in the generic config, and not in each site config separately. Is `dbdatabase` missing from the generic config on purpose? If not, can it be added?

**Comment by mworrell** [comment]
I like the idea of @kaos about defaulting the schema name to the site name.
Anyone objecting?

@arjan @mmzeeman

**Comment by arjan** [comment]
:+1:, should be easy now that #838 is implemented

**Comment by ddeboer** [comment]
Actually, we moved away from sharing a database between sites and now have each site in its own database. So changing the current default for `schema` (public) to something else would require us to add an extra param in the site config. 

What about adding some convention? If `dbdatabase` is set globally, default `schema` to site name. If not set, default `schema` to `public` (as is currently the case). Or does this get too confusing?

**Comment by mworrell** [comment]
So:

 * if site database is the default configured, then default schema is site name.
 * if site database is custom, then schema is public

Makes sense, actually.

**Comment by ddeboer** [comment]
Exactly!

**Comment by arjan** [comment]
Although this behaviour can seem unpredictable, so it could benefit from being well documented :)

**Comment by mworrell** [comment]
I want to modify the install scripts - so that they *do* show the defaults.  Now they show the wrong ones.

Maybe it is best to redo them in Erlang, then we can also use them from the web ui.

**Comment by mworrell** [comment]
To be done in addsite script and zotonic status add-site handling code:

 * If database == default database then schema defaults to `sitename`
 * If database != default database then schema defaults to `public`

**Comment by mworrell** [comment]
@arjan @ddeboer do we still want this behavior?

**Comment by mworrell** [comment]
To be resolved in issue #2199
