### ISSUE TITLE
Share / re-use compiled templates between sites / restarts

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#772]
Compiled templates vary with:

 * site
 * language / selected texts
 * selected user-agent class (desktop, phone etc)

On compilation these are combined to make different template modules.
If we flush the caching system, reload translations, change modules then we invalidate all compiled templates.

On closer look we can see that in fact:

 * templates between sites are often the same (think admin and base modules)
 * reloading translations only changes a minority of the texts
 * enabling/disabling modules often don't have influence on templates
 * flushing caches doesn't change the template (-selection)

It would be quite an optimization if we can combine compiled templates if they are not changed or are the same as another compiled template.

(compiling and loading the new tpl in the beam-vm is what takes the most time).

I propose that we do something like:

 * after parsing calculate a checksum
 * see if there is a loaded template module with that checksum, use that one if found
 * have some mechanism to purge templates if they are invalidated/unused.

For this we need to change the administration in the template modules, which now includes a reset-counter for syncing with the flush or re-load mechanisms.

/cc @kaos @mmzeeman

**Comment by mworrell** [comment]
Fixed with the new template compiler.

(Except for hard restarts - then we need to save the beams to disk)

**Comment by heiheshang** [comment]
templates in modules are not indexed
after restarting only sees pattern
1.0-dev
