### ISSUE TITLE
Already started crash with comet.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#824]
12:24:02.612 [error] CRASH REPORT Process <0.31199.7> with 1 neighbours exited with reason: no match of right hand value {error,{already_started,<0.31207.7>}} in z_session:page_start/2 line 617 in gen_server:terminate/6 line 747
12:24:02.612 [error] webmachine error: path="/comet": {exit,{{{badmatch,{error,{already_started,<0.31207.7>}}},[{z_session,page_start,2,[{file,"src/support/z_session.erl"},{line,617}]},{z_session,handle_call,3,[{file,"src/support/z_session.erl"},{line,443}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,588}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},{gen_server,call,[<0.31199.7>,{ensure_page_session,<<"BlHjrlkd9WCE55yVnMby">>}]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,180}]},{z_session,ensure_page_session,1,[{file,"src/support/z_session.erl"},{line,221}]},{controller_comet,forbidden,2,[{file,"modules/mod_base/controllers/controller_comet.erl"},{line,54}]},{webmachine_controller,controller_call,3,[{file,"src/webmachine_controller.erl"},{line,209}]},{webmachine_decision_core,decision,3,[{file,"src/webmachine_decision_core.erl"},{line,206}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,31}]},{webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,107}]},{mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,102}]}]}

**Comment by mworrell** [comment]
Didn't see this happen again, still an issue?

**Comment by mmzeeman** [comment]
No, me neither.
