### ISSUE TITLE
mod_oembed: supervise the oembed_client process

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#828]
The `oembed_client` is not supervised, only linked to the module.
The dummy module gen_server traps exits so that it can unsubscribe from events, so crashes of the `oembed_client` go unnoticed.

I am wondering what the best strategy is:

 1. Make mod_oembed into a supervisor; or
 2. Add a more generic process worker pool, where processes can also be linked to modules.

I am leaning to (2) as more modules will have the same problem.

**Comment by ddeboer** [comment]
@mworrell You refactored the oembed client in https://github.com/zotonic/zotonic/pull/1435/. If that has fixed this issue, please close this.
