### ISSUE TITLE
It seems that there is no supporting pivot_tsv in Unicode Languages except ASCII English

### ISSUE THREAD

**Issue by witeman** [zotonic/zotonic#846]
We want to use the full text search function of mod_search for Chinese, but we found that there isn't working. And I found that there is no Chinese Word Segmentation in pivot_tsv column, but when I typed some English article, there do be some English Word Segmentation in that column.  Is there some doc about this? Or some hinted procedures to turn it into multi-language mode of full text search?

I guess it is due to the word segmentation engine only support for english?

**Comment by mworrell** [comment]
This is tracked at #553
