### ISSUE TITLE
mod_acl_simple_role permission problem

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#852]
I created a role and crossed all possible rights, attached a user to it.

Now, this user is allowed to create Person/users, but when I click on

Auth->Users->Make a New user

I get the message: "Only administrators can add users".

How can I give the admin right to all members of this role?

**Comment by ddeboer** [comment]
Is this still an issue?

If so, please report it at https://github.com/zotonic/mod_acl_simple_roles, as mod_acl_simple_roles has been removed from the Zotonic core. If possible, migrate to mod_acl_user_groups instead.
