### ISSUE TITLE
Admin: Modal dialog should not be closed with click on background

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#854]
With the admin dialogs  it is easy to accidentally hit the background. Dialog closes and work has to be redone.

**Comment by ArthurClemens** [comment]
For preventing backdrop click it is simply a matter of setting `backdrop` to `static`.
Closing using ESC should work in bootstrap but doesn't. It seems that the key event is captured and not passed. Perhaps by a conflicting ui library?

**Comment by mworrell** [comment]
The backdrop can now be set to `static` preventing accidental close of dialogs.
