### ISSUE TITLE
Dialog "session expired" has confusing message

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#867]
"Your session has expired or is invalid. Reload the page to continue."

Then on reload I must sign in again. Why not present sign in immediately? (with the message "Sign in again to continue")

**Comment by ArthurClemens** [comment]
I see this all the time at milledoni.nl, but this site is still on 0.12, and perhaps the server connection was changed. Or we removed that unknowingly from our templates.

**Comment by mworrell** [comment]
Strange - I don't see it on MaxClass / LearningStone, which are running the 0.11.x branch (which is quite similar).

We did make some changes to reload browsers which don't have a valid session. Those changes were not merged into the 0.12 - afaik.

**Comment by ArthurClemens** [comment]
I don't see the message anymore unless Zotonic has been restarted.
