### ISSUE TITLE
Add option to "compile all" from Status page

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#870]
I was trying to add a new module and it would not start. Doing "Rescan modules" did not have any effect. In the end I had to open a zotonic shell and do `z:m()`. Would be easier to have this in the web interface.

**Comment by ddeboer** [comment]
We now have the ‘Rebuild all’ button. Does that solve your problem?

**Comment by ddeboer** [comment]
Closing due to lack of feedback. Please re-open if you still encounter the issue.
