### ISSUE TITLE
Admin overview: optional category-specific column

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#886]
I am quite happy with my admin overviews for a specific category: the category column is replaced with a custom piece of info that helps to distinguish the pages.

These are some examples:
![admin-column-specific-1](https://cloud.githubusercontent.com/assets/350303/5325485/ca71e96c-7cec-11e4-8677-66866cb6596e.png)

![admin-column-specific-2](https://cloud.githubusercontent.com/assets/350303/5325486/ca937226-7cec-11e4-9a0d-07d6bc2c345d.png)

![admin-column-specific-3](https://cloud.githubusercontent.com/assets/350303/5325487/ca954ad8-7cec-11e4-8d9a-9a05b8bfc29d.png)

Changes to `_admin_overview_list.tpl`:
* `catinclude` in header second column: new template `_admin_sort_header.tpl`
* conditional `catinclude` in rows second column: new template `_admin_overview_list_specific.tpl` (conditional so that when viewing "all categories", the overview does not turn into chaos)

**Comment by mworrell** [comment]
:+1:
