### ISSUE TITLE
mod_comment does not update page when first comment is posted

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#887]
Hi!

I'm using mod_comment for a project and there is this strange thing happening. When there ar no comments yet on the page and you add the first one nothing happens. It's like nothing happens. When i refresh i see the comment displayed. If i add another comment it shows up without a refresh. 

~ Dorien

**Comment by mworrell** [comment]
Duplicate issue #660

**Comment by mworrell** [comment]
@DorienD is this still an issue?

**Comment by mworrell** [comment]
Looking at the code it is still an issue.
