### ISSUE TITLE
Name fields strange responsive behavior

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#903]
The labels and the input fields are in seperate divs. Would be better if a label and an input field would be in the same div (with the right column classes).

![screen shot 2015-01-09 at 16 39 36](https://cloud.githubusercontent.com/assets/5102362/5682164/4d3296de-981e-11e4-8240-20013c734ecd.png)

**Comment by ArthurClemens** [comment]
Which version of Zotonic are you using?

**Comment by DorienD** [comment]
0.12.3

**Comment by ArthurClemens** [comment]
Weird. This is how it should look like:

![person-fields](https://cloud.githubusercontent.com/assets/350303/5719619/51c8a8f6-9b1a-11e4-8839-8270f188a3b5.png)

Did you find this in the Admin, edit Person page?

**Comment by mworrell** [comment]
I think the problem is if we make the screen smaller that then the fields are below each other?

**Comment by ArthurClemens** [comment]
Yes, I see it now. Will work on it.
