### ISSUE TITLE
ubf.js requires jQuery

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#908]
For a lean JS based app, jQuery is overhead I would like to do without. As per documentation, `lib/js/modules/ubf.js` must be included in the template, but this causes the error `Can't find variable: jQuery`.

I think that all jQuery calls can be replaced by native versions:
- `$.each` becomes `array.forEach`
- `$.isArray` becomes `Array.isArray(arr);`
- `$.keys` becomes `Object.keys(obj)`

@mmzeeman ?

**Comment by mworrell** [comment]
Totally agree. Is there an overview of these equivalents?
We might also remove quite a bit from the other js files.

**Comment by ArthurClemens** [comment]
* From (most) jQuery to vanilla: http://youmightnotneedjquery.com
* For a complete overview of functions: https://developer.mozilla.org/en-US/docs/Web/JavaScript

**Comment by mmzeeman** [comment]
Indeed, but I need to check things carefully as I need still need to support IE8.

**Comment by ArthurClemens** [comment]
If you need to use polyfills, they should be added separately (to be included by devs if needed).

@mworrell zotonic.js has a large number of jquery references. Refactoring would be easier if the file was split and had unit tests...

**Comment by mworrell** [comment]
Yes that .js file has grown considerable over the years.
Maybe we can use the lightweight js-loader that @mmzeeman is using and cut it into pieces.

**Comment by ddeboer** [comment]
What about dropping IE 8 (and 9) support for 1.0? It would allow us to clean up the JS big time.

**Comment by mmzeeman** [comment]
We have to check the stats.

**Comment by mmzeeman** [comment]
One of our corporate clients is moving from IE8 to IE10 in the coming months.

**Comment by ddeboer** [comment]
:fireworks:

**Comment by mmzeeman** [comment]
The shim module inserts this in the head. Works pretty nicely I must say.

<meta http-equiv="X-UA-Compatible" content="IE=edge">


We could probably add shims for IE < 10 without much hassle.

**Comment by mworrell** [comment]
:+1:

**Comment by mmzeeman** [comment]
Then we use that... We can emded an include all so you can embed custom shims if needed. The json we embed is custom, and not needed for core zotonic. *Note: we need it for a postMessage api. IE 8 doesn't support sending serialisable objects. in that case we send things as json strings*

**Comment by ddeboer** [comment]
What about postponing the removal of JQuery until after 1.0 and after we’ve introduced the components (which will obsolete lots of custom JQuery event handling).

**Comment by mworrell** [comment]
Removed jquery from ubf.js in c8c460b64f70c37f36482ff37a83fc67fa3efd74

Shall we make a separate issue about removing jquery calls from the other js files?

**Comment by mworrell** [comment]
Closed, followup issue is: #1558
