### ISSUE TITLE
dbdriver of postgresql does not support numeric field type.

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#91]
*From http://code.google.com/p/zotonic/issues/detail?id=86*

<b>What steps will reproduce the problem?</b>
1.when field type of postgresql table is numeric, the float type data is 
decode as binary string, not the correct float number.
<b>2.</b>
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>

<b>What version of the product are you using? On what operating system?</b>

<b>Please provide any additional information below.</b>
Code in pgsql_binary.erl is no numeric type support.

**Comment by mworrell** [comment]
Closing, as we are now using vanilla epgsql, if this is still needed the an issue should be files there.
