### ISSUE TITLE
Restructure password reset email

### ISSUE THREAD

**Issue by ArthurClemens** [zotonic/zotonic#914]
The current email is quite long and not enough to the point:

---

subject: How to reset your password

Hello Arthur,

You requested a new password for [tutorial.com](http://tutorial.com). Below are your account details and a link to set a new password.

Your account name is “arthur”. The e-mail address associated with your account is “arthurclemens@gmail.com”.

Click on the link below to enter a new password, when clicking doesn't work then you can copy and paste the complete address to your browser.

http://tutorial.com/en/logon/reset?secret=YAE423h2TeqdyCWXurWx

When you didn't request a password reset, you can ignore this e-mail. Maybe someone made an error typing his or her e-mail address.

Kind regards,

[Tutorial](http://tutorial.com)

---

Suggestion:

---

subject: How to reset your Tutorial  password

To reset your Tutorial password, click this link:

http://tutorial.com/en/logon/reset?secret=YAE423h2TeqdyCWXurWx

If you didn't request a password reset, you can ignore this e-mail. Someone probably made an error typing their e-mail address.

---

**Comment by mworrell** [comment]
I think that with MaxClass we explicitly added the username and email address.

This because some people tend to mix their email in their client and also tend to forget their username (which is needed if your email doesn't work).

CC'ing Michiel for additional comments @michielklonhammer

**Comment by mworrell** [comment]
I agree that the email can be reorganized and some shorter sentences can be used.
Also the 'when' should be a 'if'

**Comment by ArthurClemens** [comment]
Is the username/email a check for the user? In case the user has more usernames?

In that case we could start the email with:

---
You have requested to reset your password for your account “arthur” (e-mail address arthurclemens@gmail.com).
---

**Comment by mworrell** [comment]
Yes, especially at MaxClass we have the possibility to have multiple users with the same email address (think of young children using their parent's email address).

**Comment by michielklonhammer** [comment]
yes, the multiple email architecture was for MaxClass and can be useful. if you do enter the email address for the password -reset, you simply get several mails. It works very well. If you don't want that, you simply verify if the email is new when it's entered. We did that for LearningStone.

I've been writing a lot of text  and use more  straightforward sentences in an active form. So no If... then but the verb first.  I also avoid broken sentences to make translations easier, so the name of the site comes at the end, (it's one string less - and with LearningStone at 2000 strings this counts). and one last thing: avoid U and Je in the Dutch translations of basic zotonic functions as sites vary with which is used.
so....

Click on this link to reset your password for .............

http://tutorial.com/en/logon/reset?secret=YAE423h2TeqdyCWXurWx

Please ignore this e-mail if you weren't expecting it. Someone might have made a mistake.

Kind regards,
Tutorial

**Comment by ArthurClemens** [comment]
"If you don't want that, you simply verify if the email is new when it's entered" - you mean if the programmer does not want that?

Active sentences: yes.

Broken sentences needs a fix with parametric translation strings. 

Why "kind regards" from a thing (site)? I think it can be left out.

**Comment by michielklonhammer** [comment]
Yes, in a lot of cases you should prefer unique emailadresses so you 
just tell the user it's already being used. In some cased like MaxClass 
it's great to be able to use the same emailadres for multiple accounts.
I would love parametric translation strings!
I guess the "kind regards" is a matter of taste, for these basic emails 
it's ok to leave them out. I like the feeling of people behind/in a site 
but for a framework it's ok to choose the most neutral form.

------ Original Message ------

**Comment by mmzeeman** [comment]
People always forget things. Usernames, passwords. But they usually remember their email address. That's why we use email-address =:= username for channel.

Btw, we also want te remove passwords. It happens very often that whole groups start to work with channel again for a specific campaign and the whole group forgot their password. Our main problem is that this are usually persons who are not computer literate and don't have experience with resetting passwords via email. It is just too scary for them to press that button. They see that screen and think "Oops, something is wrong here" and call support!

We are thinking about replace username:password with a login-email with something in it (a link, or some code) that allows them to enter the site. This could also double as an automatic signup facility if you add business rules. (e.g. everybody with an example.com email can signup). That way users can easily start themselves without bothering us too much, and is probably safe enough (I have to research this)

**Comment by ArthurClemens** [comment]
"we also want te remove passwords" - we as Zotonic or as your company?

Having usernames in the sign up screen is adding complexity that is not necessary on lots of sites. As sign up screens are becoming simpler (less typing on mobile), even repeat password is becoming something of the past.
So this should be configurable, or at least easy to override by choosing the right templates. I am working on this in the sign up refactoring.

**Comment by mmzeeman** [comment]
Sorry, our company.

**Comment by mmzeeman** [comment]
Indeed, if you can reset the password with your email you can do without the repeat password field.
