### ISSUE TITLE
Order of results wrong in Survey.

### ISSUE THREAD

**Issue by michielklonhammer** [zotonic/zotonic#915]
Due to LearningStone we've been improving the surveys (for us "forms") but I came across this problem. If you move questions, the order of the results mail stays in the original order so you get things like
Name
Country
Second Name
...while you ment
name
Second name
Country.

--------------
If we fix this and add an intro to the survey, we could also create the option "Send result to respondent"

Bye the way I once noticed that a space in a field label breaks a page jump when you use any type of branching.

**Comment by ddeboer** [comment]
Fixed in 0.11. Needs to be merged into 0.13 and master.
