### ISSUE TITLE
mod_acl_simple_roles: /admin page crashes on role without can_view_all

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#916]
Users of a role without "All members are allowed to view all content. (Check this for supervisors.)"
can't visit the admin "dashboard"

Error message:

@z_webmachine_error_handler:render_error:33 webmachine error: path="/admin": {error,{error,function_clause,[{mod_acl_simple_roles,can_edit1,[undefined,[meta,categorization,collection,location,media,person,artifact,article,organization,mailinglist,other]],[{file,"modules/mod_acl_simple_roles/mod_acl_simple_roles.erl"},{line,296}]},{mod_acl_simple_roles,can_view,2,[{file,"modules/mod_acl_simple_roles/mod_acl_simple_roles.erl"},{line,257}]},{z_notifier,first1,3,[{file,"src/support/z_notifier.erl"},{line,187}]},{z_acl,is_allowed,3,[{file,"src/support/z_acl.erl"},{line,69}]},{template_being_here__desktop_opt_zotonic_modules_mod_admin_templates_admin_tpl,render2,2,[]},{template_being_here__desktop_opt_zotonic_modules_mod_admin_templates_admin_tpl,render,2,[]},{z_template,render1,5,[{file,"src/support/z_template.erl"},{line,115}]},{controller_admin,html,1,[{file,"modules/mod_admin/controllers/controller_admin.erl"},{line,33}]}]}}

**Comment by mworrell** [comment]
In master we have removed this ACL module.

Closing this issue.

Reopen at https://github.com/zotonic/mod_acl_simple_roles if it still an issue.
