### ISSUE TITLE
Automatically delete non-referred items

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#918]
Some resources only exist in the context of other resources. They are created together, and should be deleted if the *leading* resource is deleted.

An example is the profile image of an user. If the user is deleted, their profile images should also be deleted.

I propose to add a flag to the system: `is_dependent` (another term is welcome).

After edge-delete the dependent resources can be checked on incoming edges. If no edges are incoming *and* there is no module reporting any other dependencies, then the resource will be deleted.  (That is if it was not set to *protected*)

@arjan @michielklonhammer

**Comment by mworrell** [comment]
Added support for `is_dependent` to the master branch in https://github.com/zotonic/zotonic/commit/c23d9f1c857a1888ab3e37b5ffda569b616c1a69

**Comment by michielklonhammer** [comment]
Dat is fijn! Dat haalt een zeurend dingetje weg uit mijn gedachten.

------ Original Message ------

**Comment by mworrell** [comment]
Zit geloof ik nog op de master - maar kan het overhalen naar de 0.11.x

**Comment by michielklonhammer** [comment]
ai... zeur zeur :-)

------ Original Message ------

**Comment by ArthurClemens** [comment]
I am having problems wrapping my head around this. In the example of the profile image, which resource should get the tag `is_dependent`?

A description would be useful for the documentation and the admin interface.

**Comment by mworrell** [comment]
The image is dependent on the profile. So the image gets the 'is_dependent' flag.

**Comment by ArthurClemens** [comment]
So `is_dependent` means `delete_this_if_all_referrers_are_deleted`. A kind of garbage collection.
