### ISSUE TITLE
mediaclass: user-defined crop does not work

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#919]

**Comment by ArthurClemens** [comment]
I have seen it work.

**Comment by arjan** [comment]
Yes as long as you specify `crop` in the image tag. The thing is, the coordinates for the crop are generated at the time the image URL is created. And when you use a mediaclass, the crop argument is not part of the URL.

**Comment by mworrell** [comment]
I use crop extensively in mediaclasses. The default is a crop center. How do you specify your now working crop?

**Comment by mworrell** [comment]
Oh, you mean the crop with use specified coordinates as the center?

**Comment by arjan** [comment]
yes, i'll adjust the ticket name

**Comment by ddeboer** [comment]
Confirmed not working as it should. Adding `crop` to `image` in the template *does* work.

**Comment by mworrell** [comment]
As we now also derive the cropping point from the uploaded images (exif), I propose to simplify the crop.

Right now we have crop variations (top, left, right etc), I don't know of any project actually using that. My proposal is to *always* crop using the cropping point, and no other variations.

ok?  /cc @mmzeeman

**Comment by mworrell** [comment]
While on this point, I would like to move the cropping point property to the medium record, as it is really a property of the medium and should change/disappear when a new file is uploaded.

**Comment by ArthurClemens** [comment]
I agree with both.

**Comment by ddeboer** [comment]
:+1:

**Comment by ArthurClemens** [comment]
+1 for fixing this

**Comment by mworrell** [comment]
Also merged into the 0.x
