### ISSUE TITLE
Slow ssl clients can cause very low ssl response times and cancelled requests.

### ISSUE THREAD

**Issue by mmzeeman** [zotonic/zotonic#923]
After investigation I found that mochiweb had an empty acceptor pool. This causes very low accept 
rates and timeouts.

The reason for this is that ssl handshake time is also folded into the accept time for ssl sockets. The accept can take as long as 30 seconds before timing out. This can easily cause an empty acceptor pool.

Going to quickly fix it by making the `acceptor_pool_size` seperately configurable for ssl and normal tcp, and intruduce defaults which are higher than the current default.

After that I will change mochiweb in such a way that the socket is accepted to the socket server before the ssl handshake is completed.

**Comment by mworrell** [comment]
:+1:

**Comment by mworrell** [comment]
Maybe also check the `hibernate_after` ssl option, seems to help reduce memory usage spikes.

**Comment by mmzeeman** [comment]
Looking at mochiweb now... I think a new acceptor should be started after the `ssl:transport_accept`, and not after the handshake is completed.

**Comment by mmzeeman** [comment]
Made a couple of changes to our mochiweb, and tested things with https://code.google.com/p/slowhttptest/wiki/SlowReadTest.

https://github.com/zotonic/mochiweb/commit/fbc04e494600530568b8c962df7202ca26b6620b
and
https://github.com/zotonic/mochiweb/commit/2e58adf73eca446ec039d9078858469b6c2d0253

Everything works well with these changes.
