### ISSUE TITLE
Text disappears after moving a block

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#925]
Hi!

When we move a block the text in the tinymce disappears. If we save and refresh the text is back.

**Comment by mworrell** [comment]
I used to have a workaround for that in the admin: on drag start, unload all mce instances, and on drag stop re-instantiate them.

**Comment by DorienD** [comment]
Is that something we should implement or is that something that is supposed to be standard in Zotonic?

**Comment by mworrell** [comment]
It should be part of the admin javascript.  It your problem in the admin or in admin-templates re-used on the front-end?

**Comment by DorienD** [comment]
In the admin

**Comment by DorienD** [comment]
Any thoughts on this?

**Comment by mworrell** [comment]
Yes, but has to be tested, is on my todo.

**Comment by ArthurClemens** [comment]
Working on it.
