### ISSUE TITLE
TinyMCE: Empty popup after clicking insert-link-button

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#926]
Hi!

If we insert a link in the tinymce editor and click on ok we get a empty screen. Screenshot attached.

![screen shot 2015-03-13 at 16 59 54](https://cloud.githubusercontent.com/assets/5102362/6642098/6c6fd7e0-c9a2-11e4-9fe0-88774027dac1.png)

**Comment by DorienD** [comment]
Any thoughts on this one :)

**Comment by mworrell** [comment]
Still a problem?

Looks like a javascript issue to me?

**Comment by DorienD** [comment]
Hmmm i've tried this again on the staging env but it is not repeating itself anymore. When i add a url now it does not give a blank popup. Guess we can close this one.

**Comment by mworrell** [comment]
Thanks for testing!

**Comment by DorienD** [comment]
Hi!

It is still happening, i have found another case. When you add a hyperlink without http the empty box shows again. When you add a url with http the empty box doesn't show.

~ Dorien

**Comment by LinoyMK** [comment]
same issue exists

**Comment by mworrell** [comment]
Any Javascript errors in the browser's console logs?

**Comment by LinoyMK** [comment]
thanks, I fixed this issue.
In my case i used bootstrap css in my page that overwrite the tinymce label width.

**Comment by mworrell** [comment]
Hi @LinoyMK, can you share the css rule?  Might help others as well.

(Interesting that a label css rule can render the popup empty.)

**Comment by LinoyMK** [comment]
This is the css of bootstrap for label
label {
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
  font-weight: bold;
}
here the max-width is added as 100%, i overwrite that to none like below

/* Tiny MCE popup fix*/
.mce-reset label {
  max-width: none !important;
}

**Comment by mworrell** [comment]
Thank you @LinoyMK!

**Comment by mworrell** [comment]
Closing, as this has been resolved.
