### ISSUE TITLE
Date range time

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#927]
Hi!

If I only want to fill in a date i also get 00:00 for free. But this makes it pretty hard to make ifs in the templates when a user only wants to insert a date but no time.

**Comment by mworrell** [comment]
I am not sure what you mean with "insert a date"?

Who is entering the data?
Which templates are you using?
Where/what are you displaying?

**Comment by DorienD** [comment]
In the admin on a page i'm adding a date range. 

I want to display a date but only a time when a time is specified. Now i get a 00:00 date for free when i only select a day with the calendar.

**Comment by mworrell** [comment]
You can check for the `is_all_day` flag.
Which you need to use anyway because of timezones :)

Something like this (also displaying less if the start date equals to the end date):

```
{% if id.date_is_all_day %}
	{% if id.date_start[1] == id.date_end[1] %}
		{{ id.date_start|date:_"l, N d, Y":id.date_is_all_day }}
	{% else %}
		{{ [id.date_start, id.date_end ]|date_range:[_"l, N d, Y", " – ", ""]:id.date_is_all_day }}
	{% endif %}
{% else %}
	{{ [id.date_start, id.date_end ]|date_range:[_"l, N d, Y f A", " – ", _"f A"] }} {{ id.date_start|date:"T" }}
{% endif %}
```

**Comment by DorienD** [comment]
So the user always has to define that when they only want a date the all day has to be checked?

**Comment by mworrell** [comment]
That is the idea, because then the date range is also "on the day", and independent from the timezone.

**Comment by mworrell** [comment]
Of course, if you make a simple entry form then you can also add a hidden input for the 'is_all_day' flag. This is also useful when entering birthdays.

**Comment by DorienD** [comment]
But then if someone would create an event on the website, and we would add the all day in a hidden field they would not be able to add a time. Maybe the best solution is to add a admin template for events and add a date input and time input.

**Comment by mworrell** [comment]
I mostly re-use (parts of) the admin date component `_admin_edit_content_date_range.tpl`

Maybe we should split the fields of that on in its own template for easier re-use?

@arjan

**Comment by DorienD** [comment]
I would love a date and time field apart from each other so that if a visitor wants to add an event they can easily fill in a time or not.

**Comment by mworrell** [comment]
They are apart, aren't they?

**Comment by mworrell** [comment]
I think this has been solved?  Closing for now.
