### ISSUE TITLE
Some client js files not found

### ISSUE THREAD

**Issue by hummermania** [zotonic/zotonic#928]
I see continuously messages in admin panel System->Journal and in logfiles:

Site Administrator @ 15 Мар 2015, 13:27
warning — z_lib_include:198
lib file not found: js/modules/z.live.js

Site Administrator @ 15 Мар 2015, 13:27
warning — z_lib_include:198
lib file not found: js/pubzub.js

Site Administrator @ 15 Мар 2015, 13:27
warning — z_lib_include:198
lib file not found: js/qlobber.js

Somewhere sets incorrect path?

Zotonic was installed from Git instruction and then checkout to "release-0.12.x"

**Comment by mmzeeman** [comment]
Try enabling mod_mqtt (via system -> modules).

**Comment by hummermania** [comment]
It's work - thanks! Mybe needed to add some check (enable/disable module) in page render that it doesn't include <script> tag on page?

**Comment by mworrell** [comment]
That might be a good debug/development option, indeed.
Will check this whilst I am working on some template related things anyway.

Closing this issue for now.
