### ISSUE TITLE
setting initial admin password does not work

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#93]
_From http://code.google.com/p/zotonic/issues/detail?id=88_

<b>What steps will reproduce the problem?</b>
1. Change the admin password in the Zotonic Config:
    {adminpassword, &quot;test&quot;},

<b>What is the expected output? What do you see instead?</b>
   Should be able to login using 'test' as the password, however still 
have to use 'admin'.

<b>What version of the product are you using? On what operating system?</b>

   Using HG Tip

**Comment by paucus** [comment]
I installed the latest version a couple of days ago, and cannot find the password file and it does not take an empty pwd either... I cannot log in to the sample site. Using the Docker version.

**Comment by mworrell** [comment]
@paucus on the docker version, check the `/etc/zotonic/` directory for configurations.  You can also see the zotonic_status password from the command line with:

```Erlang
z_config:get(password).
```

**Comment by paucus** [comment]
Thank you very much! 

I managed to find the password, adjusting my mental model of what is kept where… 
I created the sample blog site, following the instructions, but got an error:

21:58:54.513 [info] Zotonic started
21:58:54.513 [info] ===============
21:58:54.513 [info] Config files used:
21:58:54.513 [info] - /root/.zotonic/1/erlang.config
21:58:54.513 [info] - /root/.zotonic/1/zotonic.config
21:58:54.513 [info] 
21:58:54.513 [info] Web server listening on IPv4 any:8000, SSL any::8443
21:58:54.513 [info] Web server listening on IPv6 ::8000, SSL ::8443
21:58:54.513 [info] 
21:59:54.263 [info] PageId without page session (session_id undefined)
21:59:55.147 [info] PageId without page session (session_id undefined)
Recompile: /opt/zotonic/user/sites/mrcblog/SITE
/opt/zotonic/user/sites/mrcblog/SITE.erl:19: syntax error before: '.'
/opt/zotonic/user/sites/mrcblog/SITE.erl:21: no module definition
Recompile: /opt/zotonic/user/sites/mrcblog/mrcblog

I’m using the wizardly_mclean Docker image.

In the instructions I suggest expanding the description of how to use the Docker image, keeping it separate from the instructions for using the system installed directly on one’s computer, and mentioning (on Mac) the useful Kitematic app, and how it lets you easily map the Docker directories holding sites and modules to your own folders on the Mac, where you can edit the files easily. The Docker images don’t even have an editor, and users not yet experts in Docker, these little issues add a lot of frustration and time to resolve them. I was getting confused, for instance, in what goes in a terminal session on my Mac vs the terminal session running on the Docker image, which you can open via Kitematic.  My ignorance, but I’m sure others will run up against the same issues. 

Now to see how to fix this, as the blog won’t run properly…

Thanks again!

**Comment by mworrell** [comment]
I am a bit surprised that the name of the site module is `SITE` (capitals).
It should be something with lower case, like the name of your site (mrcblog)

How did you make the site?

**Comment by ddeboer** [comment]
It looks like the `SITE.erl` skeleton has been copied instead of used as a template and filled in. My guess is that your `mrcblog/SITE.erl` still has `-module(%%SITE%%).` in it.

Did you use [addsite](http://docs.zotonic.com/en/latest/ref/cli/cli-addsite.html)?
