### ISSUE TITLE
Adding blocks 

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#931]
Hi!

When we add our own block we have to restart zotonic in order to see them in the admin. Is there a way we can add our own blocks without restarting zotonic?

**Comment by mworrell** [comment]
You mean, you added some templates?  Or you added the observe function to add the blocks.

For the templates you can reindex the modules.
For the observe function, just stop/start the module containing the function (which als triggers a template reindex).

**Comment by DorienD** [comment]
Adding the blocks in the .erl file

**Comment by mworrell** [comment]
Restarting the module (if the observe is new) should show the newly added blocks.
The will also re-index the templates, so that any new block-templates are found.
