### ISSUE TITLE
zotonic compilefile does not work for user files

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#935]
`$ zotonic compilefile /path/to/sites/my/file.erl` throws:

```
/path/to/sites/my/file.erl is not under the Zotonic basedir.
```

This is even the case when i configure `/path/to/sites` to be the `user_sites_dir` in my Zotonic configuration. Why is this? Would it be possible to allow `compilefile` to compile files in the user site and module directories, too?

**Comment by mmzeeman** [comment]
For another use case I'm considering splitting compilation into two steps. One zotonic the other the user code with the possibility to place user beam files into `user_ebin_dir`. This would allow me to deploy pre-compiled beams.

**Comment by feng19** [comment]
can the file structure like this:
user
-mod_xxx/xxx(site)
--include
---some_hrl_file.hrl
--src
---controllers
----other_erl_file.erl
---support
----other_erl_file.erl
---support
----other_erl_file.erl
---mod_xxx.erl/xxx(site).erl
--ebin
---mod_xxx.beam/xxx(site).beam
--priv
---lib
----js
----images
----css
---translations
---dispatch
--templates

**Comment by mworrell** [comment]
@feng19 Actually that might be part of what we call the *OTP-ifciation* of Zotonic. The goal of that project is to make Zotonic completely compatible with the OTP structure (and releases).

One of the ideas is to move all modules into the apps and deps, and move templates/css/js into the priv folder of those apps.

**Comment by feng19** [comment]
@mworrell thanks,I am ready to make a lib to help me deploy pre-compiled beams recently,now I went to think about it again

**Comment by mmzeeman** [comment]
What I'm currently thinking about is simply split the compilation into two stages.

1. zotonic
2. user modules and sites

With the addition of being able to configure `user_ebin_dir` as location of the user beams. With as default `$ZOTONIC/ebin`. Or should I make it three stages?

**Comment by mworrell** [comment]
As we are now using rebar3 and OTP structure we will be removing separate "compilefile" commands.
