### ISSUE TITLE
Facebook login title change request

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#937]
Hi!

Can the title on the facebook login button be changed to Log in with Facebook.

Thanks!

**Comment by ArthurClemens** [comment]
The template has two options: "Connect with Facebook" and "Login with Facebook". Perhaps this is not a useful distinction?

@mworrell ?

**Comment by mworrell** [comment]
The "Connect with ..." option is used if you are already logged in and want to add a Facebook connection. So it is quite a distinction.

**Comment by ArthurClemens** [comment]
ah ok.

Wording: on https://developers.facebook.com/docs/apps/review/branding Facebook gives the example "Log in with Facebook" too. So "Login" becomes "Log in".

**Comment by mworrell** [comment]
Ok - maybe also check for more occurrences of "log in" as a verb (vs the noun "login").

**Comment by ArthurClemens** [comment]
@DorienD is this the wording change you suggested?

**Comment by DorienD** [comment]
Jep :)

**Comment by ArthurClemens** [comment]
No translation files exist yet. I forgot how to generate those (not documented?).

**Comment by mworrell** [comment]
I think I have to document that process - though I was also thinking of combining all (core) translations into a single file – might be easier for translating.
