### ISSUE TITLE
{% overrules %} tag doesn't play nice with cattemplates

### ISSUE THREAD

**Issue by sjorsrijsdam** [zotonic/zotonic#938]
In most of our sites we include a module with default templates and dispatch rules.
The site is supposed to overrule some templates from the module but when do that Zotonic throws an error that it cannot find `page.tpl`

The setup is similar to that described below.

**In the module we have**

*`page.person.tpl`*
```twig
{% extends "page.tpl" %}

{% block content %}
    <div class="person">
        {% block personDetails %}
            Name: Sjors
        {% endblock %}
    </div>
{% endblock %}
```

*`page.tpl`*
```twig
<html>
    <body>{% block content %}{% endblock %}</body>
</html>
```

**In the site we have**
*`page.person.tpl`*
```twig
{% overrules %}

{% block personDetails %}
    Name: Sjors Rijsdam
{% endblock %}
```

**Comment by mworrell** [comment]
Indeed, I can reproduce the problem,

It seems that the `{% overrules %}` in de `page.person.tpl` is looking for some `page.tpl`, which it (somehow) can't find.  It should be looking for `page.person.tpl`.

**Comment by mworrell** [comment]
@sjorsrijsdam I pushed a fix to the 0.12 branch, can you check if this solves your problem?
If so then I will merge into master as well.

**Comment by sjorsrijsdam** [comment]
Yes, on the release-0.12.x branch the bug is no longer present.
Thanks!

**Comment by mworrell** [comment]
Thanks for testing - I will merge it into the master (and the acl branch)

**Comment by mworrell** [comment]
Fix had been merged in the branches:

  * master
  * acl-content-groups
  * 0.12
  * 0.11
