### ISSUE TITLE
OAuth2 server support

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#940]
What would be the best way to add OAuth2 server support to Zotonic? 

I needed this primarily for the [authorization code grant](https://tools.ietf.org/html/rfc6749#section-4.1), so I started work on a [mod_oauth2](https://github.com/driebit/mod_oauth2). I decided against adding OAuth2 to the current mod_oauth, as the two OAuth versions differ enough to create a mess.

Then there is https://github.com/kivra/oauth2, which I’d prefer to use as it’s a rather complete, framework-agnostic library. However, I saw no easy way to use their [oauth2_backend.erl](https://github.com/kivra/oauth2/blob/master/src/oauth2_backend.erl) behaviour in Zotonic, as checking the database for tokens etc. would require a `Context` argument (which the oauth2 lib knows nothing about).

**Comment by mworrell** [comment]
Having a quick look it seems to me that we could use the `appctx()` in the oauth2 library?

**Comment by mworrell** [comment]
I agree to separate oauth and oauth2 - they are quite separate indeed.

**Comment by ddeboer** [comment]
Ah, must have missed `appctx()`, thanks. I’ll have a go at rewriting what I have now at [driebit/mod_oauth2] to use the kivra/oauth2 lib. If there are others who need OAuth2 server support, feel free to help. :wink:

**Comment by mworrell** [comment]
In master we are removing the OAuth1.1 support and moving to OAuth2.0 (the defacto standard these days)
