### ISSUE TITLE
mod_comment: comments per user

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#943]
We like to have an enhancement to the comment model to be able to display a list of comments created by a user.
Something like
{% with m.comment.creator[id] as comments %}

**Comment by mworrell** [comment]
Is a search model better? Then you also have paging etc.

```
{% for id in m.search.paged[{comments_by_user user_id=...}] %}
   ...
{% endfor %}
```

**Comment by fredpook** [comment]
Yes that would we fine.

**Comment by mworrell** [comment]
For visibility we might want to add a filter `is_visible_comment` ...

**Comment by ddeboer** [comment]
@fredpook Is this still relevant? I guess at Driebit we’re moving towards mod_ginger_remark.

**Comment by fredpook** [comment]
no can close
