### ISSUE TITLE
mqtt/pubzub: make the ~pagesession/session retain the last message

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#951]
The topic `~pagesession/session` on the page should retain the last page status, so that any subscribe will receive that status.

This makes initialization of listeners easier, especially when the page pid or session changes and re-subscription to server topics is needed.

**Comment by mmzeeman** [comment]
Nice one, where do you want to retain the message? Something localstorage based?

As you probably know, retained messages are currently not supported in our server based pub/sub broker.

**Comment by mworrell** [comment]
I think we should save the value in some Javascript array, next to the topic tree. We only need to retain the value during the life of the page session.

**Comment by mworrell** [comment]
In master we moved to Cotonic.

Cotonic can store messages.
