### ISSUE TITLE
Pager issues

### ISSUE THREAD

**Issue by arjan** [zotonic/zotonic#952]
The paging behaviour sometimes shows the same page before and after the dots, e.g. when you have 5 pages:
![image](https://cloud.githubusercontent.com/assets/24722/7611985/2c1d8a00-f988-11e4-925c-5927fb0a5e5a.png)

**Comment by mworrell** [comment]
Bootstrap 3 ?

**Comment by arjan** [comment]
Yes

**Comment by arjan** [comment]
maybe it is project specific, I've assigned it to myself :)

**Comment by mworrell** [comment]
The ` 5 ... 5` is something that is in there al long time already.

**Comment by arjan** [comment]
Yes, and I intend to fix it ;)

**Comment by ArthurClemens** [comment]
How to reproduce this?

**Comment by mworrell** [comment]
We need more logical calculation of the page numbers to be shown. It is messy right now.

**Comment by ArthurClemens** [comment]
e0172eadad85b985bd9105843736b255c2f818a0
