### ISSUE TITLE
svc_needauth should not look at session

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#963]
Services can set `svc_needauth(true)` to declare that clients need to be authorized to access them. However, [by default](https://github.com/zotonic/zotonic/blob/master/modules/mod_base/controllers/controller_api.erl#L95) `controller_api` looks at the session, which yields unexpected results in the context of REST(ish) APIs that should be stateless: requests are considered authorized even if no Authorization header is set.

So let’s either:
- remove the check on session and let OAuth(2) listeners do the authentication
- come up with a way to define a specific authentication scheme to be used (e.g., `session`, `oauth`, `oauth2`).

**Comment by arjan** [comment]
Having session support is quite handy when a javascript hosted on the same domain wants to call some service API.

However I agree that the check could be made more modular. In line with https://github.com/arjan/mod_service_auth_basic we could make a `mod_service_auth_session` which provides session authorization.

What do you think @mworrell?

**Comment by ddeboer** [comment]
Agreed, we should also support the same-domain JS use-case. So a separate `auth_session` module (that can be turned off for RESTish API's) sounds like a good solution.

**Comment by mworrell** [comment]
I master we removed the services.

Closing issue.
