### ISSUE TITLE
Add CLI command for restarting site

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#964]
In some cases (such as when observers are changed) it is necessary to restart the site. Especially on production systems, it would be nice if the `zotonic` command provided a way to do this.

/cc @CyBeRoni

**Comment by CyBeRoni** [comment]
start/stop of course, not 'restart'.

**Comment by ddeboer** [comment]
Yes, or all three of them. :)

**Comment by mmzeeman** [comment]
You have a similar problem when one of the modules has different observers. In that case you don't have to restart the whole site, restarting the module is enough.

I'm looking into a way of managing module and site observes this automatically. It could be checked after a compile.

**Comment by mworrell** [comment]
Wondering if we can get _sys_ or _code_ provide us with upgrade messages for any module in the system,.

**Comment by mworrell** [comment]
Asking it on the Erlang Questions mailing list... this kind of system messages are a bit hairy.

**Comment by mmzeeman** [comment]
After compiling the dispatch rules of the sites are flushed. That might also be a good spot to "flush" the observe's by sending a message to all processes running below the site process.

**Comment by mworrell** [comment]
That flush is only done after a `z:m()`, not after a `z:compile()`.  I try not to use the flush on hot systems as it also resets all templates and gives spikes on the server.

**Comment by mworrell** [comment]
The above commits will trace module loads and re-start any module with changed exports.

**Comment by mworrell** [comment]
A zotonic command to start/stop modules can still be useful, though for site maintenance now.

**Comment by mworrell** [comment]
The automatic observe-reload also needs a check on the schema version.

**Comment by mworrell** [comment]
See also commit 5867b86

This adds better support for *fswatch* and *inotify* and removes the tracer.

**Comment by CyBeRoni** [comment]
How do I start and stop a site from a script with that?

**Comment by mworrell** [comment]
I comment here with this commit because starting/stopping a module due to observers or mod_schema changes was one of the items. This can now be done automatically.

Start/stop site is another part :)

**Comment by ddeboer** [comment]
:+1:
