### ISSUE TITLE
Use translation keys instead of messages

### ISSUE THREAD

**Issue by ddeboer** [zotonic/zotonic#965]
Currently, translation files use full content strings as ids, such as ‘Are you sure you want to delete the username from’. The problem with this is that when you want to change the English sentence (to, e.g., ‘Are you _really_ sure you want to delete the _user’s_ name from’) you need to change that msgid in all translation files. 

So in my opinion, it’s better to use translation keys (e.g. ‘confirmation.user_deletion‘) instead.

Keep in mind that keys should describe their purpose (label.question) not their location (question_form.top_part.question_text_input_label) to be independent from page layout changes. Perhaps prefixing module-specific messages with the module name makes sense, though.

**Comment by arjan** [comment]
You can also just create a `en.po` translation strings file, which is how I solve that issue currently.

**Comment by mworrell** [comment]
You see that other software (Apple comes to mind) also uses labels, the nice thing is that they can be defined very specifically, especially for small wordt like `of`, which is context sensitive in its translation.

I like this request in that it solves this ambiguity.

/cc @michielklonhammer @mmzeeman @ArthurClemens

**Comment by ArthurClemens** [comment]
Good addition

**Comment by mworrell** [comment]
I propose to stick with the normal  .po files and add special sentences/labels for strings that are ambiguous, using the `en.po` file @arjan suggested.

Sticking to the normal po/pot flow ensures that the we can use automated tools and sites like crowdin.
