### ISSUE TITLE
mod_search: multiple hasobject's don't work

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#968]
1 line for instance 
`hasobject=[394,works_for]`
does work but
`hasobject=[394,works_for]`
`hasobject=[2448,works_for]`
doesn't work

the documentation says: "Specifying this multiple times does an “or” of the conditions."
Am I using the right syntax?

**Comment by arjan** [comment]
what do you mean with "does not work"? What is the behaviour you're seeing?

**Comment by fredpook** [comment]
I am getting less or no results. It looks like "and" logic.

**Comment by mworrell** [comment]
Looking at the code it is indeed an *AND*.  It makes multiple joins, which are grouped with `and`' in the `where` clause.

**Comment by fredpook** [comment]
The use cases for multiple hasobject queries are usually OR 
Can we have a a new argument like or_hasobject ?

**Comment by mworrell** [comment]
An *OR* is always quite interesting in complexity (you need grouping etc). Isn't a match on object-ids better? Then you also get an order on relevance.

What is your use case?

**Comment by fredpook** [comment]
The use case is a query of all persons working for the 3 different daughter companies of the client.
Or a query of all articles that have one or both keywords of 2 specific keywords.

**Comment by mworrell** [comment]
Which order do you want those results?

One of the issues is that with a SQL join you will need a group-by to remove duplicates, which results in either more than one column in the select or no ordering (other than by id).

**Comment by mworrell** [comment]
We might want to add a special query for this ... as I think that the *group by* will give problems with the generic query builder. And resulting rows with the templates, which in general only expect a single id per returned row.

**Comment by fredpook** [comment]
A match would do if it accepts some filtering on object ids and predicates. The order of the results can be the ranking

**Comment by mworrell** [comment]
The current matching code and pivot does not distinguish any predicates. So you can only match on an overlap of object ids (and/or object categories).

We could change this though, by adding extra predicate+object 'words' to the related pivot.

**Comment by fredpook** [comment]
Adding predicate+object to the match pivot could be very usefull in general. It could be used to make the context of a rsc more "meaningful"

**Comment by mworrell** [comment]
So then we could have a query like:

`{match_pred predicate=... predicate=... id=...}`

Which would match against certain object-predicates of a resource *id*.
Ordering would be on best match first.

**Comment by fredpook** [comment]
Yes, except matching against a given id should be optional. If no id given than match with the given object ids.

**Comment by mworrell** [comment]
Then we would have something like:

`{match_objects_predicate hasobject=[394,works_for] ... }`

as an alternative where you define the objects, with their predicates.

**Comment by fredpook** [comment]
Yes, please :)

**Comment by mworrell** [comment]
I added an extra search term "hasanyobject".
The help is:

**hasanyobject**

  Like hasobject, but allows to define an "or" operation on the edge.
  You can define multiple combinations of predicates and objects, any
  resource having such an outgoing edge will be matched.

  ``hasanyobject=1,2,3``
  ``hasanyobject=[1,author],2,3``
  ``hasanyobject=[*,author],2,3``

  The term ``[*,author],2,3`` selects any resource with an *author*,
  or a connection to the ids 2 or 3 (with any predicate).
