### ISSUE TITLE
Upgrade epgsql app to 3.x

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#969]
We are using 2.x, and 3.x is out.
@alvaropag is already using it, and he saw no problems.

**Comment by mworrell** [comment]
@arjan do you know if this might give problems?

**Comment by mworrell** [comment]
@mmzeeman found #917

**Comment by frkarl** [comment]
They have renamed module names from pgsql to epgsql so that need to be changed.

**Comment by frkarl** [comment]
https://github.com/zotonic/zotonic/pull/987

**Comment by ddeboer** [comment]
Closing as we’re now at 3.0, thanks @frkarl!
