### ISSUE TITLE
Upcoming does not work in query page

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#970]
Hi!

I've made a query page with the following rules:
`upcoming
cat=deadline
sort=rsc.pivot_date_start`

And this gives us this result:
http://filmfonds.ginger-staging.driebit.net/nl/page/2546/indiendata

But! As you can see the first date is not in the future. On another page i use a template search query 

`{% with m.search[{query cat="deadline" upcoming hasobject=id sort="-rsc.pivot_date_start"}] as result %}`

And here the upcoming does work:

http://filmfonds.ginger-staging.driebit.net/nl/page/2600/realisering-minoritaire-coproductie-met-vaf#indiendata

I think this is a bug? Staging env is on 12.4

**Comment by mworrell** [comment]
That is an issue in the syntax of the query, I have relaxed that in ce1f496

Before my change, you had to specify *key=value* in the text.
In your case, replace the `upcoming` with `upcoming=1`
