### ISSUE TITLE
Adding category adds multiple times

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#971]
Hi!

I'm getting double categories. When i add a subcategory 'Collectiegroep' in 'Collectie' zotonic also adds a 'Collectiegroep' category within 'Zoekopdracht'

![screen shot 2015-06-23 at 17 31 27](https://cloud.githubusercontent.com/assets/5102362/8310101/4a425fea-19ce-11e5-86c3-cc5c16c60863.png)

~ Dorien

**Comment by mworrell** [comment]
Which version are you using?

**Comment by DorienD** [comment]
ACL branch

**Comment by mworrell** [comment]
Might be an issue with your machine being slow, you are using your local virtual machine?

**Comment by DorienD** [comment]
Hmmm, I'm using a vagrant that has a v.memory = 1536. Think that should be enough? And also on our test environment this happens (also running acl branch)

**Comment by mworrell** [comment]
I will check - we are looking at the hierarchy editor anyway.

**Comment by DorienD** [comment]
Oeh this also happens on our staging env which is on 12.4 tag

**Comment by mworrell** [comment]
Interesting, didn't see it here previously

**Comment by mworrell** [comment]
I did reproduce it.
