### ISSUE TITLE
"Any category" filter finds nothing in resource selection dialog 

### ISSUE THREAD

**Issue by Dirklectisch** [zotonic/zotonic#976]
When I try to add a connection to a resource from the admin panel and select "any category" in the dropdown box, I won't get any results no matter what the search term.

One way to reproduce is to create a Zotonic site based on the default blog skeleton. Go to any resource and try to add the "Zotonic's Typography" article as a related resource. The resource will only appear if you select the "Text" as the category. I expected it to appear also when selecting either "Any category" or "Valid for: Relation".

**Comment by mworrell** [comment]
The lazy loader in this dialog keeps loading new results.
Checking this.

**Comment by mworrell** [comment]
Fixed, this was a max-height which excluded the lazy-loader, so that the lazy-loader stayed in view while all possible pages were loaded.

Also fixed on the 0.12.x branch.
