### ISSUE TITLE
Build errors on Erlang 18.0 – dict() type changed.

### ISSUE THREAD

**Issue by frkarl** [zotonic/zotonic#979]
Been trying to build zotonic on erlang 18 but getting errors

The version of proper and poolboy an probably other deps are using dict() set() queue() 
that where removed with erlang 18.

**Comment by mworrell** [comment]
Hi Fredrik,

We didn’t get around testing in 18.0 yet.
There might be some other issues as well.

Thanks for testing though, we need to investigate which versions of which deps to take.

Cheers, Marc
