### ISSUE TITLE
Change title insert media item

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#984]
Hi! 

Would it be possible to remove the zotonic in 'Plaats Zotonic mediabestand'?

![screen shot 2015-07-09 at 17 51 15](https://cloud.githubusercontent.com/assets/5102362/8599873/1d89a9a8-2663-11e5-9a52-f62f48df7722.png)

~ Dorien

**Comment by frkarl** [comment]
The path to the file where the text are located is:
modules/mod_editor_tinymce/lib/js/tinymce-4.1.6/tinymce/plugins/zmedia/langs/nl.js

You could copy that module and change the text.

**Comment by mworrell** [comment]
Closing this, as you can overrule it if you want to.
