### ISSUE TITLE
Question mark after surname

### ISSUE THREAD

**Issue by DorienD** [zotonic/zotonic#985]
Hi!

The question mark is hiding behind the text input. 

![screen shot 2015-07-09 at 17 59 32](https://cloud.githubusercontent.com/assets/5102362/8600083/4e843fc2-2664-11e5-8ff7-d70a7799b9a6.png)

**Comment by ArthurClemens** [comment]
That is part of my unfinished work on the admin blocks.

**Comment by mworrell** [comment]
I just mark this for the 1.0, so we have it filed for later checks.

**Comment by mworrell** [comment]
:+1:
