### ISSUE TITLE
Modal dialog window width

### ISSUE THREAD

**Issue by onnet** [zotonic/zotonic#986]
Hi!

Trying to change width of dialog window but seems it is impossible with current z.dialog.js:
action={ dialog_open title=_"Details" template="mytest.tpl" width=234 }

If I am changing these lines:
https://github.com/zotonic/zotonic/blob/master/modules/mod_base/lib/js/modules/z.dialog.js#L100-L107
to something like this everything works fine:

            if (width > 0) {
                $modalDialog.css({
                    width: width
                });
            }

Could you please advise if there is a bug or I am trying to control dialog width in wrong manner

Regards,
Kirill

**Comment by ArthurClemens** [comment]
Your assertion was correct. This is fixed now. However in order to not have a too wide dialog on small screens it is better to set the width in css, where you have control over breakpoints.

**Comment by ArthurClemens** [comment]
The previous code used polling to reposition the modal every 250ms. The idea was that expanding content would grow the dialog, so the position needed to be updated.

But when the dialog is kept centered vertically, longer content would lead to a jump upward

I believe that the new behavior is preferable: with expanding content the dialog keeps the current position, while the contents makes it grow vertically.

**Comment by mworrell** [comment]
Just for documentations: use the option `dialogClass` to add a class to the opened dialog.
