### ISSUE TITLE
mod_search: unknown query term error crashes admin and page

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#988]
In mod_search/support/search_query.erl an error is thrown for term mismatches but since the admin will crash on a mismatched term the user has no chance to correct it.
Can we just log the error and skip the mismatch?

**Comment by mworrell** [comment]
I agree that if such an error is coming from user input then it is better to just generate an error (or warning) and return an empty result (as the non-existing query term would return an empty result set anyway).

**Comment by mworrell** [comment]
When does this error occur?  On saving a query (search collection) or when showing a query result?

**Comment by fredpook** [comment]
When showing a query result page. The query term text is generated by the anymeta import

**Comment by mworrell** [comment]
Which options do you use for `m_rsc:insert` ?
As normally the `preflight_check` would throw an error if you try to insert an invalid search.

**Comment by fredpook** [comment]
{ok, RscId} = m_rsc_update:update(RscId, Fields, [{escape_texts, false}, is_import], Context);

**Comment by mworrell** [comment]
Could you test with the above changes (on 0.13.x)?

**Comment by fredpook** [comment]
Tested and fixes the problem in zotonic.. Query pages with an invalid query are now displayed (with empty list of course) and the admin is displayed so the user can correct the mistake.
However the import from anymeta now breaks with an error in the preflight_check.
Shall I make an issue for this in mod_import_anymeta so we can close this one?

**Comment by mworrell** [comment]
Yes, please do make an issue in mod_import_anymeta. Then we can close this and proceed to releasing 0.13.1
