### ISSUE TITLE
controller_static_pages: hide all files and directories starting with a '.'

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#991]
Now we can expose files and/or directories that the user might think are hidden.
Think of `.git` and `.htaccess` files.

**Comment by mworrell** [comment]
In the controller we also calculate multiple encodings, but it is not handled.
Will remove this caching and encodings.

/cc @arjan

**Comment by mworrell** [comment]
If we need gzip encoding we better use the newer `z_file_entry`

**Comment by mworrell** [comment]
Also cc @mmzeeman (didn't you use this controller?)

**Comment by mmzeeman** [comment]
No, I use controller lib from a dispatch rule to. But Thanks for the warming.
