### ISSUE TITLE
logging: normalize log notifications and add support for Kibana

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#992]
I need to add support for log (of various events/sources) storage in Elastic Search for analysis with Kibana.

For this I think that it is useful to normalize some log events:
1. A standard log event: `#zlog{type, properties)` 
2. Change internal logging to this format
3. Add some extra log events (like access log)

The events are handled by one or more log processors (aka sinks), depending on the enabled modules.

For the Elastic Search logging, the events will be buffered and written in batches to an index like `zotonic-log-<sitename>`   Every log event's _type_ will be mapped to a Elastic Search _type_.

We might want to use an ES index per period, this will be handled by some configuration.
The name of the ES index will be postfixed: `zotonic-log-<sitename>-201507` 
I propose a default period of a year.

Another configuration will decide which log _types_ are written to Elastic Search.

/cc @arjan @mmzeeman @fredpook

**Comment by mworrell** [comment]
Also cc @kaos

**Comment by arjan** [comment]
Makes sense to do it like this. I would do two things:
* refactor `mod_logging` and related `z:debug`,`z:info` etc. functions to use the same log events.
* Maybe it makes sense to use `logstash` to put the logs into Elasticsearch
* I would not add too much ELK-stack specific code in Zotonic's core; let's make it an external module.

**Comment by arjan** [comment]
Also, see @ddeboer's https://github.com/driebit/mod_elasticsearch

**Comment by mworrell** [comment]
I agree with the external module.

Regarding logstash, I think exporting directly to ES is very simple and removes an extra moving part. On the other hand, the nice thing about logstash is added flexibility on filtering and selecting sinks.

**Comment by mworrell** [comment]
Regarding `mod_elasticsearch`: I was just thinking of using a bulk `POST` to the ES HTTP interface for adding the information.

**Comment by ddeboer** [comment]
Bulk POST is [available](https://github.com/tsloughter/erlastic_search/blob/master/src/erlastic_search.erl#L172) in the lib that I use in mod_elasticsearch, so we’d just have to add it to mod_elasticsearch as well. The benefit is that you can then configure your connection to ES in a standard way.

**Comment by kaos** [comment]
+1 for logging to elastic. I also agree with keeping any ELK specifics out of the core.

Don't forget about the standard event logger, though. You may have a module that use some third party module, or otherwise doesn't use the zotonic logging framework. It would be nice to get those logs captured as well.

I know I wrote a module that hooks into the event logger to send all logs to a web page, but I can't find it now. It's not hard to do, though.

**Comment by mmzeeman** [comment]
Do you want to use the notifier for the zlog notifications? 

And indeed a separate module sounds logic too. 

As you know I currently use a simple wrap disk_log module to log events. It works very nicely in practice and doesn't require additional configuration. You have to know beforehand what you what signals you want to record however. It sounds like this isn't clear in your use-case.

**Comment by mworrell** [comment]
I was thinking about using the standard `z_notifier`, though I will check if we can use `lager` or `error_logger'.  (Less and more standard is better)

The main purpose I have is logging high level events, which can be analyzed later. Think of actions, like *article created*. I am not aiming at channeling the debug log (or something similar noisy) to ELK.

**Comment by mworrell** [comment]
About using disk_log - that could be a great replacement of the current logger module, which logs in the database.

**Comment by mmzeeman** [comment]
Aha, I currently use notifications, as most of these high level events where are already notifications. Things like session-started, stopped, url changes, chat message sent, arrived, etc.

I just pick up these notifications in a logging module which writes to a standard erlang disk_log. That way the logging itself is outside the main logic. This proved to be very handy when a client requested us to sent the events to their own google analytics tracker.

**Comment by mworrell** [comment]
Yes indeed, those are already available and easy to hook into. Just as how it should be. En event logging module can even hook into the *z_notifier:first/2* notifications by having a high pro and returning `undefined`.

I feel the most for using the `z_notifier` for some general (to be logged) notifications. As `lager` and/or `error_logger` are more like fire-hoses for low level debugging and errors.

**Comment by fredpook** [comment]
Logging in ES would be great. Driebit's Ginger websites needs logging of insert/update/delete events on rsc's  so we can produce daily digest emails for rsc owners. Pulling these from ES sounds like a good idea to me.

**Comment by mmzeeman** [comment]
And sometimes you need to do a little bit of processing before logging. Having the context is handy in those situations.

**Comment by mworrell** [comment]
Still open: #zlog{} messages for things like access logs.

**Comment by mworrell** [comment]
For access logs we might want to log:

 * Timestamp
 * Request URI
 * HTTP status code
 * User Id
 * Page Id
 * Dispatch rule
 * Controller
 * Time taken
 * Bytes sent
 * User agent class
 * User agent string
 * Language
 * Timezone
 * Remote IP
 * Persistent id (from the cookie)
 * Session id (from the cookie)

Anything else?

Maybe also good to log all web socket postbacks as well?

**Comment by mmzeeman** [comment]
I think you are missing the site name.


Marc Worrell schreef op 2015-08-18 16:20:

**Comment by mworrell** [comment]
Currently the `mod_logging_elastic` creates an index per site:  zotonic-log-*sitename*

Within that index there are types per log-type (email, etc).

**Comment by arjan** [comment]
HTTP request method?

**Comment by mmzeeman** [comment]
And http vs https

**Comment by mworrell** [comment]
* Request method (get, post, etc)
 * Protocol (http, https, ...)
 * Protocol version (1.0, 1.1, 2)
 * Timestamp
 * Request URI
 * HTTP status code
 * User Id
 * Page Id
 * Dispatch rule
 * Controller
 * Time taken
 * Bytes sent
 * User agent class
 * User agent string
 * Language
 * Timezone
 * Remote IP
 * Persistent id (from the cookie)
 * Session id (from the cookie)
