### ISSUE TITLE
Limit maximum number of outgoing connections to a single server

### ISSUE THREAD

**Issue by mworrell** [zotonic/zotonic#993]
Currently we have no limit on the number of connections per SMTP server, only on the total amount of sending processes.

Currently we max at 30 concurrent senders.

I propose to set the max to 100 and add an additional limit of 5 per recipient domain and/or recipient SMTP server.

/cc @michielklonhammer @mmzeeman

**Comment by mworrell** [comment]
One option is to have max 100 sender processes alive at any moment, and let these sender processes only connect to their peer SMTP server iff there are less than 5 connections for that server (and/or domain).  If there are 5 or more, then there are two strategies:

 1. re-queue the message with a random timeout
 2. sleep and retry till there is an opportunity to send

I think that a combination of the two might be best: allow only 5 concurrent connections, and max 20 (?) total sending processes per domain. This will prevent that a mass mailing to one single domain can slow down the whole SMTP sending process for all other email.

**Comment by mworrell** [comment]
Also /cc @arjan

**Comment by michielklonhammer** [comment]
A bit of background here: LearningStone has a client with a poorly configured email server and spam filter. We researched this a bit and some providers don't like more than 5 concurrent connections to one domain. Most  providers probably use other methods to check if they should cut us off but in this case we're sending mail to more than 10 users at the same domain and they're blocking us. It's thanks to the great Zotonic bounce management error messages that we're seeing in the first place!

**Comment by mmzeeman** [comment]
Oops.

Btw. httpc has such a limits in place already.

**Comment by mworrell** [comment]
For now I added a simple strategy:

 * Start max 100 parallel email senders
 * Allow max 5 parallel connections per relay
 * Sender process polls every second till it gets a slot to send
 * The email server maintains a list of all workers and their relay host
