### ISSUE TITLE
Page path adds slash in front of path

### ISSUE THREAD

**Issue by fredpook** [zotonic/zotonic#995]
Since aba6f0d redirecting to the page path is possible but a slash is always added in front.
So http://foobar.com/ becomes /http://foobar.com/
and the path will become  /en/http://foobar.com

**Comment by mworrell** [comment]
The page_path can't be a complete uri, only the path fragment. The path fragment always starts with a `/`

Having said that, the ':' should have been removed during sanitization.

**Comment by fredpook** [comment]
Ok,
So the only way to have a redirect leaving the site is using the website and is_website_redirect property?
If so it will only be available for resources that have an address, like organizations. Many rsc don't have the address admin block so those can't use this for redirecting.

**Comment by mworrell** [comment]
You can use the separate (smaller) website block in those instances.

The `page_path` is the path of the resource on the site you are editing, not on another site.

**Comment by mworrell** [comment]
I made the sanitization a bit stricter in z_url.erl (z_stdlib)
